// app/modules/user_application_identity/UserApplicationIdentityConstants.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var8 = require;
    var3 = exports;
    var7 = dependencyMap;
    var _closure1_slot0 = var8;
    var _closure1_slot1 = var7;
    var1 = global;
    var6 = var1.Object;
    var5 = var6.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var5.bind(var6)(var3, var1, var4);
    var6 = {};
    var1 = '1443033465766281327';
    var6['RIOT_GAMES'] = var1;
    var1 = '1412940519742636124';
    var6['BATTLENET'] = var1;
    var1 = {};
    var4 = var6.RIOT_GAMES;
    var1['applicationId'] = var4;
    var4 = function getMigrationExperimentEnabled(arg1) {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 0;
        var2 = var2[var1];
        var1 = undefined;
        var3 = var3.bind(var1)(var2);
        var2 = var3.getIsRiotSocialSDKMigrationEnabled;
        var1 = {};
        var4 = arg1;
        var1['location'] = var4;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var1['getMigrationExperimentEnabled'] = var4;
    var4 = function useMigrationExperimentEnabled(arg1) {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 0;
        var2 = var2[var1];
        var1 = undefined;
        var3 = var3.bind(var1)(var2);
        var2 = var3.useIsRiotSocialSDKMigrationEnabled;
        var1 = {};
        var4 = arg1;
        var1['location'] = var4;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var1['useMigrationExperimentEnabled'] = var4;
    var5 = new Array(1);
    var5[0] = var1;
    var1 = {};
    var4 = var6.RIOT_GAMES;
    var1['applicationId'] = var4;
    var4 = function getMigrationExperimentEnabled(arg1) {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 0;
        var2 = var2[var1];
        var1 = undefined;
        var3 = var3.bind(var1)(var2);
        var2 = var3.getIsRiotSocialSDKMigrationEnabled;
        var1 = {};
        var4 = arg1;
        var1['location'] = var4;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var1['getMigrationExperimentEnabled'] = var4;
    var4 = function useMigrationExperimentEnabled(arg1) {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 0;
        var2 = var2[var1];
        var1 = undefined;
        var3 = var3.bind(var1)(var2);
        var2 = var3.useIsRiotSocialSDKMigrationEnabled;
        var1 = {};
        var4 = arg1;
        var1['location'] = var4;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var1['useMigrationExperimentEnabled'] = var4;
    var4 = new Array(2);
    var4[0] = var1;
    var1 = {};
    var9 = var6.BATTLENET;
    var1['applicationId'] = var9;
    var9 = function getMigrationExperimentEnabled(arg1) {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 0;
        var2 = var2[var1];
        var1 = undefined;
        var1 = var3.bind(var1)(var2);
        var3 = var1.battlenetSocialSDKMigrationExperiment;
        var2 = var3.getConfig;
        var1 = {};
        var4 = arg1;
        var1['location'] = var4;
        var1 = var2.bind(var3)(var1);
        var1 = var1.enabled;
        return var1;
    };
    var1['getMigrationExperimentEnabled'] = var9;
    var9 = function useMigrationExperimentEnabled(arg1) {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 0;
        var2 = var2[var1];
        var1 = undefined;
        var1 = var3.bind(var1)(var2);
        var3 = var1.battlenetSocialSDKMigrationExperiment;
        var2 = var3.useConfig;
        var1 = {};
        var4 = arg1;
        var1['location'] = var4;
        var1 = var2.bind(var3)(var1);
        var1 = var1.enabled;
        return var1;
    };
    var1['useMigrationExperimentEnabled'] = var9;
    var4[1] = var1;
    var _closure1_slot2 = var4;
    var1 = 1;
    var7 = var7[var1];
    var1 = undefined;
    var9 = var8.bind(var1)(var7);
    var8 = var9.fileFinishedImporting;
    var7 = 'modules/user_application_identity/UserApplicationIdentityConstants.tsx';
    var7 = var8.bind(var9)(var7);
    var3['ApplicationIdentityConnections'] = var6;
    var3['APPLICATION_IDENTITY_CONNECTIONS_ALLOWED_APPLICATIONS'] = var5;
    var3['APPLICATION_IDENTITY_CONNECTIONS_SCREEN_APPLICATIONS'] = var4;
    var2 = function getMigratedApplicationIdentityConnectionsScreenApplications(arg1) {
        var2 = arg1;
        var _closure2_slot0 = var2;
        var4 = _closure1_slot2;
        var3 = var4.filter;
        var2 = function(arg1) {
            var3 = arg1;
            var2 = var3.getMigrationExperimentEnabled;
            var1 = _closure2_slot0;
            var1 = var2.bind(var3)(var1);
            return var1;
        };
        var3 = var3.bind(var4)(var2);
        var2 = var3.map;
        var1 = function(arg1) {
            var1 = arg1;
            var1 = var1.applicationId;
            return var1;
        };
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var3['getMigratedApplicationIdentityConnectionsScreenApplications'] = var2;
    return var1;
})();