// app/modules/remixing/native/components/RemixingText.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var1 = metroImportDefault;
    var _closure1_slot1 = var1;
    var _closure1_slot2 = var6;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var7 = var6[var1];
    var4 = metroImportAll;
    var1 = undefined;
    var4 = var4.bind(var1)(var7);
    var4 = 1;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.useRemixingEditorStore;
    var _closure1_slot3 = var4;
    var4 = 2;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var7 = var4.jsx;
    var _closure1_slot4 = var7;
    var4 = var4.jsxs;
    var _closure1_slot5 = var4;
    var4 = 9;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/remixing/native/components/RemixingText.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function _default(arg1) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var1 = arg1;
            var4 = var1.id;
            var15 = var1.size;
            var _closure2_slot0 = var15;
            var18 = var1.textParams;
            var _closure2_slot1 = var18;
            var3 = var1.position;
            var _closure2_slot2 = var3;
            var9 = var1.transform;
            var7 = var1.transformMap;
            var10 = var1.shader;
            var6 = undefined;
            var _closure2_slot5 = var6;
            var _closure2_slot6 = var6;
            var2 = _closure1_slot3;
            var1 = function(arg1) {
                var1 = arg1;
                var1 = var1.editingComponent;
                return var1;
            };
            var2 = var2.bind(var6)(var1);
            var13 = _closure1_slot1;
            var12 = _closure1_slot2;
            var1 = 3;
            var1 = var12[var1];
            var5 = var13.bind(var6)(var1);
            var1 = var18.fontSize;
            var1 = var5.bind(var6)(var1);
            var5 = var1.font;
            var _closure2_slot3 = var5;
            var1 = 4;
            var1 = var12[var1];
            var1 = var13.bind(var6)(var1);
            var7 = var1.bind(var6)(var4, var7, var9);
            var9 = _closure1_slot0;
            var1 = 5;
            var1 = var12[var1];
            var12 = var9.bind(var6)(var1);
            var9 = var12.useSupportedStringLines;
            var1 = var18.lines;
            var13 = var9.bind(var12)(var4, var5, var1);
            var _closure2_slot4 = var13;
            var1 = null;
            var9 = var1 != var10;
            var14 = undefined;
            if(!var9) { _fun0001_ip = 2; continue _fun0001 }
case 3:
            var12 = _closure1_slot1;
            var16 = _closure1_slot2;
            var9 = 6;
            var9 = var16[var9];
            var9 = var12.bind(var6)(var9);
            var14 = var9[var10];
case 2:
            if(!(var1 != var5)) { _fun0001_ip = 4; continue _fun0001 }
case 5:
            var10 = new Array(0);
            _closure2_slot5 = var10;
            var12 = new Array(0);
            _closure2_slot6 = var12;
            var9 = var13.map;
            var5 = function(arg1, arg2) {
                var11 = arg2;
                var4 = _closure2_slot3;
                var2 = var4.getGlyphIDs;
                var1 = arg1;
                var2 = var2.bind(var4)(var1);
                var1 = var4.getGlyphWidths;
                var5 = var1.bind(var4)(var2);
                var4 = var5.reduce;
                var2 = function(arg1, arg2) {
                    var2 = arg1;
                    var1 = arg2;
                    var1 = var2 + var1;
                    return var1;
                };
                var1 = 0;
                var9 = var4.bind(var5)(var2, var1);
                var5 = _closure2_slot2;
                var2 = var5.x;
                var1 = _closure2_slot0;
                var1 = var1.width;
                var4 = var1 - var9;
                var1 = 0.5;
                var1 = var1 * var4;
                var8 = var2 + var1;
                var13 = _closure2_slot6;
                var12 = var13.push;
                var7 = _closure1_slot0;
                var10 = _closure1_slot2;
                var6 = 7;
                var2 = var10[var6];
                var1 = undefined;
                var18 = var7.bind(var1)(var2);
                var17 = var18.rect;
                var14 = var5.y;
                var2 = _closure2_slot1;
                var4 = var2.fontSize;
                var4 = var11 * var4;
                var14 = var14 + var4;
                var4 = 3;
                var22 = var14 + var4;
                var19 = 6;
                var21 = var9 + var19;
                var14 = var2.fontSize;
                var20 = var14 + var19;
                var23 = var8 - var4;
                var24 = var18;
                var4 = var24[var17](var23, var22, var21, var20, var19);
                var4 = var12.bind(var13)(var4);
                var4 = _closure2_slot5;
                var3 = var4.push;
                var6 = var10[var6];
                var7 = var7.bind(var1)(var6);
                var6 = var7.rect;
                var10 = var5.y;
                var5 = 1;
                var11 = var11 + var5;
                var5 = var2.fontSize;
                var5 = var11 * var5;
                var22 = var10 + var5;
                var20 = var2.fontSize;
                var24 = var7;
                var23 = var8;
                var21 = var9;
                var2 = var24[var6](var23, var22, var21, var20, var19);
                var2 = var3.bind(var4)(var2);
                return var1;
            };
            var5 = var9.bind(var13)(var5);
            var9 = _closure1_slot0;
            var5 = _closure1_slot2;
            var16 = 7;
            var5 = var5[var16];
            var19 = var9.bind(var6)(var5);
            var17 = var19.rect;
            var23 = var3.x;
            var22 = var3.y;
            var21 = var15.width;
            var20 = var15.height;
            var24 = var19;
            var13 = var24[var17](var23, var22, var21, var20, var19);
            var5 = var1 == var2;
            var3 = undefined;
            if(var5) { _fun0001_ip = 6; continue _fun0001 }
case 7:
            var3 = var2.id;
case 6:
            var2 = null;
            if(!(var3 !== var4)) { _fun0001_ip = 8; continue _fun0001 }
case 9:
            var5 = _closure1_slot5;
            var9 = _closure1_slot0;
            var17 = _closure1_slot2;
            var3 = var17[var16];
            var3 = var9.bind(var6)(var3);
            var4 = var3.Group;
            var3 = {};
            var18 = var18.color;
            var3['color'] = var18;
            var3['transform'] = var7;
            var7 = 8;
            var7 = var17[var7];
            var9 = var9.bind(var6)(var7);
            var7 = var9.centerOfRect;
            var7 = var7.bind(var9)(var13);
            var3['origin'] = var7;
            var9 = var12.map;
            var7 = function(arg1, arg2) {
                var1 = arg1;
                var5 = _closure1_slot4;
                var3 = _closure1_slot0;
                var4 = _closure1_slot2;
                var2 = 7;
                var2 = var4[var2];
                var4 = undefined;
                var2 = var3.bind(var4)(var2);
                var3 = var2.RoundedRect;
                var2 = {};
                var6 = 10;
                var2['r'] = var6;
                var6 = _closure2_slot1;
                var6 = var6.backgroundColor;
                var2['color'] = var6;
                var6 = var1.x;
                var2['x'] = var6;
                var6 = var1.y;
                var2['y'] = var6;
                var6 = var1.height;
                var2['height'] = var6;
                var1 = var1.width;
                var2['width'] = var1;
                var1 = arg2;
                var1 = var5.bind(var4)(var3, var2, var1);
                return var1;
            };
            var9 = var9.bind(var12)(var7);
            var7 = new Array(4);
            var7[0] = var9;
            var7[1] = var1;
            var9 = var1 != var14;
            if(!var9) { _fun0001_ip = 10; continue _fun0001 }
case 11:
            var13 = _closure1_slot4;
            var12 = _closure1_slot0;
            var11 = _closure1_slot2;
            var11 = var11[var16];
            var11 = var12.bind(var6)(var11);
            var12 = var11.Shader;
            var11 = {};
            var11['source'] = var14;
            var14 = {};
            var16 = var15.width;
            var14['w'] = var16;
            var15 = var15.height;
            var14['h'] = var15;
            var11['uniforms'] = var14;
            var9 = var13.bind(var6)(var12, var11);
case 10:
            var7[2] = var9;
            var9 = var10.map;
            var8 = function(arg1, arg2) {
                var6 = arg1;
                var5 = arg2;
                var4 = _closure1_slot4;
                var2 = _closure1_slot0;
                var3 = _closure1_slot2;
                var1 = 7;
                var1 = var3[var1];
                var3 = undefined;
                var1 = var2.bind(var3)(var1);
                var2 = var1.Text;
                var1 = {};
                var8 = _closure2_slot1;
                var8 = var8.color;
                var1['color'] = var8;
                var8 = _closure2_slot4;
                var8 = var8[var5];
                var1['text'] = var8;
                var7 = _closure2_slot3;
                var1['font'] = var7;
                var7 = var6.x;
                var1['x'] = var7;
                var6 = var6.y;
                var1['y'] = var6;
                var1 = var4.bind(var3)(var2, var1, var5);
                return var1;
            };
            var8 = var9.bind(var10)(var8);
            var7[3] = var8;
            var3['children'] = var7;
            var2 = var5.bind(var6)(var4, var3);
case 8:
            return var2;
case 4:
            return var1;
        }
    };
    var3['default'] = var2;
    return var1;
})();