// app/design/components/Sheet/native/ActionSheetPresenter.native.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var7 = metroImportDefault;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var7;
    var _closure1_slot2 = var6;
    var1 = global;
    var9 = var1.Object;
    var8 = var9.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var8.bind(var9)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var7.bind(var1)(var4);
    var _closure1_slot3 = var4;
    var4 = 1;
    var8 = var6[var4];
    var4 = metroImportAll;
    var8 = var4.bind(var1)(var8);
    var _closure1_slot4 = var8;
    var4 = 2;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.StyleSheet;
    var _closure1_slot5 = var4;
    var4 = 3;
    var4 = var6[var4];
    var4 = var7.bind(var1)(var4);
    var _closure1_slot6 = var4;
    var4 = 4;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.NOOP;
    var _closure1_slot7 = var4;
    var4 = 5;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.jsx;
    var _closure1_slot8 = var4;
    var7 = var8.forwardRef;
    var4 = function(arg1, arg2) {
        var1 = arg1;
        var9 = var1.sheetKey;
        var _closure2_slot0 = var9;
        var7 = var1.content;
        var16 = var1.impressionName;
        var12 = var1.impressionProperties;
        var13 = _closure1_slot4;
        var4 = var13.useState;
        var2 = 'visible';
        var6 = var4.bind(var13)(var2);
        var5 = _closure1_slot3;
        var4 = undefined;
        var2 = 2;
        var5 = var5.bind(var4)(var6, var2);
        var2 = 0;
        var15 = var5[var2];
        var _closure2_slot1 = var15;
        var2 = 1;
        var2 = var5[var2];
        var _closure2_slot2 = var2;
        var2 = var13.useRef;
        var6 = _closure1_slot7;
        var2 = var2.bind(var13)(var6);
        var _closure2_slot3 = var2;
        var8 = var13.useCallback;
        var5 = function(arg1) {
            var2 = _closure2_slot3;
            var1 = arg1;
            var2['current'] = var1;
            var1 = undefined;
            return var1;
        };
        var2 = new Array(0);
        var5 = var8.bind(var13)(var5, var2);
        var _closure2_slot4 = var5;
        var2 = var13.useRef;
        var2 = var2.bind(var13)(var6);
        var _closure2_slot5 = var2;
        var8 = var13.useCallback;
        var6 = function() {
            var2 = _closure2_slot5;
            var1 = var2.current;
            var1 = var1.bind(var2)();
            var1 = undefined;
            return var1;
        };
        var2 = new Array(0);
        var14 = var8.bind(var13)(var6, var2);
        var _closure2_slot6 = var14;
        var2 = _closure1_slot1;
        var10 = _closure1_slot2;
        var6 = 6;
        var6 = var10[var6];
        var11 = var2.bind(var4)(var6);
        var8 = {};
        var6 = _closure1_slot0;
        var17 = 7;
        var17 = var10[var17];
        var17 = var6.bind(var4)(var17);
        var17 = var17.ImpressionTypes;
        var17 = var17.HALFSHEET;
        var8['type'] = var17;
        var8['name'] = var16;
        var8['properties'] = var12;
        var8 = var11.bind(var4)(var8);
        var16 = var13.useImperativeHandle;
        var12 = arg2;
        var11 = function() {
            var1 = {};
            var3 = function componentDidEnter() {
                var3 = _closure2_slot2;
                var1 = undefined;
                var2 = 'visible';
                var2 = var3.bind(var1)(var2);
                return var1;
            };
            var1['componentDidEnter'] = var3;
            var3 = function componentWillLeave(arg1) {
                var4 = _closure2_slot2;
                var1 = undefined;
                var3 = 'exiting';
                var3 = var4.bind(var1)(var3);
                var3 = _closure2_slot5;
                var2 = arg1;
                var3['current'] = var2;
                return var1;
            };
            var1['componentWillLeave'] = var3;
            var2 = function componentDidLeave() {
                var4 = _closure2_slot2;
                var1 = undefined;
                var3 = 'exited';
                var3 = var4.bind(var1)(var3);
                var3 = _closure2_slot5;
                var2 = _closure1_slot7;
                var3['current'] = var2;
                return var1;
            };
            var1['componentDidLeave'] = var2;
            return var1;
        };
        var8 = new Array(0);
        var8 = var16.bind(var13)(var12, var11, var8);
        var12 = var13.useCallback;
        var11 = new Array(1);
        var11[0] = var9;
        var8 = function() {
            var3 = _closure1_slot1;
            var2 = _closure1_slot2;
            var1 = 8;
            var2 = var2[var1];
            var1 = undefined;
            var4 = var3.bind(var1)(var2);
            var3 = var4.hideActionSheet;
            var2 = _closure2_slot0;
            var2 = var3.bind(var4)(var2);
            return var1;
        };
        var8 = var12.bind(var13)(var8, var11);
        var _closure2_slot7 = var8;
        var12 = var13.useMemo;
        var11 = new Array(4);
        var11[0] = var15;
        var11[1] = var8;
        var11[2] = var14;
        var11[3] = var5;
        var5 = function() {
            var1 = {};
            var3 = _closure2_slot1;
            var1['transitionState'] = var3;
            var3 = _closure2_slot7;
            var1['close'] = var3;
            var3 = _closure2_slot6;
            var1['onLeave'] = var3;
            var2 = _closure2_slot4;
            var1['registerDismissHandler'] = var2;
            return var1;
        };
        var5 = var12.bind(var13)(var5, var11);
        var12 = var13.useCallback;
        var11 = new Array(1);
        var11[0] = var8;
        var3 = function() {
            _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
                var2 = _closure2_slot3;
                var3 = var2.current;
                var2 = null;
                if(!(var2 != var3)) { _fun0001_ip = 2; continue _fun0001 }
case 3:
                var3 = _closure2_slot3;
                var2 = var3.current;
                var2 = var2.bind(var3)();
case 2:
                var2 = _closure2_slot7;
                var1 = undefined;
                var1 = var2.bind(var1)();
                var1 = true;
                return var1;
            }
        };
        var11 = var12.bind(var13)(var3, var11);
        var3 = 9;
        var3 = var10[var3];
        var3 = var2.bind(var4)(var3);
        var3 = var3.bind(var4)(var11);
        var3 = _closure1_slot8;
        var1 = 10;
        var1 = var10[var1];
        var1 = var2.bind(var4)(var1);
        var2 = var1.Provider;
        var1 = {};
        var1['value'] = var5;
        var5 = 11;
        var5 = var10[var5];
        var5 = var6.bind(var4)(var5);
        var6 = var5.Dialog;
        var5 = {};
        var5['dialogKey'] = var9;
        var5['onDismiss'] = var8;
        var5['children'] = var7;
        var5 = var3.bind(var4)(var6, var5);
        var1['children'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var4 = var7.bind(var8)(var4);
    var _closure1_slot9 = var4;
    var4 = 15;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'design/components/Sheet/native/ActionSheetPresenter.native.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function ActionSheetPresenter(arg1) {
        var2 = arg1;
        var5 = var2.appEntryKey;
        var7 = _closure1_slot0;
        var8 = _closure1_slot2;
        var2 = 12;
        var2 = var8[var2];
        var4 = undefined;
        var11 = var7.bind(var4)(var2);
        var10 = var11.useStateFromStoresArray;
        var2 = _closure1_slot6;
        var9 = new Array(1);
        var9[0] = var2;
        var3 = function() {
            var2 = _closure1_slot6;
            var1 = var2.getStack;
            var1 = var1.bind(var2)();
            return var1;
        };
        var2 = new Array(0);
        var3 = var10.bind(var11)(var9, var3, var2);
        var2 = function filterStackForAppEntryKey(arg1, arg2) {
            _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
case 0:
                var4 = arg1;
                var3 = 'share';
                var1 = arg2;
                if(!(var3 !== var1)) { _fun0002_ip = 4; continue _fun0002 }
case 5:
                var3 = var4.filter;
                var1 = function(arg1) {
                    var1 = arg1;
                    var2 = var1.appEntryKey;
                    var1 = 'share';
                    var1 = var1 !== var2;
                    return var1;
                };
                var1 = var3.bind(var4)(var1);
                _fun0002_ip = 6; continue _fun0002;
case 4:
                var3 = var4.filter;
                var2 = function(arg1) {
                    var1 = arg1;
                    var2 = var1.appEntryKey;
                    var1 = 'share';
                    var1 = var1 === var2;
                    return var1;
                };
                var1 = var3.bind(var4)(var2);
case 6:
                return var1;
            }
        };
        var3 = var2.bind(var4)(var3, var5);
        var2 = var3.map;
        var1 = function(arg1) {
            var1 = arg1;
            var7 = var1.content;
            var5 = var1.key;
            var6 = var1.impressionName;
            var1 = var1.impressionProperties;
            var4 = _closure1_slot8;
            var3 = _closure1_slot9;
            var2 = {};
            var2['sheetKey'] = var5;
            var2['content'] = var7;
            var2['impressionName'] = var6;
            var2['impressionProperties'] = var1;
            var1 = undefined;
            var1 = var4.bind(var1)(var3, var2, var5);
            return var1;
        };
        var5 = var2.bind(var3)(var1);
        var3 = _closure1_slot8;
        var1 = 13;
        var1 = var8[var1];
        var1 = var7.bind(var4)(var1);
        var2 = var1.TransitionGroup;
        var1 = {};
        var6 = _closure1_slot5;
        var6 = var6.absoluteFill;
        var1['style'] = var6;
        var6 = 14;
        var6 = var8[var6];
        var6 = var7.bind(var4)(var6);
        var6 = var6.TransitionGroupOverlayView;
        var1['component'] = var6;
        var1['children'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var3['ActionSheetPresenter'] = var2;
    return var1;
})();