// app/design/components/Sheet/native/showSimpleActionSheet.native.tsx
export default (function(argFoo, argBar, argBaz, _, __, argFre, argPlu) {
    report = argBar;
    zuuluu = argFre;
    tangon = argPlu;
    var _closure1_slot0 = report;
    entity = argBaz;
    var _closure1_slot1 = entity;
    var _closure1_slot2 = tangon;
    entity = global;
    option = entity.Object;
    golfie = option.defineProperty;
    oscard = {};
    entity = true;
    oscard['value'] = entity;
    entity = '__esModule';
    entity = golfie.bind(option)(zuuluu, entity, oscard);
    entity = 3;
    tangon = tangon[entity];
    entity = undefined;
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'design/components/Sheet/native/showSimpleActionSheet.native.tsx';
    tangon = report.bind(oscard)(tangon);
    michal = function(argFoo) { // Original name: showSimpleActionSheet
        tangon = argFoo;
        golfie = tangon.key;
        var _closure2_slot0 = golfie;
        yankee = tangon.stackingBehavior;
        entity = null;
        zuuluu = Object.create(entity);
        entity = 0;
        zuuluu['key'] = entity;
        zuuluu['stackingBehavior'] = entity;
        backup = {};
        foxtra = tangon;
        romeon = zuuluu;
        verify = copyDataProperties(backup, foxtra, romeon);
        report = _closure1_slot1;
        michal = _closure1_slot2;
        tangon = michal[entity];
        entity = undefined;
        report = report.bind(entity)(tangon);
        tangon = report.openLazy;
        offset = _closure1_slot0;
        zuuluu = 2;
        zuuluu = michal[zuuluu];
        offset = offset.bind(entity)(zuuluu);
        zuuluu = 1;
        zuuluu = michal[zuuluu];
        michal = michal.paths;
        zuuluu = offset.bind(entity)(zuuluu, michal);
        michal = {};
        backup = michal;
        foxtra = verify;
        verify = copyDataProperties(backup, foxtra);
        verify = function() { // Original name: hideActionSheet
            zuuluu = _closure1_slot1;
            michal = _closure1_slot2;
            entity = 0;
            michal = michal[entity];
            entity = undefined;
            tangon = zuuluu.bind(entity)(michal);
            zuuluu = tangon.hideActionSheet;
            michal = _closure2_slot0;
            michal = zuuluu.bind(tangon)(michal);
            return entity;
        };
        option = 'hideActionSheet';
        michal[option] = verify;
        kiloes = report;
        backup = zuuluu;
        foxtra = golfie;
        romeon = michal;
        michal = kiloes[tangon](backup, foxtra, romeon, yankee, offset);
        return entity;
    };
    zuuluu['showSimpleActionSheet'] = michal;
    return entity;
})();