// app/modules/emojis/EmojiTypes.tsx
export default (function(_, argBar, __, ___, ____, argFred, argPlugh) {
    zulu = argFred;
    entity = global;
    report = entity.Object;
    tango = report.defineProperty;
    mike = {};
    entity = true;
    mike['value'] = entity;
    entity = '__esModule';
    entity = tango.bind(report)(zulu, entity, mike);
    mike = {};
    tango = 0;
    mike['UNICODE'] = tango;
    entity = 'UNICODE';
    mike[tango] = entity;
    report = 1;
    mike['GUILD'] = report;
    entity = 'GUILD';
    mike[report] = entity;
    entity = argPlugh;
    report = entity[tango];
    tango = argBar;
    entity = undefined;
    oscar = tango.bind(entity)(report);
    report = oscar.fileFinishedImporting;
    tango = 'modules/emojis/EmojiTypes.tsx';
    tango = report.bind(oscar)(tango);
    zulu['EmojiTypes'] = mike;
    return entity;
})();