// app/modules/application_commands/ApplicationCommandQueryTypes.tsx
export default (function(_, argBar, __, ___, ____, argFre, argPlu) {
    zuuluu = argFre;
    entity = global;
    report = entity.Object;
    tangon = report.defineProperty;
    michal = {};
    entity = true;
    michal['value'] = entity;
    entity = '__esModule';
    entity = tangon.bind(report)(zuuluu, entity, michal);
    tangon = {};
    entity = 'none';
    tangon['NONE'] = entity;
    entity = 'application_only';
    tangon['APPLICATION_ONLY'] = entity;
    entity = 'command_only';
    tangon['COMMAND_ONLY'] = entity;
    entity = 'command_or_application';
    tangon['COMMAND_OR_APPLICATION'] = entity;
    michal = {};
    entity = 'allow';
    michal['ALLOW'] = entity;
    entity = 'only_text';
    michal['ONLY_TEXT'] = entity;
    entity = 'deny';
    michal['DENY'] = entity;
    report = argPlu;
    entity = 0;
    oscard = report[entity];
    report = argBar;
    entity = undefined;
    golfie = report.bind(entity)(oscard);
    oscard = golfie.fileFinishedImporting;
    report = 'modules/application_commands/ApplicationCommandQueryTypes.tsx';
    report = oscard.bind(golfie)(report);
    zuuluu['ScoreMethod'] = tangon;
    zuuluu['BuiltInCommandFilter'] = michal;
    return entity;
})();