// app/modules/interaction_components/content_inventory_entry/ContentInventoryEmbedExperiments.tsx
export default (function(argFoo, argBar, _, __, ___, argFred, argPlugh) {
    oscar = argBar;
    zulu = argFred;
    golf = argPlugh;
    entity = global;
    options = entity.Object;
    report = options.defineProperty;
    tango = {};
    romeo = true;
    tango['value'] = romeo;
    entity = '__esModule';
    entity = report.bind(options)(zulu, entity, tango);
    entity = 0;
    tango = golf[entity];
    entity = undefined;
    verify = oscar.bind(entity)(tango);
    options = verify.createExperiment;
    tango = {'kind': 'user', 'id': '2024-06_content_entry_embed', 'label': 'Content Inventory Embed'};
    report = {};
    offset = false;
    report['enabled'] = offset;
    tango['defaultConfig'] = report;
    yankee = {'id': 1, 'label': 'Enabled'};
    report = 1;
    offset = {};
    offset['enabled'] = romeo;
    yankee['config'] = offset;
    offset = new Array(1);
    offset[0] = yankee;
    tango['treatments'] = offset;
    tango = options.bind(verify)(tango);
    var _closure1_slot0 = tango;
    report = golf[report];
    golf = oscar.bind(entity)(report);
    oscar = golf.fileFinishedImporting;
    report = 'modules/interaction_components/content_inventory_entry/ContentInventoryEmbedExperiments.tsx';
    report = oscar.bind(golf)(report);
    zulu['ContentInventoryEmbedExperiment'] = tango;
    tango = function(argFoo) { // Original name: isContentInventoryEmbedEnabled
        zulu = _closure1_slot0;
        mike = zulu.getCurrentConfig;
        entity = {};
        tango = argFoo;
        entity['location'] = tango;
        entity = mike.bind(zulu)(entity);
        entity = entity.enabled;
        return entity;
    };
    zulu['isContentInventoryEmbedEnabled'] = tango;
    mike = function(argFoo) { // Original name: useIsContentInventoryEmbedEnabled
        zulu = _closure1_slot0;
        mike = zulu.useExperiment;
        entity = {};
        tango = argFoo;
        entity['location'] = tango;
        entity = mike.bind(zulu)(entity);
        entity = entity.enabled;
        return entity;
    };
    zulu['useIsContentInventoryEmbedEnabled'] = mike;
    return entity;
})();