// app/modules/premium/PremiumSKUFeature.tsx
export default (function(argFoo, argBar, argBaz, _, __, argFred, argPlugh) {
    golf = argBaz;
    zulu = argFred;
    report = argPlugh;
    entity = global;
    options = entity.Object;
    tango = options.defineProperty;
    mike = {};
    entity = true;
    mike['value'] = entity;
    entity = '__esModule';
    entity = tango.bind(options)(zulu, entity, mike);
    entity = 0;
    mike = report[entity];
    entity = undefined;
    tango = golf.bind(entity)(mike);
    mike = 1;
    mike = report[mike];
    mike = golf.bind(entity)(mike);
    var _closure1_slot0 = mike;
    mike = function(argFoo, argBar, argBaz) { // Original name: PremiumSKUFeature
        mike = argBar;
        oscar = this;
        tango = _closure1_slot0;
        zulu = _closure1_slot1;
        entity = undefined;
        zulu = tango.bind(entity)(oscar, zulu);
        zulu = argFoo;
        oscar['name'] = zulu;
        zulu = argBaz;
        oscar['description'] = zulu;
        oscar['getFeatureValue'] = mike;
        zulu = global;
        report = zulu.Object;
        tango = report.defineProperty;
        zulu = {'value': null, 'configurable': false, 'writable': false};
        zulu['value'] = mike;
        mike = 'getFeatureValue';
        mike = tango.bind(report)(oscar, mike, zulu);
        return entity;
    };
    var _closure1_slot1 = mike;
    mike = tango.bind(entity)(mike);
    tango = 2;
    report = report[tango];
    tango = argBar;
    oscar = tango.bind(entity)(report);
    report = oscar.fileFinishedImporting;
    tango = 'modules/premium/PremiumSKUFeature.tsx';
    tango = report.bind(oscar)(tango);
    zulu['default'] = mike;
    return entity;
})();