// app/modules/user_settings/native/connections/useConsoleLinkSettingsCoachmark.tsx
export default (function(native1, native2, native3, native4, native5, native6, native7) {
    var5 = native2;
    var7 = native3;
    var3 = native6;
    var6 = native7;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var7;
    var _closure1_slot2 = var6;
    var1 = function ConsoleLinkCoachmarkImg() {
        var1 = _closure1_slot10;
        var4 = undefined;
        var8 = var1.bind(var4)();
        var3 = _closure1_slot9;
        var2 = _closure1_slot5;
        var1 = {};
        var5 = var8.coachmarkImageContainer;
        var1['style'] = var5;
        var7 = _closure1_slot9;
        var6 = _closure1_slot6;
        var5 = {};
        var9 = {};
        var11 = _closure1_slot1;
        var12 = _closure1_slot2;
        var10 = 7;
        var10 = var12[var10];
        var10 = var11.bind(var4)(var10);
        var9['uri'] = var10;
        var5['source'] = var9;
        var8 = var8.coachmarkImage;
        var5['style'] = var8;
        var5 = var7.bind(var4)(var6, var5);
        var1['children'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var _closure1_slot11 = var1;
    var1 = global;
    var9 = var1.Object;
    var8 = var9.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var8.bind(var9)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var7.bind(var1)(var4);
    var _closure1_slot3 = var4;
    var4 = 1;
    var7 = var6[var4];
    var4 = native4;
    var4 = var4.bind(var1)(var7);
    var _closure1_slot4 = var4;
    var4 = 2;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var7 = var4.View;
    var _closure1_slot5 = var7;
    var4 = var4.Image;
    var _closure1_slot6 = var4;
    var4 = 3;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.UserSettingsSections;
    var _closure1_slot7 = var4;
    var4 = 4;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.ContentDismissActionType;
    var _closure1_slot8 = var4;
    var4 = 5;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.jsx;
    var _closure1_slot9 = var4;
    var4 = 6;
    var4 = var6[var4];
    var8 = var5.bind(var1)(var4);
    var7 = var8.createStyles;
    var4 = {};
    var9 = {'alignItems': 'center', 'justifyContent': 'center'};
    var4['coachmarkImageContainer'] = var9;
    var9 = {'width': 62, 'height': 56};
    var4['coachmarkImage'] = var9;
    var4 = var7.bind(var8)(var4);
    var _closure1_slot10 = var4;
    var4 = 14;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/user_settings/native/connections/useConsoleLinkSettingsCoachmark.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function useConsoleLinkSettingsCoachmark(arg1) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
 0:
            var2 = arg1;
            var2 = var2.disabled;
            var8 = undefined;
            var _closure2_slot0 = var8;
            var _closure2_slot1 = var8;
            var6 = _closure1_slot0;
            var7 = _closure1_slot2;
            var4 = 8;
            var4 = var7[var4];
            var9 = var6.bind(var8)(var4);
            var5 = var9.useIsConnectionsConsoleLinkExperimentEnabled;
            var4 = {};
            var10 = 'useNewConsoleCoachmark';
            var4['location'] = var10;
            var10 = !var2;
            var4['autoTrackExposure'] = var10;
            var5 = var5.bind(var9)(var4);
            var4 = 9;
            var4 = var7[var4];
            var6 = var6.bind(var8)(var4);
            var4 = var6.useGetDismissibleContent;
            if(!var5) { _fun0001_ip = 140; continue _fun0001 }
 95:
            if(var2) { _fun0001_ip = 140; continue _fun0001 }
 98:
            var7 = _closure1_slot0;
            var9 = _closure1_slot2;
            var2 = 10;
            var2 = var9[var2];
            var2 = var7.bind(var8)(var2);
            var2 = var2.DismissibleContent;
            var7 = var2.CONNECTIONS_LINK_CONSOLE_COACHMARK;
            var2 = new Array(1);
            var2[0] = var7;
            _fun0001_ip = 144; continue _fun0001;
 140:
            var2 = new Array(0);
 144:
            var6 = var4.bind(var6)(var2);
            var4 = _closure1_slot3;
            var2 = 2;
            var6 = var4.bind(var8)(var6, var2);
            var2 = 0;
            var4 = var6[var2];
            var2 = 1;
            var7 = var6[var2];
            _closure2_slot0 = var7;
            var6 = _closure1_slot0;
            var9 = _closure1_slot2;
            var2 = 10;
            var2 = var9[var2];
            var2 = var6.bind(var8)(var2);
            var2 = var2.DismissibleContent;
            var2 = var2.CONNECTIONS_LINK_CONSOLE_COACHMARK;
            var2 = var4 === var2;
            _closure2_slot1 = var2;
            var6 = _closure1_slot4;
            var4 = var6.useMemo;
            var3 = new Array(2);
            var3[0] = var2;
            var3[1] = var7;
            var1 = function() {
                var1 = {};
                var7 = _closure1_slot0;
                var8 = _closure1_slot2;
                var3 = 11;
                var4 = var8[var3];
                var6 = undefined;
                var4 = var7.bind(var6)(var4);
                var9 = var4.intl;
                var5 = var9.string;
                var4 = var8[var3];
                var4 = var7.bind(var6)(var4);
                var4 = var4.t;
                var4 = var4.yh1HSU;
                var4 = var5.bind(var9)(var4);
                var1['title'] = var4;
                var4 = var8[var3];
                var4 = var7.bind(var6)(var4);
                var9 = var4.intl;
                var5 = var9.string;
                var4 = var8[var3];
                var4 = var7.bind(var6)(var4);
                var4 = var4.t;
                var4 = var4.a0xiio;
                var4 = var5.bind(var9)(var4);
                var1['description'] = var4;
                var4 = 'bottom';
                var1['position'] = var4;
                var4 = _closure2_slot1;
                var1['visible'] = var4;
                var4 = 'primary';
                var1['buttonVariant'] = var4;
                var4 = var8[var3];
                var4 = var7.bind(var6)(var4);
                var5 = var4.intl;
                var4 = var5.string;
                var3 = var8[var3];
                var3 = var7.bind(var6)(var3);
                var3 = var3.t;
                var3 = var3.6gSXHB;
                var3 = var4.bind(var5)(var3);
                var1['buttonLabel'] = var3;
                var3 = function onButtonPress() {
                    var8 = _closure1_slot0;
                    var9 = _closure1_slot2;
                    var1 = 12;
                    var3 = var9[var1];
                    var1 = undefined;
                    var5 = var8.bind(var1)(var3);
                    var4 = var5.openUserSettings;
                    var3 = {};
                    var6 = _closure1_slot7;
                    var6 = var6.CONNECTIONS;
                    var3['screen'] = var6;
                    var6 = {};
                    var7 = 13;
                    var7 = var9[var7];
                    var7 = var8.bind(var1)(var7);
                    var7 = var7.ADD_CONNECTIONS_SHEET_SENTINEL;
                    var6['selectedPlatformType'] = var7;
                    var3['params'] = var6;
                    var3 = var4.bind(var5)(var3);
                    var3 = _closure2_slot0;
                    var2 = _closure1_slot8;
                    var2 = var2.USER_DISMISS;
                    var2 = var3.bind(var1)(var2);
                    return var1;
                };
                var1['onButtonPress'] = var3;
                var3 = function onDismiss() {
                    var3 = _closure2_slot0;
                    var1 = _closure1_slot8;
                    var2 = var1.USER_DISMISS;
                    var1 = undefined;
                    var2 = var3.bind(var1)(var2);
                    return var1;
                };
                var1['onDismiss'] = var3;
                var2 = function renderImgComponent() {
                    var4 = _closure1_slot9;
                    var3 = _closure1_slot11;
                    var2 = undefined;
                    var1 = {};
                    var1 = var4.bind(var2)(var3, var1);
                    return var1;
                };
                var1['renderImgComponent'] = var2;
                return var1;
            };
            var3 = var4.bind(var6)(var1, var3);
            var1 = null;
            if(!var5) { _fun0001_ip = 272; continue _fun0001 }
 258:
            var1 = null;
            if(!var2) { _fun0001_ip = 272; continue _fun0001 }
 263:
            var2 = {};
            var2['props'] = var3;
            var1 = var2;
 272:
            return var1;
        }
    };
    var3['default'] = var2;
    return var1;
})();