// app/modules/app_launcher/native/screens/command_view/hooks/useOptionAnimations.tsx
export default (function(argFoo, argBar, argBaz, argCorge, _, argFred, argPlugh) {
    golf = argBar;
    zulu = argFred;
    options = argPlugh;
    var _closure1_slot0 = golf;
    var _closure1_slot1 = options;
    entity = global;
    oscar = entity.Object;
    report = oscar.defineProperty;
    tango = {};
    entity = true;
    tango['value'] = entity;
    entity = '__esModule';
    entity = report.bind(oscar)(zulu, entity, tango);
    entity = 0;
    report = options[entity];
    tango = argBaz;
    entity = undefined;
    tango = tango.bind(entity)(report);
    var _closure1_slot2 = tango;
    tango = 1;
    report = options[tango];
    tango = argCorge;
    tango = tango.bind(entity)(report);
    var _closure1_slot3 = tango;
    tango = {};
    report = 'function LayoutAnimation_useOptionAnimationsTsx1(values){const{withTiming,OPTION_ENTRY_EXIT_LAYOUT_SHIFT_DURATION}=this.__closure;const animations={originY:withTiming(values.targetOriginY,{duration:OPTION_ENTRY_EXIT_LAYOUT_SHIFT_DURATION})};const initialValues={originY:values.currentOriginY};return{initialValues:initialValues,animations:animations};}';
    tango['code'] = report;
    var _closure1_slot4 = tango;
    tango = function() {
        entity = function(argFoo) { // Original name: LayoutAnimation
            tango = argFoo;
            mike = {};
            report = _closure1_slot0;
            zulu = _closure1_slot1;
            entity = 2;
            zulu = zulu[entity];
            entity = undefined;
            oscar = report.bind(entity)(zulu);
            report = oscar.withTiming;
            zulu = tango.targetOriginY;
            entity = {};
            golf = 300;
            entity['duration'] = golf;
            entity = report.bind(oscar)(zulu, entity);
            mike['originY'] = entity;
            entity = {};
            zulu = {};
            tango = tango.currentOriginY;
            zulu['originY'] = tango;
            entity['initialValues'] = zulu;
            entity['animations'] = mike;
            return entity;
        };
        zulu = {};
        oscar = _closure1_slot0;
        report = _closure1_slot1;
        tango = 2;
        report = report[tango];
        tango = undefined;
        tango = oscar.bind(tango)(report);
        tango = tango.withTiming;
        zulu['withTiming'] = tango;
        tango = 300;
        zulu['OPTION_ENTRY_EXIT_LAYOUT_SHIFT_DURATION'] = tango;
        entity['__closure'] = zulu;
        zulu = 16804895997501.0;
        entity['__workletHash'] = zulu;
        mike = _closure1_slot4;
        entity['__initData'] = mike;
        return entity;
    };
    report = tango.bind(entity)();
    tango = {};
    oscar = 'function ExitingAnimation_useOptionAnimationsTsx2(values){const{withTiming,OPTION_ENTRY_EXIT_LAYOUT_SHIFT_DURATION}=this.__closure;const offScreenX=Math.min(values.currentOriginX-values.windowWidth,-values.windowWidth);const animations={opacity:withTiming(0,{duration:OPTION_ENTRY_EXIT_LAYOUT_SHIFT_DURATION}),originX:withTiming(offScreenX,{duration:OPTION_ENTRY_EXIT_LAYOUT_SHIFT_DURATION})};const initialValues={originX:values.currentOriginX,opacity:1};return{initialValues:initialValues,animations:animations};}';
    tango['code'] = oscar;
    var _closure1_slot5 = tango;
    tango = function() {
        entity = function(argFoo) { // Original name: ExitingAnimation
            tango = argFoo;
            entity = global;
            report = entity.Math;
            zulu = report.min;
            mike = tango.currentOriginX;
            entity = tango.windowWidth;
            mike = mike - entity;
            entity = tango.windowWidth;
            entity = -entity;
            oscar = zulu.bind(report)(mike, entity);
            mike = {};
            report = _closure1_slot0;
            options = _closure1_slot1;
            entity = 2;
            golf = options[entity];
            zulu = undefined;
            romeo = report.bind(zulu)(golf);
            yankee = romeo.withTiming;
            offset = {};
            golf = 300;
            offset['duration'] = golf;
            verify = 0;
            verify = yankee.bind(romeo)(verify, offset);
            mike['opacity'] = verify;
            entity = options[entity];
            report = report.bind(zulu)(entity);
            zulu = report.withTiming;
            entity = {};
            entity['duration'] = golf;
            entity = zulu.bind(report)(oscar, entity);
            mike['originX'] = entity;
            entity = {};
            zulu = {};
            tango = tango.currentOriginX;
            zulu['originX'] = tango;
            tango = 1;
            zulu['opacity'] = tango;
            entity['initialValues'] = zulu;
            entity['animations'] = mike;
            return entity;
        };
        zulu = {};
        oscar = _closure1_slot0;
        report = _closure1_slot1;
        tango = 2;
        report = report[tango];
        tango = undefined;
        tango = oscar.bind(tango)(report);
        tango = tango.withTiming;
        zulu['withTiming'] = tango;
        tango = 300;
        zulu['OPTION_ENTRY_EXIT_LAYOUT_SHIFT_DURATION'] = tango;
        entity['__closure'] = zulu;
        zulu = 8977480282966.0;
        entity['__workletHash'] = zulu;
        mike = _closure1_slot5;
        entity['__initData'] = mike;
        return entity;
    };
    tango = tango.bind(entity)();
    oscar = {};
    verify = 'function useOptionAnimationsTsx3(){const{withTiming,Easing,OPTION_ENTRY_EXIT_LAYOUT_SHIFT_DURATION,withDelay,runOnJS,handleMountAnimationComplete}=this.__closure;const scaleAnimation=withTiming(1,{duration:250,easing:Easing.bezier(0.25,1.75,0.25,1.25)});const opacityAnimation=withTiming(1,{duration:200});const layoutShiftDelay=OPTION_ENTRY_EXIT_LAYOUT_SHIFT_DURATION-100;return{animations:{opacity:withDelay(layoutShiftDelay,opacityAnimation),transform:[{scale:withDelay(layoutShiftDelay,scaleAnimation)}]},initialValues:{opacity:0,transform:[{scale:0.92}]},callback:function(){runOnJS(handleMountAnimationComplete)();}};}';
    oscar['code'] = verify;
    var _closure1_slot6 = oscar;
    oscar = 4;
    oscar = options[oscar];
    options = golf.bind(entity)(oscar);
    golf = options.fileFinishedImporting;
    oscar = 'modules/app_launcher/native/screens/command_view/hooks/useOptionAnimations.tsx';
    oscar = golf.bind(options)(oscar);
    oscar = 300;
    zulu['OPTION_ENTRY_EXIT_LAYOUT_SHIFT_DURATION'] = oscar;
    zulu['LayoutAnimation'] = report;
    zulu['ExitingAnimation'] = tango;
    mike = function() { // Original name: useOptionEnteringAnimation
        tango = _closure1_slot0;
        report = _closure1_slot1;
        entity = 3;
        entity = report[entity];
        oscar = undefined;
        report = tango.bind(oscar)(entity);
        tango = report.useSharedValue;
        entity = false;
        entity = tango.bind(report)(entity);
        var _closure2_slot0 = entity;
        report = _closure1_slot3;
        golf = report.useRef;
        tango = new Array(0);
        tango = golf.bind(report)(tango);
        var _closure2_slot1 = tango;
        golf = report.useCallback;
        tango = new Array(1);
        tango[0] = entity;
        entity = function() {
            tango = _closure2_slot0;
            zulu = tango.set;
            mike = true;
            mike = zulu.bind(tango)(mike);
            entity = _closure2_slot1;
            tango = entity.current;
            zulu = tango.forEach;
            mike = function(argFoo) {
                mike = argFoo;
                entity = undefined;
                entity = mike.bind(entity)();
                return entity;
            };
            mike = zulu.bind(tango)(mike);
            tango = entity.current;
            zulu = tango.splice;
            entity = entity.current;
            mike = entity.length;
            entity = 0;
            entity = zulu.bind(tango)(entity, mike);
            entity = undefined;
            return entity;
        };
        entity = golf.bind(report)(entity, tango);
        var _closure2_slot2 = entity;
        tango = report.useState;
        entity = function() {
            entity = function() { // Original name: n
                options = _closure1_slot0;
                verify = _closure1_slot1;
                entity = 2;
                mike = verify[entity];
                report = undefined;
                oscar = options.bind(report)(mike);
                tango = oscar.withTiming;
                mike = {};
                zulu = 250;
                mike['duration'] = zulu;
                zulu = 3;
                golf = verify[zulu];
                golf = options.bind(report)(golf);
                foxtrot = golf.Easing;
                romeo = foxtrot.bezier;
                yankee = 0.25;
                sizing = 1.75;
                backup = 1.25;
                result = foxtrot;
                output = yankee;
                kilo = yankee;
                golf = result[romeo](output, sizing, kilo, backup, foxtrot);
                mike['easing'] = golf;
                offset = 1;
                golf = tango.bind(oscar)(offset, mike);
                entity = verify[entity];
                tango = options.bind(report)(entity);
                mike = tango.withTiming;
                entity = {};
                oscar = 200;
                entity['duration'] = oscar;
                yankee = mike.bind(tango)(offset, entity);
                entity = {};
                mike = {};
                tango = verify[zulu];
                offset = options.bind(report)(tango);
                tango = offset.withDelay;
                tango = tango.bind(offset)(oscar, yankee);
                mike['opacity'] = tango;
                tango = {};
                zulu = verify[zulu];
                report = options.bind(report)(zulu);
                zulu = report.withDelay;
                zulu = zulu.bind(report)(oscar, golf);
                tango['scale'] = zulu;
                zulu = new Array(1);
                zulu[0] = tango;
                mike['transform'] = zulu;
                entity['animations'] = mike;
                mike = {};
                zulu = 0;
                mike['opacity'] = zulu;
                tango = {};
                zulu = 0.92;
                tango['scale'] = zulu;
                zulu = new Array(1);
                zulu[0] = tango;
                mike['transform'] = zulu;
                entity['initialValues'] = mike;
                mike = function() { // Original name: callback
                    zulu = _closure1_slot0;
                    mike = _closure1_slot1;
                    entity = 3;
                    mike = mike[entity];
                    entity = undefined;
                    tango = zulu.bind(entity)(mike);
                    zulu = tango.runOnJS;
                    mike = _closure2_slot2;
                    mike = zulu.bind(tango)(mike);
                    mike = mike.bind(entity)();
                    return entity;
                };
                entity['callback'] = mike;
                return entity;
            };
            zulu = {};
            oscar = _closure1_slot0;
            golf = _closure1_slot1;
            tango = 2;
            tango = golf[tango];
            report = undefined;
            tango = oscar.bind(report)(tango);
            tango = tango.withTiming;
            zulu['withTiming'] = tango;
            tango = 3;
            options = golf[tango];
            options = oscar.bind(report)(options);
            options = options.Easing;
            zulu['Easing'] = options;
            options = 300;
            zulu['OPTION_ENTRY_EXIT_LAYOUT_SHIFT_DURATION'] = options;
            options = golf[tango];
            options = oscar.bind(report)(options);
            options = options.withDelay;
            zulu['withDelay'] = options;
            tango = golf[tango];
            tango = oscar.bind(report)(tango);
            tango = tango.runOnJS;
            zulu['runOnJS'] = tango;
            tango = _closure2_slot2;
            zulu['handleMountAnimationComplete'] = tango;
            entity['__closure'] = zulu;
            zulu = 1048348699475.0;
            entity['__workletHash'] = zulu;
            mike = _closure1_slot6;
            entity['__initData'] = mike;
            return entity;
        };
        report = tango.bind(report)(entity);
        entity = {};
        tango = _closure1_slot2;
        zulu = 1;
        tango = tango.bind(oscar)(report, zulu);
        zulu = 0;
        zulu = tango[zulu];
        entity['EnteringAnimation'] = zulu;
        mike = function(argFoo) { // Original name: registerAnimationCompleteCallback
            _fun119123: for(var _fun119123_ip = 0; ; ) switch(_fun119123_ip) {
 0:
                mike = argFoo;
                tango = _closure2_slot0;
                zulu = tango.get;
                zulu = zulu.bind(tango)();
                if(zulu) { _fun119123_ip = 43; continue _fun119123 }
 22:
                entity = _closure2_slot1;
                zulu = entity.current;
                entity = zulu.push;
                entity = entity.bind(zulu)(mike);
                _fun119123_ip = 49; continue _fun119123;
 43:
                entity = undefined;
                entity = mike.bind(entity)();
 49:
                entity = undefined;
                return entity;
            }
        };
        entity['registerAnimationCompleteCallback'] = mike;
        return entity;
    };
    zulu['useOptionEnteringAnimation'] = mike;
    return entity;
})();