// app/modules/client_themes/ClientThemesBackgroundActionCreators.tsx
export default (function(argFoo, argBar, argBaz, _, __, argFred, argPlugh) {
    zulu = argFred;
    tango = argPlugh;
    entity = argBaz;
    var _closure1_slot0 = entity;
    var _closure1_slot1 = tango;
    entity = global;
    golf = entity.Object;
    oscar = golf.defineProperty;
    report = {};
    entity = true;
    report['value'] = entity;
    entity = '__esModule';
    entity = oscar.bind(golf)(zulu, entity, report);
    entity = 1;
    report = tango[entity];
    tango = argBar;
    entity = undefined;
    oscar = tango.bind(entity)(report);
    report = oscar.fileFinishedImporting;
    tango = 'modules/client_themes/ClientThemesBackgroundActionCreators.tsx';
    tango = report.bind(oscar)(tango);
    tango = function(argFoo) {
        zulu = _closure1_slot0;
        mike = _closure1_slot1;
        entity = 0;
        mike = mike[entity];
        entity = undefined;
        tango = zulu.bind(entity)(mike);
        zulu = tango.dispatch;
        mike = {};
        report = 'UPDATE_BACKGROUND_GRADIENT_PRESET';
        mike['type'] = report;
        report = argFoo;
        mike['presetId'] = report;
        mike = zulu.bind(tango)(mike);
        return entity;
    };
    zulu['updateBackgroundGradientPreset'] = tango;
    tango = function(argFoo) {
        zulu = _closure1_slot0;
        mike = _closure1_slot1;
        entity = 0;
        mike = mike[entity];
        entity = undefined;
        tango = zulu.bind(entity)(mike);
        zulu = tango.dispatch;
        mike = {};
        report = 'UPDATE_MOBILE_PENDING_THEME_INDEX';
        mike['type'] = report;
        report = argFoo;
        mike['mobileThemesIndex'] = report;
        mike = zulu.bind(tango)(mike);
        return entity;
    };
    zulu['updateMobilePendingThemeIndex'] = tango;
    tango = function() {
        zulu = _closure1_slot0;
        mike = _closure1_slot1;
        entity = 0;
        mike = mike[entity];
        entity = undefined;
        tango = zulu.bind(entity)(mike);
        zulu = tango.dispatch;
        mike = {'type': 'UPDATE_BACKGROUND_GRADIENT_PRESET', 'presetId': null};
        mike = zulu.bind(tango)(mike);
        return entity;
    };
    zulu['resetBackgroundGradientPreset'] = tango;
    tango = function() {
        zulu = _closure1_slot0;
        mike = _closure1_slot1;
        entity = 0;
        mike = mike[entity];
        entity = undefined;
        tango = zulu.bind(entity)(mike);
        zulu = tango.dispatch;
        mike = {};
        report = 'CLIENT_THEMES_EDITOR_OPEN';
        mike['type'] = report;
        mike = zulu.bind(tango)(mike);
        return entity;
    };
    zulu['openClientThemeEditor'] = tango;
    tango = function() {
        zulu = _closure1_slot0;
        mike = _closure1_slot1;
        entity = 0;
        mike = mike[entity];
        entity = undefined;
        tango = zulu.bind(entity)(mike);
        zulu = tango.dispatch;
        mike = {};
        report = 'CLIENT_THEMES_EDITOR_CLOSE';
        mike['type'] = report;
        mike = zulu.bind(tango)(mike);
        return entity;
    };
    zulu['closeClientThemeEditor'] = tango;
    mike = function() {
        zulu = _closure1_slot0;
        mike = _closure1_slot1;
        entity = 0;
        mike = mike[entity];
        entity = undefined;
        tango = zulu.bind(entity)(mike);
        zulu = tango.dispatch;
        mike = {};
        report = 'RESET_PREVIEW_CLIENT_THEME';
        mike['type'] = report;
        mike = zulu.bind(tango)(mike);
        return entity;
    };
    zulu['resetPreviewClientTheme'] = mike;
    return entity;
})();