// app/modules/media_keyboard/native/components/MediaKeyboardActionSheet.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var1 = metroImportDefault;
    var _closure1_slot1 = var1;
    var _closure1_slot2 = var6;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var7 = var6[var1];
    var4 = metroImportAll;
    var1 = undefined;
    var4 = var4.bind(var1)(var7);
    var _closure1_slot3 = var4;
    var4 = 1;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.MediaPickerActionSheetEngagedActions;
    var _closure1_slot4 = var4;
    var4 = 2;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.AnalyticEvents;
    var _closure1_slot5 = var4;
    var4 = 3;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.jsx;
    var _closure1_slot6 = var4;
    var4 = 16;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/media_keyboard/native/components/MediaKeyboardActionSheet.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function MediaKeyboardActionSheet(arg1) {
        var3 = arg1;
        var25 = var3.title;
        var23 = var3.subtitle;
        var16 = var3.channel;
        var15 = var3.draftType;
        var8 = var3.uploadLimit;
        var7 = var3.disableWhenReachedLimit;
        var9 = var3.includedUploadIds;
        var14 = var3.onPressCamera;
        var13 = var3.onAttachPress;
        var _closure2_slot0 = var13;
        var12 = var3.onPressItem;
        var11 = var3.onLongPressItem;
        var10 = var3.onViewAll;
        var2 = var3.onClose;
        var _closure2_slot1 = var2;
        var26 = var3.onBack;
        var21 = _closure1_slot0;
        var17 = _closure1_slot2;
        var3 = 4;
        var3 = var17[var3];
        var4 = undefined;
        var18 = var21.bind(var4)(var3);
        var5 = var18.useSharedValue;
        var3 = -1;
        var5 = var5.bind(var18)(var3);
        var24 = _closure1_slot3;
        var19 = var24.useMemo;
        var18 = new Array(1);
        var18[0] = var13;
        var3 = function() {
            var2 = {};
            var5 = _closure1_slot0;
            var6 = _closure1_slot2;
            var3 = 5;
            var1 = var6[var3];
            var4 = undefined;
            var1 = var5.bind(var4)(var1);
            var8 = var1.intl;
            var7 = var8.string;
            var1 = var6[var3];
            var1 = var5.bind(var4)(var1);
            var1 = var1.t;
            var1 = var1.RgIi2B;
            var1 = var7.bind(var8)(var1);
            var2['text'] = var1;
            var1 = 6;
            var1 = var6[var1];
            var1 = var5.bind(var4)(var1);
            var1 = var1.PollsIcon;
            var2['IconComponent'] = var1;
            var1 = function onPress() {
                var1 = undefined;
                return var1;
            };
            var2['onPress'] = var1;
            var1 = true;
            var2['disabled'] = var1;
            var1 = new Array(2);
            var1[0] = var2;
            var2 = {};
            var7 = var6[var3];
            var7 = var5.bind(var4)(var7);
            var8 = var7.intl;
            var7 = var8.string;
            var3 = var6[var3];
            var3 = var5.bind(var4)(var3);
            var3 = var3.t;
            var3 = var3.8Hvr3+;
            var3 = var7.bind(var8)(var3);
            var2['text'] = var3;
            var3 = 7;
            var3 = var6[var3];
            var3 = var5.bind(var4)(var3);
            var3 = var3.AttachmentIcon;
            var2['IconComponent'] = var3;
            var3 = _closure2_slot0;
            var2['onPress'] = var3;
            var3 = false;
            var2['disabled'] = var3;
            var1[1] = var2;
            return var1;
        };
        var18 = var19.bind(var24)(var3, var18);
        var3 = _closure1_slot6;
        var6 = _closure1_slot1;
        var19 = 8;
        var19 = var17[var19];
        var22 = var6.bind(var4)(var19);
        var19 = {};
        var19['title'] = var25;
        var19['subtitle'] = var23;
        var19['animatedIndex'] = var5;
        var19['channel'] = var16;
        var19['overflowButtons'] = var18;
        var19['draftType'] = var15;
        var20 = true;
        var19['hideScrim'] = var20;
        var19['onBack'] = var26;
        var19['onViewAll'] = var10;
        var19['uploadLimit'] = var8;
        var19['disableWhenReachedLimit'] = var7;
        var19['includedUploadIds'] = var9;
        var19 = var3.bind(var4)(var22, var19);
        var _closure2_slot2 = var19;
        var22 = var24.useCallback;
        var19 = new Array(11);
        var19[0] = var5;
        var19[1] = var16;
        var19[2] = var15;
        var19[3] = var26;
        var19[4] = var10;
        var19[5] = var8;
        var19[6] = var9;
        var19[7] = var7;
        var19[8] = var25;
        var19[9] = var23;
        var19[10] = var18;
        var18 = function() {
            var1 = _closure2_slot2;
            return var1;
        };
        var22 = var22.bind(var24)(var18, var19);
        var23 = var24.useCallback;
        var19 = function() {
            var3 = _closure1_slot0;
            var4 = _closure1_slot2;
            var1 = 9;
            var2 = var4[var1];
            var1 = undefined;
            var7 = var3.bind(var1)(var2);
            var5 = var7.triggerHapticFeedback;
            var3 = _closure1_slot1;
            var2 = 10;
            var2 = var4[var2];
            var2 = var3.bind(var1)(var2);
            var2 = var2.IMPACT_LIGHT;
            var2 = var5.bind(var7)(var2);
            var2 = 11;
            var2 = var4[var2];
            var5 = var3.bind(var1)(var2);
            var4 = var5.track;
            var2 = _closure1_slot5;
            var3 = var2.MEDIA_PICKER_ACTION_SHEET_ENGAGED;
            var2 = {};
            var6 = _closure1_slot4;
            var6 = var6.FULLY_EXPANDED;
            var2['action'] = var6;
            var2 = var4.bind(var5)(var3, var2);
            return var1;
        };
        var18 = new Array(0);
        var19 = var23.bind(var24)(var19, var18);
        var23 = var24.useCallback;
        var18 = new Array(1);
        var18[0] = var2;
        var2 = function() {
            _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
                var3 = _closure2_slot1;
                var2 = null;
                if(!(var2 != var3)) { _fun0001_ip = 2; continue _fun0001 }
case 3:
                var2 = _closure2_slot1;
                var1 = undefined;
                var1 = var2.bind(var1)();
case 2:
                var1 = undefined;
                return var1;
            }
        };
        var18 = var23.bind(var24)(var2, var18);
        var _closure2_slot3 = var18;
        var2 = 12;
        var2 = var17[var2];
        var2 = var6.bind(var4)(var2);
        var1 = function() {
            var1 = function() {
                _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
case 0:
                    var3 = _closure2_slot3;
                    var1 = null;
                    var4 = var1 == var3;
                    var3 = undefined;
                    var1 = undefined;
                    if(var4) { _fun0002_ip = 4; continue _fun0002 }
case 5:
                    var2 = _closure2_slot3;
                    var1 = var2.bind(var3)();
case 4:
                    return var1;
                }
            };
            return var1;
        };
        var1 = var2.bind(var4)(var1);
        var1 = 13;
        var1 = var17[var1];
        var1 = var21.bind(var4)(var1);
        var2 = var1.BottomSheet;
        var1 = {};
        var1['handleComponent'] = var22;
        var1['scrollable'] = var20;
        var20 = 14;
        var20 = var17[var20];
        var21 = var21.bind(var4)(var20);
        var20 = var21.isMetaQuest;
        var20 = var20.bind(var21)();
        var1['startExpanded'] = var20;
        var1['onExpand'] = var19;
        var1['onDismiss'] = var18;
        var1['animatedIndex'] = var5;
        var5 = 15;
        var5 = var17[var5];
        var6 = var6.bind(var4)(var5);
        var5 = {};
        var5['channel'] = var16;
        var5['draftType'] = var15;
        var5['onPressCamera'] = var14;
        var5['onAttachPress'] = var13;
        var5['onPressItem'] = var12;
        var5['onLongPressItem'] = var11;
        var5['onViewAll'] = var10;
        var5['includedUploadIds'] = var9;
        var5['uploadLimit'] = var8;
        var5['disableWhenReachedLimit'] = var7;
        var5 = var3.bind(var4)(var6, var5);
        var1['children'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var3['default'] = var2;
    return var1;
})();