// app/modules/media_keyboard/native/components/MediaKeyboardBottomSheetHandle.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var13 = metroImportDefault;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var13;
    var _closure1_slot2 = var6;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var7 = var6[var1];
    var4 = metroImportAll;
    var1 = undefined;
    var7 = var4.bind(var1)(var7);
    var4 = 1;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var8 = var4.Pressable;
    var _closure1_slot3 = var8;
    var8 = var4.View;
    var _closure1_slot4 = var8;
    var12 = var4.StyleSheet;
    var4 = 2;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var11 = var4.DRAG_HANDLE;
    var4 = 3;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.jsx;
    var _closure1_slot5 = var4;
    var4 = 4;
    var4 = var6[var4];
    var9 = var5.bind(var1)(var4);
    var8 = var9.createStyles;
    var4 = {};
    var10 = {};
    var16 = var12.absoluteFillObject;
    var17 = var10;
    var12 = copyDataProperties(var17, var16);
    var14 = 'transparent';
    var12 = 'backgroundColor';
    var10[11] = var14;
    var14 = var11.slotHeight;
    var12 = 'height';
    var10[11] = var14;
    var14 = 'center';
    var12 = 'alignItems';
    var10[11] = var14;
    var12 = 'bottom';
    var10[11] = var1;
    var4['headerHandleWrap'] = var10;
    var10 = {};
    var12 = var11.barColor;
    var10['backgroundColor'] = var12;
    var12 = 5;
    var12 = var6[var12];
    var12 = var13.bind(var1)(var12);
    var12 = var12.radii;
    var12 = var12.xs;
    var10['borderRadius'] = var12;
    var12 = var11.barMarginTop;
    var10['marginTop'] = var12;
    var12 = var11.barHeight;
    var10['height'] = var12;
    var11 = var11.barWidth;
    var10['width'] = var11;
    var4['dragHandleBar'] = var10;
    var4 = var8.bind(var9)(var4);
    var _closure1_slot6 = var4;
    var4 = var7.memo;
    var2 = function MediaKeyboardBottomSheetHandle(arg1) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var1 = arg1;
            var8 = var1.animatedIndex;
            var7 = var1.onPress;
            var1 = _closure1_slot6;
            var5 = undefined;
            var10 = var1.bind(var5)();
            var4 = _closure1_slot0;
            var6 = _closure1_slot2;
            var1 = 6;
            var1 = var6[var1];
            var3 = var4.bind(var5)(var1);
            var1 = var3.useGradientBottom;
            var9 = var1.bind(var3)();
            var3 = _closure1_slot1;
            var1 = 7;
            var1 = var6[var1];
            var3 = var3.bind(var5)(var1);
            var1 = 'MediaKeyboardBottomSheetHandle';
            var1 = var3.bind(var5)(var1);
            var3 = 8;
            var3 = var6[var3];
            var6 = var4.bind(var5)(var3);
            var4 = var6.useDerivedStateFromSharedValue;
            var3 = function(arg1) {
                var2 = arg1;
                var1 = 0;
                var1 = var2 > var1;
                return var1;
            };
            var6 = var4.bind(var6)(var8, var3);
            var11 = _closure1_slot0;
            var12 = _closure1_slot2;
            var3 = 9;
            var4 = var12[var3];
            var4 = var11.bind(var5)(var4);
            var8 = var4.intl;
            var4 = var8.string;
            var3 = var12[var3];
            var3 = var11.bind(var5)(var3);
            var3 = var3.t;
            if(var6) { _fun0001_ip = 2; continue _fun0001 }
case 3:
            var6 = var3.dcl9MQ;
            var6 = var4.bind(var8)(var6);
            _fun0001_ip = 4; continue _fun0001;
case 2:
            var3 = var3.iTcuma;
            var6 = var4.bind(var8)(var3);
case 4:
            var4 = _closure1_slot5;
            if(var1) { _fun0001_ip = 5; continue _fun0001 }
case 6:
            var3 = _closure1_slot3;
            var1 = {};
            var1['accessibilityLabel'] = var6;
            var8 = 'button';
            var1['accessibilityRole'] = var8;
            var8 = null;
            var8 = var8 == var7;
            var1['aria-hidden'] = var8;
            var11 = var10.headerHandleWrap;
            var8 = new Array(2);
            var8[0] = var11;
            var8[1] = var9;
            var1['style'] = var8;
            var1['onPress'] = var7;
            var9 = _closure1_slot4;
            var8 = {};
            var10 = var10.dragHandleBar;
            var8['style'] = var10;
            var8 = var4.bind(var5)(var9, var8);
            var1['children'] = var8;
            var1 = var4.bind(var5)(var3, var1);
            _fun0001_ip = 7; continue _fun0001;
case 5:
            var3 = _closure1_slot0;
            var8 = _closure1_slot2;
            var2 = 10;
            var2 = var8[var2];
            var2 = var3.bind(var5)(var2);
            var3 = var2.ActionSheetDragHandle;
            var2 = {};
            var2['onPress'] = var7;
            var2['accessibilityLabel'] = var6;
            var6 = null;
            var6 = var6 == var7;
            var2['aria-hidden'] = var6;
            var1 = var4.bind(var5)(var3, var2);
case 7:
            return var1;
        }
    };
    var2 = var4.bind(var7)(var2);
    var4 = 11;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/media_keyboard/native/components/MediaKeyboardBottomSheetHandle.tsx';
    var4 = var5.bind(var6)(var4);
    var3['default'] = var2;
    return var1;
})();