// app/modules/notification_settings/native/NotificationSettingsModal.native.tsx
export default (function(native1, native2, native3, native4, native5, native6, native7) {
    var6 = native2;
    var12 = native3;
    var3 = native6;
    var7 = native7;
    var _closure1_slot0 = var6;
    var _closure1_slot1 = var12;
    var _closure1_slot2 = var7;
    var1 = function _isNativeReflectConstruct() {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
 0:
 2: // try_start_0
            var2 = global;
            var3 = var2.Boolean;
            var3 = var3.prototype;
            var4 = var3.valueOf;
            var3 = var4.call;
            var8 = var2.Reflect;
            var7 = var8.construct;
            var6 = var2.Boolean;
            var5 = new Array(0);
            var2 = function() {
                var1 = undefined;
                return var1;
            };
            var2 = var7.bind(var8)(var6, var5, var2);
            var2 = var3.bind(var4)(var2);
            var2 = !var2;
            var _closure2_slot0 = var2;
 72: // try_end0
            _fun0001_ip = 76; continue _fun0001;
 74: // catch_target0
            CatchBlockStart(arg_register=1);
 76:
            var2 = function _isNativeReflectConstruct() {
                var1 = _closure2_slot0;
                var1 = !var1;
                var1 = !var1;
                return var1;
            };
            _closure1_slot37 = var2;
            var1 = undefined;
            var1 = var2.bind(var1)();
            return var1;
        }
    };
    var _closure1_slot37 = var1;
    var1 = ['categories'];
    var _closure1_slot3 = var1;
    var1 = global;
    var8 = var1.Object;
    var5 = var8.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var5.bind(var8)(var3, var1, var2);
    var1 = 0;
    var2 = var7[var1];
    var1 = undefined;
    var2 = var12.bind(var1)(var2);
    var _closure1_slot4 = var2;
    var2 = 1;
    var2 = var7[var2];
    var2 = var12.bind(var1)(var2);
    var _closure1_slot5 = var2;
    var2 = 2;
    var2 = var7[var2];
    var2 = var12.bind(var1)(var2);
    var _closure1_slot6 = var2;
    var2 = 3;
    var2 = var7[var2];
    var2 = var12.bind(var1)(var2);
    var _closure1_slot7 = var2;
    var2 = 4;
    var2 = var7[var2];
    var2 = var12.bind(var1)(var2);
    var _closure1_slot8 = var2;
    var2 = 5;
    var2 = var7[var2];
    var2 = var12.bind(var1)(var2);
    var _closure1_slot9 = var2;
    var2 = 6;
    var5 = var7[var2];
    var2 = native4;
    var2 = var2.bind(var1)(var5);
    var _closure1_slot10 = var2;
    var5 = 7;
    var5 = var7[var5];
    var5 = var6.bind(var1)(var5);
    var5 = var5.View;
    var _closure1_slot11 = var5;
    var5 = 8;
    var5 = var7[var5];
    var5 = var6.bind(var1)(var5);
    var5 = var5.isGuildReadableType;
    var _closure1_slot12 = var5;
    var5 = 9;
    var5 = var7[var5];
    var5 = var12.bind(var1)(var5);
    var _closure1_slot13 = var5;
    var5 = 10;
    var5 = var7[var5];
    var5 = var12.bind(var1)(var5);
    var _closure1_slot14 = var5;
    var5 = 11;
    var5 = var7[var5];
    var5 = var12.bind(var1)(var5);
    var _closure1_slot15 = var5;
    var5 = 12;
    var5 = var7[var5];
    var5 = var12.bind(var1)(var5);
    var _closure1_slot16 = var5;
    var5 = 13;
    var5 = var7[var5];
    var5 = var12.bind(var1)(var5);
    var _closure1_slot17 = var5;
    var5 = 14;
    var5 = var7[var5];
    var5 = var12.bind(var1)(var5);
    var _closure1_slot18 = var5;
    var5 = 15;
    var5 = var7[var5];
    var5 = var12.bind(var1)(var5);
    var _closure1_slot19 = var5;
    var5 = 16;
    var5 = var7[var5];
    var5 = var12.bind(var1)(var5);
    var _closure1_slot20 = var5;
    var5 = 17;
    var5 = var7[var5];
    var5 = var6.bind(var1)(var5);
    var8 = var5.AnalyticEvents;
    var _closure1_slot21 = var8;
    var8 = var5.UserNotificationSettings;
    var _closure1_slot22 = var8;
    var8 = var5.ChannelTypes;
    var _closure1_slot23 = var8;
    var8 = var5.NotificationSettingsSections;
    var _closure1_slot24 = var8;
    var8 = var5.SettingsPaneTypes;
    var _closure1_slot25 = var8;
    var8 = var5.MAX_MEMBERS_NOTIFY_ALL_MESSAGES;
    var _closure1_slot26 = var8;
    var8 = var5.GuildFeatures;
    var _closure1_slot27 = var8;
    var8 = var5.HighlightSettings;
    var _closure1_slot28 = var8;
    var8 = var5.HelpdeskArticles;
    var _closure1_slot29 = var8;
    var5 = var5.EMPTY_STRING_SNOWFLAKE_ID;
    var _closure1_slot30 = var5;
    var5 = 18;
    var5 = var7[var5];
    var5 = var6.bind(var1)(var5);
    var8 = var5.jsx;
    var _closure1_slot31 = var8;
    var8 = var5.jsxs;
    var _closure1_slot32 = var8;
    var5 = var5.Fragment;
    var _closure1_slot33 = var5;
    var5 = 19;
    var5 = var7[var5];
    var9 = var6.bind(var1)(var5);
    var8 = var9.createLegacyClassComponentStyles;
    var5 = {};
    var10 = {'height': 16, 'width': 16, 'opacity': 0.6};
    var5['channelIcon'] = var10;
    var10 = {'flexDirection': 'row', 'alignItems': 'center'};
    var5['channelOverrideType'] = var10;
    var10 = {};
    var11 = 'right';
    var10['textAlign'] = var11;
    var5['channelOverrideTypeText'] = var10;
    var10 = {'fontSize': 12, 'color': null, 'paddingHorizontal': 12, 'marginTop': 4};
    var11 = 20;
    var13 = var7[var11];
    var13 = var12.bind(var1)(var13);
    var13 = var13.unsafe_rawColors;
    var13 = var13.BLUE_345;
    var10['color'] = var13;
    var5['highlightsLearnMore'] = var10;
    var10 = {'height': 1, 'backgroundColor': null, 'marginVertical': 24};
    var11 = var7[var11];
    var11 = var12.bind(var1)(var11);
    var11 = var11.colors;
    var11 = var11.BORDER_SUBTLE;
    var10['backgroundColor'] = var11;
    var5['separator'] = var10;
    var5 = var8.bind(var9)(var5);
    var _closure1_slot34 = var5;
    var5 = var2.PureComponent;
    var2 = function(arg1) {
        var4 = function NotificationSettings(arg1) {
            _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
 0:
                var5 = this;
                var13 = 0;
                var1 = copyRestArgs(var13);
                var8 = _closure1_slot5;
                var3 = _closure2_slot0;
                var4 = undefined;
                var8 = var8.bind(var4)(var5, var3);
                var10 = new Array(0);
                var13 = var10;
                var12 = var1;
                var11 = 0;
                var1 = arraySpread(var13, var12, var11);
                var1 = _closure1_slot8;
                var9 = var1.bind(var4)(var3);
                var3 = _closure1_slot7;
                var1 = _closure1_slot37;
                var1 = var1.bind(var4)();
                if(var1) { _fun0002_ip = 86; continue _fun0002 }
 73:
                var1 = var9.apply;
                var1 = var1.bind(var9)(var5, var10);
                _fun0002_ip = 120; continue _fun0002;
 86:
                var7 = global;
                var8 = var7.Reflect;
                var7 = var8.construct;
                var6 = _closure1_slot8;
                var6 = var6.bind(var4)(var5);
                var6 = var6.constructor;
                var1 = var7.bind(var8)(var9, var10, var6);
 120:
                var1 = var3.bind(var4)(var5, var1);
                var _closure3_slot0 = var1;
                var3 = function() {
                    _fun0003: for(var _fun0003_ip = 0; ; ) switch(_fun0003_ip) {
 0:
                        var1 = _closure3_slot0;
                        var1 = var1.props;
                        var5 = var1.guildId;
                        var1 = var1.muted;
                        var3 = _closure1_slot1;
                        var9 = _closure1_slot2;
                        if(var1) { _fun0003_ip = 130; continue _fun0003 }
 37:
                        var2 = 21;
                        var2 = var9[var2];
                        var11 = undefined;
                        var10 = var3.bind(var11)(var2);
                        var8 = var10.openLazy;
                        var4 = _closure1_slot0;
                        var2 = 23;
                        var2 = var9[var2];
                        var7 = var4.bind(var11)(var2);
                        var2 = 22;
                        var4 = var9[var2];
                        var2 = var9.paths;
                        var7 = var7.bind(var11)(var4, var2);
                        var2 = global;
                        var2 = var2.HermesInternal;
                        var4 = var2.concat;
                        var2 = 'muteSettings';
                        var4 = var4.bind(var2)(var5);
                        var2 = {};
                        var2['guildId'] = var5;
                        var2 = var8.bind(var10)(var7, var4, var2);
                        _fun0003_ip = 203; continue _fun0003;
 130:
                        var2 = 24;
                        var2 = var9[var2];
                        var8 = undefined;
                        var4 = var3.bind(var8)(var2);
                        var3 = var4.updateGuildNotificationSettings;
                        var2 = {};
                        var7 = !var1;
                        var2['muted'] = var7;
                        var7 = _closure1_slot0;
                        var6 = 25;
                        var6 = var9[var6];
                        var6 = var7.bind(var8)(var6);
                        var7 = var6.NotificationLabel;
                        var6 = var7.muted;
                        var1 = !var1;
                        var1 = var6.bind(var7)(var1);
                        var1 = var3.bind(var4)(var5, var2, var1);
 203:
                        var1 = undefined;
                        return var1;
                    }
                };
                var1['handleMutePress'] = var3;
                var3 = function(arg1, arg2, arg3) {
                    var3 = _closure1_slot1;
                    var2 = _closure1_slot2;
                    var1 = 24;
                    var2 = var2[var1];
                    var1 = undefined;
                    var6 = var3.bind(var1)(var2);
                    var5 = var6.updateGuildNotificationSettings;
                    var2 = _closure3_slot0;
                    var2 = var2.props;
                    var4 = var2.guildId;
                    var3 = {};
                    var7 = arg2;
                    var2 = arg1;
                    var3[var2] = var7;
                    var2 = arg3;
                    var2 = var5.bind(var6)(var4, var3, var2);
                    return var1;
                };
                var1['handleToggleChange'] = var3;
                var3 = function(arg1) {
                    var8 = arg1;
                    var4 = _closure1_slot1;
                    var9 = _closure1_slot2;
                    var1 = 24;
                    var3 = var9[var1];
                    var1 = undefined;
                    var6 = var4.bind(var1)(var3);
                    var5 = var6.updateGuildNotificationSettings;
                    var3 = _closure3_slot0;
                    var3 = var3.props;
                    var4 = var3.guildId;
                    var3 = {};
                    var3['message_notifications'] = var8;
                    var7 = _closure1_slot0;
                    var2 = 25;
                    var2 = var9[var2];
                    var2 = var7.bind(var1)(var2);
                    var7 = var2.NotificationLabel;
                    var2 = var7.notifications;
                    var2 = var2.bind(var7)(var8);
                    var2 = var5.bind(var6)(var4, var3, var2);
                    return var1;
                };
                var1['handleTypeChange'] = var3;
                var3 = function() {
                    var1 = _closure3_slot0;
                    var1 = var1.props;
                    var5 = var1.guildId;
                    var4 = var1.navigation;
                    var3 = var4.push;
                    var1 = _closure1_slot24;
                    var2 = var1.ADD_OVERRIDE;
                    var1 = {};
                    var1['guildId'] = var5;
                    var1 = var3.bind(var4)(var2, var1);
                    var1 = undefined;
                    return var1;
                };
                var1['handleAddOverride'] = var3;
                var2 = function(arg1) {
                    var1 = _closure3_slot0;
                    var1 = var1.props;
                    var4 = var1.navigation;
                    var3 = var4.push;
                    var1 = _closure1_slot24;
                    var2 = var1.CHANNEL_OVERRIDE;
                    var1 = {};
                    var5 = arg1;
                    var1['channelId'] = var5;
                    var1 = var3.bind(var4)(var2, var1);
                    var1 = undefined;
                    return var1;
                };
                var1['handleChannelSelect'] = var2;
                return var1;
            }
        };
        var _closure2_slot0 = var4;
        var5 = _closure1_slot9;
        var3 = undefined;
        var2 = arg1;
        var2 = var5.bind(var3)(var4, var2);
        var2 = _closure1_slot6;
        var5 = {};
        var1 = 'componentDidMount';
        var5['key'] = var1;
        var1 = function value() {
            var3 = _closure1_slot1;
            var2 = _closure1_slot2;
            var1 = 26;
            var2 = var2[var1];
            var1 = undefined;
            var5 = var3.bind(var1)(var2);
            var4 = var5.trackWithMetadata;
            var2 = _closure1_slot21;
            var3 = var2.SETTINGS_PANE_VIEWED;
            var2 = {};
            var7 = 'guild';
            var2['settings_type'] = var7;
            var6 = _closure1_slot25;
            var6 = var6.GUILD_NOTIFICATION_SETTINGS;
            var2['destination_pane'] = var6;
            var2 = var4.bind(var5)(var3, var2);
            return var1;
        };
        var5['value'] = var1;
        var1 = new Array(8);
        var1[0] = var5;
        var5 = {};
        var7 = 'renderServerSettings';
        var5['key'] = var7;
        var7 = function value() {
            _fun0004: for(var _fun0004_ip = 0; ; ) switch(_fun0004_ip) {
 0:
                var13 = this;
                var _closure3_slot0 = var13;
                var1 = var13.props;
                var12 = var1.messageNotifications;
                var15 = var1.muted;
                var19 = var1.guildMemberCount;
                var1 = var1.shouldUseNewNotificationSystem;
                var3 = _closure1_slot34;
                var2 = var13.context;
                var5 = undefined;
                var10 = var3.bind(var5)(var2);
                var4 = _closure1_slot32;
                if(var1) { _fun0004_ip = 704; continue _fun0004 }
 67:
                var21 = _closure1_slot0;
                var11 = _closure1_slot2;
                var6 = 30;
                var1 = var11[var6];
                var1 = var21.bind(var5)(var1);
                var2 = var1.FormRadioGroup;
                var1 = {};
                var20 = 31;
                var3 = var11[var20];
                var3 = var21.bind(var5)(var3);
                var9 = var3.intl;
                var8 = var9.string;
                var3 = var11[var20];
                var3 = var21.bind(var5)(var3);
                var3 = var3.t;
                var3 = var3.lprV7e;
                var3 = var8.bind(var9)(var3);
                var1['title'] = var3;
                var1['value'] = var12;
                var3 = false;
                var1['hasIcons'] = var3;
                var9 = _closure1_slot31;
                var3 = var11[var6];
                var3 = var21.bind(var5)(var3);
                var8 = var3.FormRadioRow;
                var3 = {};
                var17 = 'right';
                var3['align'] = var17;
                var16 = var11[var20];
                var16 = var21.bind(var5)(var16);
                var18 = var16.intl;
                var16 = var18.string;
                var11 = var11[var20];
                var11 = var21.bind(var5)(var11);
                var11 = var11.t;
                var11 = var11.n/bTaW;
                var11 = var16.bind(var18)(var11);
                var3['label'] = var11;
                var3['disabled'] = var15;
                var11 = _closure1_slot22;
                var11 = var11.ALL_MESSAGES;
                var3['value'] = var11;
                var18 = null;
                var16 = var18 != var19;
                var11 = null;
                if(!var16) { _fun0004_ip = 331; continue _fun0004 }
 266:
                var16 = _closure1_slot26;
                var16 = var19 >= var16;
                var11 = null;
                if(!var16) { _fun0004_ip = 331; continue _fun0004 }
 279:
                var21 = _closure1_slot0;
                var16 = _closure1_slot2;
                var18 = var16[var20];
                var18 = var21.bind(var5)(var18);
                var19 = var18.intl;
                var18 = var19.string;
                var16 = var16[var20];
                var16 = var21.bind(var5)(var16);
                var16 = var16.t;
                var16 = var16.Dh5p5u;
                var11 = var18.bind(var19)(var16);
 331:
                var3['subLabel'] = var11;
                var11 = _closure1_slot22;
                var16 = var11.ALL_MESSAGES;
                var16 = var12 === var16;
                var3['selected'] = var16;
                var16 = function onPress() {
                    var3 = _closure3_slot0;
                    var2 = var3.handleTypeChange;
                    var1 = _closure1_slot22;
                    var1 = var1.ALL_MESSAGES;
                    var1 = var2.bind(var3)(var1);
                    var1 = undefined;
                    return var1;
                };
                var3['onPress'] = var16;
                var8 = var9.bind(var5)(var8, var3);
                var3 = new Array(5);
                var3[0] = var8;
                var9 = _closure1_slot31;
                var19 = _closure1_slot0;
                var16 = _closure1_slot2;
                var8 = var16[var6];
                var8 = var19.bind(var5)(var8);
                var18 = var8.FormDivider;
                var8 = {};
                var8 = var9.bind(var5)(var18, var8);
                var3[1] = var8;
                var8 = var16[var6];
                var8 = var19.bind(var5)(var8);
                var18 = var8.FormRadioRow;
                var8 = {};
                var8['align'] = var17;
                var21 = var16[var20];
                var21 = var19.bind(var5)(var21);
                var24 = var21.intl;
                var23 = var24.format;
                var21 = var16[var20];
                var21 = var19.bind(var5)(var21);
                var21 = var21.t;
                var22 = var21.L2hmY2;
                var21 = {};
                var21 = var23.bind(var24)(var22, var21);
                var8['label'] = var21;
                var21 = var11.ONLY_MENTIONS;
                var8['value'] = var21;
                var8['disabled'] = var15;
                var21 = function onPress() {
                    var3 = _closure3_slot0;
                    var2 = var3.handleTypeChange;
                    var1 = _closure1_slot22;
                    var1 = var1.ONLY_MENTIONS;
                    var1 = var2.bind(var3)(var1);
                    var1 = undefined;
                    return var1;
                };
                var8['onPress'] = var21;
                var21 = var11.ONLY_MENTIONS;
                var21 = var12 === var21;
                var8['selected'] = var21;
                var8 = var9.bind(var5)(var18, var8);
                var3[2] = var8;
                var8 = var16[var6];
                var8 = var19.bind(var5)(var8);
                var18 = var8.FormDivider;
                var8 = {};
                var8 = var9.bind(var5)(var18, var8);
                var3[3] = var8;
                var6 = var16[var6];
                var6 = var19.bind(var5)(var6);
                var8 = var6.FormRadioRow;
                var6 = {};
                var6['align'] = var17;
                var17 = var16[var20];
                var17 = var19.bind(var5)(var17);
                var18 = var17.intl;
                var17 = var18.string;
                var16 = var16[var20];
                var16 = var19.bind(var5)(var16);
                var16 = var16.t;
                var16 = var16.CtVGyc;
                var16 = var17.bind(var18)(var16);
                var6['label'] = var16;
                var16 = var11.NO_MESSAGES;
                var6['value'] = var16;
                var6['disabled'] = var15;
                var14 = function onPress() {
                    var3 = _closure3_slot0;
                    var2 = var3.handleTypeChange;
                    var1 = _closure1_slot22;
                    var1 = var1.NO_MESSAGES;
                    var1 = var2.bind(var3)(var1);
                    var1 = undefined;
                    return var1;
                };
                var6['onPress'] = var14;
                var11 = var11.NO_MESSAGES;
                var11 = var12 === var11;
                var6['selected'] = var11;
                var6 = var9.bind(var5)(var8, var6);
                var3[4] = var6;
                var1['children'] = var3;
                var1 = var4.bind(var5)(var2, var1);
                _fun0004_ip = 951; continue _fun0004;
 704:
                var3 = _closure1_slot33;
                var2 = {};
                var9 = _closure1_slot11;
                var6 = {};
                var8 = {};
                var11 = 12;
                var8['marginHorizontal'] = var11;
                var6['style'] = var8;
                var8 = _closure1_slot31;
                var12 = _closure1_slot0;
                var14 = _closure1_slot2;
                var7 = 27;
                var7 = var14[var7];
                var7 = var12.bind(var5)(var7);
                var11 = var7.NotificationSettingsGuildPresets;
                var7 = {};
                var15 = var13.props;
                var15 = var15.guildId;
                var7['guildId'] = var15;
                var11 = var8.bind(var5)(var11, var7);
                var7 = new Array(3);
                var7[0] = var11;
                var11 = 28;
                var11 = var14[var11];
                var11 = var12.bind(var5)(var11);
                var16 = var11.NotificationSettingsGuildMessageNotification;
                var11 = {};
                var17 = {};
                var15 = 24;
                var17['marginTop'] = var15;
                var11['style'] = var17;
                var17 = var13.props;
                var17 = var17.guildId;
                var11['guildId'] = var17;
                var11 = var8.bind(var5)(var16, var11);
                var7[1] = var11;
                var11 = 29;
                var11 = var14[var11];
                var11 = var12.bind(var5)(var11);
                var12 = var11.NotificationSettingsGuildMessageUnread;
                var11 = {};
                var14 = {};
                var14['marginTop'] = var15;
                var11['style'] = var14;
                var13 = var13.props;
                var13 = var13.guildId;
                var11['guildId'] = var13;
                var11 = var8.bind(var5)(var12, var11);
                var7[2] = var11;
                var6['children'] = var7;
                var7 = var4.bind(var5)(var9, var6);
                var6 = new Array(2);
                var6[0] = var7;
                var7 = {};
                var10 = var10.separator;
                var7['style'] = var10;
                var7 = var8.bind(var5)(var9, var7);
                var6[1] = var7;
                var2['children'] = var6;
                var1 = var4.bind(var5)(var3, var2);
 951:
                return var1;
            }
        };
        var5['value'] = var7;
        var1[1] = var5;
        var5 = {};
        var7 = 'renderNotificationOptions';
        var5['key'] = var7;
        var7 = function value() {
            _fun0005: for(var _fun0005_ip = 0; ; ) switch(_fun0005_ip) {
 0:
                var1 = this;
                var _closure3_slot0 = var1;
                var3 = _closure1_slot34;
                var2 = var1.context;
                var4 = undefined;
                var24 = var3.bind(var4)(var2);
                var1 = var1.props;
                var14 = var1.muted;
                var11 = var1.suppressEveryone;
                var18 = var1.suppressRoles;
                var15 = var1.mobilePush;
                var17 = var1.muteEvents;
                var19 = var1.notifyHighlights;
                var1 = var1.guildId;
                var _closure3_slot1 = var1;
                var3 = _closure1_slot32;
                var2 = _closure1_slot33;
                var1 = {};
                var22 = _closure1_slot0;
                var16 = _closure1_slot2;
                var10 = 30;
                var5 = var16[var10];
                var5 = var22.bind(var4)(var5);
                var6 = var5.FormSection;
                var5 = {};
                var7 = {};
                var12 = _closure1_slot31;
                var8 = var16[var10];
                var8 = var22.bind(var4)(var8);
                var21 = var8.FormHint;
                var8 = {};
                var20 = 31;
                var23 = var16[var20];
                var23 = var22.bind(var4)(var23);
                var26 = var23.intl;
                var25 = var26.string;
                var23 = var16[var20];
                var23 = var22.bind(var4)(var23);
                var23 = var23.t;
                var23 = var23.Vw/Xn5;
                var23 = var25.bind(var26)(var23);
                var8['children'] = var23;
                var21 = var12.bind(var4)(var21, var8);
                var8 = new Array(2);
                var8[0] = var21;
                var21 = 32;
                var21 = var16[var21];
                var21 = var22.bind(var4)(var21);
                var23 = var21.LegacyText;
                var21 = {};
                var24 = var24.highlightsLearnMore;
                var21['style'] = var24;
                var24 = 'link';
                var21['accessibilityRole'] = var24;
                var24 = function onPress() {
                    var6 = _closure1_slot1;
                    var7 = _closure1_slot2;
                    var2 = 33;
                    var2 = var7[var2];
                    var5 = undefined;
                    var3 = var6.bind(var5)(var2);
                    var2 = var3.openURL;
                    var4 = 34;
                    var4 = var7[var4];
                    var5 = var6.bind(var5)(var4);
                    var4 = var5.getArticleURL;
                    var1 = _closure1_slot29;
                    var1 = var1.HIGHLIGHTS;
                    var1 = var4.bind(var5)(var1);
                    var1 = var2.bind(var3)(var1);
                    return var1;
                };
                var21['onPress'] = var24;
                var24 = var16[var20];
                var24 = var22.bind(var4)(var24);
                var26 = var24.intl;
                var25 = var26.string;
                var24 = var16[var20];
                var24 = var22.bind(var4)(var24);
                var24 = var24.t;
                var24 = var24.PRBn9P;
                var24 = var25.bind(var26)(var24);
                var21['children'] = var24;
                var21 = var12.bind(var4)(var23, var21);
                var8[1] = var21;
                var7['children'] = var8;
                var7 = var3.bind(var4)(var2, var7);
                var5['hint'] = var7;
                var7 = var16[var10];
                var7 = var22.bind(var4)(var7);
                var8 = var7.FormSwitchRow;
                var7 = {};
                var21 = var16[var20];
                var21 = var22.bind(var4)(var21);
                var25 = var21.intl;
                var24 = var25.format;
                var21 = var16[var20];
                var21 = var22.bind(var4)(var21);
                var21 = var21.t;
                var23 = var21.OWiWAg;
                var21 = {};
                var21 = var24.bind(var25)(var23, var21);
                var7['label'] = var21;
                var7['value'] = var11;
                var11 = function onValueChange(arg1) {
                    var6 = arg1;
                    var5 = _closure3_slot0;
                    var4 = var5.handleToggleChange;
                    var3 = _closure1_slot0;
                    var2 = _closure1_slot2;
                    var1 = 25;
                    var2 = var2[var1];
                    var1 = undefined;
                    var2 = var3.bind(var1)(var2);
                    var3 = var2.NotificationLabel;
                    var2 = var3.suppressEveryone;
                    var3 = var2.bind(var3)(var6);
                    var2 = 'suppress_everyone';
                    var2 = var4.bind(var5)(var2, var6, var3);
                    return var1;
                };
                var7['onValueChange'] = var11;
                var8 = var12.bind(var4)(var8, var7);
                var7 = new Array(3);
                var7[0] = var8;
                var8 = var16[var10];
                var8 = var22.bind(var4)(var8);
                var11 = var8.FormSwitchRow;
                var8 = {};
                var21 = var16[var20];
                var21 = var22.bind(var4)(var21);
                var24 = var21.intl;
                var23 = var24.string;
                var21 = var16[var20];
                var21 = var22.bind(var4)(var21);
                var21 = var21.t;
                var21 = var21.O/QdoK;
                var21 = var23.bind(var24)(var21);
                var8['label'] = var21;
                var8['value'] = var18;
                var18 = function onValueChange(arg1) {
                    var6 = arg1;
                    var5 = _closure3_slot0;
                    var4 = var5.handleToggleChange;
                    var3 = _closure1_slot0;
                    var2 = _closure1_slot2;
                    var1 = 25;
                    var2 = var2[var1];
                    var1 = undefined;
                    var2 = var3.bind(var1)(var2);
                    var3 = var2.NotificationLabel;
                    var2 = var3.suppressRoles;
                    var3 = var2.bind(var3)(var6);
                    var2 = 'suppress_roles';
                    var2 = var4.bind(var5)(var2, var6, var3);
                    return var1;
                };
                var8['onValueChange'] = var18;
                var8 = var12.bind(var4)(var11, var8);
                var7[1] = var8;
                var8 = var16[var10];
                var8 = var22.bind(var4)(var8);
                var11 = var8.FormSwitchRow;
                var8 = {};
                var8['disabled'] = var14;
                var18 = var16[var20];
                var18 = var22.bind(var4)(var18);
                var21 = var18.intl;
                var18 = var21.string;
                var16 = var16[var20];
                var16 = var22.bind(var4)(var16);
                var16 = var16.t;
                var16 = var16.gPuteH;
                var16 = var18.bind(var21)(var16);
                var8['label'] = var16;
                var16 = var14;
                if(var16) { _fun0005_ip = 612; continue _fun0005 }
 598:
                var18 = _closure1_slot28;
                var18 = var18.DISABLED;
                var16 = var19 === var18;
 612:
                var8['value'] = var16;
                var16 = function onValueChange(arg1) {
                    _fun0006: for(var _fun0006_ip = 0; ; ) switch(_fun0006_ip) {
 0:
                        var2 = arg1;
                        var4 = _closure1_slot1;
                        var3 = _closure1_slot2;
                        var1 = 24;
                        var3 = var3[var1];
                        var1 = undefined;
                        var6 = var4.bind(var1)(var3);
                        var5 = var6.updateGuildNotificationSettings;
                        var4 = _closure3_slot1;
                        var3 = {};
                        var9 = _closure1_slot28;
                        if(var2) { _fun0006_ip = 58; continue _fun0006 }
 50:
                        var8 = var9.ENABLED;
                        _fun0006_ip = 64; continue _fun0006;
 58:
                        var8 = var9.DISABLED;
 64:
                        var3['notify_highlights'] = var8;
                        var8 = _closure1_slot0;
                        var9 = _closure1_slot2;
                        var7 = 25;
                        var7 = var9[var7];
                        var7 = var8.bind(var1)(var7);
                        var8 = var7.NotificationLabel;
                        var7 = var8.highlights;
                        var2 = !var2;
                        var2 = var7.bind(var8)(var2);
                        var2 = var5.bind(var6)(var4, var3, var2);
                        return var1;
                    }
                };
                var8['onValueChange'] = var16;
                var8 = var12.bind(var4)(var11, var8);
                var7[2] = var8;
                var5['children'] = var7;
                var6 = var3.bind(var4)(var6, var5);
                var5 = new Array(2);
                var5[0] = var6;
                var8 = _closure1_slot32;
                var19 = _closure1_slot0;
                var16 = _closure1_slot2;
                var6 = var16[var10];
                var6 = var19.bind(var4)(var6);
                var7 = var6.FormSection;
                var6 = {};
                var12 = _closure1_slot31;
                var9 = var16[var10];
                var9 = var19.bind(var4)(var9);
                var11 = var9.FormSwitchRow;
                var9 = {};
                var18 = var16[var20];
                var18 = var19.bind(var4)(var18);
                var22 = var18.intl;
                var21 = var22.string;
                var18 = var16[var20];
                var18 = var19.bind(var4)(var18);
                var18 = var18.t;
                var18 = var18.ONG3Y2;
                var18 = var21.bind(var22)(var18);
                var9['label'] = var18;
                var9['value'] = var17;
                var17 = function onValueChange(arg1) {
                    var6 = arg1;
                    var5 = _closure3_slot0;
                    var4 = var5.handleToggleChange;
                    var3 = _closure1_slot0;
                    var2 = _closure1_slot2;
                    var1 = 25;
                    var2 = var2[var1];
                    var1 = undefined;
                    var2 = var3.bind(var1)(var2);
                    var3 = var2.NotificationLabel;
                    var2 = var3.mutedEvents;
                    var3 = var2.bind(var3)(var6);
                    var2 = 'mute_scheduled_events';
                    var2 = var4.bind(var5)(var2, var6, var3);
                    return var1;
                };
                var9['onValueChange'] = var17;
                var11 = var12.bind(var4)(var11, var9);
                var9 = new Array(3);
                var9[0] = var11;
                var11 = var16[var10];
                var11 = var19.bind(var4)(var11);
                var17 = var11.FormDivider;
                var11 = {};
                var11 = var12.bind(var4)(var17, var11);
                var9[1] = var11;
                var10 = var16[var10];
                var10 = var19.bind(var4)(var10);
                var11 = var10.FormSwitchRow;
                var10 = {};
                var10['disabled'] = var14;
                var17 = var16[var20];
                var17 = var19.bind(var4)(var17);
                var18 = var17.intl;
                var17 = var18.string;
                var16 = var16[var20];
                var16 = var19.bind(var4)(var16);
                var16 = var16.t;
                var16 = var16.h1DL6+;
                var16 = var17.bind(var18)(var16);
                var10['label'] = var16;
                var14 = !var14;
                if(!var14) { _fun0005_ip = 891; continue _fun0005 }
 888:
                var14 = var15;
 891:
                var10['value'] = var14;
                var13 = function onValueChange(arg1) {
                    var6 = arg1;
                    var5 = _closure3_slot0;
                    var4 = var5.handleToggleChange;
                    var3 = _closure1_slot0;
                    var2 = _closure1_slot2;
                    var1 = 25;
                    var2 = var2[var1];
                    var1 = undefined;
                    var2 = var3.bind(var1)(var2);
                    var3 = var2.NotificationLabel;
                    var2 = var3.mobilePush;
                    var3 = var2.bind(var3)(var6);
                    var2 = 'mobile_push';
                    var2 = var4.bind(var5)(var2, var6, var3);
                    return var1;
                };
                var10['onValueChange'] = var13;
                var10 = var12.bind(var4)(var11, var10);
                var9[2] = var10;
                var6['children'] = var9;
                var6 = var8.bind(var4)(var7, var6);
                var5[1] = var6;
                var1['children'] = var5;
                var1 = var3.bind(var4)(var2, var1);
                return var1;
            }
        };
        var5['value'] = var7;
        var1[2] = var5;
        var5 = {};
        var7 = 'renderMuteSection';
        var5['key'] = var7;
        var7 = function value() {
            _fun0007: for(var _fun0007_ip = 0; ; ) switch(_fun0007_ip) {
 0:
                var6 = this;
                var1 = var6.props;
                var2 = var1.muted;
                var9 = var1.muteConfig;
                var13 = var1.guild;
                var1 = var1.shouldUseNewNotificationSystem;
                if(var1) { _fun0007_ip = 475; continue _fun0007 }
 37:
                var3 = _closure1_slot0;
                var1 = _closure1_slot2;
                var12 = 31;
                var4 = var1[var12];
                var10 = undefined;
                var4 = var3.bind(var10)(var4);
                var7 = var4.intl;
                var5 = var7.format;
                var1 = var1[var12];
                var1 = var3.bind(var10)(var1);
                var1 = var1.t;
                if(var2) { _fun0007_ip = 127; continue _fun0007 }
 89:
                var4 = var1.J+7D9P;
                var3 = {};
                var8 = null;
                var14 = var8 == var13;
                var8 = undefined;
                if(var14) { _fun0007_ip = 115; continue _fun0007 }
 110:
                var8 = var13.name;
 115:
                var3['name'] = var8;
                var3 = var5.bind(var7)(var4, var3);
                _fun0007_ip = 163; continue _fun0007;
 127:
                var4 = var1.e8hzDQ;
                var1 = {};
                var8 = null;
                var14 = var8 == var13;
                var8 = undefined;
                if(var14) { _fun0007_ip = 153; continue _fun0007 }
 148:
                var8 = var13.name;
 153:
                var1['name'] = var8;
                var3 = var5.bind(var7)(var4, var1);
 163:
                var7 = _closure1_slot31;
                var8 = _closure1_slot0;
                var1 = _closure1_slot2;
                var16 = 30;
                var4 = var1[var16];
                var4 = var8.bind(var10)(var4);
                var5 = var4.FormSection;
                var4 = {};
                var13 = var1[var16];
                var13 = var8.bind(var10)(var13);
                var14 = var13.FormHint;
                var13 = {};
                var15 = var1[var12];
                var15 = var8.bind(var10)(var15);
                var17 = var15.intl;
                var15 = var17.string;
                var12 = var1[var12];
                var12 = var8.bind(var10)(var12);
                var12 = var12.t;
                var12 = var12.8wbTQ0;
                var12 = var15.bind(var17)(var12);
                var13['children'] = var12;
                var12 = 'mute-hint';
                var12 = var7.bind(var10)(var14, var13, var12);
                var4['hint'] = var12;
                var1 = var1[var16];
                var1 = var8.bind(var10)(var1);
                var8 = var1.FormRow;
                var1 = {};
                var1['label'] = var3;
                var3 = var6.handleMutePress;
                var1['onPress'] = var3;
                var12 = null;
                if(var2) { _fun0007_ip = 357; continue _fun0007 }
 316:
                var15 = _closure1_slot31;
                var14 = _closure1_slot0;
                var13 = _closure1_slot2;
                var13 = var13[var16];
                var13 = var14.bind(var10)(var13);
                var13 = var13.FormRow;
                var14 = var13.Arrow;
                var13 = {};
                var12 = var15.bind(var10)(var14, var13);
 357:
                var1['trailing'] = var12;
                var1 = var7.bind(var10)(var8, var1);
                var4['children'] = var1;
                var1 = 'mute';
                var4 = var7.bind(var10)(var5, var4, var1);
                var1 = new Array(2);
                var1[0] = var4;
                var3 = null;
                if(!var2) { _fun0007_ip = 469; continue _fun0007 }
 396:
                var8 = _closure1_slot31;
                var7 = _closure1_slot1;
                var12 = _closure1_slot2;
                var4 = 36;
                var5 = var12[var4];
                var7 = var7.bind(var10)(var5);
                var5 = {};
                var5['muteConfig'] = var9;
                var11 = _closure1_slot0;
                var4 = var12[var4];
                var4 = var11.bind(var10)(var4);
                var4 = var4.MuteSettingType;
                var4 = var4.SERVER;
                var5['type'] = var4;
                var4 = 'muted-until';
                var3 = var8.bind(var10)(var7, var5, var4);
 469:
                var1[1] = var3;
                return var1;
 475:
                var1 = null;
                if(!var2) { _fun0007_ip = 633; continue _fun0007 }
 483:
                var5 = _closure1_slot31;
                var8 = _closure1_slot0;
                var10 = _closure1_slot2;
                var7 = 35;
                var2 = var10[var7];
                var4 = undefined;
                var2 = var8.bind(var4)(var2);
                var3 = var2.NotificationSettingsMuteBanner;
                var2 = {};
                var11 = 31;
                var12 = var10[var11];
                var12 = var8.bind(var4)(var12);
                var13 = var12.intl;
                var12 = var13.string;
                var11 = var10[var11];
                var11 = var8.bind(var4)(var11);
                var11 = var11.t;
                var11 = var11.ZSkXJS;
                var11 = var12.bind(var13)(var11);
                var2['title'] = var11;
                var7 = var10[var7];
                var8 = var8.bind(var4)(var7);
                var7 = var8.getMuteBannerSubtitleFromConfig;
                var7 = var7.bind(var8)(var9);
                var2['subtitle'] = var7;
                var7 = {'marginHorizontal': 12, 'marginBottom': 16};
                var2['style'] = var7;
                var6 = var6.handleMutePress;
                var2['onPressUnmute'] = var6;
                var1 = var5.bind(var4)(var3, var2);
 633:
                return var1;
            }
        };
        var5['value'] = var7;
        var1[3] = var5;
        var5 = {};
        var7 = 'renderChannels';
        var5['key'] = var7;
        var7 = function value() {
            var8 = this;
            var _closure3_slot0 = var8;
            var6 = _closure1_slot31;
            var4 = _closure1_slot0;
            var7 = _closure1_slot2;
            var3 = 30;
            var1 = var7[var3];
            var5 = undefined;
            var1 = var4.bind(var5)(var1);
            var10 = var1.FormSection;
            var9 = {};
            var12 = 31;
            var1 = var7[var12];
            var1 = var4.bind(var5)(var1);
            var14 = var1.intl;
            var11 = var14.string;
            var1 = var7[var12];
            var1 = var4.bind(var5)(var1);
            var1 = var1.t;
            var1 = var1.O4TIvr;
            var1 = var11.bind(var14)(var1);
            var9['title'] = var1;
            var1 = var7[var3];
            var1 = var4.bind(var5)(var1);
            var11 = var1.FormRow;
            var1 = {};
            var16 = _closure1_slot1;
            var13 = 37;
            var13 = var7[var13];
            var14 = var16.bind(var5)(var13);
            var13 = {};
            var15 = 38;
            var15 = var7[var15];
            var15 = var16.bind(var5)(var15);
            var13['source'] = var15;
            var13 = var6.bind(var5)(var14, var13);
            var1['leading'] = var13;
            var13 = var7[var12];
            var13 = var4.bind(var5)(var13);
            var14 = var13.intl;
            var13 = var14.string;
            var12 = var7[var12];
            var12 = var4.bind(var5)(var12);
            var12 = var12.t;
            var12 = var12.quib7e;
            var12 = var13.bind(var14)(var12);
            var1['label'] = var12;
            var12 = var8.handleAddOverride;
            var1['onPress'] = var12;
            var1 = var6.bind(var5)(var11, var1);
            var9['children'] = var1;
            var1 = 'override-header';
            var9 = var6.bind(var5)(var10, var9, var1);
            var1 = new Array(2);
            var1[0] = var9;
            var3 = var7[var3];
            var3 = var4.bind(var5)(var3);
            var4 = var3.FormSection;
            var3 = {};
            var7 = var8.getOverriddenChannels;
            var8 = var7.bind(var8)();
            var7 = var8.map;
            var2 = function(arg1) {
                var3 = _closure3_slot0;
                var2 = var3.renderChannel;
                var1 = arg1;
                var1 = var2.bind(var3)(var1);
                return var1;
            };
            var2 = var7.bind(var8)(var2);
            var3['children'] = var2;
            var2 = 'override-channels';
            var2 = var6.bind(var5)(var4, var3, var2);
            var1[1] = var2;
            return var1;
        };
        var5['value'] = var7;
        var1[4] = var5;
        var5 = {};
        var7 = 'renderChannel';
        var5['key'] = var7;
        var7 = function value(arg1) {
            _fun0008: for(var _fun0008_ip = 0; ; ) switch(_fun0008_ip) {
 0:
                var1 = arg1;
                var2 = this;
                var _closure3_slot0 = var2;
                var _closure3_slot1 = var1;
                var4 = _closure1_slot34;
                var3 = var2.context;
                var5 = undefined;
                var16 = var4.bind(var5)(var3);
                var6 = null;
                if(!(var6 == var1)) { _fun0008_ip = 43; continue _fun0008 }
 41:
                return var5;
 43:
                var3 = var2.props;
                var4 = var3.channelOverrides;
                var3 = var1.id;
                var3 = var4[var3];
                var8 = _closure1_slot0;
                var10 = _closure1_slot2;
                var4 = 39;
                var4 = var10[var4];
                var8 = var8.bind(var5)(var4);
                var4 = var8.getChannelIcon;
                var17 = var4.bind(var8)(var1);
                var4 = var1.parent_id;
                var4 = var6 != var4;
                var12 = undefined;
                if(!var4) { _fun0008_ip = 129; continue _fun0008 }
 109:
                var10 = _closure1_slot13;
                var8 = var10.getChannel;
                var4 = var1.parent_id;
                var12 = var8.bind(var10)(var4);
 129:
                var8 = _closure1_slot0;
                var10 = _closure1_slot2;
                var4 = 40;
                var4 = var10[var4];
                var8 = var8.bind(var5)(var4);
                var4 = var8.computeIsMuted;
                var4 = var4.bind(var8)(var3);
                if(var4) { _fun0008_ip = 399; continue _fun0008 }
 166:
                var4 = var3.message_notifications;
                var3 = _closure1_slot22;
                var3 = var3.ALL_MESSAGES;
                if(!(var3 !== var4)) { _fun0008_ip = 342; continue _fun0008 }
 189:
                var3 = _closure1_slot22;
                var3 = var3.ONLY_MENTIONS;
                if(!(var3 !== var4)) { _fun0008_ip = 282; continue _fun0008 }
 203:
                var3 = _closure1_slot22;
                var3 = var3.NO_MESSAGES;
                var15 = undefined;
                if(!(var3 === var4)) { _fun0008_ip = 456; continue _fun0008 }
 222:
                var10 = _closure1_slot0;
                var11 = _closure1_slot2;
                var3 = 31;
                var4 = var11[var3];
                var4 = var10.bind(var5)(var4);
                var8 = var4.intl;
                var4 = var8.string;
                var3 = var11[var3];
                var3 = var10.bind(var5)(var3);
                var3 = var3.t;
                var3 = var3.CtVGyc;
                var15 = var4.bind(var8)(var3);
                _fun0008_ip = 456; continue _fun0008;
 282:
                var4 = _closure1_slot0;
                var11 = _closure1_slot2;
                var3 = 31;
                var8 = var11[var3];
                var8 = var4.bind(var5)(var8);
                var10 = var8.intl;
                var8 = var10.format;
                var3 = var11[var3];
                var3 = var4.bind(var5)(var3);
                var3 = var3.t;
                var4 = var3.L2hmY2;
                var3 = {};
                var15 = var8.bind(var10)(var4, var3);
                _fun0008_ip = 456; continue _fun0008;
 342:
                var10 = _closure1_slot0;
                var11 = _closure1_slot2;
                var3 = 31;
                var4 = var11[var3];
                var4 = var10.bind(var5)(var4);
                var8 = var4.intl;
                var4 = var8.string;
                var3 = var11[var3];
                var3 = var10.bind(var5)(var3);
                var3 = var3.t;
                var3 = var3.n/bTaW;
                var15 = var4.bind(var8)(var3);
                _fun0008_ip = 456; continue _fun0008;
 399:
                var10 = _closure1_slot0;
                var11 = _closure1_slot2;
                var3 = 31;
                var4 = var11[var3];
                var4 = var10.bind(var5)(var4);
                var8 = var4.intl;
                var4 = var8.string;
                var3 = var11[var3];
                var3 = var10.bind(var5)(var3);
                var3 = var3.t;
                var3 = var3.fpKdS0;
                var15 = var4.bind(var8)(var3);
 456:
                var2 = var2.props;
                var2 = var2.shouldUseNewNotificationSystem;
                if(!var2) { _fun0008_ip = 548; continue _fun0008 }
 470:
                var8 = _closure1_slot0;
                var10 = _closure1_slot2;
                var2 = 41;
                var3 = var10[var2];
                var4 = var8.bind(var5)(var3);
                var3 = var4.presetName;
                var2 = var10[var2];
                var11 = var8.bind(var5)(var2);
                var10 = var11.presetFromSettings;
                var13 = _closure1_slot19;
                var2 = var13.resolveUnreadSetting;
                var8 = var2.bind(var13)(var1);
                var2 = var13.resolvedMessageNotifications;
                var2 = var2.bind(var13)(var1);
                var2 = var10.bind(var11)(var8, var2);
                var15 = var3.bind(var4)(var2);
 548:
                var4 = _closure1_slot31;
                var11 = _closure1_slot0;
                var8 = _closure1_slot2;
                var13 = 30;
                var2 = var8[var13];
                var2 = var11.bind(var5)(var2);
                var3 = var2.FormRow;
                var2 = {};
                var19 = _closure1_slot1;
                var18 = 37;
                var10 = var8[var18];
                var14 = var19.bind(var5)(var10);
                var10 = {};
                var18 = var8[var18];
                var18 = var19.bind(var5)(var18);
                var18 = var18.Sizes;
                var18 = var18.CUSTOM;
                var10['size'] = var18;
                var10['source'] = var17;
                var17 = var16.channelIcon;
                var10['style'] = var17;
                var10 = var4.bind(var5)(var14, var10);
                var2['leading'] = var10;
                var10 = 42;
                var8 = var8[var10];
                var17 = var11.bind(var5)(var8);
                var14 = var17.computeChannelName;
                var11 = _closure1_slot20;
                var8 = _closure1_slot18;
                var8 = var14.bind(var17)(var1, var11, var8);
                var2['label'] = var8;
                var7 = function onPress() {
                    var3 = _closure3_slot0;
                    var2 = var3.handleChannelSelect;
                    var1 = _closure3_slot1;
                    var1 = var1.id;
                    var1 = var2.bind(var3)(var1);
                    return var1;
                };
                var2['onPress'] = var7;
                var7 = var6 != var12;
                var6 = null;
                if(!var7) { _fun0008_ip = 743; continue _fun0008 }
 705:
                var8 = _closure1_slot0;
                var7 = _closure1_slot2;
                var7 = var7[var10];
                var11 = var8.bind(var5)(var7);
                var10 = var11.computeChannelName;
                var8 = _closure1_slot20;
                var7 = _closure1_slot18;
                var6 = var10.bind(var11)(var12, var8, var7);
 743:
                var2['subLabel'] = var6;
                var8 = _closure1_slot32;
                var7 = _closure1_slot11;
                var6 = {};
                var10 = var16.channelOverrideType;
                var6['style'] = var10;
                var12 = _closure1_slot31;
                var11 = _closure1_slot0;
                var10 = _closure1_slot2;
                var9 = 43;
                var9 = var10[var9];
                var9 = var11.bind(var5)(var9);
                var14 = var9.Text;
                var9 = {'style': null, 'variant': 'text-md/medium', 'color': 'text-muted'};
                var16 = var16.channelOverrideTypeText;
                var9['style'] = var16;
                var9['children'] = var15;
                var14 = var12.bind(var5)(var14, var9);
                var9 = new Array(2);
                var9[0] = var14;
                var10 = var10[var13];
                var10 = var11.bind(var5)(var10);
                var10 = var10.FormRow;
                var11 = var10.Arrow;
                var10 = {};
                var10 = var12.bind(var5)(var11, var10);
                var9[1] = var10;
                var6['children'] = var9;
                var6 = var8.bind(var5)(var7, var6);
                var2['trailing'] = var6;
                var1 = var1.id;
                var1 = var4.bind(var5)(var3, var2, var1);
                return var1;
            }
        };
        var5['value'] = var7;
        var1[5] = var5;
        var5 = {};
        var7 = 'render';
        var5['key'] = var7;
        var7 = function value() {
            _fun0009: for(var _fun0009_ip = 0; ; ) switch(_fun0009_ip) {
 0:
                var7 = this;
                var1 = var7.props;
                var1 = var1.guild;
                var2 = null;
                if(!(var2 != var1)) { _fun0009_ip = 51; continue _fun0009 }
 19:
                var4 = var1.features;
                var3 = var4.has;
                var1 = _closure1_slot27;
                var1 = var1.HUB;
                var1 = var3.bind(var4)(var1);
                if(var1) { _fun0009_ip = 166; continue _fun0009 }
 51:
                var5 = _closure1_slot32;
                var3 = _closure1_slot0;
                var4 = _closure1_slot2;
                var1 = 30;
                var1 = var4[var1];
                var4 = undefined;
                var1 = var3.bind(var4)(var1);
                var3 = var1.Form;
                var1 = {};
                var6 = var7.renderMuteSection;
                var8 = var6.bind(var7)();
                var6 = new Array(4);
                var6[0] = var8;
                var8 = var7.renderServerSettings;
                var8 = var8.bind(var7)();
                var6[1] = var8;
                var8 = var7.renderNotificationOptions;
                var8 = var8.bind(var7)();
                var6[2] = var8;
                var8 = var7.renderChannels;
                var8 = var8.bind(var7)();
                var6[3] = var8;
                var1['children'] = var6;
                var1 = var5.bind(var4)(var3, var1);
                _fun0009_ip = 220; continue _fun0009;
 166:
                var5 = _closure1_slot31;
                var3 = _closure1_slot0;
                var4 = _closure1_slot2;
                var2 = 30;
                var2 = var4[var2];
                var4 = undefined;
                var2 = var3.bind(var4)(var2);
                var3 = var2.Form;
                var2 = {};
                var6 = var7.renderMuteSection;
                var6 = var6.bind(var7)();
                var2['children'] = var6;
                var1 = var5.bind(var4)(var3, var2);
 220:
                return var1;
            }
        };
        var5['value'] = var7;
        var1[6] = var5;
        var5 = {};
        var7 = 'getOverriddenChannels';
        var5['key'] = var7;
        var6 = function value() {
            var8 = this;
            var2 = var8.props;
            var4 = var2.channels;
            var7 = var2.channelOverrides;
            var2 = global;
            var5 = var2.Set;
            var6 = _closure1_slot0;
            var3 = _closure1_slot2;
            var2 = 44;
            var3 = var3[var2];
            var2 = undefined;
            var6 = var6.bind(var2)(var3);
            var3 = var6.filterOverrides;
            var2 = {};
            var9 = false;
            var2['ignoreNotificationSetting'] = var9;
            var9 = var8.props;
            var9 = var9.shouldUseNewNotificationSystem;
            var2['ignoreMute'] = var9;
            var8 = var8.props;
            var8 = var8.shouldUseNewNotificationSystem;
            var8 = !var8;
            var2['ignoreUnreadSetting'] = var8;
            var11 = var3.bind(var6)(var7, var2);
            var3 = var5.prototype;
            var3 = Object.create(var3, {constructor: {value: var5}});
            var12 = var3;
            var2 = new var12[var5](var11, var10);
            var2 = var2 instanceof Object ? var2 : var3;
            var _closure3_slot0 = var2;
            var3 = var4.map;
            var2 = function(arg1) {
                _fun0010: for(var _fun0010_ip = 0; ; ) switch(_fun0010_ip) {
 0:
                    var1 = arg1;
                    var2 = var1.channel;
                    var4 = _closure3_slot0;
                    var3 = var4.has;
                    var1 = var2.id;
                    var3 = var3.bind(var4)(var1);
                    var1 = null;
                    if(!var3) { _fun0010_ip = 38; continue _fun0010 }
 35:
                    var1 = var2;
 38:
                    return var1;
                }
            };
            var3 = var3.bind(var4)(var2);
            var2 = var3.filter;
            var1 = function(arg1) {
                var1 = arg1;
                return var1;
            };
            var1 = var2.bind(var3)(var1);
            return var1;
        };
        var5['value'] = var6;
        var1[7] = var5;
        var1 = var2.bind(var3)(var4, var1);
        return var1;
    };
    var2 = var2.bind(var1)(var5);
    var _closure1_slot35 = var2;
    var5 = 45;
    var5 = var7[var5];
    var5 = var6.bind(var1)(var5);
    var5 = var5.ThemeContext;
    var2['contextType'] = var5;
    var5 = function ConnectedNotificationSettings(arg1) {
        var2 = arg1;
        var14 = var2.guildId;
        var _closure2_slot0 = var14;
        var7 = _closure1_slot0;
        var9 = _closure1_slot2;
        var2 = 46;
        var2 = var9[var2];
        var4 = undefined;
        var3 = var7.bind(var4)(var2);
        var2 = var3.useNavigation;
        var12 = var2.bind(var3)();
        var2 = 47;
        var2 = var9[var2];
        var8 = var7.bind(var4)(var2);
        var6 = var8.useStateFromStoresObject;
        var2 = _closure1_slot19;
        var3 = new Array(4);
        var3[0] = var2;
        var2 = _closure1_slot16;
        var3[1] = var2;
        var2 = _closure1_slot14;
        var3[2] = var2;
        var2 = _closure1_slot15;
        var3[3] = var2;
        var2 = function() {
            var1 = {};
            var5 = _closure1_slot16;
            var3 = var5.getGuild;
            var4 = _closure2_slot0;
            var3 = var3.bind(var5)(var4);
            var1['guild'] = var3;
            var3 = _closure1_slot19;
            var5 = var3.isSuppressEveryoneEnabled;
            var5 = var5.bind(var3)(var4);
            var1['suppressEveryone'] = var5;
            var5 = var3.isSuppressRolesEnabled;
            var5 = var5.bind(var3)(var4);
            var1['suppressRoles'] = var5;
            var5 = var3.isMobilePushEnabled;
            var5 = var5.bind(var3)(var4);
            var1['mobilePush'] = var5;
            var5 = var3.isMuteScheduledEventsEnabled;
            var5 = var5.bind(var3)(var4);
            var1['muteEvents'] = var5;
            var5 = var3.isMuted;
            var5 = var5.bind(var3)(var4);
            var1['muted'] = var5;
            var5 = var3.getMuteConfig;
            var5 = var5.bind(var3)(var4);
            var1['muteConfig'] = var5;
            var5 = var3.getMessageNotifications;
            var5 = var5.bind(var3)(var4);
            var1['messageNotifications'] = var5;
            var5 = var3.getChannelOverrides;
            var5 = var5.bind(var3)(var4);
            var1['channelOverrides'] = var5;
            var6 = _closure1_slot14;
            var5 = var6.getCategories;
            var5 = var5.bind(var6)(var4);
            var1['categories'] = var5;
            var5 = _closure1_slot15;
            var2 = var5.getMemberCount;
            var2 = var2.bind(var5)(var4);
            var1['guildMemberCount'] = var2;
            var2 = var3.getNotifyHighlights;
            var2 = var2.bind(var3)(var4);
            var1['notifyHighlights'] = var2;
            return var1;
        };
        var6 = var6.bind(var8)(var3, var2);
        var8 = var6.categories;
        var _closure2_slot1 = var8;
        var3 = _closure1_slot4;
        var2 = _closure1_slot3;
        var10 = var3.bind(var4)(var6, var2);
        var6 = _closure1_slot10;
        var3 = var6.useMemo;
        var2 = new Array(1);
        var2[0] = var8;
        var1 = function() {
            var2 = _closure1_slot1;
            var3 = _closure1_slot2;
            var1 = 48;
            var1 = var3[var1];
            var5 = undefined;
            var4 = var2.bind(var5)(var1);
            var3 = _closure2_slot1;
            var2 = var3._categories;
            var1 = function(arg1) {
                _fun0011: for(var _fun0011_ip = 0; ; ) switch(_fun0011_ip) {
 0:
                    var1 = arg1;
                    var1 = var1.channel;
                    var3 = var1.type;
                    var4 = _closure1_slot12;
                    var1 = undefined;
                    var1 = var4.bind(var1)(var3);
                    if(var1) { _fun0011_ip = 44; continue _fun0011 }
 30:
                    var2 = _closure1_slot23;
                    var2 = var2.GUILD_CATEGORY;
                    var1 = var3 === var2;
 44:
                    return var1;
                }
            };
            var1 = var4.bind(var5)(var2, var3, var1);
            return var1;
        };
        var13 = var3.bind(var6)(var1, var2);
        var1 = 44;
        var1 = var9[var1];
        var3 = var7.bind(var4)(var1);
        var2 = var3.useShouldUseNewNotificationSystem;
        var1 = 'NotificationSettingsModalNative';
        var11 = var2.bind(var3)(var1);
        var3 = _closure1_slot32;
        var1 = 49;
        var1 = var9[var1];
        var1 = var7.bind(var4)(var1);
        var2 = var1.RedesignCompat;
        var1 = {};
        var8 = _closure1_slot31;
        var6 = _closure1_slot35;
        var5 = {};
        var5['guildId'] = var14;
        var5['channels'] = var13;
        var5['navigation'] = var12;
        var5['shouldUseNewNotificationSystem'] = var11;
        var16 = var5;
        var15 = var10;
        var10 = copyDataProperties(var16, var15);
        var6 = var8.bind(var4)(var6, var5);
        var5 = new Array(2);
        var5[0] = var6;
        var6 = 50;
        var6 = var9[var6];
        var6 = var7.bind(var4)(var6);
        var7 = var6.NavScrim;
        var6 = {};
        var6 = var8.bind(var4)(var7, var6);
        var5[1] = var6;
        var1['children'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var _closure1_slot36 = var5;
    var5 = 55;
    var5 = var7[var5];
    var7 = var6.bind(var1)(var5);
    var6 = var7.fileFinishedImporting;
    var5 = 'modules/notification_settings/native/NotificationSettingsModal.native.tsx';
    var5 = var6.bind(var7)(var5);
    var4 = function NotificationSettingsModal() {
        _fun0012: for(var _fun0012_ip = 0; ; ) switch(_fun0012_ip) {
 0:
            var2 = _closure1_slot0;
            var6 = _closure1_slot2;
            var3 = 47;
            var3 = var6[var3];
            var4 = undefined;
            var9 = var2.bind(var4)(var3);
            var7 = var9.useStateFromStores;
            var3 = _closure1_slot17;
            var5 = new Array(1);
            var5[0] = var3;
            var3 = function() {
                var2 = _closure1_slot17;
                var1 = var2.getProps;
                var1 = var1.bind(var2)();
                var1 = var1.guildId;
                return var1;
            };
            var7 = var7.bind(var9)(var5, var3);
            var9 = _closure1_slot10;
            var5 = var9.useMemo;
            var3 = function() {
                var2 = function getScreens() {
                    var1 = {};
                    var2 = _closure1_slot24;
                    var7 = var2.OVERVIEW;
                    var3 = {};
                    var9 = _closure1_slot0;
                    var10 = _closure1_slot2;
                    var6 = 51;
                    var11 = var10[var6];
                    var8 = undefined;
                    var12 = var9.bind(var8)(var11);
                    var11 = var12.getHeaderCloseButton;
                    var13 = _closure1_slot1;
                    var5 = 24;
                    var5 = var10[var5];
                    var5 = var13.bind(var8)(var5);
                    var5 = var5.close;
                    var5 = var11.bind(var12)(var5);
                    var3['headerLeft'] = var5;
                    var5 = 31;
                    var11 = var10[var5];
                    var11 = var9.bind(var8)(var11);
                    var13 = var11.intl;
                    var12 = var13.string;
                    var11 = var10[var5];
                    var11 = var9.bind(var8)(var11);
                    var11 = var11.t;
                    var11 = var11.h850Sk;
                    var11 = var12.bind(var13)(var11);
                    var3['title'] = var11;
                    var11 = function render(arg1) {
                        var1 = arg1;
                        var1 = var1.guildId;
                        var4 = _closure1_slot31;
                        var3 = _closure1_slot36;
                        var2 = {};
                        var2['guildId'] = var1;
                        var1 = undefined;
                        var1 = var4.bind(var1)(var3, var2);
                        return var1;
                    };
                    var3['render'] = var11;
                    var1[var7] = var3;
                    var7 = var2.ADD_OVERRIDE;
                    var3 = {};
                    var11 = var10[var5];
                    var11 = var9.bind(var8)(var11);
                    var13 = var11.intl;
                    var12 = var13.string;
                    var11 = var10[var5];
                    var11 = var9.bind(var8)(var11);
                    var11 = var11.t;
                    var11 = var11.s7vIQU;
                    var11 = var12.bind(var13)(var11);
                    var3['title'] = var11;
                    var11 = var10[var6];
                    var12 = var9.bind(var8)(var11);
                    var11 = var12.getHeaderBackButton;
                    var11 = var11.bind(var12)();
                    var3['headerLeft'] = var11;
                    var11 = function render(arg1, arg2) {
                        var1 = arg1;
                        var5 = var1.guildId;
                        var4 = _closure1_slot31;
                        var2 = _closure1_slot1;
                        var3 = _closure1_slot2;
                        var1 = 52;
                        var1 = var3[var1];
                        var3 = undefined;
                        var2 = var2.bind(var3)(var1);
                        var1 = {};
                        var1['guildId'] = var5;
                        var5 = arg2;
                        var1['navigation'] = var5;
                        var1 = var4.bind(var3)(var2, var1);
                        return var1;
                    };
                    var3['render'] = var11;
                    var1[var7] = var3;
                    var3 = var2.CHANNEL_OVERRIDE;
                    var2 = {};
                    var6 = var10[var6];
                    var7 = var9.bind(var8)(var6);
                    var6 = var7.getHeaderBackButton;
                    var6 = var6.bind(var7)();
                    var2['headerLeft'] = var6;
                    var6 = var10[var5];
                    var6 = var9.bind(var8)(var6);
                    var7 = var6.intl;
                    var6 = var7.string;
                    var5 = var10[var5];
                    var5 = var9.bind(var8)(var5);
                    var5 = var5.t;
                    var5 = var5.h850Sk;
                    var5 = var6.bind(var7)(var5);
                    var2['title'] = var5;
                    var4 = function render(arg1) {
                        var1 = arg1;
                        var5 = var1.channelId;
                        var4 = _closure1_slot31;
                        var2 = _closure1_slot1;
                        var3 = _closure1_slot2;
                        var1 = 53;
                        var1 = var3[var1];
                        var3 = undefined;
                        var2 = var2.bind(var3)(var1);
                        var1 = {};
                        var1['channelId'] = var5;
                        var5 = true;
                        var1['inGuildContext'] = var5;
                        var1 = var4.bind(var3)(var2, var1);
                        return var1;
                    };
                    var2['render'] = var4;
                    var1[var3] = var2;
                    return var1;
                };
                var1 = undefined;
                var1 = var2.bind(var1)();
                return var1;
            };
            var1 = new Array(0);
            var5 = var5.bind(var9)(var3, var1);
            var3 = _closure1_slot31;
            var1 = 54;
            var1 = var6[var1];
            var1 = var2.bind(var4)(var1);
            var2 = var1.Navigator;
            var1 = {};
            var1['screens'] = var5;
            var6 = {};
            var5 = _closure1_slot24;
            var5 = var5.OVERVIEW;
            var6['name'] = var5;
            var5 = {};
            var9 = null;
            if(!(var9 == var7)) { _fun0012_ip = 140; continue _fun0012 }
 136:
            var7 = _closure1_slot30;
 140:
            var5['guildId'] = var7;
            var6['params'] = var5;
            var5 = new Array(1);
            var5[0] = var6;
            var1['initialRouteStack'] = var5;
            var1 = var3.bind(var4)(var2, var1);
            return var1;
        }
    };
    var3['default'] = var4;
    var3['NotificationSettings'] = var2;
    return var1;
})();