// app/modules/premium/native/gift_code_modal/GiftCodeRedeemModal.tsx
export default (function(argFoo, argBar, argBaz, argCorge, _, argFred, argPlugh) {
    oscar = argBar;
    report = argBaz;
    zulu = argFred;
    golf = argPlugh;
    var _closure1_slot0 = oscar;
    var _closure1_slot1 = report;
    var _closure1_slot2 = golf;
    entity = global;
    verify = entity.Object;
    options = verify.defineProperty;
    mike = {};
    entity = true;
    mike['value'] = entity;
    entity = '__esModule';
    entity = options.bind(verify)(zulu, entity, mike);
    entity = 0;
    options = golf[entity];
    mike = argCorge;
    entity = undefined;
    mike = mike.bind(entity)(options);
    mike = 1;
    mike = golf[mike];
    mike = report.bind(entity)(mike);
    var _closure1_slot3 = mike;
    mike = 2;
    mike = golf[mike];
    mike = report.bind(entity)(mike);
    var _closure1_slot4 = mike;
    mike = 3;
    mike = golf[mike];
    mike = oscar.bind(entity)(mike);
    mike = mike.jsx;
    var _closure1_slot5 = mike;
    mike = {};
    report = 'giftcode-start';
    mike['START'] = report;
    report = 'giftcode-success';
    mike['SUCCESS'] = report;
    report = 'giftcode-error';
    mike['ERROR'] = report;
    report = 'giftcode-use-avatar-decoration';
    mike['USE_AVATAR_DECORATION'] = report;
    report = 'giftcode-use-profile-effect';
    mike['USE_PROFILE_EFFECT'] = report;
    var _closure1_slot6 = mike;
    report = function() { // Original name: renderHeaderTitleUseAvatarDecoration
        tango = _closure1_slot5;
        options = _closure1_slot0;
        verify = _closure1_slot2;
        entity = 4;
        entity = verify[entity];
        zulu = undefined;
        entity = options.bind(zulu)(entity);
        mike = entity.Text;
        entity = {};
        report = 'redesign/heading-18/bold';
        entity['variant'] = report;
        report = 5;
        oscar = verify[report];
        oscar = options.bind(zulu)(oscar);
        golf = oscar.intl;
        oscar = golf.string;
        report = verify[report];
        report = options.bind(zulu)(report);
        report = report.t;
        report = report.Tna/TU;
        report = oscar.bind(golf)(report);
        entity['children'] = report;
        entity = tango.bind(zulu)(mike, entity);
        return entity;
    };
    var _closure1_slot7 = report;
    report = function() { // Original name: renderHeaderTitleUseProfileEffect
        tango = _closure1_slot5;
        options = _closure1_slot0;
        verify = _closure1_slot2;
        entity = 4;
        entity = verify[entity];
        zulu = undefined;
        entity = options.bind(zulu)(entity);
        mike = entity.Text;
        entity = {};
        report = 'redesign/heading-18/bold';
        entity['variant'] = report;
        report = 5;
        oscar = verify[report];
        oscar = options.bind(zulu)(oscar);
        golf = oscar.intl;
        oscar = golf.string;
        report = verify[report];
        report = options.bind(zulu)(report);
        report = report.t;
        report = report.0nEVoK;
        report = oscar.bind(golf)(report);
        entity['children'] = report;
        entity = tango.bind(zulu)(mike, entity);
        return entity;
    };
    var _closure1_slot8 = report;
    report = 6;
    report = golf[report];
    options = oscar.bind(entity)(report);
    report = options.getHeaderNoTitle;
    report = report.bind(options)();
    var _closure1_slot9 = report;
    report = 16;
    report = golf[report];
    golf = oscar.bind(entity)(report);
    oscar = golf.fileFinishedImporting;
    report = 'modules/premium/native/gift_code_modal/GiftCodeRedeemModal.tsx';
    report = oscar.bind(golf)(report);
    tango = function(argFoo) { // Original name: GiftCodeRedeemModal
        _fun91589: for(var _fun91589_ip = 0; ; ) switch(_fun91589_ip) {
 0:
            oscar = argFoo;
            report = oscar.code;
            var _closure2_slot0 = report;
            entity = null;
            tango = Object.create(entity);
            zulu = 0;
            tango['code'] = zulu;
            sizing = {};
            kilo = oscar;
            backup = tango;
            offset = copyDataProperties(sizing, kilo, backup);
            tango = _closure1_slot0;
            verify = _closure1_slot2;
            zulu = 13;
            golf = verify[zulu];
            oscar = undefined;
            foxtrot = tango.bind(oscar)(golf);
            romeo = foxtrot.useStateFromStores;
            golf = _closure1_slot3;
            yankee = new Array(1);
            yankee[0] = golf;
            golf = function() {
                zulu = _closure1_slot3;
                mike = zulu.get;
                entity = _closure2_slot0;
                entity = mike.bind(zulu)(entity);
                return entity;
            };
            romeo = romeo.bind(foxtrot)(yankee, golf);
            zulu = verify[zulu];
            yankee = tango.bind(oscar)(zulu);
            golf = yankee.useStateFromStores;
            zulu = _closure1_slot4;
            tango = new Array(1);
            tango[0] = zulu;
            zulu = function() {
                mike = _closure1_slot4;
                entity = mike.getCurrentUser;
                entity = entity.bind(mike)();
                return entity;
            };
            zulu = golf.bind(yankee)(tango, zulu);
            golf = _closure1_slot1;
            tango = 14;
            tango = verify[tango];
            tango = golf.bind(oscar)(tango);
            yankee = tango.bind(oscar)(report, zulu);
            if(!(entity != zulu)) { _fun91589_ip = 334; continue _fun91589 }
 160:
            mike = function(argFoo) { // Original name: getScreens
                entity = argFoo;
                var _closure3_slot0 = entity;
                entity = {};
                mike = _closure1_slot6;
                offset = mike.START;
                zulu = {};
                verify = _closure1_slot9;
                zulu['headerTitle'] = verify;
                golf = _closure1_slot0;
                options = _closure1_slot2;
                report = 6;
                romeo = options[report];
                oscar = undefined;
                backup = golf.bind(oscar)(romeo);
                foxtrot = backup.getHeaderCloseButton;
                romeo = function() {
                    zulu = _closure1_slot1;
                    mike = _closure1_slot2;
                    entity = 7;
                    mike = mike[entity];
                    entity = undefined;
                    mike = zulu.bind(entity)(mike);
                    entity = mike.pop;
                    entity = entity.bind(mike)();
                    return entity;
                };
                romeo = foxtrot.bind(backup)(romeo);
                zulu['headerLeft'] = romeo;
                romeo = function(argFoo) { // Original name: render
                    tango = _closure1_slot5;
                    mike = _closure1_slot1;
                    zulu = _closure1_slot2;
                    entity = 8;
                    entity = zulu[entity];
                    zulu = undefined;
                    mike = mike.bind(zulu)(entity);
                    entity = {};
                    golf = argFoo;
                    options = entity;
                    report = copyDataProperties(options, golf);
                    oscar = _closure3_slot0;
                    report = 'user';
                    entity[report] = oscar;
                    entity = tango.bind(zulu)(mike, entity);
                    return entity;
                };
                zulu['render'] = romeo;
                entity[offset] = zulu;
                offset = mike.SUCCESS;
                zulu = {};
                zulu['headerTitle'] = verify;
                romeo = options[report];
                backup = golf.bind(oscar)(romeo);
                foxtrot = backup.getHeaderCloseButton;
                romeo = function() {
                    zulu = _closure1_slot1;
                    mike = _closure1_slot2;
                    entity = 7;
                    mike = mike[entity];
                    entity = undefined;
                    mike = zulu.bind(entity)(mike);
                    entity = mike.pop;
                    entity = entity.bind(mike)();
                    return entity;
                };
                romeo = foxtrot.bind(backup)(romeo);
                zulu['headerLeft'] = romeo;
                romeo = function(argFoo) { // Original name: render
                    tango = _closure1_slot5;
                    mike = _closure1_slot1;
                    zulu = _closure1_slot2;
                    entity = 9;
                    entity = zulu[entity];
                    zulu = undefined;
                    mike = mike.bind(zulu)(entity);
                    entity = {};
                    golf = argFoo;
                    options = entity;
                    report = copyDataProperties(options, golf);
                    oscar = _closure3_slot0;
                    report = 'user';
                    entity[report] = oscar;
                    entity = tango.bind(zulu)(mike, entity);
                    return entity;
                };
                zulu['render'] = romeo;
                entity[offset] = zulu;
                offset = mike.USE_AVATAR_DECORATION;
                zulu = {};
                romeo = _closure1_slot7;
                zulu['headerTitle'] = romeo;
                romeo = options[report];
                backup = golf.bind(oscar)(romeo);
                foxtrot = backup.getHeaderCloseButton;
                romeo = function() {
                    zulu = _closure1_slot1;
                    mike = _closure1_slot2;
                    entity = 7;
                    mike = mike[entity];
                    entity = undefined;
                    mike = zulu.bind(entity)(mike);
                    entity = mike.pop;
                    entity = entity.bind(mike)();
                    return entity;
                };
                romeo = foxtrot.bind(backup)(romeo);
                zulu['headerLeft'] = romeo;
                romeo = function(argFoo) { // Original name: render
                    tango = _closure1_slot5;
                    mike = _closure1_slot1;
                    zulu = _closure1_slot2;
                    entity = 10;
                    entity = zulu[entity];
                    zulu = undefined;
                    mike = mike.bind(zulu)(entity);
                    entity = {};
                    golf = argFoo;
                    options = entity;
                    report = copyDataProperties(options, golf);
                    oscar = _closure3_slot0;
                    report = 'user';
                    entity[report] = oscar;
                    entity = tango.bind(zulu)(mike, entity);
                    return entity;
                };
                zulu['render'] = romeo;
                entity[offset] = zulu;
                offset = mike.USE_PROFILE_EFFECT;
                zulu = {};
                yankee = _closure1_slot8;
                zulu['headerTitle'] = yankee;
                yankee = options[report];
                foxtrot = golf.bind(oscar)(yankee);
                romeo = foxtrot.getHeaderCloseButton;
                yankee = function() {
                    zulu = _closure1_slot1;
                    mike = _closure1_slot2;
                    entity = 7;
                    mike = mike[entity];
                    entity = undefined;
                    mike = zulu.bind(entity)(mike);
                    entity = mike.pop;
                    entity = entity.bind(mike)();
                    return entity;
                };
                yankee = romeo.bind(foxtrot)(yankee);
                zulu['headerLeft'] = yankee;
                yankee = function(argFoo) { // Original name: render
                    tango = _closure1_slot5;
                    mike = _closure1_slot1;
                    zulu = _closure1_slot2;
                    entity = 11;
                    entity = zulu[entity];
                    zulu = undefined;
                    mike = mike.bind(zulu)(entity);
                    entity = {};
                    golf = argFoo;
                    options = entity;
                    report = copyDataProperties(options, golf);
                    oscar = _closure3_slot0;
                    report = 'user';
                    entity[report] = oscar;
                    entity = tango.bind(zulu)(mike, entity);
                    return entity;
                };
                zulu['render'] = yankee;
                entity[offset] = zulu;
                zulu = mike.ERROR;
                mike = {};
                mike['headerTitle'] = verify;
                report = options[report];
                golf = golf.bind(oscar)(report);
                oscar = golf.getHeaderCloseButton;
                report = function() {
                    zulu = _closure1_slot1;
                    mike = _closure1_slot2;
                    entity = 7;
                    mike = mike[entity];
                    entity = undefined;
                    mike = zulu.bind(entity)(mike);
                    entity = mike.pop;
                    entity = entity.bind(mike)();
                    return entity;
                };
                report = oscar.bind(golf)(report);
                mike['headerLeft'] = report;
                tango = function(argFoo) { // Original name: render
                    tango = _closure1_slot5;
                    mike = _closure1_slot1;
                    zulu = _closure1_slot2;
                    entity = 12;
                    entity = zulu[entity];
                    zulu = undefined;
                    mike = mike.bind(zulu)(entity);
                    entity = {};
                    oscar = argFoo;
                    golf = entity;
                    report = copyDataProperties(golf, oscar);
                    entity = tango.bind(zulu)(mike, entity);
                    return entity;
                };
                mike['render'] = tango;
                entity[zulu] = mike;
                return entity;
            };
            golf = mike.bind(oscar)(zulu);
            zulu = entity == romeo;
            mike = null;
            if(zulu) { _fun91589_ip = 332; continue _fun91589 }
 184:
            report = _closure1_slot5;
            tango = _closure1_slot0;
            verify = _closure1_slot2;
            zulu = 15;
            zulu = verify[zulu];
            zulu = tango.bind(oscar)(zulu);
            tango = zulu.Navigator;
            zulu = {};
            zulu['screens'] = golf;
            if(!(entity == yankee)) { _fun91589_ip = 273; continue _fun91589 }
 225:
            verify = {};
            golf = _closure1_slot6;
            golf = golf.START;
            verify['name'] = golf;
            golf = {};
            golf['giftCode'] = romeo;
            sizing = golf;
            kilo = offset;
            romeo = copyDataProperties(sizing, kilo);
            verify['params'] = golf;
            golf = new Array(1);
            golf[0] = verify;
            _fun91589_ip = 321; continue _fun91589;
 273:
            verify = {};
            options = _closure1_slot6;
            options = options.ERROR;
            verify['name'] = options;
            options = {};
            options['message'] = yankee;
            sizing = options;
            kilo = offset;
            offset = copyDataProperties(sizing, kilo);
            verify['params'] = options;
            options = new Array(1);
            options[0] = verify;
            golf = options;
 321:
            zulu['initialRouteStack'] = golf;
            mike = report.bind(oscar)(tango, zulu);
 332:
            return mike;
 334:
            return entity;
        }
    };
    zulu['default'] = tango;
    zulu['GiftCodeModalScreens'] = mike;
    return entity;
})();