// app/modules/premium/native/gift_code_modal/GiftCodeRedeemModal.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var6 = require;
    var5 = metroImportDefault;
    var3 = exports;
    var7 = dependencyMap;
    var _closure1_slot0 = var6;
    var _closure1_slot1 = var5;
    var _closure1_slot2 = var7;
    var1 = global;
    var9 = var1.Object;
    var8 = var9.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var8.bind(var9)(var3, var1, var2);
    var1 = 0;
    var8 = var7[var1];
    var2 = metroImportAll;
    var1 = undefined;
    var2 = var2.bind(var1)(var8);
    var2 = 1;
    var2 = var7[var2];
    var2 = var5.bind(var1)(var2);
    var _closure1_slot3 = var2;
    var2 = 2;
    var2 = var7[var2];
    var2 = var5.bind(var1)(var2);
    var _closure1_slot4 = var2;
    var2 = 3;
    var2 = var7[var2];
    var2 = var6.bind(var1)(var2);
    var2 = var2.jsx;
    var _closure1_slot5 = var2;
    var2 = {};
    var5 = 'giftcode-start';
    var2['START'] = var5;
    var5 = 'giftcode-success';
    var2['SUCCESS'] = var5;
    var5 = 'giftcode-error';
    var2['ERROR'] = var5;
    var5 = 'giftcode-use-avatar-decoration';
    var2['USE_AVATAR_DECORATION'] = var5;
    var5 = 'giftcode-use-profile-effect';
    var2['USE_PROFILE_EFFECT'] = var5;
    var5 = 'giftcode-use-nameplate';
    var2['USE_NAMEPLATE'] = var5;
    var _closure1_slot6 = var2;
    var5 = function renderHeaderTitleUseAvatarDecoration() {
        var4 = _closure1_slot5;
        var8 = _closure1_slot0;
        var9 = _closure1_slot2;
        var1 = 4;
        var1 = var9[var1];
        var3 = undefined;
        var1 = var8.bind(var3)(var1);
        var2 = var1.Text;
        var1 = {};
        var5 = 'redesign/heading-18/bold';
        var1['variant'] = var5;
        var5 = 5;
        var6 = var9[var5];
        var6 = var8.bind(var3)(var6);
        var7 = var6.intl;
        var6 = var7.string;
        var5 = var9[var5];
        var5 = var8.bind(var3)(var5);
        var5 = var5.t;
        var5 = var5.BVcYCw;
        var5 = var6.bind(var7)(var5);
        var1['children'] = var5;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var _closure1_slot7 = var5;
    var5 = function renderHeaderTitleUseProfileEffect() {
        var4 = _closure1_slot5;
        var8 = _closure1_slot0;
        var9 = _closure1_slot2;
        var1 = 4;
        var1 = var9[var1];
        var3 = undefined;
        var1 = var8.bind(var3)(var1);
        var2 = var1.Text;
        var1 = {};
        var5 = 'redesign/heading-18/bold';
        var1['variant'] = var5;
        var5 = 5;
        var6 = var9[var5];
        var6 = var8.bind(var3)(var6);
        var7 = var6.intl;
        var6 = var7.string;
        var5 = var9[var5];
        var5 = var8.bind(var3)(var5);
        var5 = var5.t;
        var5 = var5./dRfCQ;
        var5 = var6.bind(var7)(var5);
        var1['children'] = var5;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var _closure1_slot8 = var5;
    var5 = function renderHeaderTitleUseNameplate() {
        var4 = _closure1_slot5;
        var8 = _closure1_slot0;
        var9 = _closure1_slot2;
        var1 = 4;
        var1 = var9[var1];
        var3 = undefined;
        var1 = var8.bind(var3)(var1);
        var2 = var1.Text;
        var1 = {};
        var5 = 'redesign/heading-18/bold';
        var1['variant'] = var5;
        var5 = 5;
        var6 = var9[var5];
        var6 = var8.bind(var3)(var6);
        var7 = var6.intl;
        var6 = var7.string;
        var5 = var9[var5];
        var5 = var8.bind(var3)(var5);
        var5 = var5.t;
        var5 = var5.BwdeMz;
        var5 = var6.bind(var7)(var5);
        var1['children'] = var5;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var _closure1_slot9 = var5;
    var5 = 6;
    var5 = var7[var5];
    var8 = var6.bind(var1)(var5);
    var5 = var8.getHeaderNoTitle;
    var5 = var5.bind(var8)();
    var _closure1_slot10 = var5;
    var5 = 17;
    var5 = var7[var5];
    var7 = var6.bind(var1)(var5);
    var6 = var7.fileFinishedImporting;
    var5 = 'modules/premium/native/gift_code_modal/GiftCodeRedeemModal.tsx';
    var5 = var6.bind(var7)(var5);
    var4 = function GiftCodeRedeemModal(arg1) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
 0:
            var6 = arg1;
            var5 = var6.code;
            var _closure2_slot0 = var5;
            var1 = null;
            var4 = Object.create(var1);
            var3 = 0;
            var4['code'] = var3;
            var16 = {};
            var15 = var6;
            var14 = var4;
            var10 = copyDataProperties(var16, var15, var14);
            var4 = _closure1_slot0;
            var9 = _closure1_slot2;
            var3 = 14;
            var7 = var9[var3];
            var6 = undefined;
            var13 = var4.bind(var6)(var7);
            var12 = var13.useStateFromStores;
            var7 = _closure1_slot3;
            var11 = new Array(1);
            var11[0] = var7;
            var7 = function() {
                var3 = _closure1_slot3;
                var2 = var3.get;
                var1 = _closure2_slot0;
                var1 = var2.bind(var3)(var1);
                return var1;
            };
            var12 = var12.bind(var13)(var11, var7);
            var3 = var9[var3];
            var11 = var4.bind(var6)(var3);
            var7 = var11.useStateFromStores;
            var3 = _closure1_slot4;
            var4 = new Array(1);
            var4[0] = var3;
            var3 = function() {
                var2 = _closure1_slot4;
                var1 = var2.getCurrentUser;
                var1 = var1.bind(var2)();
                return var1;
            };
            var3 = var7.bind(var11)(var4, var3);
            var7 = _closure1_slot1;
            var4 = 15;
            var4 = var9[var4];
            var4 = var7.bind(var6)(var4);
            var11 = var4.bind(var6)(var5, var3);
            if(!(var1 != var3)) { _fun0001_ip = 334; continue _fun0001 }
 160:
            var2 = function getScreens(arg1) {
                var1 = arg1;
                var _closure3_slot0 = var1;
                var1 = {};
                var2 = _closure1_slot6;
                var10 = var2.START;
                var3 = {};
                var9 = _closure1_slot10;
                var3['headerTitle'] = var9;
                var7 = _closure1_slot0;
                var8 = _closure1_slot2;
                var5 = 6;
                var12 = var8[var5];
                var6 = undefined;
                var14 = var7.bind(var6)(var12);
                var13 = var14.getHeaderCloseButton;
                var12 = function() {
                    var3 = _closure1_slot1;
                    var2 = _closure1_slot2;
                    var1 = 7;
                    var2 = var2[var1];
                    var1 = undefined;
                    var2 = var3.bind(var1)(var2);
                    var1 = var2.pop;
                    var1 = var1.bind(var2)();
                    return var1;
                };
                var12 = var13.bind(var14)(var12);
                var3['headerLeft'] = var12;
                var12 = function render(arg1) {
                    var4 = _closure1_slot5;
                    var2 = _closure1_slot1;
                    var3 = _closure1_slot2;
                    var1 = 8;
                    var1 = var3[var1];
                    var3 = undefined;
                    var2 = var2.bind(var3)(var1);
                    var1 = {};
                    var7 = arg1;
                    var8 = var1;
                    var5 = copyDataProperties(var8, var7);
                    var6 = _closure3_slot0;
                    var5 = 'user';
                    var1[var5] = var6;
                    var1 = var4.bind(var3)(var2, var1);
                    return var1;
                };
                var3['render'] = var12;
                var1[var10] = var3;
                var10 = var2.SUCCESS;
                var3 = {};
                var3['headerTitle'] = var9;
                var12 = var8[var5];
                var14 = var7.bind(var6)(var12);
                var13 = var14.getHeaderCloseButton;
                var12 = function() {
                    var3 = _closure1_slot1;
                    var2 = _closure1_slot2;
                    var1 = 7;
                    var2 = var2[var1];
                    var1 = undefined;
                    var2 = var3.bind(var1)(var2);
                    var1 = var2.pop;
                    var1 = var1.bind(var2)();
                    return var1;
                };
                var12 = var13.bind(var14)(var12);
                var3['headerLeft'] = var12;
                var12 = function render(arg1) {
                    var4 = _closure1_slot5;
                    var2 = _closure1_slot1;
                    var3 = _closure1_slot2;
                    var1 = 9;
                    var1 = var3[var1];
                    var3 = undefined;
                    var2 = var2.bind(var3)(var1);
                    var1 = {};
                    var7 = arg1;
                    var8 = var1;
                    var5 = copyDataProperties(var8, var7);
                    var6 = _closure3_slot0;
                    var5 = 'user';
                    var1[var5] = var6;
                    var1 = var4.bind(var3)(var2, var1);
                    return var1;
                };
                var3['render'] = var12;
                var1[var10] = var3;
                var10 = var2.USE_AVATAR_DECORATION;
                var3 = {};
                var12 = _closure1_slot7;
                var3['headerTitle'] = var12;
                var12 = var8[var5];
                var14 = var7.bind(var6)(var12);
                var13 = var14.getHeaderCloseButton;
                var12 = function() {
                    var3 = _closure1_slot1;
                    var2 = _closure1_slot2;
                    var1 = 7;
                    var2 = var2[var1];
                    var1 = undefined;
                    var2 = var3.bind(var1)(var2);
                    var1 = var2.pop;
                    var1 = var1.bind(var2)();
                    return var1;
                };
                var12 = var13.bind(var14)(var12);
                var3['headerLeft'] = var12;
                var12 = function render(arg1) {
                    var4 = _closure1_slot5;
                    var2 = _closure1_slot1;
                    var3 = _closure1_slot2;
                    var1 = 10;
                    var1 = var3[var1];
                    var3 = undefined;
                    var2 = var2.bind(var3)(var1);
                    var1 = {};
                    var7 = arg1;
                    var8 = var1;
                    var5 = copyDataProperties(var8, var7);
                    var6 = _closure3_slot0;
                    var5 = 'user';
                    var1[var5] = var6;
                    var1 = var4.bind(var3)(var2, var1);
                    return var1;
                };
                var3['render'] = var12;
                var1[var10] = var3;
                var10 = var2.USE_PROFILE_EFFECT;
                var3 = {};
                var12 = _closure1_slot8;
                var3['headerTitle'] = var12;
                var12 = var8[var5];
                var14 = var7.bind(var6)(var12);
                var13 = var14.getHeaderCloseButton;
                var12 = function() {
                    var3 = _closure1_slot1;
                    var2 = _closure1_slot2;
                    var1 = 7;
                    var2 = var2[var1];
                    var1 = undefined;
                    var2 = var3.bind(var1)(var2);
                    var1 = var2.pop;
                    var1 = var1.bind(var2)();
                    return var1;
                };
                var12 = var13.bind(var14)(var12);
                var3['headerLeft'] = var12;
                var12 = function render(arg1) {
                    var4 = _closure1_slot5;
                    var2 = _closure1_slot1;
                    var3 = _closure1_slot2;
                    var1 = 11;
                    var1 = var3[var1];
                    var3 = undefined;
                    var2 = var2.bind(var3)(var1);
                    var1 = {};
                    var7 = arg1;
                    var8 = var1;
                    var5 = copyDataProperties(var8, var7);
                    var6 = _closure3_slot0;
                    var5 = 'user';
                    var1[var5] = var6;
                    var1 = var4.bind(var3)(var2, var1);
                    return var1;
                };
                var3['render'] = var12;
                var1[var10] = var3;
                var10 = var2.USE_NAMEPLATE;
                var3 = {};
                var11 = _closure1_slot9;
                var3['headerTitle'] = var11;
                var11 = var8[var5];
                var13 = var7.bind(var6)(var11);
                var12 = var13.getHeaderCloseButton;
                var11 = function() {
                    var3 = _closure1_slot1;
                    var2 = _closure1_slot2;
                    var1 = 7;
                    var2 = var2[var1];
                    var1 = undefined;
                    var2 = var3.bind(var1)(var2);
                    var1 = var2.pop;
                    var1 = var1.bind(var2)();
                    return var1;
                };
                var11 = var12.bind(var13)(var11);
                var3['headerLeft'] = var11;
                var11 = function render(arg1) {
                    var4 = _closure1_slot5;
                    var2 = _closure1_slot1;
                    var3 = _closure1_slot2;
                    var1 = 12;
                    var1 = var3[var1];
                    var3 = undefined;
                    var2 = var2.bind(var3)(var1);
                    var1 = {};
                    var7 = arg1;
                    var8 = var1;
                    var5 = copyDataProperties(var8, var7);
                    var6 = _closure3_slot0;
                    var5 = 'user';
                    var1[var5] = var6;
                    var1 = var4.bind(var3)(var2, var1);
                    return var1;
                };
                var3['render'] = var11;
                var1[var10] = var3;
                var3 = var2.ERROR;
                var2 = {};
                var2['headerTitle'] = var9;
                var5 = var8[var5];
                var7 = var7.bind(var6)(var5);
                var6 = var7.getHeaderCloseButton;
                var5 = function() {
                    var3 = _closure1_slot1;
                    var2 = _closure1_slot2;
                    var1 = 7;
                    var2 = var2[var1];
                    var1 = undefined;
                    var2 = var3.bind(var1)(var2);
                    var1 = var2.pop;
                    var1 = var1.bind(var2)();
                    return var1;
                };
                var5 = var6.bind(var7)(var5);
                var2['headerLeft'] = var5;
                var4 = function render(arg1) {
                    var4 = _closure1_slot5;
                    var2 = _closure1_slot1;
                    var3 = _closure1_slot2;
                    var1 = 13;
                    var1 = var3[var1];
                    var3 = undefined;
                    var2 = var2.bind(var3)(var1);
                    var1 = {};
                    var6 = arg1;
                    var7 = var1;
                    var5 = copyDataProperties(var7, var6);
                    var1 = var4.bind(var3)(var2, var1);
                    return var1;
                };
                var2['render'] = var4;
                var1[var3] = var2;
                return var1;
            };
            var7 = var2.bind(var6)(var3);
            var3 = var1 == var12;
            var2 = null;
            if(var3) { _fun0001_ip = 332; continue _fun0001 }
 184:
            var5 = _closure1_slot5;
            var4 = _closure1_slot0;
            var9 = _closure1_slot2;
            var3 = 16;
            var3 = var9[var3];
            var3 = var4.bind(var6)(var3);
            var4 = var3.Navigator;
            var3 = {};
            var3['screens'] = var7;
            if(!(var1 == var11)) { _fun0001_ip = 273; continue _fun0001 }
 225:
            var9 = {};
            var7 = _closure1_slot6;
            var7 = var7.START;
            var9['name'] = var7;
            var7 = {};
            var7['giftCode'] = var12;
            var16 = var7;
            var15 = var10;
            var12 = copyDataProperties(var16, var15);
            var9['params'] = var7;
            var7 = new Array(1);
            var7[0] = var9;
            _fun0001_ip = 321; continue _fun0001;
 273:
            var9 = {};
            var8 = _closure1_slot6;
            var8 = var8.ERROR;
            var9['name'] = var8;
            var8 = {};
            var8['message'] = var11;
            var16 = var8;
            var15 = var10;
            var10 = copyDataProperties(var16, var15);
            var9['params'] = var8;
            var8 = new Array(1);
            var8[0] = var9;
            var7 = var8;
 321:
            var3['initialRouteStack'] = var7;
            var2 = var5.bind(var6)(var4, var3);
 332:
            return var2;
 334:
            return var1;
        }
    };
    var3['default'] = var4;
    var3['GiftCodeModalScreens'] = var2;
    return var1;
})();