// app/modules/quests/native/QuestRewardDetailsBottomSheet.native.tsx
export default (function(argFoo, argBar, argBaz, argCor, _, argFre, argPlu) {
    report = argBar;
    zuuluu = argFre;
    oscard = argPlu;
    var _closure1_slot0 = report;
    entity = argBaz;
    var _closure1_slot1 = entity;
    var _closure1_slot2 = oscard;
    entity = global;
    option = entity.Object;
    golfie = option.defineProperty;
    tangon = {};
    entity = true;
    tangon['value'] = entity;
    entity = '__esModule';
    entity = golfie.bind(option)(zuuluu, entity, tangon);
    entity = 0;
    golfie = oscard[entity];
    tangon = argCor;
    entity = undefined;
    tangon = tangon.bind(entity)(golfie);
    var _closure1_slot3 = tangon;
    tangon = 1;
    tangon = oscard[tangon];
    tangon = report.bind(entity)(tangon);
    tangon = tangon.View;
    var _closure1_slot4 = tangon;
    tangon = 2;
    tangon = oscard[tangon];
    tangon = report.bind(entity)(tangon);
    golfie = tangon.jsx;
    var _closure1_slot5 = golfie;
    tangon = tangon.jsxs;
    var _closure1_slot6 = tangon;
    tangon = 3;
    tangon = oscard[tangon];
    option = report.bind(entity)(tangon);
    golfie = option.createStyles;
    tangon = function(argFoo) {
        _fun00001: for(var _fun00002_ip = 0; ; ) switch(_fun00002_ip) {
 0:
            entity = {};
            michal = {};
            golfie = _closure1_slot1;
            tangon = _closure1_slot2;
            oscard = 4;
            tangon = tangon[oscard];
            report = undefined;
            tangon = golfie.bind(report)(tangon);
            tangon = tangon.spacing;
            tangon = tangon.PX_16;
            michal['paddingHorizontal'] = tangon;
            golfie = argFoo;
            tangon = undefined;
            if(!golfie) { _fun00002_ip = 79; continue _fun00001 }
 51:
            option = _closure1_slot1;
            golfie = _closure1_slot2;
            golfie = golfie[oscard];
            golfie = option.bind(report)(golfie);
            golfie = golfie.spacing;
            tangon = golfie.PX_8;
 79:
            michal['paddingBottom'] = tangon;
            entity['wrapper'] = michal;
            michal = {};
            tangon = 1;
            michal['flexShrink'] = tangon;
            entity['rewardDetailsCopy'] = michal;
            michal = {};
            michal['height'] = tangon;
            tangon = _closure1_slot1;
            zuuluu = _closure1_slot2;
            zuuluu = zuuluu[oscard];
            zuuluu = tangon.bind(report)(zuuluu);
            zuuluu = zuuluu.colors;
            zuuluu = zuuluu.BORDER_STRONG;
            michal['backgroundColor'] = zuuluu;
            entity['separator'] = michal;
            return entity;
        }
    };
    tangon = golfie.bind(option)(tangon);
    var _closure1_slot7 = tangon;
    tangon = 15;
    tangon = oscard[tangon];
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/quests/native/QuestRewardDetailsBottomSheet.native.tsx';
    tangon = report.bind(oscard)(tangon);
    michal = function(argFoo) { // Original name: QuestRewardDetailsBottomSheet
        michal = argFoo;
        report = michal.questId;
        offset = _closure1_slot0;
        romeon = _closure1_slot2;
        michal = 5;
        michal = romeon[michal];
        tangon = undefined;
        zuuluu = offset.bind(tangon)(michal);
        michal = zuuluu.useNonNullableQuest;
        source = michal.bind(zuuluu)(report);
        var _closure2_slot0 = source;
        zuuluu = _closure1_slot7;
        michal = 6;
        michal = romeon[michal];
        report = offset.bind(tangon)(michal);
        michal = report.isAndroid;
        michal = michal.bind(report)();
        kiloes = zuuluu.bind(tangon)(michal);
        report = _closure1_slot3;
        oscard = report.useMemo;
        michal = source.config;
        zuuluu = new Array(1);
        zuuluu[0] = michal;
        michal = function() {
            zuuluu = _closure1_slot0;
            michal = _closure1_slot2;
            entity = 7;
            michal = michal[entity];
            entity = undefined;
            entity = zuuluu.bind(entity)(michal);
            zuuluu = entity.SharedQuestFields;
            michal = zuuluu.build;
            entity = _closure2_slot0;
            entity = entity.config;
            entity = michal.bind(zuuluu)(entity);
            return entity;
        };
        ctrled = oscard.bind(report)(michal, zuuluu);
        zuuluu = report.useMemo;
        michal = new Array(1);
        michal[0] = source;
        entity = function() {
            _fun00003: for(var _fun00004_ip = 0; ; ) switch(_fun00004_ip) {
 0:
                tangon = _closure1_slot0;
                michal = _closure1_slot2;
                zuuluu = 8;
                zuuluu = michal[zuuluu];
                report = undefined;
                golfie = tangon.bind(report)(zuuluu);
                oscard = golfie.getQuestPrimaryReward;
                zuuluu = _closure2_slot0;
                zuuluu = oscard.bind(golfie)(zuuluu);
                zuuluu = zuuluu.type;
                oscard = 9;
                michal = michal[oscard];
                michal = tangon.bind(report)(michal);
                michal = michal.QuestRewardTypes;
                michal = michal.REWARD_CODE;
                if(!(michal !== zuuluu)) { _fun00004_ip = 459; continue _fun00003 }
 79:
                tangon = _closure1_slot0;
                michal = _closure1_slot2;
                michal = michal[oscard];
                michal = tangon.bind(report)(michal);
                michal = michal.QuestRewardTypes;
                michal = michal.COLLECTIBLE;
                if(!(michal !== zuuluu)) { _fun00004_ip = 400; continue _fun00003 }
 115:
                tangon = _closure1_slot0;
                michal = _closure1_slot2;
                michal = michal[oscard];
                michal = tangon.bind(report)(michal);
                michal = michal.QuestRewardTypes;
                michal = michal.IN_GAME;
                if(!(michal !== zuuluu)) { _fun00004_ip = 341; continue _fun00003 }
 151:
                tangon = _closure1_slot0;
                michal = _closure1_slot2;
                michal = michal[oscard];
                michal = tangon.bind(report)(michal);
                michal = michal.QuestRewardTypes;
                michal = michal.VIRTUAL_CURRENCY;
                if(!(michal !== zuuluu)) { _fun00004_ip = 282; continue _fun00003 }
 184:
                tangon = _closure1_slot0;
                michal = _closure1_slot2;
                michal = michal[oscard];
                michal = tangon.bind(report)(michal);
                michal = michal.QuestRewardTypes;
                michal = michal.FRACTIONAL_PREMIUM;
                if(!(michal !== zuuluu)) { _fun00004_ip = 223; continue _fun00003 }
 217:
                michal = '';
                return michal;
 223:
                oscard = _closure1_slot0;
                golfie = _closure1_slot2;
                michal = 10;
                zuuluu = golfie[michal];
                zuuluu = oscard.bind(report)(zuuluu);
                tangon = zuuluu.intl;
                zuuluu = tangon.string;
                michal = golfie[michal];
                michal = oscard.bind(report)(michal);
                michal = michal.t;
                michal = michal.f0efMj;
                michal = zuuluu.bind(tangon)(michal);
                return michal;
 282:
                oscard = _closure1_slot0;
                golfie = _closure1_slot2;
                michal = 10;
                zuuluu = golfie[michal];
                zuuluu = oscard.bind(report)(zuuluu);
                tangon = zuuluu.intl;
                zuuluu = tangon.string;
                michal = golfie[michal];
                michal = oscard.bind(report)(michal);
                michal = michal.t;
                michal = michal.c2uVzc;
                michal = zuuluu.bind(tangon)(michal);
                return michal;
 341:
                oscard = _closure1_slot0;
                golfie = _closure1_slot2;
                michal = 10;
                zuuluu = golfie[michal];
                zuuluu = oscard.bind(report)(zuuluu);
                tangon = zuuluu.intl;
                zuuluu = tangon.string;
                michal = golfie[michal];
                michal = oscard.bind(report)(michal);
                michal = michal.t;
                michal = michal.efPXsr;
                michal = zuuluu.bind(tangon)(michal);
                return michal;
 400:
                oscard = _closure1_slot0;
                golfie = _closure1_slot2;
                michal = 10;
                zuuluu = golfie[michal];
                zuuluu = oscard.bind(report)(zuuluu);
                tangon = zuuluu.intl;
                zuuluu = tangon.string;
                michal = golfie[michal];
                michal = oscard.bind(report)(michal);
                michal = michal.t;
                michal = michal.1rQyNj;
                michal = zuuluu.bind(tangon)(michal);
                return michal;
 459:
                tangon = _closure1_slot0;
                oscard = _closure1_slot2;
                entity = 10;
                michal = oscard[entity];
                michal = tangon.bind(report)(michal);
                zuuluu = michal.intl;
                michal = zuuluu.string;
                entity = oscard[entity];
                entity = tangon.bind(report)(entity);
                entity = entity.t;
                entity = entity.rc9liI;
                entity = michal.bind(zuuluu)(entity);
                return entity;
            }
        };
        yankee = zuuluu.bind(report)(entity, michal);
        zuuluu = _closure1_slot5;
        entity = 11;
        entity = romeon[entity];
        entity = offset.bind(tangon)(entity);
        michal = entity.BottomSheet;
        entity = {};
        report = true;
        entity['startExpanded'] = report;
        golfie = _closure1_slot6;
        output = 12;
        report = romeon[output];
        report = offset.bind(tangon)(report);
        oscard = report.Stack;
        report = {};
        update = 'vertical';
        report['direction'] = update;
        echoed = _closure1_slot1;
        verify = 4;
        option = romeon[verify];
        option = echoed.bind(tangon)(option);
        option = option.spacing;
        option = option.PX_16;
        report['spacing'] = option;
        option = kiloes.wrapper;
        report['style'] = option;
        option = romeon[output];
        option = offset.bind(tangon)(option);
        backup = option.Stack;
        option = {'align': 'center', 'direction': 'horizontal'};
        sizing = romeon[verify];
        sizing = echoed.bind(tangon)(sizing);
        sizing = sizing.spacing;
        sizing = sizing.PX_16;
        option['spacing'] = sizing;
        sizing = 13;
        sizing = romeon[sizing];
        result = echoed.bind(tangon)(sizing);
        sizing = {'quest': null, 'height': 56, 'width': 56};
        sizing['quest'] = source;
        result = zuuluu.bind(tangon)(result, sizing);
        sizing = new Array(2);
        sizing[0] = result;
        output = romeon[output];
        output = offset.bind(tangon)(output);
        result = output.Stack;
        output = {};
        output['direction'] = update;
        verify = romeon[verify];
        verify = echoed.bind(tangon)(verify);
        verify = verify.spacing;
        verify = verify.PX_4;
        output['spacing'] = verify;
        verify = kiloes.rewardDetailsCopy;
        output['style'] = verify;
        verify = 14;
        echoed = romeon[verify];
        echoed = offset.bind(tangon)(echoed);
        update = echoed.Text;
        echoed = {'variant': 'eyebrow', 'color': 'text-secondary'};
        source = 10;
        vacuum = romeon[source];
        vacuum = offset.bind(tangon)(vacuum);
        sequen = vacuum.intl;
        vacuum = sequen.string;
        source = romeon[source];
        source = offset.bind(tangon)(source);
        source = source.t;
        source = source.jyYgZ2;
        source = vacuum.bind(sequen)(source);
        echoed['children'] = source;
        update = zuuluu.bind(tangon)(update, echoed);
        echoed = new Array(2);
        echoed[0] = update;
        update = romeon[verify];
        update = offset.bind(tangon)(update);
        source = update.Text;
        update = {'variant': 'heading-lg/semibold', 'color': 'text-primary'};
        ctrled = ctrled.defaultReward;
        ctrled = ctrled.messages;
        ctrled = ctrled.name;
        update['children'] = ctrled;
        update = zuuluu.bind(tangon)(source, update);
        echoed[1] = update;
        output['children'] = echoed;
        output = golfie.bind(tangon)(result, output);
        sizing[1] = output;
        option['children'] = sizing;
        backup = golfie.bind(tangon)(backup, option);
        option = new Array(3);
        option[0] = backup;
        backup = _closure1_slot4;
        foxtra = {};
        kiloes = kiloes.separator;
        foxtra['style'] = kiloes;
        foxtra = zuuluu.bind(tangon)(backup, foxtra);
        option[1] = foxtra;
        verify = romeon[verify];
        verify = offset.bind(tangon)(verify);
        offset = verify.Text;
        verify = {'variant': 'text-md/normal', 'color': 'text-secondary'};
        verify['children'] = yankee;
        verify = zuuluu.bind(tangon)(offset, verify);
        option[2] = verify;
        report['children'] = option;
        report = golfie.bind(tangon)(oscard, report);
        entity['children'] = report;
        entity = zuuluu.bind(tangon)(michal, entity);
        return entity;
    };
    zuuluu['default'] = michal;
    return entity;
})();