// app/modules/multi_account/useMultiAccount.tsx
export default (function(native1, native2, native3, native4, native5, native6, native7) {
    var5 = native2;
    var7 = native3;
    var8 = native4;
    var3 = native6;
    var6 = native7;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var7;
    var _closure1_slot2 = var8;
    var _closure1_slot3 = var6;
    var1 = global;
    var10 = var1.Object;
    var9 = var10.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var9.bind(var10)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var8.bind(var1)(var4);
    var _closure1_slot4 = var4;
    var4 = 1;
    var4 = var6[var4];
    var4 = var7.bind(var1)(var4);
    var _closure1_slot5 = var4;
    var4 = 5;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/multi_account/useMultiAccount.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function useMultiAccountUsers() {
        var5 = _closure1_slot0;
        var4 = _closure1_slot3;
        var1 = 2;
        var4 = var4[var1];
        var1 = undefined;
        var6 = var5.bind(var1)(var4);
        var5 = var6.useStateFromStoresObject;
        var1 = _closure1_slot5;
        var4 = new Array(1);
        var4[0] = var1;
        var1 = function() {
            var1 = {};
            var3 = _closure1_slot5;
            var2 = var3.getIsValidatingUsers;
            var2 = var2.bind(var3)();
            var1['isLoading'] = var2;
            var2 = var3.getUsers;
            var2 = var2.bind(var3)();
            var1['multiAccountUsers'] = var2;
            return var1;
        };
        var1 = var5.bind(var6)(var4, var1);
        var5 = _closure1_slot4;
        var4 = var5.useEffect;
        var3 = function() {
            var3 = _closure1_slot1;
            var2 = _closure1_slot3;
            var1 = 3;
            var2 = var2[var1];
            var1 = undefined;
            var4 = var3.bind(var1)(var2);
            var3 = var4.wait;
            var2 = function() {
                var3 = _closure1_slot2;
                var2 = _closure1_slot3;
                var1 = 4;
                var2 = var2[var1];
                var1 = undefined;
                var3 = var3.bind(var1)(var2);
                var2 = var3.validateMultiAccountTokens;
                var2 = var2.bind(var3)();
                return var1;
            };
            var2 = var3.bind(var4)(var2);
            return var1;
        };
        var2 = new Array(0);
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['useMultiAccountUsers'] = var2;
    return var1;
})();