// app/modules/multi_account/useMultiAccount.tsx
export default (function(_, argBar, argBaz, argCorge, __, argFred, argPlugh) {
    report = argBar;
    golf = argBaz;
    options = argCorge;
    zulu = argFred;
    oscar = argPlugh;
    var _closure1_slot0 = report;
    var _closure1_slot1 = golf;
    var _closure1_slot2 = options;
    var _closure1_slot3 = oscar;
    entity = global;
    offset = entity.Object;
    verify = offset.defineProperty;
    tango = {};
    entity = true;
    tango['value'] = entity;
    entity = '__esModule';
    entity = verify.bind(offset)(zulu, entity, tango);
    entity = 0;
    tango = oscar[entity];
    entity = undefined;
    tango = options.bind(entity)(tango);
    var _closure1_slot4 = tango;
    tango = 1;
    tango = oscar[tango];
    tango = golf.bind(entity)(tango);
    var _closure1_slot5 = tango;
    tango = 5;
    tango = oscar[tango];
    oscar = report.bind(entity)(tango);
    report = oscar.fileFinishedImporting;
    tango = 'modules/multi_account/useMultiAccount.tsx';
    tango = report.bind(oscar)(tango);
    mike = function() { // Original name: useMultiAccountUsers
        report = _closure1_slot0;
        tango = _closure1_slot3;
        entity = 2;
        tango = tango[entity];
        entity = undefined;
        oscar = report.bind(entity)(tango);
        report = oscar.useStateFromStoresObject;
        entity = _closure1_slot5;
        tango = new Array(1);
        tango[0] = entity;
        entity = function() {
            entity = {};
            zulu = _closure1_slot5;
            mike = zulu.getIsValidatingUsers;
            mike = mike.bind(zulu)();
            entity['isLoading'] = mike;
            mike = zulu.getUsers;
            mike = mike.bind(zulu)();
            entity['multiAccountUsers'] = mike;
            return entity;
        };
        entity = report.bind(oscar)(tango, entity);
        report = _closure1_slot4;
        tango = report.useEffect;
        zulu = function() {
            zulu = _closure1_slot1;
            mike = _closure1_slot3;
            entity = 3;
            mike = mike[entity];
            entity = undefined;
            tango = zulu.bind(entity)(mike);
            zulu = tango.wait;
            mike = function() {
                zulu = _closure1_slot2;
                mike = _closure1_slot3;
                entity = 4;
                mike = mike[entity];
                entity = undefined;
                zulu = zulu.bind(entity)(mike);
                mike = zulu.validateMultiAccountTokens;
                mike = mike.bind(zulu)();
                return entity;
            };
            mike = zulu.bind(tango)(mike);
            return entity;
        };
        mike = new Array(0);
        mike = tango.bind(report)(zulu, mike);
        return entity;
    };
    zulu['useMultiAccountUsers'] = mike;
    return entity;
})();