// app/modules/guild_progress/native/action_sheet/GuildProgressActionSheet.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var6 = require;
    var15 = metroImportDefault;
    var3 = exports;
    var7 = dependencyMap;
    var _closure1_slot0 = var6;
    var _closure1_slot1 = var15;
    var _closure1_slot2 = var7;
    var2 = function GuildProgressHeader(arg1) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var1 = arg1;
            var14 = var1.title;
            var9 = var1.subtitle;
            var19 = var1.percentCompleted;
            var1 = _closure1_slot16;
            var4 = undefined;
            var10 = var1.bind(var4)();
            var3 = _closure1_slot15;
            var2 = _closure1_slot5;
            var1 = {};
            var5 = var10.header;
            var1['style'] = var5;
            var12 = _closure1_slot15;
            var8 = _closure1_slot5;
            var5 = {};
            var7 = var10.progress;
            var5['style'] = var7;
            var13 = _closure1_slot14;
            var11 = _closure1_slot1;
            var15 = _closure1_slot2;
            var7 = 31;
            var7 = var15[var7];
            var11 = var11.bind(var4)(var7);
            var7 = {};
            var15 = 96;
            var7['size'] = var15;
            var7['percent'] = var19;
            var7 = var13.bind(var4)(var11, var7);
            var13 = new Array(3);
            var13[0] = var7;
            var15 = _closure1_slot14;
            var11 = _closure1_slot5;
            var7 = {};
            var17 = var10.progressCenter;
            var16 = new Array(2);
            var16[0] = var17;
            var18 = 100;
            var17 = null;
            if(!(var18 === var19)) { _fun0001_ip = 2; continue _fun0001 }
case 3:
            var17 = var10.progressCenterCompleted;
case 2:
            var16[1] = var17;
            var7['style'] = var16;
            var7 = var15.bind(var4)(var11, var7);
            var13[1] = var7;
            var18 = _closure1_slot14;
            var15 = _closure1_slot1;
            var11 = _closure1_slot2;
            var7 = 32;
            var16 = var11[var7];
            var17 = var15.bind(var4)(var16);
            var16 = {};
            var19 = var10.progressArt;
            var16['style'] = var19;
            var19 = 33;
            var19 = var11[var19];
            var19 = var15.bind(var4)(var19);
            var16['source'] = var19;
            var16 = var18.bind(var4)(var17, var16);
            var13[2] = var16;
            var5['children'] = var13;
            var8 = var12.bind(var4)(var8, var5);
            var5 = new Array(4);
            var5[0] = var8;
            var12 = _closure1_slot14;
            var7 = var11[var7];
            var8 = var15.bind(var4)(var7);
            var7 = {};
            var13 = var10.progressSparkles;
            var7['style'] = var13;
            var13 = 34;
            var13 = var11[var13];
            var13 = var15.bind(var4)(var13);
            var7['source'] = var13;
            var7 = var12.bind(var4)(var8, var7);
            var5[1] = var7;
            var13 = _closure1_slot14;
            var7 = _closure1_slot0;
            var8 = 26;
            var8 = var11[var8];
            var8 = var7.bind(var4)(var8);
            var12 = var8.Text;
            var8 = {'style': null, 'variant': 'heading-xl/extrabold', 'color': 'header-primary', 'accessibilityRole': 'header'};
            var15 = var10.headerTitle;
            var8['style'] = var15;
            var8['children'] = var14;
            var8 = var13.bind(var4)(var12, var8);
            var5[2] = var8;
            var8 = _closure1_slot14;
            var6 = 35;
            var6 = var11[var6];
            var6 = var7.bind(var4)(var6);
            var7 = var6.LegacyText;
            var6 = {};
            var10 = var10.headerSubtitle;
            var6['style'] = var10;
            var6['children'] = var9;
            var6 = var8.bind(var4)(var7, var6);
            var5[3] = var6;
            var1['children'] = var5;
            var1 = var3.bind(var4)(var2, var1);
            return var1;
        }
    };
    var _closure1_slot17 = var2;
    var1 = global;
    var9 = var1.Object;
    var8 = var9.defineProperty;
    var5 = {};
    var1 = true;
    var5['value'] = var1;
    var1 = '__esModule';
    var1 = var8.bind(var9)(var3, var1, var5);
    var1 = 0;
    var5 = var7[var1];
    var1 = undefined;
    var5 = var15.bind(var1)(var5);
    var _closure1_slot3 = var5;
    var11 = 1;
    var8 = var7[var11];
    var5 = metroImportAll;
    var5 = var5.bind(var1)(var8);
    var _closure1_slot4 = var5;
    var5 = 2;
    var5 = var7[var5];
    var5 = var6.bind(var1)(var5);
    var5 = var5.View;
    var _closure1_slot5 = var5;
    var5 = 3;
    var5 = var7[var5];
    var5 = var15.bind(var1)(var5);
    var _closure1_slot6 = var5;
    var13 = 4;
    var5 = var7[var13];
    var5 = var15.bind(var1)(var5);
    var _closure1_slot7 = var5;
    var5 = 5;
    var5 = var7[var5];
    var5 = var6.bind(var1)(var5);
    var8 = var5.AnalyticsSetupTypes;
    var _closure1_slot8 = var8;
    var5 = var5.AnalyticsActions;
    var _closure1_slot9 = var5;
    var5 = 6;
    var5 = var7[var5];
    var5 = var6.bind(var1)(var5);
    var8 = var5.UPLOAD_MEDIUM_SIZE;
    var _closure1_slot10 = var8;
    var8 = var5.AnalyticEvents;
    var _closure1_slot11 = var8;
    var8 = var5.ComponentActions;
    var _closure1_slot12 = var8;
    var5 = var5.InstantInviteSources;
    var _closure1_slot13 = var5;
    var5 = 7;
    var5 = var7[var5];
    var5 = var6.bind(var1)(var5);
    var8 = var5.jsx;
    var _closure1_slot14 = var8;
    var5 = var5.jsxs;
    var _closure1_slot15 = var5;
    var5 = 8;
    var5 = var7[var5];
    var9 = var6.bind(var1)(var5);
    var8 = var9.createStyles;
    var5 = {};
    var10 = {};
    var12 = 16;
    var10['padding'] = var12;
    var5['container'] = var10;
    var12 = 'center';
    var10 = {'alignItems': 'center', 'paddingTop': 8, 'paddingBottom': 16};
    var5['header'] = var10;
    var10 = {'justifyContent': 'center', 'alignItems': 'center', 'position': 'relative', 'marginBottom': 12};
    var5['progress'] = var10;
    var10 = {'position': 'absolute', 'backgroundColor': null, 'width': 84, 'height': 84, 'borderRadius': 44};
    var14 = 9;
    var14 = var7[var14];
    var14 = var6.bind(var1)(var14);
    var14 = var14.PROGRESS_BACKGROUND_COLOR;
    var10['backgroundColor'] = var14;
    var5['progressCenter'] = var10;
    var10 = {};
    var14 = 10;
    var16 = var7[var14];
    var16 = var15.bind(var1)(var16);
    var16 = var16.colors;
    var16 = var16.BG_BRAND;
    var10['backgroundColor'] = var16;
    var5['progressCenterCompleted'] = var10;
    var10 = {'position': 'absolute', 'width': 56, 'height': 46};
    var5['progressArt'] = var10;
    var10 = {'position': 'absolute', 'top': 8, 'width': 160, 'height': 51};
    var5['progressSparkles'] = var10;
    var10 = {'marginBottom': 8, 'textAlign': 'center'};
    var5['headerTitle'] = var10;
    var10 = {'fontSize': 14, 'fontWeight': '500'};
    var14 = var7[var14];
    var14 = var15.bind(var1)(var14);
    var14 = var14.colors;
    var14 = var14.HEADER_SECONDARY;
    var10['color'] = var14;
    var5['headerSubtitle'] = var10;
    var10 = {};
    var10['marginTop'] = var13;
    var5['footer'] = var10;
    var10 = {};
    var10['alignItems'] = var12;
    var5['center'] = var10;
    var10 = {};
    var10['flex'] = var11;
    var5['button'] = var10;
    var5 = var8.bind(var9)(var5);
    var _closure1_slot16 = var5;
    var5 = 36;
    var5 = var7[var5];
    var7 = var6.bind(var1)(var5);
    var6 = var7.fileFinishedImporting;
    var5 = 'modules/guild_progress/native/action_sheet/GuildProgressActionSheet.tsx';
    var5 = var6.bind(var7)(var5);
    var4 = function GuildProgressActionSheet(arg1) {
        _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
case 0:
            var1 = arg1;
            var2 = var1.guild;
            var _closure2_slot0 = var2;
            var1 = _closure1_slot16;
            var4 = undefined;
            var13 = var1.bind(var4)();
            var17 = _closure1_slot0;
            var16 = _closure1_slot2;
            var3 = 11;
            var1 = var16[var3];
            var8 = var17.bind(var4)(var1);
            var7 = var8.useStateFromStores;
            var1 = _closure1_slot7;
            var6 = new Array(1);
            var6[0] = var1;
            var1 = function() {
                var3 = _closure1_slot7;
                var2 = var3.getDefaultChannel;
                var1 = _closure2_slot0;
                var1 = var1.id;
                var1 = var2.bind(var3)(var1);
                return var1;
            };
            var1 = var7.bind(var8)(var6, var1);
            var _closure2_slot1 = var1;
            var1 = 9;
            var6 = var16[var1];
            var7 = var17.bind(var4)(var6);
            var6 = var7.useIOSCompletionStates;
            var6 = var6.bind(var7)(var2);
            var7 = var6.guildPopulated;
            var12 = var6.guildPersonalized;
            var11 = var6.guildMessaged;
            var23 = var6.numFinished;
            var _closure2_slot2 = var23;
            var22 = var6.totalSteps;
            var _closure2_slot3 = var22;
            var3 = var16[var3];
            var9 = var17.bind(var4)(var3);
            var8 = var9.useStateFromStoresObject;
            var3 = _closure1_slot6;
            var6 = new Array(1);
            var6[0] = var3;
            var3 = function() {
                var2 = _closure1_slot6;
                var1 = var2.getErrors;
                var1 = var1.bind(var2)();
                return var1;
            };
            var3 = var8.bind(var9)(var6, var3);
            var _closure2_slot4 = var3;
            var2 = var2.id;
            var _closure2_slot5 = var2;
            var8 = _closure1_slot4;
            var9 = var8.useLayoutEffect;
            var3 = var3.message;
            var6 = new Array(1);
            var6[0] = var3;
            var3 = function() {
                _fun0003: for(var _fun0003_ip = 0; ; ) switch(_fun0003_ip) {
case 0:
                    var2 = _closure2_slot4;
                    var3 = var2.message;
                    var2 = null;
                    if(!(var2 != var3)) { _fun0003_ip = 4; continue _fun0003 }
case 5:
                    var4 = _closure1_slot0;
                    var3 = _closure1_slot2;
                    var2 = 12;
                    var3 = var3[var2];
                    var2 = undefined;
                    var3 = var4.bind(var2)(var3);
                    var2 = var3.presentError;
                    var1 = _closure2_slot4;
                    var1 = var1.message;
                    var1 = var2.bind(var3)(var1);
case 4:
                    var1 = undefined;
                    return var1;
                }
            };
            var3 = var9.bind(var8)(var3, var6);
            var9 = var8.useEffect;
            var6 = new Array(1);
            var6[0] = var2;
            var3 = function() {
                var4 = _closure1_slot1;
                var3 = _closure1_slot2;
                var1 = 13;
                var3 = var3[var1];
                var1 = undefined;
                var5 = var4.bind(var1)(var3);
                var4 = var5.track;
                var2 = _closure1_slot11;
                var3 = var2.OPEN_POPOUT;
                var2 = {};
                var6 = 'Guild Progress Sheet';
                var2['type'] = var6;
                var6 = _closure2_slot5;
                var2['guild_id'] = var6;
                var2 = var4.bind(var5)(var3, var2);
                return var1;
            };
            var3 = var9.bind(var8)(var3, var6);
            var6 = var8.useEffect;
            var3 = new Array(3);
            var3[0] = var2;
            var3[1] = var22;
            var3[2] = var23;
            var2 = function() {
                _fun0004: for(var _fun0004_ip = 0; ; ) switch(_fun0004_ip) {
case 0:
                    var3 = _closure2_slot2;
                    var2 = _closure2_slot3;
                    if(!(var3 === var2)) { _fun0004_ip = 6; continue _fun0004 }
case 7:
                    var4 = _closure1_slot1;
                    var3 = _closure1_slot2;
                    var2 = 14;
                    var3 = var3[var2];
                    var2 = undefined;
                    var3 = var4.bind(var2)(var3);
                    var2 = var3.markCompletedProgressSeen;
                    var1 = _closure2_slot5;
                    var1 = var2.bind(var3)(var1);
case 6:
                    var1 = undefined;
                    return var1;
                }
            };
            var2 = var6.bind(var8)(var2, var3);
            var8 = _closure1_slot14;
            var14 = _closure1_slot1;
            var2 = 15;
            var3 = var16[var2];
            var6 = var14.bind(var4)(var3);
            var3 = {};
            var9 = function onPress() {
                _fun0005: for(var _fun0005_ip = 0; ; ) switch(_fun0005_ip) {
case 0:
                    var3 = _closure2_slot1;
                    var2 = null;
                    if(!(var2 != var3)) { _fun0005_ip = 8; continue _fun0005 }
case 9:
                    var4 = _closure1_slot0;
                    var3 = _closure1_slot2;
                    var2 = 16;
                    var3 = var3[var2];
                    var2 = undefined;
                    var4 = var4.bind(var2)(var3);
                    var3 = var4.showInstantInviteActionSheet;
                    var2 = _closure2_slot1;
                    var1 = {};
                    var5 = _closure1_slot13;
                    var5 = var5.GUILD_PROGRESS;
                    var1['source'] = var5;
                    var1 = var3.bind(var4)(var2, var1);
case 8:
                    var1 = undefined;
                    return var1;
                }
            };
            var3['onPress'] = var9;
            var9 = 17;
            var9 = var16[var9];
            var9 = var14.bind(var4)(var9);
            var3['source'] = var9;
            var18 = 18;
            var9 = var16[var18];
            var9 = var17.bind(var4)(var9);
            var15 = var9.intl;
            var10 = var15.string;
            var9 = var16[var18];
            var9 = var17.bind(var4)(var9);
            var9 = var9.t;
            var9 = var9.q9n0TU;
            var9 = var10.bind(var15)(var9);
            var3['title'] = var9;
            var3['isCompleted'] = var7;
            var10 = _closure1_slot8;
            var7 = var10.GUILD_PROGRESS;
            var3['analyticsSetupType'] = var7;
            var7 = _closure1_slot9;
            var9 = var7.INVITE;
            var3['analyticsAction'] = var9;
            var9 = var8.bind(var4)(var6, var3);
            var3 = function() {
                var4 = _closure1_slot3;
                var3 = undefined;
                var2 = function* () {
                    var1 = function* anon_0_() {
                        _fun0006: for(var _fun0006_ip = 0; ; ) switch(_fun0006_ip) {
case 0:
                            StartGenerator();
                            ResumeGenerator(result_out_reg=0, return_bool_out_reg=1);
                            if(var2) { _fun0006_ip = 10; continue _fun0006 }
case 11:
                            var6 = _closure1_slot1;
                            var7 = _closure1_slot2;
                            var8 = 19;
                            var2 = var7[var8];
                            var3 = undefined;
                            var10 = var6.bind(var3)(var2);
                            var9 = var10.init;
                            var2 = _closure2_slot5;
                            var2 = var9.bind(var10)(var2);
                            var9 = _closure1_slot0;
                            var2 = 9;
                            var2 = var7[var2];
                            var10 = var9.bind(var3)(var2);
                            var9 = var10.hideActionSheet;
                            var2 = _closure2_slot0;
                            var2 = var2.id;
                            var2 = var9.bind(var10)(var2);
                            var2 = 20;
                            var2 = var7[var2];
                            var7 = var6.bind(var3)(var2);
                            var6 = var7.openImagePicker;
                            var2 = {};
                            var9 = _closure1_slot10;
                            var2['size'] = var9;
                            var2 = var6.bind(var7)(var2);
                            SaveGenerator(address=126);
case 12:
                            return var2;
case 13:
                            ResumeGenerator(result_out_reg=1, return_bool_out_reg=5);
                            if(var6) { _fun0006_ip = 14; continue _fun0006 }
case 15:
                            var7 = var2.base64;
                            var6 = null;
                            if(!(var6 != var7)) { _fun0006_ip = 16; continue _fun0006 }
case 17:
                            var6 = _closure1_slot1;
                            var5 = _closure1_slot2;
                            var5 = var5[var8];
                            var6 = var6.bind(var3)(var5);
                            var5 = var6.updateIcon;
                            var4 = _closure2_slot5;
                            var4 = var5.bind(var6)(var4, var7);
case 16:
                            return var3;
case 14:
                            return var2;
case 10:
                            return var1;
                        }
                    };
                    return var1;
                };
                var2 = var4.bind(var3)(var2);
                var _closure3_slot0 = var2;
                var1 = function() {
                    var1 = undefined;
                    var4 = _closure3_slot0;
                    var3 = var4.apply;
                    var1 = arguments;
                    var2 = var1;
                    var1 = this;
                    var1 = var3.bind(var4)(var1, var2);
                    return var1;
                };
                return var1;
            };
            var15 = var3.bind(var4)();
            var8 = _closure1_slot14;
            var3 = var16[var2];
            var6 = var14.bind(var4)(var3);
            var3 = {};
            var3['onPress'] = var15;
            var15 = 21;
            var15 = var16[var15];
            var15 = var14.bind(var4)(var15);
            var3['source'] = var15;
            var15 = var16[var18];
            var15 = var17.bind(var4)(var15);
            var20 = var15.intl;
            var19 = var20.string;
            var15 = var16[var18];
            var15 = var17.bind(var4)(var15);
            var15 = var15.t;
            var15 = var15.DWB2YW;
            var15 = var19.bind(var20)(var15);
            var3['title'] = var15;
            var3['isCompleted'] = var12;
            var12 = var10.GUILD_PROGRESS;
            var3['analyticsSetupType'] = var12;
            var12 = var7.PERSONALIZE_SERVER;
            var3['analyticsAction'] = var12;
            var8 = var8.bind(var4)(var6, var3);
            var6 = _closure1_slot14;
            var2 = var16[var2];
            var3 = var14.bind(var4)(var2);
            var2 = {};
            var12 = function onPress() {
                _fun0007: for(var _fun0007_ip = 0; ; ) switch(_fun0007_ip) {
case 0:
                    var1 = _closure2_slot1;
                    var5 = null;
                    if(!(var5 != var1)) { _fun0007_ip = 18; continue _fun0007 }
case 9:
                    var3 = _closure1_slot0;
                    var2 = _closure1_slot2;
                    var1 = 22;
                    var2 = var2[var1];
                    var1 = undefined;
                    var3 = var3.bind(var1)(var2);
                    var2 = var3.transitionToChannel;
                    var1 = _closure2_slot1;
                    var1 = var1.id;
                    var1 = var2.bind(var3)(var1);
case 18:
                    var6 = _closure1_slot1;
                    var3 = _closure1_slot2;
                    var1 = 23;
                    var3 = var3[var1];
                    var1 = undefined;
                    var6 = var6.bind(var1)(var3);
                    var3 = var6.hideActionSheet;
                    var3 = var3.bind(var6)();
                    var3 = _closure2_slot1;
                    var3 = var5 != var3;
                    var5 = undefined;
                    if(!var3) { _fun0007_ip = 12; continue _fun0007 }
case 19:
                    var3 = {};
                    var4 = _closure2_slot1;
                    var4 = var4.id;
                    var3['channelId'] = var4;
                    var5 = var3;
case 12:
                    var4 = _closure1_slot0;
                    var6 = _closure1_slot2;
                    var3 = 24;
                    var3 = var6[var3];
                    var3 = var4.bind(var1)(var3);
                    var4 = var3.ComponentDispatch;
                    var3 = var4.dispatch;
                    var2 = _closure1_slot12;
                    var2 = var2.TEXTAREA_FOCUS;
                    var2 = var3.bind(var4)(var2, var5);
                    return var1;
                }
            };
            var2['onPress'] = var12;
            var12 = 25;
            var12 = var16[var12];
            var12 = var14.bind(var4)(var12);
            var2['source'] = var12;
            var12 = var16[var18];
            var12 = var17.bind(var4)(var12);
            var15 = var12.intl;
            var14 = var15.string;
            var12 = var16[var18];
            var12 = var17.bind(var4)(var12);
            var12 = var12.t;
            var12 = var12.dNktpq;
            var12 = var14.bind(var15)(var12);
            var2['title'] = var12;
            var2['isCompleted'] = var11;
            var10 = var10.GUILD_PROGRESS;
            var2['analyticsSetupType'] = var10;
            var7 = var7.SEND_MESSAGE;
            var2['analyticsAction'] = var7;
            var7 = var6.bind(var4)(var3, var2);
            var10 = var23 === var22;
            var2 = global;
            var6 = var2.Math;
            var3 = var6.max;
            var1 = var16[var1];
            var1 = var17.bind(var4)(var1);
            var2 = var1.MIN_PROGRESS_PERCENT;
            var1 = 100;
            var1 = var1 * var23;
            var1 = var1 / var22;
            var14 = var3.bind(var6)(var2, var1);
            var15 = function handleDismissGuildProgress() {
                var3 = _closure1_slot1;
                var4 = _closure1_slot2;
                var1 = 14;
                var2 = var4[var1];
                var1 = undefined;
                var9 = var3.bind(var1)(var2);
                var8 = var9.dismissProgress;
                var2 = _closure2_slot0;
                var5 = var2.id;
                var5 = var8.bind(var9)(var5);
                var5 = 23;
                var5 = var4[var5];
                var8 = var3.bind(var1)(var5);
                var5 = var8.hideActionSheet;
                var10 = var2.id;
                var2 = global;
                var2 = var2.HermesInternal;
                var9 = var2.concat;
                var2 = 'guild-progress-';
                var2 = var9.bind(var2)(var10);
                var2 = var5.bind(var8)(var2);
                var2 = 13;
                var2 = var4[var2];
                var5 = var3.bind(var1)(var2);
                var4 = var5.track;
                var2 = _closure1_slot11;
                var3 = var2.SERVER_SETUP_CTA_CLICKED;
                var2 = {};
                var8 = _closure1_slot9;
                var8 = var8.DISMISS_GUILD_PROGRESS;
                var2['action'] = var8;
                var7 = _closure1_slot8;
                var7 = var7.GUILD_PROGRESS;
                var2['setup_type'] = var7;
                var7 = _closure2_slot3;
                var2['num_total_actions'] = var7;
                var6 = _closure2_slot2;
                var2['num_actions_completed'] = var6;
                var2 = var4.bind(var5)(var3, var2);
                return var1;
            };
            var3 = _closure1_slot15;
            var2 = _closure1_slot5;
            var1 = {};
            var6 = var13.container;
            var1['style'] = var6;
            var12 = _closure1_slot14;
            var11 = _closure1_slot17;
            var6 = {};
            var19 = var16[var18];
            var19 = var17.bind(var4)(var19);
            var24 = var19.intl;
            var20 = var24.string;
            var19 = var16[var18];
            var19 = var17.bind(var4)(var19);
            var19 = var19.t;
            var19 = var19.tu/tr6;
            var19 = var20.bind(var24)(var19);
            var6['title'] = var19;
            var19 = var16[var18];
            var19 = var17.bind(var4)(var19);
            var20 = var19.intl;
            var19 = var20.format;
            var16 = var16[var18];
            var16 = var17.bind(var4)(var16);
            var16 = var16.t;
            var17 = var16.l6iRLi;
            var16 = {};
            var16['numFinished'] = var23;
            var16['total'] = var22;
            var21 = function stepsHook(arg1, arg2) {
                var5 = _closure1_slot14;
                var2 = _closure1_slot0;
                var3 = _closure1_slot2;
                var1 = 26;
                var1 = var3[var1];
                var4 = undefined;
                var1 = var2.bind(var4)(var1);
                var3 = var1.Text;
                var2 = {'variant': 'text-sm/medium', 'color': 'header-primary'};
                var1 = arg1;
                var2['children'] = var1;
                var1 = arg2;
                var1 = var5.bind(var4)(var3, var2, var1);
                return var1;
            };
            var16['stepsHook'] = var21;
            var16 = var19.bind(var20)(var17, var16);
            var6['subtitle'] = var16;
            var6['percentCompleted'] = var14;
            var11 = var12.bind(var4)(var11, var6);
            var6 = new Array(5);
            var6[0] = var11;
            var6[1] = var9;
            var6[2] = var8;
            var6[3] = var7;
            var9 = _closure1_slot14;
            var8 = _closure1_slot5;
            var7 = {};
            var12 = var13.footer;
            var11 = new Array(2);
            var11[0] = var12;
            var12 = null;
            if(var10) { _fun0002_ip = 20; continue _fun0002 }
case 21:
            var12 = var13.center;
case 20:
            var11[1] = var12;
            var7['style'] = var11;
            var13 = _closure1_slot14;
            if(var10) { _fun0002_ip = 22; continue _fun0002 }
case 23:
            var21 = _closure1_slot0;
            var17 = _closure1_slot2;
            var10 = 28;
            var10 = var17[var10];
            var10 = var21.bind(var4)(var10);
            var11 = var10.PressableOpacity;
            var10 = {};
            var12 = 'button';
            var10['accessibilityRole'] = var12;
            var10['onPress'] = var15;
            var16 = _closure1_slot14;
            var12 = 26;
            var12 = var17[var12];
            var12 = var21.bind(var4)(var12);
            var14 = var12.Text;
            var12 = {'variant': 'text-sm/medium', 'color': 'header-secondary'};
            var19 = var17[var18];
            var19 = var21.bind(var4)(var19);
            var20 = var19.intl;
            var19 = var20.string;
            var17 = var17[var18];
            var17 = var21.bind(var4)(var17);
            var17 = var17.t;
            var17 = var17.9E36wc;
            var17 = var19.bind(var20)(var17);
            var12['children'] = var17;
            var12 = var16.bind(var4)(var14, var12);
            var10['children'] = var12;
            var10 = var13.bind(var4)(var11, var10);
            _fun0002_ip = 24; continue _fun0002;
case 22:
            var12 = _closure1_slot1;
            var14 = _closure1_slot2;
            var11 = 27;
            var11 = var14[var11];
            var12 = var12.bind(var4)(var11);
            var11 = {};
            var11['onPress'] = var15;
            var17 = _closure1_slot0;
            var15 = var14[var18];
            var15 = var17.bind(var4)(var15);
            var16 = var15.intl;
            var15 = var16.string;
            var14 = var14[var18];
            var14 = var17.bind(var4)(var14);
            var14 = var14.t;
            var14 = var14.0/5zho;
            var14 = var15.bind(var16)(var14);
            var11['text'] = var14;
            var10 = var13.bind(var4)(var12, var11);
case 24:
            var7['children'] = var10;
            var7 = var9.bind(var4)(var8, var7);
            var6[4] = var7;
            var1['children'] = var6;
            var8 = var3.bind(var4)(var2, var1);
            var3 = _closure1_slot14;
            var6 = _closure1_slot0;
            var9 = _closure1_slot2;
            var1 = 29;
            var1 = var9[var1];
            var1 = var6.bind(var4)(var1);
            var2 = var1.RedesignCompat;
            var1 = {};
            var7 = _closure1_slot14;
            var5 = 30;
            var5 = var9[var5];
            var5 = var6.bind(var4)(var5);
            var6 = var5.ActionSheet;
            var5 = {'showGradient': true, 'startExpanded': true};
            var5['children'] = var8;
            var5 = var7.bind(var4)(var6, var5);
            var1['children'] = var5;
            var1 = var3.bind(var4)(var2, var1);
            return var1;
        }
    };
    var3['default'] = var4;
    var3['GuildProgressHeader'] = var2;
    return var1;
})();