// discord_common/js/shared/shared-constants/ACRequestOperations.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var3 = exports;
    var1 = global;
    var5 = var1.Object;
    var4 = var5.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var4.bind(var5)(var3, var1, var2);
    var2 = {};
    var1 = 'ac_create';
    var2['CREATE'] = var1;
    var1 = 'ac_reactivate';
    var2['REACTIVATE'] = var1;
    var1 = 'ac_charge';
    var2['CHARGE'] = var1;
    var1 = 'ac_cancel';
    var2['CANCEL'] = var1;
    var4 = dependencyMap;
    var1 = 0;
    var5 = var4[var1];
    var4 = require;
    var1 = undefined;
    var6 = var4.bind(var1)(var5);
    var5 = var6.fileFinishedImporting;
    var4 = '../discord_common/js/shared/shared-constants/ACRequestOperations.tsx';
    var4 = var5.bind(var6)(var4);
    var3['ACRequestOperations'] = var2;
    return var1;
})();