// discord_common/js/shared/shared-constants/AppCrashedReasons.tsx
export default (function(native1, native2, native3, native4, native5, native6, native7) {
    var3 = native6;
    var1 = global;
    var6 = var1.Object;
    var5 = var6.defineProperty;
    var4 = {};
    var2 = true;
    var4['value'] = var2;
    var2 = '__esModule';
    var2 = var5.bind(var6)(var3, var2, var4);
    var4 = {};
    var2 = 'unhandled_native_error';
    var4['UNHANDLED_NATIVE_ERROR'] = var2;
    var2 = 'unhandled_js_error';
    var4['UNHANDLED_JS_ERROR'] = var2;
    var2 = 'socket_crashed';
    var4['SOCKET_CRASHED'] = var2;
    var2 = {};
    var6 = var1.Set;
    var1 = var6.prototype;
    var5 = Object.create(var1, {constructor: {value: var6}});
    var10 = ['socket_crashed', 'unhandled_js_error', 'unhandled_native_error'];
    var11 = var5;
    var1 = new var11[var6](var10, var9);
    var1 = var1 instanceof Object ? var1 : var5;
    var2['ALL'] = var1;
    var5 = native7;
    var1 = 0;
    var6 = var5[var1];
    var5 = native2;
    var1 = undefined;
    var7 = var5.bind(var1)(var6);
    var6 = var7.fileFinishedImporting;
    var5 = '../discord_common/js/shared/shared-constants/AppCrashedReasons.tsx';
    var5 = var6.bind(var7)(var5);
    var3['AppCrashedReasons'] = var4;
    var3['AppCrashedReasonsSets'] = var2;
    return var1;
})();