// discord_common/js/shared/shared-constants/ApplicationWidgetLayoutName.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var3 = exports;
    var1 = global;
    var5 = var1.Object;
    var4 = var5.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var4.bind(var5)(var3, var1, var2);
    var2 = {};
    var1 = 'widget_top_hero';
    var2['WIDGET_TOP_HERO'] = var1;
    var1 = 'widget_top_contained';
    var2['WIDGET_TOP_CONTAINED'] = var1;
    var1 = 'widget_bottom_stats';
    var2['WIDGET_BOTTOM_STATS'] = var1;
    var1 = 'widget_bottom_progress';
    var2['WIDGET_BOTTOM_PROGRESS'] = var1;
    var1 = 'widget_bottom_collection';
    var2['WIDGET_BOTTOM_COLLECTION'] = var1;
    var1 = 'mini_profile_hero_stat';
    var2['MINI_PROFILE_HERO_STAT'] = var1;
    var1 = 'mini_profile_contained_stat';
    var2['MINI_PROFILE_CONTAINED_STAT'] = var1;
    var1 = 'activity_accessory_stat';
    var2['ACTIVITY_ACCESSORY_STAT'] = var1;
    var1 = 'add_widget_preview_hero';
    var2['ADD_WIDGET_PREVIEW_HERO'] = var1;
    var1 = 'add_widget_preview_contained';
    var2['ADD_WIDGET_PREVIEW_CONTAINED'] = var1;
    var4 = dependencyMap;
    var1 = 0;
    var5 = var4[var1];
    var4 = require;
    var1 = undefined;
    var6 = var4.bind(var1)(var5);
    var5 = var6.fileFinishedImporting;
    var4 = '../discord_common/js/shared/shared-constants/ApplicationWidgetLayoutName.tsx';
    var4 = var5.bind(var6)(var4);
    var3['ApplicationWidgetLayoutName'] = var2;
    return var1;
})();