// discord_common/js/shared/shared-constants/ApplicationCollectionItemFlags.tsx
export default (function(_, argBar, __, ___, ____, argFred, argPlugh) {
    zulu = argFred;
    entity = global;
    report = entity.Object;
    tango = report.defineProperty;
    mike = {};
    entity = true;
    mike['value'] = entity;
    entity = '__esModule';
    entity = tango.bind(report)(zulu, entity, mike);
    mike = {};
    tango = 1;
    mike['PROMOTED'] = tango;
    entity = 'PROMOTED';
    mike[tango] = entity;
    tango = 2;
    mike['SKIPS_APPLICATION_DISCOVERABILITY_VALIDATION'] = tango;
    entity = 'SKIPS_APPLICATION_DISCOVERABILITY_VALIDATION';
    mike[tango] = entity;
    tango = 0;
    mike['DEFAULT'] = tango;
    entity = 'DEFAULT';
    mike[tango] = entity;
    entity = argPlugh;
    report = entity[tango];
    tango = argBar;
    entity = undefined;
    oscar = tango.bind(entity)(report);
    report = oscar.fileFinishedImporting;
    tango = '../discord_common/js/shared/shared-constants/ApplicationCollectionItemFlags.tsx';
    tango = report.bind(oscar)(tango);
    zulu['ApplicationCollectionItemFlags'] = mike;
    return entity;
})();