// discord_common/js/shared/shared-constants/ApplicationDirectorySearchResultType.tsx
export default (function(_, argBar, __, ___, ____, argFre, argPlu) {
    zuuluu = argFre;
    entity = global;
    report = entity.Object;
    tangon = report.defineProperty;
    michal = {};
    entity = true;
    michal['value'] = entity;
    entity = '__esModule';
    entity = tangon.bind(report)(zuuluu, entity, michal);
    michal = {};
    tangon = 1;
    michal['APPLICATION'] = tangon;
    entity = 'APPLICATION';
    michal[tangon] = entity;
    tangon = 2;
    michal['ACTIVITY_APPLICATION'] = tangon;
    entity = 'ACTIVITY_APPLICATION';
    michal[tangon] = entity;
    tangon = 3;
    michal['CONNECTION'] = tangon;
    entity = 'CONNECTION';
    michal[tangon] = entity;
    tangon = argPlu;
    entity = 0;
    report = tangon[entity];
    tangon = argBar;
    entity = undefined;
    oscard = tangon.bind(entity)(report);
    report = oscard.fileFinishedImporting;
    tangon = '../discord_common/js/shared/shared-constants/ApplicationDirectorySearchResultType.tsx';
    tangon = report.bind(oscard)(tangon);
    zuuluu['ApplicationDirectorySearchResultType'] = michal;
    return entity;
})();