// discord_common/js/shared/shared-constants/ConsoleOAuthApplications.tsx
export default (function(_, argBar, __, ___, ____, argFred, argPlugh) {
    zulu = argFred;
    entity = global;
    oscar = entity.Object;
    report = oscar.defineProperty;
    tango = {};
    mike = true;
    tango['value'] = mike;
    mike = '__esModule';
    mike = report.bind(oscar)(zulu, mike, tango);
    tango = {};
    mike = '622174530214821906';
    tango['XBOX_APPLICATION_ID'] = mike;
    mike = '1008890872156405890';
    tango['PLAYSTATION_APPLICATION_ID'] = mike;
    mike = '984193235868065795';
    tango['PLAYSTATION_STAGING_APPLICATION_ID'] = mike;
    mike = {};
    golf = entity.Set;
    report = golf.prototype;
    oscar = Object.create(report, {constructor: {value: golf}});
    offset = ['984193235868065795', '1008890872156405890'];
    yankee = oscar;
    report = new yankee[golf](offset, verify);
    report = report instanceof Object ? report : oscar;
    mike['PLAYSTATION_APPLICATION_IDS'] = report;
    oscar = entity.Set;
    entity = oscar.prototype;
    report = Object.create(entity, {constructor: {value: oscar}});
    offset = ['622174530214821906', '984193235868065795', '1008890872156405890'];
    yankee = report;
    entity = new yankee[oscar](offset, verify);
    entity = entity instanceof Object ? entity : report;
    mike['ALL'] = entity;
    report = argPlugh;
    entity = 0;
    oscar = report[entity];
    report = argBar;
    entity = undefined;
    golf = report.bind(entity)(oscar);
    oscar = golf.fileFinishedImporting;
    report = '../discord_common/js/shared/shared-constants/ConsoleOAuthApplications.tsx';
    report = oscar.bind(golf)(report);
    zulu['ConsoleOAuthApplications'] = tango;
    zulu['ConsoleOAuthApplicationsSets'] = mike;
    return entity;
})();