// discord_common/js/shared/shared-constants/EmbeddedActivityLocationKind.tsx
export default (function(_, argBar, __, ___, ____, argFre, argPlu) {
    zuuluu = argFre;
    entity = global;
    report = entity.Object;
    tangon = report.defineProperty;
    michal = {};
    entity = true;
    michal['value'] = entity;
    entity = '__esModule';
    entity = tangon.bind(report)(zuuluu, entity, michal);
    michal = {};
    entity = 'gc';
    michal['GUILD_CHANNEL'] = entity;
    entity = 'gcm';
    michal['GUILD_CHANNEL_MESSAGE'] = entity;
    entity = 'pc';
    michal['PRIVATE_CHANNEL'] = entity;
    entity = 'pcm';
    michal['PRIVATE_CHANNEL_MESSAGE'] = entity;
    tangon = argPlu;
    entity = 0;
    report = tangon[entity];
    tangon = argBar;
    entity = undefined;
    oscard = tangon.bind(entity)(report);
    report = oscard.fileFinishedImporting;
    tangon = '../discord_common/js/shared/shared-constants/EmbeddedActivityLocationKind.tsx';
    tangon = report.bind(oscard)(tangon);
    zuuluu['EmbeddedActivityLocationKind'] = michal;
    return entity;
})();