// discord_common/js/shared/shared-constants/EmbeddedActivityLocationKind.tsx
export default (function(native1, native2, native3, native4, native5, native6, native7) {
    var3 = native6;
    var1 = global;
    var5 = var1.Object;
    var4 = var5.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var4.bind(var5)(var3, var1, var2);
    var2 = {};
    var1 = 'gc';
    var2['GUILD_CHANNEL'] = var1;
    var1 = 'gcm';
    var2['GUILD_CHANNEL_MESSAGE'] = var1;
    var1 = 'pc';
    var2['PRIVATE_CHANNEL'] = var1;
    var1 = 'pcm';
    var2['PRIVATE_CHANNEL_MESSAGE'] = var1;
    var4 = native7;
    var1 = 0;
    var5 = var4[var1];
    var4 = native2;
    var1 = undefined;
    var6 = var4.bind(var1)(var5);
    var5 = var6.fileFinishedImporting;
    var4 = '../discord_common/js/shared/shared-constants/EmbeddedActivityLocationKind.tsx';
    var4 = var5.bind(var6)(var4);
    var3['EmbeddedActivityLocationKind'] = var2;
    return var1;
})();