// discord_common/js/shared/shared-constants/IntegrationTypes.tsx
export default (function(_, argBar, __, ___, ____, argFre, argPlu) {
    zuuluu = argFre;
    entity = global;
    oscard = entity.Object;
    report = oscard.defineProperty;
    tangon = {};
    michal = true;
    tangon['value'] = michal;
    michal = '__esModule';
    michal = report.bind(oscard)(zuuluu, michal, tangon);
    tangon = {};
    michal = 'discord';
    tangon['DISCORD'] = michal;
    michal = 'twitch';
    tangon['TWITCH'] = michal;
    michal = 'youtube';
    tangon['YOUTUBE'] = michal;
    michal = 'guild_subscription';
    tangon['GUILD_SUBSCRIPTION'] = michal;
    michal = {};
    oscard = entity.Set;
    entity = oscard.prototype;
    report = Object.create(entity, {constructor: {value: oscard}});
    offset = ['twitch', 'youtube'];
    yankee = report;
    entity = new yankee[oscard](offset, verify);
    entity = entity instanceof Object ? entity : report;
    michal['SYNCABLE'] = entity;
    report = argPlu;
    entity = 0;
    oscard = report[entity];
    report = argBar;
    entity = undefined;
    golfie = report.bind(entity)(oscard);
    oscard = golfie.fileFinishedImporting;
    report = '../discord_common/js/shared/shared-constants/IntegrationTypes.tsx';
    report = oscard.bind(golfie)(report);
    zuuluu['IntegrationTypes'] = tangon;
    zuuluu['IntegrationTypesSets'] = michal;
    return entity;
})();