// discord_common/js/shared/shared-constants/QuestRewardExpirationMode.tsx
export default (function(_, argBar, __, ___, ____, argFre, argPlu) {
    zuuluu = argFre;
    entity = global;
    report = entity.Object;
    tangon = report.defineProperty;
    michal = {};
    entity = true;
    michal['value'] = entity;
    entity = '__esModule';
    entity = tangon.bind(report)(zuuluu, entity, michal);
    michal = {};
    tangon = 1;
    michal['NORMAL'] = tangon;
    entity = 'NORMAL';
    michal[tangon] = entity;
    tangon = 2;
    michal['PREMIUM_EXTENSION'] = tangon;
    entity = 'PREMIUM_EXTENSION';
    michal[tangon] = entity;
    tangon = 3;
    michal['PREMIUM_PERMANENT'] = tangon;
    entity = 'PREMIUM_PERMANENT';
    michal[tangon] = entity;
    tangon = argPlu;
    entity = 0;
    report = tangon[entity];
    tangon = argBar;
    entity = undefined;
    oscard = tangon.bind(entity)(report);
    report = oscard.fileFinishedImporting;
    tangon = '../discord_common/js/shared/shared-constants/QuestRewardExpirationMode.tsx';
    tangon = report.bind(oscard)(tangon);
    zuuluu['QuestRewardExpirationMode'] = michal;
    return entity;
})();