// discord_common/js/shared/shared-constants/QuestRewardCodePlatforms.tsx
export default (function(_, argBar, __, ___, ____, argFred, argPlugh) {
    zulu = argFred;
    entity = global;
    report = entity.Object;
    tango = report.defineProperty;
    mike = {};
    entity = true;
    mike['value'] = entity;
    entity = '__esModule';
    entity = tango.bind(report)(zulu, entity, mike);
    mike = {};
    tango = 0;
    mike['CROSS_PLATFORM'] = tango;
    entity = 'CROSS_PLATFORM';
    mike[tango] = entity;
    report = 1;
    mike['XBOX'] = report;
    entity = 'XBOX';
    mike[report] = entity;
    report = 2;
    mike['PLAYSTATION'] = report;
    entity = 'PLAYSTATION';
    mike[report] = entity;
    report = 3;
    mike['SWITCH'] = report;
    entity = 'SWITCH';
    mike[report] = entity;
    report = 4;
    mike['PC'] = report;
    entity = 'PC';
    mike[report] = entity;
    entity = argPlugh;
    report = entity[tango];
    tango = argBar;
    entity = undefined;
    oscar = tango.bind(entity)(report);
    report = oscar.fileFinishedImporting;
    tango = '../discord_common/js/shared/shared-constants/QuestRewardCodePlatforms.tsx';
    tango = report.bind(oscar)(tango);
    zulu['QuestRewardCodePlatforms'] = mike;
    return entity;
})();