// discord_common/js/shared/shared-constants/SurveyActionTypes.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var3 = exports;
    var1 = global;
    var5 = var1.Object;
    var4 = var5.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var4.bind(var5)(var3, var1, var2);
    var2 = {};
    var1 = 'nitro_unsubbed';
    var2['NITRO_UNSUBBED'] = var1;
    var1 = 'checkpoint_completed';
    var2['CHECKPOINT_COMPLETED'] = var1;
    var1 = 'quest_completed';
    var2['QUEST_COMPLETED'] = var1;
    var1 = 'warp_vpn_coachmark_dismissed_nitro';
    var2['WARP_VPN_COACHMARK_DISMISSED_NITRO'] = var1;
    var1 = 'warp_vpn_coachmark_dismissed_non_nitro';
    var2['WARP_VPN_COACHMARK_DISMISSED_NON_NITRO'] = var1;
    var1 = 'warp_vpn_settings_bounce_nitro';
    var2['WARP_VPN_SETTINGS_BOUNCE_NITRO'] = var1;
    var1 = 'warp_vpn_settings_bounce_non_nitro';
    var2['WARP_VPN_SETTINGS_BOUNCE_NON_NITRO'] = var1;
    var4 = dependencyMap;
    var1 = 0;
    var5 = var4[var1];
    var4 = require;
    var1 = undefined;
    var6 = var4.bind(var1)(var5);
    var5 = var6.fileFinishedImporting;
    var4 = '../discord_common/js/shared/shared-constants/SurveyActionTypes.tsx';
    var4 = var5.bind(var6)(var4);
    var3['SurveyActionTypes'] = var2;
    return var1;
})();