// discord_common/js/shared/shared-constants/TrendingType.tsx
export default (function(_, argBar, __, ___, ____, argFre, argPlu) {
    zuuluu = argFre;
    entity = global;
    report = entity.Object;
    tangon = report.defineProperty;
    michal = {};
    entity = true;
    michal['value'] = entity;
    entity = '__esModule';
    entity = tangon.bind(report)(zuuluu, entity, michal);
    michal = {};
    tangon = 0;
    michal['TRENDING_TYPE_UNSPECIFIED'] = tangon;
    entity = 'TRENDING_TYPE_UNSPECIFIED';
    michal[tangon] = entity;
    report = 1;
    michal['GLOBAL'] = report;
    entity = 'GLOBAL';
    michal[report] = entity;
    entity = argPlu;
    report = entity[tangon];
    tangon = argBar;
    entity = undefined;
    oscard = tangon.bind(entity)(report);
    report = oscard.fileFinishedImporting;
    tangon = '../discord_common/js/shared/shared-constants/TrendingType.tsx';
    tangon = report.bind(oscard)(tangon);
    zuuluu['TrendingType'] = michal;
    return entity;
})();