// app/modules/guild_role_subscriptions/GuildRoleSubscriptionsModalActionCreators.native.tsx
export default (function(argFoo, argBar, argBaz, argCorge, _, argFred, argPlugh) {
    report = argBar;
    zulu = argFred;
    oscar = argPlugh;
    var _closure1_slot0 = report;
    entity = argBaz;
    var _closure1_slot1 = entity;
    var _closure1_slot2 = oscar;
    entity = global;
    options = entity.Object;
    golf = options.defineProperty;
    tango = {};
    entity = true;
    tango['value'] = entity;
    entity = '__esModule';
    entity = golf.bind(options)(zulu, entity, tango);
    entity = 0;
    golf = oscar[entity];
    tango = argCorge;
    entity = undefined;
    tango = tango.bind(entity)(golf);
    var _closure1_slot3 = tango;
    tango = 5;
    tango = oscar[tango];
    oscar = report.bind(entity)(tango);
    report = oscar.fileFinishedImporting;
    tango = 'modules/guild_role_subscriptions/GuildRoleSubscriptionsModalActionCreators.native.tsx';
    tango = report.bind(oscar)(tango);
    tango = function(argFoo) { // Original name: showCreateBenefitModal
        entity = argFoo;
        options = entity.guildId;
        mike = entity.listingId;
        verify = entity.type;
        golf = entity.onSave;
        zulu = _closure1_slot3;
        entity = zulu.resetImperatively;
        entity = entity.bind(zulu)();
        oscar = _closure1_slot1;
        zulu = _closure1_slot2;
        entity = 1;
        report = zulu[entity];
        entity = undefined;
        oscar = oscar.bind(entity)(report);
        report = oscar.pushLazy;
        offset = _closure1_slot0;
        tango = 3;
        tango = zulu[tango];
        offset = offset.bind(entity)(tango);
        tango = 2;
        tango = zulu[tango];
        zulu = zulu.paths;
        tango = offset.bind(entity)(tango, zulu);
        zulu = {};
        zulu['benefitType'] = verify;
        zulu['guildId'] = options;
        zulu['onSave'] = golf;
        zulu['listingId'] = mike;
        mike = 'GuildRoleSubscriptionBenefitEditorModal';
        mike = report.bind(oscar)(tango, zulu, mike);
        return entity;
    };
    zulu['showCreateBenefitModal'] = tango;
    tango = function(argFoo) { // Original name: showEditBenefitModal
        entity = argFoo;
        verify = entity.guildId;
        offset = entity.benefit;
        mike = entity.listingId;
        options = entity.onDelete;
        golf = entity.onSave;
        zulu = _closure1_slot3;
        entity = zulu.initializeImperatively;
        entity = entity.bind(zulu)(offset);
        oscar = _closure1_slot1;
        zulu = _closure1_slot2;
        entity = 1;
        report = zulu[entity];
        entity = undefined;
        oscar = oscar.bind(entity)(report);
        report = oscar.pushLazy;
        yankee = _closure1_slot0;
        tango = 3;
        tango = zulu[tango];
        yankee = yankee.bind(entity)(tango);
        tango = 2;
        tango = zulu[tango];
        zulu = zulu.paths;
        tango = yankee.bind(entity)(tango, zulu);
        zulu = {};
        offset = offset.ref_type;
        zulu['benefitType'] = offset;
        zulu['guildId'] = verify;
        zulu['onDelete'] = options;
        zulu['onSave'] = golf;
        zulu['listingId'] = mike;
        mike = 'GuildRoleSubscriptionBenefitEditorModal';
        mike = report.bind(oscar)(tango, zulu, mike);
        return entity;
    };
    zulu['showEditBenefitModal'] = tango;
    mike = function(argFoo) { // Original name: showEditEmojisModal
        _fun00001: for(var _fun00002_ip = 0; ; ) switch(_fun00002_ip) {
 0:
            entity = argFoo;
            offset = entity.guildId;
            verify = entity.subscriptionRoleId;
            golf = entity.listingId;
            options = entity.initialTierEmojiIds;
            mike = entity.onSave;
            oscar = _closure1_slot1;
            zulu = _closure1_slot2;
            entity = 1;
            report = zulu[entity];
            entity = undefined;
            oscar = oscar.bind(entity)(report);
            report = oscar.pushLazy;
            yankee = _closure1_slot0;
            tango = 3;
            tango = zulu[tango];
            yankee = yankee.bind(entity)(tango);
            tango = 4;
            tango = zulu[tango];
            zulu = zulu.paths;
            tango = yankee.bind(entity)(tango, zulu);
            zulu = {};
            zulu['guildId'] = offset;
            zulu['subscriptionRoleId'] = verify;
            verify = null;
            if(!(verify == options)) { _fun00002_ip = 142; continue _fun00001 }
 114:
            verify = global;
            verify = verify.Set;
            offset = verify.prototype;
            offset = Object.create(offset, {constructor: {value: verify}});
            kilo = offset;
            verify = new kilo[verify](backup);
            options = verify instanceof Object ? verify : offset;
 142:
            zulu['initialTierEmojiIds'] = options;
            zulu['listingId'] = golf;
            zulu['onSave'] = mike;
            mike = 'GuildRoleSubscriptionEmojiEditorModal';
            mike = report.bind(oscar)(tango, zulu, mike);
            return entity;
        }
    };
    zulu['showEditEmojisModal'] = mike;
    return entity;
})();