// app/modules/webauthn/native/WebAuthnScreens.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var1 = metroImportDefault;
    var _closure1_slot1 = var1;
    var _closure1_slot2 = var6;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var5.bind(var1)(var4);
    var4 = var4.WebAuthnScreens;
    var _closure1_slot3 = var4;
    var4 = 1;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.jsx;
    var _closure1_slot4 = var4;
    var4 = 11;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/webauthn/native/WebAuthnScreens.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function getScreens(arg1) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var1 = arg1;
            var7 = var1.isModal;
            var1 = {};
            var2 = _closure1_slot3;
            var6 = var2.MODAL_UPSELL;
            var3 = {};
            var8 = '';
            var3['title'] = var8;
            var8 = function render() {
                var4 = _closure1_slot4;
                var2 = _closure1_slot1;
                var3 = _closure1_slot2;
                var1 = 2;
                var1 = var3[var1];
                var3 = undefined;
                var2 = var2.bind(var3)(var1);
                var1 = {};
                var1 = var4.bind(var3)(var2, var1);
                return var1;
            };
            var3['render'] = var8;
            var1[5] = var3;
            var3 = var2.INIT;
            var2 = {};
            var12 = _closure1_slot0;
            var6 = _closure1_slot2;
            var9 = 3;
            var10 = var6[var9];
            var8 = undefined;
            var10 = var12.bind(var8)(var10);
            var11 = var10.intl;
            var10 = var11.string;
            var6 = var6[var9];
            var6 = var12.bind(var8)(var6);
            var6 = var6.t;
            var6 = var6["0N1s81"];
            var6 = var10.bind(var11)(var6);
            var2['title'] = var6;
            var6 = function render() {
                var4 = _closure1_slot4;
                var2 = _closure1_slot1;
                var3 = _closure1_slot2;
                var1 = 4;
                var1 = var3[var1];
                var3 = undefined;
                var2 = var2.bind(var3)(var1);
                var1 = {};
                var1 = var4.bind(var3)(var2, var1);
                return var1;
            };
            var2['render'] = var6;
            var6 = undefined;
            if(!var7) { _fun0001_ip = 2; continue _fun0001 }
case 3:
            var11 = _closure1_slot0;
            var14 = _closure1_slot2;
            var10 = 5;
            var10 = var14[var10];
            var12 = var11.bind(var8)(var10);
            var11 = var12.getHeaderCloseButton;
            var13 = _closure1_slot1;
            var10 = 6;
            var10 = var14[var10];
            var10 = var13.bind(var8)(var10);
            var10 = var10.closePasskeyUpsellModal;
            var6 = var11.bind(var12)(var10);
case 2:
            var2['headerLeft'] = var6;
            var1[2] = var2;
            var2 = _closure1_slot3;
            var10 = var2.EDIT;
            var3 = {};
            var6 = function render(arg1) {
                var4 = _closure1_slot4;
                var2 = _closure1_slot1;
                var3 = _closure1_slot2;
                var1 = 7;
                var1 = var3[var1];
                var3 = undefined;
                var2 = var2.bind(var3)(var1);
                var1 = {};
                var6 = arg1;
                var7 = var1;
                var5 = copyDataProperties(var7, var6);
                var1 = var4.bind(var3)(var2, var1);
                return var1;
            };
            var3['render'] = var6;
            var12 = _closure1_slot0;
            var6 = _closure1_slot2;
            var11 = var6[var9];
            var11 = var12.bind(var8)(var11);
            var14 = var11.intl;
            var13 = var14.string;
            var11 = var6[var9];
            var11 = var12.bind(var8)(var11);
            var11 = var11.t;
            var11 = var11.UBBwwF;
            var11 = var13.bind(var14)(var11);
            var3['title'] = var11;
            var1[9] = var3;
            var10 = var2.REGISTER;
            var3 = {};
            var11 = function render() {
                var4 = _closure1_slot4;
                var2 = _closure1_slot1;
                var3 = _closure1_slot2;
                var1 = 8;
                var1 = var3[var1];
                var3 = undefined;
                var2 = var2.bind(var3)(var1);
                var1 = {};
                var1 = var4.bind(var3)(var2, var1);
                return var1;
            };
            var3['render'] = var11;
            var11 = var6[var9];
            var11 = var12.bind(var8)(var11);
            var14 = var11.intl;
            var13 = var14.string;
            var11 = var6[var9];
            var11 = var12.bind(var8)(var11);
            var11 = var11.t;
            var11 = var11.vrOCCk;
            var11 = var13.bind(var14)(var11);
            var3['title'] = var11;
            var1[9] = var3;
            var3 = var2.NAME;
            var2 = {};
            var10 = function render(arg1) {
                var4 = _closure1_slot4;
                var2 = _closure1_slot1;
                var3 = _closure1_slot2;
                var1 = 9;
                var1 = var3[var1];
                var3 = undefined;
                var2 = var2.bind(var3)(var1);
                var1 = {};
                var6 = arg1;
                var7 = var1;
                var5 = copyDataProperties(var7, var6);
                var1 = var4.bind(var3)(var2, var1);
                return var1;
            };
            var2['render'] = var10;
            var10 = var6[var9];
            var10 = var12.bind(var8)(var10);
            var11 = var10.intl;
            var10 = var11.string;
            var6 = var6[var9];
            var6 = var12.bind(var8)(var6);
            var6 = var6.t;
            var6 = var6.cY/IOu;
            var6 = var10.bind(var11)(var6);
            var2['title'] = var6;
            var6 = undefined;
            if(!var7) { _fun0001_ip = 4; continue _fun0001 }
case 5:
            var10 = _closure1_slot0;
            var13 = _closure1_slot2;
            var7 = 5;
            var7 = var13[var7];
            var11 = var10.bind(var8)(var7);
            var10 = var11.getHeaderCloseButton;
            var12 = _closure1_slot1;
            var7 = 6;
            var7 = var13[var7];
            var7 = var12.bind(var8)(var7);
            var7 = var7.closePasskeyUpsellModal;
            var6 = var10.bind(var11)(var7);
case 4:
            var2['headerLeft'] = var6;
            var1[2] = var2;
            var2 = _closure1_slot3;
            var3 = var2.SUCCESS;
            var2 = {};
            var5 = function render() {
                var4 = _closure1_slot4;
                var2 = _closure1_slot1;
                var3 = _closure1_slot2;
                var1 = 10;
                var1 = var3[var1];
                var3 = undefined;
                var2 = var2.bind(var3)(var1);
                var1 = {};
                var1 = var4.bind(var3)(var2, var1);
                return var1;
            };
            var2['render'] = var5;
            var7 = _closure1_slot0;
            var4 = _closure1_slot2;
            var5 = var4[var9];
            var5 = var7.bind(var8)(var5);
            var6 = var5.intl;
            var5 = var6.string;
            var4 = var4[var9];
            var4 = var7.bind(var8)(var4);
            var4 = var4.t;
            var4 = var4["7wPZln"];
            var4 = var5.bind(var6)(var4);
            var2['title'] = var4;
            var1[2] = var2;
            return var1;
        }
    };
    var3['getScreens'] = var2;
    return var1;
})();