// app/modules/premium/gifting/native/views/GiftingBadgeIcon.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var7 = var6[var1];
    var4 = metroImportAll;
    var1 = undefined;
    var4 = var4.bind(var1)(var7);
    var4 = 1;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.Image;
    var _closure1_slot0 = var4;
    var4 = 2;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.getBadgeAssetFromCDN;
    var _closure1_slot1 = var4;
    var4 = 3;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.jsx;
    var _closure1_slot2 = var4;
    var4 = 4;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/premium/gifting/native/views/GiftingBadgeIcon.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function GiftingBadgeIcon(arg1) {
        var1 = arg1;
        var9 = var1.icon;
        var5 = var1.size;
        var6 = var1.style;
        var4 = _closure1_slot2;
        var3 = _closure1_slot0;
        var2 = {};
        var7 = {};
        var8 = _closure1_slot1;
        var1 = undefined;
        var8 = var8.bind(var1)(var9);
        var7['uri'] = var8;
        var2['source'] = var7;
        var7 = {};
        var7['width'] = var5;
        var7['height'] = var5;
        var5 = new Array(2);
        var5[0] = var7;
        var5[1] = var6;
        var2['style'] = var5;
        var1 = var4.bind(var1)(var3, var2);
        return var1;
    };
    var3['default'] = var2;
    return var1;
})();