// app/modules/pomelo/UUForcedMigrationExperiment.tsx
export default (function(_, argBar, __, ___, ____, argFred, argPlugh) {
    oscar = argBar;
    zulu = argFred;
    golf = argPlugh;
    entity = global;
    options = entity.Object;
    report = options.defineProperty;
    tango = {};
    romeo = true;
    tango['value'] = romeo;
    entity = '__esModule';
    entity = report.bind(options)(zulu, entity, tango);
    entity = 0;
    tango = golf[entity];
    entity = undefined;
    verify = oscar.bind(entity)(tango);
    options = verify.createExperiment;
    tango = {'kind': 'user', 'id': '2024-01_uu_forced_migration', 'label': 'Unique Username Forced Migration UI'};
    report = {};
    offset = false;
    report['enabled'] = offset;
    tango['defaultConfig'] = report;
    yankee = {'id': 1, 'label': 'Enable Forced Migration UI'};
    report = 1;
    offset = {};
    offset['enabled'] = romeo;
    yankee['config'] = offset;
    offset = new Array(1);
    offset[0] = yankee;
    tango['treatments'] = offset;
    tango = options.bind(verify)(tango);
    var _closure1_slot0 = tango;
    report = golf[report];
    golf = oscar.bind(entity)(report);
    oscar = golf.fileFinishedImporting;
    report = 'modules/pomelo/UUForcedMigrationExperiment.tsx';
    report = oscar.bind(golf)(report);
    zulu['UUForcedMigrationExperiment'] = tango;
    tango = function() {
        tango = _closure1_slot0;
        zulu = tango.useExperiment;
        mike = {};
        entity = 'force_migration';
        mike['location'] = entity;
        entity = {};
        report = false;
        entity['autoTrackExposure'] = report;
        entity = zulu.bind(tango)(mike, entity);
        entity = entity.enabled;
        return entity;
    };
    zulu['useForceMigration'] = tango;
    mike = function() {
        tango = _closure1_slot0;
        zulu = tango.getCurrentConfig;
        mike = {};
        entity = 'force_migration';
        mike['location'] = entity;
        entity = {};
        report = false;
        entity['autoTrackExposure'] = report;
        entity = zulu.bind(tango)(mike, entity);
        entity = entity.enabled;
        return entity;
    };
    zulu['getForceMigration'] = mike;
    return entity;
})();