// app/utils/native/HcaptchaModal.tsx
export default (function(argFoo, argBar, argBaz, argCor, _, argFre, argPlu) {
    report = argBar;
    golfie = argBaz;
    zuuluu = argFre;
    oscard = argPlu;
    var _closure1_slot0 = report;
    var _closure1_slot1 = golfie;
    var _closure1_slot2 = oscard;
    entity = global;
    verify = entity.Object;
    option = verify.defineProperty;
    tangon = {};
    entity = true;
    tangon['value'] = entity;
    entity = '__esModule';
    entity = option.bind(verify)(zuuluu, entity, tangon);
    entity = 0;
    option = oscard[entity];
    tangon = argCor;
    entity = undefined;
    tangon = tangon.bind(entity)(option);
    tangon = 1;
    tangon = oscard[tangon];
    tangon = report.bind(entity)(tangon);
    option = tangon.View;
    var _closure1_slot3 = option;
    option = tangon.ActivityIndicator;
    var _closure1_slot4 = option;
    tangon = tangon.StyleSheet;
    var _closure1_slot5 = tangon;
    tangon = 2;
    tangon = oscard[tangon];
    tangon = golfie.bind(entity)(tangon);
    var _closure1_slot6 = tangon;
    tangon = 3;
    tangon = oscard[tangon];
    tangon = golfie.bind(entity)(tangon);
    var _closure1_slot7 = tangon;
    tangon = 4;
    tangon = oscard[tangon];
    tangon = report.bind(entity)(tangon);
    golfie = tangon.ModalAnimation;
    tangon = 5;
    option = oscard[tangon];
    option = report.bind(entity)(option);
    option = option.jsx;
    var _closure1_slot8 = option;
    tangon = oscard[tangon];
    tangon = report.bind(entity)(tangon);
    tangon = tangon.jsxs;
    var _closure1_slot9 = tangon;
    tangon = 6;
    tangon = oscard[tangon];
    verify = report.bind(entity)(tangon);
    option = verify.createStyles;
    tangon = {};
    offset = {'flex': 1, 'justifyContent': 'center', 'alignItems': 'center'};
    tangon['container'] = offset;
    tangon = option.bind(verify)(tangon);
    var _closure1_slot10 = tangon;
    michal = function(argFoo) { // Original name: HcaptchaModal
        _fun00001: for(var _fun00002_ip = 0; ; ) switch(_fun00002_ip) {
 0:
            entity = _closure1_slot10;
            tangon = undefined;
            report = entity.bind(tangon)();
            michal = _closure1_slot0;
            zuuluu = _closure1_slot2;
            entity = 7;
            entity = zuuluu[entity];
            oscard = michal.bind(tangon)(entity);
            zuuluu = oscard.useStateFromStores;
            entity = _closure1_slot7;
            michal = new Array(1);
            michal[0] = entity;
            entity = function() {
                michal = _closure1_slot7;
                entity = michal.getCurrentUser;
                entity = entity.bind(michal)();
                return entity;
            };
            entity = zuuluu.bind(oscard)(michal, entity);
            michal = null;
            oscard = michal == entity;
            if(oscard) { _fun00002_ip = 116; continue _fun00001 }
 74:
            michal = entity.ageVerificationStatus;
            zuuluu = _closure1_slot0;
            golfie = _closure1_slot2;
            entity = 8;
            entity = golfie[entity];
            entity = zuuluu.bind(tangon)(entity);
            entity = entity.AgeVerificationStatusUkAndAusOnly;
            entity = entity.CLIENT_ONLY_PENDING;
            oscard = michal !== entity;
 116:
            zuuluu = _closure1_slot9;
            michal = _closure1_slot3;
            entity = {};
            report = report.container;
            entity['style'] = report;
            if(!oscard) { _fun00002_ip = 231; continue _fun00001 }
 138:
            option = _closure1_slot8;
            golfie = _closure1_slot4;
            report = {};
            verify = 'small';
            report['size'] = verify;
            offset = _closure1_slot0;
            romeon = _closure1_slot2;
            verify = 9;
            verify = romeon[verify];
            offset = offset.bind(tangon)(verify);
            verify = offset.isAndroid;
            offset = verify.bind(offset)();
            verify = undefined;
            if(!offset) { _fun00002_ip = 221; continue _fun00001 }
 190:
            romeon = _closure1_slot1;
            foxtra = _closure1_slot2;
            offset = 10;
            offset = foxtra[offset];
            offset = romeon.bind(tangon)(offset);
            offset = offset.unsafe_rawColors;
            verify = offset.WHITE_500;
 221:
            report['color'] = verify;
            oscard = option.bind(tangon)(golfie, report);
 231:
            report = new Array(2);
            report[0] = oscard;
            option = _closure1_slot8;
            golfie = _closure1_slot3;
            oscard = {};
            verify = _closure1_slot5;
            verify = verify.absoluteFillObject;
            oscard['style'] = verify;
            offset = _closure1_slot1;
            romeon = _closure1_slot2;
            verify = 11;
            verify = romeon[verify];
            offset = offset.bind(tangon)(verify);
            verify = {};
            backup = argFoo;
            kiloes = verify;
            romeon = copyDataProperties(kiloes, backup);
            yankee = _closure1_slot6;
            romeon = yankee.locale;
            yankee = 'languageCode';
            verify[yankee] = romeon;
            verify = option.bind(tangon)(offset, verify);
            oscard['children'] = verify;
            oscard = option.bind(tangon)(golfie, oscard);
            report[1] = oscard;
            entity['children'] = report;
            entity = zuuluu.bind(tangon)(michal, entity);
            return entity;
        }
    };
    tangon = {};
    golfie = golfie.FADE;
    tangon['animation'] = golfie;
    michal['modalConfig'] = tangon;
    tangon = 12;
    tangon = oscard[tangon];
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'utils/native/HcaptchaModal.tsx';
    tangon = report.bind(oscard)(tangon);
    zuuluu['default'] = michal;
    return entity;
})();