// app/utils/native/MFAInterceptionUtils.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var1 = metroImportDefault;
    var _closure1_slot1 = var1;
    var _closure1_slot2 = var6;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var7 = var6[var1];
    var4 = metroImportAll;
    var1 = undefined;
    var4 = var4.bind(var1)(var7);
    var4 = 1;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.jsx;
    var _closure1_slot3 = var4;
    var4 = 5;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'utils/native/MFAInterceptionUtils.tsx';
    var4 = var5.bind(var6)(var4);
    var4 = function showAlert(arg1, arg2, arg3) {
        var1 = arg1;
        var _closure2_slot0 = var1;
        var1 = arg2;
        var _closure2_slot1 = var1;
        var1 = arg3;
        var _closure2_slot2 = var1;
        var3 = _closure1_slot1;
        var2 = _closure1_slot2;
        var1 = 2;
        var2 = var2[var1];
        var1 = undefined;
        var4 = var3.bind(var1)(var2);
        var3 = var4.openLazy;
        var2 = {};
        var5 = function importer() {
            var3 = _closure1_slot0;
            var1 = _closure1_slot2;
            var2 = 4;
            var2 = var1[var2];
            var4 = undefined;
            var3 = var3.bind(var4)(var2);
            var2 = 3;
            var2 = var1[var2];
            var1 = var1.paths;
            var3 = var3.bind(var4)(var2, var1);
            var2 = var3.then;
            var1 = function(arg1) {
                var2 = arg1;
                var2 = var2.default;
                var _closure4_slot0 = var2;
                var1 = function(arg1) {
                    var4 = _closure1_slot3;
                    var3 = _closure4_slot0;
                    var2 = {};
                    var7 = arg1;
                    var8 = var2;
                    var1 = copyDataProperties(var8, var7);
                    var7 = _closure2_slot2;
                    var8 = var2;
                    var5 = copyDataProperties(var8, var7);
                    var6 = _closure2_slot0;
                    var5 = 'handleSubmit';
                    var2[var5] = var6;
                    var5 = _closure2_slot1;
                    var1 = 'handleEarlyClose';
                    var2[var1] = var5;
                    var1 = undefined;
                    var1 = var4.bind(var1)(var3, var2);
                    return var1;
                };
                return var1;
            };
            var1 = var2.bind(var3)(var1);
            return var1;
        };
        var2['importer'] = var5;
        var2 = var3.bind(var4)(var2);
        return var1;
    };
    var3['showAlert'] = var4;
    var2 = function() {
        var3 = _closure1_slot1;
        var2 = _closure1_slot2;
        var1 = 2;
        var2 = var2[var1];
        var1 = undefined;
        var2 = var3.bind(var1)(var2);
        var1 = var2.close;
        var1 = var1.bind(var2)();
        return var1;
    };
    var3['closeAlert'] = var2;
    return var1;
})();