// app/modules/guild_onboarding/native/GuildOnboardingConstants.tsx
export default (function(_, argBar, __, ___, ____, argFre, argPlu) {
    zuuluu = argFre;
    entity = global;
    report = entity.Object;
    tangon = report.defineProperty;
    michal = {};
    entity = true;
    michal['value'] = entity;
    entity = '__esModule';
    entity = tangon.bind(report)(zuuluu, entity, michal);
    michal = {};
    entity = 'cover';
    michal['COVER'] = entity;
    entity = 'prompt';
    michal['PROMPT'] = entity;
    entity = 'completed';
    michal['COMPLETED'] = entity;
    entity = 'rules';
    michal['RULES'] = entity;
    tangon = argPlu;
    entity = 0;
    report = tangon[entity];
    tangon = argBar;
    entity = undefined;
    oscard = tangon.bind(entity)(report);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/guild_onboarding/native/GuildOnboardingConstants.tsx';
    tangon = report.bind(oscard)(tangon);
    tangon = 'GUILD_ONBOARDING_MODAL_KEY';
    zuuluu['GUILD_ONBOARDING_MODAL_KEY'] = tangon;
    tangon = 'CHANNELS_AND_ROLES_MODAL_KEY';
    zuuluu['CHANNELS_AND_ROLES_MODAL_KEY'] = tangon;
    zuuluu['GuildOnboardingModalStates'] = michal;
    return entity;
})();