// app/modules/dismissible_content/web/SelectedDismissibleContent.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var6 = require;
    var3 = exports;
    var7 = dependencyMap;
    var _closure1_slot0 = var6;
    var _closure1_slot1 = var7;
    var4 = function useSelectedDismissibleContent(arg1, arg2) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var5 = arguments[2];
            var6 = undefined;
            if(!(var5 === var6)) { _fun0001_ip = 2; continue _fun0001 }
case 3:
            var5 = false;
case 2:
            var4 = _closure1_slot0;
            var7 = _closure1_slot1;
            var2 = 3;
            var2 = var7[var2];
            var9 = var4.bind(var6)(var2);
            var8 = var9.useGetDismissibleContent;
            var3 = arg1;
            var2 = arg2;
            var3 = var8.bind(var9)(var3, var2);
            var2 = _closure1_slot2;
            var1 = 2;
            var2 = var2.bind(var6)(var3, var1);
            var1 = 0;
            var3 = var2[var1];
            var1 = 1;
            var2 = var2[var1];
            var1 = 4;
            var1 = var7[var1];
            var4 = var4.bind(var6)(var1);
            var1 = var4.useSelectedDismissibleContentShared;
            var1 = var1.bind(var4)(var3, var2, var5);
            var1 = new Array(2);
            var1[0] = var3;
            var1[1] = var2;
            return var1;
        }
    };
    var _closure1_slot5 = var4;
    var1 = global;
    var9 = var1.Object;
    var8 = var9.defineProperty;
    var5 = {};
    var1 = true;
    var5['value'] = var1;
    var1 = '__esModule';
    var1 = var8.bind(var9)(var3, var1, var5);
    var1 = 0;
    var8 = var7[var1];
    var5 = metroImportDefault;
    var1 = undefined;
    var5 = var5.bind(var1)(var8);
    var _closure1_slot2 = var5;
    var5 = 1;
    var8 = var7[var5];
    var5 = metroImportAll;
    var5 = var5.bind(var1)(var8);
    var5 = 2;
    var5 = var7[var5];
    var5 = var6.bind(var1)(var5);
    var8 = var5.Fragment;
    var _closure1_slot3 = var8;
    var5 = var5.jsx;
    var _closure1_slot4 = var5;
    var5 = 5;
    var5 = var7[var5];
    var7 = var6.bind(var1)(var5);
    var6 = var7.fileFinishedImporting;
    var5 = 'modules/dismissible_content/web/SelectedDismissibleContent.tsx';
    var5 = var6.bind(var7)(var5);
    var5 = function SelectedDismissibleContent(arg1) {
        var1 = arg1;
        var7 = var1.contentTypes;
        var6 = var1.children;
        var5 = var1.groupName;
        var3 = var1.bypassAutoDismiss;
        var2 = _closure1_slot5;
        var4 = undefined;
        var5 = var2.bind(var4)(var7, var5, var3);
        var3 = _closure1_slot2;
        var2 = 2;
        var3 = var3.bind(var4)(var5, var2);
        var2 = 0;
        var8 = var3[var2];
        var2 = 1;
        var7 = var3[var2];
        var3 = _closure1_slot4;
        var2 = _closure1_slot3;
        var1 = {};
        var5 = {};
        var5['visibleContent'] = var8;
        var5['markAsDismissed'] = var7;
        var5 = var6.bind(var4)(var5);
        var1['children'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var3['default'] = var5;
    var3['useSelectedDismissibleContent'] = var4;
    var4 = function useSelectedVersionedDismissibleContent(arg1, arg2, arg3) {
        _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
case 0:
            var5 = arguments[3];
            var6 = undefined;
            if(!(var5 === var6)) { _fun0002_ip = 2; continue _fun0002 }
case 3:
            var5 = false;
case 2:
            var4 = _closure1_slot0;
            var7 = _closure1_slot1;
            var2 = 3;
            var2 = var7[var2];
            var10 = var4.bind(var6)(var2);
            var9 = var10.useGetVersionedDismissibleContent;
            var8 = arg1;
            var3 = arg2;
            var2 = arg3;
            var3 = var9.bind(var10)(var8, var3, var2);
            var2 = _closure1_slot2;
            var1 = 2;
            var2 = var2.bind(var6)(var3, var1);
            var1 = 0;
            var3 = var2[var1];
            var1 = 1;
            var2 = var2[var1];
            var1 = 4;
            var1 = var7[var1];
            var4 = var4.bind(var6)(var1);
            var1 = var4.useSelectedDismissibleContentShared;
            var1 = var1.bind(var4)(var3, var2, var5);
            var1 = new Array(2);
            var1[0] = var3;
            var1[1] = var2;
            return var1;
        }
    };
    var3['useSelectedVersionedDismissibleContent'] = var4;
    var4 = function useSelectedTimeRecurringDismissibleContent(arg1, arg2, arg3) {
        _fun0003: for(var _fun0003_ip = 0; ; ) switch(_fun0003_ip) {
case 0:
            var5 = arguments[3];
            var6 = undefined;
            if(!(var5 === var6)) { _fun0003_ip = 2; continue _fun0003 }
case 3:
            var5 = false;
case 2:
            var4 = _closure1_slot0;
            var7 = _closure1_slot1;
            var2 = 3;
            var2 = var7[var2];
            var10 = var4.bind(var6)(var2);
            var9 = var10.useGetTimeRecurringDismissibleContent;
            var8 = arg1;
            var3 = arg2;
            var2 = arg3;
            var3 = var9.bind(var10)(var8, var3, var2);
            var2 = _closure1_slot2;
            var1 = 2;
            var2 = var2.bind(var6)(var3, var1);
            var1 = 0;
            var3 = var2[var1];
            var1 = 1;
            var2 = var2[var1];
            var1 = 4;
            var1 = var7[var1];
            var4 = var4.bind(var6)(var1);
            var1 = var4.useSelectedDismissibleContentShared;
            var1 = var1.bind(var4)(var3, var2, var5);
            var1 = new Array(2);
            var1[0] = var3;
            var1[1] = var2;
            return var1;
        }
    };
    var3['useSelectedTimeRecurringDismissibleContent'] = var4;
    var4 = function useSelectedSnowflakeBoundDismissibleContent(arg1, arg2, arg3) {
        _fun0004: for(var _fun0004_ip = 0; ; ) switch(_fun0004_ip) {
case 0:
            var5 = arguments[3];
            var6 = undefined;
            if(!(var5 === var6)) { _fun0004_ip = 2; continue _fun0004 }
case 3:
            var5 = false;
case 2:
            var4 = _closure1_slot0;
            var7 = _closure1_slot1;
            var2 = 3;
            var2 = var7[var2];
            var10 = var4.bind(var6)(var2);
            var9 = var10.useGetSnowflakeBoundDismissibleContent;
            var8 = arg1;
            var3 = arg2;
            var2 = arg3;
            var3 = var9.bind(var10)(var8, var3, var2);
            var2 = _closure1_slot2;
            var1 = 2;
            var2 = var2.bind(var6)(var3, var1);
            var1 = 0;
            var3 = var2[var1];
            var1 = 1;
            var2 = var2[var1];
            var1 = 4;
            var1 = var7[var1];
            var4 = var4.bind(var6)(var1);
            var1 = var4.useSelectedDismissibleContentShared;
            var1 = var1.bind(var4)(var3, var2, var5);
            var1 = new Array(2);
            var1[0] = var3;
            var1[1] = var2;
            return var1;
        }
    };
    var3['useSelectedSnowflakeBoundDismissibleContent'] = var4;
    var4 = function useSelectedSnowflakeBoundGuildDismissibleContent(arg1, arg2, arg3, arg4) {
        _fun0005: for(var _fun0005_ip = 0; ; ) switch(_fun0005_ip) {
case 0:
            var6 = arg2;
            var5 = arguments[4];
            var7 = undefined;
            if(!(var5 === var7)) { _fun0005_ip = 4; continue _fun0005 }
case 5:
            var5 = false;
case 4:
            var4 = _closure1_slot0;
            var8 = _closure1_slot1;
            var2 = 3;
            var2 = var8[var2];
            var11 = var4.bind(var7)(var2);
            var10 = var11.UNSAFE_useGetSnowflakeBoundGuildDismissibleContent;
            var15 = arg1;
            var14 = arg3;
            var12 = arg4;
            var16 = var11;
            var13 = var6;
            var3 = var16[var10](var15, var14, var13, var12, var11);
            var2 = _closure1_slot2;
            var1 = 2;
            var2 = var2.bind(var7)(var3, var1);
            var1 = 0;
            var3 = var2[var1];
            var1 = 1;
            var2 = var2[var1];
            var1 = 4;
            var1 = var8[var1];
            var4 = var4.bind(var7)(var1);
            var1 = var4.useSelectedDismissibleContentShared;
            var16 = var4;
            var15 = var3;
            var14 = var2;
            var13 = var5;
            var12 = var6;
            var1 = var16[var1](var15, var14, var13, var12, var11);
            var1 = new Array(2);
            var1[0] = var3;
            var1[1] = var2;
            return var1;
        }
    };
    var3['useSelectedSnowflakeBoundGuildDismissibleContent'] = var4;
    var4 = function useSelectedSingleUseGuildDismissibleContent(arg1, arg2, arg3) {
        _fun0006: for(var _fun0006_ip = 0; ; ) switch(_fun0006_ip) {
case 0:
            var6 = arg2;
            var5 = arguments[3];
            var7 = undefined;
            if(!(var5 === var7)) { _fun0006_ip = 4; continue _fun0006 }
case 5:
            var5 = false;
case 4:
            var4 = _closure1_slot0;
            var8 = _closure1_slot1;
            var2 = 3;
            var2 = var8[var2];
            var10 = var4.bind(var7)(var2);
            var9 = var10.UNSAFE_useGetSingleUseGuildDismissibleContent;
            var3 = arg1;
            var2 = arg3;
            var3 = var9.bind(var10)(var3, var6, var2);
            var2 = _closure1_slot2;
            var1 = 2;
            var2 = var2.bind(var7)(var3, var1);
            var1 = 0;
            var3 = var2[var1];
            var1 = 1;
            var2 = var2[var1];
            var1 = 4;
            var1 = var8[var1];
            var4 = var4.bind(var7)(var1);
            var1 = var4.useSelectedDismissibleContentShared;
            var15 = var4;
            var14 = var3;
            var13 = var2;
            var12 = var5;
            var11 = var6;
            var1 = var15[var1](var14, var13, var12, var11, var10);
            var1 = new Array(2);
            var1[0] = var3;
            var1[1] = var2;
            return var1;
        }
    };
    var3['useSelectedSingleUseGuildDismissibleContent'] = var4;
    var4 = function useSelectedTimeRecurringGuildDismissibleContent(arg1, arg2, arg3, arg4) {
        var6 = arg2;
        var5 = _closure1_slot0;
        var7 = _closure1_slot1;
        var2 = 3;
        var2 = var7[var2];
        var4 = undefined;
        var10 = var5.bind(var4)(var2);
        var9 = var10.UNSAFE_useGetTimeRecurringGuildDismissibleContent;
        var14 = arg1;
        var12 = arg3;
        var11 = arg4;
        var15 = var10;
        var13 = var6;
        var3 = var15[var9](var14, var13, var12, var11, var10);
        var2 = _closure1_slot2;
        var1 = 2;
        var2 = var2.bind(var4)(var3, var1);
        var1 = 0;
        var3 = var2[var1];
        var1 = 1;
        var2 = var2[var1];
        var1 = 4;
        var1 = var7[var1];
        var5 = var5.bind(var4)(var1);
        var4 = var5.useSelectedDismissibleContentShared;
        var12 = false;
        var15 = var5;
        var14 = var3;
        var13 = var2;
        var11 = var6;
        var1 = var15[var4](var14, var13, var12, var11, var10);
        var1 = new Array(2);
        var1[0] = var3;
        var1[1] = var2;
        return var1;
    };
    var3['useSelectedTimeRecurringGuildDismissibleContent'] = var4;
    var4 = function SelectedVersionedDismissibleContent(arg1) {
        var1 = arg1;
        var11 = var1.contentType;
        var10 = var1.latestVersion;
        var8 = var1.groupName;
        var5 = var1.bypassAutoDismiss;
        var6 = var1.children;
        var3 = _closure1_slot0;
        var9 = _closure1_slot1;
        var2 = 3;
        var2 = var9[var2];
        var4 = undefined;
        var7 = var3.bind(var4)(var2);
        var2 = var7.useGetVersionedDismissibleContent;
        var8 = var2.bind(var7)(var11, var10, var8);
        var7 = _closure1_slot2;
        var2 = 2;
        var7 = var7.bind(var4)(var8, var2);
        var2 = 0;
        var8 = var7[var2];
        var2 = 1;
        var7 = var7[var2];
        var2 = 4;
        var2 = var9[var2];
        var3 = var3.bind(var4)(var2);
        var2 = var3.useSelectedDismissibleContentShared;
        var2 = var2.bind(var3)(var8, var7, var5);
        var3 = _closure1_slot4;
        var2 = _closure1_slot3;
        var1 = {};
        var5 = {};
        var5['visibleContent'] = var8;
        var5['markAsDismissed'] = var7;
        var5 = var6.bind(var4)(var5);
        var1['children'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var3['SelectedVersionedDismissibleContent'] = var4;
    var4 = function SelectedTimeRecurringDismissibleContent(arg1) {
        var1 = arg1;
        var11 = var1.contentType;
        var10 = var1.timeRecurringConfig;
        var8 = var1.groupName;
        var5 = var1.bypassAutoDismiss;
        var6 = var1.children;
        var3 = _closure1_slot0;
        var9 = _closure1_slot1;
        var2 = 3;
        var2 = var9[var2];
        var4 = undefined;
        var7 = var3.bind(var4)(var2);
        var2 = var7.useGetTimeRecurringDismissibleContent;
        var8 = var2.bind(var7)(var11, var10, var8);
        var7 = _closure1_slot2;
        var2 = 2;
        var7 = var7.bind(var4)(var8, var2);
        var2 = 0;
        var8 = var7[var2];
        var2 = 1;
        var7 = var7[var2];
        var2 = 4;
        var2 = var9[var2];
        var3 = var3.bind(var4)(var2);
        var2 = var3.useSelectedDismissibleContentShared;
        var2 = var2.bind(var3)(var8, var7, var5);
        var3 = _closure1_slot4;
        var2 = _closure1_slot3;
        var1 = {};
        var5 = {};
        var5['visibleContent'] = var8;
        var5['markAsDismissed'] = var7;
        var5 = var6.bind(var4)(var5);
        var1['children'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var3['SelectedTimeRecurringDismissibleContent'] = var4;
    var4 = function SelectedTimeReccuringSnowflakeBoundDismissibleContent(arg1) {
        var1 = arg1;
        var12 = var1.contentType;
        var14 = var1.newSnowflakeId;
        var15 = var1.timeRecurringConfig;
        var13 = var1.groupName;
        var5 = var1.bypassAutoDismiss;
        var6 = var1.children;
        var3 = _closure1_slot0;
        var9 = _closure1_slot1;
        var2 = 3;
        var2 = var9[var2];
        var4 = undefined;
        var7 = var3.bind(var4)(var2);
        var2 = var7.useGetTimeReccuringSnowflakeBoundDismissibleContent;
        var17 = var7;
        var16 = var12;
        var8 = var17[var2](var16, var15, var14, var13, var12);
        var7 = _closure1_slot2;
        var2 = 2;
        var7 = var7.bind(var4)(var8, var2);
        var2 = 0;
        var8 = var7[var2];
        var2 = 1;
        var7 = var7[var2];
        var2 = 4;
        var2 = var9[var2];
        var3 = var3.bind(var4)(var2);
        var2 = var3.useSelectedDismissibleContentShared;
        var2 = var2.bind(var3)(var8, var7, var5);
        var3 = _closure1_slot4;
        var2 = _closure1_slot3;
        var1 = {};
        var5 = {};
        var5['visibleContent'] = var8;
        var5['markAsDismissed'] = var7;
        var5 = var6.bind(var4)(var5);
        var1['children'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var3['SelectedTimeReccuringSnowflakeBoundDismissibleContent'] = var4;
    var4 = function SelectedSingleUseGuildDismissibleContent(arg1) {
        var1 = arg1;
        var10 = var1.contentTypes;
        var9 = var1.guildId;
        var8 = var1.groupName;
        var6 = var1.children;
        var3 = _closure1_slot0;
        var5 = _closure1_slot1;
        var2 = 3;
        var2 = var5[var2];
        var4 = undefined;
        var7 = var3.bind(var4)(var2);
        var2 = var7.UNSAFE_useGetSingleUseGuildDismissibleContent;
        var8 = var2.bind(var7)(var10, var9, var8);
        var7 = _closure1_slot2;
        var2 = 2;
        var7 = var7.bind(var4)(var8, var2);
        var2 = 0;
        var8 = var7[var2];
        var2 = 1;
        var7 = var7[var2];
        var2 = 4;
        var2 = var5[var2];
        var5 = var3.bind(var4)(var2);
        var3 = var5.useSelectedDismissibleContentShared;
        var12 = false;
        var15 = var5;
        var14 = var8;
        var13 = var7;
        var11 = var9;
        var2 = var15[var3](var14, var13, var12, var11, var10);
        var3 = _closure1_slot4;
        var2 = _closure1_slot3;
        var1 = {};
        var5 = {};
        var5['visibleContent'] = var8;
        var5['markAsDismissed'] = var7;
        var5 = var6.bind(var4)(var5);
        var1['children'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var3['SelectedSingleUseGuildDismissibleContent'] = var4;
    var2 = function SelectedTimeRecurringGuildDismissibleContent(arg1) {
        var1 = arg1;
        var11 = var1.contentType;
        var9 = var1.guildId;
        var13 = var1.timeRecurringConfig;
        var12 = var1.groupName;
        var6 = var1.children;
        var3 = _closure1_slot0;
        var5 = _closure1_slot1;
        var2 = 3;
        var2 = var5[var2];
        var4 = undefined;
        var7 = var3.bind(var4)(var2);
        var2 = var7.UNSAFE_useGetTimeRecurringGuildDismissibleContent;
        var16 = var7;
        var15 = var11;
        var14 = var9;
        var8 = var16[var2](var15, var14, var13, var12, var11);
        var7 = _closure1_slot2;
        var2 = 2;
        var7 = var7.bind(var4)(var8, var2);
        var2 = 0;
        var8 = var7[var2];
        var2 = 1;
        var7 = var7[var2];
        var2 = 4;
        var2 = var5[var2];
        var5 = var3.bind(var4)(var2);
        var3 = var5.useSelectedDismissibleContentShared;
        var13 = false;
        var16 = var5;
        var15 = var8;
        var14 = var7;
        var12 = var9;
        var2 = var16[var3](var15, var14, var13, var12, var11);
        var3 = _closure1_slot4;
        var2 = _closure1_slot3;
        var1 = {};
        var5 = {};
        var5['visibleContent'] = var8;
        var5['markAsDismissed'] = var7;
        var5 = var6.bind(var4)(var5);
        var1['children'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var3['SelectedTimeRecurringGuildDismissibleContent'] = var2;
    return var1;
})();