// app/design/components/Navigator/native/useNavigation.native.tsx
export default (function(_, argBar, __, ___, ____, argFre, argPlu) {
    oscard = argBar;
    zuuluu = argFre;
    report = argPlu;
    var _closure1_slot0 = oscard;
    var _closure1_slot1 = report;
    tangon = function() { // Original name: useNavigation
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 0;
        michal = michal[entity];
        entity = undefined;
        michal = zuuluu.bind(entity)(michal);
        entity = michal.useNavigation;
        entity = entity.bind(michal)();
        return entity;
    };
    entity = global;
    verify = entity.Object;
    option = verify.defineProperty;
    golfie = {};
    entity = true;
    golfie['value'] = entity;
    entity = '__esModule';
    entity = option.bind(verify)(zuuluu, entity, golfie);
    entity = 1;
    report = report[entity];
    entity = undefined;
    golfie = oscard.bind(entity)(report);
    oscard = golfie.fileFinishedImporting;
    report = 'design/components/Navigator/native/useNavigation.native.tsx';
    report = oscard.bind(golfie)(report);
    zuuluu['useNavigation'] = tangon;
    report = function() { // Original name: useNativeStackNavigation
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 0;
        michal = michal[entity];
        entity = undefined;
        michal = zuuluu.bind(entity)(michal);
        entity = michal.useNavigation;
        entity = entity.bind(michal)();
        return entity;
    };
    zuuluu['useNativeStackNavigation'] = report;
    zuuluu['useStackNavigation'] = tangon;
    michal = function() { // Original name: useTabNavigation
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 0;
        michal = michal[entity];
        entity = undefined;
        michal = zuuluu.bind(entity)(michal);
        entity = michal.useNavigation;
        entity = entity.bind(michal)();
        return entity;
    };
    zuuluu['useTabNavigation'] = michal;
    return entity;
})();