// app/modules/channel_prompts/native/PromptPhotoActionSheet.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var12 = metroImportDefault;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var12;
    var _closure1_slot2 = var6;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var12.bind(var1)(var4);
    var _closure1_slot3 = var4;
    var4 = 1;
    var7 = var6[var4];
    var4 = metroImportAll;
    var4 = var4.bind(var1)(var7);
    var _closure1_slot4 = var4;
    var4 = 2;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.View;
    var _closure1_slot5 = var4;
    var7 = 3;
    var7 = var6[var7];
    var7 = var5.bind(var1)(var7);
    var7 = var7.DraftType;
    var _closure1_slot6 = var7;
    var10 = 4;
    var7 = var6[var10];
    var7 = var12.bind(var1)(var7);
    var _closure1_slot7 = var7;
    var7 = 5;
    var7 = var6[var7];
    var7 = var5.bind(var1)(var7);
    var7 = var7.MediaKeyboardTarget;
    var _closure1_slot8 = var7;
    var7 = 6;
    var7 = var6[var7];
    var7 = var5.bind(var1)(var7);
    var7 = var7.MessageSendLocation;
    var _closure1_slot9 = var7;
    var7 = 7;
    var7 = var6[var7];
    var7 = var5.bind(var1)(var7);
    var7 = var7.NativePermissionTypes;
    var _closure1_slot10 = var7;
    var7 = 8;
    var7 = var6[var7];
    var7 = var5.bind(var1)(var7);
    var8 = var7.jsx;
    var _closure1_slot11 = var8;
    var7 = var7.jsxs;
    var _closure1_slot12 = var7;
    var _closure1_slot13 = var4;
    var4 = 9;
    var4 = var6[var4];
    var8 = var5.bind(var1)(var4);
    var7 = var8.createStyles;
    var4 = {};
    var9 = {};
    var11 = 'relative';
    var9['position'] = var11;
    var11 = 10;
    var13 = var6[var11];
    var13 = var12.bind(var1)(var13);
    var13 = var13.colors;
    var13 = var13.BLACK;
    var9['backgroundColor'] = var13;
    var4['container'] = var9;
    var9 = {'position': 'absolute', 'width': '100%', 'height': '100%', 'display': 'flex', 'justifyContent': 'center', 'alignItems': 'center'};
    var4['background'] = var9;
    var9 = {};
    var13 = 24;
    var9['paddingHorizontal'] = var13;
    var4['backgroundText'] = var9;
    var9 = {'position': 'absolute', 'width': '100%', 'top': 0, 'left': 0};
    var4['controls'] = var9;
    var9 = {'borderRadius': null, 'height': 64, 'width': 64, 'display': 'flex', 'alignItems': 'center', 'justifyContent': 'center'};
    var13 = var6[var11];
    var13 = var12.bind(var1)(var13);
    var13 = var13.radii;
    var13 = var13.xxl;
    var9['borderRadius'] = var13;
    var13 = var6[var11];
    var13 = var12.bind(var1)(var13);
    var13 = var13.colors;
    var13 = var13.BG_BRAND;
    var9['backgroundColor'] = var13;
    var4['mainCTAWrapper'] = var9;
    var9 = {};
    var13 = 0.6;
    var9['opacity'] = var13;
    var4['disabled'] = var9;
    var9 = {'width': 36, 'height': 36, 'tintColor': '#fff'};
    var4['mainCTA'] = var9;
    var9 = {'height': 24, 'width': 24, 'tintColor': '#fff'};
    var4['icon'] = var9;
    var9 = {'height': 32, 'width': 32, 'tintColor': '#fff'};
    var4['galleryIcon'] = var9;
    var9 = {'position': 'absolute', 'padding': 8, 'borderRadius': null, 'backgroundColor': 'rgba(0,0,0,0.3)'};
    var11 = var6[var11];
    var11 = var12.bind(var1)(var11);
    var11 = var11.radii;
    var11 = var11.xxl;
    var9['borderRadius'] = var11;
    var4['controlButton'] = var9;
    var9 = {'position': 'absolute', 'width': '100%', 'display': 'flex', 'alignItems': 'center'};
    var4['bottomBar'] = var9;
    var9 = {};
    var9['marginBottom'] = var10;
    var4['errorText'] = var9;
    var4 = var7.bind(var8)(var4);
    var _closure1_slot14 = var4;
    var4 = 35;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/channel_prompts/native/PromptPhotoActionSheet.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function PromptPhotoActionSheet(arg1) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var1 = arg1;
            var2 = var1.message;
            var _closure2_slot0 = var2;
            var2 = var1.channel;
            var _closure2_slot1 = var2;
            var1 = var1.chatInputRef;
            var _closure2_slot2 = var1;
            var1 = _closure1_slot14;
            var4 = undefined;
            var26 = var1.bind(var4)();
            var2 = _closure1_slot1;
            var9 = _closure1_slot2;
            var1 = 11;
            var1 = var9[var1];
            var1 = var2.bind(var4)(var1);
            var1 = var1.bind(var4)();
            var1 = var1.bottom;
            var28 = 8;
            var23 = var1 + var28;
            var1 = 12;
            var1 = var9[var1];
            var1 = var2.bind(var4)(var1);
            var1 = var1.bind(var4)();
            var15 = var1.width;
            var5 = var1.height;
            var1 = global;
            var3 = var1.Math;
            var2 = var3.floor;
            var1 = 0.85;
            var1 = var1 * var5;
            var14 = var2.bind(var3)(var1);
            var7 = _closure1_slot4;
            var1 = var7.useState;
            var25 = null;
            var1 = var1.bind(var7)(var25);
            var6 = _closure1_slot3;
            var5 = 2;
            var1 = var6.bind(var4)(var1, var5);
            var3 = 0;
            var11 = var1[var3];
            var2 = 1;
            var1 = var1[var2];
            var _closure2_slot3 = var1;
            var10 = var7.useEffect;
            var8 = new Array(1);
            var8[0] = var1;
            var1 = function() {
                var4 = _closure1_slot1;
                var3 = _closure1_slot2;
                var1 = 13;
                var3 = var3[var1];
                var1 = undefined;
                var5 = var4.bind(var1)(var3);
                var4 = var5.requestPermission;
                var2 = _closure1_slot10;
                var3 = var2.CAMERA;
                var2 = {};
                var6 = false;
                var2['showAuthorizationError'] = var6;
                var4 = var4.bind(var5)(var3, var2);
                var3 = var4.then;
                var2 = function(arg1) {
                    var3 = _closure2_slot3;
                    var1 = undefined;
                    var2 = arg1;
                    var2 = var3.bind(var1)(var2);
                    return var1;
                };
                var2 = var3.bind(var4)(var2);
                return var1;
            };
            var1 = var10.bind(var7)(var1, var8);
            var1 = var7.useRef;
            var30 = var1.bind(var7)(var25);
            var1 = var7.useState;
            var13 = false;
            var1 = var1.bind(var7)(var13);
            var1 = var6.bind(var4)(var1, var5);
            var24 = var1[var3];
            var1 = var1[var2];
            var _closure2_slot4 = var1;
            var1 = var7.useState;
            var1 = var1.bind(var7)(var13);
            var1 = var6.bind(var4)(var1, var5);
            var8 = var1[var3];
            var _closure2_slot5 = var8;
            var1 = var1[var2];
            var _closure2_slot6 = var1;
            var1 = var7.useState;
            var1 = var1.bind(var7)(var13);
            var1 = var6.bind(var4)(var1, var5);
            var27 = var1[var3];
            var1 = var1[var2];
            var _closure2_slot7 = var1;
            var8 = var7.useState;
            var8 = var8.bind(var7)(var13);
            var8 = var6.bind(var4)(var8, var5);
            var19 = var8[var3];
            var _closure2_slot8 = var19;
            var8 = var8[var2];
            var _closure2_slot9 = var8;
            var12 = var7.useEffect;
            var10 = new Array(1);
            var10[0] = var19;
            var8 = function() {
                _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
case 0:
                    var2 = _closure2_slot8;
                    var5 = undefined;
                    if(var2) { _fun0002_ip = 2; continue _fun0002 }
case 3:
                    return var5;
case 2:
                    var2 = global;
                    var4 = var2.setTimeout;
                    var3 = function() {
                        var3 = _closure2_slot9;
                        var1 = undefined;
                        var2 = false;
                        var2 = var3.bind(var1)(var2);
                        return var1;
                    };
                    var2 = 4000;
                    var2 = var4.bind(var5)(var3, var2);
                    var _closure3_slot0 = var2;
                    var1 = function() {
                        var1 = global;
                        var3 = var1.clearTimeout;
                        var2 = _closure3_slot0;
                        var1 = undefined;
                        var1 = var3.bind(var1)(var2);
                        return var1;
                    };
                    return var1;
                }
            };
            var8 = var12.bind(var7)(var8, var10);
            var10 = var7.useCallback;
            var8 = new Array(1);
            var8[0] = var1;
            var1 = function() {
                var3 = _closure2_slot7;
                var1 = undefined;
                var2 = true;
                var2 = var3.bind(var1)(var2);
                return var1;
            };
            var20 = var10.bind(var7)(var1, var8);
            var10 = new Array(0);
            var8 = var10.find;
            var1 = function(arg1) {
                _fun0003: for(var _fun0003_ip = 0; ; ) switch(_fun0003_ip) {
case 0:
                    var1 = _closure2_slot5;
                    var2 = arg1;
                    var3 = var2.position;
                    if(var1) { _fun0003_ip = 4; continue _fun0003 }
case 5:
                    var1 = 'back';
                    var1 = var1 === var3;
                    _fun0003_ip = 6; continue _fun0003;
case 4:
                    var2 = 'front';
                    var1 = var2 === var3;
case 6:
                    return var1;
                }
            };
            var29 = var8.bind(var10)(var1);
            var1 = var7.useState;
            var1 = var1.bind(var7)(var25);
            var1 = var6.bind(var4)(var1, var5);
            var17 = var1[var3];
            var _closure2_slot10 = var17;
            var1 = var1[var2];
            var _closure2_slot11 = var1;
            var3 = _closure1_slot11;
            var10 = _closure1_slot0;
            var1 = 14;
            var1 = var9[var1];
            var1 = var10.bind(var4)(var1);
            var2 = var1.BottomSheet;
            var1 = {};
            var18 = true;
            var1['startExpanded'] = var18;
            var5 = var14 + var23;
            var1['startHeight'] = var5;
            var5 = var14 + var23;
            var1['contentHeight'] = var5;
            var1['header'] = var25;
            var7 = _closure1_slot12;
            var6 = _closure1_slot5;
            var5 = {};
            var12 = var26.container;
            var8 = new Array(2);
            var8[0] = var12;
            var12 = {};
            var12['width'] = var15;
            var12['height'] = var14;
            var8[1] = var12;
            var5['style'] = var8;
            var8 = {};
            var12 = var26.background;
            var8['style'] = var12;
            var16 = 15;
            var9 = var9[var16];
            var9 = var10.bind(var4)(var9);
            var10 = var9.Text;
            var9 = {'variant': 'heading-lg/bold', 'color': 'always-white'};
            var12 = var26.backgroundText;
            var9['style'] = var12;
            if(!(var13 !== var11)) { _fun0001_ip = 7; continue _fun0001 }
case 8:
            var32 = _closure1_slot0;
            var33 = _closure1_slot2;
            var11 = 16;
            var12 = var33[var11];
            var12 = var32.bind(var4)(var12);
            var31 = var12.intl;
            var12 = var31.string;
            var11 = var33[var11];
            var11 = var32.bind(var4)(var11);
            var11 = var11.t;
            var11 = var11.6ha5ko;
            var11 = var12.bind(var31)(var11);
            _fun0001_ip = 9; continue _fun0001;
case 7:
            var31 = _closure1_slot0;
            var34 = _closure1_slot2;
            var12 = 16;
            var32 = var34[var12];
            var32 = var31.bind(var4)(var32);
            var33 = var32.intl;
            var32 = var33.format;
            var12 = var34[var12];
            var12 = var31.bind(var4)(var12);
            var12 = var12.t;
            var31 = var12.dNBlTw;
            var12 = {};
            var11 = var32.bind(var33)(var31, var12);
case 9:
            var9['children'] = var11;
            var9 = var3.bind(var4)(var10, var9);
            var8['children'] = var9;
            var9 = var3.bind(var4)(var6, var8);
            var8 = new Array(4);
            var8[0] = var9;
            var10 = var25 != var29;
            var9 = null;
            if(!var10) { _fun0001_ip = 10; continue _fun0001 }
case 11:
            var12 = _closure1_slot11;
            var11 = _closure1_slot13;
            var10 = {};
            var10['ref'] = var30;
            var30 = {};
            var30['height'] = var14;
            var31 = '100%';
            var30['width'] = var31;
            var10['style'] = var30;
            var10['device'] = var29;
            var10['onInitialized'] = var20;
            var29 = _closure1_slot0;
            var30 = _closure1_slot2;
            var20 = 17;
            var20 = var30[var20];
            var29 = var29.bind(var4)(var20);
            var20 = var29.isAndroid;
            var20 = var20.bind(var29)();
            if(var20) { _fun0001_ip = 12; continue _fun0001 }
case 13:
            var20 = !var24;
case 12:
            var10['isActive'] = var20;
            var10['photo'] = var18;
            var10['audio'] = var13;
            var10['video'] = var13;
            var9 = var12.bind(var4)(var11, var10);
case 10:
            var8[1] = var9;
            var10 = var25 != var17;
            var9 = null;
            if(!var10) { _fun0001_ip = 14; continue _fun0001 }
case 15:
            var12 = _closure1_slot11;
            var11 = _closure1_slot1;
            var13 = _closure1_slot2;
            var10 = 18;
            var10 = var13[var10];
            var11 = var11.bind(var4)(var10);
            var10 = {};
            var13 = {};
            var18 = 'absolute';
            var13['position'] = var18;
            var13['height'] = var14;
            var13['width'] = var15;
            var10['style'] = var13;
            var13 = {};
            var15 = var17.node;
            var15 = var15.image;
            var15 = var15.uri;
            var13['uri'] = var15;
            var10['source'] = var13;
            var9 = var12.bind(var4)(var11, var10);
case 14:
            var8[2] = var9;
            var11 = _closure1_slot12;
            var10 = _closure1_slot5;
            var9 = {};
            var13 = var26.controls;
            var12 = new Array(2);
            var12[0] = var13;
            var13 = {};
            var13['height'] = var14;
            var12[1] = var13;
            var9['style'] = var12;
            var12 = var25 == var17;
            var13 = null;
            if(!var12) { _fun0001_ip = 16; continue _fun0001 }
case 17:
            var15 = _closure1_slot11;
            var14 = _closure1_slot0;
            var30 = _closure1_slot2;
            var12 = 19;
            var12 = var30[var12];
            var12 = var14.bind(var4)(var12);
            var14 = var12.PressableOpacity;
            var12 = {};
            var20 = var26.controlButton;
            var18 = new Array(2);
            var18[0] = var20;
            var20 = {};
            var20['bottom'] = var23;
            var20['left'] = var28;
            var18[1] = var20;
            var12['style'] = var18;
            var18 = function onPress() {
                _fun0004: for(var _fun0004_ip = 0; ; ) switch(_fun0004_ip) {
case 0:
                    var1 = _closure2_slot2;
                    var3 = var1.current;
                    var1 = null;
                    if(!(var1 != var3)) { _fun0004_ip = 18; continue _fun0004 }
case 5:
                    var2 = var3.openCustomKeyboard;
                    var1 = {};
                    var8 = _closure1_slot0;
                    var6 = _closure1_slot2;
                    var4 = 20;
                    var6 = var6[var4];
                    var4 = undefined;
                    var4 = var8.bind(var4)(var6);
                    var4 = var4.KeyboardTypes;
                    var4 = var4.MEDIA;
                    var1['type'] = var4;
                    var4 = {};
                    var5 = _closure1_slot8;
                    var5 = var5.CHAT;
                    var4['target'] = var5;
                    var1['context'] = var4;
                    var1 = var2.bind(var3)(var1);
case 18:
                    var5 = _closure1_slot0;
                    var4 = _closure1_slot2;
                    var1 = 21;
                    var3 = var4[var1];
                    var1 = undefined;
                    var6 = var5.bind(var1)(var3);
                    var5 = var6.createPendingReply;
                    var3 = {};
                    var8 = _closure2_slot0;
                    var3['message'] = var8;
                    var7 = _closure2_slot1;
                    var3['channel'] = var7;
                    var7 = true;
                    var3['shouldMention'] = var7;
                    var3 = var5.bind(var6)(var3);
                    var3 = _closure1_slot1;
                    var2 = 22;
                    var2 = var4[var2];
                    var3 = var3.bind(var1)(var2);
                    var2 = var3.hideActionSheet;
                    var2 = var2.bind(var3)();
                    return var1;
                }
            };
            var12['onPress'] = var18;
            var18 = 'Image Gallery';
            var12['accessibilityLabel'] = var18;
            var18 = 'button';
            var12['accessibilityRole'] = var18;
            var29 = _closure1_slot1;
            var18 = 23;
            var18 = var30[var18];
            var20 = var29.bind(var4)(var18);
            var18 = {};
            var24 = 24;
            var24 = var30[var24];
            var24 = var29.bind(var4)(var24);
            var18['source'] = var24;
            var24 = var26.galleryIcon;
            var18['style'] = var24;
            var18 = var15.bind(var4)(var20, var18);
            var12['children'] = var18;
            var13 = var15.bind(var4)(var14, var12);
case 16:
            var12 = new Array(4);
            var12[0] = var13;
            var14 = var25 == var17;
            var13 = null;
            if(!var14) { _fun0001_ip = 19; continue _fun0001 }
case 20:
            var18 = _closure1_slot11;
            var15 = _closure1_slot0;
            var31 = _closure1_slot2;
            var14 = 19;
            var14 = var31[var14];
            var14 = var15.bind(var4)(var14);
            var15 = var14.PressableOpacity;
            var14 = {};
            var24 = var26.controlButton;
            var20 = new Array(2);
            var20[0] = var24;
            var24 = {'top': 8, 'right': 8};
            var20[1] = var24;
            var14['style'] = var20;
            var20 = function onPress() {
                var3 = _closure2_slot6;
                var1 = undefined;
                var2 = function(arg1) {
                    var1 = arg1;
                    var1 = !var1;
                    return var1;
                };
                var2 = var3.bind(var1)(var2);
                return var1;
            };
            var14['onPress'] = var20;
            var20 = 'Swap Camera';
            var14['accessibilityLabel'] = var20;
            var20 = 'button';
            var14['accessibilityRole'] = var20;
            var30 = _closure1_slot1;
            var20 = 23;
            var20 = var31[var20];
            var24 = var30.bind(var4)(var20);
            var20 = {};
            var29 = 25;
            var29 = var31[var29];
            var29 = var30.bind(var4)(var29);
            var20['source'] = var29;
            var29 = var26.icon;
            var20['style'] = var29;
            var20 = var18.bind(var4)(var24, var20);
            var14['children'] = var20;
            var13 = var18.bind(var4)(var15, var14);
case 19:
            var12[1] = var13;
            var14 = var25 != var17;
            var13 = null;
            if(!var14) { _fun0001_ip = 21; continue _fun0001 }
case 22:
            var18 = _closure1_slot11;
            var15 = _closure1_slot0;
            var30 = _closure1_slot2;
            var14 = 19;
            var14 = var30[var14];
            var14 = var15.bind(var4)(var14);
            var15 = var14.PressableOpacity;
            var14 = {};
            var20 = function onPress() {
                _fun0005: for(var _fun0005_ip = 0; ; ) switch(_fun0005_ip) {
case 0:
                    var2 = _closure2_slot10;
                    var3 = null;
                    if(!(var3 != var2)) { _fun0005_ip = 23; continue _fun0005 }
case 24:
                    var5 = _closure1_slot0;
                    var4 = _closure1_slot2;
                    var2 = 26;
                    var4 = var4[var2];
                    var2 = undefined;
                    var8 = var5.bind(var2)(var4);
                    var7 = var8.handleSelectKeyboardItem;
                    var4 = _closure2_slot1;
                    var12 = var4.id;
                    var11 = _closure2_slot10;
                    var13 = var8;
                    var10 = true;
                    var9 = true;
                    var4 = var13[var7](var12, var11, var10, var9, var8);
                    var1 = _closure2_slot11;
                    var1 = var1.bind(var2)(var3);
case 23:
                    var1 = undefined;
                    return var1;
                }
            };
            var14['onPress'] = var20;
            var24 = var26.controlButton;
            var20 = new Array(2);
            var20[0] = var24;
            var24 = {};
            var24['bottom'] = var23;
            var24['right'] = var28;
            var20[1] = var24;
            var14['style'] = var20;
            var20 = 'Retake Photo';
            var14['accessibilityLabel'] = var20;
            var20 = 'button';
            var14['accessibilityRole'] = var20;
            var29 = _closure1_slot1;
            var20 = 23;
            var20 = var30[var20];
            var24 = var29.bind(var4)(var20);
            var20 = {};
            var28 = 27;
            var28 = var30[var28];
            var28 = var29.bind(var4)(var28);
            var20['source'] = var28;
            var28 = var26.icon;
            var20['style'] = var28;
            var20 = var18.bind(var4)(var24, var20);
            var14['children'] = var20;
            var13 = var18.bind(var4)(var15, var14);
case 21:
            var12[2] = var13;
            var15 = _closure1_slot12;
            var14 = _closure1_slot5;
            var13 = {};
            var20 = var26.bottomBar;
            var18 = new Array(2);
            var18[0] = var20;
            var20 = {};
            var20['bottom'] = var23;
            var18[1] = var20;
            var13['style'] = var18;
            var18 = 'box-none';
            var13['pointerEvents'] = var18;
            var18 = null;
            if(!var19) { _fun0001_ip = 25; continue _fun0001 }
case 26:
            var20 = _closure1_slot11;
            var29 = _closure1_slot0;
            var30 = _closure1_slot2;
            var16 = var30[var16];
            var16 = var29.bind(var4)(var16);
            var19 = var16.Text;
            var16 = {'variant': 'text-md/semibold', 'color': 'text-feedback-critical'};
            var23 = var26.errorText;
            var16['style'] = var23;
            var23 = 16;
            var24 = var30[var23];
            var24 = var29.bind(var4)(var24);
            var28 = var24.intl;
            var24 = var28.string;
            var23 = var30[var23];
            var23 = var29.bind(var4)(var23);
            var23 = var23.t;
            var23 = var23.z++Kz/;
            var23 = var24.bind(var28)(var23);
            var16['children'] = var23;
            var18 = var20.bind(var4)(var19, var16);
case 25:
            var16 = new Array(2);
            var16[0] = var18;
            var19 = _closure1_slot11;
            var20 = _closure1_slot0;
            var23 = _closure1_slot2;
            var18 = 19;
            var18 = var23[var18];
            var18 = var20.bind(var4)(var18);
            var18 = var18.PressableOpacity;
            if(!(var25 == var17)) { _fun0001_ip = 27; continue _fun0001 }
case 28:
            var17 = {};
            var20 = function onPress() {
                _fun0006: for(var _fun0006_ip = 0; ; ) switch(_fun0006_ip) {
case 0:
                    var3 = _closure2_slot10;
                    var2 = null;
                    if(!(var2 == var3)) { _fun0006_ip = 29; continue _fun0006 }
case 24:
                    var5 = _closure2_slot4;
                    var3 = undefined;
                    var2 = true;
                    var4 = var5.bind(var3)(var2);
                    var4 = false;
                    var4 = var5.bind(var3)(var4);
                    var1 = _closure2_slot9;
                    var1 = var1.bind(var3)(var2);
case 29:
                    var1 = undefined;
                    return var1;
                }
            };
            var17['onPress'] = var20;
            var23 = var26.mainCTAWrapper;
            var20 = new Array(2);
            var20[0] = var23;
            var23 = null;
            if(var27) { _fun0001_ip = 30; continue _fun0001 }
case 31:
            var23 = var26.disabled;
case 30:
            var20[1] = var23;
            var17['style'] = var20;
            var20 = !var27;
            var17['disabled'] = var20;
            var20 = 'Take Photo';
            var17['accessibilityLabel'] = var20;
            var20 = 'button';
            var17['accessibilityRole'] = var20;
            var24 = _closure1_slot11;
            var29 = _closure1_slot1;
            var30 = _closure1_slot2;
            var20 = 23;
            var20 = var30[var20];
            var23 = var29.bind(var4)(var20);
            var20 = {};
            var28 = 34;
            var28 = var30[var28];
            var28 = var29.bind(var4)(var28);
            var20['source'] = var28;
            var28 = var26.mainCTA;
            var20['style'] = var28;
            var20 = var24.bind(var4)(var23, var20);
            var17['children'] = var20;
            _fun0001_ip = 32; continue _fun0001;
case 27:
            var20 = {};
            var22 = function onPress() {
                var3 = _closure1_slot1;
                var4 = _closure1_slot2;
                var1 = 28;
                var2 = var4[var1];
                var1 = undefined;
                var7 = var3.bind(var1)(var2);
                var6 = var7.parse;
                var2 = _closure2_slot1;
                var5 = '';
                var8 = var6.bind(var7)(var2, var5);
                var12 = _closure1_slot7;
                var10 = var12.getUploads;
                var7 = var2.id;
                var5 = _closure1_slot6;
                var6 = var5.ChannelMessage;
                var10 = var10.bind(var12)(var7, var6);
                var _closure3_slot0 = var10;
                var7 = _closure1_slot0;
                var6 = 21;
                var6 = var4[var6];
                var12 = var7.bind(var1)(var6);
                var7 = var12.createPendingReply;
                var6 = {};
                var13 = _closure2_slot0;
                var6['message'] = var13;
                var6['channel'] = var2;
                var13 = true;
                var6['shouldMention'] = var13;
                var6 = var7.bind(var12)(var6);
                var6 = 29;
                var6 = var4[var6];
                var12 = var3.bind(var1)(var6);
                var7 = var12.clearAll;
                var6 = var2.id;
                var5 = var5.ChannelMessage;
                var5 = var7.bind(var12)(var6, var5);
                var5 = 30;
                var5 = var4[var5];
                var7 = var3.bind(var1)(var5);
                var6 = var7.sendMessage;
                var17 = var2.id;
                var2 = {};
                var11 = _closure1_slot9;
                var11 = var11.CHANNEL_PROMPT;
                var2['location'] = var11;
                var2['attachmentsToUpload'] = var10;
                var9 = function onAttachmentUploadError(arg1, arg2, arg3) {
                    _fun0007: for(var _fun0007_ip = 0; ; ) switch(_fun0007_ip) {
case 0:
                        var4 = _closure1_slot0;
                        var3 = _closure1_slot2;
                        var1 = 31;
                        var3 = var3[var1];
                        var1 = undefined;
                        var6 = var4.bind(var1)(var3);
                        var5 = var6.handleUploadMessageAttachmentsErrors;
                        var4 = {};
                        var3 = arg1;
                        var4['file'] = var3;
                        var8 = _closure2_slot1;
                        var7 = var8.getGuildId;
                        var7 = var7.bind(var8)();
                        var4['guildId'] = var7;
                        var7 = new Array(0);
                        var4['analyticsLocations'] = var7;
                        var7 = arg2;
                        var4['code'] = var7;
                        var7 = arg3;
                        var4['reason'] = var7;
                        var4 = var5.bind(var6)(var4);
                        if(!var4) { _fun0007_ip = 33; continue _fun0007 }
case 34:
                        var5 = _closure1_slot1;
                        var6 = _closure1_slot2;
                        var4 = 29;
                        var4 = var6[var4];
                        var8 = var5.bind(var1)(var4);
                        var7 = var8.setUploads;
                        var4 = {};
                        var3 = _closure2_slot1;
                        var9 = var3.id;
                        var4['channelId'] = var9;
                        var9 = _closure3_slot0;
                        var4['uploads'] = var9;
                        var2 = _closure1_slot6;
                        var9 = var2.ChannelMessage;
                        var4['draftType'] = var9;
                        var9 = true;
                        var4['resetState'] = var9;
                        var4 = var7.bind(var8)(var4);
                        var4 = 32;
                        var4 = var6[var4];
                        var6 = var5.bind(var1)(var4);
                        var5 = var6.saveDraft;
                        var4 = var3.id;
                        var3 = var2.ChannelMessage;
                        var2 = '';
                        var2 = var5.bind(var6)(var4, var2, var3);
case 33:
                        return var1;
                    }
                };
                var2['onAttachmentUploadError'] = var9;
                var18 = var7;
                var16 = var8;
                var15 = undefined;
                var14 = var2;
                var2 = var18[var6](var17, var16, var15, var14, var13);
                var2 = 22;
                var2 = var4[var2];
                var3 = var3.bind(var1)(var2);
                var2 = var3.hideActionSheet;
                var2 = var2.bind(var3)();
                return var1;
            };
            var20['onPress'] = var22;
            var22 = var26.mainCTAWrapper;
            var20['style'] = var22;
            var22 = !var27;
            var20['disabled'] = var22;
            var22 = 'Send Photo';
            var20['accessibilityLabel'] = var22;
            var22 = 'button';
            var20['accessibilityRole'] = var22;
            var23 = _closure1_slot11;
            var28 = _closure1_slot1;
            var29 = _closure1_slot2;
            var21 = 23;
            var21 = var29[var21];
            var22 = var28.bind(var4)(var21);
            var21 = {};
            var24 = 33;
            var24 = var29[var24];
            var24 = var28.bind(var4)(var24);
            var21['source'] = var24;
            var28 = var26.mainCTA;
            var24 = new Array(2);
            var24[0] = var28;
            var25 = null;
            if(var27) { _fun0001_ip = 35; continue _fun0001 }
case 36:
            var25 = var26.disabled;
case 35:
            var24[1] = var25;
            var21['style'] = var24;
            var21 = var23.bind(var4)(var22, var21);
            var20['children'] = var21;
            var17 = var20;
case 32:
            var17 = var19.bind(var4)(var18, var17);
            var16[1] = var17;
            var13['children'] = var16;
            var13 = var15.bind(var4)(var14, var13);
            var12[3] = var13;
            var9['children'] = var12;
            var9 = var11.bind(var4)(var10, var9);
            var8[3] = var9;
            var5['children'] = var8;
            var5 = var7.bind(var4)(var6, var5);
            var1['children'] = var5;
            var1 = var3.bind(var4)(var2, var1);
            return var1;
        }
    };
    var3['default'] = var2;
    return var1;
})();