// app/design/components/TableRow/native/TableRowConstants.tsx
export default (function(_, argBar, __, ___, ____, argFre, argPlu) {
    report = argBar;
    zuuluu = argFre;
    tangon = argPlu;
    entity = global;
    golfie = entity.Object;
    oscard = golfie.defineProperty;
    michal = {};
    entity = true;
    michal['value'] = entity;
    entity = '__esModule';
    entity = oscard.bind(golfie)(zuuluu, entity, michal);
    entity = 0;
    michal = tangon[entity];
    entity = undefined;
    michal = report.bind(entity)(michal);
    oscard = michal.Platform;
    michal = michal.StyleSheet;
    michal = 1;
    tangon = tangon[michal];
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'design/components/TableRow/native/TableRowConstants.tsx';
    tangon = report.bind(oscard)(tangon);
    tangon = 60;
    zuuluu['TABLE_ROW_HEIGHT'] = tangon;
    tangon = 36;
    zuuluu['TABLE_ROW_CONTENT_HEIGHT'] = tangon;
    tangon = 32;
    zuuluu['TABLE_ROW_ICON_SIZE'] = tangon;
    tangon = 12;
    zuuluu['TABLE_ROW_PADDING'] = tangon;
    tangon = 56;
    zuuluu['TABLE_ROW_DIVIDER_PADDING'] = tangon;
    zuuluu['TABLE_DIVIDER_WIDTH'] = michal;
    return entity;
})();