// app/modules/shared_space_warnings/show_gdm_modal/showGdmBlockedUserModal.native.tsx
export default (function(argFoo, argBar, argBaz, _, __, argFred, argPlugh) {
    report = argBar;
    zulu = argFred;
    tango = argPlugh;
    var _closure1_slot0 = report;
    entity = argBaz;
    var _closure1_slot1 = entity;
    var _closure1_slot2 = tango;
    entity = global;
    options = entity.Object;
    golf = options.defineProperty;
    oscar = {};
    entity = true;
    oscar['value'] = entity;
    entity = '__esModule';
    entity = golf.bind(options)(zulu, entity, oscar);
    entity = 3;
    tango = tango[entity];
    entity = undefined;
    oscar = report.bind(entity)(tango);
    report = oscar.fileFinishedImporting;
    tango = 'modules/shared_space_warnings/show_gdm_modal/showGdmBlockedUserModal.native.tsx';
    tango = report.bind(oscar)(tango);
    mike = function(argFoo) { // Original name: showGdmBlockedUserModal
        entity = argFoo;
        options = entity.channelId;
        golf = entity.blockedUserIds;
        mike = entity.ignoredUserIds;
        oscar = _closure1_slot1;
        zulu = _closure1_slot2;
        entity = 0;
        report = zulu[entity];
        entity = undefined;
        oscar = oscar.bind(entity)(report);
        report = oscar.openLazy;
        verify = _closure1_slot0;
        tango = 2;
        tango = zulu[tango];
        verify = verify.bind(entity)(tango);
        tango = 1;
        tango = zulu[tango];
        zulu = zulu.paths;
        tango = verify.bind(entity)(tango, zulu);
        zulu = {};
        zulu['channelId'] = options;
        zulu['blockedUserIds'] = golf;
        zulu['ignoredUserIds'] = mike;
        mike = 'gdm_blocked_user_action_sheet';
        mike = report.bind(oscar)(tango, mike, zulu);
        return entity;
    };
    zulu['showGdmBlockedUserModal'] = mike;
    return entity;
})();