// app/modules/collectibles/CollectiblesShopHomeStore.tsx
export default (function(argFoo, argBar, argBaz, _, __, argFre, argPlu) {
    oscard = argBaz;
    zuuluu = argFre;
    report = argPlu;
    entity = function() { // Original name: _isNativeReflectConstruct
        _fun00001: for(var _fun00002_ip = 0; ; ) switch(_fun00002_ip) {
 0:
 2: // try_start_0
            michal = global;
            zuuluu = michal.Boolean;
            zuuluu = zuuluu.prototype;
            tangon = zuuluu.valueOf;
            zuuluu = tangon.call;
            option = michal.Reflect;
            golfie = option.construct;
            oscard = michal.Boolean;
            report = new Array(0);
            michal = function() {
                entity = undefined;
                return entity;
            };
            michal = golfie.bind(option)(oscard, report, michal);
            michal = zuuluu.bind(tangon)(michal);
            michal = !michal;
            var _closure2_slot0 = michal;
 70: // try_end0
            _fun00002_ip = 74; continue _fun00001;
 72: // catch_target0
            CatchBlockStart(arg_register=1);
 74:
            michal = function() { // Original name: _isNativeReflectConstruct
                entity = _closure2_slot0;
                entity = !entity;
                entity = !entity;
                return entity;
            };
            _closure1_slot13 = michal;
            entity = undefined;
            entity = michal.bind(entity)();
            return entity;
        }
    };
    var _closure1_slot13 = entity;
    michal = global;
    verify = michal.Object;
    option = verify.defineProperty;
    golfie = {};
    entity = true;
    golfie['value'] = entity;
    entity = '__esModule';
    entity = option.bind(verify)(zuuluu, entity, golfie);
    entity = 0;
    golfie = report[entity];
    entity = undefined;
    golfie = oscard.bind(entity)(golfie);
    var _closure1_slot0 = golfie;
    golfie = 1;
    golfie = report[golfie];
    golfie = oscard.bind(entity)(golfie);
    var _closure1_slot1 = golfie;
    golfie = 2;
    golfie = report[golfie];
    golfie = oscard.bind(entity)(golfie);
    var _closure1_slot2 = golfie;
    golfie = 3;
    golfie = report[golfie];
    golfie = oscard.bind(entity)(golfie);
    var _closure1_slot3 = golfie;
    golfie = 4;
    golfie = report[golfie];
    golfie = oscard.bind(entity)(golfie);
    var _closure1_slot4 = golfie;
    golfie = new Array(0);
    var _closure1_slot5 = golfie;
    golfie = michal.Map;
    option = golfie.prototype;
    option = Object.create(option, {constructor: {value: golfie}});
    foxtra = option;
    golfie = new foxtra[golfie](romeon);
    golfie = golfie instanceof Object ? golfie : option;
    var _closure1_slot6 = golfie;
    golfie = michal.Map;
    option = golfie.prototype;
    option = Object.create(option, {constructor: {value: golfie}});
    foxtra = option;
    golfie = new foxtra[golfie](romeon);
    golfie = golfie instanceof Object ? golfie : option;
    var _closure1_slot7 = golfie;
    golfie = michal.Map;
    option = golfie.prototype;
    option = Object.create(option, {constructor: {value: golfie}});
    foxtra = option;
    golfie = new foxtra[golfie](romeon);
    golfie = golfie instanceof Object ? golfie : option;
    var _closure1_slot8 = golfie;
    golfie = michal.Map;
    option = golfie.prototype;
    option = Object.create(option, {constructor: {value: golfie}});
    foxtra = option;
    golfie = new foxtra[golfie](romeon);
    golfie = golfie instanceof Object ? golfie : option;
    var _closure1_slot9 = golfie;
    golfie = michal.Map;
    option = golfie.prototype;
    option = Object.create(option, {constructor: {value: golfie}});
    foxtra = option;
    golfie = new foxtra[golfie](romeon);
    golfie = golfie instanceof Object ? golfie : option;
    var _closure1_slot10 = golfie;
    michal = michal.Map;
    golfie = michal.prototype;
    golfie = Object.create(golfie, {constructor: {value: michal}});
    foxtra = golfie;
    michal = new foxtra[michal](romeon);
    michal = michal instanceof Object ? michal : golfie;
    var _closure1_slot11 = michal;
    var _closure1_slot12 = entity;
    michal = 5;
    michal = report[michal];
    michal = oscard.bind(entity)(michal);
    golfie = michal.Store;
    michal = function(argFoo) {
        tangon = function() { // Original name: CollectiblesShopHomesStore
            _fun00003: for(var _fun00004_ip = 0; ; ) switch(_fun00004_ip) {
 0:
                tangon = this;
                zuuluu = undefined;
                report = undefined;
                entity = _closure1_slot0;
                michal = _closure2_slot0;
                entity = entity.bind(zuuluu)(tangon, michal);
                entity = _closure1_slot3;
                verify = entity.bind(zuuluu)(michal);
                michal = _closure1_slot2;
                entity = _closure1_slot13;
                entity = entity.bind(zuuluu)();
                if(entity) { _fun00004_ip = 69; continue _fun00003 }
 51:
                golfie = verify.apply;
                report = arguments;
                entity = report;
                entity = golfie.bind(verify)(tangon, entity);
                _fun00004_ip = 105; continue _fun00003;
 69:
                golfie = global;
                option = golfie.Reflect;
                golfie = option.construct;
                oscard = _closure1_slot3;
                oscard = oscard.bind(zuuluu)(tangon);
                oscard = oscard.constructor;
                report = arguments;
                entity = golfie.bind(option)(verify, report, oscard);
 105:
                entity = michal.bind(zuuluu)(tangon, entity);
                return entity;
            }
        };
        var _closure2_slot0 = tangon;
        report = _closure1_slot4;
        zuuluu = undefined;
        michal = argFoo;
        michal = report.bind(zuuluu)(tangon, michal);
        michal = _closure1_slot1;
        report = {};
        entity = 'getLastSuccessfulFetch';
        report['key'] = entity;
        entity = function(argFoo) { // Original name: value
            zuuluu = _closure1_slot6;
            michal = zuuluu.get;
            entity = argFoo;
            entity = michal.bind(zuuluu)(entity);
            return entity;
        };
        report['value'] = entity;
        entity = new Array(7);
        entity[0] = report;
        report = {};
        golfie = 'getLastErrorTimestamp';
        report['key'] = golfie;
        golfie = function(argFoo) { // Original name: value
            zuuluu = _closure1_slot7;
            michal = zuuluu.get;
            entity = argFoo;
            entity = michal.bind(zuuluu)(entity);
            return entity;
        };
        report['value'] = golfie;
        entity[1] = report;
        report = {};
        golfie = 'getLastFetchOptions';
        report['key'] = golfie;
        golfie = function(argFoo) { // Original name: value
            zuuluu = _closure1_slot8;
            michal = zuuluu.get;
            entity = argFoo;
            entity = michal.bind(zuuluu)(entity);
            return entity;
        };
        report['value'] = golfie;
        entity[2] = report;
        report = {};
        golfie = 'getFetchShopHomeError';
        report['key'] = golfie;
        golfie = function(argFoo) { // Original name: value
            zuuluu = _closure1_slot9;
            michal = zuuluu.get;
            entity = argFoo;
            entity = michal.bind(zuuluu)(entity);
            return entity;
        };
        report['value'] = golfie;
        entity[3] = report;
        report = {};
        golfie = 'getIsFetchingShopHome';
        report['key'] = golfie;
        golfie = function(argFoo) { // Original name: value
            zuuluu = _closure1_slot10;
            michal = zuuluu.get;
            entity = argFoo;
            entity = michal.bind(zuuluu)(entity);
            return entity;
        };
        report['value'] = golfie;
        entity[4] = report;
        report = {};
        golfie = 'getShopBlocks';
        report['key'] = golfie;
        golfie = function(argFoo) { // Original name: value
            _fun00005: for(var _fun00006_ip = 0; ; ) switch(_fun00006_ip) {
 0:
                tangon = _closure1_slot11;
                zuuluu = tangon.get;
                entity = argFoo;
                entity = zuuluu.bind(tangon)(entity);
                zuuluu = null;
                if(!(zuuluu == entity)) { _fun00006_ip = 30; continue _fun00005 }
 26:
                entity = _closure1_slot5;
 30:
                return entity;
            }
        };
        report['value'] = golfie;
        entity[5] = report;
        report = {};
        golfie = 'getShopHomeConfigOverride';
        report['key'] = golfie;
        oscard = function() { // Original name: value
            entity = _closure1_slot12;
            return entity;
        };
        report['value'] = oscard;
        entity[6] = report;
        entity = michal.bind(zuuluu)(tangon, entity);
        return entity;
    };
    golfie = michal.bind(entity)(golfie);
    michal = 'CollectiblesShopHomesStore';
    golfie['displayName'] = michal;
    michal = 6;
    michal = report[michal];
    romeon = oscard.bind(entity)(michal);
    michal = {};
    option = function(argFoo) { // Original name: COLLECTIBLES_SHOP_HOME_FETCH
        michal = argFoo;
        oscard = _closure1_slot10;
        report = oscard.set;
        tangon = michal.tab;
        entity = true;
        entity = report.bind(oscard)(tangon, entity);
        oscard = _closure1_slot9;
        report = oscard.set;
        tangon = michal.tab;
        entity = undefined;
        tangon = report.bind(oscard)(tangon, entity);
        golfie = _closure1_slot8;
        oscard = golfie.set;
        report = michal.tab;
        tangon = michal.options;
        tangon = oscard.bind(golfie)(report, tangon);
        oscard = golfie.set;
        report = michal.tab;
        tangon = michal.options;
        tangon = oscard.bind(golfie)(report, tangon);
        tangon = _closure1_slot7;
        zuuluu = tangon.set;
        michal = michal.tab;
        michal = zuuluu.bind(tangon)(michal, entity);
        return entity;
    };
    michal['COLLECTIBLES_SHOP_HOME_FETCH'] = option;
    option = function(argFoo) { // Original name: COLLECTIBLES_SHOP_HOME_FETCH_SUCCESS
        michal = argFoo;
        oscard = _closure1_slot11;
        report = oscard.set;
        tangon = michal.tab;
        entity = michal.shopHome;
        entity = entity.shopBlocks;
        entity = report.bind(oscard)(tangon, entity);
        oscard = _closure1_slot6;
        report = oscard.set;
        tangon = michal.tab;
        entity = global;
        golfie = entity.Date;
        entity = golfie.now;
        entity = entity.bind(golfie)();
        entity = report.bind(oscard)(tangon, entity);
        oscard = _closure1_slot10;
        report = oscard.set;
        tangon = michal.tab;
        entity = false;
        entity = report.bind(oscard)(tangon, entity);
        oscard = _closure1_slot9;
        report = oscard.set;
        tangon = michal.tab;
        entity = undefined;
        tangon = report.bind(oscard)(tangon, entity);
        tangon = _closure1_slot7;
        zuuluu = tangon.set;
        michal = michal.tab;
        michal = zuuluu.bind(tangon)(michal, entity);
        return entity;
    };
    michal['COLLECTIBLES_SHOP_HOME_FETCH_SUCCESS'] = option;
    option = function(argFoo) { // Original name: COLLECTIBLES_SHOP_HOME_FETCH_FAILURE
        entity = argFoo;
        oscard = _closure1_slot11;
        report = oscard.set;
        tangon = entity.tab;
        zuuluu = _closure1_slot5;
        zuuluu = report.bind(oscard)(tangon, zuuluu);
        oscard = _closure1_slot10;
        report = oscard.set;
        tangon = entity.tab;
        zuuluu = false;
        zuuluu = report.bind(oscard)(tangon, zuuluu);
        oscard = _closure1_slot9;
        report = oscard.set;
        tangon = entity.tab;
        zuuluu = entity.error;
        zuuluu = report.bind(oscard)(tangon, zuuluu);
        tangon = _closure1_slot7;
        zuuluu = tangon.set;
        michal = entity.tab;
        entity = global;
        report = entity.Date;
        entity = report.now;
        entity = entity.bind(report)();
        entity = zuuluu.bind(tangon)(michal, entity);
        entity = undefined;
        return entity;
    };
    michal['COLLECTIBLES_SHOP_HOME_FETCH_FAILURE'] = option;
    option = function(argFoo) { // Original name: COLLECTIBLES_SET_SHOP_HOME_CONFIG_OVERRIDE
        entity = argFoo;
        michal = entity.shopHomeConfigOverride;
        _closure1_slot12 = michal;
        entity = undefined;
        return entity;
    };
    michal['COLLECTIBLES_SET_SHOP_HOME_CONFIG_OVERRIDE'] = option;
    tangon = function() { // Original name: LOGOUT
        zuuluu = _closure1_slot11;
        entity = zuuluu.clear;
        entity = entity.bind(zuuluu)();
        zuuluu = _closure1_slot8;
        entity = zuuluu.clear;
        entity = entity.bind(zuuluu)();
        zuuluu = _closure1_slot9;
        entity = zuuluu.clear;
        entity = entity.bind(zuuluu)();
        zuuluu = _closure1_slot10;
        entity = zuuluu.clear;
        entity = entity.bind(zuuluu)();
        zuuluu = _closure1_slot6;
        entity = zuuluu.clear;
        entity = entity.bind(zuuluu)();
        zuuluu = _closure1_slot7;
        entity = zuuluu.clear;
        entity = entity.bind(zuuluu)();
        entity = undefined;
        _closure1_slot12 = entity;
        return entity;
    };
    michal['LOGOUT'] = tangon;
    tangon = golfie.prototype;
    tangon = Object.create(tangon, {constructor: {value: golfie}});
    foxtra = tangon;
    yankee = michal;
    michal = new foxtra[golfie](romeon, yankee, offset);
    michal = michal instanceof Object ? michal : tangon;
    tangon = 7;
    report = report[tangon];
    tangon = argBar;
    oscard = tangon.bind(entity)(report);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/collectibles/CollectiblesShopHomeStore.tsx';
    tangon = report.bind(oscard)(tangon);
    zuuluu['default'] = michal;
    return entity;
})();