// app/modules/premium/roadblocks/native/utils/openPremiumUpsellActionSheet.tsx
export default (function(argFoo, argBar, argBaz, _, __, argFred, argPlugh) {
    report = argBar;
    zulu = argFred;
    tango = argPlugh;
    var _closure1_slot0 = report;
    entity = argBaz;
    var _closure1_slot1 = entity;
    var _closure1_slot2 = tango;
    entity = global;
    options = entity.Object;
    golf = options.defineProperty;
    oscar = {};
    entity = true;
    oscar['value'] = entity;
    entity = '__esModule';
    entity = golf.bind(options)(zulu, entity, oscar);
    entity = 3;
    tango = tango[entity];
    entity = undefined;
    oscar = report.bind(entity)(tango);
    report = oscar.fileFinishedImporting;
    tango = 'modules/premium/roadblocks/native/utils/openPremiumUpsellActionSheet.tsx';
    tango = report.bind(oscar)(tango);
    mike = function(argFoo) { // Original name: openPremiumUpsellActionSheet
        report = _closure1_slot1;
        mike = _closure1_slot2;
        entity = 0;
        tango = mike[entity];
        entity = undefined;
        oscar = report.bind(entity)(tango);
        report = oscar.openLazy;
        tango = _closure1_slot0;
        zulu = 2;
        zulu = mike[zulu];
        tango = tango.bind(entity)(zulu);
        zulu = 1;
        zulu = mike[zulu];
        mike = mike.paths;
        tango = tango.bind(entity)(zulu, mike);
        zulu = {};
        mike = argFoo;
        zulu['featureName'] = mike;
        mike = 'PremiumUpsellActionSheetKey';
        mike = report.bind(oscar)(tango, mike, zulu);
        return entity;
    };
    zulu['default'] = mike;
    mike = 'PremiumUpsellActionSheetKey';
    zulu['PREMIUM_UPSELL_ACTION_SHEET_KEY'] = mike;
    return entity;
})();