// app/modules/age_assurance/native/AgeVerificationGetStartedModal.tsx
export default (function(argFoo, argBar, argBaz, argCor, _, argFre, argPlu) {
    report = argBar;
    yankee = argBaz;
    zuuluu = argFre;
    oscard = argPlu;
    var _closure1_slot0 = report;
    var _closure1_slot1 = yankee;
    var _closure1_slot2 = oscard;
    entity = global;
    option = entity.Object;
    golfie = option.defineProperty;
    tangon = {};
    entity = true;
    tangon['value'] = entity;
    entity = '__esModule';
    entity = golfie.bind(option)(zuuluu, entity, tangon);
    entity = 0;
    golfie = oscard[entity];
    tangon = argCor;
    entity = undefined;
    tangon = tangon.bind(entity)(golfie);
    var _closure1_slot3 = tangon;
    tangon = 1;
    tangon = oscard[tangon];
    tangon = report.bind(entity)(tangon);
    tangon = tangon.jsx;
    var _closure1_slot4 = tangon;
    tangon = 2;
    tangon = oscard[tangon];
    option = report.bind(entity)(tangon);
    golfie = option.createStyles;
    tangon = {};
    verify = {};
    offset = 3;
    offset = oscard[offset];
    offset = yankee.bind(entity)(offset);
    offset = offset.colors;
    offset = offset.BACKGROUND_MOBILE_PRIMARY;
    verify['backgroundColor'] = offset;
    offset = 'transparent';
    verify['shadowColor'] = offset;
    tangon['headerStyle'] = verify;
    tangon = golfie.bind(option)(tangon);
    var _closure1_slot5 = tangon;
    tangon = {};
    golfie = 'INTRO';
    tangon['INTRO'] = golfie;
    golfie = 'RETRY';
    tangon['RETRY'] = golfie;
    var _closure1_slot6 = tangon;
    tangon = 12;
    tangon = oscard[tangon];
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/age_assurance/native/AgeVerificationGetStartedModal.tsx';
    tangon = report.bind(oscard)(tangon);
    michal = function(argFoo) { // Original name: AgeVerificationGetStartedModal
        _fun00001: for(var _fun00002_ip = 0; ; ) switch(_fun00002_ip) {
 0:
            michal = argFoo;
            verify = michal.entryPoint;
            var _closure2_slot0 = verify;
            oscard = michal.isRetry;
            michal = _closure1_slot5;
            tangon = undefined;
            michal = michal.bind(tangon)();
            var _closure2_slot1 = michal;
            option = _closure1_slot3;
            offset = option.useMemo;
            golfie = function() {
                zuuluu = _closure1_slot0;
                michal = _closure1_slot2;
                entity = 8;
                michal = michal[entity];
                entity = undefined;
                michal = zuuluu.bind(entity)(michal);
                entity = michal.v4;
                entity = entity.bind(michal)();
                return entity;
            };
            zuuluu = new Array(0);
            offset = offset.bind(option)(golfie, zuuluu);
            var _closure2_slot2 = offset;
            golfie = option.useMemo;
            zuuluu = new Array(2);
            zuuluu[0] = michal;
            zuuluu[1] = offset;
            michal = function() {
                tangon = _closure2_slot1;
                zuuluu = _closure2_slot2;
                michal = function(argFoo, argBar) { // Original name: getScreens
                    offset = argFoo;
                    entity = argBar;
                    var _closure4_slot0 = entity;
                    golfie = function() { // Original name: closeModal
                        zuuluu = _closure1_slot1;
                        michal = _closure1_slot2;
                        entity = 4;
                        michal = michal[entity];
                        entity = undefined;
                        michal = zuuluu.bind(entity)(michal);
                        entity = michal.pop;
                        entity = entity.bind(michal)();
                        return entity;
                    };
                    var _closure4_slot1 = golfie;
                    entity = {};
                    michal = _closure1_slot6;
                    yankee = michal.INTRO;
                    zuuluu = {};
                    oscard = offset.headerStyle;
                    zuuluu['headerStyle'] = oscard;
                    oscard = function() { // Original name: headerTitle
                        entity = null;
                        return entity;
                    };
                    zuuluu['headerTitle'] = oscard;
                    option = _closure1_slot0;
                    verify = _closure1_slot2;
                    report = 5;
                    romeon = verify[report];
                    oscard = undefined;
                    foxtra = option.bind(oscard)(romeon);
                    romeon = foxtra.getHeaderCloseButton;
                    romeon = romeon.bind(foxtra)(golfie);
                    zuuluu['headerLeft'] = romeon;
                    romeon = function() { // Original name: render
                        tangon = _closure1_slot4;
                        michal = _closure1_slot1;
                        zuuluu = _closure1_slot2;
                        entity = 6;
                        entity = zuuluu[entity];
                        zuuluu = undefined;
                        michal = michal.bind(zuuluu)(entity);
                        entity = {};
                        oscard = _closure4_slot1;
                        entity['onClose'] = oscard;
                        report = _closure4_slot0;
                        entity['modalSessionId'] = report;
                        entity = tangon.bind(zuuluu)(michal, entity);
                        return entity;
                    };
                    zuuluu['render'] = romeon;
                    entity[yankee] = zuuluu;
                    zuuluu = michal.RETRY;
                    michal = {};
                    offset = offset.headerStyle;
                    michal['headerStyle'] = offset;
                    offset = function() { // Original name: headerTitle
                        entity = null;
                        return entity;
                    };
                    michal['headerTitle'] = offset;
                    report = verify[report];
                    oscard = option.bind(oscard)(report);
                    report = oscard.getHeaderCloseButton;
                    report = report.bind(oscard)(golfie);
                    michal['headerLeft'] = report;
                    tangon = function() { // Original name: render
                        tangon = _closure1_slot4;
                        michal = _closure1_slot1;
                        zuuluu = _closure1_slot2;
                        entity = 7;
                        entity = zuuluu[entity];
                        zuuluu = undefined;
                        michal = michal.bind(zuuluu)(entity);
                        entity = {};
                        oscard = _closure4_slot1;
                        entity['onClose'] = oscard;
                        report = _closure4_slot0;
                        entity['modalSessionId'] = report;
                        entity = tangon.bind(zuuluu)(michal, entity);
                        return entity;
                    };
                    michal['render'] = tangon;
                    entity[zuuluu] = michal;
                    return entity;
                };
                entity = undefined;
                entity = michal.bind(entity)(tangon, zuuluu);
                return entity;
            };
            golfie = golfie.bind(option)(michal, zuuluu);
            zuuluu = option.useEffect;
            michal = new Array(2);
            michal[0] = offset;
            michal[1] = verify;
            entity = function() {
                golfie = _closure1_slot0;
                option = _closure1_slot2;
                zuuluu = 9;
                michal = option[zuuluu];
                entity = undefined;
                oscard = golfie.bind(entity)(michal);
                report = oscard.trackAgeVerificationModalViewed;
                tangon = _closure2_slot2;
                zuuluu = option[zuuluu];
                zuuluu = golfie.bind(entity)(zuuluu);
                zuuluu = zuuluu.AgeVerificationModalVersion;
                zuuluu = zuuluu.PRIMARY;
                michal = _closure2_slot0;
                michal = report.bind(oscard)(tangon, zuuluu, michal);
                return entity;
            };
            entity = zuuluu.bind(option)(entity, michal);
            zuuluu = _closure1_slot4;
            michal = _closure1_slot0;
            option = _closure1_slot2;
            entity = 10;
            entity = option[entity];
            entity = michal.bind(tangon)(entity);
            michal = entity.Navigator;
            entity = {};
            entity['screens'] = golfie;
            golfie = _closure1_slot6;
            if(oscard) { _fun00002_ip = 180; continue _fun00001 }
 172:
            oscard = golfie.INTRO;
            _fun00002_ip = 186; continue _fun00001;
 180:
            oscard = golfie.RETRY;
 186:
            entity['initialRouteName'] = oscard;
            option = _closure1_slot0;
            verify = _closure1_slot2;
            report = 11;
            oscard = verify[report];
            oscard = option.bind(tangon)(oscard);
            golfie = oscard.intl;
            oscard = golfie.string;
            report = verify[report];
            report = option.bind(tangon)(report);
            report = report.t;
            report = report.13/7kZ;
            report = oscard.bind(golfie)(report);
            entity['headerBackTitle'] = report;
            entity = zuuluu.bind(tangon)(michal, entity);
            return entity;
        }
    };
    zuuluu['default'] = michal;
    return entity;
})();