// app/modules/checkpoint/native/components/openCheckpointModal.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var1 = metroImportDefault;
    var _closure1_slot1 = var1;
    var _closure1_slot2 = var6;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var5.bind(var1)(var4);
    var4 = var4.AnalyticEvents;
    var _closure1_slot3 = var4;
    var4 = 5;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/checkpoint/native/components/openCheckpointModal.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function openCheckpointModal(arg1) {
        var4 = _closure1_slot1;
        var2 = _closure1_slot2;
        var1 = 1;
        var3 = var2[var1];
        var1 = undefined;
        var8 = var4.bind(var1)(var3);
        var7 = var8.track;
        var3 = _closure1_slot3;
        var6 = var3.CHECKPOINT_STARTED;
        var3 = {};
        var9 = arg1;
        var3['source'] = var9;
        var3 = var7.bind(var8)(var6, var3);
        var3 = 2;
        var3 = var2[var3];
        var4 = var4.bind(var1)(var3);
        var3 = var4.pushLazy;
        var6 = _closure1_slot0;
        var5 = 4;
        var5 = var2[var5];
        var6 = var6.bind(var1)(var5);
        var5 = 3;
        var5 = var2[var5];
        var2 = var2.paths;
        var2 = var6.bind(var1)(var5, var2);
        var2 = var3.bind(var4)(var2);
        return var1;
    };
    var3['default'] = var2;
    return var1;
})();