// app/modules/game_community_upsell/native/GameCommunityUpsellDevTools.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var11 = metroImportDefault;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var6;
    var1 = function MultiGuildDevTools() {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var1 = _closure1_slot9;
            var4 = undefined;
            var13 = var1.bind(var4)();
            var6 = _closure1_slot0;
            var7 = _closure1_slot1;
            var1 = 7;
            var2 = var7[var1];
            var8 = var6.bind(var4)(var2);
            var5 = var8.useStateFromStores;
            var2 = _closure1_slot5;
            var3 = new Array(1);
            var3[0] = var2;
            var2 = function() {
                var2 = _closure1_slot5;
                var1 = var2.getUserAgnosticState;
                var1 = var1.bind(var2)();
                return var1;
            };
            var2 = var5.bind(var8)(var3, var2);
            var _closure2_slot0 = var2;
            var1 = var7[var1];
            var5 = var6.bind(var4)(var1);
            var3 = var5.useStateFromStoresObject;
            var1 = _closure1_slot6;
            var2 = new Array(1);
            var2[0] = var1;
            var1 = function() {
                var1 = {};
                var4 = _closure1_slot6;
                var3 = var4.getPresentableUpsellGuilds;
                var3 = var3.bind(var4)();
                var3 = var3.length;
                var1['guildsCount'] = var3;
                var4 = _closure1_slot6;
                var3 = var4.getDismissedGuildIds;
                var3 = var3.bind(var4)();
                var3 = var3.size;
                var1['dismissedCount'] = var3;
                var3 = _closure1_slot6;
                var2 = var3.getLastFetchedAt;
                var2 = var2.bind(var3)();
                var1['lastFetchedAt'] = var2;
                return var1;
            };
            var1 = var3.bind(var5)(var2, var1);
            var30 = var1.guildsCount;
            var29 = var1.dismissedCount;
            var3 = var1.lastFetchedAt;
            var28 = global;
            var5 = var28.Object;
            var2 = var5.entries;
            var1 = 8;
            var1 = var7[var1];
            var1 = var6.bind(var4)(var1);
            var1 = var1.DETECTABLE_GAME_TO_APPLICATION_ID_MAP;
            var5 = var2.bind(var5)(var1);
            var2 = var5.map;
            var1 = function(arg1) {
                _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
case 0:
                    var6 = arg1;
                    var1 = var6[Symbol.iterator];
                    var6 = var1().next;
                    var4 = var6().value;
                    var3 = var1;
                    var2 = undefined;
                    var3 = var3 === var2;
                    var5 = undefined;
                    if(var3) { _fun0002_ip = 2; continue _fun0002 }
case 3:
                    var5 = var4;
case 2:
                    var4 = undefined;
                    if(var3) { _fun0002_ip = 4; continue _fun0002 }
case 5:
                    var7 = var6().value;
                    var6 = var1;
                    var6 = var6 === var2;
                    var4 = undefined;
                    var3 = var6;
                    if(var6) { _fun0002_ip = 4; continue _fun0002 }
case 6:
                    var4 = var7;
                    var3 = var6;
case 4:
                    if(var3) { _fun0002_ip = 7; continue _fun0002 }
case 8:
                    var1.return();
case 7:
                    var1 = _closure2_slot0;
                    var1 = var1.apps;
                    var3 = var1[var5];
                    var1 = {};
                    var1['detectableAppName'] = var5;
                    var1['gameId'] = var4;
                    var4 = null;
                    var5 = var4 == var3;
                    var6 = undefined;
                    if(var5) { _fun0002_ip = 9; continue _fun0002 }
case 10:
                    var6 = var3.detected;
case 9:
                    var5 = var4 != var6;
                    if(!var5) { _fun0002_ip = 11; continue _fun0002 }
case 12:
                    var5 = var6;
case 11:
                    var1['detected'] = var5;
                    var4 = var4 == var3;
                    var2 = undefined;
                    if(var4) { _fun0002_ip = 13; continue _fun0002 }
case 14:
                    var2 = var3.lastScannedAt;
case 13:
                    var1['lastScannedAt'] = var2;
                    return var1;
                }
            };
            var18 = var2.bind(var5)(var1);
            var17 = 0;
            var1 = var3 > var17;
            var27 = 'Never';
            if(!var1) { _fun0001_ip = 15; continue _fun0001 }
case 16:
            var1 = var28.Date;
            var2 = var1.prototype;
            var2 = Object.create(var2, {constructor: {value: var1}});
            var33 = var2;
            var32 = var3;
            var1 = new var33[var1](var32, var31);
            var2 = var1 instanceof Object ? var1 : var2;
            var1 = var2.toLocaleTimeString;
            var3 = var1.bind(var2)();
            var1 = var28.HermesInternal;
            var2 = var1.concat;
            var1 = '';
            var27 = var2.bind(var1)(var3);
case 15:
            var5 = _closure1_slot2;
            var3 = var5.useCallback;
            var2 = function() {
                var3 = _closure1_slot5;
                var2 = var3.DEV_resetState;
                var2 = var2.bind(var3)();
                var3 = _closure1_slot6;
                var2 = var3.DEV_clearFetchCache;
                var2 = var2.bind(var3)();
                var5 = _closure1_slot0;
                var6 = _closure1_slot1;
                var1 = 9;
                var2 = var6[var1];
                var1 = undefined;
                var4 = var5.bind(var1)(var2);
                var3 = var4.detectLocalApps;
                var2 = 10;
                var2 = var6[var2];
                var2 = var5.bind(var1)(var2);
                var2 = var2.ALL_DETECTABLE_APP_NAMES;
                var2 = var3.bind(var4)(var2);
                return var1;
            };
            var1 = new Array(0);
            var19 = var3.bind(var5)(var2, var1);
            var _closure2_slot1 = var19;
            var3 = _closure1_slot7;
            var2 = _closure1_slot3;
            var1 = {};
            var5 = var13.container;
            var1['style'] = var5;
            var7 = _closure1_slot8;
            var6 = _closure1_slot4;
            var5 = {};
            var8 = var13.scrollView;
            var5['style'] = var8;
            var10 = _closure1_slot7;
            var9 = _closure1_slot3;
            var8 = {};
            var11 = var13.section;
            var8['style'] = var11;
            var15 = _closure1_slot7;
            var14 = _closure1_slot0;
            var11 = _closure1_slot1;
            var12 = 11;
            var11 = var11[var12];
            var11 = var14.bind(var4)(var11);
            var14 = var11.TableRowGroup;
            var11 = {};
            var16 = 'Detected Apps';
            var11['title'] = var16;
            var16 = var18.length;
            if(!(var17 !== var16)) { _fun0001_ip = 17; continue _fun0001 }
case 18:
            var17 = var18.map;
            var16 = function(arg1) {
                _fun0003: for(var _fun0003_ip = 0; ; ) switch(_fun0003_ip) {
case 0:
                    var1 = arg1;
                    var5 = _closure1_slot7;
                    var3 = _closure1_slot0;
                    var4 = _closure1_slot1;
                    var2 = 12;
                    var2 = var4[var2];
                    var4 = undefined;
                    var2 = var3.bind(var4)(var2);
                    var3 = var2.TableRow;
                    var2 = {};
                    var6 = var1.detectableAppName;
                    var2['label'] = var6;
                    var11 = var1.gameId;
                    var6 = var1.detected;
                    var10 = 'Not detected';
                    if(!var6) { _fun0003_ip = 19; continue _fun0003 }
case 20:
                    var10 = 'Detected';
case 19:
                    var7 = var1.lastScannedAt;
                    var6 = null;
                    var6 = var6 != var7;
                    var9 = '';
                    if(!var6) { _fun0003_ip = 21; continue _fun0003 }
case 22:
                    var6 = global;
                    var12 = var6.Date;
                    var16 = var1.lastScannedAt;
                    var8 = var12.prototype;
                    var8 = Object.create(var8, {constructor: {value: var12}});
                    var17 = var8;
                    var7 = new var17[var12](var16, var15);
                    var8 = var7 instanceof Object ? var7 : var8;
                    var7 = var8.toLocaleTimeString;
                    var12 = var7.bind(var8)();
                    var6 = var6.HermesInternal;
                    var8 = var6.concat;
                    var7 = ' (scanned ';
                    var6 = ')';
                    var9 = var8.bind(var7)(var12, var6);
case 21:
                    var6 = global;
                    var6 = var6.HermesInternal;
                    var8 = var6.concat;
                    var17 = 'Game ID: ';
                    var15 = ' — ';
                    var16 = var11;
                    var14 = var10;
                    var13 = var9;
                    var6 = var17[var8](var16, var15, var14, var13, var12);
                    var2['subLabel'] = var6;
                    var6 = true;
                    var2['disabled'] = var6;
                    var1 = var1.detectableAppName;
                    var1 = var5.bind(var4)(var3, var2, var1);
                    return var1;
                }
            };
            var16 = var17.bind(var18)(var16);
            _fun0001_ip = 23; continue _fun0001;
case 17:
            var20 = _closure1_slot7;
            var18 = _closure1_slot0;
            var22 = _closure1_slot1;
            var17 = 12;
            var17 = var22[var17];
            var17 = var18.bind(var4)(var17);
            var18 = var17.TableRow;
            var17 = {'label': 'No games configured', 'subLabel': 'MULTI_GUILD_GAME_CONFIGS is empty', 'disabled': true};
            var16 = var20.bind(var4)(var18, var17);
case 23:
            var11['children'] = var16;
            var11 = var15.bind(var4)(var14, var11);
            var8['children'] = var11;
            var9 = var10.bind(var4)(var9, var8);
            var8 = new Array(3);
            var8[0] = var9;
            var11 = _closure1_slot7;
            var10 = _closure1_slot3;
            var9 = {};
            var14 = var13.section;
            var9['style'] = var14;
            var17 = _closure1_slot8;
            var20 = _closure1_slot0;
            var22 = _closure1_slot1;
            var14 = var22[var12];
            var14 = var20.bind(var4)(var14);
            var15 = var14.TableRowGroup;
            var14 = {};
            var16 = 'Store State';
            var14['title'] = var16;
            var25 = _closure1_slot7;
            var16 = 12;
            var18 = var22[var16];
            var18 = var20.bind(var4)(var18);
            var23 = var18.TableRow;
            var18 = {'label': 'Presentable Guilds', 'subLabel': null, 'disabled': true};
            var26 = var28.String;
            var26 = var26.bind(var4)(var30);
            var18['subLabel'] = var26;
            var23 = var25.bind(var4)(var23, var18);
            var18 = new Array(3);
            var18[0] = var23;
            var26 = _closure1_slot7;
            var23 = var22[var16];
            var23 = var20.bind(var4)(var23);
            var25 = var23.TableRow;
            var23 = {'label': 'Dismissed Guilds', 'subLabel': null, 'disabled': true};
            var28 = var28.String;
            var28 = var28.bind(var4)(var29);
            var23['subLabel'] = var28;
            var23 = var26.bind(var4)(var25, var23);
            var18[1] = var23;
            var26 = _closure1_slot7;
            var23 = var22[var16];
            var23 = var20.bind(var4)(var23);
            var25 = var23.TableRow;
            var23 = {'label': 'Last Fetched', 'subLabel': null, 'disabled': true};
            var23['subLabel'] = var27;
            var23 = var26.bind(var4)(var25, var23);
            var18[2] = var23;
            var14['children'] = var18;
            var14 = var17.bind(var4)(var15, var14);
            var9['children'] = var14;
            var9 = var11.bind(var4)(var10, var9);
            var8[1] = var9;
            var11 = _closure1_slot7;
            var10 = _closure1_slot3;
            var9 = {};
            var13 = var13.section;
            var9['style'] = var13;
            var14 = _closure1_slot8;
            var12 = var22[var12];
            var12 = var20.bind(var4)(var12);
            var13 = var12.TableRowGroup;
            var12 = {};
            var15 = 'Actions';
            var12['title'] = var15;
            var18 = _closure1_slot7;
            var15 = var22[var16];
            var15 = var20.bind(var4)(var15);
            var17 = var15.TableRow;
            var15 = {'label': 'Refresh Upsell Guilds', 'subLabel': 'Redects games and suggested guilds'};
            var15['onPress'] = var19;
            var26 = _closure1_slot7;
            var23 = 13;
            var19 = var22[var23];
            var19 = var20.bind(var4)(var19);
            var25 = var19.RefreshIcon;
            var19 = {};
            var19 = var26.bind(var4)(var25, var19);
            var15['icon'] = var19;
            var27 = _closure1_slot7;
            var19 = 14;
            var25 = var22[var19];
            var25 = var20.bind(var4)(var25);
            var26 = var25.TableRowArrow;
            var25 = {};
            var25 = var27.bind(var4)(var26, var25);
            var15['trailing'] = var25;
            var17 = var18.bind(var4)(var17, var15);
            var15 = new Array(4);
            var15[0] = var17;
            var25 = _closure1_slot7;
            var17 = var22[var16];
            var17 = var20.bind(var4)(var17);
            var18 = var17.TableRow;
            var17 = {'label': 'Clear Dismissed Guilds', 'subLabel': 'Reset dismissed guild IDs so all guilds show again'};
            var26 = function onPress() {
                var2 = _closure1_slot6;
                var1 = var2.DEV_clearDismissedGuilds;
                var1 = var1.bind(var2)();
                var2 = _closure2_slot1;
                var1 = undefined;
                var2 = var2.bind(var1)();
                return var1;
            };
            var17['onPress'] = var26;
            var28 = _closure1_slot7;
            var26 = var22[var23];
            var26 = var20.bind(var4)(var26);
            var27 = var26.RefreshIcon;
            var26 = {};
            var26 = var28.bind(var4)(var27, var26);
            var17['icon'] = var26;
            var28 = _closure1_slot7;
            var26 = var22[var19];
            var26 = var20.bind(var4)(var26);
            var27 = var26.TableRowArrow;
            var26 = {};
            var26 = var28.bind(var4)(var27, var26);
            var17['trailing'] = var26;
            var17 = var25.bind(var4)(var18, var17);
            var15[1] = var17;
            var25 = _closure1_slot7;
            var17 = var22[var16];
            var17 = var20.bind(var4)(var17);
            var18 = var17.TableRow;
            var17 = {'label': 'Clear All Store State', 'subLabel': 'Reset all MobileGameCommunitiesStore state (guilds, dismissed, fetch cache)'};
            var26 = function onPress() {
                var2 = _closure1_slot6;
                var1 = var2.DEV_clearState;
                var1 = var1.bind(var2)();
                var1 = undefined;
                return var1;
            };
            var17['onPress'] = var26;
            var28 = _closure1_slot7;
            var26 = var22[var23];
            var26 = var20.bind(var4)(var26);
            var27 = var26.RefreshIcon;
            var26 = {};
            var26 = var28.bind(var4)(var27, var26);
            var17['icon'] = var26;
            var28 = _closure1_slot7;
            var26 = var22[var19];
            var26 = var20.bind(var4)(var26);
            var27 = var26.TableRowArrow;
            var26 = {};
            var26 = var28.bind(var4)(var27, var26);
            var17['trailing'] = var26;
            var17 = var25.bind(var4)(var18, var17);
            var15[2] = var17;
            var18 = _closure1_slot7;
            var16 = var22[var16];
            var16 = var20.bind(var4)(var16);
            var17 = var16.TableRow;
            var16 = {'label': 'Reset Upsell Animation', 'subLabel': 'Clear the dismissed state for the create button NUX animation so it can replay'};
            var24 = function onPress() {
                var3 = _closure1_slot0;
                var4 = _closure1_slot1;
                var1 = 15;
                var2 = var4[var1];
                var1 = undefined;
                var6 = var3.bind(var1)(var2);
                var5 = var6.removeDismissedContent;
                var2 = 16;
                var2 = var4[var2];
                var2 = var3.bind(var1)(var2);
                var2 = var2.DismissibleContent;
                var2 = var2.MOBILE_MULTI_GUILD_CREATE_UPSELL_ANIMATION;
                var2 = var5.bind(var6)(var2);
                var2 = 17;
                var2 = var4[var2];
                var3 = var3.bind(var1)(var2);
                var2 = var3.resetDismissibleContentFrameworkStore;
                var2 = var2.bind(var3)();
                return var1;
            };
            var16['onPress'] = var24;
            var25 = _closure1_slot7;
            var23 = var22[var23];
            var23 = var20.bind(var4)(var23);
            var24 = var23.RefreshIcon;
            var23 = {};
            var23 = var25.bind(var4)(var24, var23);
            var16['icon'] = var23;
            var21 = _closure1_slot7;
            var19 = var22[var19];
            var19 = var20.bind(var4)(var19);
            var20 = var19.TableRowArrow;
            var19 = {};
            var19 = var21.bind(var4)(var20, var19);
            var16['trailing'] = var19;
            var16 = var18.bind(var4)(var17, var16);
            var15[3] = var16;
            var12['children'] = var15;
            var12 = var14.bind(var4)(var13, var12);
            var9['children'] = var12;
            var9 = var11.bind(var4)(var10, var9);
            var8[2] = var9;
            var5['children'] = var8;
            var5 = var7.bind(var4)(var6, var5);
            var1['children'] = var5;
            var1 = var3.bind(var4)(var2, var1);
            return var1;
        }
    };
    var _closure1_slot10 = var1;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var7 = var6[var1];
    var4 = metroImportAll;
    var1 = undefined;
    var4 = var4.bind(var1)(var7);
    var _closure1_slot2 = var4;
    var12 = 1;
    var4 = var6[var12];
    var4 = var5.bind(var1)(var4);
    var7 = var4.View;
    var _closure1_slot3 = var7;
    var4 = var4.ScrollView;
    var _closure1_slot4 = var4;
    var4 = 2;
    var4 = var6[var4];
    var4 = var11.bind(var1)(var4);
    var _closure1_slot5 = var4;
    var4 = 3;
    var4 = var6[var4];
    var4 = var11.bind(var1)(var4);
    var _closure1_slot6 = var4;
    var4 = 4;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var7 = var4.jsx;
    var _closure1_slot7 = var7;
    var4 = var4.jsxs;
    var _closure1_slot8 = var4;
    var4 = 5;
    var4 = var6[var4];
    var8 = var5.bind(var1)(var4);
    var7 = var8.createStyles;
    var4 = {};
    var9 = {};
    var10 = 6;
    var13 = var6[var10];
    var13 = var11.bind(var1)(var13);
    var13 = var13.colors;
    var13 = var13.BACKGROUND_BASE_LOW;
    var9['backgroundColor'] = var13;
    var9['flex'] = var12;
    var4['container'] = var9;
    var9 = {};
    var9['flex'] = var12;
    var4['scrollView'] = var9;
    var9 = {};
    var12 = var6[var10];
    var12 = var11.bind(var1)(var12);
    var12 = var12.spacing;
    var12 = var12.PX_16;
    var9['paddingHorizontal'] = var12;
    var12 = var6[var10];
    var12 = var11.bind(var1)(var12);
    var12 = var12.spacing;
    var12 = var12.PX_16;
    var9['paddingTop'] = var12;
    var10 = var6[var10];
    var10 = var11.bind(var1)(var10);
    var10 = var10.spacing;
    var10 = var10.PX_8;
    var9['paddingBottom'] = var10;
    var4['section'] = var9;
    var4 = var7.bind(var8)(var4);
    var _closure1_slot9 = var4;
    var4 = 18;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/game_community_upsell/native/GameCommunityUpsellDevTools.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function GameCommunityUpsellDevTools() {
        var4 = _closure1_slot7;
        var3 = _closure1_slot10;
        var2 = undefined;
        var1 = {};
        var1 = var4.bind(var2)(var3, var1);
        return var1;
    };
    var3['default'] = var2;
    return var1;
})();