// app/modules/replies/PendingReplyActionCreators.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var3 = exports;
    var4 = dependencyMap;
    var1 = metroImportDefault;
    var _closure1_slot0 = var1;
    var _closure1_slot1 = var4;
    var1 = global;
    var7 = var1.Object;
    var6 = var7.defineProperty;
    var5 = {};
    var1 = true;
    var5['value'] = var1;
    var1 = '__esModule';
    var1 = var6.bind(var7)(var3, var1, var5);
    var1 = 1;
    var5 = var4[var1];
    var4 = require;
    var1 = undefined;
    var6 = var4.bind(var1)(var5);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/replies/PendingReplyActionCreators.tsx';
    var4 = var5.bind(var6)(var4);
    var4 = function createPendingReply(arg1) {
        var1 = arg1;
        var9 = var1.message;
        var8 = var1.channel;
        var7 = var1.shouldMention;
        var6 = var1.showMentionToggle;
        var5 = var1.source;
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 0;
        var2 = var2[var1];
        var1 = undefined;
        var4 = var3.bind(var1)(var2);
        var3 = var4.dispatch;
        var2 = {};
        var10 = 'CREATE_PENDING_REPLY';
        var2['type'] = var10;
        var2['message'] = var9;
        var2['channel'] = var8;
        var2['shouldMention'] = var7;
        var2['showMentionToggle'] = var6;
        var2['source'] = var5;
        var2 = var3.bind(var4)(var2);
        return var1;
    };
    var3['createPendingReply'] = var4;
    var4 = function createShallowPendingReply(arg1) {
        var1 = arg1;
        var7 = var1.messageId;
        var6 = var1.channel;
        var5 = var1.shouldMention;
        var4 = var1.showMentionToggle;
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 0;
        var2 = var2[var1];
        var1 = undefined;
        var3 = var3.bind(var1)(var2);
        var2 = var3.dispatch;
        var1 = {};
        var8 = 'CREATE_SHALLOW_PENDING_REPLY';
        var1['type'] = var8;
        var1['messageId'] = var7;
        var1['channel'] = var6;
        var1['shouldMention'] = var5;
        var1['showMentionToggle'] = var4;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var3['createShallowPendingReply'] = var4;
    var4 = function setPendingReplyShouldMention(arg1, arg2) {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 0;
        var2 = var2[var1];
        var1 = undefined;
        var4 = var3.bind(var1)(var2);
        var3 = var4.dispatch;
        var2 = {};
        var5 = 'SET_PENDING_REPLY_SHOULD_MENTION';
        var2['type'] = var5;
        var5 = arg1;
        var2['channelId'] = var5;
        var5 = arg2;
        var2['shouldMention'] = var5;
        var2 = var3.bind(var4)(var2);
        return var1;
    };
    var3['setPendingReplyShouldMention'] = var4;
    var2 = function deletePendingReply(arg1) {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 0;
        var2 = var2[var1];
        var1 = undefined;
        var4 = var3.bind(var1)(var2);
        var3 = var4.dispatch;
        var2 = {};
        var5 = 'DELETE_PENDING_REPLY';
        var2['type'] = var5;
        var5 = arg1;
        var2['channelId'] = var5;
        var2 = var3.bind(var4)(var2);
        return var1;
    };
    var3['deletePendingReply'] = var2;
    return var1;
})();