// app/modules/safety_flows/native/ErrorScreen.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var11 = metroImportDefault;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var11;
    var _closure1_slot2 = var6;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var11.bind(var1)(var4);
    var _closure1_slot3 = var4;
    var4 = 1;
    var4 = var6[var4];
    var4 = var11.bind(var1)(var4);
    var _closure1_slot4 = var4;
    var4 = 2;
    var7 = var6[var4];
    var4 = metroImportAll;
    var4 = var4.bind(var1)(var7);
    var _closure1_slot5 = var4;
    var4 = 3;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.View;
    var _closure1_slot6 = var4;
    var4 = 4;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var7 = var4.jsx;
    var _closure1_slot7 = var7;
    var4 = var4.jsxs;
    var _closure1_slot8 = var4;
    var4 = 5;
    var4 = var6[var4];
    var8 = var5.bind(var1)(var4);
    var7 = var8.createStyles;
    var4 = {};
    var9 = {'flexDirection': 'column', 'justifyContent': 'center', 'gap': null, 'padding': null, 'alignItems': 'center'};
    var10 = 6;
    var12 = var6[var10];
    var12 = var11.bind(var1)(var12);
    var12 = var12.spacing;
    var12 = var12.PX_8;
    var9['gap'] = var12;
    var12 = var6[var10];
    var12 = var11.bind(var1)(var12);
    var12 = var12.spacing;
    var12 = var12.PX_16;
    var9['padding'] = var12;
    var4['container'] = var9;
    var9 = {};
    var10 = var6[var10];
    var10 = var11.bind(var1)(var10);
    var10 = var10.spacing;
    var10 = var10.PX_8;
    var9['marginTop'] = var10;
    var4['buttonContainer'] = var9;
    var4 = var7.bind(var8)(var4);
    var _closure1_slot9 = var4;
    var4 = 15;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/safety_flows/native/ErrorScreen.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function ErrorScreen() {
        var3 = _closure1_slot5;
        var2 = var3.useState;
        var1 = false;
        var3 = var2.bind(var3)(var1);
        var2 = _closure1_slot4;
        var4 = undefined;
        var1 = 2;
        var2 = var2.bind(var4)(var3, var1);
        var1 = 0;
        var12 = var2[var1];
        var1 = 1;
        var1 = var2[var1];
        var _closure2_slot0 = var1;
        var17 = _closure1_slot0;
        var18 = _closure1_slot2;
        var1 = 7;
        var1 = var18[var1];
        var2 = var17.bind(var4)(var1);
        var1 = var2.useNavigation;
        var1 = var1.bind(var2)();
        var _closure2_slot1 = var1;
        var1 = _closure1_slot9;
        var8 = var1.bind(var4)();
        var1 = function() {
            var4 = _closure1_slot3;
            var3 = undefined;
            var2 = function* () {
                var1 = function* anon_0_() {
                    _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
                        StartGenerator();
                        ResumeGenerator(result_out_reg=0, return_bool_out_reg=1);
                        if(var2) { _fun0001_ip = 2; continue _fun0001 }
case 3:
                        var5 = undefined;
                        var4 = undefined;
case 4: // try_start_0
                        var6 = _closure2_slot0;
                        var2 = true;
                        var2 = var6.bind(var5)(var2);
                        var7 = _closure1_slot0;
                        var8 = _closure1_slot2;
                        var2 = 8;
                        var2 = var8[var2];
                        var7 = var7.bind(var5)(var2);
                        var2 = var7.getCurrentTask;
                        var2 = var2.bind(var7)();
                        SaveGenerator(address=65);
case 5:
                        return var2;
case 6:
                        ResumeGenerator(result_out_reg=1, return_bool_out_reg=6);
                        if(var7) { _fun0001_ip = 7; continue _fun0001 }
case 8:
                        var4 = var2;
                        var7 = null;
                        if(!(var7 != var2)) { _fun0001_ip = 9; continue _fun0001 }
case 10:
                        var7 = _closure1_slot0;
                        var8 = _closure1_slot2;
                        var6 = 9;
                        var6 = var8[var6];
                        var8 = var7.bind(var5)(var6);
                        var7 = var8.navigateToScreenForTask;
                        var6 = _closure2_slot1;
                        var4 = var7.bind(var8)(var6, var4);
case 9: // try_end0
                        var6 = _closure2_slot0;
                        var4 = false;
                        var4 = var6.bind(var5)(var4);
                        return var5;
case 7:
                        var4 = _closure2_slot0;
                        var3 = false;
                        var3 = var4.bind(var5)(var3);
                        return var2;
case 11: // catch_target0
                        CatchBlockStart(arg_register=1);
                        var4 = _closure2_slot0;
                        var3 = false;
                        var3 = var4.bind(var5)(var3);
                        throw var2;
case 2:
                        return var1;
                    }
                };
                return var1;
            };
            var2 = var4.bind(var3)(var2);
            var _closure3_slot0 = var2;
            var1 = function() {
                var1 = undefined;
                var4 = _closure3_slot0;
                var3 = var4.apply;
                var1 = arguments;
                var2 = var1;
                var1 = this;
                var1 = var3.bind(var4)(var1, var2);
                return var1;
            };
            return var1;
        };
        var15 = var1.bind(var4)();
        var3 = _closure1_slot8;
        var2 = _closure1_slot6;
        var1 = {};
        var6 = var8.container;
        var1['style'] = var6;
        var11 = _closure1_slot7;
        var6 = 10;
        var5 = var18[var6];
        var5 = var17.bind(var4)(var5);
        var7 = var5.Text;
        var5 = {};
        var9 = 'heading-lg/semibold';
        var5['variant'] = var9;
        var14 = 11;
        var9 = var18[var14];
        var9 = var17.bind(var4)(var9);
        var16 = var9.intl;
        var10 = var16.string;
        var9 = var18[var14];
        var9 = var17.bind(var4)(var9);
        var9 = var9.t;
        var9 = var9.c6kn6O;
        var9 = var10.bind(var16)(var9);
        var5['children'] = var9;
        var7 = var11.bind(var4)(var7, var5);
        var5 = new Array(3);
        var5[0] = var7;
        var6 = var18[var6];
        var6 = var17.bind(var4)(var6);
        var7 = var6.Text;
        var6 = {'variant': 'text-md/normal', 'color': 'text-muted'};
        var9 = var18[var14];
        var9 = var17.bind(var4)(var9);
        var16 = var9.intl;
        var10 = var16.string;
        var9 = var18[var14];
        var9 = var17.bind(var4)(var9);
        var9 = var9.t;
        var9 = var9.ZUEGFh;
        var9 = var10.bind(var16)(var9);
        var6['children'] = var9;
        var6 = var11.bind(var4)(var7, var6);
        var5[1] = var6;
        var6 = 12;
        var6 = var18[var6];
        var6 = var17.bind(var4)(var6);
        var7 = var6.Stack;
        var6 = {};
        var8 = var8.buttonContainer;
        var6['style'] = var8;
        var8 = 8;
        var6['spacing'] = var8;
        var9 = 13;
        var8 = var18[var9];
        var8 = var17.bind(var4)(var8);
        var10 = var8.Button;
        var8 = {};
        var13 = function onPress() {
            var3 = _closure1_slot1;
            var2 = _closure1_slot2;
            var1 = 14;
            var2 = var2[var1];
            var1 = undefined;
            var3 = var3.bind(var1)(var2);
            var2 = var3.logout;
            var1 = 'safety_flows_error_screen';
            var1 = var2.bind(var3)(var1);
            return var1;
        };
        var8['onPress'] = var13;
        var13 = var18[var14];
        var13 = var17.bind(var4)(var13);
        var19 = var13.intl;
        var16 = var19.string;
        var13 = var18[var14];
        var13 = var17.bind(var4)(var13);
        var13 = var13.t;
        var13 = var13.2jxGen;
        var13 = var16.bind(var19)(var13);
        var8['text'] = var13;
        var13 = 'secondary';
        var8['variant'] = var13;
        var13 = 'md';
        var8['size'] = var13;
        var10 = var11.bind(var4)(var10, var8);
        var8 = new Array(2);
        var8[0] = var10;
        var9 = var18[var9];
        var9 = var17.bind(var4)(var9);
        var10 = var9.Button;
        var9 = {};
        var9['onPress'] = var15;
        var15 = var18[var14];
        var15 = var17.bind(var4)(var15);
        var16 = var15.intl;
        var15 = var16.string;
        var14 = var18[var14];
        var14 = var17.bind(var4)(var14);
        var14 = var14.t;
        var14 = var14.7NqTJi;
        var14 = var15.bind(var16)(var14);
        var9['text'] = var14;
        var14 = 'primary';
        var9['variant'] = var14;
        var9['size'] = var13;
        var9['loading'] = var12;
        var9 = var11.bind(var4)(var10, var9);
        var8[1] = var9;
        var6['children'] = var8;
        var6 = var3.bind(var4)(var7, var6);
        var5[2] = var6;
        var1['children'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var3['default'] = var2;
    return var1;
})();