// app/modules/guild_instant_invites/native/InstantInvite.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var6 = require;
    var3 = exports;
    var7 = dependencyMap;
    var _closure1_slot0 = var6;
    var1 = metroImportDefault;
    var _closure1_slot1 = var1;
    var _closure1_slot2 = var7;
    var1 = global;
    var8 = var1.Object;
    var5 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var5.bind(var8)(var3, var1, var4);
    var1 = 0;
    var5 = var7[var1];
    var4 = metroImportAll;
    var1 = undefined;
    var8 = var4.bind(var1)(var5);
    var _closure1_slot3 = var8;
    var11 = 1;
    var4 = var7[var11];
    var4 = var6.bind(var1)(var4);
    var4 = var4.View;
    var _closure1_slot4 = var4;
    var4 = 2;
    var4 = var7[var4];
    var4 = var6.bind(var1)(var4);
    var4 = var4.Routes;
    var _closure1_slot5 = var4;
    var4 = 3;
    var4 = var7[var4];
    var4 = var6.bind(var1)(var4);
    var5 = var4.jsx;
    var _closure1_slot6 = var5;
    var4 = var4.jsxs;
    var _closure1_slot7 = var4;
    var4 = 4;
    var4 = var7[var4];
    var9 = var6.bind(var1)(var4);
    var5 = var9.createStyles;
    var4 = {};
    var10 = {'marginLeft': 4294967280, 'marginBottom': 4294967280, 'marginTop': 8, 'flex': 1};
    var4['creatorWrapper'] = var10;
    var10 = {'flex': 1, 'flexDirection': 'row', 'alignItems': 'center', 'gap': 8};
    var4['gameWrapper'] = var10;
    var10 = {};
    var10['flex'] = var11;
    var4['gameText'] = var10;
    var4 = var5.bind(var9)(var4);
    var _closure1_slot8 = var4;
    var5 = var8.memo;
    var4 = function(arg1) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var1 = arg1;
            var21 = var1.invite;
            var _closure2_slot0 = var21;
            var7 = var1.onInviteRevoked;
            var1 = _closure1_slot8;
            var4 = undefined;
            var15 = var1.bind(var4)();
            var14 = var21.uses;
            var13 = var21.maxUses;
            var2 = var21.guild;
            var20 = null;
            var3 = var20 == var2;
            var1 = undefined;
            if(var3) { _fun0001_ip = 2; continue _fun0001 }
case 3:
            var1 = var2.id;
case 2:
            var3 = _closure1_slot0;
            var5 = _closure1_slot2;
            var2 = 21;
            var2 = var5[var2];
            var8 = var3.bind(var4)(var2);
            var6 = var8.useInviteRoleAssignment;
            var2 = 'InstantInvite';
            var2 = var6.bind(var8)(var1, var2);
            var6 = var2.enabled;
            var2 = 22;
            var2 = var5[var2];
            var5 = var3.bind(var4)(var2);
            var3 = var5.useInviteActions;
            var2 = {};
            var2['invite'] = var21;
            var2['onInviteRevoked'] = var7;
            var24 = var3.bind(var5)(var2);
            var7 = _closure1_slot3;
            var5 = var7.useMemo;
            var2 = var21.roles;
            var3 = new Array(1);
            var3[0] = var2;
            var2 = function() {
                var1 = _closure2_slot0;
                var3 = var1.roles;
                var2 = var3.map;
                var1 = function(arg1) {
                    var1 = arg1;
                    var1 = var1.id;
                    return var1;
                };
                var1 = var2.bind(var3)(var1);
                return var1;
            };
            var12 = var5.bind(var7)(var2, var3);
            var19 = var1;
            if(!var6) { _fun0001_ip = 4; continue _fun0001 }
case 5:
            var2 = var12.length;
            var1 = 0;
            var6 = var2 > var1;
case 4:
            if(!var6) { _fun0001_ip = 6; continue _fun0001 }
case 7:
            var6 = var20 != var19;
case 6:
            var3 = _closure1_slot7;
            var8 = _closure1_slot0;
            var16 = _closure1_slot2;
            var1 = 13;
            var1 = var16[var1];
            var1 = var8.bind(var4)(var1);
            var2 = var1.Card;
            var1 = {};
            var9 = 14;
            var5 = var16[var9];
            var5 = var8.bind(var4)(var5);
            var7 = var5.Stack;
            var5 = {'direction': 'horizontal', 'justify': 'space-between'};
            var11 = _closure1_slot6;
            var17 = 16;
            var17 = var16[var17];
            var17 = var8.bind(var4)(var17);
            var18 = var17.Text;
            var17 = {'variant': 'text-lg/bold', 'tabularNumbers': true};
            var22 = var21.code;
            var17['children'] = var22;
            var18 = var11.bind(var4)(var18, var17);
            var17 = new Array(2);
            var17[0] = var18;
            var18 = 17;
            var18 = var16[var18];
            var18 = var8.bind(var4)(var18);
            var22 = var18.ContextMenu;
            var18 = {};
            var18['items'] = var24;
            var23 = function children(arg1) {
                var3 = arg1;
                var6 = var3.ref;
                var1 = null;
                var2 = Object.create(var1);
                var1 = 0;
                var2['ref'] = var1;
                var14 = {};
                var13 = var3;
                var12 = var2;
                var13 = copyDataProperties(var14, var13, var12);
                var4 = _closure1_slot6;
                var10 = _closure1_slot0;
                var11 = _closure1_slot2;
                var1 = 18;
                var1 = var11[var1];
                var3 = undefined;
                var1 = var10.bind(var3)(var1);
                var2 = var1.IconButton;
                var1 = {'size': 'sm', 'variant': 'secondary'};
                var8 = _closure1_slot1;
                var7 = 12;
                var7 = var11[var7];
                var7 = var8.bind(var3)(var7);
                var7 = var7.more;
                var1['icon'] = var7;
                var7 = 9;
                var8 = var11[var7];
                var8 = var10.bind(var3)(var8);
                var9 = var8.intl;
                var8 = var9.string;
                var7 = var11[var7];
                var7 = var10.bind(var3)(var7);
                var7 = var7.t;
                var7 = var7.DEoVWZ;
                var7 = var8.bind(var9)(var7);
                var1['accessibilityLabel'] = var7;
                var1['ref'] = var6;
                var14 = var1;
                var5 = copyDataProperties(var14, var13);
                var1 = var4.bind(var3)(var2, var1);
                return var1;
            };
            var18['children'] = var23;
            var18 = var11.bind(var4)(var22, var18);
            var17[1] = var18;
            var5['children'] = var17;
            var7 = var3.bind(var4)(var7, var5);
            var5 = new Array(4);
            var5[0] = var7;
            var7 = 19;
            var7 = var16[var7];
            var7 = var8.bind(var4)(var7);
            var8 = var7.InstantInviteDetails;
            var7 = {};
            var16 = var21.channel;
            var7['channel'] = var16;
            var16 = var21.getExpiresAt;
            var16 = var16.bind(var21)();
            var7['expiresAt'] = var16;
            var7 = var11.bind(var4)(var8, var7);
            var5[1] = var7;
            if(!var6) { _fun0001_ip = 8; continue _fun0001 }
case 9:
            var11 = _closure1_slot6;
            var8 = _closure1_slot1;
            var16 = _closure1_slot2;
            var7 = 23;
            var7 = var16[var7];
            var8 = var8.bind(var4)(var7);
            var7 = {};
            var7['roleIds'] = var12;
            var7['guildId'] = var19;
            var6 = var11.bind(var4)(var8, var7);
case 8:
            var5[2] = var6;
            var8 = _closure1_slot7;
            var7 = _closure1_slot0;
            var6 = _closure1_slot2;
            var6 = var6[var9];
            var6 = var7.bind(var4)(var6);
            var7 = var6.Stack;
            var6 = {'direction': 'horizontal', 'align': 'flex-end'};
            var12 = _closure1_slot6;
            var11 = _closure1_slot4;
            var9 = {};
            var15 = var15.creatorWrapper;
            var9['style'] = var15;
            var16 = var21.inviter;
            var17 = var20 == var16;
            var15 = undefined;
            if(var17) { _fun0001_ip = 10; continue _fun0001 }
case 11:
            var15 = var16.id;
case 10:
            var16 = var20 != var15;
            var15 = null;
            if(!var16) { _fun0001_ip = 12; continue _fun0001 }
case 13:
            var18 = _closure1_slot6;
            var17 = _closure1_slot1;
            var22 = _closure1_slot2;
            var16 = 20;
            var16 = var22[var16];
            var17 = var17.bind(var4)(var16);
            var16 = {'start': true, 'end': true};
            var21 = var21.inviter;
            var22 = var20 == var21;
            var20 = undefined;
            if(var22) { _fun0001_ip = 14; continue _fun0001 }
case 15:
            var20 = var21.id;
case 14:
            var16['userId'] = var20;
            var16['guildId'] = var19;
            var15 = var18.bind(var4)(var17, var16);
case 12:
            var9['children'] = var15;
            var11 = var12.bind(var4)(var11, var9);
            var9 = new Array(2);
            var9[0] = var11;
            var12 = _closure1_slot6;
            var11 = _closure1_slot1;
            var15 = _closure1_slot2;
            var10 = 24;
            var10 = var15[var10];
            var11 = var11.bind(var4)(var10);
            var10 = {};
            var10['uses'] = var14;
            var10['maxUses'] = var13;
            var10 = var12.bind(var4)(var11, var10);
            var9[1] = var10;
            var6['children'] = var9;
            var6 = var8.bind(var4)(var7, var6);
            var5[3] = var6;
            var1['children'] = var5;
            var1 = var3.bind(var4)(var2, var1);
            return var1;
        }
    };
    var4 = var5.bind(var8)(var4);
    var5 = 25;
    var5 = var7[var5];
    var7 = var6.bind(var1)(var5);
    var6 = var7.fileFinishedImporting;
    var5 = 'modules/guild_instant_invites/native/InstantInvite.tsx';
    var5 = var6.bind(var7)(var5);
    var3['default'] = var4;
    var2 = function LinkedChannelInvite(arg1) {
        _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
case 0:
            var1 = arg1;
            var15 = var1.channel;
            var _closure2_slot0 = var15;
            var4 = undefined;
            var _closure2_slot1 = var4;
            var _closure2_slot2 = var4;
            var _closure2_slot3 = var4;
            var1 = _closure1_slot8;
            var13 = var1.bind(var4)();
            var1 = var15.linkedLobby;
            var11 = null;
            var2 = var11 == var1;
            var16 = undefined;
            if(var2) { _fun0002_ip = 3; continue _fun0002 }
case 16:
            var16 = var1.linked_by;
case 3:
            var2 = _closure1_slot0;
            var3 = _closure1_slot2;
            var1 = 5;
            var1 = var3[var1];
            var3 = var2.bind(var4)(var1);
            var2 = var3.useGetOrFetchApplication;
            var5 = var15.linkedLobby;
            var6 = var11 == var5;
            var1 = undefined;
            if(var6) { _fun0002_ip = 17; continue _fun0002 }
case 18:
            var1 = var5.application_id;
case 17:
            var22 = var2.bind(var3)(var1);
            var2 = _closure1_slot0;
            var3 = _closure1_slot2;
            var1 = 6;
            var1 = var3[var1];
            var2 = var2.bind(var4)(var1);
            var1 = var2.useCanUnlinkLobbyChannel;
            var6 = var1.bind(var2)(var15);
            _closure2_slot1 = var6;
            var2 = _closure1_slot1;
            var1 = 7;
            var1 = var3[var1];
            var3 = var2.bind(var4)(var1);
            var2 = var15.id;
            var1 = var11 == var22;
            var5 = undefined;
            if(var1) { _fun0002_ip = 19; continue _fun0002 }
case 20:
            var5 = var22.name;
case 19:
            var7 = var11 != var5;
            var1 = '';
            if(!var7) { _fun0002_ip = 4; continue _fun0002 }
case 21:
            var1 = var5;
case 4:
            var1 = var3.bind(var4)(var2, var1);
            _closure2_slot2 = var1;
            var5 = _closure1_slot3;
            var3 = var5.useCallback;
            var2 = new Array(2);
            var2[0] = var6;
            var2[1] = var1;
            var1 = function() {
                _fun0003: for(var _fun0003_ip = 0; ; ) switch(_fun0003_ip) {
case 0:
                    var2 = _closure2_slot1;
                    if(var2) { _fun0003_ip = 22; continue _fun0003 }
case 23:
                    var3 = _closure1_slot1;
                    var10 = _closure1_slot2;
                    var2 = 8;
                    var2 = var10[var2];
                    var9 = undefined;
                    var4 = var3.bind(var9)(var2);
                    var3 = var4.show;
                    var2 = {};
                    var8 = _closure1_slot0;
                    var5 = 9;
                    var6 = var10[var5];
                    var6 = var8.bind(var9)(var6);
                    var11 = var6.intl;
                    var7 = var11.string;
                    var6 = var10[var5];
                    var6 = var8.bind(var9)(var6);
                    var6 = var6.t;
                    var6 = var6.JmUENg;
                    var6 = var7.bind(var11)(var6);
                    var2['title'] = var6;
                    var6 = var10[var5];
                    var6 = var8.bind(var9)(var6);
                    var7 = var6.intl;
                    var6 = var7.string;
                    var5 = var10[var5];
                    var5 = var8.bind(var9)(var5);
                    var5 = var5.t;
                    var5 = var5.SrvsML;
                    var5 = var6.bind(var7)(var5);
                    var2['body'] = var5;
                    var2 = var3.bind(var4)(var2);
                    _fun0003_ip = 24; continue _fun0003;
case 22:
                    var2 = _closure2_slot2;
                    var1 = undefined;
                    var1 = var2.bind(var1)();
case 24:
                    var1 = undefined;
                    return var1;
                }
            };
            var1 = var3.bind(var5)(var1, var2);
            _closure2_slot3 = var1;
            var3 = var5.useMemo;
            var6 = var15.guild_id;
            var2 = new Array(3);
            var2[0] = var6;
            var6 = var15.id;
            var2[1] = var6;
            var2[2] = var1;
            var1 = function() {
                var2 = {};
                var9 = _closure1_slot0;
                var6 = _closure1_slot2;
                var4 = 9;
                var1 = var6[var4];
                var5 = undefined;
                var1 = var9.bind(var5)(var1);
                var8 = var1.intl;
                var7 = var8.string;
                var1 = var6[var4];
                var1 = var9.bind(var5)(var1);
                var1 = var1.t;
                var1 = var1.aW2YlJ;
                var1 = var7.bind(var8)(var1);
                var2['label'] = var1;
                var1 = 10;
                var1 = var6[var1];
                var1 = var9.bind(var5)(var1);
                var1 = var1.ArrowSmallRightIcon;
                var2['IconComponent'] = var1;
                var1 = function action() {
                    var4 = _closure1_slot0;
                    var3 = _closure1_slot2;
                    var1 = 11;
                    var3 = var3[var1];
                    var1 = undefined;
                    var4 = var4.bind(var1)(var3);
                    var3 = var4.transitionTo;
                    var7 = _closure1_slot5;
                    var6 = var7.CHANNEL;
                    var2 = _closure2_slot0;
                    var5 = var2.guild_id;
                    var2 = var2.id;
                    var2 = var6.bind(var7)(var5, var2);
                    var2 = var3.bind(var4)(var2);
                    return var1;
                };
                var2['action'] = var1;
                var1 = new Array(2);
                var1[0] = var2;
                var2 = {};
                var7 = var6[var4];
                var7 = var9.bind(var5)(var7);
                var8 = var7.intl;
                var7 = var8.string;
                var4 = var6[var4];
                var4 = var9.bind(var5)(var4);
                var4 = var4.t;
                var4 = var4.JmUENg;
                var4 = var7.bind(var8)(var4);
                var2['label'] = var4;
                var4 = _closure1_slot1;
                var3 = 12;
                var3 = var6[var3];
                var3 = var4.bind(var5)(var3);
                var3 = var3.revoke;
                var2['iconSource'] = var3;
                var3 = 'destructive';
                var2['variant'] = var3;
                var3 = _closure2_slot3;
                var2['action'] = var3;
                var1[1] = var2;
                return var1;
            };
            var20 = var3.bind(var5)(var1, var2);
            var3 = _closure1_slot7;
            var17 = _closure1_slot0;
            var21 = _closure1_slot2;
            var1 = 13;
            var1 = var21[var1];
            var1 = var17.bind(var4)(var1);
            var2 = var1.Card;
            var1 = {};
            var9 = 14;
            var5 = var21[var9];
            var5 = var17.bind(var4)(var5);
            var10 = var5.Stack;
            var5 = {'direction': 'horizontal', 'justify': 'space-between'};
            var7 = _closure1_slot4;
            var6 = {};
            var8 = var13.gameWrapper;
            var6['style'] = var8;
            var18 = _closure1_slot6;
            var14 = _closure1_slot1;
            var23 = 15;
            var8 = var21[var23];
            var14 = var14.bind(var4)(var8);
            var8 = {};
            var8['game'] = var22;
            var23 = var21[var23];
            var23 = var17.bind(var4)(var23);
            var23 = var23.GameIconSizes;
            var23 = var23.SIZE_24;
            var8['size'] = var23;
            var14 = var18.bind(var4)(var14, var8);
            var8 = new Array(2);
            var8[0] = var14;
            var14 = 16;
            var14 = var21[var14];
            var14 = var17.bind(var4)(var14);
            var17 = var14.Text;
            var14 = {'ellipsizeMode': 'tail', 'lineClamp': 1, 'variant': 'text-lg/bold'};
            var21 = var13.gameText;
            var14['style'] = var21;
            var23 = var11 == var22;
            var21 = undefined;
            if(var23) { _fun0002_ip = 25; continue _fun0002 }
case 26:
            var21 = var22.name;
case 25:
            var14['children'] = var21;
            var14 = var18.bind(var4)(var17, var14);
            var8[1] = var14;
            var6['children'] = var8;
            var6 = var3.bind(var4)(var7, var6);
            var14 = new Array(2);
            var14[0] = var6;
            var8 = _closure1_slot6;
            var7 = _closure1_slot0;
            var6 = _closure1_slot2;
            var17 = 17;
            var17 = var6[var17];
            var17 = var7.bind(var4)(var17);
            var18 = var17.ContextMenu;
            var17 = {};
            var17['items'] = var20;
            var19 = function children(arg1) {
                var3 = arg1;
                var6 = var3.ref;
                var1 = null;
                var2 = Object.create(var1);
                var1 = 0;
                var2['ref'] = var1;
                var14 = {};
                var13 = var3;
                var12 = var2;
                var13 = copyDataProperties(var14, var13, var12);
                var4 = _closure1_slot6;
                var10 = _closure1_slot0;
                var11 = _closure1_slot2;
                var1 = 18;
                var1 = var11[var1];
                var3 = undefined;
                var1 = var10.bind(var3)(var1);
                var2 = var1.IconButton;
                var1 = {'size': 'sm', 'variant': 'secondary'};
                var8 = _closure1_slot1;
                var7 = 12;
                var7 = var11[var7];
                var7 = var8.bind(var3)(var7);
                var7 = var7.more;
                var1['icon'] = var7;
                var7 = 9;
                var8 = var11[var7];
                var8 = var10.bind(var3)(var8);
                var9 = var8.intl;
                var8 = var9.string;
                var7 = var11[var7];
                var7 = var10.bind(var3)(var7);
                var7 = var7.t;
                var7 = var7.DEoVWZ;
                var7 = var8.bind(var9)(var7);
                var1['accessibilityLabel'] = var7;
                var1['ref'] = var6;
                var14 = var1;
                var5 = copyDataProperties(var14, var13);
                var1 = var4.bind(var3)(var2, var1);
                return var1;
            };
            var17['children'] = var19;
            var17 = var8.bind(var4)(var18, var17);
            var14[1] = var17;
            var5['children'] = var14;
            var10 = var3.bind(var4)(var10, var5);
            var5 = new Array(3);
            var5[0] = var10;
            var10 = 19;
            var10 = var6[var10];
            var10 = var7.bind(var4)(var10);
            var14 = var10.InstantInviteDetails;
            var10 = {};
            var10['channel'] = var15;
            var10 = var8.bind(var4)(var14, var10);
            var5[1] = var10;
            var6 = var6[var9];
            var6 = var7.bind(var4)(var6);
            var7 = var6.Stack;
            var6 = {'direction': 'horizontal', 'align': 'flex-end'};
            var10 = _closure1_slot4;
            var9 = {};
            var13 = var13.creatorWrapper;
            var9['style'] = var13;
            var13 = var11 != var16;
            var11 = null;
            if(!var13) { _fun0002_ip = 27; continue _fun0002 }
case 28:
            var14 = _closure1_slot6;
            var13 = _closure1_slot1;
            var17 = _closure1_slot2;
            var12 = 20;
            var12 = var17[var12];
            var13 = var13.bind(var4)(var12);
            var12 = {'start': true, 'end': true};
            var12['userId'] = var16;
            var15 = var15.guild_id;
            var12['guildId'] = var15;
            var11 = var14.bind(var4)(var13, var12);
case 27:
            var9['children'] = var11;
            var9 = var8.bind(var4)(var10, var9);
            var6['children'] = var9;
            var6 = var8.bind(var4)(var7, var6);
            var5[2] = var6;
            var1['children'] = var5;
            var1 = var3.bind(var4)(var2, var1);
            return var1;
        }
    };
    var3['LinkedChannelInvite'] = var2;
    return var1;
})();