// app/design/components/Modal/native/Modal.native.tsx
export default (function(argFoo, argBar, argBaz, argCorge, _, argFred, argPlugh) {
    report = argBar;
    zulu = argFred;
    oscar = argPlugh;
    var _closure1_slot0 = report;
    entity = argBaz;
    var _closure1_slot1 = entity;
    var _closure1_slot2 = oscar;
    entity = global;
    options = entity.Object;
    golf = options.defineProperty;
    tango = {};
    entity = true;
    tango['value'] = entity;
    entity = '__esModule';
    entity = golf.bind(options)(zulu, entity, tango);
    entity = 0;
    golf = oscar[entity];
    tango = argCorge;
    entity = undefined;
    tango = tango.bind(entity)(golf);
    tango = 1;
    tango = oscar[tango];
    tango = report.bind(entity)(tango);
    tango = tango.jsx;
    var _closure1_slot3 = tango;
    tango = 5;
    tango = oscar[tango];
    oscar = report.bind(entity)(tango);
    report = oscar.fileFinishedImporting;
    tango = 'design/components/Modal/native/Modal.native.tsx';
    tango = report.bind(oscar)(tango);
    mike = function(argFoo) { // Original name: Modal
        zulu = _closure1_slot1;
        verify = _closure1_slot2;
        mike = 2;
        mike = verify[mike];
        tango = undefined;
        mike = zulu.bind(tango)(mike);
        report = mike.bind(tango)();
        zulu = _closure1_slot3;
        options = _closure1_slot0;
        entity = 3;
        entity = verify[entity];
        entity = options.bind(tango)(entity);
        mike = entity.Navigator;
        entity = {};
        offset = argFoo;
        yankee = entity;
        oscar = copyDataProperties(yankee, offset);
        oscar = {};
        golf = 4;
        golf = verify[golf];
        golf = options.bind(tango)(golf);
        golf = golf.NAV_BAR_HEIGHT;
        report = report.top;
        report = golf + report;
        oscar['height'] = report;
        report = 'headerStyle';
        entity[report] = oscar;
        entity = zulu.bind(tango)(mike, entity);
        return entity;
    };
    zulu['Modal'] = mike;
    return entity;
})();