// app/modules/user_settings/native/defs/ExplicitMediaFiltersNonFriendsDMsSetting.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var7 = require;
    var3 = exports;
    var8 = dependencyMap;
    var _closure1_slot0 = var7;
    var _closure1_slot1 = var8;
    var4 = function useObscuredContentNonFriendsDmSettingValue() {
        var3 = _closure1_slot0;
        var5 = _closure1_slot1;
        var1 = 3;
        var1 = var5[var1];
        var2 = undefined;
        var4 = var3.bind(var2)(var1);
        var1 = var4.useExplicitContentSettingOrDefault;
        var1 = var1.bind(var4)();
        var4 = var1.explicitContentNonFriendDm;
        var1 = 4;
        var1 = var5[var1];
        var3 = var3.bind(var2)(var1);
        var1 = var3.redactionSettingToRenderedString;
        var1 = var1.bind(var3)(var4);
        var1 = var1.bind(var2)();
        return var1;
    };
    var2 = function onObscuredContentNonFriendsDmOnPress() {
        var3 = _closure1_slot0;
        var4 = _closure1_slot1;
        var1 = 5;
        var2 = var4[var1];
        var1 = undefined;
        var5 = var3.bind(var1)(var2);
        var2 = var5.getExplicitContentSettingOrDefault;
        var2 = var2.bind(var5)();
        var5 = var2.explicitContentNonFriendDm;
        var2 = 6;
        var7 = var4[var2];
        var7 = var3.bind(var1)(var7);
        var8 = var7.intl;
        var7 = var8.string;
        var2 = var4[var2];
        var2 = var3.bind(var1)(var2);
        var2 = var2.t;
        var2 = var2.GYpoAq;
        var7 = var7.bind(var8)(var2);
        var2 = 7;
        var2 = var4[var2];
        var4 = var3.bind(var1)(var2);
        var3 = var4.handleSensitiveMediaFilterPress;
        var2 = {};
        var2['title'] = var7;
        var6 = _closure1_slot3;
        var6 = var6.bind(var1)();
        var2['subtitle'] = var6;
        var6 = function handlePress(arg1) {
            var3 = _closure1_slot0;
            var2 = _closure1_slot1;
            var1 = 5;
            var2 = var2[var1];
            var1 = undefined;
            var3 = var3.bind(var1)(var2);
            var2 = var3.updateExplicitContentSetting;
            var1 = {};
            var4 = arg1;
            var1['explicitContentNonFriendDm'] = var4;
            var1 = var2.bind(var3)(var1);
            return var1;
        };
        var2['handlePress'] = var6;
        var2['currentValue'] = var5;
        var2 = var3.bind(var4)(var2);
        return var1;
    };
    var11 = function getTitle() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 6;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.Yh+HX1;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var _closure1_slot3 = var11;
    var1 = global;
    var9 = var1.Object;
    var6 = var9.defineProperty;
    var5 = {};
    var1 = true;
    var5['value'] = var1;
    var1 = '__esModule';
    var1 = var6.bind(var9)(var3, var1, var5);
    var1 = 0;
    var5 = var8[var1];
    var1 = undefined;
    var5 = var7.bind(var1)(var5);
    var5 = var5.MobileSetting;
    var _closure1_slot2 = var5;
    var5 = 8;
    var5 = var8[var5];
    var9 = var7.bind(var1)(var5);
    var6 = var9.createPressable;
    var5 = {};
    var5['title'] = var11;
    var11 = function parent() {
        var1 = _closure1_slot2;
        var1 = var1.SENSITIVE_CONTENT_FILTERS;
        return var1;
    };
    var5['parent'] = var11;
    var5['useTrailing'] = var4;
    var5['onPress'] = var2;
    var11 = function getSearchTerms() {
        var6 = _closure1_slot0;
        var7 = _closure1_slot1;
        var2 = 6;
        var1 = var7[var2];
        var5 = undefined;
        var1 = var6.bind(var5)(var1);
        var4 = var1.intl;
        var3 = var4.string;
        var1 = var7[var2];
        var1 = var6.bind(var5)(var1);
        var1 = var1.t;
        var1 = var1.N/oRI+;
        var3 = var3.bind(var4)(var1);
        var1 = new Array(3);
        var1[0] = var3;
        var3 = var7[var2];
        var3 = var6.bind(var5)(var3);
        var8 = var3.intl;
        var4 = var8.string;
        var3 = var7[var2];
        var3 = var6.bind(var5)(var3);
        var3 = var3.t;
        var3 = var3.QVdYsK;
        var3 = var4.bind(var8)(var3);
        var1[1] = var3;
        var3 = var7[var2];
        var3 = var6.bind(var5)(var3);
        var4 = var3.intl;
        var3 = var4.string;
        var2 = var7[var2];
        var2 = var6.bind(var5)(var2);
        var2 = var2.t;
        var2 = var2.5mnTa7;
        var2 = var3.bind(var4)(var2);
        var1[2] = var2;
        return var1;
    };
    var5['additionalSearchTerms'] = var11;
    var10 = function useIsDisabled() {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var4 = _closure1_slot0;
            var5 = _closure1_slot1;
            var1 = 1;
            var1 = var5[var1];
            var3 = undefined;
            var2 = var4.bind(var3)(var1);
            var1 = var2.useIsParentallyControlled;
            var1 = var1.bind(var2)();
            var2 = 2;
            var2 = var5[var2];
            var4 = var4.bind(var3)(var2);
            var3 = var4.useIsGidgetPawtectEnabled;
            var2 = 'explicit_media_filters_non_friends_dms_native';
            var2 = var3.bind(var4)(var2);
            if(var1) { _fun0001_ip = 2; continue _fun0001 }
case 3:
            var1 = var2;
case 2:
            return var1;
        }
    };
    var5['useIsDisabled'] = var10;
    var5 = var6.bind(var9)(var5);
    var6 = 9;
    var6 = var8[var6];
    var8 = var7.bind(var1)(var6);
    var7 = var8.fileFinishedImporting;
    var6 = 'modules/user_settings/native/defs/ExplicitMediaFiltersNonFriendsDMsSetting.tsx';
    var6 = var7.bind(var8)(var6);
    var3['default'] = var5;
    var3['useObscuredContentNonFriendsDmSettingValue'] = var4;
    var3['onObscuredContentNonFriendsDmOnPress'] = var2;
    return var1;
})();