// app/modules/avatar_decorations/AvatarDecorationConstants.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var1 = global;
    var7 = var1.Object;
    var4 = var7.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var4.bind(var7)(var3, var1, var2);
    var1 = 0;
    var2 = var6[var1];
    var1 = undefined;
    var2 = var5.bind(var1)(var2);
    var4 = var2.AvatarSizes;
    var2 = {};
    var8 = var4.SIZE_56;
    var7 = 4;
    var2[var8] = var7;
    var8 = var4.SIZE_80;
    var7 = 6;
    var2[var8] = var7;
    var7 = var4.SIZE_120;
    var4 = 8;
    var2[var7] = var4;
    var4 = 1;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/avatar_decorations/AvatarDecorationConstants.tsx';
    var4 = var5.bind(var6)(var4);
    var4 = 1.2;
    var3['DECORATION_TO_AVATAR_RATIO'] = var4;
    var3['AvatarDecorationBorderSizes'] = var2;
    var2 = 70;
    var3['AVATAR_DECORATION_SIZE'] = var2;
    var2 = 50;
    var3['MOBILE_SETTINGS_AVATAR_DECORATION_SIZE'] = var2;
    return var1;
})();