// app/modules/premium/powerups/native/hooks/useGuildPowerupOnShowDeactivate.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var6;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var7 = var6[var1];
    var4 = metroImportAll;
    var1 = undefined;
    var8 = var4.bind(var1)(var7);
    var _closure1_slot2 = var8;
    var4 = 1;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.jsx;
    var _closure1_slot3 = var4;
    var7 = var8.lazy;
    var4 = function() {
        var3 = _closure1_slot0;
        var1 = _closure1_slot1;
        var2 = 3;
        var2 = var1[var2];
        var4 = undefined;
        var3 = var3.bind(var4)(var2);
        var2 = 2;
        var2 = var1[var2];
        var1 = var1.paths;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var4 = var7.bind(var8)(var4);
    var _closure1_slot4 = var4;
    var4 = 5;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/premium/powerups/native/hooks/useGuildPowerupOnShowDeactivate.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function useGuildPowerupOnShowDeactivate(arg1, arg2) {
        var6 = arg1;
        var5 = arg2;
        var8 = _closure1_slot3;
        var7 = _closure1_slot4;
        var4 = {};
        var4['guildId'] = var6;
        var4['powerup'] = var5;
        var3 = undefined;
        var3 = var8.bind(var3)(var7, var4);
        var _closure2_slot0 = var3;
        var4 = _closure1_slot2;
        var3 = var4.useCallback;
        var2 = new Array(2);
        var2[0] = var6;
        var2[1] = var5;
        var1 = function() {
            var3 = _closure1_slot0;
            var2 = _closure1_slot1;
            var1 = 4;
            var2 = var2[var1];
            var1 = undefined;
            var5 = var3.bind(var1)(var2);
            var4 = var5.openAlert;
            var3 = _closure2_slot0;
            var2 = 'guild-powerups-deactivate-alert';
            var2 = var4.bind(var5)(var2, var3);
            return var1;
        };
        var1 = var3.bind(var4)(var1, var2);
        return var1;
    };
    var3['default'] = var2;
    return var1;
})();