// app/modules/user_settings/defs/native/FriendRequestsMutualFriendsSetting.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var4 = metroImportAll;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var4;
    var _closure1_slot2 = var6;
    var1 = global;
    var9 = var1.Object;
    var7 = var9.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var9)(var3, var1, var2);
    var1 = 0;
    var2 = var6[var1];
    var1 = undefined;
    var2 = var4.bind(var1)(var2);
    var _closure1_slot3 = var2;
    var2 = 1;
    var2 = var6[var2];
    var2 = var5.bind(var1)(var2);
    var9 = var2.MobileSetting;
    var2 = 2;
    var2 = var6[var2];
    var2 = var5.bind(var1)(var2);
    var2 = var2.FriendSourceFlags;
    var _closure1_slot4 = var2;
    var2 = 7;
    var2 = var6[var2];
    var7 = var5.bind(var1)(var2);
    var4 = var7.createToggle;
    var2 = {};
    var10 = function useTitle() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot2;
        var1 = 8;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.IqlCSq;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var2['useTitle'] = var10;
    var9 = var9.CONTENT_AND_SOCIAL_DISCORD;
    var2['parent'] = var9;
    var9 = function useFriendRequestsMutualFriendsSettingValue() {
        var5 = _closure1_slot0;
        var4 = _closure1_slot2;
        var3 = 4;
        var4 = var4[var3];
        var3 = undefined;
        var3 = var5.bind(var3)(var4);
        var4 = var3.FriendSourceFlagsSetting;
        var3 = var4.useSetting;
        var5 = var3.bind(var4)();
        var _closure2_slot0 = var5;
        var4 = _closure1_slot3;
        var3 = var4.useMemo;
        var2 = new Array(1);
        var2[0] = var5;
        var1 = function() {
            var3 = _closure1_slot0;
            var2 = _closure1_slot2;
            var1 = 5;
            var2 = var2[var1];
            var1 = undefined;
            var3 = var3.bind(var1)(var2);
            var2 = var3.computeFlags;
            var1 = _closure2_slot0;
            var1 = var2.bind(var3)(var1);
            return var1;
        };
        var1 = var3.bind(var4)(var1, var2);
        var1 = var1.mutualFriends;
        return var1;
    };
    var2['useValue'] = var9;
    var9 = function onFriendRequestsMutualFriendsSettingValueChange(arg1) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var3 = _closure1_slot0;
            var4 = _closure1_slot2;
            var2 = 4;
            var6 = var4[var2];
            var1 = undefined;
            var6 = var3.bind(var1)(var6);
            var7 = var6.FriendSourceFlagsSetting;
            var6 = var7.getSetting;
            var8 = var6.bind(var7)();
            var2 = var4[var2];
            var2 = var3.bind(var1)(var2);
            var4 = var2.FriendSourceFlagsSetting;
            var3 = var4.updateSetting;
            var6 = _closure1_slot1;
            var7 = _closure1_slot2;
            var2 = 6;
            var2 = var7[var2];
            var7 = var6.bind(var1)(var2);
            var2 = arg1;
            if(var2) { _fun0001_ip = 2; continue _fun0001 }
case 3:
            var9 = var7.removeFlags;
            var2 = _closure1_slot4;
            var6 = var2.MUTUAL_FRIENDS;
            var2 = var2.NO_RELATION;
            var2 = var9.bind(var7)(var8, var6, var2);
            _fun0001_ip = 4; continue _fun0001;
case 2:
            var6 = var7.addFlag;
            var5 = _closure1_slot4;
            var5 = var5.MUTUAL_FRIENDS;
            var2 = var6.bind(var7)(var8, var5);
case 4:
            var2 = var3.bind(var4)(var2);
            return var1;
        }
    };
    var2['onValueChange'] = var9;
    var8 = function useIsDisabled() {
        var3 = _closure1_slot0;
        var2 = _closure1_slot2;
        var1 = 3;
        var2 = var2[var1];
        var1 = undefined;
        var2 = var3.bind(var1)(var2);
        var1 = var2.useIsParentallyControlled;
        var1 = var1.bind(var2)();
        return var1;
    };
    var2['useIsDisabled'] = var8;
    var2 = var4.bind(var7)(var2);
    var4 = 9;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/user_settings/defs/native/FriendRequestsMutualFriendsSetting.tsx';
    var4 = var5.bind(var6)(var4);
    var3['default'] = var2;
    return var1;
})();