// app/modules/user_settings/defs/native/ShowDevToolsSetting.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var6;
    var1 = global;
    var7 = var1.Object;
    var4 = var7.defineProperty;
    var2 = {};
    var8 = true;
    var2['value'] = var8;
    var1 = '__esModule';
    var1 = var4.bind(var7)(var3, var1, var2);
    var1 = 1;
    var2 = var6[var1];
    var1 = undefined;
    var7 = var5.bind(var1)(var2);
    var4 = var7.createPressable;
    var2 = {};
    var10 = function useTitle() {
        var1 = 'Show Dev Tools';
        return var1;
    };
    var2['useTitle'] = var10;
    var10 = null;
    var2['parent'] = var10;
    var10 = 2;
    var10 = var6[var10];
    var10 = var5.bind(var1)(var10);
    var10 = var10.StaffBadgeIcon;
    var2['IconComponent'] = var10;
    var10 = 3;
    var10 = var6[var10];
    var10 = var5.bind(var1)(var10);
    var10 = var10.navigateToDevTools;
    var2['onPress'] = var10;
    var10 = 4;
    var10 = var6[var10];
    var10 = var5.bind(var1)(var10);
    var10 = var10.useStaffOrDeveloperSettingPredicate;
    var2['usePredicate'] = var10;
    var9 = function getAdditionalSearchTerms() {
        var4 = global;
        var5 = var4.Object;
        var3 = var5.values;
        var7 = _closure1_slot0;
        var8 = _closure1_slot1;
        var1 = 0;
        var2 = var8[var1];
        var6 = undefined;
        var2 = var7.bind(var6)(var2);
        var2 = var2.DevToolsScreens;
        var10 = var3.bind(var5)(var2);
        var3 = new Array(0);
        var11 = var3;
        var9 = 0;
        var9 = arraySpread(var11, var10, var9);
        var5 = var4.Object;
        var4 = var5.values;
        var1 = var8[var1];
        var1 = var7.bind(var6)(var1);
        var1 = var1.PerformanceTestingScreens;
        var10 = var4.bind(var5)(var1);
        var11 = var3;
        var1 = arraySpread(var11, var10, var9);
        var2 = var3.map;
        var1 = function(arg1) {
            var1 = arg1;
            var1 = var1.headerTitle;
            return var1;
        };
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var2['useSearchTerms'] = var9;
    var2['withArrow'] = var8;
    var2 = var4.bind(var7)(var2);
    var4 = 5;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/user_settings/defs/native/ShowDevToolsSetting.tsx';
    var4 = var5.bind(var6)(var4);
    var3['default'] = var2;
    return var1;
})();