// app/modules/people/native/ClearAllIncomingRequestsConfirmationModal.tsx
export default (function(argFoo, argBar, argBaz, _, __, argFred, argPlugh) {
    report = argBar;
    zulu = argFred;
    tango = argPlugh;
    var _closure1_slot0 = report;
    entity = argBaz;
    var _closure1_slot1 = entity;
    var _closure1_slot2 = tango;
    entity = global;
    options = entity.Object;
    golf = options.defineProperty;
    oscar = {};
    entity = true;
    oscar['value'] = entity;
    entity = '__esModule';
    entity = golf.bind(options)(zulu, entity, oscar);
    entity = 3;
    tango = tango[entity];
    entity = undefined;
    oscar = report.bind(entity)(tango);
    report = oscar.fileFinishedImporting;
    tango = 'modules/people/native/ClearAllIncomingRequestsConfirmationModal.tsx';
    tango = report.bind(oscar)(tango);
    mike = function(argFoo) { // Original name: openClearAllIncomingRequestsConfirmationModal
        report = _closure1_slot1;
        mike = _closure1_slot2;
        entity = 0;
        tango = mike[entity];
        entity = undefined;
        report = report.bind(entity)(tango);
        tango = report.pushLazy;
        oscar = _closure1_slot0;
        zulu = 2;
        zulu = mike[zulu];
        oscar = oscar.bind(entity)(zulu);
        zulu = 1;
        zulu = mike[zulu];
        mike = mike.paths;
        zulu = oscar.bind(entity)(zulu, mike);
        mike = {};
        oscar = argFoo;
        mike['incomingPendingRequestCount'] = oscar;
        mike = tango.bind(report)(zulu, mike);
        return entity;
    };
    zulu['default'] = mike;
    return entity;
})();