// app/modules/multi_account/native/ManageAccountsConstants.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var1 = global;
    var7 = var1.Object;
    var4 = var7.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var4.bind(var7)(var3, var1, var2);
    var1 = 0;
    var2 = var6[var1];
    var1 = undefined;
    var2 = var5.bind(var1)(var2);
    var4 = var2.AuthStates;
    var2 = {};
    var7 = 'MANAGE_ACCOUNTS';
    var2['MANAGE_ACCOUNTS'] = var7;
    var8 = var4.LOGIN;
    var2['LOGIN'] = var8;
    var7 = 'LOGIN';
    var2[var8] = var7;
    var8 = var4.ACCOUNT_DISABLED_OR_DELETION_SCHEDULED;
    var2['ACCOUNT_DISABLED_OR_DELETION_SCHEDULED'] = var8;
    var7 = 'ACCOUNT_DISABLED_OR_DELETION_SCHEDULED';
    var2[var8] = var7;
    var7 = var4.MFA;
    var2['MFA'] = var7;
    var4 = 'MFA';
    var2[var7] = var4;
    var4 = 1;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/multi_account/native/ManageAccountsConstants.tsx';
    var4 = var5.bind(var6)(var4);
    var3['ManageAccountsScreens'] = var2;
    return var1;
})();