// app/modules/remixing/RemixingTextStore.tsx
export default (function(argFoo, argBar, _, __, ___, argFre, argPlu) {
    report = argBar;
    zuuluu = argFre;
    oscard = argPlu;
    var _closure1_slot0 = report;
    var _closure1_slot1 = oscard;
    entity = global;
    option = entity.Object;
    golfie = option.defineProperty;
    tangon = {};
    entity = true;
    tangon['value'] = entity;
    entity = '__esModule';
    entity = golfie.bind(option)(zuuluu, entity, tangon);
    golfie = {'text': '', 'textWidth': 0, 'textBackgroundColor': 'transparent', 'fontSize': 30, 'shouldSaveText': true};
    tangon = 0;
    entity = {'x': 0, 'y': 0};
    golfie['addTextPosition'] = entity;
    entity = undefined;
    golfie['textTransform'] = entity;
    var _closure1_slot2 = golfie;
    tangon = oscard[tangon];
    golfie = report.bind(entity)(tangon);
    tangon = golfie.create;
    michal = function(argFoo) {
        entity = argFoo;
        var _closure2_slot0 = entity;
        entity = {};
        report = _closure1_slot2;
        oscard = entity;
        zuuluu = copyDataProperties(oscard, report);
        tangon = function(argFoo) { // Original name: setText
            michal = argFoo;
            var _closure3_slot0 = michal;
            tangon = _closure1_slot0;
            zuuluu = _closure1_slot1;
            michal = 1;
            zuuluu = zuuluu[michal];
            michal = undefined;
            zuuluu = tangon.bind(michal)(zuuluu);
            michal = zuuluu.batchUpdates;
            entity = function() {
                zuuluu = _closure2_slot0;
                michal = {};
                entity = _closure3_slot0;
                michal['text'] = entity;
                entity = undefined;
                entity = zuuluu.bind(entity)(michal);
                return entity;
            };
            entity = michal.bind(zuuluu)(entity);
            return entity;
        };
        zuuluu = 'setText';
        entity[zuuluu] = tangon;
        tangon = function(argFoo) { // Original name: setTextWidth
            michal = argFoo;
            var _closure3_slot0 = michal;
            tangon = _closure1_slot0;
            zuuluu = _closure1_slot1;
            michal = 1;
            zuuluu = zuuluu[michal];
            michal = undefined;
            zuuluu = tangon.bind(michal)(zuuluu);
            michal = zuuluu.batchUpdates;
            entity = function() {
                zuuluu = _closure2_slot0;
                michal = {};
                entity = _closure3_slot0;
                michal['textWidth'] = entity;
                entity = undefined;
                entity = zuuluu.bind(entity)(michal);
                return entity;
            };
            entity = michal.bind(zuuluu)(entity);
            return entity;
        };
        zuuluu = 'setTextWidth';
        entity[zuuluu] = tangon;
        tangon = function(argFoo) { // Original name: setTextBackgroundColor
            michal = argFoo;
            var _closure3_slot0 = michal;
            tangon = _closure1_slot0;
            zuuluu = _closure1_slot1;
            michal = 1;
            zuuluu = zuuluu[michal];
            michal = undefined;
            zuuluu = tangon.bind(michal)(zuuluu);
            michal = zuuluu.batchUpdates;
            entity = function() {
                zuuluu = _closure2_slot0;
                michal = {};
                entity = _closure3_slot0;
                michal['textBackgroundColor'] = entity;
                entity = undefined;
                entity = zuuluu.bind(entity)(michal);
                return entity;
            };
            entity = michal.bind(zuuluu)(entity);
            return entity;
        };
        zuuluu = 'setTextBackgroundColor';
        entity[zuuluu] = tangon;
        tangon = function(argFoo) { // Original name: setFontSize
            michal = argFoo;
            var _closure3_slot0 = michal;
            tangon = _closure1_slot0;
            zuuluu = _closure1_slot1;
            michal = 1;
            zuuluu = zuuluu[michal];
            michal = undefined;
            zuuluu = tangon.bind(michal)(zuuluu);
            michal = zuuluu.batchUpdates;
            entity = function() {
                zuuluu = _closure2_slot0;
                michal = {};
                entity = _closure3_slot0;
                michal['fontSize'] = entity;
                entity = undefined;
                entity = zuuluu.bind(entity)(michal);
                return entity;
            };
            entity = michal.bind(zuuluu)(entity);
            return entity;
        };
        zuuluu = 'setFontSize';
        entity[zuuluu] = tangon;
        tangon = function(argFoo) { // Original name: setShouldSaveText
            michal = argFoo;
            var _closure3_slot0 = michal;
            tangon = _closure1_slot0;
            zuuluu = _closure1_slot1;
            michal = 1;
            zuuluu = zuuluu[michal];
            michal = undefined;
            zuuluu = tangon.bind(michal)(zuuluu);
            michal = zuuluu.batchUpdates;
            entity = function() {
                zuuluu = _closure2_slot0;
                michal = {};
                entity = _closure3_slot0;
                michal['shouldSaveText'] = entity;
                entity = undefined;
                entity = zuuluu.bind(entity)(michal);
                return entity;
            };
            entity = michal.bind(zuuluu)(entity);
            return entity;
        };
        zuuluu = 'setShouldSaveText';
        entity[zuuluu] = tangon;
        tangon = function(argFoo) { // Original name: setAddTextPosition
            michal = argFoo;
            var _closure3_slot0 = michal;
            tangon = _closure1_slot0;
            zuuluu = _closure1_slot1;
            michal = 1;
            zuuluu = zuuluu[michal];
            michal = undefined;
            zuuluu = tangon.bind(michal)(zuuluu);
            michal = zuuluu.batchUpdates;
            entity = function() {
                zuuluu = _closure2_slot0;
                michal = {};
                entity = _closure3_slot0;
                michal['addTextPosition'] = entity;
                entity = undefined;
                entity = zuuluu.bind(entity)(michal);
                return entity;
            };
            entity = michal.bind(zuuluu)(entity);
            return entity;
        };
        zuuluu = 'setAddTextPosition';
        entity[zuuluu] = tangon;
        tangon = function(argFoo) { // Original name: setTextTransform
            michal = argFoo;
            var _closure3_slot0 = michal;
            tangon = _closure1_slot0;
            zuuluu = _closure1_slot1;
            michal = 1;
            zuuluu = zuuluu[michal];
            michal = undefined;
            zuuluu = tangon.bind(michal)(zuuluu);
            michal = zuuluu.batchUpdates;
            entity = function() {
                zuuluu = _closure2_slot0;
                michal = {};
                entity = _closure3_slot0;
                michal['textTransform'] = entity;
                entity = undefined;
                entity = zuuluu.bind(entity)(michal);
                return entity;
            };
            entity = michal.bind(zuuluu)(entity);
            return entity;
        };
        zuuluu = 'setTextTransform';
        entity[zuuluu] = tangon;
        zuuluu = function() { // Original name: reset
            zuuluu = _closure1_slot0;
            michal = _closure1_slot1;
            entity = 1;
            michal = michal[entity];
            entity = undefined;
            tangon = zuuluu.bind(entity)(michal);
            zuuluu = tangon.batchUpdates;
            michal = function() {
                zuuluu = _closure2_slot0;
                michal = _closure1_slot2;
                entity = undefined;
                entity = zuuluu.bind(entity)(michal);
                return entity;
            };
            michal = zuuluu.bind(tangon)(michal);
            return entity;
        };
        michal = 'reset';
        entity[michal] = zuuluu;
        return entity;
    };
    michal = tangon.bind(golfie)(michal);
    tangon = 2;
    tangon = oscard[tangon];
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/remixing/RemixingTextStore.tsx';
    tangon = report.bind(oscard)(tangon);
    zuuluu['useRemixingTextStore'] = michal;
    return entity;
})();