// app/modules/app_startup/ManagerRegistry.native.tsx
export default (function(_, argBar, __, ___, ____, argFre, argPlu) {
    report = argBar;
    zuuluu = argFre;
    oscard = argPlu;
    var _closure1_slot0 = report;
    var _closure1_slot1 = oscard;
    entity = global;
    verify = entity.Object;
    option = verify.defineProperty;
    michal = {};
    tangon = true;
    michal['value'] = tangon;
    entity = '__esModule';
    entity = option.bind(verify)(zuuluu, entity, michal);
    michal = {};
    entity = {};
    option = ['DISPLAYED_INVITE_SHOW', 'DISPLAYED_INVITE_CLEAR', 'DEFERRED_INVITE_SHOW', 'REGISTER_SUCCESS'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 0;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['AcceptInviteManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN', 'CHANNEL_SELECT', 'AGE_GATE_MODAL_OPEN', 'AGE_GATE_MODAL_CLOSE', 'GUILD_UPDATE'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 1;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['AgeGateManager'] = entity;
    entity = {};
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 2;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['hasStoreChangeListeners'] = tangon;
    michal['AppAnalyticsManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 3;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['ATTManager'] = entity;
    entity = {};
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 4;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['hasStoreChangeListeners'] = tangon;
    michal['AudioSessionModeManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN', 'AUDIO_SET_LOCAL_VOLUME', 'AUDIO_TOGGLE_LOCAL_MUTE', 'AUDIO_TOGGLE_LOCAL_SOUNDBOARD_MUTE'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 5;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['AudioSettingsManager'] = entity;
    entity = {};
    option = ['MESSAGE_CREATE', 'POST_CONNECTION_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 6;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['BackgroundSyncManager'] = entity;
    entity = {};
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 7;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['loadAfterConnectionOpen'] = tangon;
    michal['BlockedDomainManager'] = entity;
    entity = {};
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 8;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['loadAfterConnectionOpen'] = tangon;
    michal['BugReportManager'] = entity;
    entity = {};
    option = ['VOICE_STATE_UPDATES', 'EMBEDDED_ACTIVITY_CLOSE', 'CONNECTION_CLOSED'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 9;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['CallIdleManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN', 'CONNECTION_CLOSED', 'APP_STATE_UPDATE', 'WINDOW_FOCUS'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 10;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['CacheManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 11;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['ChangelogManager'] = entity;
    entity = {};
    option = ['GUILD_LOCAL_RING_START', 'GUILD_RING_STOP'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 12;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['hasStoreChangeListeners'] = tangon;
    michal['ChannelCallManager'] = entity;
    entity = {};
    option = ['GUILD_CREATE', 'POST_CONNECTION_OPEN', 'CHANNEL_SYNC'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 13;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['ChannelResyncManager'] = entity;
    entity = {};
    option = ['CHANNEL_SELECT', 'CHANNEL_UPDATES'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 14;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['ChannelSafetyWarningsManager'] = entity;
    entity = {};
    option = ['VOICE_CHANNEL_SELECT', 'CALL_CREATE', 'USER_SETTINGS_MODAL_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 15;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['CommonTriggerPointManager'] = entity;
    entity = {};
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 16;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['loadAfterConnectionOpen'] = tangon;
    michal['CommunicationDisabledManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 17;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['ContactSyncLifecycleManager'] = entity;
    entity = {};
    option = ['USER_SETTINGS_PROTO_UPDATE', 'POST_CONNECTION_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 18;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['loadAfterConnectionOpen'] = tangon;
    michal['CustomStatusManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN', 'IDLE'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 19;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['loadAfterConnectionOpen'] = tangon;
    michal['DeadchatPromptManager'] = entity;
    entity = {};
    option = ['DM_SETTINGS_UPSELL_SHOW'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 20;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['DmSettingsUpsellManager'] = entity;
    entity = {};
    option = ['EMOJI_INTERACTION_INITIATED'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 21;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['TopEmojisDataManager'] = entity;
    entity = {};
    option = ['GUILD_CREATE', 'DELETED_ENTITY_IDS'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 22;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['loadRightBeforeConnectionOpen'] = tangon;
    michal['EntityVersionsManager'] = entity;
    entity = {};
    option = ['CHANNEL_SELECT', 'LOAD_MESSAGES_SUCCESS', 'MESSAGE_CREATE', 'MESSAGE_UPDATE', 'SEARCH_FINISH', 'MOD_VIEW_SEARCH_FINISH', 'LOAD_FORUM_POSTS', 'LOAD_ARCHIVED_THREADS_SUCCESS', 'LOAD_THREADS_SUCCESS', 'LOGOUT', 'LOAD_PINNED_MESSAGES_SUCCESS', 'USER_SETTINGS_PROTO_UPDATE', 'CHANNEL_RTC_UPDATE_CHAT_OPEN', 'SIDEBAR_VIEW_CHANNEL'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 23;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['ExplicitMediaManager'] = entity;
    entity = {};
    option = ['APP_STATE_UPDATE', 'LOGOUT', 'POST_CONNECTION_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 24;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['KvBackgroundManager'] = entity;
    entity = {};
    option = ['VOICE_CHANNEL_SHOW_FEEDBACK', 'STREAM_CLOSE', 'EMBEDDED_ACTIVITY_CLOSE', 'IN_APP_REPORTS_SHOW_FEEDBACK', 'BLOCK_USER_SHOW_FEEDBACK'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 25;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['FeedbackManager'] = entity;
    entity = {};
    option = ['CHANNEL_PRELOAD'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 26;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['ForumManager'] = entity;
    entity = {};
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 27;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['loadAfterConnectionOpen'] = tangon;
    michal['ForumGuidelinesManager'] = entity;
    entity = {};
    option = ['CHANNEL_SELECT', 'THREAD_CREATE'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 28;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['ForumPostAnalyticsManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN', 'CONNECTION_RESUMED', 'CONNECTION_CLOSED', 'APP_STATE_UPDATE'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 29;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['FrecencyUserSettingsManager'] = entity;
    entity = {};
    option = ['WAIT_FOR_REMOTE_SESSION', 'POST_CONNECTION_OPEN', 'SESSIONS_REPLACE', 'AUDIO_TOGGLE_SELF_DEAF', 'AUDIO_TOGGLE_SELF_MUTE', 'VOICE_STATE_UPDATES', 'CONSOLE_COMMAND_UPDATE', 'PASSIVE_UPDATE_V2', 'REMOTE_SESSION_DISCONNECT'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 30;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['GameConsoleManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN', 'CHANNEL_SELECT', 'MESSAGE_CREATE', 'THREAD_CREATE', 'GUILD_MEMBER_UPDATE', 'GUILD_DELETE'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 31;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['GuildOnboardingHomeManager'] = entity;
    entity = {};
    option = ['CHANNEL_SELECT', 'GUILD_DELETE', 'POST_CONNECTION_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 32;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['GuildOnboardingManager'] = entity;
    entity = {};
    option = ['GUILD_POWERUP_ENTITLEMENTS_CREATE', 'GUILD_POWERUP_ENTITLEMENTS_DELETE', 'GUILD_APPLIED_BOOSTS_UPDATE'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 33;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    entity['hasStoreChangeListeners'] = tangon;
    michal['GuildPowerupsManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN', 'GUILD_DELETE', 'GUILD_UNAVAILABLE', 'INVITE_RESOLVE_SUCCESS', 'CHANNEL_SELECT'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 34;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['GuildScheduledEventManager'] = entity;
    entity = {};
    option = ['INVITE_ACCEPT_SUCCESS'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 35;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['GuildVerificationManager'] = entity;
    entity = {};
    option = ['GUILD_JOIN_REQUEST_UPDATE', 'CHANNEL_SELECT', 'POST_CONNECTION_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 36;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['MemberVerificationApplicationManager'] = entity;
    entity = {};
    option = ['MESSAGE_UPDATE', 'MESSAGE_CREATE'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 37;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['MessageSessionMetadataManager'] = entity;
    entity = {};
    option = ['NOTIFICATIONS_SET_DISABLED_SOUNDS'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 38;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['hasStoreChangeListeners'] = tangon;
    michal['HolidayEventsManager'] = entity;
    entity = {};
    option = ['APP_STATE_UPDATE', 'POST_CONNECTION_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 39;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['IAPManager'] = entity;
    entity = {};
    option = ['INTERACTION_MODAL_CREATE', 'INTERACTION_IFRAME_MODAL_CREATE', 'INTERACTION_IFRAME_MODAL_CLOSE', 'RPC_APP_DISCONNECTED'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 40;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['InteractionModalManager'] = entity;
    entity = {};
    option = ['APP_STATE_UPDATE'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 41;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['DiskUsageManager'] = entity;
    entity = {};
    option = ['NATIVE_APP_INSTANT_INVITE_GDM_SHARE_FAILED'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 42;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['InstantInviteManager'] = entity;
    entity = {};
    option = ['APP_STATE_UPDATE', 'CONNECTION_OPEN_SUPPLEMENTAL'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 43;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['JankStatsManager'] = entity;
    entity = {};
    option = ['APP_STATE_UPDATE', 'CONNECTION_OPEN_SUPPLEMENTAL'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 44;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['JSWatchdogManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 45;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['LoginRequiredActionManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN', 'MESSAGE_UPDATE', 'LOAD_MESSAGES_SUCCESS', 'LOAD_MESSAGES_AROUND_SUCCESS', 'LOAD_RECENT_MENTIONS_SUCCESS', 'LOAD_PINNED_MESSAGES_SUCCESS', 'SEARCH_FINISH', 'MOD_VIEW_SEARCH_FINISH'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 46;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['MessageCodedLinkManager'] = entity;
    entity = {'actions': null, 'inlineRequire': null, 'neverLoadBeforeConnectionOpen': false, 'hasStoreChangeListeners': true, 'loadRightBeforeConnectionOpen': true};
    option = ['APP_STATE_UPDATE', 'OVERLAY_INITIALIZE', 'CHANNEL_SELECT', 'VOICE_CHANNEL_SELECT', 'THREAD_CREATE', 'THREAD_LIST_SYNC', 'CHANNEL_CREATE', 'CHANNEL_PRELOAD', 'GUILD_CREATE', 'MESSAGE_END_EDIT', 'LOAD_MESSAGES_SUCCESS', 'UPLOAD_FAIL', 'CHANNEL_DELETE', 'THREAD_DELETE', 'CHANNEL_RTC_JUMP_TO_VOICE_CHANNEL_MESSAGE'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 47;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    option = false;
    michal['MessageManager'] = entity;
    entity = {};
    verify = ['CONNECTION_OPEN_SUPPLEMENTAL', 'CONNECTION_RESUMED', 'GUILD_CREATE', 'GUILD_DELETE', 'LOAD_MESSAGES_SUCCESS', 'LOCAL_MESSAGES_LOADED', 'LOGOUT', 'MESSAGE_CREATE', 'MESSAGE_DELETE', 'MESSAGE_UPDATE', 'THREAD_LIST_SYNC'];
    entity['actions'] = verify;
    verify = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 48;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = verify;
    entity['neverLoadBeforeConnectionOpen'] = option;
    michal['MessagePreviewManager'] = entity;
    entity = {};
    verify = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 49;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = verify;
    entity['loadAfterConnectionOpen'] = tangon;
    michal['MetricKitManager'] = entity;
    entity = {};
    verify = ['LOGOUT'];
    entity['actions'] = verify;
    verify = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 50;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = verify;
    entity['loadAfterConnectionOpen'] = tangon;
    michal['MultiAccountManager'] = entity;
    entity = {};
    verify = ['START_HANGOUT', 'END_HANGOUT', 'APP_STATE_UPDATE', 'VOICE_STATE_UPDATES', 'SPEAKING', 'MESSAGE_CREATE', 'LOAD_USER_AFFINITIES_SUCCESS'];
    entity['actions'] = verify;
    verify = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 51;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = verify;
    entity['neverLoadBeforeConnectionOpen'] = option;
    michal['NativeHangoutsManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 52;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['NativeOnDemandResourceManager'] = entity;
    entity = {};
    option = ['ONBOARDING_STEP'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 53;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['NewUserManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN', 'ONBOARDING_START'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 54;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['RedesignNewUserManager'] = entity;
    entity = {};
    option = ['MESSAGE_CREATE', 'INVITE_ACCEPT_SUCCESS', 'RELATIONSHIP_ADD', 'POST_CONNECTION_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 55;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['NotificationPermissionManager'] = entity;
    entity = {};
    option = ['LOGOUT'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 56;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['loadAfterConnectionOpen'] = tangon;
    michal['NUFChannelsManager'] = entity;
    entity = {};
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 57;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['hasStoreChangeListeners'] = tangon;
    michal['ParticipantFocusManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 58;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['PomeloManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN', 'EXPERIMENTS_FETCH_SUCCESS'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 59;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['PromotionsManager'] = entity;
    entity = {};
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 60;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['hasStoreChangeListeners'] = tangon;
    michal['ProximitySensorManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN', 'CURRENT_USER_UPDATE', 'LOGOUT'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 61;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['PushNotificationCacheManager'] = entity;
    entity = {};
    option = ['RELATIONSHIP_ADD', 'FRIEND_REQUEST_ACCEPTED'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 62;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['RelationshipManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 63;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['RTCLatencyTestManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 64;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['SavedMessagesManager'] = entity;
    entity = {};
    option = ['SAVED_MESSAGES_UPDATE', 'SAVED_MESSAGE_CREATE', 'SAVED_MESSAGE_DELETE'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 65;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['MessageRemindersNotificationManager'] = entity;
    entity = {};
    option = ['USER_SETTINGS_PROTO_UPDATE', 'POST_CONNECTION_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 66;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['SearchManager'] = entity;
    entity = {};
    option = ['GUILD_CREATE', 'CHANNEL_CREATE', 'LOGOUT'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 67;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['SelectedChannelManager'] = entity;
    entity = {};
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 68;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['hasStoreChangeListeners'] = tangon;
    michal['SelfPresenceStoreManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 69;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['SettingTreeManagerLifecycleManager'] = entity;
    entity = {};
    option = ['CHANNEL_SELECT', 'APP_STATE_UPDATE'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 70;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['SharedSpacesWarningManager'] = entity;
    entity = {};
    option = ['VOICE_CHANNEL_SELECT', 'VOICE_STATE_UPDATES'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 71;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['StageBoostUpsellManager'] = entity;
    entity = {};
    option = ['VOICE_STATE_UPDATES'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 72;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['StageChannelRequestToSpeakMessageManager'] = entity;
    entity = {};
    option = ['VOICE_CHANNEL_SELECT', 'LOGOUT', 'STAGE_MUSIC_MUTE', 'STAGE_MUSIC_PLAY', 'VOICE_STATE_UPDATES', 'AUDIO_SET_OUTPUT_VOLUME', 'AUDIO_TOGGLE_SELF_DEAF'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 73;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['StageMusicManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 74;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['SubscriptionManager'] = entity;
    entity = {};
    option = ['CHANNEL_DELETE', 'MESSAGE_CREATE', 'GUILD_DELETE'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 75;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['ThreadManager'] = entity;
    entity = {};
    option = ['GUILD_CREATE', 'POST_CONNECTION_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 76;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['UnreadSettingsManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN', 'MESSAGE_CREATE', 'CHANNEL_SELECT'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 77;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['UrgentSystemDMManagerBase'] = entity;
    entity = {};
    option = ['CATEGORY_COLLAPSE', 'CATEGORY_EXPAND', 'CATEGORY_COLLAPSE_ALL', 'CATEGORY_EXPAND_ALL', 'POST_CONNECTION_OPEN', 'USER_GUILD_SETTINGS_FULL_UPDATE'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 78;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['UserGuildSettingsManager'] = entity;
    entity = {};
    option = ['LOGOUT', 'POST_CONNECTION_OPEN', 'CONNECTION_OPEN_SUPPLEMENTAL', 'OVERLAY_INITIALIZE', 'CURRENT_USER_UPDATE', 'GUILD_CREATE', 'GUILD_MEMBERS_CHUNK_BATCH', 'GUILD_MEMBER_ADD', 'GUILD_MEMBER_UPDATE', 'RELATIONSHIP_ADD', 'RELATIONSHIP_UPDATE', 'RELATIONSHIP_REMOVE', 'CHANNEL_CREATE', 'CHANNEL_UPDATES', 'CHANNEL_RECIPIENT_ADD', 'PASSIVE_UPDATE_V2'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 79;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['UserSearchManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN', 'OVERLAY_INITIALIZE', 'USER_SETTINGS_PROTO_UPDATE'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 80;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['UserSettingsManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN', 'BILLING_USER_TRIAL_OFFER_FETCH_SUCCESS'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 81;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['UserTrialOfferManager'] = entity;
    entity = {};
    option = ['VOICE_CHANNEL_SELECT'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 82;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['VideoBackgroundManager'] = entity;
    entity = {};
    option = ['VOICE_CHANNEL_SELECT'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 83;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['VoiceChannelNotificationsManager'] = entity;
    entity = {};
    option = ['CHANNEL_UPDATES', 'VOICE_STATE_UPDATES'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 84;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['VoiceChannelSettingsManager'] = entity;
    entity = {};
    option = ['VOICE_CHANNEL_SELECT', 'VOICE_STATE_UPDATES'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 85;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['VoicePermissionManager'] = entity;
    entity = {};
    option = ['MEDIA_ENGINE_NOISE_CANCELLATION_ERROR', 'MEDIA_ENGINE_VOICE_ACTIVITY_DETECTION_ERROR'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 86;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['VoiceProcessingErrorManager'] = entity;
    entity = {};
    option = ['CONNECTION_OPEN_SUPPLEMENTAL', 'GUILD_SETTINGS_CLOSE', 'USER_SETTINGS_MODAL_CLOSE', 'NOTIFICATION_SETTINGS_MODAL_CLOSE', 'PREMIUM_PAYMENT_MODAL_CLOSE', 'EMAIL_VERIFICATION_MODAL_CLOSE', 'IFE_EXPERIMENT_SEARCH_MODAL_CLOSE', 'CREATE_INVITE_MODAL_CLOSE', 'QUICKSWITCHER_HIDE', 'EMAIL_VERIFICATION_MODAL_OPEN', 'USER_REQUIRED_ACTION_UPDATE', 'GUILD_SETTINGS_OPEN', 'NOTIFICATION_SETTINGS_MODAL_OPEN', 'CREATE_INVITE_MODAL_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 87;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['DeprecatedModalManager'] = entity;
    entity = {};
    option = ['VOICE_CHANNEL_SELECT', 'RTC_CONNECTION_STATE'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 88;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['VoicePanelManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN', 'MESSAGE_UPDATE', 'LOAD_MESSAGES_SUCCESS', 'LOAD_MESSAGES_AROUND_SUCCESS', 'LOAD_RECENT_MENTIONS_SUCCESS', 'LOAD_PINNED_MESSAGES_SUCCESS', 'SEARCH_FINISH', 'MOD_VIEW_SEARCH_FINISH', 'LOAD_THREADS_SUCCESS', 'LOAD_ARCHIVED_THREADS_SUCCESS', 'LOAD_FORUM_POSTS'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 89;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['MediaPostEmbedManager'] = entity;
    entity = {};
    option = ['RTC_CONNECTION_FLAGS', 'RTC_CONNECTION_STATE', 'POST_CONNECTION_OPEN', 'RTC_CONNECTION_USERS_MERGED', 'CLIPS_ALLOW_VOICE_RECORDING_UPDATE', 'CLIPS_SETTINGS_UPDATE', 'CLIPS_INIT_FAILURE', 'STREAM_START', 'RUNNING_GAMES_CHANGE', 'RUNNING_GAME_TOGGLE_DETECTION', 'CLIPS_RESTART', 'RTC_CONNECTION_VIDEO', 'MEDIA_ENGINE_SET_HARDWARE_ENCODING'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 90;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['ClipsManager'] = entity;
    entity = {};
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 91;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['SearchFetchManager'] = entity;
    entity = {'inlineRequire': null, 'hasStoreChangeListeners': true, 'neverLoadBeforeConnectionOpen': true};
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 92;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['CustomRendererExperimentManager'] = entity;
    entity = {};
    option = ['CHANNEL_CREATE'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 93;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['MidjourneyOnboardingManager'] = entity;
    entity = {};
    option = ['MESSAGE_ACK', 'CHANNEL_SELECT', 'POST_CONNECTION_OPEN', 'EXPERIMENT_OVERRIDE_BUCKET', 'EXPERIMENTS_FETCH_SUCCESS'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 94;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['NativeNotificationsManager'] = entity;
    entity = {};
    option = ['VIBING_WUMPUS_PLAY_MUSIC', 'VIBING_WUMPUS_STOP_MUSIC', 'VIBING_WUMPUS_PAUSE_MUSIC'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 95;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['InappropriateConversationsManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN', 'CONNECTION_CLOSED', 'IDLE', 'WINDOW_FOCUS', 'CONTENT_INVENTORY_TOGGLE_FEED_HIDDEN', 'CONTENT_INVENTORY_MANUAL_REFRESH', 'CONTENT_INVENTORY_INBOX_STALE', 'SPOTIFY_NEW_TRACK', 'GAME_PROFILE_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 96;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['ContentInventoryManager'] = entity;
    entity = {};
    option = ['QUESTS_FETCH_CURRENT_QUESTS_BEGIN', 'POST_CONNECTION_OPEN', 'RUNNING_GAMES_CHANGE', 'USER_SETTINGS_PROTO_UPDATE', 'LOGOUT'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 97;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['QuestFetchManager'] = entity;
    entity = {};
    option = ['QUESTS_VISIBLE_MOBILE_MESSAGES_CHANGED'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 98;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['hasStoreChangeListeners'] = tangon;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['QuestMobileEmbedVisibilityManager'] = entity;
    entity = {};
    option = ['MESSAGE_CREATE', 'MESSAGE_SEND_FAILED'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 99;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['MessageSendFailureNotificationManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 100;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['NativeExperimentBridgeManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN', 'USER_SETTINGS_PROTO_UPDATE'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 101;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['UserSettingsNativeBridgeManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN', 'MESSAGE_UPDATE', 'LOAD_MESSAGES_SUCCESS', 'LOAD_MESSAGES_AROUND_SUCCESS', 'LOAD_RECENT_MENTIONS_SUCCESS', 'LOAD_PINNED_MESSAGES_SUCCESS', 'SEARCH_FINISH', 'MOD_VIEW_SEARCH_FINISH'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 102;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['ForwardGuildBreadcrumbManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN', 'LOGIN_SUCCESS', 'LOGIN_RESET', 'LOGOUT'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 103;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    entity['hasStoreChangeListeners'] = tangon;
    michal['PasskeyUpsellManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 104;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    michal['GlobalDiscoveryServersFeaturedSearchManager'] = entity;
    entity = {};
    option = ['POST_CONNECTION_OPEN', 'MESSAGE_UPDATE', 'LOAD_MESSAGES_SUCCESS', 'LOAD_MESSAGES_AROUND_SUCCESS', 'LOAD_RECENT_MENTIONS_SUCCESS', 'LOAD_PINNED_MESSAGES_SUCCESS', 'SEARCH_FINISH', 'MOD_VIEW_SEARCH_FINISH'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 105;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['ReferralMessageManager'] = entity;
    entity = {};
    option = ['MEDIA_ENGINE_SET_AUDIO_ENABLED', 'AUDIO_INPUT_DETECTED', 'AUDIO_SET_DISPLAY_SILENCE_WARNING', 'CERTIFIED_DEVICES_SET', 'AUDIO_SET_INPUT_DEVICE', 'AUDIO_SET_OUTPUT_DEVICE', 'MEDIA_ENGINE_DEVICES', 'RTC_CONNECTION_STATE', 'VOICE_STATE_UPDATES', 'MEDIA_ENGINE_SET_GO_LIVE_SOURCE', 'MEDIA_ENGINE_SOUNDSHARE_FAILED', 'MEDIA_ENGINE_NOISE_CANCELLATION_ERROR', 'MEDIA_ENGINE_VOICE_ACTIVITY_DETECTION_ERROR', 'MEDIA_ENGINE_VIDEO_STATE_CHANGED', 'NATIVE_SCREEN_SHARE_PICKER_UPDATE', 'NATIVE_SCREEN_SHARE_PICKER_ERROR', 'MEDIA_SESSION_JOINED', 'RTC_CONNECTION_UPDATE_ID', 'RTC_CONNECTION_REMOTE_VIDEO_SINK_WANTS', 'REPORT_AV_ERROR', 'VIDEO_STREAM_READY_TIMEOUT', 'CLEAR_VIDEO_STREAM_READY_TIMEOUT', 'RTC_CONNECTION_VIDEO'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 106;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['AVErrorManager'] = entity;
    entity = {};
    option = ['STREAM_WATCH', 'STREAM_START', 'STREAM_CREATE', 'STREAM_UPDATE', 'STREAM_DELETE', 'STREAM_CLOSE', 'CALL_UPDATE', 'CHANNEL_UPDATES', 'VOICE_CHANNEL_SELECT', 'VOICE_STATE_UPDATES', 'MEDIA_ENGINE_VIDEO_STATE_CHANGED'];
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 107;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['ApplicationStreamingManager'] = entity;
    entity = {};
    option = new Array(0);
    entity['actions'] = option;
    option = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 108;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = option;
    entity['hasStoreChangeListeners'] = tangon;
    michal['LibdiscoreExperimentManager'] = entity;
    entity = {};
    option = ['CONNECTION_OPEN_SUPPLEMENTAL', 'SAFETY_FLOWS_MODAL_OPEN', 'USER_REQUIRED_ACTION_UPDATE'];
    entity['actions'] = option;
    golfie = function() { // Original name: inlineRequire
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 109;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    entity['inlineRequire'] = golfie;
    entity['neverLoadBeforeConnectionOpen'] = tangon;
    michal['SafetyFlowsManager'] = entity;
    entity = 110;
    tangon = oscard[entity];
    entity = undefined;
    golfie = report.bind(entity)(tangon);
    tangon = golfie.initialize;
    tangon = tangon.bind(golfie)(michal);
    tangon = 111;
    tangon = oscard[tangon];
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/app_startup/ManagerRegistry.native.tsx';
    tangon = report.bind(oscard)(tangon);
    zuuluu['default'] = michal;
    return entity;
})();