// app/modules/icymi/native/ICYMIContext.tsx
export default (function(native1, native2, native3, native4, native5, native6, native7) {
    var5 = native2;
    var3 = native6;
    var6 = native7;
    var1 = global;
    var7 = var1.Object;
    var4 = var7.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var4.bind(var7)(var3, var1, var2);
    var7 = 0;
    var2 = var6[var7];
    var1 = undefined;
    var2 = var5.bind(var1)(var2);
    var4 = var2.createContext;
    var2 = {};
    var2['width'] = var7;
    var2 = var4.bind(var1)(var2);
    var4 = 1;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/icymi/native/ICYMIContext.tsx';
    var4 = var5.bind(var6)(var4);
    var3['ICYMIContext'] = var2;
    return var1;
})();