// app/design/components/experimental/Button/native/HeaderButton.native.tsx
export default (function(native1, native2, native3, native4, native5, native6, native7) {
    var5 = native2;
    var3 = native6;
    var6 = native7;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var6;
    var2 = function HeaderButton(arg1) {
        var4 = _closure1_slot2;
        var2 = _closure1_slot0;
        var3 = _closure1_slot1;
        var1 = 2;
        var1 = var3[var1];
        var3 = undefined;
        var1 = var2.bind(var3)(var1);
        var2 = var1.BaseTextButton;
        var1 = {};
        var5 = 'header';
        var1['accessibilityRole'] = var5;
        var7 = arg1;
        var8 = var1;
        var5 = copyDataProperties(var8, var7);
        var6 = 'sm';
        var5 = 'size';
        var1[var5] = var6;
        var6 = 'heading-md/bold';
        var5 = 'textVariant';
        var1[var5] = var6;
        var6 = 'secondary-overlay';
        var5 = 'variant';
        var1[var5] = var6;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var1 = global;
    var9 = var1.Object;
    var8 = var9.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var8.bind(var9)(var3, var1, var4);
    var1 = 0;
    var8 = var6[var1];
    var4 = native4;
    var1 = undefined;
    var4 = var4.bind(var1)(var8);
    var4 = 1;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.jsx;
    var _closure1_slot2 = var4;
    var4 = 2;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.BaseTextButton;
    var4 = var4.Icon;
    var2['Icon'] = var4;
    var4 = 3;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'design/components/experimental/Button/native/HeaderButton.native.tsx';
    var4 = var5.bind(var6)(var4);
    var3['HeaderButton'] = var2;
    return var1;
})();