// app/modules/voice_panel/native/header/calculateVoicePanelHeaderSpecs.tsx
export default (function(argFoo, argBar, _, __, ___, argFred, argPlugh) {
    oscar = argBar;
    zulu = argFred;
    golf = argPlugh;
    entity = global;
    options = entity.Object;
    report = options.defineProperty;
    mike = {};
    entity = true;
    mike['value'] = entity;
    entity = '__esModule';
    entity = report.bind(options)(zulu, entity, mike);
    entity = 0;
    mike = golf[entity];
    entity = undefined;
    mike = oscar.bind(entity)(mike);
    mike = mike.EDGE_GUTTER;
    var _closure1_slot0 = mike;
    report = {};
    options = 'function calculateVoicePanelHeaderSpecs_calculateVoicePanelHeaderSpecsTsx1(safeArea){const{EDGE_GUTTER,BASE_VOICE_PANEL_HEADER_HEIGHT}=this.__closure;const paddingTop=Math.max(EDGE_GUTTER,safeArea.top);const paddingLeft=Math.max(EDGE_GUTTER,safeArea.left);const paddingRight=Math.max(EDGE_GUTTER,safeArea.right);const height=BASE_VOICE_PANEL_HEADER_HEIGHT+paddingTop;return{height:height,paddingTop:paddingTop,paddingLeft:paddingLeft,paddingRight:paddingRight};}';
    report['code'] = options;
    tango = function(argFoo) { // Original name: t
        mike = argFoo;
        zulu = global;
        oscar = zulu.Math;
        tango = oscar.max;
        report = _closure1_slot0;
        entity = mike.top;
        tango = tango.bind(oscar)(report, entity);
        entity = {};
        oscar = 44;
        oscar = oscar + tango;
        entity['height'] = oscar;
        entity['paddingTop'] = tango;
        golf = zulu.Math;
        oscar = golf.max;
        tango = mike.left;
        tango = oscar.bind(golf)(report, tango);
        entity['paddingLeft'] = tango;
        tango = zulu.Math;
        zulu = tango.max;
        mike = mike.right;
        mike = zulu.bind(tango)(report, mike);
        entity['paddingRight'] = mike;
        return entity;
    };
    options = {};
    options['EDGE_GUTTER'] = mike;
    mike = 44;
    options['BASE_VOICE_PANEL_HEADER_HEIGHT'] = mike;
    tango['__closure'] = options;
    options = 12950553046958.0;
    tango['__workletHash'] = options;
    tango['__initData'] = report;
    report = 1;
    report = golf[report];
    golf = oscar.bind(entity)(report);
    oscar = golf.fileFinishedImporting;
    report = 'modules/voice_panel/native/header/calculateVoicePanelHeaderSpecs.tsx';
    report = oscar.bind(golf)(report);
    zulu['default'] = tango;
    zulu['BASE_VOICE_PANEL_HEADER_HEIGHT'] = mike;
    return entity;
})();