// app/modules/quests/native/QuestDisclosureModal/QuestDisclosureModal.tsx
export default (function(argFoo, argBar, argBaz, _, __, argFre, argPlu) {
    report = argBar;
    zuuluu = argFre;
    oscard = argPlu;
    var _closure1_slot0 = report;
    entity = argBaz;
    var _closure1_slot1 = entity;
    var _closure1_slot2 = oscard;
    entity = function() { // Original name: CloseButton
        tangon = _closure1_slot3;
        option = _closure1_slot0;
        verify = _closure1_slot2;
        entity = 1;
        entity = verify[entity];
        zuuluu = undefined;
        entity = option.bind(zuuluu)(entity);
        michal = entity.HeaderActionButton;
        entity = {};
        oscard = _closure1_slot1;
        report = 2;
        report = verify[report];
        report = oscard.bind(zuuluu)(report);
        entity['source'] = report;
        report = function() { // Original name: onPress
            zuuluu = _closure1_slot1;
            michal = _closure1_slot2;
            entity = 3;
            michal = michal[entity];
            entity = undefined;
            michal = zuuluu.bind(entity)(michal);
            entity = michal.hideModal;
            entity = entity.bind(michal)();
            return entity;
        };
        entity['onPress'] = report;
        report = 4;
        oscard = verify[report];
        oscard = option.bind(zuuluu)(oscard);
        golfie = oscard.intl;
        oscard = golfie.string;
        report = verify[report];
        report = option.bind(zuuluu)(report);
        report = report.t;
        report = report.cpT0Cg;
        report = oscard.bind(golfie)(report);
        entity['accessibilityLabel'] = report;
        entity = tangon.bind(zuuluu)(michal, entity);
        return entity;
    };
    var _closure1_slot5 = entity;
    entity = global;
    option = entity.Object;
    golfie = option.defineProperty;
    tangon = {};
    entity = true;
    tangon['value'] = entity;
    entity = '__esModule';
    entity = golfie.bind(option)(zuuluu, entity, tangon);
    entity = 0;
    tangon = oscard[entity];
    entity = undefined;
    tangon = report.bind(entity)(tangon);
    tangon = tangon.jsx;
    var _closure1_slot3 = tangon;
    tangon = {};
    golfie = 'disclosure';
    tangon['DISCLOSURE'] = golfie;
    var _closure1_slot4 = tangon;
    tangon = 8;
    tangon = oscard[tangon];
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/quests/native/QuestDisclosureModal/QuestDisclosureModal.tsx';
    tangon = report.bind(oscard)(tangon);
    michal = function(argFoo) { // Original name: QuestDisclosureModal
        entity = argFoo;
        michal = entity.isTargetedDisclosure;
        var _closure2_slot0 = michal;
        michal = entity.gamePublisher;
        var _closure2_slot1 = michal;
        michal = entity.gameTitle;
        var _closure2_slot2 = michal;
        entity = entity.cosponsorName;
        var _closure2_slot3 = entity;
        entity = function() { // Original name: onClose
            zuuluu = _closure1_slot1;
            michal = _closure1_slot2;
            entity = 3;
            michal = michal[entity];
            entity = undefined;
            michal = zuuluu.bind(entity)(michal);
            entity = michal.hideModal;
            entity = entity.bind(michal)();
            return entity;
        };
        var _closure2_slot4 = entity;
        oscard = {};
        report = _closure1_slot4;
        zuuluu = report.DISCLOSURE;
        michal = {};
        golfie = _closure1_slot5;
        michal['headerLeft'] = golfie;
        golfie = function() { // Original name: headerRight
            entity = null;
            return entity;
        };
        michal['headerRight'] = golfie;
        golfie = function() { // Original name: headerTitle
            tangon = _closure1_slot3;
            option = _closure1_slot0;
            verify = _closure1_slot2;
            entity = 5;
            entity = verify[entity];
            zuuluu = undefined;
            entity = option.bind(zuuluu)(entity);
            michal = entity.NavigatorHeader;
            entity = {};
            report = 4;
            oscard = verify[report];
            oscard = option.bind(zuuluu)(oscard);
            golfie = oscard.intl;
            oscard = golfie.string;
            report = verify[report];
            report = option.bind(zuuluu)(report);
            report = report.t;
            report = report.GcsZKC;
            report = oscard.bind(golfie)(report);
            entity['title'] = report;
            entity = tangon.bind(zuuluu)(michal, entity);
            return entity;
        };
        michal['headerTitle'] = golfie;
        tangon = function() { // Original name: render
            tangon = _closure1_slot3;
            michal = _closure1_slot1;
            zuuluu = _closure1_slot2;
            entity = 6;
            entity = zuuluu[entity];
            zuuluu = undefined;
            michal = michal.bind(zuuluu)(entity);
            entity = {};
            oscard = _closure2_slot0;
            entity['isTargetedDisclosure'] = oscard;
            oscard = _closure2_slot1;
            entity['gamePublisher'] = oscard;
            oscard = _closure2_slot2;
            entity['gameTitle'] = oscard;
            oscard = _closure2_slot4;
            entity['onClose'] = oscard;
            report = _closure2_slot3;
            entity['cosponsorName'] = report;
            entity = tangon.bind(zuuluu)(michal, entity);
            return entity;
        };
        michal['render'] = tangon;
        oscard[zuuluu] = michal;
        tangon = _closure1_slot3;
        option = _closure1_slot0;
        verify = _closure1_slot2;
        entity = 7;
        entity = verify[entity];
        zuuluu = undefined;
        entity = option.bind(zuuluu)(entity);
        michal = entity.Navigator;
        entity = {};
        entity['screens'] = oscard;
        report = report.DISCLOSURE;
        entity['initialRouteName'] = report;
        report = 4;
        oscard = verify[report];
        oscard = option.bind(zuuluu)(oscard);
        golfie = oscard.intl;
        oscard = golfie.string;
        report = verify[report];
        report = option.bind(zuuluu)(report);
        report = report.t;
        report = report.13/7kZ;
        report = oscard.bind(golfie)(report);
        entity['headerBackTitle'] = report;
        entity = tangon.bind(zuuluu)(michal, entity);
        return entity;
    };
    zuuluu['default'] = michal;
    return entity;
})();