// app/modules/quests/native/QuestDisclosureModal/QuestDisclosureModal.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var1 = metroImportDefault;
    var _closure1_slot1 = var1;
    var _closure1_slot2 = var6;
    var1 = function CloseButton() {
        var4 = _closure1_slot3;
        var8 = _closure1_slot0;
        var9 = _closure1_slot2;
        var1 = 1;
        var1 = var9[var1];
        var3 = undefined;
        var1 = var8.bind(var3)(var1);
        var2 = var1.HeaderActionButton;
        var1 = {};
        var6 = _closure1_slot1;
        var5 = 2;
        var5 = var9[var5];
        var5 = var6.bind(var3)(var5);
        var1['source'] = var5;
        var5 = function onPress() {
            var3 = _closure1_slot1;
            var2 = _closure1_slot2;
            var1 = 3;
            var2 = var2[var1];
            var1 = undefined;
            var2 = var3.bind(var1)(var2);
            var1 = var2.hideModal;
            var1 = var1.bind(var2)();
            return var1;
        };
        var1['onPress'] = var5;
        var5 = 4;
        var6 = var9[var5];
        var6 = var8.bind(var3)(var6);
        var7 = var6.intl;
        var6 = var7.string;
        var5 = var9[var5];
        var5 = var8.bind(var3)(var5);
        var5 = var5.t;
        var5 = var5.cpT0Cg;
        var5 = var6.bind(var7)(var5);
        var1['accessibilityLabel'] = var5;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var _closure1_slot5 = var1;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var5.bind(var1)(var4);
    var4 = var4.jsx;
    var _closure1_slot3 = var4;
    var4 = {};
    var7 = 'disclosure';
    var4['DISCLOSURE'] = var7;
    var _closure1_slot4 = var4;
    var4 = 8;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/quests/native/QuestDisclosureModal/QuestDisclosureModal.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function QuestDisclosureModal(arg1) {
        var1 = arg1;
        var2 = var1.isTargetedDisclosure;
        var _closure2_slot0 = var2;
        var2 = var1.gamePublisher;
        var _closure2_slot1 = var2;
        var2 = var1.gameTitle;
        var _closure2_slot2 = var2;
        var1 = var1.cosponsorName;
        var _closure2_slot3 = var1;
        var1 = function onClose() {
            var3 = _closure1_slot1;
            var2 = _closure1_slot2;
            var1 = 3;
            var2 = var2[var1];
            var1 = undefined;
            var2 = var3.bind(var1)(var2);
            var1 = var2.hideModal;
            var1 = var1.bind(var2)();
            return var1;
        };
        var _closure2_slot4 = var1;
        var6 = {};
        var5 = _closure1_slot4;
        var3 = var5.DISCLOSURE;
        var2 = {};
        var7 = _closure1_slot5;
        var2['headerLeft'] = var7;
        var7 = function headerRight() {
            var1 = null;
            return var1;
        };
        var2['headerRight'] = var7;
        var7 = function headerTitle() {
            var4 = _closure1_slot3;
            var8 = _closure1_slot0;
            var9 = _closure1_slot2;
            var1 = 5;
            var1 = var9[var1];
            var3 = undefined;
            var1 = var8.bind(var3)(var1);
            var2 = var1.NavigatorHeader;
            var1 = {};
            var5 = 4;
            var6 = var9[var5];
            var6 = var8.bind(var3)(var6);
            var7 = var6.intl;
            var6 = var7.string;
            var5 = var9[var5];
            var5 = var8.bind(var3)(var5);
            var5 = var5.t;
            var5 = var5.GcsZKC;
            var5 = var6.bind(var7)(var5);
            var1['title'] = var5;
            var1 = var4.bind(var3)(var2, var1);
            return var1;
        };
        var2['headerTitle'] = var7;
        var4 = function render() {
            var4 = _closure1_slot3;
            var2 = _closure1_slot1;
            var3 = _closure1_slot2;
            var1 = 6;
            var1 = var3[var1];
            var3 = undefined;
            var2 = var2.bind(var3)(var1);
            var1 = {};
            var6 = _closure2_slot0;
            var1['isTargetedDisclosure'] = var6;
            var6 = _closure2_slot1;
            var1['gamePublisher'] = var6;
            var6 = _closure2_slot2;
            var1['gameTitle'] = var6;
            var6 = _closure2_slot4;
            var1['onClose'] = var6;
            var5 = _closure2_slot3;
            var1['cosponsorName'] = var5;
            var1 = var4.bind(var3)(var2, var1);
            return var1;
        };
        var2['render'] = var4;
        var6[var3] = var2;
        var4 = _closure1_slot3;
        var8 = _closure1_slot0;
        var9 = _closure1_slot2;
        var1 = 7;
        var1 = var9[var1];
        var3 = undefined;
        var1 = var8.bind(var3)(var1);
        var2 = var1.Navigator;
        var1 = {};
        var1['screens'] = var6;
        var5 = var5.DISCLOSURE;
        var1['initialRouteName'] = var5;
        var5 = 4;
        var6 = var9[var5];
        var6 = var8.bind(var3)(var6);
        var7 = var6.intl;
        var6 = var7.string;
        var5 = var9[var5];
        var5 = var8.bind(var3)(var5);
        var5 = var5.t;
        var5 = var5.13/7kZ;
        var5 = var6.bind(var7)(var5);
        var1['headerBackTitle'] = var5;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var3['default'] = var2;
    return var1;
})();