// app/modules/telemetry_ring/native/TelemetryRingNative.android.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var3 = exports;
    var5 = dependencyMap;
    var2 = metroImportDefault;
    var _closure1_slot0 = var2;
    var _closure1_slot1 = var5;
    var2 = global;
    var7 = var2.Object;
    var6 = var7.defineProperty;
    var4 = {};
    var2 = true;
    var4['value'] = var2;
    var2 = '__esModule';
    var2 = var6.bind(var7)(var3, var2, var4);
    var2 = {};
    var4 = 'SENTRY';
    var2['SENTRY'] = var4;
    var4 = 'NORMAL';
    var2['NORMAL'] = var4;
    var4 = 'ZOOMED';
    var2['ZOOMED'] = var4;
    var4 = {};
    var6 = function append(arg1, arg2, arg3, arg4, arg5) {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 0;
        var2 = var2[var1];
        var1 = undefined;
        var8 = var3.bind(var1)(var2);
        var7 = var8.append;
        var13 = arg1;
        var12 = arg2;
        var11 = arg3;
        var10 = arg4;
        var9 = arg5;
        var14 = var8;
        var2 = var14[var7](var13, var12, var11, var10, var9, var8);
        return var1;
    };
    var4['append'] = var6;
    var6 = function snapshot(arg1, arg2, arg3, arg4) {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 0;
        var2 = var2[var1];
        var1 = undefined;
        var6 = var3.bind(var1)(var2);
        var5 = var6.snapshot;
        var10 = arg1;
        var9 = arg2;
        var8 = arg3;
        var7 = arg4;
        var11 = var6;
        var1 = var11[var5](var10, var9, var8, var7, var6);
        return var1;
    };
    var4['snapshot'] = var6;
    var1 = function clear() {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 0;
        var2 = var2[var1];
        var1 = undefined;
        var3 = var3.bind(var1)(var2);
        var2 = var3.clear;
        var2 = var2.bind(var3)();
        return var1;
    };
    var4['clear'] = var1;
    var1 = 1;
    var6 = var5[var1];
    var5 = require;
    var1 = undefined;
    var7 = var5.bind(var1)(var6);
    var6 = var7.fileFinishedImporting;
    var5 = 'modules/telemetry_ring/native/TelemetryRingNative.android.tsx';
    var5 = var6.bind(var7)(var5);
    var3['default'] = var4;
    var3['TelemetryChannel'] = var2;
    return var1;
})();