// app/modules/main_tabs_v2/native/shared_components/user_list/useScaledActionHeight.tsx
export default (function(_, argBar, __, ___, ____, argFre, argPlu) {
    report = argBar;
    zuuluu = argFre;
    oscard = argPlu;
    var _closure1_slot0 = report;
    var _closure1_slot1 = oscard;
    entity = global;
    option = entity.Object;
    golfie = option.defineProperty;
    tangon = {};
    entity = true;
    tangon['value'] = entity;
    entity = '__esModule';
    entity = golfie.bind(option)(zuuluu, entity, tangon);
    tangon = 0;
    golfie = oscard[tangon];
    entity = undefined;
    golfie = report.bind(entity)(golfie);
    golfie = golfie.TABLE_ROW_HEIGHT;
    var _closure1_slot2 = golfie;
    tangon = oscard[tangon];
    tangon = report.bind(entity)(tangon);
    tangon = tangon.TABLE_ROW_CONTENT_HEIGHT;
    var _closure1_slot3 = tangon;
    tangon = 2;
    tangon = oscard[tangon];
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/main_tabs_v2/native/shared_components/user_list/useScaledActionHeight.tsx';
    tangon = report.bind(oscard)(tangon);
    michal = function() { // Original name: useScaledActionHeight
        tangon = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 1;
        michal = michal[entity];
        entity = undefined;
        michal = tangon.bind(entity)(michal);
        entity = michal.useFontScale;
        entity = entity.bind(michal)();
        michal = _closure1_slot2;
        tangon = global;
        report = tangon.Math;
        tangon = report.max;
        zuuluu = _closure1_slot3;
        entity = entity * zuuluu;
        zuuluu = entity - zuuluu;
        entity = 0;
        entity = tangon.bind(report)(zuuluu, entity);
        entity = michal + entity;
        return entity;
    };
    zuuluu['default'] = michal;
    return entity;
})();