// app/modules/interactions/InteractionTypes.tsx
export default (function(_, argBar, __, ___, ____, argFre, argPlu) {
    zuuluu = argFre;
    entity = global;
    report = entity.Object;
    tangon = report.defineProperty;
    michal = {};
    entity = true;
    michal['value'] = entity;
    entity = '__esModule';
    entity = tangon.bind(report)(zuuluu, entity, michal);
    michal = {};
    tangon = 0;
    michal['QUEUED'] = tangon;
    entity = 'QUEUED';
    michal[tangon] = entity;
    report = 1;
    michal['CREATED'] = report;
    entity = 'CREATED';
    michal[report] = entity;
    report = 2;
    michal['FAILED'] = report;
    entity = 'FAILED';
    michal[report] = entity;
    entity = argPlu;
    report = entity[tangon];
    tangon = argBar;
    entity = undefined;
    oscard = tangon.bind(entity)(report);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/interactions/InteractionTypes.tsx';
    tangon = report.bind(oscard)(tangon);
    zuuluu['InteractionState'] = michal;
    return entity;
})();