// app/modules/guild_sidebar/native/PremiumGuildSubscriptionPromptTooltip.tsx
export default (function(argFoo, argBar, argBaz, argCorge, _, argFred, argPlugh) {
    report = argBar;
    yankee = argBaz;
    zulu = argFred;
    oscar = argPlugh;
    var _closure1_slot0 = report;
    var _closure1_slot1 = yankee;
    var _closure1_slot2 = oscar;
    entity = global;
    options = entity.Object;
    golf = options.defineProperty;
    tango = {};
    entity = true;
    tango['value'] = entity;
    entity = '__esModule';
    entity = golf.bind(options)(zulu, entity, tango);
    entity = 0;
    golf = oscar[entity];
    tango = argCorge;
    entity = undefined;
    tango = tango.bind(entity)(golf);
    var _closure1_slot3 = tango;
    tango = 1;
    tango = oscar[tango];
    tango = report.bind(entity)(tango);
    options = tango.StyleSheet;
    tango = 2;
    tango = oscar[tango];
    tango = yankee.bind(entity)(tango);
    var _closure1_slot4 = tango;
    tango = 3;
    tango = oscar[tango];
    tango = yankee.bind(entity)(tango);
    var _closure1_slot5 = tango;
    tango = 4;
    tango = oscar[tango];
    tango = report.bind(entity)(tango);
    tango = tango.jsx;
    var _closure1_slot6 = tango;
    golf = options.create;
    tango = {};
    offset = 16;
    verify = {'marginTop': 8, 'marginLeft': 190, 'top': 2, 'position': 'relative', 'borderTopWidth': 0, 'borderRightWidth': 0, 'borderBottomWidth': 16, 'borderLeftWidth': 16};
    tango['arrow'] = verify;
    verify = {};
    romeo = 173;
    verify['marginLeft'] = romeo;
    tango['shortWidthArrow'] = verify;
    verify = {};
    verify['padding'] = offset;
    tango['tooltip'] = verify;
    verify = {'position': 'absolute', 'width': 240, 'zIndex': 10, 'right': 8, 'top': 4294967286};
    tango['tooltipContainer'] = verify;
    verify = {};
    offset = 200;
    verify['width'] = offset;
    tango['shortWidthTooltipContainer'] = verify;
    verify = {};
    offset = 'center';
    verify['textAlign'] = offset;
    tango['tooltipText'] = verify;
    verify = {'paddingVertical': 0, 'marginTop': 14, 'alignSelf': 'stretch'};
    offset = 5;
    romeo = oscar[offset];
    romeo = yankee.bind(entity)(romeo);
    romeo = romeo.unsafe_rawColors;
    romeo = romeo.PRIMARY_100;
    verify['backgroundColor'] = romeo;
    tango['closeButton'] = verify;
    verify = {};
    offset = oscar[offset];
    offset = yankee.bind(entity)(offset);
    offset = offset.unsafe_rawColors;
    offset = offset.BRAND_500;
    verify['color'] = offset;
    tango['closeButtonText'] = verify;
    tango = golf.bind(options)(tango);
    var _closure1_slot7 = tango;
    tango = {};
    golf = 'function PremiumGuildSubscriptionPromptTooltipTsx1(){const{scrollPosition}=this.__closure;return scrollPosition.get();}';
    tango['code'] = golf;
    var _closure1_slot8 = tango;
    tango = {};
    golf = 'function PremiumGuildSubscriptionPromptTooltipTsx2(current,previous){const{bannerOffset,headerHeight,runOnJS,checkScrolling}=this.__closure;const newTranslateY=Math.max(bannerOffset-current,headerHeight/2);const oldTranslateY=Math.max(bannerOffset-(previous!==null&&previous!==void 0?previous:0),headerHeight/2);if(newTranslateY!==oldTranslateY){runOnJS(checkScrolling)();}}';
    tango['code'] = golf;
    var _closure1_slot9 = tango;
    tango = {};
    golf = 'function PremiumGuildSubscriptionPromptTooltipTsx3(){const{bannerOffset,scrollPosition,headerHeight,withTiming,opacity,shouldLoop,withRepeat,withSequence,translateBounceOffset}=this.__closure;const translateY=Math.max(bannerOffset-scrollPosition.get(),headerHeight/2);return{opacity:withTiming(opacity.get(),{duration:500}),transform:[{translateY:!shouldLoop.get()?translateY:withRepeat(withSequence(withTiming(translateY,{duration:500}),withTiming(translateY+translateBounceOffset,{duration:500})),-1,true)}]};}';
    tango['code'] = golf;
    var _closure1_slot10 = tango;
    tango = {};
    golf = 'function PremiumGuildSubscriptionPromptTooltipTsx4(){const{scrollPosition}=this.__closure;return scrollPosition.get();}';
    tango['code'] = golf;
    var _closure1_slot11 = tango;
    tango = {};
    golf = 'function PremiumGuildSubscriptionPromptTooltipTsx5(current,previous){const{bannerOffset,bannerHeight,headerHeight,runOnJS,checkScrolling}=this.__closure;const newTranslateY=Math.max(current-bannerOffset,bannerHeight+headerHeight/2);const oldTranslateY=Math.max((previous!==null&&previous!==void 0?previous:0)-bannerOffset,bannerHeight+headerHeight/2);if(newTranslateY!==oldTranslateY){runOnJS(checkScrolling)();}}';
    tango['code'] = golf;
    var _closure1_slot12 = tango;
    tango = {};
    golf = 'function PremiumGuildSubscriptionPromptTooltipTsx6(){const{scrollPosition,bannerHeight,headerHeight,withTiming,opacity,shouldLoop,withRepeat,withSequence,translateBounceOffset}=this.__closure;let sp=scrollPosition.get();if(sp<=bannerHeight){sp=bannerHeight+headerHeight/2;}else{sp=sp+headerHeight/2;}const translateY=sp;return{opacity:withTiming(opacity.get(),{duration:500}),transform:[{translateY:!shouldLoop.get()?translateY:withRepeat(withSequence(withTiming(translateY,{duration:500}),withTiming(translateY+translateBounceOffset,{duration:500})),-1,true)}]};}';
    tango['code'] = golf;
    var _closure1_slot13 = tango;
    tango = 12;
    tango = oscar[tango];
    oscar = report.bind(entity)(tango);
    report = oscar.fileFinishedImporting;
    tango = 'modules/guild_sidebar/native/PremiumGuildSubscriptionPromptTooltip.tsx';
    tango = report.bind(oscar)(tango);
    tango = function(argFoo) { // Original name: PremiumGuildSubscriptionPromptTooltip
        _fun00001: for(var _fun00002_ip = 0; ; ) switch(_fun00002_ip) {
 0:
            entity = argFoo;
            result = entity.bannerHeight;
            var _closure2_slot0 = result;
            output = entity.headerHeight;
            var _closure2_slot1 = output;
            echo = entity.scrollPosition;
            var _closure2_slot2 = echo;
            kilo = entity.onClosePress;
            tango = undefined;
            var _closure2_slot5 = tango;
            var _closure2_slot6 = tango;
            var _closure2_slot7 = tango;
            var _closure2_slot8 = tango;
            zulu = -result;
            entity = 2;
            entity = output / entity;
            control = zulu - entity;
            var _closure2_slot3 = control;
            golf = _closure1_slot0;
            options = _closure1_slot2;
            report = 6;
            entity = options[report];
            oscar = golf.bind(tango)(entity);
            zulu = oscar.useSharedValue;
            entity = 0;
            offset = zulu.bind(oscar)(entity);
            var _closure2_slot4 = offset;
            oscar = 7;
            zulu = options[oscar];
            romeo = golf.bind(tango)(zulu);
            yankee = romeo.useStateFromStores;
            zulu = _closure1_slot5;
            verify = new Array(1);
            verify[0] = zulu;
            zulu = function() {
                mike = _closure1_slot5;
                entity = mike.getWidth;
                entity = entity.bind(mike)();
                return entity;
            };
            zulu = yankee.bind(romeo)(verify, zulu);
            oscar = options[oscar];
            verify = golf.bind(tango)(oscar);
            options = verify.useStateFromStores;
            oscar = _closure1_slot4;
            golf = new Array(1);
            golf[0] = oscar;
            oscar = function() {
                entity = _closure1_slot4;
                entity = entity.useReducedMotion;
                return entity;
            };
            oscar = options.bind(verify)(golf, oscar);
            romeo = 4;
            if(!oscar) { _fun00002_ip = 205; continue _fun00001 }
 203:
            romeo = 0;
 205:
            _closure2_slot5 = romeo;
            sizing = _closure1_slot0;
            entity = _closure1_slot2;
            oscar = entity[report];
            options = sizing.bind(tango)(oscar);
            golf = options.useSharedValue;
            oscar = false;
            foxtrot = golf.bind(options)(oscar);
            _closure2_slot6 = foxtrot;
            verify = _closure1_slot3;
            golf = verify.useRef;
            oscar = -1;
            oscar = golf.bind(verify)(oscar);
            _closure2_slot7 = oscar;
            options = verify.useCallback;
            golf = new Array(2);
            golf[0] = oscar;
            golf[1] = foxtrot;
            oscar = function() {
                zulu = global;
                report = zulu.clearTimeout;
                entity = _closure2_slot7;
                tango = entity.current;
                entity = undefined;
                tango = report.bind(entity)(tango);
                tango = _closure2_slot7;
                oscar = zulu.setTimeout;
                report = function() {
                    zulu = _closure2_slot6;
                    mike = zulu.set;
                    entity = true;
                    entity = mike.bind(zulu)(entity);
                    entity = undefined;
                    return entity;
                };
                zulu = 100;
                zulu = oscar.bind(entity)(report, zulu);
                tango['current'] = zulu;
                tango = _closure2_slot6;
                zulu = tango.set;
                mike = false;
                mike = zulu.bind(tango)(mike);
                return entity;
            };
            source = options.bind(verify)(oscar, golf);
            _closure2_slot8 = source;
            oscar = entity[report];
            yankee = sizing.bind(tango)(oscar);
            options = yankee.useAnimatedReaction;
            golf = function() { // Original name: _
                mike = _closure2_slot2;
                entity = mike.get;
                entity = entity.bind(mike)();
                return entity;
            };
            oscar = {};
            oscar['scrollPosition'] = echo;
            golf['__closure'] = oscar;
            oscar = 17178753567879.0;
            golf['__workletHash'] = oscar;
            oscar = _closure1_slot11;
            golf['__initData'] = oscar;
            oscar = function(argFoo, argBar) { // Original name: T
                _fun00003: for(var _fun00004_ip = 0; ; ) switch(_fun00004_ip) {
 0:
                    mike = argBar;
                    tango = global;
                    golf = tango.Math;
                    oscar = golf.max;
                    report = _closure2_slot3;
                    zulu = argFoo;
                    report = zulu - report;
                    verify = _closure2_slot0;
                    zulu = _closure2_slot1;
                    options = 2;
                    zulu = zulu / options;
                    zulu = verify + zulu;
                    zulu = oscar.bind(golf)(report, zulu);
                    oscar = tango.Math;
                    report = oscar.max;
                    tango = null;
                    golf = tango != mike;
                    tango = 0;
                    if(!golf) { _fun00004_ip = 80; continue _fun00003 }
 77:
                    tango = mike;
 80:
                    mike = _closure2_slot3;
                    tango = tango - mike;
                    golf = _closure2_slot0;
                    mike = _closure2_slot1;
                    mike = mike / options;
                    mike = golf + mike;
                    mike = report.bind(oscar)(tango, mike);
                    if(!(zulu !== mike)) { _fun00004_ip = 157; continue _fun00003 }
 114:
                    tango = _closure1_slot0;
                    zulu = _closure1_slot2;
                    mike = 6;
                    zulu = zulu[mike];
                    mike = undefined;
                    tango = tango.bind(mike)(zulu);
                    zulu = tango.runOnJS;
                    entity = _closure2_slot8;
                    entity = zulu.bind(tango)(entity);
                    entity = entity.bind(mike)();
 157:
                    entity = undefined;
                    return entity;
                }
            };
            update = {};
            update['bannerOffset'] = control;
            update['bannerHeight'] = result;
            update['headerHeight'] = output;
            control = entity[report];
            control = sizing.bind(tango)(control);
            control = control.runOnJS;
            update['runOnJS'] = control;
            update['checkScrolling'] = source;
            oscar['__closure'] = update;
            update = 12896852940649.0;
            oscar['__workletHash'] = update;
            update = _closure1_slot12;
            oscar['__initData'] = update;
            oscar = options.bind(yankee)(golf, oscar);
            oscar = entity[report];
            options = sizing.bind(tango)(oscar);
            golf = options.useAnimatedStyle;
            oscar = function() { // Original name: R
                _fun00005: for(var _fun00006_ip = 0; ; ) switch(_fun00006_ip) {
 0:
                    mike = _closure2_slot2;
                    entity = mike.get;
                    mike = entity.bind(mike)();
                    entity = _closure2_slot0;
                    if(!(!(mike <= entity))) { _fun00006_ip = 41; continue _fun00005 }
 24:
                    zulu = _closure2_slot1;
                    entity = 2;
                    entity = zulu / entity;
                    offset = mike + entity;
                    _fun00006_ip = 60; continue _fun00005;
 41:
                    mike = _closure2_slot0;
                    zulu = _closure2_slot1;
                    entity = 2;
                    entity = zulu / entity;
                    offset = mike + entity;
 60:
                    entity = {};
                    zulu = _closure1_slot0;
                    mike = _closure1_slot2;
                    kilo = 8;
                    mike = mike[kilo];
                    backup = undefined;
                    golf = zulu.bind(backup)(mike);
                    oscar = golf.withTiming;
                    zulu = _closure2_slot4;
                    mike = zulu.get;
                    zulu = mike.bind(zulu)();
                    mike = {};
                    foxtrot = 500;
                    mike['duration'] = foxtrot;
                    mike = oscar.bind(golf)(zulu, mike);
                    entity['opacity'] = mike;
                    zulu = {};
                    oscar = _closure2_slot6;
                    mike = oscar.get;
                    oscar = mike.bind(oscar)();
                    mike = offset;
                    if(!oscar) { _fun00006_ip = 273; continue _fun00005 }
 151:
                    romeo = _closure1_slot0;
                    yankee = _closure1_slot2;
                    report = 6;
                    oscar = yankee[report];
                    options = romeo.bind(backup)(oscar);
                    golf = options.withRepeat;
                    report = yankee[report];
                    verify = romeo.bind(backup)(report);
                    oscar = verify.withSequence;
                    report = yankee[kilo];
                    output = romeo.bind(backup)(report);
                    sizing = output.withTiming;
                    report = {};
                    report['duration'] = foxtrot;
                    report = sizing.bind(output)(offset, report);
                    yankee = yankee[kilo];
                    romeo = romeo.bind(backup)(yankee);
                    yankee = romeo.withTiming;
                    tango = _closure2_slot5;
                    offset = offset + tango;
                    tango = {};
                    tango['duration'] = foxtrot;
                    tango = yankee.bind(romeo)(offset, tango);
                    oscar = oscar.bind(verify)(report, tango);
                    report = -1;
                    tango = true;
                    mike = golf.bind(options)(oscar, report, tango);
 273:
                    zulu['translateY'] = mike;
                    mike = new Array(1);
                    mike[0] = zulu;
                    entity['transform'] = mike;
                    return entity;
                }
            };
            yankee = {};
            yankee['scrollPosition'] = echo;
            yankee['bannerHeight'] = result;
            yankee['headerHeight'] = output;
            output = 8;
            output = entity[output];
            output = sizing.bind(tango)(output);
            output = output.withTiming;
            yankee['withTiming'] = output;
            yankee['opacity'] = offset;
            yankee['shouldLoop'] = foxtrot;
            foxtrot = entity[report];
            foxtrot = sizing.bind(tango)(foxtrot);
            foxtrot = foxtrot.withRepeat;
            yankee['withRepeat'] = foxtrot;
            foxtrot = entity[report];
            foxtrot = sizing.bind(tango)(foxtrot);
            foxtrot = foxtrot.withSequence;
            yankee['withSequence'] = foxtrot;
            yankee['translateBounceOffset'] = romeo;
            oscar['__closure'] = yankee;
            yankee = 17167097810223.0;
            oscar['__workletHash'] = yankee;
            yankee = _closure1_slot13;
            oscar['__initData'] = yankee;
            oscar = golf.bind(options)(oscar);
            options = verify.useEffect;
            golf = new Array(1);
            golf[0] = offset;
            mike = function() {
                entity = global;
                tango = entity.setTimeout;
                entity = undefined;
                zulu = function() {
                    zulu = _closure2_slot4;
                    mike = zulu.set;
                    entity = 1;
                    entity = mike.bind(zulu)(entity);
                    entity = undefined;
                    return entity;
                };
                mike = 500;
                mike = tango.bind(entity)(zulu, mike);
                return entity;
            };
            mike = options.bind(verify)(mike, golf);
            mike = 330;
            offset = zulu <= mike;
            zulu = _closure1_slot6;
            mike = _closure1_slot1;
            entity = entity[report];
            entity = mike.bind(tango)(entity);
            mike = entity.View;
            entity = {};
            report = _closure1_slot7;
            golf = report.tooltipContainer;
            report = new Array(3);
            report[0] = golf;
            golf = null;
            if(!offset) { _fun00002_ip = 690; continue _fun00001 }
 680:
            options = _closure1_slot7;
            golf = options.shortWidthTooltipContainer;
 690:
            report[1] = golf;
            report[2] = oscar;
            entity['style'] = report;
            golf = _closure1_slot6;
            oscar = _closure1_slot1;
            options = _closure1_slot2;
            report = 9;
            report = options[report];
            oscar = oscar.bind(tango)(report);
            report = {};
            options = _closure1_slot7;
            yankee = options.tooltip;
            report['containerStyle'] = yankee;
            yankee = options.tooltipText;
            report['labelStyle'] = yankee;
            yankee = options.arrow;
            options = new Array(2);
            options[0] = yankee;
            verify = null;
            if(!offset) { _fun00002_ip = 783; continue _fun00001 }
 773:
            offset = _closure1_slot7;
            verify = offset.shortWidthArrow;
 783:
            options[1] = verify;
            report['arrowStyle'] = options;
            echo = _closure1_slot0;
            foxtrot = _closure1_slot2;
            sizing = 10;
            options = foxtrot[sizing];
            options = echo.bind(tango)(options);
            offset = options.intl;
            verify = offset.string;
            options = foxtrot[sizing];
            options = echo.bind(tango)(options);
            options = options.t;
            options = options.UyHD4O;
            options = verify.bind(offset)(options);
            report['label'] = options;
            options = foxtrot[sizing];
            options = echo.bind(tango)(options);
            offset = options.intl;
            verify = offset.string;
            options = foxtrot[sizing];
            options = echo.bind(tango)(options);
            options = options.t;
            options = options.Q3qa4+;
            options = verify.bind(offset)(options);
            report['title'] = options;
            offset = _closure1_slot6;
            romeo = _closure1_slot1;
            yankee = 11;
            options = foxtrot[yankee];
            verify = romeo.bind(tango)(options);
            options = {};
            output = foxtrot[sizing];
            output = echo.bind(tango)(output);
            result = output.intl;
            output = result.string;
            sizing = foxtrot[sizing];
            sizing = echo.bind(tango)(sizing);
            sizing = sizing.t;
            sizing = sizing.U9PrMz;
            sizing = output.bind(result)(sizing);
            options['text'] = sizing;
            options['onPress'] = kilo;
            kilo = foxtrot[yankee];
            kilo = romeo.bind(tango)(kilo);
            kilo = kilo.Colors;
            kilo = kilo.PRIMARY;
            options['color'] = kilo;
            backup = _closure1_slot7;
            kilo = backup.closeButtonText;
            options['textStyle'] = kilo;
            backup = backup.closeButton;
            options['style'] = backup;
            yankee = foxtrot[yankee];
            yankee = romeo.bind(tango)(yankee);
            yankee = yankee.Sizes;
            yankee = yankee.SMALL;
            options['size'] = yankee;
            yankee = true;
            options['shrink'] = yankee;
            options = offset.bind(tango)(verify, options);
            report['children'] = options;
            report = golf.bind(tango)(oscar, report);
            entity['children'] = report;
            entity = zulu.bind(tango)(mike, entity);
            return entity;
        }
    };
    zulu['default'] = tango;
    mike = function(argFoo) { // Original name: PremiumGuildSubscriptionPromptTooltipFlashList
        _fun00007: for(var _fun00008_ip = 0; ; ) switch(_fun00008_ip) {
 0:
            entity = argFoo;
            zulu = entity.bannerHeight;
            output = entity.headerHeight;
            var _closure2_slot0 = output;
            result = entity.scrollPosition;
            var _closure2_slot1 = result;
            kilo = entity.onClosePress;
            tango = undefined;
            var _closure2_slot4 = tango;
            var _closure2_slot5 = tango;
            var _closure2_slot6 = tango;
            var _closure2_slot7 = tango;
            entity = 2;
            entity = output / entity;
            echo = entity + zulu;
            var _closure2_slot2 = echo;
            golf = _closure1_slot0;
            options = _closure1_slot2;
            report = 6;
            entity = options[report];
            oscar = golf.bind(tango)(entity);
            zulu = oscar.useSharedValue;
            entity = 0;
            offset = zulu.bind(oscar)(entity);
            var _closure2_slot3 = offset;
            oscar = 7;
            zulu = options[oscar];
            romeo = golf.bind(tango)(zulu);
            yankee = romeo.useStateFromStores;
            zulu = _closure1_slot5;
            verify = new Array(1);
            verify[0] = zulu;
            zulu = function() {
                mike = _closure1_slot5;
                entity = mike.getWidth;
                entity = entity.bind(mike)();
                return entity;
            };
            zulu = yankee.bind(romeo)(verify, zulu);
            oscar = options[oscar];
            verify = golf.bind(tango)(oscar);
            options = verify.useStateFromStores;
            oscar = _closure1_slot4;
            golf = new Array(1);
            golf[0] = oscar;
            oscar = function() {
                entity = _closure1_slot4;
                entity = entity.useReducedMotion;
                return entity;
            };
            oscar = options.bind(verify)(golf, oscar);
            romeo = 4;
            if(!oscar) { _fun00008_ip = 198; continue _fun00007 }
 196:
            romeo = 0;
 198:
            _closure2_slot4 = romeo;
            sizing = _closure1_slot0;
            entity = _closure1_slot2;
            oscar = entity[report];
            options = sizing.bind(tango)(oscar);
            golf = options.useSharedValue;
            oscar = false;
            foxtrot = golf.bind(options)(oscar);
            _closure2_slot5 = foxtrot;
            verify = _closure1_slot3;
            golf = verify.useRef;
            oscar = -1;
            oscar = golf.bind(verify)(oscar);
            _closure2_slot6 = oscar;
            options = verify.useCallback;
            golf = new Array(2);
            golf[0] = oscar;
            golf[1] = foxtrot;
            oscar = function() {
                zulu = global;
                report = zulu.clearTimeout;
                entity = _closure2_slot6;
                tango = entity.current;
                entity = undefined;
                tango = report.bind(entity)(tango);
                tango = _closure2_slot6;
                oscar = zulu.setTimeout;
                report = function() {
                    zulu = _closure2_slot5;
                    mike = zulu.set;
                    entity = true;
                    entity = mike.bind(zulu)(entity);
                    entity = undefined;
                    return entity;
                };
                zulu = 100;
                zulu = oscar.bind(entity)(report, zulu);
                tango['current'] = zulu;
                tango = _closure2_slot5;
                zulu = tango.set;
                mike = false;
                mike = zulu.bind(tango)(mike);
                return entity;
            };
            source = options.bind(verify)(oscar, golf);
            _closure2_slot7 = source;
            oscar = entity[report];
            yankee = sizing.bind(tango)(oscar);
            options = yankee.useAnimatedReaction;
            golf = function() { // Original name: _
                mike = _closure2_slot1;
                entity = mike.get;
                entity = entity.bind(mike)();
                return entity;
            };
            oscar = {};
            oscar['scrollPosition'] = result;
            golf['__closure'] = oscar;
            oscar = 2831463390050.0;
            golf['__workletHash'] = oscar;
            oscar = _closure1_slot8;
            golf['__initData'] = oscar;
            oscar = function(argFoo, argBar) { // Original name: T
                _fun00009: for(var _fun00010_ip = 0; ; ) switch(_fun00010_ip) {
 0:
                    options = argBar;
                    mike = global;
                    verify = mike.Math;
                    oscar = verify.max;
                    tango = _closure2_slot2;
                    zulu = argFoo;
                    report = tango - zulu;
                    zulu = _closure2_slot0;
                    golf = 2;
                    zulu = zulu / golf;
                    zulu = oscar.bind(verify)(report, zulu);
                    oscar = mike.Math;
                    report = oscar.max;
                    mike = null;
                    verify = mike != options;
                    mike = 0;
                    if(!verify) { _fun00010_ip = 72; continue _fun00009 }
 69:
                    mike = options;
 72:
                    tango = tango - mike;
                    mike = _closure2_slot0;
                    mike = mike / golf;
                    mike = report.bind(oscar)(tango, mike);
                    if(!(zulu !== mike)) { _fun00010_ip = 137; continue _fun00009 }
 94:
                    tango = _closure1_slot0;
                    zulu = _closure1_slot2;
                    mike = 6;
                    zulu = zulu[mike];
                    mike = undefined;
                    tango = tango.bind(mike)(zulu);
                    zulu = tango.runOnJS;
                    entity = _closure2_slot7;
                    entity = zulu.bind(tango)(entity);
                    entity = entity.bind(mike)();
 137:
                    entity = undefined;
                    return entity;
                }
            };
            update = {};
            update['bannerOffset'] = echo;
            update['headerHeight'] = output;
            control = entity[report];
            control = sizing.bind(tango)(control);
            control = control.runOnJS;
            update['runOnJS'] = control;
            update['checkScrolling'] = source;
            oscar['__closure'] = update;
            update = 10643233591625.0;
            oscar['__workletHash'] = update;
            update = _closure1_slot9;
            oscar['__initData'] = update;
            oscar = options.bind(yankee)(golf, oscar);
            oscar = entity[report];
            options = sizing.bind(tango)(oscar);
            golf = options.useAnimatedStyle;
            oscar = function() { // Original name: R
                _fun00011: for(var _fun00012_ip = 0; ; ) switch(_fun00012_ip) {
 0:
                    entity = global;
                    report = entity.Math;
                    zulu = report.max;
                    mike = _closure2_slot2;
                    oscar = _closure2_slot1;
                    entity = oscar.get;
                    entity = entity.bind(oscar)();
                    mike = mike - entity;
                    oscar = _closure2_slot0;
                    entity = 2;
                    entity = oscar / entity;
                    offset = zulu.bind(report)(mike, entity);
                    entity = {};
                    zulu = _closure1_slot0;
                    mike = _closure1_slot2;
                    kilo = 8;
                    mike = mike[kilo];
                    backup = undefined;
                    golf = zulu.bind(backup)(mike);
                    oscar = golf.withTiming;
                    zulu = _closure2_slot3;
                    mike = zulu.get;
                    zulu = mike.bind(zulu)();
                    mike = {};
                    foxtrot = 500;
                    mike['duration'] = foxtrot;
                    mike = oscar.bind(golf)(zulu, mike);
                    entity['opacity'] = mike;
                    zulu = {};
                    oscar = _closure2_slot5;
                    mike = oscar.get;
                    oscar = mike.bind(oscar)();
                    mike = offset;
                    if(!oscar) { _fun00012_ip = 267; continue _fun00011 }
 145:
                    romeo = _closure1_slot0;
                    yankee = _closure1_slot2;
                    report = 6;
                    oscar = yankee[report];
                    options = romeo.bind(backup)(oscar);
                    golf = options.withRepeat;
                    report = yankee[report];
                    verify = romeo.bind(backup)(report);
                    oscar = verify.withSequence;
                    report = yankee[kilo];
                    output = romeo.bind(backup)(report);
                    sizing = output.withTiming;
                    report = {};
                    report['duration'] = foxtrot;
                    report = sizing.bind(output)(offset, report);
                    yankee = yankee[kilo];
                    romeo = romeo.bind(backup)(yankee);
                    yankee = romeo.withTiming;
                    tango = _closure2_slot4;
                    offset = offset + tango;
                    tango = {};
                    tango['duration'] = foxtrot;
                    tango = yankee.bind(romeo)(offset, tango);
                    oscar = oscar.bind(verify)(report, tango);
                    report = -1;
                    tango = true;
                    mike = golf.bind(options)(oscar, report, tango);
 267:
                    zulu['translateY'] = mike;
                    mike = new Array(1);
                    mike[0] = zulu;
                    entity['transform'] = mike;
                    return entity;
                }
            };
            yankee = {};
            yankee['bannerOffset'] = echo;
            yankee['scrollPosition'] = result;
            yankee['headerHeight'] = output;
            output = 8;
            output = entity[output];
            output = sizing.bind(tango)(output);
            output = output.withTiming;
            yankee['withTiming'] = output;
            yankee['opacity'] = offset;
            yankee['shouldLoop'] = foxtrot;
            foxtrot = entity[report];
            foxtrot = sizing.bind(tango)(foxtrot);
            foxtrot = foxtrot.withRepeat;
            yankee['withRepeat'] = foxtrot;
            foxtrot = entity[report];
            foxtrot = sizing.bind(tango)(foxtrot);
            foxtrot = foxtrot.withSequence;
            yankee['withSequence'] = foxtrot;
            yankee['translateBounceOffset'] = romeo;
            oscar['__closure'] = yankee;
            yankee = 167669905565.0;
            oscar['__workletHash'] = yankee;
            yankee = _closure1_slot10;
            oscar['__initData'] = yankee;
            oscar = golf.bind(options)(oscar);
            options = verify.useEffect;
            golf = new Array(1);
            golf[0] = offset;
            mike = function() {
                entity = global;
                tango = entity.setTimeout;
                entity = undefined;
                zulu = function() {
                    zulu = _closure2_slot3;
                    mike = zulu.set;
                    entity = 1;
                    entity = mike.bind(zulu)(entity);
                    entity = undefined;
                    return entity;
                };
                mike = 500;
                mike = tango.bind(entity)(zulu, mike);
                return entity;
            };
            mike = options.bind(verify)(mike, golf);
            mike = 330;
            offset = zulu <= mike;
            zulu = _closure1_slot6;
            mike = _closure1_slot1;
            entity = entity[report];
            entity = mike.bind(tango)(entity);
            mike = entity.View;
            entity = {};
            report = _closure1_slot7;
            golf = report.tooltipContainer;
            report = new Array(3);
            report[0] = golf;
            golf = null;
            if(!offset) { _fun00008_ip = 678; continue _fun00007 }
 668:
            options = _closure1_slot7;
            golf = options.shortWidthTooltipContainer;
 678:
            report[1] = golf;
            report[2] = oscar;
            entity['style'] = report;
            golf = _closure1_slot6;
            oscar = _closure1_slot1;
            options = _closure1_slot2;
            report = 9;
            report = options[report];
            oscar = oscar.bind(tango)(report);
            report = {};
            options = _closure1_slot7;
            yankee = options.tooltip;
            report['containerStyle'] = yankee;
            yankee = options.tooltipText;
            report['labelStyle'] = yankee;
            yankee = options.arrow;
            options = new Array(2);
            options[0] = yankee;
            verify = null;
            if(!offset) { _fun00008_ip = 771; continue _fun00007 }
 761:
            offset = _closure1_slot7;
            verify = offset.shortWidthArrow;
 771:
            options[1] = verify;
            report['arrowStyle'] = options;
            echo = _closure1_slot0;
            foxtrot = _closure1_slot2;
            sizing = 10;
            options = foxtrot[sizing];
            options = echo.bind(tango)(options);
            offset = options.intl;
            verify = offset.string;
            options = foxtrot[sizing];
            options = echo.bind(tango)(options);
            options = options.t;
            options = options.UyHD4O;
            options = verify.bind(offset)(options);
            report['label'] = options;
            options = foxtrot[sizing];
            options = echo.bind(tango)(options);
            offset = options.intl;
            verify = offset.string;
            options = foxtrot[sizing];
            options = echo.bind(tango)(options);
            options = options.t;
            options = options.Q3qa4+;
            options = verify.bind(offset)(options);
            report['title'] = options;
            offset = _closure1_slot6;
            romeo = _closure1_slot1;
            yankee = 11;
            options = foxtrot[yankee];
            verify = romeo.bind(tango)(options);
            options = {};
            output = foxtrot[sizing];
            output = echo.bind(tango)(output);
            result = output.intl;
            output = result.string;
            sizing = foxtrot[sizing];
            sizing = echo.bind(tango)(sizing);
            sizing = sizing.t;
            sizing = sizing.U9PrMz;
            sizing = output.bind(result)(sizing);
            options['text'] = sizing;
            options['onPress'] = kilo;
            kilo = foxtrot[yankee];
            kilo = romeo.bind(tango)(kilo);
            kilo = kilo.Colors;
            kilo = kilo.PRIMARY;
            options['color'] = kilo;
            backup = _closure1_slot7;
            kilo = backup.closeButtonText;
            options['textStyle'] = kilo;
            backup = backup.closeButton;
            options['style'] = backup;
            yankee = foxtrot[yankee];
            yankee = romeo.bind(tango)(yankee);
            yankee = yankee.Sizes;
            yankee = yankee.SMALL;
            options['size'] = yankee;
            yankee = true;
            options['shrink'] = yankee;
            options = offset.bind(tango)(verify, options);
            report['children'] = options;
            report = golf.bind(tango)(oscar, report);
            entity['children'] = report;
            entity = zulu.bind(tango)(mike, entity);
            return entity;
        }
    };
    zulu['PremiumGuildSubscriptionPromptTooltipFlashList'] = mike;
    return entity;
})();