// app/modules/notifications/NotificationConstants.tsx
export default (function(_, argBar, __, ___, ____, argFred, argPlugh) {
    zulu = argFred;
    entity = global;
    report = entity.Object;
    tango = report.defineProperty;
    mike = {};
    entity = true;
    mike['value'] = entity;
    entity = '__esModule';
    entity = tango.bind(report)(zulu, entity, mike);
    tango = {};
    mike = 16;
    tango['USE_NEW_NOTIFICATIONS'] = mike;
    entity = 'USE_NEW_NOTIFICATIONS';
    tango[mike] = entity;
    mike = 32;
    tango['MENTION_ON_ALL_MESSAGES'] = mike;
    entity = 'MENTION_ON_ALL_MESSAGES';
    tango[mike] = entity;
    mike = {};
    entity = 'guild';
    mike['GUILD'] = entity;
    entity = 'channel';
    mike['CHANNEL'] = entity;
    entity = 'account';
    mike['ACCOUNT'] = entity;
    report = argPlugh;
    entity = 0;
    oscar = report[entity];
    report = argBar;
    entity = undefined;
    golf = report.bind(entity)(oscar);
    oscar = golf.fileFinishedImporting;
    report = 'modules/notifications/NotificationConstants.tsx';
    report = oscar.bind(golf)(report);
    zulu['AccountNotificationFlags'] = tango;
    zulu['NotificationSettingsUpdateType'] = mike;
    return entity;
})();