// app/modules/main_tabs_v2/native/shared_components/ScrollTargets.tsx
export default (function(argFoo, argBar, _, argCor, __, argFre, argPlu) {
    golfie = argBar;
    zuuluu = argFre;
    option = argPlu;
    var _closure1_slot0 = golfie;
    var _closure1_slot1 = option;
    entity = function(argFoo, argBar) { // Original name: useTextFieldForwardedComponent
        entity = function() { // Original name: useTextFieldForwardedRef
            report = _closure1_slot2;
            tangon = report.useRef;
            zuuluu = null;
            zuuluu = tangon.bind(report)(zuuluu);
            var _closure3_slot0 = zuuluu;
            report = _closure1_slot2;
            tangon = report.useMemo;
            michal = new Array(1);
            michal[0] = zuuluu;
            entity = function() {
                entity = {};
                zuuluu = function() { // Original name: blur
                    entity = _closure3_slot0;
                    michal = entity.current;
                    entity = michal.blur;
                    entity = entity.bind(michal)();
                    return entity;
                };
                entity['blur'] = zuuluu;
                zuuluu = function() { // Original name: focus
                    entity = _closure3_slot0;
                    michal = entity.current;
                    entity = michal.focus;
                    entity = entity.bind(michal)();
                    return entity;
                };
                entity['focus'] = zuuluu;
                zuuluu = function() { // Original name: isFocused
                    entity = _closure3_slot0;
                    michal = entity.current;
                    entity = michal.isFocused;
                    entity = entity.bind(michal)();
                    return entity;
                };
                entity['isFocused'] = zuuluu;
                zuuluu = function(argFoo) { // Original name: setText
                    entity = _closure3_slot0;
                    zuuluu = entity.current;
                    michal = zuuluu.setText;
                    entity = argFoo;
                    entity = michal.bind(zuuluu)(entity);
                    return entity;
                };
                entity['setText'] = zuuluu;
                michal = function() { // Original name: getText
                    entity = _closure3_slot0;
                    michal = entity.current;
                    entity = michal.getText;
                    entity = entity.bind(michal)();
                    return entity;
                };
                entity['getText'] = michal;
                return entity;
            };
            michal = tangon.bind(report)(entity, michal);
            entity = {};
            entity['textAreaRef'] = zuuluu;
            entity['textAreaApi'] = michal;
            return entity;
        };
        tangon = undefined;
        entity = entity.bind(tangon)();
        oscard = entity.textAreaRef;
        entity = entity.textAreaApi;
        var _closure2_slot0 = entity;
        entity = function() { // Original name: useViewForwardedRef
            report = _closure1_slot2;
            tangon = report.useRef;
            zuuluu = null;
            zuuluu = tangon.bind(report)(zuuluu);
            var _closure3_slot0 = zuuluu;
            report = _closure1_slot2;
            tangon = report.useMemo;
            michal = new Array(1);
            michal[0] = zuuluu;
            entity = function() {
                entity = {};
                michal = function(argFoo) { // Original name: measure
                    entity = _closure3_slot0;
                    zuuluu = entity.current;
                    michal = zuuluu.measure;
                    entity = argFoo;
                    entity = michal.bind(zuuluu)(entity);
                    return entity;
                };
                entity['measure'] = michal;
                return entity;
            };
            michal = tangon.bind(report)(entity, michal);
            entity = {};
            entity['viewRef'] = zuuluu;
            entity['viewApi'] = michal;
            return entity;
        };
        entity = entity.bind(tangon)();
        report = entity.viewRef;
        entity = entity.viewApi;
        var _closure2_slot1 = entity;
        option = _closure1_slot2;
        golfie = option.useImperativeHandle;
        zuuluu = argFoo;
        michal = function() {
            entity = {};
            tangon = _closure2_slot0;
            report = entity;
            zuuluu = copyDataProperties(report, tangon);
            tangon = _closure2_slot1;
            report = entity;
            michal = copyDataProperties(report, tangon);
            return entity;
        };
        michal = golfie.bind(option)(zuuluu, michal);
        zuuluu = _closure1_slot4;
        michal = _closure1_slot3;
        entity = {};
        entity['ref'] = report;
        report = argBar;
        report = report.bind(tangon)(oscard);
        entity['children'] = report;
        entity = zuuluu.bind(tangon)(michal, entity);
        return entity;
    };
    var _closure1_slot5 = entity;
    entity = global;
    oscard = entity.Object;
    report = oscard.defineProperty;
    tangon = {};
    entity = true;
    tangon['value'] = entity;
    entity = '__esModule';
    entity = report.bind(oscard)(zuuluu, entity, tangon);
    entity = 0;
    report = option[entity];
    tangon = argCor;
    entity = undefined;
    verify = tangon.bind(entity)(report);
    var _closure1_slot2 = verify;
    tangon = 1;
    tangon = option[tangon];
    tangon = golfie.bind(entity)(tangon);
    tangon = tangon.View;
    var _closure1_slot3 = tangon;
    tangon = 2;
    tangon = option[tangon];
    tangon = golfie.bind(entity)(tangon);
    tangon = tangon.jsx;
    var _closure1_slot4 = tangon;
    report = verify.forwardRef;
    tangon = function(argFoo, argBar) {
        michal = argFoo;
        var _closure2_slot0 = michal;
        tangon = _closure1_slot5;
        zuuluu = undefined;
        michal = argBar;
        entity = function(argFoo) {
            tangon = _closure1_slot4;
            michal = _closure1_slot0;
            zuuluu = _closure1_slot1;
            entity = 3;
            entity = zuuluu[entity];
            zuuluu = undefined;
            entity = michal.bind(zuuluu)(entity);
            michal = entity.SearchField;
            entity = {};
            report = argFoo;
            entity['ref'] = report;
            oscard = _closure2_slot0;
            golfie = entity;
            report = copyDataProperties(golfie, oscard);
            entity = tangon.bind(zuuluu)(michal, entity);
            return entity;
        };
        entity = tangon.bind(zuuluu)(michal, entity);
        return entity;
    };
    report = report.bind(verify)(tangon);
    oscard = verify.forwardRef;
    tangon = function(argFoo, argBar) {
        michal = argFoo;
        var _closure2_slot0 = michal;
        tangon = _closure1_slot5;
        zuuluu = undefined;
        michal = argBar;
        entity = function(argFoo) {
            tangon = _closure1_slot4;
            michal = _closure1_slot0;
            zuuluu = _closure1_slot1;
            entity = 4;
            entity = zuuluu[entity];
            zuuluu = undefined;
            entity = michal.bind(zuuluu)(entity);
            michal = entity.TextInput;
            entity = {};
            report = argFoo;
            entity['ref'] = report;
            oscard = _closure2_slot0;
            golfie = entity;
            report = copyDataProperties(golfie, oscard);
            entity = tangon.bind(zuuluu)(michal, entity);
            return entity;
        };
        entity = tangon.bind(zuuluu)(michal, entity);
        return entity;
    };
    tangon = oscard.bind(verify)(tangon);
    oscard = verify.forwardRef;
    michal = function(argFoo, argBar) {
        michal = argFoo;
        var _closure2_slot0 = michal;
        tangon = _closure1_slot5;
        zuuluu = undefined;
        michal = argBar;
        entity = function(argFoo) {
            tangon = _closure1_slot4;
            michal = _closure1_slot0;
            zuuluu = _closure1_slot1;
            entity = 5;
            entity = zuuluu[entity];
            zuuluu = undefined;
            entity = michal.bind(zuuluu)(entity);
            michal = entity.TextArea;
            entity = {};
            report = argFoo;
            entity['ref'] = report;
            oscard = _closure2_slot0;
            golfie = entity;
            report = copyDataProperties(golfie, oscard);
            entity = tangon.bind(zuuluu)(michal, entity);
            return entity;
        };
        entity = tangon.bind(zuuluu)(michal, entity);
        return entity;
    };
    michal = oscard.bind(verify)(michal);
    oscard = 6;
    oscard = option[oscard];
    option = golfie.bind(entity)(oscard);
    golfie = option.fileFinishedImporting;
    oscard = 'modules/main_tabs_v2/native/shared_components/ScrollTargets.tsx';
    oscard = golfie.bind(option)(oscard);
    zuuluu['SearchFieldScrollTarget'] = report;
    zuuluu['TextInputScrollTarget'] = tangon;
    zuuluu['TextAreaScrollTarget'] = michal;
    return entity;
})();