// app/modules/user_settings/native/mfa_modal_flow/TwoFASetupModalActionCreators.tsx
export default (function(_, argBar, argBaz, __, ___, argFre, argPlu) {
    report = argBar;
    zuuluu = argFre;
    tangon = argPlu;
    var _closure1_slot0 = report;
    michal = argBaz;
    var _closure1_slot1 = michal;
    var _closure1_slot2 = tangon;
    michal = global;
    option = michal.Object;
    golfie = option.defineProperty;
    oscard = {};
    michal = true;
    oscard['value'] = michal;
    michal = '__esModule';
    michal = golfie.bind(option)(zuuluu, michal, oscard);
    michal = {};
    oscard = function() { // Original name: open
        report = _closure1_slot1;
        michal = _closure1_slot2;
        entity = 0;
        tangon = michal[entity];
        entity = undefined;
        oscard = report.bind(entity)(tangon);
        report = oscard.pushLazy;
        tangon = _closure1_slot0;
        zuuluu = 2;
        zuuluu = michal[zuuluu];
        tangon = tangon.bind(entity)(zuuluu);
        zuuluu = 1;
        zuuluu = michal[zuuluu];
        michal = michal.paths;
        tangon = tangon.bind(entity)(zuuluu, michal);
        zuuluu = {};
        michal = 'TWO_FA_SETUP_MODAL_KEY';
        michal = report.bind(oscard)(tangon, zuuluu, michal);
        return entity;
    };
    michal['open'] = oscard;
    entity = function() { // Original name: close
        zuuluu = _closure1_slot1;
        michal = _closure1_slot2;
        entity = 0;
        michal = michal[entity];
        entity = undefined;
        tangon = zuuluu.bind(entity)(michal);
        zuuluu = tangon.popWithKey;
        michal = 'TWO_FA_SETUP_MODAL_KEY';
        michal = zuuluu.bind(tangon)(michal);
        return entity;
    };
    michal['close'] = entity;
    entity = 3;
    tangon = tangon[entity];
    entity = undefined;
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/user_settings/native/mfa_modal_flow/TwoFASetupModalActionCreators.tsx';
    tangon = report.bind(oscard)(tangon);
    zuuluu['default'] = michal;
    return entity;
})();