// app/modules/auth/native/components/RegisterPassword.tsx
export default (function(native1, native2, native3, native4, native5, native6, native7) {
    var5 = native2;
    var7 = native3;
    var3 = native6;
    var6 = native7;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var7;
    var _closure1_slot2 = var6;
    var1 = global;
    var9 = var1.Object;
    var8 = var9.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var8.bind(var9)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var7.bind(var1)(var4);
    var _closure1_slot3 = var4;
    var10 = 1;
    var4 = var6[var10];
    var4 = var7.bind(var1)(var4);
    var _closure1_slot4 = var4;
    var4 = 2;
    var7 = var6[var4];
    var4 = native4;
    var4 = var4.bind(var1)(var7);
    var _closure1_slot5 = var4;
    var4 = 3;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.ScrollView;
    var _closure1_slot6 = var4;
    var11 = 4;
    var4 = var6[var11];
    var4 = var5.bind(var1)(var4);
    var7 = var4.setRegistrationErrors;
    var _closure1_slot7 = var7;
    var7 = var4.updateRegistrationOptions;
    var _closure1_slot8 = var7;
    var4 = var4.useRegistrationUIStore;
    var _closure1_slot9 = var4;
    var4 = 5;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var7 = var4.RegisterTransitionSteps;
    var _closure1_slot10 = var7;
    var4 = var4.RegistrationTransitionActionTypes;
    var _closure1_slot11 = var4;
    var4 = 6;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.AuthStates;
    var _closure1_slot12 = var4;
    var4 = 7;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var7 = var4.jsx;
    var _closure1_slot13 = var7;
    var4 = var4.jsxs;
    var _closure1_slot14 = var4;
    var4 = 8;
    var4 = var6[var4];
    var8 = var5.bind(var1)(var4);
    var7 = var8.createStyles;
    var4 = {};
    var9 = {};
    var12 = 24;
    var9['marginTop'] = var12;
    var4['password'] = var9;
    var9 = {'marginTop': 24, 'marginBottom': 50};
    var4['button'] = var9;
    var9 = {};
    var9['marginTop'] = var11;
    var4['errors'] = var9;
    var9 = {'marginBottom': 8, 'width': '90%'};
    var4['status'] = var9;
    var9 = {};
    var9['flex'] = var10;
    var4['page'] = var9;
    var4 = var7.bind(var8)(var4);
    var _closure1_slot15 = var4;
    var4 = {};
    var7 = 9;
    var8 = var6[var7];
    var8 = var5.bind(var1)(var8);
    var9 = var8.LinearTransition;
    var8 = var9.easing;
    var10 = var6[var7];
    var10 = var5.bind(var1)(var10);
    var11 = var10.Easing;
    var10 = var11.inOut;
    var7 = var6[var7];
    var7 = var5.bind(var1)(var7);
    var7 = var7.Easing;
    var7 = var7.quad;
    var7 = var10.bind(var11)(var7);
    var9 = var8.bind(var9)(var7);
    var8 = var9.duration;
    var7 = 300;
    var7 = var8.bind(var9)(var7);
    var4['layout'] = var7;
    var _closure1_slot16 = var4;
    var4 = 22;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/auth/native/components/RegisterPassword.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function RegisterPassword() {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
 0:
            var18 = function handleSubmit() {
                var1 = undefined;
                var4 = _closure2_slot6;
                var3 = var4.apply;
                var1 = arguments;
                var2 = var1;
                var1 = this;
                var1 = var3.bind(var4)(var1, var2);
                return var1;
            };
            var2 = function _handleSubmit() {
                var4 = undefined;
                var1 = undefined;
                var3 = _closure1_slot3;
                var2 = function* () {
                    var1 = function* anon_0_() {
                        _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
 0:
                            StartGenerator();
                            ResumeGenerator(result_out_reg=0, return_bool_out_reg=1);
                            if(var2) { _fun0002_ip = 319; continue _fun0002 }
 10:
                            var5 = undefined;
                            var8 = undefined;
                            var4 = _closure2_slot0;
                            var2 = {};
                            var6 = _closure1_slot10;
                            var6 = var6.PASSWORD;
                            var2['step'] = var6;
                            var6 = _closure1_slot11;
                            var6 = var6.SUBMITTED;
                            var2['actionType'] = var6;
                            var2 = var4.bind(var5)(var2);
 61: // try_start_0
                            var4 = _closure2_slot2;
                            var2 = true;
                            var2 = var4.bind(var5)(var2);
                            var2 = _closure2_slot5;
                            var2 = var2.bind(var5)();
                            SaveGenerator(address=84);
 82:
                            return var2;
 84:
                            ResumeGenerator(result_out_reg=1, return_bool_out_reg=3);
                            if(var4) { _fun0002_ip = 290; continue _fun0002 }
 93:
                            var8 = var2;
                            var4 = null;
                            if(!(var4 == var2)) { _fun0002_ip = 202; continue _fun0002 }
 102: // try_end0
                            var6 = _closure2_slot2;
                            var4 = false;
                            var4 = var6.bind(var5)(var4);
                            var6 = {};
                            var13 = _closure2_slot1;
                            var14 = var6;
                            var4 = copyDataProperties(var14, var13);
                            var9 = _closure2_slot4;
                            var4 = 'password';
                            var6[var4] = var9;
                            var4 = _closure1_slot8;
                            var4 = var4.bind(var5)(var6);
                            var6 = _closure1_slot0;
                            var9 = _closure1_slot2;
                            var4 = 14;
                            var4 = var9[var4];
                            var11 = var6.bind(var5)(var4);
                            var10 = var11.handleNextOrSubmitRegistration;
                            var4 = _closure1_slot12;
                            var9 = var4.REGISTER_PASSWORD;
                            var6 = _closure2_slot3;
                            var4 = _closure2_slot0;
                            var4 = var10.bind(var11)(var9, var6, var4);
                            return var5;
 202: // try_start_1
                            var6 = _closure1_slot7;
                            var4 = {};
                            var4['password'] = var8;
                            var4 = var6.bind(var5)(var4);
                            var6 = _closure2_slot0;
                            var4 = {};
                            var8 = _closure1_slot10;
                            var8 = var8.PASSWORD;
                            var4['step'] = var8;
                            var7 = _closure1_slot11;
                            var7 = var7.INPUT_ERROR;
                            var4['actionType'] = var7;
                            var7 = ['password'];
                            var4['details'] = var7;
                            var4 = var6.bind(var5)(var4);
 274: // try_end1
                            var7 = _closure2_slot2;
                            var6 = false;
                            var6 = var7.bind(var5)(var6);
                            var4 = undefined;
                            return var4;
 290:
                            var6 = _closure2_slot2;
                            var4 = false;
                            var4 = var6.bind(var5)(var4);
                            return var2;
 304: // catch_target0 // catch_target1
                            CatchBlockStart(arg_register=1);
                            var4 = _closure2_slot2;
                            var3 = false;
                            var3 = var4.bind(var5)(var3);
                            throw var2;
 319:
                            return var1;
                        }
                    };
                    return var1;
                };
                var4 = var3.bind(var4)(var2);
                _closure2_slot6 = var4;
                var3 = var4.apply;
                var1 = arguments;
                var2 = var1;
                var1 = this;
                var1 = var3.bind(var4)(var1, var2);
                return var1;
            };
            var _closure2_slot6 = var2;
            var2 = _closure1_slot15;
            var4 = undefined;
            var20 = var2.bind(var4)();
            var5 = _closure1_slot5;
            var3 = var5.useContext;
            var15 = _closure1_slot0;
            var23 = _closure1_slot2;
            var2 = 10;
            var2 = var23[var2];
            var2 = var15.bind(var4)(var2);
            var2 = var2.TrackRegistrationContext;
            var6 = var3.bind(var5)(var2);
            var _closure2_slot0 = var6;
            var3 = _closure1_slot9;
            var2 = function(arg1) {
                var1 = arg1;
                var1 = var1.registrationOptions;
                return var1;
            };
            var2 = var3.bind(var4)(var2);
            var _closure2_slot1 = var2;
            var2 = function(arg1) {
                var1 = arg1;
                var1 = var1.submitting;
                return var1;
            };
            var21 = var3.bind(var4)(var2);
            var7 = var5.useState;
            var2 = false;
            var8 = var7.bind(var5)(var2);
            var7 = _closure1_slot4;
            var2 = 2;
            var2 = var7.bind(var4)(var8, var2);
            var7 = 0;
            var22 = var2[var7];
            var11 = 1;
            var2 = var2[var11];
            var _closure2_slot2 = var2;
            var2 = function(arg1) {
                var1 = arg1;
                var1 = var1.errors;
                return var1;
            };
            var19 = var3.bind(var4)(var2);
            var2 = 11;
            var2 = var23[var2];
            var3 = var15.bind(var4)(var2);
            var2 = var3.useNavigation;
            var2 = var2.bind(var3)();
            var _closure2_slot3 = var2;
            var2 = 12;
            var2 = var23[var2];
            var3 = var15.bind(var4)(var2);
            var2 = var3.usePasswordRegistrationStep;
            var2 = var2.bind(var3)();
            var29 = var2.password;
            var _closure2_slot4 = var29;
            var28 = var2.setPassword;
            var27 = var2.passwordScore;
            var17 = var2.preventSubmitPassword;
            var2 = var2.validatePassword;
            var _closure2_slot5 = var2;
            var12 = _closure1_slot1;
            var2 = 13;
            var2 = var23[var2];
            var7 = var12.bind(var4)(var2);
            var2 = 14;
            var2 = var23[var2];
            var9 = var15.bind(var4)(var2);
            var8 = var9.getPreviousRegistrationTransitionStep;
            var2 = _closure1_slot12;
            var3 = var2.REGISTER_PASSWORD;
            var3 = var8.bind(var9)(var3);
            var3 = var7.bind(var4)(var3);
            var3 = 15;
            var3 = var23[var3];
            var3 = var12.bind(var4)(var3);
            var2 = var2.REGISTER_PASSWORD;
            var2 = var3.bind(var4)(var2);
            var3 = var5.useEffect;
            var2 = new Array(1);
            var2[0] = var6;
            var1 = function() {
                var3 = _closure2_slot0;
                var2 = {};
                var4 = _closure1_slot10;
                var4 = var4.PASSWORD;
                var2['step'] = var4;
                var1 = _closure1_slot11;
                var1 = var1.VIEWED;
                var2['actionType'] = var1;
                var1 = undefined;
                var2 = var3.bind(var1)(var2);
                return var1;
            };
            var1 = var3.bind(var5)(var1, var2);
            var3 = _closure1_slot13;
            var1 = 16;
            var1 = var23[var1];
            var2 = var12.bind(var4)(var1);
            var1 = {};
            var5 = var20.page;
            var1['style'] = var5;
            var5 = 17;
            var5 = var23[var5];
            var6 = var12.bind(var4)(var5);
            var5 = {};
            var25 = 18;
            var7 = var23[var25];
            var7 = var15.bind(var4)(var7);
            var9 = var7.intl;
            var8 = var9.string;
            var7 = var23[var25];
            var7 = var15.bind(var4)(var7);
            var7 = var7.t;
            var7 = var7.PTHakp;
            var7 = var8.bind(var9)(var7);
            var5['headerText'] = var7;
            var9 = _closure1_slot14;
            var8 = _closure1_slot6;
            var7 = {};
            var10 = {};
            var10['flexGrow'] = var11;
            var7['contentContainerStyle'] = var10;
            var10 = 'handled';
            var7['keyboardShouldPersistTaps'] = var10;
            var11 = 9;
            var10 = var23[var11];
            var10 = var12.bind(var4)(var10);
            var24 = var10.View;
            var10 = {};
            var13 = var20.password;
            var10['style'] = var13;
            var13 = _closure1_slot16;
            var31 = var10;
            var30 = var13;
            var14 = copyDataProperties(var31, var30);
            var14 = 19;
            var14 = var23[var14];
            var14 = var15.bind(var4)(var14);
            var26 = var14.RegisterPasswordInput;
            var14 = {};
            var14['password'] = var29;
            var14['onPasswordChange'] = var28;
            var14['onSubmitEditing'] = var18;
            var14['passwordScore'] = var27;
            var27 = true;
            var14['autoFocus'] = var27;
            var26 = var3.bind(var4)(var26, var14);
            var14 = 'children';
            var10[var14] = var26;
            var24 = var3.bind(var4)(var24, var10);
            var10 = new Array(2);
            var10[0] = var24;
            var11 = var23[var11];
            var11 = var12.bind(var4)(var11);
            var12 = var11.View;
            var11 = {};
            var24 = var20.button;
            var11['style'] = var24;
            var31 = var11;
            var30 = var13;
            var13 = copyDataProperties(var31, var30);
            var13 = 20;
            var13 = var23[var13];
            var13 = var15.bind(var4)(var13);
            var15 = var13.Button;
            var13 = {};
            var23 = 'lg';
            var13['size'] = var23;
            if(var21) { _fun0001_ip = 669; continue _fun0001 }
 666:
            var21 = var22;
 669:
            var13['loading'] = var21;
            var24 = _closure1_slot0;
            var21 = _closure1_slot2;
            var22 = var21[var25];
            var22 = var24.bind(var4)(var22);
            var23 = var22.intl;
            var22 = var23.string;
            var21 = var21[var25];
            var21 = var24.bind(var4)(var21);
            var21 = var21.t;
            var21 = var21.PDTjLC;
            var21 = var22.bind(var23)(var21);
            var13['text'] = var21;
            var13['onPress'] = var18;
            var13['disabled'] = var17;
            var15 = var3.bind(var4)(var15, var13);
            var13 = new Array(2);
            var13[0] = var15;
            var15 = var19.message;
            var21 = null;
            var17 = var21 != var15;
            var15 = null;
            if(!var17) { _fun0001_ip = 834; continue _fun0001 }
 768:
            var18 = var19.message;
            var17 = '';
            var15 = null;
            if(!(var17 !== var18)) { _fun0001_ip = 834; continue _fun0001 }
 783:
            var18 = _closure1_slot13;
            var17 = _closure1_slot1;
            var21 = _closure1_slot2;
            var16 = 21;
            var16 = var21[var16];
            var17 = var17.bind(var4)(var16);
            var16 = {};
            var20 = var20.errors;
            var16['style'] = var20;
            var19 = var19.message;
            var16['children'] = var19;
            var15 = var18.bind(var4)(var17, var16);
 834:
            var13[1] = var15;
            var11[var14] = var13;
            var11 = var9.bind(var4)(var12, var11);
            var10[1] = var11;
            var7['children'] = var10;
            var7 = var9.bind(var4)(var8, var7);
            var5['children'] = var7;
            var5 = var3.bind(var4)(var6, var5);
            var1['children'] = var5;
            var1 = var3.bind(var4)(var2, var1);
            return var1;
        }
    };
    var3['default'] = var2;
    return var1;
})();