// app/modules/quests/native/VideoQuestModal/VideoQuestModal.tsx
export default (function(argFoo, argBar, argBaz, argCor, _, argFre, argPlu) {
    oscard = argBar;
    kiloes = argBaz;
    zuuluu = argFre;
    golfie = argPlu;
    var _closure1_slot0 = oscard;
    var _closure1_slot1 = kiloes;
    var _closure1_slot2 = golfie;
    entity = global;
    option = entity.Object;
    report = option.defineProperty;
    michal = {};
    entity = true;
    michal['value'] = entity;
    entity = '__esModule';
    entity = report.bind(option)(zuuluu, entity, michal);
    verify = 0;
    michal = golfie[verify];
    entity = undefined;
    michal = kiloes.bind(entity)(michal);
    var _closure1_slot3 = michal;
    foxtra = 1;
    report = golfie[foxtra];
    michal = argCor;
    option = michal.bind(entity)(report);
    var _closure1_slot4 = option;
    output = 2;
    michal = golfie[output];
    michal = oscard.bind(entity)(michal);
    report = michal.View;
    var _closure1_slot5 = report;
    sizing = michal.StyleSheet;
    michal = michal.AppState;
    var _closure1_slot6 = michal;
    michal = 3;
    michal = golfie[michal];
    michal = oscard.bind(entity)(michal);
    michal = michal.AnalyticEvents;
    var _closure1_slot7 = michal;
    michal = 4;
    michal = golfie[michal];
    michal = oscard.bind(entity)(michal);
    report = michal.jsx;
    var _closure1_slot8 = report;
    michal = michal.jsxs;
    var _closure1_slot9 = michal;
    michal = {'mass': 1.9, 'damping': 18, 'stiffness': 80, 'overshootClamping': true};
    var _closure1_slot10 = michal;
    michal = {};
    michal['WATCH_VIDEO'] = verify;
    report = 'WATCH_VIDEO';
    michal[verify] = report;
    michal['POST_WATCH_VIDEO'] = foxtra;
    report = 'POST_WATCH_VIDEO';
    michal[foxtra] = report;
    var _closure1_slot11 = michal;
    report = 5;
    report = golfie[report];
    offset = oscard.bind(entity)(report);
    verify = offset.createStyles;
    report = {};
    yankee = {'flexDirection': 'column', 'flexGrow': 1, 'flexShrink': 1, 'zIndex': 1};
    report['wrapper'] = yankee;
    yankee = {};
    yankee['flex'] = foxtra;
    report['contentWrapper'] = yankee;
    yankee = {};
    source = sizing.absoluteFillObject;
    ctrled = yankee;
    romeon = copyDataProperties(ctrled, source);
    romeon = 6;
    backup = golfie[romeon];
    backup = kiloes.bind(entity)(backup);
    backup = backup.radii;
    result = backup.lg;
    backup = 'borderRadius';
    yankee[backup] = result;
    result = golfie[romeon];
    result = kiloes.bind(entity)(result);
    result = result.colors;
    echoed = result.BG_BASE_TERTIARY;
    result = 'backgroundColor';
    yankee[result] = echoed;
    report['contentBackground'] = yankee;
    yankee = {};
    yankee['zIndex'] = output;
    report['modalContentWrapper'] = yankee;
    yankee = {};
    source = sizing.absoluteFillObject;
    ctrled = yankee;
    sizing = copyDataProperties(ctrled, source);
    romeon = golfie[romeon];
    romeon = kiloes.bind(entity)(romeon);
    romeon = romeon.radii;
    romeon = romeon.lg;
    yankee[backup] = romeon;
    romeon = 'flex';
    yankee[romeon] = foxtra;
    backup = 'hidden';
    romeon = 'overflow';
    yankee[romeon] = backup;
    backup = 'none';
    romeon = 'pointerEvents';
    yankee[romeon] = backup;
    romeon = 'zIndex';
    yankee[romeon] = foxtra;
    report['backgroundWrapper'] = yankee;
    report = verify.bind(offset)(report);
    var _closure1_slot12 = report;
    report = {};
    verify = 'function VideoQuestModalTsx1(){const{withSpring,clamp,postWatchAnimationState,BACKGROUND_ENTRANCE_ANIMATION_SPRING_CONFIG,interpolate,CLOUDS_BACKGROUND_INVISIBLE_OFFSET_Y}=this.__closure;return{opacity:withSpring(clamp(postWatchAnimationState.get(),0,1),BACKGROUND_ENTRANCE_ANIMATION_SPRING_CONFIG),transform:[{translateY:withSpring(interpolate(postWatchAnimationState.get(),[0,1],[CLOUDS_BACKGROUND_INVISIBLE_OFFSET_Y,0]),BACKGROUND_ENTRANCE_ANIMATION_SPRING_CONFIG)}]};}';
    report['code'] = verify;
    var _closure1_slot13 = report;
    report = {};
    verify = 'function VideoQuestModalTsx2(){const{withSpring,interpolate,postWatchAnimationState,safeAreaInsets,BACKGROUND_ENTRANCE_ANIMATION_SPRING_CONFIG}=this.__closure;return{transform:[{translateY:withSpring(interpolate(postWatchAnimationState.get(),[0,1],[safeAreaInsets.top,0]),BACKGROUND_ENTRANCE_ANIMATION_SPRING_CONFIG)}],opacity:withSpring(postWatchAnimationState.get(),BACKGROUND_ENTRANCE_ANIMATION_SPRING_CONFIG)};}';
    report['code'] = verify;
    var _closure1_slot14 = report;
    verify = option.memo;
    report = function(argFoo) {
        _fun00001: for(var _fun00002_ip = 0; ; ) switch(_fun00002_ip) {
 0:
            michal = argFoo;
            echoed = michal.onClose;
            var _closure2_slot0 = echoed;
            golfie = michal.initialStep;
            var _closure2_slot1 = golfie;
            output = michal.sourceQuestContent;
            var _closure2_slot2 = output;
            zuuluu = _closure1_slot0;
            tangon = _closure1_slot2;
            michal = 7;
            michal = tangon[michal];
            tangon = undefined;
            zuuluu = zuuluu.bind(tangon)(michal);
            michal = zuuluu.useVideoQuestModalContext;
            michal = michal.bind(zuuluu)();
            zuuluu = michal.quest;
            var _closure2_slot3 = zuuluu;
            michal = michal.videoSessionId;
            var _closure2_slot4 = michal;
            oscard = zuuluu.userStatus;
            verify = null;
            option = verify == oscard;
            report = undefined;
            if(option) { _fun00002_ip = 113; continue _fun00001 }
 107:
            report = oscard.completedAt;
 113:
            yankee = verify != report;
            var _closure2_slot5 = yankee;
            option = _closure1_slot4;
            oscard = option.useState;
            report = golfie;
            if(!(verify == report)) { _fun00002_ip = 161; continue _fun00001 }
 137:
            offset = _closure1_slot11;
            if(yankee) { _fun00002_ip = 152; continue _fun00001 }
 144:
            verify = offset.WATCH_VIDEO;
            _fun00002_ip = 158; continue _fun00001;
 152:
            verify = offset.POST_WATCH_VIDEO;
 158:
            report = verify;
 161:
            report = oscard.bind(option)(report);
            romeon = _closure1_slot3;
            verify = 2;
            option = romeon.bind(tangon)(report, verify);
            report = 0;
            kiloes = option[report];
            var _closure2_slot6 = kiloes;
            oscard = 1;
            option = option[oscard];
            var _closure2_slot7 = option;
            offset = _closure1_slot4;
            foxtra = offset.useState;
            option = false;
            option = foxtra.bind(offset)(option);
            option = romeon.bind(tangon)(option, verify);
            vacuum = option[report];
            option = option[oscard];
            var _closure2_slot8 = option;
            option = offset.useCallback;
            verify = zuuluu.id;
            zuuluu = new Array(3);
            zuuluu[0] = verify;
            zuuluu[1] = michal;
            zuuluu[2] = output;
            michal = function(argFoo) {
                _fun00003: for(var _fun00004_ip = 0; ; ) switch(_fun00004_ip) {
 0:
                    oscard = argFoo;
                    zuuluu = _closure1_slot0;
                    michal = _closure1_slot2;
                    entity = 8;
                    michal = michal[entity];
                    entity = undefined;
                    report = zuuluu.bind(entity)(michal);
                    tangon = report.lockOrientation;
                    if(oscard) { _fun00004_ip = 51; continue _fun00003 }
 37:
                    zuuluu = 'PORTRAIT';
                    michal = true;
                    michal = tangon.bind(report)(zuuluu, michal);
                    _fun00004_ip = 63; continue _fun00003;
 51:
                    zuuluu = 'LANDSCAPE';
                    michal = true;
                    michal = tangon.bind(report)(zuuluu, michal);
 63:
                    michal = _closure2_slot8;
                    michal = michal.bind(entity)(oscard);
                    zuuluu = _closure1_slot0;
                    tangon = _closure1_slot2;
                    michal = 9;
                    michal = tangon[michal];
                    tangon = zuuluu.bind(entity)(michal);
                    zuuluu = tangon.trackQuestEvent;
                    michal = {};
                    option = _closure2_slot3;
                    option = option.id;
                    michal['questId'] = option;
                    golfie = _closure1_slot7;
                    if(oscard) { _fun00004_ip = 132; continue _fun00003 }
 124:
                    oscard = golfie.QUEST_VIDEO_FULLSCREEN_EXITED;
                    _fun00004_ip = 138; continue _fun00003;
 132:
                    oscard = golfie.QUEST_VIDEO_FULLSCREEN_ENTERED;
 138:
                    michal['event'] = oscard;
                    oscard = {};
                    golfie = _closure2_slot4;
                    oscard['video_session_id'] = golfie;
                    michal['properties'] = oscard;
                    report = _closure2_slot2;
                    michal['sourceQuestContent'] = report;
                    michal = zuuluu.bind(tangon)(michal);
                    return entity;
                }
            };
            source = option.bind(offset)(michal, zuuluu);
            var _closure2_slot9 = source;
            verify = offset.useContext;
            zuuluu = _closure1_slot0;
            michal = _closure1_slot2;
            option = 10;
            option = michal[option];
            option = zuuluu.bind(tangon)(option);
            option = option.QuestDockGestureContext;
            option = verify.bind(offset)(option);
            verify = option.windowDimensions;
            option = _closure1_slot12;
            romeon = option.bind(tangon)();
            foxtra = _closure1_slot1;
            option = 11;
            option = michal[option];
            option = foxtra.bind(tangon)(option);
            option = option.bind(tangon)(verify);
            sizing = option.height;
            foxtra = offset.useEffect;
            verify = new Array(2);
            verify[0] = echoed;
            verify[1] = kiloes;
            option = function() {
                _fun00005: for(var _fun00006_ip = 0; ; ) switch(_fun00006_ip) {
 0:
                    report = _closure1_slot0;
                    tangon = _closure1_slot2;
                    zuuluu = 12;
                    tangon = tangon[zuuluu];
                    zuuluu = undefined;
                    report = report.bind(zuuluu)(tangon);
                    tangon = report.isIOS;
                    tangon = tangon.bind(report)();
                    if(!tangon) { _fun00006_ip = 61; continue _fun00005 }
 40:
                    report = _closure2_slot6;
                    tangon = _closure1_slot11;
                    tangon = tangon.WATCH_VIDEO;
                    if(!(report !== tangon)) { _fun00006_ip = 63; continue _fun00005 }
 61:
                    return zuuluu;
 63:
                    report = _closure1_slot6;
                    tangon = report.addEventListener;
                    zuuluu = 'change';
                    michal = function(argFoo) {
                        _fun00007: for(var _fun00008_ip = 0; ; ) switch(_fun00008_ip) {
 0:
                            michal = 'active';
                            entity = argFoo;
                            if(!(michal !== entity)) { _fun00008_ip = 24; continue _fun00007 }
 11:
                            michal = _closure2_slot0;
                            entity = undefined;
                            entity = michal.bind(entity)();
 24:
                            entity = undefined;
                            return entity;
                        }
                    };
                    michal = tangon.bind(report)(zuuluu, michal);
                    var _closure3_slot0 = michal;
                    entity = function() {
                        michal = _closure3_slot0;
                        entity = michal.remove;
                        entity = entity.bind(michal)();
                        entity = undefined;
                        return entity;
                    };
                    return entity;
                }
            };
            option = foxtra.bind(offset)(option, verify);
            verify = offset.useLayoutEffect;
            option = new Array(2);
            option[0] = yankee;
            option[1] = golfie;
            golfie = function() {
                _fun00009: for(var _fun00010_ip = 0; ; ) switch(_fun00010_ip) {
 0:
                    michal = _closure2_slot5;
                    if(!michal) { _fun00010_ip = 20; continue _fun00009 }
 10:
                    tangon = _closure2_slot1;
                    zuuluu = null;
                    michal = zuuluu == tangon;
 20:
                    if(!michal) { _fun00010_ip = 47; continue _fun00009 }
 23:
                    zuuluu = _closure2_slot7;
                    entity = _closure1_slot11;
                    michal = entity.POST_WATCH_VIDEO;
                    entity = undefined;
                    entity = zuuluu.bind(entity)(michal);
 47:
                    entity = undefined;
                    return entity;
                }
            };
            golfie = verify.bind(offset)(golfie, option);
            verify = offset.useCallback;
            option = function() {
                zuuluu = _closure2_slot7;
                entity = _closure1_slot11;
                michal = entity.WATCH_VIDEO;
                entity = undefined;
                michal = zuuluu.bind(entity)(michal);
                return entity;
            };
            golfie = new Array(0);
            result = verify.bind(offset)(option, golfie);
            verify = offset.useCallback;
            option = new Array(1);
            option[0] = source;
            golfie = function() {
                tangon = _closure2_slot9;
                entity = undefined;
                zuuluu = false;
                zuuluu = tangon.bind(entity)(zuuluu);
                zuuluu = _closure2_slot7;
                michal = _closure1_slot11;
                michal = michal.POST_WATCH_VIDEO;
                michal = zuuluu.bind(entity)(michal);
                return entity;
            };
            ctrled = verify.bind(offset)(golfie, option);
            verify = 13;
            michal = michal[verify];
            zuuluu = zuuluu.bind(tangon)(michal);
            michal = zuuluu.useSharedValue;
            golfie = _closure1_slot11;
            golfie = golfie.POST_WATCH_VIDEO;
            if(!(kiloes === golfie)) { _fun00002_ip = 497; continue _fun00001 }
 494:
            report = oscard;
 497:
            oscard = michal.bind(zuuluu)(report);
            var _closure2_slot10 = oscard;
            offset = _closure1_slot0;
            yankee = _closure1_slot2;
            michal = yankee[verify];
            report = offset.bind(tangon)(michal);
            zuuluu = report.useAnimatedStyle;
            michal = function() { // Original name: x
                entity = {};
                offset = _closure1_slot0;
                yankee = _closure1_slot2;
                tangon = 14;
                michal = yankee[tangon];
                verify = undefined;
                romeon = offset.bind(verify)(michal);
                report = romeon.withSpring;
                option = 13;
                michal = yankee[option];
                kiloes = offset.bind(verify)(michal);
                backup = kiloes.clamp;
                zuuluu = _closure2_slot10;
                michal = zuuluu.get;
                foxtra = michal.bind(zuuluu)();
                michal = 0;
                zuuluu = 1;
                zuuluu = backup.bind(kiloes)(foxtra, michal, zuuluu);
                oscard = _closure1_slot10;
                zuuluu = report.bind(romeon)(zuuluu, oscard);
                entity['opacity'] = zuuluu;
                zuuluu = {};
                tangon = yankee[tangon];
                report = offset.bind(verify)(tangon);
                tangon = report.withSpring;
                option = yankee[option];
                offset = offset.bind(verify)(option);
                verify = offset.interpolate;
                option = _closure2_slot10;
                golfie = option.get;
                option = golfie.bind(option)();
                golfie = new Array(2);
                yankee = -100;
                golfie[0] = yankee;
                golfie[1] = michal;
                michal = [0, 1];
                michal = verify.bind(offset)(option, michal, golfie);
                michal = tangon.bind(report)(michal, oscard);
                zuuluu['translateY'] = michal;
                michal = new Array(1);
                michal[0] = zuuluu;
                entity['transform'] = michal;
                return entity;
            };
            golfie = {};
            foxtra = 14;
            option = yankee[foxtra];
            option = offset.bind(tangon)(option);
            option = option.withSpring;
            golfie['withSpring'] = option;
            option = yankee[verify];
            option = offset.bind(tangon)(option);
            option = option.clamp;
            golfie['clamp'] = option;
            golfie['postWatchAnimationState'] = oscard;
            option = _closure1_slot10;
            golfie['BACKGROUND_ENTRANCE_ANIMATION_SPRING_CONFIG'] = option;
            update = yankee[verify];
            update = offset.bind(tangon)(update);
            update = update.interpolate;
            golfie['interpolate'] = update;
            update = -100;
            golfie['CLOUDS_BACKGROUND_INVISIBLE_OFFSET_Y'] = update;
            michal['__closure'] = golfie;
            golfie = 11571705142399.0;
            michal['__workletHash'] = golfie;
            golfie = _closure1_slot13;
            michal['__initData'] = golfie;
            sequen = zuuluu.bind(report)(michal);
            config = _closure1_slot1;
            michal = 15;
            michal = yankee[michal];
            michal = config.bind(tangon)(michal);
            target = michal.bind(tangon)();
            var _closure2_slot11 = target;
            michal = yankee[verify];
            report = offset.bind(tangon)(michal);
            zuuluu = report.useAnimatedStyle;
            michal = function() { // Original name: U
                entity = {};
                verify = {};
                oscard = _closure1_slot0;
                golfie = _closure1_slot2;
                zuuluu = 14;
                michal = golfie[zuuluu];
                tangon = undefined;
                yankee = oscard.bind(tangon)(michal);
                offset = yankee.withSpring;
                michal = 13;
                michal = golfie[michal];
                kiloes = oscard.bind(tangon)(michal);
                backup = kiloes.interpolate;
                romeon = _closure2_slot10;
                option = romeon.get;
                foxtra = option.bind(romeon)();
                option = _closure2_slot11;
                option = option.top;
                romeon = new Array(2);
                romeon[0] = option;
                option = 0;
                romeon[1] = option;
                option = [0, 1];
                option = backup.bind(kiloes)(foxtra, option, romeon);
                report = _closure1_slot10;
                option = offset.bind(yankee)(option, report);
                verify['translateY'] = option;
                option = new Array(1);
                option[0] = verify;
                entity['transform'] = option;
                zuuluu = golfie[zuuluu];
                tangon = oscard.bind(tangon)(zuuluu);
                zuuluu = tangon.withSpring;
                oscard = _closure2_slot10;
                michal = oscard.get;
                michal = michal.bind(oscard)();
                michal = zuuluu.bind(tangon)(michal, report);
                entity['opacity'] = michal;
                return entity;
            };
            golfie = {};
            foxtra = yankee[foxtra];
            foxtra = offset.bind(tangon)(foxtra);
            foxtra = foxtra.withSpring;
            golfie['withSpring'] = foxtra;
            verify = yankee[verify];
            verify = offset.bind(tangon)(verify);
            verify = verify.interpolate;
            golfie['interpolate'] = verify;
            golfie['postWatchAnimationState'] = oscard;
            golfie['safeAreaInsets'] = target;
            golfie['BACKGROUND_ENTRANCE_ANIMATION_SPRING_CONFIG'] = option;
            michal['__closure'] = golfie;
            golfie = 9769051401109.0;
            michal['__workletHash'] = golfie;
            golfie = _closure1_slot14;
            michal['__initData'] = golfie;
            papara = zuuluu.bind(report)(michal);
            report = _closure1_slot4;
            zuuluu = report.useEffect;
            michal = new Array(2);
            michal[0] = oscard;
            michal[1] = kiloes;
            entity = function() {
                _fun00011: for(var _fun00012_ip = 0; ; ) switch(_fun00012_ip) {
 0:
                    zuuluu = _closure2_slot10;
                    michal = zuuluu.set;
                    report = _closure2_slot6;
                    entity = _closure1_slot11;
                    tangon = entity.POST_WATCH_VIDEO;
                    entity = 0;
                    if(!(report === tangon)) { _fun00012_ip = 38; continue _fun00011 }
 35:
                    entity = 1;
 38:
                    entity = michal.bind(zuuluu)(entity);
                    entity = undefined;
                    return entity;
                }
            };
            entity = zuuluu.bind(report)(entity, michal);
            zuuluu = _closure1_slot8;
            michal = _closure1_slot5;
            entity = {};
            golfie = _closure1_slot9;
            foxtra = 16;
            report = yankee[foxtra];
            oscard = config.bind(tangon)(report);
            report = {};
            option = romeon.modalContentWrapper;
            report['style'] = option;
            option = {};
            update = romeon.backgroundWrapper;
            verify = new Array(2);
            verify[0] = update;
            update = {};
            update['height'] = sizing;
            verify[1] = update;
            option['style'] = verify;
            verify = yankee[foxtra];
            update = config.bind(tangon)(verify);
            verify = {};
            cntext = romeon.contentBackground;
            record = new Array(2);
            record[0] = cntext;
            cntext = {};
            target = target.top;
            cntext['top'] = target;
            record[1] = cntext;
            verify['style'] = record;
            update = zuuluu.bind(tangon)(update, verify);
            verify = new Array(3);
            verify[0] = update;
            update = yankee[foxtra];
            record = config.bind(tangon)(update);
            update = {};
            target = romeon.contentBackground;
            cntext = new Array(2);
            cntext[0] = target;
            cntext[1] = papara;
            update['style'] = cntext;
            update = zuuluu.bind(tangon)(record, update);
            verify[1] = update;
            foxtra = yankee[foxtra];
            update = config.bind(tangon)(foxtra);
            foxtra = {};
            foxtra['style'] = sequen;
            sequen = 17;
            sequen = yankee[sequen];
            config = config.bind(tangon)(sequen);
            sequen = {};
            record = 'top';
            sequen['align'] = record;
            sequen = zuuluu.bind(tangon)(config, sequen);
            foxtra['children'] = sequen;
            foxtra = zuuluu.bind(tangon)(update, foxtra);
            verify[2] = foxtra;
            option['children'] = verify;
            verify = golfie.bind(tangon)(michal, option);
            option = new Array(2);
            option[0] = verify;
            verify = 18;
            verify = yankee[verify];
            verify = offset.bind(tangon)(verify);
            offset = verify.SafeAreaPaddingView;
            verify = {};
            yankee = true;
            verify['top'] = yankee;
            foxtra = romeon.wrapper;
            yankee = new Array(2);
            yankee[0] = foxtra;
            foxtra = {};
            foxtra['height'] = sizing;
            yankee[1] = foxtra;
            verify['style'] = yankee;
            yankee = {};
            romeon = romeon.contentWrapper;
            yankee['style'] = romeon;
            romeon = _closure1_slot11;
            romeon = romeon.WATCH_VIDEO;
            foxtra = kiloes === romeon;
            if(!foxtra) { _fun00002_ip = 1225; continue _fun00001 }
 1163:
            update = _closure1_slot8;
            sizing = _closure1_slot1;
            sequen = _closure1_slot2;
            romeon = 19;
            romeon = sequen[romeon];
            sizing = sizing.bind(tangon)(romeon);
            romeon = {};
            romeon['isFullscreen'] = vacuum;
            romeon['onNavigateToPostWatchVideo'] = ctrled;
            romeon['onClose'] = echoed;
            romeon['onEnd'] = ctrled;
            romeon['setIsFullscreen'] = source;
            romeon['sourceQuestContent'] = output;
            foxtra = update.bind(tangon)(sizing, romeon);
 1225:
            romeon = new Array(2);
            romeon[0] = foxtra;
            foxtra = _closure1_slot11;
            foxtra = foxtra.POST_WATCH_VIDEO;
            foxtra = kiloes === foxtra;
            if(!foxtra) { _fun00002_ip = 1297; continue _fun00001 }
 1250:
            sizing = _closure1_slot8;
            kiloes = _closure1_slot1;
            update = _closure1_slot2;
            backup = 20;
            backup = update[backup];
            kiloes = kiloes.bind(tangon)(backup);
            backup = {};
            backup['onClose'] = echoed;
            backup['onRestartVideo'] = result;
            backup['sourceQuestContent'] = output;
            foxtra = sizing.bind(tangon)(kiloes, backup);
 1297:
            romeon[1] = foxtra;
            yankee['children'] = romeon;
            yankee = golfie.bind(tangon)(michal, yankee);
            verify['children'] = yankee;
            verify = zuuluu.bind(tangon)(offset, verify);
            option[1] = verify;
            report['children'] = option;
            report = golfie.bind(tangon)(oscard, report);
            entity['children'] = report;
            entity = zuuluu.bind(tangon)(michal, entity);
            return entity;
        }
    };
    report = verify.bind(option)(report);
    var _closure1_slot15 = report;
    report = option.memo;
    tangon = function(argFoo) { // Original name: VideoQuestModal
        entity = argFoo;
        verify = entity.questId;
        yankee = entity.questContentPosition;
        var _closure2_slot0 = yankee;
        backup = entity.onClose;
        var _closure2_slot1 = backup;
        romeon = entity.videoSessionId;
        var _closure2_slot2 = romeon;
        offset = entity.initialStep;
        var _closure2_slot3 = offset;
        report = entity.sourceQuestContent;
        var _closure2_slot4 = report;
        michal = _closure1_slot0;
        oscard = _closure1_slot2;
        tangon = 21;
        golfie = oscard[tangon];
        tangon = undefined;
        option = michal.bind(tangon)(golfie);
        golfie = option.useNonNullableQuest;
        foxtra = golfie.bind(option)(verify);
        var _closure2_slot5 = foxtra;
        verify = _closure1_slot4;
        option = verify.useMemo;
        golfie = new Array(6);
        golfie[0] = backup;
        golfie[1] = foxtra;
        golfie[2] = romeon;
        golfie[3] = yankee;
        golfie[4] = offset;
        golfie[5] = report;
        report = function() {
            entity = {};
            zuuluu = {};
            tangon = true;
            zuuluu['fullscreen'] = tangon;
            tangon = function() { // Original name: headerLeft
                entity = null;
                return entity;
            };
            zuuluu['headerLeft'] = tangon;
            michal = function() { // Original name: render
                tangon = _closure1_slot8;
                michal = _closure1_slot1;
                foxtra = _closure1_slot2;
                entity = 7;
                entity = foxtra[entity];
                zuuluu = undefined;
                entity = michal.bind(zuuluu)(entity);
                michal = entity.Provider;
                entity = {};
                oscard = {};
                offset = _closure2_slot5;
                oscard['quest'] = offset;
                golfie = _closure2_slot2;
                oscard['videoSessionId'] = golfie;
                entity['value'] = oscard;
                romeon = _closure1_slot0;
                report = 10;
                report = foxtra[report];
                report = romeon.bind(zuuluu)(report);
                oscard = report.QuestDockGestureContextProvider;
                report = {};
                golfie = 22;
                golfie = foxtra[golfie];
                golfie = romeon.bind(zuuluu)(golfie);
                option = golfie.QuestContentImpressionTrackerNative;
                golfie = {};
                yankee = true;
                golfie['overrideVisibility'] = yankee;
                yankee = 23;
                yankee = foxtra[yankee];
                yankee = romeon.bind(zuuluu)(yankee);
                yankee = yankee.QuestContent;
                yankee = yankee.VIDEO_MODAL_MOBILE;
                golfie['questContent'] = yankee;
                golfie['questOrQuests'] = offset;
                offset = _closure2_slot0;
                golfie['questContentPosition'] = offset;
                verify = _closure2_slot4;
                golfie['sourceQuestContent'] = verify;
                verify = function() { // Original name: children
                    tangon = _closure1_slot8;
                    zuuluu = _closure1_slot15;
                    michal = {};
                    report = _closure2_slot3;
                    michal['initialStep'] = report;
                    report = _closure2_slot1;
                    michal['onClose'] = report;
                    entity = _closure2_slot4;
                    michal['sourceQuestContent'] = entity;
                    entity = undefined;
                    entity = tangon.bind(entity)(zuuluu, michal);
                    return entity;
                };
                golfie['children'] = verify;
                golfie = tangon.bind(zuuluu)(option, golfie);
                report['children'] = golfie;
                report = tangon.bind(zuuluu)(oscard, report);
                entity['children'] = report;
                entity = tangon.bind(zuuluu)(michal, entity);
                return entity;
            };
            zuuluu['render'] = michal;
            michal = 'watch_mobile_video_quest';
            entity[michal] = zuuluu;
            return entity;
        };
        report = option.bind(verify)(report, golfie);
        option = verify.useLayoutEffect;
        golfie = function() {
            zuuluu = _closure1_slot0;
            tangon = _closure1_slot2;
            entity = 8;
            report = tangon[entity];
            michal = undefined;
            option = zuuluu.bind(michal)(report);
            golfie = option.lockOrientation;
            oscard = 'PORTRAIT';
            report = true;
            report = golfie.bind(option)(oscard, report);
            entity = tangon[entity];
            entity = zuuluu.bind(michal)(entity);
            entity = entity.restoreDefaultOrientation;
            return entity;
        };
        zuuluu = new Array(0);
        zuuluu = option.bind(verify)(golfie, zuuluu);
        zuuluu = _closure1_slot8;
        entity = 24;
        entity = oscard[entity];
        entity = michal.bind(tangon)(entity);
        michal = entity.Modal;
        entity = {'hideTitle': true, 'initialRouteName': 'watch_mobile_video_quest'};
        entity['screens'] = report;
        entity = zuuluu.bind(tangon)(michal, entity);
        return entity;
    };
    tangon = report.bind(option)(tangon);
    report = 25;
    report = golfie[report];
    golfie = oscard.bind(entity)(report);
    oscard = golfie.fileFinishedImporting;
    report = 'modules/quests/native/VideoQuestModal/VideoQuestModal.tsx';
    report = oscard.bind(golfie)(report);
    zuuluu['default'] = tangon;
    zuuluu['VideoQuestModalSteps'] = michal;
    return entity;
})();