// app/modules/payments/hooks/useSubscriptionSelection.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var3 = exports;
    var5 = dependencyMap;
    var1 = global;
    var7 = var1.Object;
    var6 = var7.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var6.bind(var7)(var3, var1, var4);
    var1 = 0;
    var6 = var5[var1];
    var4 = metroImportDefault;
    var1 = undefined;
    var4 = var4.bind(var1)(var6);
    var _closure1_slot0 = var4;
    var4 = 1;
    var6 = var5[var4];
    var4 = metroImportAll;
    var4 = var4.bind(var1)(var6);
    var _closure1_slot1 = var4;
    var4 = 2;
    var5 = var5[var4];
    var4 = require;
    var6 = var4.bind(var1)(var5);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/payments/hooks/useSubscriptionSelection.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function useSubscriptionSelection() {
        var9 = _closure1_slot1;
        var1 = var9.useState;
        var8 = undefined;
        var1 = var1.bind(var9)(var8);
        var7 = _closure1_slot0;
        var2 = 2;
        var1 = var7.bind(var8)(var1, var2);
        var4 = 0;
        var6 = var1[var4];
        var3 = 1;
        var5 = var1[var3];
        var1 = var9.useState;
        var1 = var1.bind(var9)(var8);
        var2 = var7.bind(var8)(var1, var2);
        var1 = {};
        var1['selectedSkuId'] = var6;
        var1['setSelectedSkuId'] = var5;
        var4 = var2[var4];
        var1['selectedPlanId'] = var4;
        var2 = var2[var3];
        var1['setSelectedPlanId'] = var2;
        return var1;
    };
    var3['default'] = var2;
    return var1;
})();