// app/design/components/experimental/BackgroundBlurView/native/BackgroundBlurView.native.tsx
export default (function(native1, native2, native3, native4, native5, native6, native7) {
    var5 = native2;
    var3 = native6;
    var6 = native7;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var6;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var7 = var6[var1];
    var4 = native4;
    var1 = undefined;
    var7 = var4.bind(var1)(var7);
    var4 = 1;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.View;
    var _closure1_slot2 = var4;
    var4 = 2;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var8 = var4.jsx;
    var _closure1_slot3 = var8;
    var4 = var4.jsxs;
    var _closure1_slot4 = var4;
    var4 = 3;
    var4 = var6[var4];
    var9 = var5.bind(var1)(var4);
    var8 = var9.createStyles;
    var4 = {};
    var10 = {'position': 'relative', 'overflow': 'hidden'};
    var4['container'] = var10;
    var4 = var8.bind(var9)(var4);
    var _closure1_slot5 = var4;
    var4 = var7.forwardRef;
    var2 = function BackgroundBlurViewComponent(arg1, arg2) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
 0:
            var3 = arg1;
            var5 = var3.children;
            var8 = var3.style;
            var12 = var3.blurTheme;
            var11 = var3.pressed;
            var10 = var3.android_blurTargetViewNativeId;
            var2 = {'children': 0, 'style': 0, 'blurTheme': 0, 'pressed': 0, 'android_blurTargetViewNativeId': 0};
            var7 = null;
            var16 = var2;
            var15 = null;
            var1 = silentSetPrototypeOf(var16, var15);
            var16 = {};
            var15 = var3;
            var14 = var2;
            var15 = copyDataProperties(var16, var15, var14);
            var1 = _closure1_slot5;
            var4 = undefined;
            var9 = var1.bind(var4)();
            var3 = _closure1_slot4;
            var2 = _closure1_slot2;
            var1 = {};
            var16 = var1;
            var13 = copyDataProperties(var16, var15);
            var13 = var9.container;
            var9 = new Array(2);
            var9[0] = var13;
            var9[1] = var8;
            var8 = 'style';
            var1[var8] = var9;
            var9 = arg2;
            var8 = 'ref';
            var1[var8] = var9;
            if(!(var7 == var11)) { _fun0001_ip = 190; continue _fun0001 }
 140:
            var9 = _closure1_slot3;
            var8 = _closure1_slot0;
            var13 = _closure1_slot1;
            var7 = 4;
            var7 = var13[var7];
            var7 = var8.bind(var4)(var7);
            var8 = var7.BackgroundBlurFill;
            var7 = {};
            var7['blurTheme'] = var12;
            var7['android_blurTargetViewNativeId'] = var10;
            var7 = var9.bind(var4)(var8, var7);
            _fun0001_ip = 243; continue _fun0001;
 190:
            var9 = _closure1_slot3;
            var8 = _closure1_slot0;
            var13 = _closure1_slot1;
            var6 = 4;
            var6 = var13[var6];
            var6 = var8.bind(var4)(var6);
            var8 = var6.BackgroundBlurFillWithPress;
            var6 = {};
            var6['blurTheme'] = var12;
            var6['pressed'] = var11;
            var6['android_blurTargetViewNativeId'] = var10;
            var7 = var9.bind(var4)(var8, var6);
 243:
            var6 = new Array(2);
            var6[0] = var7;
            var6[1] = var5;
            var5 = 'children';
            var1[var5] = var6;
            var1 = var3.bind(var4)(var2, var1);
            return var1;
        }
    };
    var2 = var4.bind(var7)(var2);
    var4 = 5;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'design/components/experimental/BackgroundBlurView/native/BackgroundBlurView.native.tsx';
    var4 = var5.bind(var6)(var4);
    var3['BackgroundBlurView'] = var2;
    return var1;
})();