// app/modules/guild_settings/discovery/GuildSettingsDiscoveryConstants.tsx
export default (function(native1, native2, native3, native4, native5, native6, native7) {
    var7 = native2;
    var3 = native6;
    var6 = native7;
    var _closure1_slot0 = var7;
    var _closure1_slot1 = var6;
    var1 = global;
    var8 = var1.Object;
    var5 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var5.bind(var8)(var3, var1, var4);
    var5 = {};
    var4 = 14;
    var5['GENERAL_CHATTING'] = var4;
    var1 = 'GENERAL_CHATTING';
    var5[var4] = var1;
    var1 = 1;
    var5['GAMING'] = var1;
    var4 = 'GAMING';
    var5[var1] = var4;
    var8 = 2;
    var5['MUSIC'] = var8;
    var4 = 'MUSIC';
    var5[var8] = var4;
    var8 = 3;
    var5['ENTERTAINMENT'] = var8;
    var4 = 'ENTERTAINMENT';
    var5[var8] = var4;
    var8 = 4;
    var5['CREATIVE_ARTS'] = var8;
    var4 = 'CREATIVE_ARTS';
    var5[var8] = var4;
    var8 = 5;
    var5['SCIENCE_AND_TECH'] = var8;
    var4 = 'SCIENCE_AND_TECH';
    var5[var8] = var4;
    var8 = 6;
    var5['EDUCATION'] = var8;
    var4 = 'EDUCATION';
    var5[var8] = var4;
    var8 = 7;
    var5['SPORTS'] = var8;
    var4 = 'SPORTS';
    var5[var8] = var4;
    var8 = 8;
    var5['FASHION_AND_BEAUTY'] = var8;
    var4 = 'FASHION_AND_BEAUTY';
    var5[var8] = var4;
    var8 = 9;
    var5['RELATIONSHIPS_AND_IDENTITY'] = var8;
    var4 = 'RELATIONSHIPS_AND_IDENTITY';
    var5[var8] = var4;
    var8 = 10;
    var5['TRAVEL_AND_FOOD'] = var8;
    var4 = 'TRAVEL_AND_FOOD';
    var5[var8] = var4;
    var8 = 11;
    var5['FITNESS_AND_HEALTH'] = var8;
    var4 = 'FITNESS_AND_HEALTH';
    var5[var8] = var4;
    var8 = 12;
    var5['FINANCE'] = var8;
    var4 = 'FINANCE';
    var5[var8] = var4;
    var8 = 13;
    var5['OTHER'] = var8;
    var4 = 'OTHER';
    var5[var8] = var4;
    var8 = 43;
    var5['EMOJI'] = var8;
    var4 = 'EMOJI';
    var5[var8] = var4;
    var8 = 49;
    var5['BOTS'] = var8;
    var4 = 'BOTS';
    var5[var8] = var4;
    var4 = {};
    var9 = var5.GENERAL_CHATTING;
    var8 = new Array(10);
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.D7iWEx;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[0] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1./L7rGx;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[1] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.cGIWjY;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[2] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.pQ3bLi;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[3] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.GIaXW1;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[4] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.BXJCGh;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[5] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.vuVkq6;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[6] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.bhfaCQ;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[7] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.XuOAEB;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[8] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.i2qs5u;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[9] = var10;
    var4[var9] = var8;
    var9 = var5.GAMING;
    var8 = new Array(10);
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.GIaXW1;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[0] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1./L7rGx;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[1] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.pQ3bLi;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[2] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.cGIWjY;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[3] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.bhfaCQ;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[4] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.XFmNp6;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[5] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.i2qs5u;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[6] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.X/WT19;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[7] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.GXGNi4;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[8] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.Kma1j4;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[9] = var10;
    var4[var9] = var8;
    var9 = var5.MUSIC;
    var8 = new Array(10);
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.bt4I09;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[0] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.kPJLKi;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[1] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.AIm/var7;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[2] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.cGIWjY;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[3] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.ge/d+f;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[4] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.6IjJBA;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[5] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.9o6KiI;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[6] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.D7iWEx;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[7] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.7ztK/P;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[8] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.rD/ntb;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[9] = var10;
    var4[var9] = var8;
    var9 = var5.ENTERTAINMENT;
    var8 = new Array(9);
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.XuOAEB;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[0] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.cGIWjY;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[1] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.D7iWEx;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[2] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.pQ3bLi;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[3] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.pdWHSU;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[4] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.QiafXV;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[5] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.vuVkq6;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[6] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.UoCpFB;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[7] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.+1/7Z2;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[8] = var10;
    var4[var9] = var8;
    var9 = var5.CREATIVE_ARTS;
    var8 = new Array(10);
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.ZtggfH;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[0] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.XuOAEB;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[1] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.94j5sL;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[2] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.cGIWjY;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[3] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.o4tBNz;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[4] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.IFIoIy;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[5] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.LbCJkp;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[6] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.pdWHSU;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[7] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.IVKcrK;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[8] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.eyEy1d;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[9] = var10;
    var4[var9] = var8;
    var9 = var5.SCIENCE_AND_TECH;
    var8 = new Array(10);
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.b7SNGh;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[0] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.3QIvxc;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[1] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.kNNW5u;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[2] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.N3xsjo;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[3] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.pHmUCg;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[4] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.KOKw4e;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[5] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.QxiuyM;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[6] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.ID64/f;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[7] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.i5+2Fx;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[8] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.mJwTU1;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[9] = var10;
    var4[var9] = var8;
    var9 = var5.EDUCATION;
    var8 = new Array(10);
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.7F8qdX;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[0] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.XmPLhY;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[1] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.G/c0Q0;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[2] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.uQYr4+;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[3] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.L2nkMj;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[4] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.iUSTDQ;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[5] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.b7SNGh;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[6] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.T+brl5;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[7] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.rAnIoK;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[8] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.cGIWjY;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[9] = var10;
    var4[var9] = var8;
    var9 = var5.SPORTS;
    var8 = new Array(10);
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.PMk3Oj;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[0] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.WzM5YG;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[1] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.+Epq9v;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[2] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.y8wELi;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[3] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.xVrb6+;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[4] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.F86j2d;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[5] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.b3cP4+;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[6] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.3KaQOz;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[7] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.+1/7Z2;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[8] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.6dJGyc;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[9] = var10;
    var4[var9] = var8;
    var9 = var5.FASHION_AND_BEAUTY;
    var8 = new Array(9);
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.4J2PYG;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[0] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.splt1N;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[1] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.MkNq8/;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[2] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.NiqSMj;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[3] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.+1/7Z2;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[4] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.xJ4Qzs;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[5] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.bNBcQ0;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[6] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.j5IdUF;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[7] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.+zpNOD;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[8] = var10;
    var4[var9] = var8;
    var9 = var5.RELATIONSHIPS_AND_IDENTITY;
    var8 = new Array(5);
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.MR5I+v;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[0] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.XuOAEB;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[1] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.UoCpFB;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[2] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.3EMtxs;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[3] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.BXJCGh;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[4] = var10;
    var4[var9] = var8;
    var9 = var5.TRAVEL_AND_FOOD;
    var8 = new Array(7);
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.rOhu7u;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[0] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.f1Zj09;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[1] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.Uh0Fx8;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[2] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.mFRT9P;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[3] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.cGIWjY;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[4] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.jEfJq6;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[5] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.YkEzAQ;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[6] = var10;
    var4[var9] = var8;
    var9 = var5.FITNESS_AND_HEALTH;
    var8 = new Array(10);
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.kg/vNz;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[0] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.1S1Wfn;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[1] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.eR1cPD;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[2] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.XPWT7O;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[3] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.vtJDam;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[4] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.4te8Ag;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[5] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.MKokFx;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[6] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.h1o0//;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[7] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.h5IW39;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[8] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.9reexc;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[9] = var10;
    var4[var9] = var8;
    var9 = var5.FINANCE;
    var8 = new Array(9);
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.rAnIoK;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[0] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.f9SRFh;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[1] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.Z53e3t;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[2] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.eWY96+;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[3] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.QxiuyM;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[4] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.eNZqqK;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[5] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.put7Hx;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[6] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.NtauHh;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[7] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.DZeh+/;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[8] = var10;
    var4[var9] = var8;
    var9 = var5.OTHER;
    var8 = new Array(8);
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.D7iWEx;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[0] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.cGIWjY;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[1] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.pQ3bLi;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[2] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.BXJCGh;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[3] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.XuOAEB;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[4] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.vmvBDg;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[5] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.UoCpFB;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[6] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.QiafXV;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[7] = var10;
    var4[var9] = var8;
    var9 = var5.EMOJI;
    var8 = new Array(9);
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.dl70Ji;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[0] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.R58PcH;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[1] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.hDjtaG;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[2] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.XuOAEB;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[3] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1./Fgjen;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[4] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.FM0+HR;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[5] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.OGdz4+;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[6] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.ZtggfH;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[7] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.QiafXV;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[8] = var10;
    var4[var9] = var8;
    var9 = var5.BOTS;
    var8 = new Array(7);
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.QYvZFh;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[0] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.C2TrLi;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[1] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.9AEkCw;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[2] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.FM0+HR;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[3] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.vwjf//;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[4] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.Exwe4+;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[5] = var10;
    var10 = function() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 0;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.QiafXV;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var8[6] = var10;
    var4[var9] = var8;
    var8 = ['en-GB'];
    var _closure1_slot2 = var8;
    var6 = var6[var1];
    var1 = undefined;
    var8 = var7.bind(var1)(var6);
    var7 = var8.fileFinishedImporting;
    var6 = 'modules/guild_settings/discovery/GuildSettingsDiscoveryConstants.tsx';
    var6 = var7.bind(var8)(var6);
    var3['GuildPrimaryCategory'] = var5;
    var3['SUGGESTED_TAGS_FOR_CATEGORIES'] = var4;
    var2 = function calculateLocaleOptions() {
        var4 = _closure1_slot0;
        var3 = _closure1_slot1;
        var2 = 0;
        var3 = var3[var2];
        var2 = undefined;
        var3 = var4.bind(var2)(var3);
        var2 = var3.getAvailableLocales;
        var4 = var2.bind(var3)();
        var3 = var4.map;
        var2 = function(arg1) {
            _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
 0:
                var1 = arg1;
                var3 = var1.value;
                var2 = var1.name;
                var1 = 'en-US';
                if(!(var1 !== var3)) { _fun0001_ip = 40; continue _fun0001 }
 21:
                var1 = {};
                var1['value'] = var3;
                var1['label'] = var2;
                var2 = undefined;
                var1['image'] = var2;
                _fun0001_ip = 119; continue _fun0001;
 40:
                var2 = {};
                var2['value'] = var3;
                var7 = _closure1_slot0;
                var8 = _closure1_slot1;
                var4 = 0;
                var5 = var8[var4];
                var3 = undefined;
                var5 = var7.bind(var3)(var5);
                var6 = var5.intl;
                var5 = var6.string;
                var4 = var8[var4];
                var4 = var7.bind(var3)(var4);
                var4 = var4.t;
                var4 = var4.WKEPHR;
                var4 = var5.bind(var6)(var4);
                var2['label'] = var4;
                var2['image'] = var3;
                var1 = var2;
 119:
                return var1;
            }
        };
        var3 = var3.bind(var4)(var2);
        var2 = var3.filter;
        var1 = function(arg1) {
            var3 = _closure1_slot2;
            var2 = var3.includes;
            var1 = arg1;
            var1 = var1.value;
            var1 = var2.bind(var3)(var1);
            var1 = !var1;
            return var1;
        };
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var3['calculateLocaleOptions'] = var2;
    return var1;
})();