// discord_common/js/packages/rtn-codegen/js/LottieNodeNativeComponent.tsx
export default (function(argFoo, argBar, argBaz, argCorge, argGrault, argFred, argPlugh) {
    golf = argBar;
    zulu = argFred;
    options = argPlugh;
    var _closure1_slot0 = golf;
    var _closure1_slot1 = options;
    entity = global;
    report = entity.Object;
    tango = report.defineProperty;
    mike = {};
    entity = true;
    mike['value'] = entity;
    entity = '__esModule';
    entity = tango.bind(report)(zulu, entity, mike);
    tango = {};
    offset = 'NativeLottieNode';
    tango['uiViewClassName'] = offset;
    entity = {};
    tango['validAttributes'] = entity;
    var _closure1_slot2 = tango;
    entity = 0;
    mike = options[entity];
    entity = undefined;
    verify = golf.bind(entity)(mike);
    report = verify.get;
    mike = function() {
        entity = _closure1_slot2;
        return entity;
    };
    report = report.bind(verify)(offset, mike);
    mike = {};
    oscar = function(argFoo, argBar, argBaz, argCorge, argGrault, argFred, argPlugh) { // Original name: setup
        zulu = _closure1_slot0;
        mike = _closure1_slot1;
        entity = 1;
        mike = mike[entity];
        entity = undefined;
        oscar = zulu.bind(entity)(mike);
        report = oscar.dispatchCommand;
        tango = new Array(6);
        mike = argBar;
        tango[0] = mike;
        mike = argBaz;
        tango[1] = mike;
        mike = argCorge;
        tango[2] = mike;
        mike = argGrault;
        tango[3] = mike;
        mike = argFred;
        tango[4] = mike;
        mike = argPlugh;
        tango[5] = mike;
        zulu = argFoo;
        mike = 'setup';
        mike = report.bind(oscar)(zulu, mike, tango);
        return entity;
    };
    mike['setup'] = oscar;
    oscar = 2;
    oscar = options[oscar];
    options = golf.bind(entity)(oscar);
    golf = options.fileFinishedImporting;
    oscar = '../discord_common/js/packages/rtn-codegen/js/LottieNodeNativeComponent.tsx';
    oscar = golf.bind(options)(oscar);
    zulu['default'] = report;
    zulu['__INTERNAL_VIEW_CONFIG'] = tango;
    zulu['Commands'] = mike;
    return entity;
})();