// discord_common/js/packages/rtn-codegen/js/SafeAreaNativeComponent.tsx
export default (function(_, argBar, __, ___, ____, argFre, argPlu) {
    oscard = argBar;
    zuuluu = argFre;
    golfie = argPlu;
    entity = global;
    option = entity.Object;
    report = option.defineProperty;
    michal = {};
    entity = true;
    michal['value'] = entity;
    entity = '__esModule';
    entity = report.bind(option)(zuuluu, entity, michal);
    michal = {};
    verify = 'DCDSafeArea';
    michal['uiViewClassName'] = verify;
    entity = {};
    report = {};
    option = 'onSafeAreaInsetsDidChange';
    report['registrationName'] = option;
    entity['topSafeAreaInsetsDidChange'] = report;
    report = {};
    option = 'onInsetsChange';
    report['registrationName'] = option;
    entity['topInsetsChange'] = report;
    michal['directEventTypes'] = entity;
    report = {};
    entity = 0;
    option = golfie[entity];
    entity = undefined;
    yankee = oscard.bind(entity)(option);
    offset = yankee.ConditionallyIgnoredEventHandlers;
    option = {'onSafeAreaInsetsDidChange': true, 'onInsetsChange': true};
    foxtra = offset.bind(yankee)(option);
    backup = report;
    option = copyDataProperties(backup, foxtra);
    michal['validAttributes'] = report;
    var _closure1_slot0 = michal;
    report = 1;
    report = golfie[report];
    option = oscard.bind(entity)(report);
    report = option.get;
    tangon = function() {
        entity = _closure1_slot0;
        return entity;
    };
    tangon = report.bind(option)(verify, tangon);
    report = 2;
    report = golfie[report];
    golfie = oscard.bind(entity)(report);
    oscard = golfie.fileFinishedImporting;
    report = '../discord_common/js/packages/rtn-codegen/js/SafeAreaNativeComponent.tsx';
    report = oscard.bind(golfie)(report);
    zuuluu['default'] = tangon;
    zuuluu['__INTERNAL_VIEW_CONFIG'] = michal;
    return entity;
})();