// discord_common/js/packages/rtn-codegen/js/StickerPickerListRowNativeComponent.tsx
export default (function(_, argBar, __, ___, ____, argFre, argPlu) {
    oscard = argBar;
    zuuluu = argFre;
    golfie = argPlu;
    entity = global;
    verify = entity.Object;
    option = verify.defineProperty;
    report = {};
    entity = true;
    report['value'] = entity;
    michal = '__esModule';
    michal = option.bind(verify)(zuuluu, michal, report);
    michal = {};
    verify = 'StickerPickerRowView';
    michal['uiViewClassName'] = verify;
    report = {};
    option = {};
    offset = 'onPressSticker';
    option['registrationName'] = offset;
    report['topPressSticker'] = option;
    option = {};
    offset = 'onLongPressSticker';
    option['registrationName'] = offset;
    report['topLongPressSticker'] = option;
    michal['directEventTypes'] = report;
    report = {};
    report['rowData'] = entity;
    entity = 0;
    option = golfie[entity];
    entity = undefined;
    yankee = oscard.bind(entity)(option);
    offset = yankee.ConditionallyIgnoredEventHandlers;
    option = {'onPressSticker': true, 'onLongPressSticker': true};
    foxtra = offset.bind(yankee)(option);
    backup = report;
    option = copyDataProperties(backup, foxtra);
    michal['validAttributes'] = report;
    var _closure1_slot0 = michal;
    report = 1;
    report = golfie[report];
    option = oscard.bind(entity)(report);
    report = option.get;
    tangon = function() {
        entity = _closure1_slot0;
        return entity;
    };
    tangon = report.bind(option)(verify, tangon);
    report = 2;
    report = golfie[report];
    golfie = oscard.bind(entity)(report);
    oscard = golfie.fileFinishedImporting;
    report = '../discord_common/js/packages/rtn-codegen/js/StickerPickerListRowNativeComponent.tsx';
    report = oscard.bind(golfie)(report);
    zuuluu['default'] = tangon;
    zuuluu['__INTERNAL_VIEW_CONFIG'] = michal;
    return entity;
})();