// app/modules/home_drawer/native/HomeDrawerExperiment.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var3 = exports;
    var5 = dependencyMap;
    var1 = global;
    var6 = var1.Object;
    var4 = var6.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var4.bind(var6)(var3, var1, var2);
    var1 = 0;
    var4 = var5[var1];
    var2 = metroImportDefault;
    var1 = undefined;
    var4 = var2.bind(var1)(var4);
    var2 = {'name': '2025-10-mobile-home-drawer', 'kind': 'user'};
    var6 = {'enableHome': false, 'landOnHome': false, 'enablePeekHint': false};
    var2['defaultConfig'] = var6;
    var6 = {};
    var7 = {'enableHome': true, 'landOnHome': false, 'enablePeekHint': true};
    var6[1] = var7;
    var7 = {'enableHome': true, 'landOnHome': true, 'enablePeekHint': false};
    var6[2] = var7;
    var2['variations'] = var6;
    var2 = var4.bind(var1)(var2);
    var4 = 1;
    var5 = var5[var4];
    var4 = require;
    var6 = var4.bind(var1)(var5);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/home_drawer/native/HomeDrawerExperiment.tsx';
    var4 = var5.bind(var6)(var4);
    var3['MobileHomeDrawerExperiment'] = var2;
    return var1;
})();