// app/modules/pomelo/native/PomeloModalConstants.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var3 = exports;
    var1 = global;
    var5 = var1.Object;
    var4 = var5.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var4.bind(var5)(var3, var1, var2);
    var4 = {};
    var1 = 'Details';
    var4['DETAILS'] = var1;
    var1 = 'Edit';
    var4['EDIT'] = var1;
    var1 = 'Reminder';
    var4['REMINDER'] = var1;
    var2 = {};
    var1 = 'display-name';
    var2['EDIT_DISPLAY_NAME'] = var1;
    var1 = 'username';
    var2['EDIT_USERNAME'] = var1;
    var1 = 'preview';
    var2['PREVIEW'] = var1;
    var1 = 'suggestion';
    var2['SUGGESTION'] = var1;
    var5 = dependencyMap;
    var1 = 0;
    var6 = var5[var1];
    var5 = require;
    var1 = undefined;
    var7 = var5.bind(var1)(var6);
    var6 = var7.fileFinishedImporting;
    var5 = 'modules/pomelo/native/PomeloModalConstants.tsx';
    var5 = var6.bind(var7)(var5);
    var5 = 'pomelo-modal';
    var3['POMELO_MODAL_KEY'] = var5;
    var5 = 'pomelo-announcement-modal';
    var3['POMELO_ANNOUNCEMENT_MODAL'] = var5;
    var3['PomeloScreens'] = var4;
    var3['EditState'] = var2;
    return var1;
})();