// app/modules/premium/native/utils/openGiftModal.tsx
export default (function(argFoo, argBar, argBaz, _, __, argFre, argPlu) {
    report = argBar;
    zuuluu = argFre;
    tangon = argPlu;
    var _closure1_slot0 = report;
    entity = argBaz;
    var _closure1_slot1 = entity;
    var _closure1_slot2 = tangon;
    entity = global;
    option = entity.Object;
    golfie = option.defineProperty;
    oscard = {};
    entity = true;
    oscard['value'] = entity;
    entity = '__esModule';
    entity = golfie.bind(option)(zuuluu, entity, oscard);
    entity = 3;
    tangon = tangon[entity];
    entity = undefined;
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/premium/native/utils/openGiftModal.tsx';
    tangon = report.bind(oscard)(tangon);
    michal = function(argFoo) { // Original name: openGiftModal
        tangon = argFoo;
        verify = tangon.navigationParams;
        entity = null;
        zuuluu = Object.create(entity);
        entity = 0;
        zuuluu['navigationParams'] = entity;
        romeon = {};
        yankee = tangon;
        offset = zuuluu;
        report = copyDataProperties(romeon, yankee, offset);
        tangon = _closure1_slot1;
        michal = _closure1_slot2;
        zuuluu = michal[entity];
        entity = undefined;
        tangon = tangon.bind(entity)(zuuluu);
        zuuluu = tangon.pushLazy;
        option = _closure1_slot0;
        golfie = 2;
        golfie = michal[golfie];
        option = option.bind(entity)(golfie);
        golfie = 1;
        golfie = michal[golfie];
        michal = michal.paths;
        romeon = option.bind(entity)(golfie, michal);
        foxtra = tangon;
        yankee = report;
        offset = undefined;
        michal = foxtra[zuuluu](romeon, yankee, offset, verify, option);
        return entity;
    };
    zuuluu['openGiftModal'] = michal;
    return entity;
})();