// app/modules/markup/MarkupUtils.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var10 = metroImportDefault;
    var7 = metroImportAll;
    var3 = exports;
    var5 = dependencyMap;
    var _closure1_slot0 = var10;
    var _closure1_slot1 = var7;
    var _closure1_slot2 = var5;
    var9 = function combineAndInjectMentionRule(arg1, arg2) {
        var4 = arg1;
        var1 = var4.mention;
        var2 = _closure1_slot0;
        var3 = _closure1_slot2;
        var1 = 0;
        var1 = var3[var1];
        var3 = undefined;
        var2 = var2.bind(var3)(var1);
        var1 = new Array(2);
        var1[0] = var4;
        var8 = arg2;
        var5 = 1;
        var9 = var1;
        var7 = var5;
        var4 = arraySpread(var9, var8, var7);
        var6 = {};
        var1[3] = var6;
        var4 = var4 + var5;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var _closure1_slot32 = var9;
    var1 = global;
    var8 = var1.Object;
    var6 = var8.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var6.bind(var8)(var3, var1, var2);
    var1 = ['url', 'autolink', 'link', 'mailto', 'tel'];
    var _closure1_slot3 = var1;
    var8 = {'enableBuildOverrides': false, 'enableEmojiClick': true};
    var _closure1_slot4 = var8;
    var2 = 1;
    var6 = var5[var2];
    var1 = undefined;
    var12 = var10.bind(var1)(var6);
    var11 = var12.once;
    var6 = function() {
        var4 = _closure1_slot32;
        var5 = _closure1_slot0;
        var6 = _closure1_slot2;
        var1 = 2;
        var1 = var6[var1];
        var3 = undefined;
        var1 = var5.bind(var3)(var1);
        var2 = var1.RULES;
        var1 = 3;
        var1 = var6[var1];
        var5 = var5.bind(var3)(var1);
        var1 = {};
        var6 = true;
        var1['enableBuildOverrides'] = var6;
        var5 = var5.bind(var3)(var1);
        var1 = new Array(1);
        var1[0] = var5;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var6 = var11.bind(var12)(var6);
    var _closure1_slot5 = var6;
    var6 = var5[var2];
    var12 = var10.bind(var1)(var6);
    var11 = var12.once;
    var6 = function() {
        var8 = _closure1_slot0;
        var9 = _closure1_slot2;
        var2 = 1;
        var2 = var9[var2];
        var6 = undefined;
        var5 = var8.bind(var6)(var2);
        var4 = var5.omit;
        var3 = _closure1_slot32;
        var2 = 2;
        var2 = var9[var2];
        var2 = var8.bind(var6)(var2);
        var2 = var2.RULES;
        var7 = 3;
        var7 = var9[var7];
        var7 = var8.bind(var6)(var7);
        var1 = _closure1_slot4;
        var7 = var7.bind(var6)(var1);
        var1 = new Array(1);
        var1[0] = var7;
        var3 = var3.bind(var6)(var2, var1);
        var2 = 'paragraph';
        var1 = 'newline';
        var1 = var4.bind(var5)(var3, var2, var1);
        return var1;
    };
    var6 = var11.bind(var12)(var6);
    var _closure1_slot6 = var6;
    var6 = var5[var2];
    var12 = var10.bind(var1)(var6);
    var11 = var12.once;
    var6 = function() {
        var4 = _closure1_slot32;
        var8 = _closure1_slot0;
        var9 = _closure1_slot2;
        var7 = 2;
        var1 = var9[var7];
        var3 = undefined;
        var1 = var8.bind(var3)(var1);
        var2 = var1.CHANNEL_TOPIC_RULES;
        var1 = 3;
        var1 = var9[var1];
        var5 = var8.bind(var3)(var1);
        var1 = {};
        var11 = _closure1_slot4;
        var12 = var1;
        var6 = copyDataProperties(var12, var11);
        var10 = 'bottom';
        var6 = 'emojiTooltipPosition';
        var1[5] = var10;
        var10 = true;
        var6 = 'shouldCloseDefaultModals';
        var1[5] = var10;
        var6 = 'shouldStopPropagation';
        var1[5] = var10;
        var5 = var5.bind(var3)(var1);
        var1 = new Array(2);
        var1[0] = var5;
        var5 = {};
        var6 = {};
        var7 = var9[var7];
        var7 = var8.bind(var3)(var7);
        var7 = var7.RULES;
        var7 = var7.text;
        var7 = var7.react;
        var6['react'] = var7;
        var5['codeBlock'] = var6;
        var1[1] = var5;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var6 = var11.bind(var12)(var6);
    var _closure1_slot7 = var6;
    var6 = var5[var2];
    var12 = var10.bind(var1)(var6);
    var11 = var12.once;
    var6 = function() {
        var4 = _closure1_slot32;
        var5 = _closure1_slot0;
        var7 = _closure1_slot2;
        var1 = 2;
        var1 = var7[var1];
        var3 = undefined;
        var1 = var5.bind(var3)(var1);
        var2 = var1.VOICE_CHANNEL_STATUS_RULES;
        var1 = 3;
        var1 = var7[var1];
        var5 = var5.bind(var3)(var1);
        var1 = {};
        var8 = _closure1_slot4;
        var9 = var1;
        var6 = copyDataProperties(var9, var8);
        var7 = false;
        var6 = 'enableEmojiClick';
        var1[5] = var7;
        var5 = var5.bind(var3)(var1);
        var1 = new Array(1);
        var1[0] = var5;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var6 = var11.bind(var12)(var6);
    var _closure1_slot8 = var6;
    var6 = var5[var2];
    var12 = var10.bind(var1)(var6);
    var11 = var12.once;
    var6 = function() {
        var4 = _closure1_slot32;
        var6 = _closure1_slot0;
        var7 = _closure1_slot2;
        var2 = 2;
        var2 = var7[var2];
        var3 = undefined;
        var2 = var6.bind(var3)(var2);
        var2 = var2.EMBED_TITLE_RULES;
        var5 = 3;
        var5 = var7[var5];
        var5 = var6.bind(var3)(var5);
        var1 = _closure1_slot4;
        var5 = var5.bind(var3)(var1);
        var1 = new Array(1);
        var1[0] = var5;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var6 = var11.bind(var12)(var6);
    var _closure1_slot9 = var6;
    var6 = var5[var2];
    var12 = var10.bind(var1)(var6);
    var11 = var12.once;
    var6 = function() {
        var8 = _closure1_slot0;
        var9 = _closure1_slot2;
        var2 = 1;
        var2 = var9[var2];
        var7 = undefined;
        var4 = var8.bind(var7)(var2);
        var3 = var4.omit;
        var6 = _closure1_slot32;
        var2 = 2;
        var2 = var9[var2];
        var2 = var8.bind(var7)(var2);
        var5 = var2.EMBED_TITLE_RULES;
        var2 = 3;
        var2 = var9[var2];
        var8 = var8.bind(var7)(var2);
        var2 = _closure1_slot4;
        var8 = var8.bind(var7)(var2);
        var2 = new Array(1);
        var2[0] = var8;
        var2 = var6.bind(var7)(var5, var2);
        var1 = _closure1_slot3;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var6 = var11.bind(var12)(var6);
    var _closure1_slot10 = var6;
    var6 = var5[var2];
    var12 = var10.bind(var1)(var6);
    var11 = var12.once;
    var6 = function() {
        var4 = _closure1_slot32;
        var6 = _closure1_slot0;
        var7 = _closure1_slot2;
        var2 = 2;
        var2 = var7[var2];
        var3 = undefined;
        var2 = var6.bind(var3)(var2);
        var2 = var2.INLINE_REPLY_RULES;
        var5 = 3;
        var5 = var7[var5];
        var5 = var6.bind(var3)(var5);
        var1 = _closure1_slot4;
        var5 = var5.bind(var3)(var1);
        var1 = new Array(1);
        var1[0] = var5;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var6 = var11.bind(var12)(var6);
    var _closure1_slot11 = var6;
    var6 = var5[var2];
    var12 = var10.bind(var1)(var6);
    var11 = var12.once;
    var6 = function() {
        var4 = _closure1_slot32;
        var6 = _closure1_slot0;
        var7 = _closure1_slot2;
        var2 = 2;
        var2 = var7[var2];
        var3 = undefined;
        var2 = var6.bind(var3)(var2);
        var2 = var2.GUILD_VERIFICATION_FORM_RULES;
        var5 = 3;
        var5 = var7[var5];
        var5 = var6.bind(var3)(var5);
        var1 = _closure1_slot4;
        var5 = var5.bind(var3)(var1);
        var1 = new Array(1);
        var1[0] = var5;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var6 = var11.bind(var12)(var6);
    var _closure1_slot12 = var6;
    var6 = var5[var2];
    var12 = var10.bind(var1)(var6);
    var11 = var12.once;
    var6 = function() {
        var4 = _closure1_slot32;
        var6 = _closure1_slot0;
        var7 = _closure1_slot2;
        var2 = 2;
        var2 = var7[var2];
        var3 = undefined;
        var2 = var6.bind(var3)(var2);
        var2 = var2.GUILD_EVENT_RULES;
        var5 = 3;
        var5 = var7[var5];
        var5 = var6.bind(var3)(var5);
        var1 = _closure1_slot4;
        var5 = var5.bind(var3)(var1);
        var1 = new Array(1);
        var1[0] = var5;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var6 = var11.bind(var12)(var6);
    var _closure1_slot13 = var6;
    var6 = var5[var2];
    var12 = var10.bind(var1)(var6);
    var11 = var12.once;
    var6 = function() {
        var4 = _closure1_slot32;
        var6 = _closure1_slot0;
        var7 = _closure1_slot2;
        var2 = 2;
        var2 = var7[var2];
        var3 = undefined;
        var2 = var6.bind(var3)(var2);
        var2 = var2.AUTO_MODERATION_SYSTEM_MESSAGE_RULES;
        var5 = 3;
        var5 = var7[var5];
        var5 = var6.bind(var3)(var5);
        var1 = _closure1_slot4;
        var5 = var5.bind(var3)(var1);
        var1 = new Array(1);
        var1[0] = var5;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var6 = var11.bind(var12)(var6);
    var _closure1_slot14 = var6;
    var6 = var5[var2];
    var12 = var10.bind(var1)(var6);
    var11 = var12.once;
    var6 = function() {
        var8 = _closure1_slot0;
        var9 = _closure1_slot2;
        var1 = 1;
        var1 = var9[var1];
        var7 = undefined;
        var3 = var8.bind(var7)(var1);
        var2 = var3.omit;
        var6 = _closure1_slot32;
        var1 = 2;
        var1 = var9[var1];
        var1 = var8.bind(var7)(var1);
        var5 = var1.RULES;
        var1 = 3;
        var1 = var9[var1];
        var8 = var8.bind(var7)(var1);
        var1 = _closure1_slot4;
        var8 = var8.bind(var7)(var1);
        var1 = new Array(1);
        var1[0] = var8;
        var5 = var6.bind(var7)(var5, var1);
        var1 = new Array(10);
        var1[0] = var5;
        var5 = 'paragraph';
        var1[1] = var5;
        var5 = 'newline';
        var1[2] = var5;
        var5 = 'strong';
        var1[3] = var5;
        var5 = 'codeBlock';
        var1[4] = var5;
        var5 = 'inlineCode';
        var1[5] = var5;
        var5 = 'u';
        var1[6] = var5;
        var5 = 'list';
        var1[7] = var5;
        var5 = 'heading';
        var1[8] = var5;
        var5 = 'subtext';
        var1[9] = var5;
        var11 = _closure1_slot3;
        var10 = 10;
        var12 = var1;
        var4 = arraySpread(var12, var11, var10);
        var12 = var2;
        var11 = var1;
        var10 = var3;
        var1 = apply(var12, var11, var10);
        return var1;
    };
    var6 = var11.bind(var12)(var6);
    var _closure1_slot15 = var6;
    var6 = {};
    var11 = 2;
    var11 = var5[var11];
    var11 = var10.bind(var1)(var11);
    var11 = var11.RULES;
    var11 = var11.text;
    var6['text'] = var11;
    var11 = var5[var2];
    var13 = var10.bind(var1)(var11);
    var12 = var13.once;
    var11 = function() {
        var3 = _closure1_slot1;
        var4 = _closure1_slot2;
        var2 = 4;
        var2 = var4[var2];
        var4 = undefined;
        var3 = var3.bind(var4)(var2);
        var2 = var3.reactParserFor;
        var1 = _closure1_slot5;
        var1 = var1.bind(var4)();
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var11 = var12.bind(var13)(var11);
    var _closure1_slot16 = var11;
    var11 = var5[var2];
    var13 = var10.bind(var1)(var11);
    var12 = var13.once;
    var11 = function() {
        var3 = _closure1_slot1;
        var4 = _closure1_slot2;
        var2 = 4;
        var2 = var4[var2];
        var4 = undefined;
        var3 = var3.bind(var4)(var2);
        var2 = var3.reactParserFor;
        var1 = _closure1_slot7;
        var1 = var1.bind(var4)();
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var11 = var12.bind(var13)(var11);
    var _closure1_slot17 = var11;
    var11 = var5[var2];
    var13 = var10.bind(var1)(var11);
    var12 = var13.once;
    var11 = function() {
        var3 = _closure1_slot1;
        var4 = _closure1_slot2;
        var2 = 4;
        var2 = var4[var2];
        var4 = undefined;
        var3 = var3.bind(var4)(var2);
        var2 = var3.reactParserFor;
        var1 = _closure1_slot8;
        var1 = var1.bind(var4)();
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var11 = var12.bind(var13)(var11);
    var _closure1_slot18 = var11;
    var11 = var5[var2];
    var13 = var10.bind(var1)(var11);
    var12 = var13.once;
    var11 = function() {
        var3 = _closure1_slot1;
        var4 = _closure1_slot2;
        var2 = 4;
        var2 = var4[var2];
        var4 = undefined;
        var3 = var3.bind(var4)(var2);
        var2 = var3.reactParserFor;
        var1 = _closure1_slot9;
        var1 = var1.bind(var4)();
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var11 = var12.bind(var13)(var11);
    var _closure1_slot19 = var11;
    var11 = var5[var2];
    var13 = var10.bind(var1)(var11);
    var12 = var13.once;
    var11 = function() {
        var3 = _closure1_slot1;
        var4 = _closure1_slot2;
        var2 = 4;
        var2 = var4[var2];
        var4 = undefined;
        var3 = var3.bind(var4)(var2);
        var2 = var3.reactParserFor;
        var1 = _closure1_slot10;
        var1 = var1.bind(var4)();
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var11 = var12.bind(var13)(var11);
    var _closure1_slot20 = var11;
    var11 = var5[var2];
    var13 = var10.bind(var1)(var11);
    var12 = var13.once;
    var11 = function() {
        var3 = _closure1_slot1;
        var4 = _closure1_slot2;
        var2 = 4;
        var2 = var4[var2];
        var4 = undefined;
        var3 = var3.bind(var4)(var2);
        var2 = var3.reactParserFor;
        var1 = _closure1_slot11;
        var1 = var1.bind(var4)();
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var11 = var12.bind(var13)(var11);
    var _closure1_slot21 = var11;
    var11 = var5[var2];
    var13 = var10.bind(var1)(var11);
    var12 = var13.once;
    var11 = function() {
        var3 = _closure1_slot1;
        var4 = _closure1_slot2;
        var2 = 4;
        var2 = var4[var2];
        var4 = undefined;
        var3 = var3.bind(var4)(var2);
        var2 = var3.reactParserFor;
        var1 = _closure1_slot12;
        var1 = var1.bind(var4)();
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var11 = var12.bind(var13)(var11);
    var _closure1_slot22 = var11;
    var11 = var5[var2];
    var13 = var10.bind(var1)(var11);
    var12 = var13.once;
    var11 = function() {
        var3 = _closure1_slot1;
        var4 = _closure1_slot2;
        var2 = 4;
        var2 = var4[var2];
        var4 = undefined;
        var3 = var3.bind(var4)(var2);
        var2 = var3.reactParserFor;
        var1 = _closure1_slot13;
        var1 = var1.bind(var4)();
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var11 = var12.bind(var13)(var11);
    var _closure1_slot23 = var11;
    var11 = var5[var2];
    var13 = var10.bind(var1)(var11);
    var12 = var13.once;
    var11 = function() {
        var3 = _closure1_slot1;
        var4 = _closure1_slot2;
        var2 = 4;
        var2 = var4[var2];
        var4 = undefined;
        var3 = var3.bind(var4)(var2);
        var2 = var3.reactParserFor;
        var1 = _closure1_slot14;
        var1 = var1.bind(var4)();
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var11 = var12.bind(var13)(var11);
    var _closure1_slot24 = var11;
    var11 = var5[var2];
    var13 = var10.bind(var1)(var11);
    var12 = var13.once;
    var11 = function() {
        var3 = _closure1_slot1;
        var4 = _closure1_slot2;
        var2 = 4;
        var2 = var4[var2];
        var4 = undefined;
        var3 = var3.bind(var4)(var2);
        var2 = var3.reactParserFor;
        var1 = _closure1_slot6;
        var1 = var1.bind(var4)();
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var11 = var12.bind(var13)(var11);
    var _closure1_slot25 = var11;
    var11 = var5[var2];
    var13 = var10.bind(var1)(var11);
    var12 = var13.once;
    var11 = function() {
        var3 = _closure1_slot1;
        var4 = _closure1_slot2;
        var2 = 4;
        var2 = var4[var2];
        var4 = undefined;
        var3 = var3.bind(var4)(var2);
        var2 = var3.astParserFor;
        var1 = _closure1_slot5;
        var1 = var1.bind(var4)();
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var11 = var12.bind(var13)(var11);
    var _closure1_slot26 = var11;
    var11 = var5[var2];
    var13 = var10.bind(var1)(var11);
    var12 = var13.once;
    var11 = function() {
        var3 = _closure1_slot1;
        var4 = _closure1_slot2;
        var2 = 4;
        var2 = var4[var2];
        var4 = undefined;
        var3 = var3.bind(var4)(var2);
        var2 = var3.astParserFor;
        var1 = _closure1_slot7;
        var1 = var1.bind(var4)();
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var11 = var12.bind(var13)(var11);
    var _closure1_slot27 = var11;
    var11 = var5[var2];
    var13 = var10.bind(var1)(var11);
    var12 = var13.once;
    var11 = function() {
        var3 = _closure1_slot1;
        var4 = _closure1_slot2;
        var2 = 4;
        var2 = var4[var2];
        var4 = undefined;
        var3 = var3.bind(var4)(var2);
        var2 = var3.astParserFor;
        var1 = _closure1_slot9;
        var1 = var1.bind(var4)();
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var11 = var12.bind(var13)(var11);
    var _closure1_slot28 = var11;
    var11 = var5[var2];
    var13 = var10.bind(var1)(var11);
    var12 = var13.once;
    var11 = function() {
        var3 = _closure1_slot1;
        var4 = _closure1_slot2;
        var2 = 4;
        var2 = var4[var2];
        var4 = undefined;
        var3 = var3.bind(var4)(var2);
        var2 = var3.astParserFor;
        var1 = _closure1_slot10;
        var1 = var1.bind(var4)();
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var11 = var12.bind(var13)(var11);
    var _closure1_slot29 = var11;
    var11 = var5[var2];
    var13 = var10.bind(var1)(var11);
    var12 = var13.once;
    var11 = function() {
        var3 = _closure1_slot1;
        var4 = _closure1_slot2;
        var2 = 4;
        var2 = var4[var2];
        var4 = undefined;
        var3 = var3.bind(var4)(var2);
        var2 = var3.astParserFor;
        var1 = _closure1_slot11;
        var1 = var1.bind(var4)();
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var11 = var12.bind(var13)(var11);
    var _closure1_slot30 = var11;
    var2 = var5[var2];
    var12 = var10.bind(var1)(var2);
    var11 = var12.once;
    var2 = function() {
        var3 = _closure1_slot1;
        var4 = _closure1_slot2;
        var2 = 4;
        var2 = var4[var2];
        var4 = undefined;
        var3 = var3.bind(var4)(var2);
        var2 = var3.astParserFor;
        var1 = _closure1_slot14;
        var1 = var1.bind(var4)();
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var2 = var11.bind(var12)(var2);
    var _closure1_slot31 = var2;
    var2 = {};
    var2['combineAndInjectMentionRule'] = var9;
    var9 = 3;
    var9 = var5[var9];
    var9 = var10.bind(var1)(var9);
    var2['createReactRules'] = var9;
    var2['defaultReactRuleOptions'] = var8;
    var9 = function get defaultRules() {
        var2 = _closure1_slot5;
        var1 = undefined;
        var1 = var2.bind(var1)();
        return var1;
    };
    var8 = 'defaultRules';
    Object.defineProperty(var2, var8, {get: var9, set: var1, enumerable: true});
    var9 = function get guildEventRules() {
        var2 = _closure1_slot13;
        var1 = undefined;
        var1 = var2.bind(var1)();
        return var1;
    };
    var8 = 'guildEventRules';
    Object.defineProperty(var2, var8, {get: var9, set: var1, enumerable: true});
    var9 = function get notifCenterV2MessagePreviewRules() {
        var2 = _closure1_slot15;
        var1 = undefined;
        var1 = var2.bind(var1)();
        return var1;
    };
    var8 = 'notifCenterV2MessagePreviewRules';
    Object.defineProperty(var2, var8, {get: var9, set: var1, enumerable: true});
    var2['lockscreenWidgetMessageRules'] = var6;
    var6 = 4;
    var8 = var5[var6];
    var8 = var7.bind(var1)(var8);
    var8 = var8.astParserFor;
    var2['astParserFor'] = var8;
    var6 = var5[var6];
    var6 = var7.bind(var1)(var6);
    var6 = var6.reactParserFor;
    var2['reactParserFor'] = var6;
    var6 = function parse(arg1) {
        var8 = 0;
        var7 = copyRestArgs(var8);
        var1 = _closure1_slot16;
        var3 = undefined;
        var2 = var1.bind(var3)();
        var1 = new Array(0);
        var8 = var1;
        var6 = 0;
        var4 = arraySpread(var8, var7, var6);
        var8 = var2;
        var7 = var1;
        var6 = undefined;
        var1 = apply(var8, var7, var6);
        return var1;
    };
    var2['parse'] = var6;
    var6 = function parseTopic(arg1, arg2, arg3, arg4) {
        var1 = _closure1_slot17;
        var6 = undefined;
        var5 = var1.bind(var6)();
        var4 = {};
        var1 = true;
        var4['allowLinks'] = var1;
        var9 = arg3;
        var10 = var4;
        var1 = copyDataProperties(var10, var9);
        var10 = arg1;
        var9 = arg2;
        var7 = arg4;
        var11 = undefined;
        var8 = var4;
        var1 = var11[var5](var10, var9, var8, var7, var6);
        return var1;
    };
    var2['parseTopic'] = var6;
    var6 = function parseVoiceChannelStatus(arg1) {
        var8 = 0;
        var7 = copyRestArgs(var8);
        var1 = _closure1_slot18;
        var3 = undefined;
        var2 = var1.bind(var3)();
        var1 = new Array(0);
        var8 = var1;
        var6 = 0;
        var4 = arraySpread(var8, var7, var6);
        var8 = var2;
        var7 = var1;
        var6 = undefined;
        var1 = apply(var8, var7, var6);
        return var1;
    };
    var2['parseVoiceChannelStatus'] = var6;
    var6 = function parseEmbedTitle(arg1) {
        var8 = 0;
        var7 = copyRestArgs(var8);
        var1 = _closure1_slot19;
        var3 = undefined;
        var2 = var1.bind(var3)();
        var1 = new Array(0);
        var8 = var1;
        var6 = 0;
        var4 = arraySpread(var8, var7, var6);
        var8 = var2;
        var7 = var1;
        var6 = undefined;
        var1 = apply(var8, var7, var6);
        return var1;
    };
    var2['parseEmbedTitle'] = var6;
    var6 = function parseEmbedTitleWithoutLinks(arg1) {
        var8 = 0;
        var7 = copyRestArgs(var8);
        var1 = _closure1_slot20;
        var3 = undefined;
        var2 = var1.bind(var3)();
        var1 = new Array(0);
        var8 = var1;
        var6 = 0;
        var4 = arraySpread(var8, var7, var6);
        var8 = var2;
        var7 = var1;
        var6 = undefined;
        var1 = apply(var8, var7, var6);
        return var1;
    };
    var2['parseEmbedTitleWithoutLinks'] = var6;
    var6 = function parseInlineReply(arg1) {
        var8 = 0;
        var7 = copyRestArgs(var8);
        var1 = _closure1_slot21;
        var3 = undefined;
        var2 = var1.bind(var3)();
        var1 = new Array(0);
        var8 = var1;
        var6 = 0;
        var4 = arraySpread(var8, var7, var6);
        var8 = var2;
        var7 = var1;
        var6 = undefined;
        var1 = apply(var8, var7, var6);
        return var1;
    };
    var2['parseInlineReply'] = var6;
    var6 = function parseGuildVerificationFormRule(arg1) {
        var8 = 0;
        var7 = copyRestArgs(var8);
        var1 = _closure1_slot22;
        var3 = undefined;
        var2 = var1.bind(var3)();
        var1 = new Array(0);
        var8 = var1;
        var6 = 0;
        var4 = arraySpread(var8, var7, var6);
        var8 = var2;
        var7 = var1;
        var6 = undefined;
        var1 = apply(var8, var7, var6);
        return var1;
    };
    var2['parseGuildVerificationFormRule'] = var6;
    var6 = function parseGuildEventDescription(arg1) {
        var8 = 0;
        var7 = copyRestArgs(var8);
        var1 = _closure1_slot23;
        var3 = undefined;
        var2 = var1.bind(var3)();
        var1 = new Array(0);
        var8 = var1;
        var6 = 0;
        var4 = arraySpread(var8, var7, var6);
        var8 = var2;
        var7 = var1;
        var6 = undefined;
        var1 = apply(var8, var7, var6);
        return var1;
    };
    var2['parseGuildEventDescription'] = var6;
    var6 = function parseAutoModerationSystemMessage(arg1) {
        var8 = 0;
        var7 = copyRestArgs(var8);
        var1 = _closure1_slot24;
        var3 = undefined;
        var2 = var1.bind(var3)();
        var1 = new Array(0);
        var8 = var1;
        var6 = 0;
        var4 = arraySpread(var8, var7, var6);
        var8 = var2;
        var7 = var1;
        var6 = undefined;
        var1 = apply(var8, var7, var6);
        return var1;
    };
    var2['parseAutoModerationSystemMessage'] = var6;
    var6 = function parseForumPostGuidelines(arg1) {
        var8 = 0;
        var7 = copyRestArgs(var8);
        var1 = _closure1_slot25;
        var3 = undefined;
        var2 = var1.bind(var3)();
        var1 = new Array(0);
        var8 = var1;
        var6 = 0;
        var4 = arraySpread(var8, var7, var6);
        var8 = var2;
        var7 = var1;
        var6 = undefined;
        var1 = apply(var8, var7, var6);
        return var1;
    };
    var2['parseForumPostGuidelines'] = var6;
    var6 = function parseToAST(arg1) {
        var8 = 0;
        var7 = copyRestArgs(var8);
        var1 = _closure1_slot26;
        var3 = undefined;
        var2 = var1.bind(var3)();
        var1 = new Array(0);
        var8 = var1;
        var6 = 0;
        var4 = arraySpread(var8, var7, var6);
        var8 = var2;
        var7 = var1;
        var6 = undefined;
        var1 = apply(var8, var7, var6);
        return var1;
    };
    var2['parseToAST'] = var6;
    var6 = function parseTopicToAST(arg1) {
        var8 = 0;
        var7 = copyRestArgs(var8);
        var1 = _closure1_slot27;
        var3 = undefined;
        var2 = var1.bind(var3)();
        var1 = new Array(0);
        var8 = var1;
        var6 = 0;
        var4 = arraySpread(var8, var7, var6);
        var8 = var2;
        var7 = var1;
        var6 = undefined;
        var1 = apply(var8, var7, var6);
        return var1;
    };
    var2['parseTopicToAST'] = var6;
    var6 = function parseEmbedTitleToAST(arg1) {
        var8 = 0;
        var7 = copyRestArgs(var8);
        var1 = _closure1_slot28;
        var3 = undefined;
        var2 = var1.bind(var3)();
        var1 = new Array(0);
        var8 = var1;
        var6 = 0;
        var4 = arraySpread(var8, var7, var6);
        var8 = var2;
        var7 = var1;
        var6 = undefined;
        var1 = apply(var8, var7, var6);
        return var1;
    };
    var2['parseEmbedTitleToAST'] = var6;
    var6 = function parseEmbedTitleWithoutLinksToAST(arg1) {
        var8 = 0;
        var7 = copyRestArgs(var8);
        var1 = _closure1_slot29;
        var3 = undefined;
        var2 = var1.bind(var3)();
        var1 = new Array(0);
        var8 = var1;
        var6 = 0;
        var4 = arraySpread(var8, var7, var6);
        var8 = var2;
        var7 = var1;
        var6 = undefined;
        var1 = apply(var8, var7, var6);
        return var1;
    };
    var2['parseEmbedTitleWithoutLinksToAST'] = var6;
    var6 = function parseInlineReplyToAST(arg1) {
        var8 = 0;
        var7 = copyRestArgs(var8);
        var1 = _closure1_slot30;
        var3 = undefined;
        var2 = var1.bind(var3)();
        var1 = new Array(0);
        var8 = var1;
        var6 = 0;
        var4 = arraySpread(var8, var7, var6);
        var8 = var2;
        var7 = var1;
        var6 = undefined;
        var1 = apply(var8, var7, var6);
        return var1;
    };
    var2['parseInlineReplyToAST'] = var6;
    var4 = function parseAutoModerationSystemMessageToAST(arg1) {
        var8 = 0;
        var7 = copyRestArgs(var8);
        var1 = _closure1_slot31;
        var3 = undefined;
        var2 = var1.bind(var3)();
        var1 = new Array(0);
        var8 = var1;
        var6 = 0;
        var4 = arraySpread(var8, var7, var6);
        var8 = var2;
        var7 = var1;
        var6 = undefined;
        var1 = apply(var8, var7, var6);
        return var1;
    };
    var2['parseAutoModerationSystemMessageToAST'] = var4;
    var4 = 5;
    var5 = var5[var4];
    var4 = require;
    var6 = var4.bind(var1)(var5);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/markup/MarkupUtils.tsx';
    var4 = var5.bind(var6)(var4);
    var3['default'] = var2;
    return var1;
})();