// app/modules/remixing/native/hooks/useGGSans700Font.tsx
export default (function(argFoo, argBar, _, __, ___, argFred, argPlugh) {
    report = argBar;
    zulu = argFred;
    oscar = argPlugh;
    var _closure1_slot0 = report;
    var _closure1_slot1 = oscar;
    entity = global;
    options = entity.Object;
    golf = options.defineProperty;
    tango = {};
    entity = true;
    tango['value'] = entity;
    entity = '__esModule';
    entity = golf.bind(options)(zulu, entity, tango);
    entity = 0;
    tango = oscar[entity];
    entity = undefined;
    tango = report.bind(entity)(tango);
    tango = tango.Platform;
    tango = 2;
    tango = oscar[tango];
    oscar = report.bind(entity)(tango);
    report = oscar.fileFinishedImporting;
    tango = 'modules/remixing/native/hooks/useGGSans700Font.tsx';
    tango = report.bind(oscar)(tango);
    mike = function(argFoo) { // Original name: _default
        entity = {};
        tango = _closure1_slot0;
        zulu = _closure1_slot1;
        mike = 1;
        zulu = zulu[mike];
        mike = undefined;
        oscar = tango.bind(mike)(zulu);
        report = oscar.useLoadFont;
        tango = '../fonts/ggsans-700-bold.ttf';
        mike = 'https://cdn.discordapp.com/assets/remix/fonts/ggsans-700-bold.ttf';
        zulu = argFoo;
        zulu = report.bind(oscar)(tango, mike, zulu);
        entity['font'] = zulu;
        entity['fontSource'] = mike;
        return entity;
    };
    zulu['default'] = mike;
    return entity;
})();