// app/modules/premium/referral_program/hooks/native/useReferralProgramCoachmark.tsx
export default (function(argFoo, argBar, argBaz, argCor, _, argFre, argPlu) {
    report = argBar;
    golfie = argBaz;
    zuuluu = argFre;
    oscard = argPlu;
    var _closure1_slot0 = report;
    var _closure1_slot1 = golfie;
    var _closure1_slot2 = oscard;
    entity = function() { // Original name: ReferralProgramCoachmarkImg
        entity = _closure1_slot9;
        tangon = undefined;
        option = entity.bind(tangon)();
        zuuluu = _closure1_slot8;
        michal = _closure1_slot5;
        entity = {};
        oscard = option.coachmarkImageContainer;
        entity['style'] = oscard;
        golfie = _closure1_slot8;
        offset = _closure1_slot1;
        yankee = _closure1_slot2;
        report = 7;
        report = yankee[report];
        oscard = offset.bind(tangon)(report);
        report = {};
        verify = 8;
        verify = yankee[verify];
        verify = offset.bind(tangon)(verify);
        report['source'] = verify;
        option = option.coachmarkImage;
        report['style'] = option;
        report = golfie.bind(tangon)(oscard, report);
        entity['children'] = report;
        entity = zuuluu.bind(tangon)(michal, entity);
        return entity;
    };
    var _closure1_slot10 = entity;
    entity = global;
    verify = entity.Object;
    option = verify.defineProperty;
    tangon = {};
    entity = true;
    tangon['value'] = entity;
    entity = '__esModule';
    entity = option.bind(verify)(zuuluu, entity, tangon);
    entity = 0;
    tangon = oscard[entity];
    entity = undefined;
    tangon = golfie.bind(entity)(tangon);
    var _closure1_slot3 = tangon;
    tangon = 1;
    golfie = oscard[tangon];
    tangon = argCor;
    tangon = tangon.bind(entity)(golfie);
    var _closure1_slot4 = tangon;
    tangon = 2;
    tangon = oscard[tangon];
    tangon = report.bind(entity)(tangon);
    tangon = tangon.View;
    var _closure1_slot5 = tangon;
    tangon = 3;
    tangon = oscard[tangon];
    tangon = report.bind(entity)(tangon);
    tangon = tangon.UserSettingsSections;
    var _closure1_slot6 = tangon;
    tangon = 4;
    tangon = oscard[tangon];
    tangon = report.bind(entity)(tangon);
    tangon = tangon.ContentDismissActionType;
    var _closure1_slot7 = tangon;
    tangon = 5;
    tangon = oscard[tangon];
    tangon = report.bind(entity)(tangon);
    tangon = tangon.jsx;
    var _closure1_slot8 = tangon;
    tangon = 6;
    tangon = oscard[tangon];
    option = report.bind(entity)(tangon);
    golfie = option.createStyles;
    tangon = {};
    verify = {'alignItems': 'center', 'justifyContent': 'center'};
    tangon['coachmarkImageContainer'] = verify;
    verify = {'width': 200, 'height': 112};
    tangon['coachmarkImage'] = verify;
    tangon = golfie.bind(option)(tangon);
    var _closure1_slot9 = tangon;
    tangon = 15;
    tangon = oscard[tangon];
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/premium/referral_program/hooks/native/useReferralProgramCoachmark.tsx';
    tangon = report.bind(oscard)(tangon);
    michal = function(argFoo) { // Original name: useReferralProgramCoachmark
        _fun00001: for(var _fun00002_ip = 0; ; ) switch(_fun00002_ip) {
 0:
            michal = argFoo;
            michal = michal.disabled;
            golfie = undefined;
            var _closure2_slot0 = golfie;
            var _closure2_slot1 = golfie;
            oscard = _closure1_slot0;
            verify = _closure1_slot2;
            tangon = 9;
            tangon = verify[tangon];
            offset = oscard.bind(golfie)(tangon);
            report = offset.useIsDismissibleContentTypeDismissed;
            option = 10;
            tangon = verify[option];
            tangon = oscard.bind(golfie)(tangon);
            tangon = tangon.DismissibleContent;
            tangon = tangon.REFERRAL_TRIAL_MOBILE_SENDER_COACHMARK;
            tangon = report.bind(offset)(tangon);
            report = 11;
            report = verify[report];
            verify = oscard.bind(golfie)(report);
            oscard = verify.useIsEligibleSenderForReferralProgram;
            report = tangon;
            if(report) { _fun00002_ip = 105; continue _fun00001 }
 102:
            report = michal;
 105:
            tangon = 'useReferralProgramCoachmark';
            oscard = oscard.bind(verify)(tangon, report);
            report = _closure1_slot0;
            verify = _closure1_slot2;
            tangon = 12;
            tangon = verify[tangon];
            report = report.bind(golfie)(tangon);
            tangon = report.useSelectedDismissibleContent;
            if(!oscard) { _fun00002_ip = 186; continue _fun00001 }
 144:
            if(michal) { _fun00002_ip = 186; continue _fun00001 }
 147:
            oscard = _closure1_slot0;
            michal = _closure1_slot2;
            michal = michal[option];
            michal = oscard.bind(golfie)(michal);
            michal = michal.DismissibleContent;
            oscard = michal.REFERRAL_TRIAL_MOBILE_SENDER_COACHMARK;
            michal = new Array(1);
            michal[0] = oscard;
            _fun00002_ip = 190; continue _fun00001;
 186:
            michal = new Array(0);
 190:
            report = tangon.bind(report)(michal);
            tangon = _closure1_slot3;
            michal = 2;
            report = tangon.bind(golfie)(report, michal);
            michal = 0;
            tangon = report[michal];
            michal = 1;
            oscard = report[michal];
            _closure2_slot0 = oscard;
            report = _closure1_slot0;
            michal = _closure1_slot2;
            michal = michal[option];
            michal = report.bind(golfie)(michal);
            michal = michal.DismissibleContent;
            michal = michal.REFERRAL_TRIAL_MOBILE_SENDER_COACHMARK;
            michal = tangon === michal;
            _closure2_slot1 = michal;
            report = _closure1_slot4;
            tangon = report.useMemo;
            zuuluu = new Array(2);
            zuuluu[0] = michal;
            zuuluu[1] = oscard;
            entity = function() {
                entity = {};
                golfie = _closure1_slot0;
                option = _closure1_slot2;
                zuuluu = 13;
                tangon = option[zuuluu];
                oscard = undefined;
                tangon = golfie.bind(oscard)(tangon);
                verify = tangon.intl;
                report = verify.string;
                tangon = option[zuuluu];
                tangon = golfie.bind(oscard)(tangon);
                tangon = tangon.t;
                tangon = tangon.USo4s7;
                tangon = report.bind(verify)(tangon);
                entity['title'] = tangon;
                tangon = option[zuuluu];
                tangon = golfie.bind(oscard)(tangon);
                verify = tangon.intl;
                report = verify.string;
                tangon = option[zuuluu];
                tangon = golfie.bind(oscard)(tangon);
                tangon = tangon.t;
                tangon = tangon.zmcRl5;
                tangon = report.bind(verify)(tangon);
                entity['description'] = tangon;
                tangon = 'bottom';
                entity['position'] = tangon;
                tangon = _closure2_slot1;
                entity['visible'] = tangon;
                tangon = function() { // Original name: onDismiss
                    zuuluu = _closure2_slot0;
                    entity = _closure1_slot7;
                    michal = entity.USER_DISMISS;
                    entity = undefined;
                    michal = zuuluu.bind(entity)(michal);
                    return entity;
                };
                entity['onDismiss'] = tangon;
                tangon = 'experimental_premium-primary';
                entity['buttonVariant'] = tangon;
                tangon = option[zuuluu];
                tangon = golfie.bind(oscard)(tangon);
                report = tangon.intl;
                tangon = report.string;
                zuuluu = option[zuuluu];
                zuuluu = golfie.bind(oscard)(zuuluu);
                zuuluu = zuuluu.t;
                zuuluu = zuuluu.RzWDqa;
                zuuluu = tangon.bind(report)(zuuluu);
                entity['buttonLabel'] = zuuluu;
                zuuluu = function() { // Original name: onButtonPress
                    tangon = _closure1_slot0;
                    zuuluu = _closure1_slot2;
                    entity = 14;
                    zuuluu = zuuluu[entity];
                    entity = undefined;
                    report = tangon.bind(entity)(zuuluu);
                    tangon = report.openUserSettings;
                    zuuluu = {};
                    oscard = _closure1_slot6;
                    oscard = oscard.PREMIUM;
                    zuuluu['screen'] = oscard;
                    zuuluu = tangon.bind(report)(zuuluu);
                    zuuluu = _closure2_slot0;
                    michal = _closure1_slot7;
                    michal = michal.TAKE_ACTION;
                    michal = zuuluu.bind(entity)(michal);
                    return entity;
                };
                entity['onButtonPress'] = zuuluu;
                michal = function() { // Original name: renderImgComponent
                    tangon = _closure1_slot8;
                    zuuluu = _closure1_slot10;
                    michal = undefined;
                    entity = {};
                    entity = tangon.bind(michal)(zuuluu, entity);
                    return entity;
                };
                entity['renderImgComponent'] = michal;
                return entity;
            };
            zuuluu = tangon.bind(report)(entity, zuuluu);
            entity = null;
            if(!michal) { _fun00002_ip = 310; continue _fun00001 }
 301:
            michal = {};
            michal['props'] = zuuluu;
            entity = michal;
 310:
            return entity;
        }
    };
    zuuluu['useReferralProgramCoachmark'] = michal;
    return entity;
})();