// app/modules/guild_member_verification/native/components/form_fields/TermsField.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var1 = metroImportDefault;
    var _closure1_slot1 = var1;
    var _closure1_slot2 = var6;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var7 = var6[var1];
    var4 = metroImportAll;
    var1 = undefined;
    var4 = var4.bind(var1)(var7);
    var4 = 1;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.View;
    var _closure1_slot3 = var4;
    var4 = 2;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var7 = var4.jsx;
    var _closure1_slot4 = var7;
    var4 = var4.jsxs;
    var _closure1_slot5 = var4;
    var4 = 3;
    var4 = var6[var4];
    var8 = var5.bind(var1)(var4);
    var7 = var8.createStyles;
    var4 = {};
    var9 = {'marginVertical': 12, 'flexDirection': 'column'};
    var4['container'] = var9;
    var4 = var7.bind(var8)(var4);
    var _closure1_slot6 = var4;
    var4 = 7;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/guild_member_verification/native/components/form_fields/TermsField.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function TermsField(arg1) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var2 = arg1;
            var1 = var2.field;
            var9 = var2.onChange;
            var11 = var2.rulesChannelId;
            var2 = _closure1_slot6;
            var4 = undefined;
            var5 = var2.bind(var4)();
            var12 = var1.values;
            var1 = var1.response;
            var2 = null;
            var10 = var2 != var1;
            if(!var10) { _fun0001_ip = 2; continue _fun0001 }
case 3:
            var10 = var1;
case 2:
            var3 = _closure1_slot5;
            var2 = _closure1_slot3;
            var1 = {};
            var5 = var5.container;
            var1['style'] = var5;
            var8 = _closure1_slot4;
            var7 = _closure1_slot1;
            var14 = _closure1_slot2;
            var5 = 4;
            var5 = var14[var5];
            var7 = var7.bind(var4)(var5);
            var5 = {};
            var5['rules'] = var12;
            var5['rulesChannelId'] = var11;
            var7 = var8.bind(var4)(var7, var5);
            var5 = new Array(2);
            var5[0] = var7;
            var13 = _closure1_slot0;
            var6 = 5;
            var6 = var14[var6];
            var6 = var13.bind(var4)(var6);
            var7 = var6.TableCheckboxRow;
            var6 = {'start': true, 'end': true};
            var6['checked'] = var10;
            var10 = 6;
            var11 = var14[var10];
            var11 = var13.bind(var4)(var11);
            var12 = var11.intl;
            var11 = var12.string;
            var10 = var14[var10];
            var10 = var13.bind(var4)(var10);
            var10 = var10.t;
            var10 = var10.2EXfGJ;
            var10 = var11.bind(var12)(var10);
            var6['label'] = var10;
            var6['onPress'] = var9;
            var6 = var8.bind(var4)(var7, var6);
            var5[1] = var6;
            var1['children'] = var5;
            var1 = var3.bind(var4)(var2, var1);
            return var1;
        }
    };
    var3['default'] = var2;
    return var1;
})();