// app/modules/user_profile/native/UserProfileEditNoteModal.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var1 = metroImportDefault;
    var _closure1_slot1 = var1;
    var _closure1_slot2 = var6;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var7 = var6[var1];
    var4 = metroImportAll;
    var1 = undefined;
    var4 = var4.bind(var1)(var7);
    var4 = 1;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.jsx;
    var _closure1_slot3 = var4;
    var4 = 8;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/user_profile/native/UserProfileEditNoteModal.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function UserProfileEditNoteModal(arg1) {
        var1 = arg1;
        var2 = var1.userId;
        var _closure2_slot0 = var2;
        var2 = var1.onSave;
        var _closure2_slot1 = var2;
        var1 = var1.onBack;
        var _closure2_slot2 = var1;
        var10 = function handleClose() {
            _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
 0:
                var3 = _closure1_slot1;
                var2 = _closure1_slot2;
                var1 = 2;
                var2 = var2[var1];
                var1 = undefined;
                var3 = var3.bind(var1)(var2);
                var2 = var3.pop;
                var2 = var2.bind(var3)();
                var4 = _closure2_slot2;
                var3 = null;
                if(!(var3 != var4)) { _fun0001_ip = 56; continue _fun0001 }
 48:
                var2 = _closure2_slot2;
                var2 = var2.bind(var1)();
 56:
                return var1;
            }
        };
        var _closure2_slot3 = var10;
        var4 = _closure1_slot3;
        var9 = _closure1_slot0;
        var11 = _closure1_slot2;
        var1 = 3;
        var1 = var11[var1];
        var3 = undefined;
        var1 = var9.bind(var3)(var1);
        var2 = var1.Navigator;
        var1 = {};
        var5 = 'root';
        var1['initialRouteName'] = var5;
        var5 = {};
        var6 = {};
        var8 = 4;
        var12 = var11[var8];
        var12 = var9.bind(var3)(var12);
        var13 = var12.intl;
        var12 = var13.string;
        var8 = var11[var8];
        var8 = var9.bind(var3)(var8);
        var8 = var8.t;
        var8 = var8.sHHsOD;
        var8 = var12.bind(var13)(var8);
        var6['title'] = var8;
        var8 = function headerTitle() {
            var4 = _closure1_slot3;
            var8 = _closure1_slot0;
            var9 = _closure1_slot2;
            var1 = 5;
            var1 = var9[var1];
            var3 = undefined;
            var1 = var8.bind(var3)(var1);
            var2 = var1.Text;
            var1 = {'variant': 'redesign/heading-18/bold', 'accessibilityRole': 'header'};
            var5 = 4;
            var6 = var9[var5];
            var6 = var8.bind(var3)(var6);
            var7 = var6.intl;
            var6 = var7.string;
            var5 = var9[var5];
            var5 = var8.bind(var3)(var5);
            var5 = var5.t;
            var5 = var5.sHHsOD;
            var5 = var6.bind(var7)(var5);
            var1['children'] = var5;
            var1 = var4.bind(var3)(var2, var1);
            return var1;
        };
        var6['headerTitle'] = var8;
        var8 = 6;
        var8 = var11[var8];
        var9 = var9.bind(var3)(var8);
        var8 = var9.getHeaderCloseButton;
        var8 = var8.bind(var9)(var10);
        var6['headerLeft'] = var8;
        var7 = function render() {
            var3 = _closure1_slot0;
            var4 = _closure1_slot2;
            var2 = 7;
            var2 = var4[var2];
            var4 = undefined;
            var2 = var3.bind(var4)(var2);
            var3 = var2.default;
            var2 = _closure1_slot3;
            var1 = {};
            var6 = _closure2_slot0;
            var1['userId'] = var6;
            var6 = _closure2_slot1;
            var1['onSave'] = var6;
            var5 = _closure2_slot3;
            var1['onClose'] = var5;
            var1 = var2.bind(var4)(var3, var1);
            return var1;
        };
        var6['render'] = var7;
        var5['root'] = var6;
        var1['screens'] = var5;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var3['default'] = var2;
    return var1;
})();