// app/modules/video_backgrounds/getDefaultBackgroundData.native.tsx
export default (function(_, argBar, __, ___, ____, argFre, argPlu) {
    report = argBar;
    zuuluu = argFre;
    oscard = argPlu;
    entity = global;
    option = entity.Object;
    golfie = option.defineProperty;
    tangon = {};
    entity = true;
    tangon['value'] = entity;
    entity = '__esModule';
    entity = golfie.bind(option)(zuuluu, entity, tangon);
    entity = 0;
    tangon = oscard[entity];
    entity = undefined;
    tangon = report.bind(entity)(tangon);
    golfie = tangon.DefaultVideoBackground;
    var _closure1_slot0 = golfie;
    tangon = {'id': null, 'source': '', 'name': ''};
    golfie = golfie.OPTION_1;
    tangon['id'] = golfie;
    var _closure1_slot1 = tangon;
    tangon = 1;
    tangon = oscard[tangon];
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/video_backgrounds/getDefaultBackgroundData.native.tsx';
    tangon = report.bind(oscard)(tangon);
    michal = function() { // Original name: _default
        entity = {};
        michal = _closure1_slot0;
        tangon = michal.OPTION_1;
        zuuluu = _closure1_slot1;
        entity[tangon] = zuuluu;
        tangon = michal.OPTION_2;
        entity[tangon] = zuuluu;
        tangon = michal.OPTION_3;
        entity[tangon] = zuuluu;
        tangon = michal.OPTION_4;
        entity[tangon] = zuuluu;
        tangon = michal.OPTION_7;
        entity[tangon] = zuuluu;
        tangon = michal.OPTION_8;
        entity[tangon] = zuuluu;
        tangon = michal.OPTION_9;
        entity[tangon] = zuuluu;
        michal = michal.OPTION_10;
        entity[michal] = zuuluu;
        return entity;
    };
    zuuluu['default'] = michal;
    return entity;
})();