// app/modules/channel_prompts/GamingStatsSetupExperiment.tsx
export default (function(_, argBar, __, ___, ____, argFred, argPlugh) {
    report = argBar;
    zulu = argFred;
    oscar = argPlugh;
    entity = global;
    golf = entity.Object;
    tango = golf.defineProperty;
    mike = {};
    yankee = true;
    mike['value'] = yankee;
    entity = '__esModule';
    entity = tango.bind(golf)(zulu, entity, mike);
    entity = 0;
    mike = oscar[entity];
    entity = undefined;
    options = report.bind(entity)(mike);
    golf = options.createExperiment;
    mike = {'kind': 'guild', 'id': '2023-09_gaming_stats_setup', 'label': 'Gaming stats exposure setup'};
    tango = {};
    verify = false;
    tango['trackGamingStats'] = verify;
    mike['defaultConfig'] = tango;
    offset = {'id': 1, 'label': 'trigger gaming stats data'};
    tango = 1;
    verify = {};
    verify['trackGamingStats'] = yankee;
    offset['config'] = verify;
    verify = new Array(1);
    verify[0] = offset;
    mike['treatments'] = verify;
    mike = golf.bind(options)(mike);
    tango = oscar[tango];
    oscar = report.bind(entity)(tango);
    report = oscar.fileFinishedImporting;
    tango = 'modules/channel_prompts/GamingStatsSetupExperiment.tsx';
    tango = report.bind(oscar)(tango);
    zulu['GamingStatsSetupExperiment'] = mike;
    return entity;
})();