// app/modules/user_settings/native/privacy_and_safety/SettingsSecureFramesVerificationsScreen.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var7 = metroImportDefault;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var7;
    var _closure1_slot2 = var6;
    var1 = function VerificationListItem(arg1) {
        var4 = arg1;
        var16 = var4.index;
        var3 = var4.userId;
        var _closure2_slot0 = var3;
        var2 = var4.verification;
        var _closure2_slot1 = var2;
        var6 = var4.start;
        var5 = var4.end;
        var9 = _closure1_slot3;
        var7 = var9.useCallback;
        var4 = new Array(2);
        var4[0] = var3;
        var3 = var2.verifiedKey;
        var4[1] = var3;
        var3 = function() {
            var3 = _closure1_slot0;
            var2 = _closure1_slot2;
            var1 = 6;
            var2 = var2[var1];
            var1 = undefined;
            var5 = var3.bind(var1)(var2);
            var4 = var5.deletePersistentVerification;
            var3 = _closure2_slot0;
            var2 = _closure2_slot1;
            var2 = var2.verifiedKey;
            var2 = var4.bind(var5)(var3, var2);
            return var1;
        };
        var10 = var7.bind(var9)(var3, var4);
        var4 = _closure1_slot3;
        var3 = var4.useMemo;
        var7 = var2.timestamp;
        var2 = new Array(1);
        var2[0] = var7;
        var1 = function() {
            var3 = _closure1_slot0;
            var2 = _closure1_slot2;
            var1 = 6;
            var2 = var2[var1];
            var1 = undefined;
            var3 = var3.bind(var1)(var2);
            var2 = var3.getSecureFramesUserVerifiedTimestamp;
            var1 = _closure2_slot1;
            var1 = var1.timestamp;
            var1 = var2.bind(var3)(var1);
            return var1;
        };
        var7 = var3.bind(var4)(var1, var2);
        var4 = _closure1_slot7;
        var9 = _closure1_slot0;
        var11 = _closure1_slot2;
        var1 = 7;
        var1 = var11[var1];
        var3 = undefined;
        var1 = var9.bind(var3)(var1);
        var2 = var1.TableRow;
        var1 = {};
        var12 = 8;
        var13 = var11[var12];
        var13 = var9.bind(var3)(var13);
        var15 = var13.intl;
        var14 = var15.formatToPlainString;
        var12 = var11[var12];
        var12 = var9.bind(var3)(var12);
        var12 = var12.t;
        var13 = var12.N4qBBA;
        var12 = {};
        var12['index'] = var16;
        var12 = var14.bind(var15)(var13, var12);
        var1['label'] = var12;
        var1['subLabel'] = var7;
        var1['start'] = var6;
        var1['end'] = var5;
        var7 = _closure1_slot7;
        var5 = 9;
        var5 = var11[var5];
        var5 = var9.bind(var3)(var5);
        var6 = var5.PressableHighlight;
        var5 = {};
        var5['onPress'] = var10;
        var10 = _closure1_slot7;
        var8 = 10;
        var8 = var11[var8];
        var8 = var9.bind(var3)(var8);
        var9 = var8.XSmallIcon;
        var8 = {};
        var8 = var10.bind(var3)(var9, var8);
        var5['children'] = var8;
        var5 = var7.bind(var3)(var6, var5);
        var1['trailing'] = var5;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var _closure1_slot10 = var1;
    var1 = function SectionListItem(arg1) {
        var1 = arg1;
        var5 = var1.title;
        var2 = _closure1_slot8;
        var4 = undefined;
        var6 = var2.bind(var4)();
        var3 = _closure1_slot7;
        var2 = _closure1_slot0;
        var7 = _closure1_slot2;
        var1 = 11;
        var1 = var7[var1];
        var1 = var2.bind(var4)(var1);
        var2 = var1.Text;
        var1 = {'style': null, 'variant': 'text-sm/semibold', 'color': 'header-secondary'};
        var6 = var6.section;
        var1['style'] = var6;
        var1['children'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var _closure1_slot11 = var1;
    var1 = function renderItem(arg1) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
 0:
            var1 = arg1;
            var1 = var1.item;
            var4 = var1.type;
            var3 = _closure1_slot9;
            var3 = var3.VERIFICATION;
            if(!(var3 !== var4)) { _fun0001_ip = 78; continue _fun0001 }
 30:
            var3 = _closure1_slot9;
            var3 = var3.SECTION;
            if(!(var3 !== var4)) { _fun0001_ip = 48; continue _fun0001 }
 44:
            var3 = undefined;
            return var3;
 48:
            var6 = _closure1_slot7;
            var5 = _closure1_slot11;
            var4 = {};
            var8 = var4;
            var7 = var1;
            var3 = copyDataProperties(var8, var7);
            var3 = undefined;
            var3 = var6.bind(var3)(var5, var4);
            return var3;
 78:
            var4 = _closure1_slot7;
            var3 = _closure1_slot10;
            var2 = {};
            var8 = var2;
            var7 = var1;
            var1 = copyDataProperties(var8, var7);
            var1 = undefined;
            var1 = var4.bind(var1)(var3, var2);
            return var1;
        }
    };
    var _closure1_slot12 = var1;
    var1 = function getItemType(arg1) {
        var1 = arg1;
        var1 = var1.type;
        return var1;
    };
    var _closure1_slot13 = var1;
    var1 = function keyExtractor(arg1) {
        _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
 0:
            var1 = arg1;
            var3 = var1.type;
            var4 = _closure1_slot9;
            var4 = var4.VERIFICATION;
            if(!(var4 !== var3)) { _fun0002_ip = 50; continue _fun0002 }
 25:
            var2 = _closure1_slot9;
            var2 = var2.SECTION;
            if(!(var2 !== var3)) { _fun0002_ip = 43; continue _fun0002 }
 39:
            var2 = undefined;
            return var2;
 43:
            var2 = var1.title;
            return var2;
 50:
            var1 = var1.verification;
            var1 = var1.verifiedKey;
            return var1;
        }
    };
    var _closure1_slot14 = var1;
    var1 = function ClearVerificationsListFooter(arg1) {
        var2 = arg1;
        var5 = var2.userId;
        var _closure2_slot0 = var5;
        var4 = _closure1_slot3;
        var3 = var4.useCallback;
        var2 = new Array(1);
        var2[0] = var5;
        var1 = function() {
            var3 = _closure1_slot0;
            var2 = _closure1_slot2;
            var1 = 6;
            var2 = var2[var1];
            var1 = undefined;
            var4 = var3.bind(var1)(var2);
            var3 = var4.deleteUserPersistentVerifications;
            var2 = _closure2_slot0;
            var2 = var3.bind(var4)(var2);
            return var1;
        };
        var5 = var3.bind(var4)(var1, var2);
        var4 = _closure1_slot7;
        var12 = _closure1_slot0;
        var13 = _closure1_slot2;
        var1 = 7;
        var1 = var13[var1];
        var3 = undefined;
        var1 = var12.bind(var3)(var1);
        var2 = var1.TableRow;
        var1 = {};
        var11 = _closure1_slot7;
        var6 = 11;
        var8 = var13[var6];
        var8 = var12.bind(var3)(var8);
        var10 = var8.Text;
        var8 = {'variant': 'text-md/semibold', 'color': 'text-danger'};
        var9 = 8;
        var14 = var13[var9];
        var14 = var12.bind(var3)(var14);
        var16 = var14.intl;
        var15 = var16.string;
        var14 = var13[var9];
        var14 = var12.bind(var3)(var14);
        var14 = var14.t;
        var14 = var14.2xL5lp;
        var14 = var15.bind(var16)(var14);
        var8['children'] = var14;
        var8 = var11.bind(var3)(var10, var8);
        var1['label'] = var8;
        var8 = _closure1_slot7;
        var6 = var13[var6];
        var6 = var12.bind(var3)(var6);
        var7 = var6.Text;
        var6 = {'variant': 'text-xs/medium', 'color': 'text-secondary'};
        var10 = var13[var9];
        var10 = var12.bind(var3)(var10);
        var11 = var10.intl;
        var10 = var11.string;
        var9 = var13[var9];
        var9 = var12.bind(var3)(var9);
        var9 = var9.t;
        var9 = var9.kgAfXF;
        var9 = var10.bind(var11)(var9);
        var6['children'] = var9;
        var6 = var8.bind(var3)(var7, var6);
        var1['subLabel'] = var6;
        var1['onPress'] = var5;
        var5 = true;
        var1['start'] = var5;
        var1['end'] = var5;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var _closure1_slot15 = var1;
    var1 = global;
    var9 = var1.Object;
    var8 = var9.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var8.bind(var9)(var3, var1, var4);
    var1 = 0;
    var8 = var6[var1];
    var4 = metroImportAll;
    var1 = undefined;
    var4 = var4.bind(var1)(var8);
    var _closure1_slot3 = var4;
    var10 = 1;
    var4 = var6[var10];
    var4 = var5.bind(var1)(var4);
    var4 = var4.View;
    var _closure1_slot4 = var4;
    var4 = 2;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.TABLE_ROW_HEIGHT;
    var _closure1_slot5 = var4;
    var4 = 3;
    var4 = var6[var4];
    var4 = var7.bind(var1)(var4);
    var _closure1_slot6 = var4;
    var4 = 4;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.jsx;
    var _closure1_slot7 = var4;
    var4 = 5;
    var4 = var6[var4];
    var8 = var5.bind(var1)(var4);
    var7 = var8.createStyles;
    var4 = {};
    var9 = {};
    var9['flexGrow'] = var10;
    var4['list'] = var9;
    var10 = 32;
    var9 = {'paddingVertical': 32, 'paddingHorizontal': 16};
    var4['listContent'] = var9;
    var9 = {};
    var9['marginTop'] = var10;
    var4['listFooter'] = var9;
    var9 = {};
    var10 = 8;
    var9['marginBottom'] = var10;
    var4['section'] = var9;
    var4 = var7.bind(var8)(var4);
    var _closure1_slot8 = var4;
    var4 = {};
    var7 = 'VERIFICATION';
    var4['VERIFICATION'] = var7;
    var7 = 'SECTION';
    var4['SECTION'] = var7;
    var _closure1_slot9 = var4;
    var4 = 19;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/user_settings/native/privacy_and_safety/SettingsSecureFramesVerificationsScreen.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function SettingsSecureFramesVerificationsScreen() {
        var2 = _closure1_slot8;
        var4 = undefined;
        var11 = var2.bind(var4)();
        var6 = _closure1_slot0;
        var9 = _closure1_slot2;
        var2 = 12;
        var2 = var9[var2];
        var3 = var6.bind(var4)(var2);
        var2 = var3.useSettingNavigationRoute;
        var2 = var2.bind(var3)();
        var2 = var2.params;
        var13 = var2.userId;
        var _closure2_slot0 = var13;
        var2 = 13;
        var2 = var9[var2];
        var3 = var6.bind(var4)(var2);
        var2 = var3.useNavigation;
        var12 = var2.bind(var3)();
        var _closure2_slot1 = var12;
        var2 = 14;
        var2 = var9[var2];
        var7 = var6.bind(var4)(var2);
        var5 = var7.useStateFromStores;
        var2 = _closure1_slot6;
        var3 = new Array(1);
        var3[0] = var2;
        var2 = function() {
            var3 = _closure1_slot6;
            var2 = var3.getUser;
            var1 = _closure2_slot0;
            var1 = var2.bind(var3)(var1);
            return var1;
        };
        var7 = var5.bind(var7)(var3, var2);
        var3 = _closure1_slot1;
        var2 = 15;
        var2 = var9[var2];
        var5 = var3.bind(var4)(var2);
        var3 = var5.getFormattedName;
        var2 = false;
        var2 = var3.bind(var5)(var7, var2);
        var _closure2_slot2 = var2;
        var5 = _closure1_slot3;
        var3 = var5.useLayoutEffect;
        var2 = function() {
            var4 = _closure2_slot1;
            var3 = var4.setOptions;
            var2 = {};
            var9 = _closure1_slot0;
            var10 = _closure1_slot2;
            var6 = 8;
            var7 = var10[var6];
            var1 = undefined;
            var7 = var9.bind(var1)(var7);
            var8 = var7.intl;
            var7 = var8.string;
            var6 = var10[var6];
            var6 = var9.bind(var1)(var6);
            var6 = var6.t;
            var6 = var6.5b3FND;
            var14 = var7.bind(var8)(var6);
            var12 = _closure2_slot2;
            var5 = global;
            var5 = var5.HermesInternal;
            var8 = var5.concat;
            var15 = '';
            var13 = ' (';
            var11 = ')';
            var5 = var15[var8](var14, var13, var12, var11, var10);
            var2['title'] = var5;
            var5 = function headerTitle() {
                var4 = _closure1_slot7;
                var8 = _closure1_slot0;
                var9 = _closure1_slot2;
                var1 = 16;
                var1 = var9[var1];
                var3 = undefined;
                var1 = var8.bind(var3)(var1);
                var2 = var1.GenericHeaderTitle;
                var1 = {};
                var5 = 8;
                var6 = var9[var5];
                var6 = var8.bind(var3)(var6);
                var7 = var6.intl;
                var6 = var7.string;
                var5 = var9[var5];
                var5 = var8.bind(var3)(var5);
                var5 = var5.t;
                var5 = var5.5b3FND;
                var5 = var6.bind(var7)(var5);
                var1['title'] = var5;
                var5 = _closure2_slot2;
                var1['subtitle'] = var5;
                var1 = var4.bind(var3)(var2, var1);
                return var1;
            };
            var2['headerTitle'] = var5;
            var2 = var3.bind(var4)(var2);
            return var1;
        };
        var2 = var3.bind(var5)(var2);
        var2 = 17;
        var2 = var9[var2];
        var3 = var6.bind(var4)(var2);
        var2 = var3.useSecureFramesUserVerifiedKeys;
        var7 = var2.bind(var3)(var13);
        var _closure2_slot3 = var7;
        var8 = _closure1_slot3;
        var5 = var8.useMemo;
        var3 = new Array(2);
        var3[0] = var13;
        var3[1] = var7;
        var2 = function() {
            var1 = new Array(0);
            var _closure3_slot0 = var1;
            var5 = var1.push;
            var3 = {};
            var6 = _closure1_slot9;
            var6 = var6.SECTION;
            var3['type'] = var6;
            var7 = _closure1_slot0;
            var10 = _closure1_slot2;
            var4 = 8;
            var8 = var10[var4];
            var6 = undefined;
            var8 = var7.bind(var6)(var8);
            var9 = var8.intl;
            var8 = var9.formatToPlainString;
            var4 = var10[var4];
            var4 = var7.bind(var6)(var4);
            var4 = var4.t;
            var7 = var4./MBjYG;
            var6 = {};
            var4 = _closure2_slot3;
            var10 = var4.length;
            var6['count'] = var10;
            var6 = var8.bind(var9)(var7, var6);
            var3['title'] = var6;
            var3 = var5.bind(var1)(var3);
            var3 = var4.forEach;
            var2 = function(arg1, arg2) {
                var5 = arg2;
                var3 = _closure3_slot0;
                var2 = var3.push;
                var1 = {};
                var4 = _closure1_slot9;
                var4 = var4.VERIFICATION;
                var1['type'] = var4;
                var4 = arg1;
                var1['verification'] = var4;
                var6 = 1;
                var4 = var5 + var6;
                var1['index'] = var4;
                var7 = _closure2_slot0;
                var1['userId'] = var7;
                var7 = 0;
                var7 = var7 === var5;
                var1['start'] = var7;
                var4 = _closure2_slot3;
                var4 = var4.length;
                var4 = var4 - var6;
                var4 = var5 === var4;
                var1['end'] = var4;
                var1 = var2.bind(var3)(var1);
                var1 = undefined;
                return var1;
            };
            var2 = var3.bind(var4)(var2);
            return var1;
        };
        var8 = var5.bind(var8)(var2, var3);
        var5 = _closure1_slot3;
        var3 = var5.useEffect;
        var2 = new Array(2);
        var2[0] = var12;
        var2[1] = var7;
        var1 = function() {
            _fun0003: for(var _fun0003_ip = 0; ; ) switch(_fun0003_ip) {
 0:
                var2 = _closure2_slot3;
                var3 = var2.length;
                var2 = 0;
                if(!(var2 === var3)) { _fun0003_ip = 32; continue _fun0003 }
 18:
                var2 = _closure2_slot1;
                var1 = var2.pop;
                var1 = var1.bind(var2)();
 32:
                var1 = undefined;
                return var1;
            }
        };
        var1 = var3.bind(var5)(var1, var2);
        var3 = _closure1_slot7;
        var2 = _closure1_slot4;
        var1 = {};
        var5 = var11.list;
        var1['style'] = var5;
        var7 = _closure1_slot7;
        var5 = 18;
        var5 = var9[var5];
        var5 = var6.bind(var4)(var5);
        var6 = var5.FlashList;
        var5 = {};
        var9 = _closure1_slot14;
        var5['keyExtractor'] = var9;
        var9 = _closure1_slot13;
        var5['getItemType'] = var9;
        var9 = _closure1_slot12;
        var5['renderItem'] = var9;
        var5['data'] = var8;
        var8 = _closure1_slot5;
        var5['estimatedItemSize'] = var8;
        var8 = var11.listContent;
        var5['contentContainerStyle'] = var8;
        var9 = _closure1_slot7;
        var8 = {};
        var11 = var11.listFooter;
        var8['style'] = var11;
        var12 = _closure1_slot7;
        var11 = _closure1_slot15;
        var10 = {};
        var10['userId'] = var13;
        var10 = var12.bind(var4)(var11, var10);
        var8['children'] = var10;
        var8 = var9.bind(var4)(var2, var8);
        var5['ListFooterComponent'] = var8;
        var5 = var7.bind(var4)(var6, var5);
        var1['children'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var3['default'] = var2;
    return var1;
})();