// app/modules/billing/native/subscription/useToggleOnIAPSuccess.tsx
export default (function(native1, native2, native3, native4, native5, native6, native7) {
    var6 = native3;
    var3 = native6;
    var5 = native7;
    var _closure1_slot0 = var6;
    var _closure1_slot1 = var5;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var4 = var5[var1];
    var1 = undefined;
    var4 = var6.bind(var1)(var4);
    var _closure1_slot2 = var4;
    var4 = 1;
    var6 = var5[var4];
    var4 = native4;
    var4 = var4.bind(var1)(var6);
    var _closure1_slot3 = var4;
    var4 = 3;
    var5 = var5[var4];
    var4 = native2;
    var6 = var4.bind(var1)(var5);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/billing/native/subscription/useToggleOnIAPSuccess.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function useToggleOnIAPSuccess() {
        var1 = function toggleFlip() {
            var3 = _closure2_slot0;
            var1 = undefined;
            var2 = function(arg1) {
                var1 = arg1;
                var1 = !var1;
                return var1;
            };
            var2 = var3.bind(var1)(var2);
            return var1;
        };
        var _closure2_slot1 = var1;
        var5 = _closure1_slot3;
        var4 = var5.useState;
        var3 = false;
        var6 = var4.bind(var5)(var3);
        var4 = _closure1_slot2;
        var3 = undefined;
        var1 = 2;
        var4 = var4.bind(var3)(var6, var1);
        var1 = 0;
        var1 = var4[var1];
        var3 = 1;
        var3 = var4[var3];
        var _closure2_slot0 = var3;
        var4 = var5.useEffect;
        var3 = function() {
            var3 = _closure1_slot0;
            var2 = _closure1_slot1;
            var1 = 2;
            var2 = var2[var1];
            var1 = undefined;
            var4 = var3.bind(var1)(var2);
            var3 = var4.subscribe;
            var2 = _closure2_slot1;
            var1 = 'IAP_PURCHASE_PRODUCT_SUCCESS';
            var1 = var3.bind(var4)(var1, var2);
            var1 = function() {
                var3 = _closure1_slot0;
                var2 = _closure1_slot1;
                var1 = 2;
                var2 = var2[var1];
                var1 = undefined;
                var5 = var3.bind(var1)(var2);
                var4 = var5.unsubscribe;
                var3 = _closure2_slot1;
                var2 = 'IAP_PURCHASE_PRODUCT_SUCCESS';
                var2 = var4.bind(var5)(var2, var3);
                return var1;
            };
            return var1;
        };
        var2 = new Array(0);
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['default'] = var2;
    return var1;
})();