// app/modules/voice_calls/VoiceActivityNotificationExperiment.tsx
export default (function(argFoo, argBar, _, __, ___, argFre, argPlu) {
    oscard = argBar;
    zuuluu = argFre;
    golfie = argPlu;
    entity = global;
    option = entity.Object;
    report = option.defineProperty;
    tangon = {};
    foxtra = true;
    tangon['value'] = foxtra;
    entity = '__esModule';
    entity = report.bind(option)(zuuluu, entity, tangon);
    entity = 0;
    tangon = golfie[entity];
    entity = undefined;
    verify = oscard.bind(entity)(tangon);
    option = verify.createExperiment;
    tangon = {'kind': 'user', 'id': '2025-07_voice_activity_notifications', 'label': 'Voice Activity Notifications'};
    report = {};
    offset = false;
    report['enabled'] = offset;
    tangon['defaultConfig'] = report;
    yankee = {'id': 1, 'label': '70% Affinity'};
    report = 1;
    offset = {};
    offset['enabled'] = foxtra;
    yankee['config'] = offset;
    offset = new Array(2);
    offset[0] = yankee;
    yankee = {'id': 2, 'label': '80% Affinity'};
    romeon = {};
    romeon['enabled'] = foxtra;
    yankee['config'] = romeon;
    offset[1] = yankee;
    tangon['treatments'] = offset;
    tangon = option.bind(verify)(tangon);
    var _closure1_slot0 = tangon;
    report = golfie[report];
    golfie = oscard.bind(entity)(report);
    oscard = golfie.fileFinishedImporting;
    report = 'modules/voice_calls/VoiceActivityNotificationExperiment.tsx';
    report = oscard.bind(golfie)(report);
    zuuluu['VoiceActivityNotificationsExperiment'] = tangon;
    tangon = function(argFoo) { // Original name: useVoiceActivityNotificationsExperiment
        tangon = _closure1_slot0;
        zuuluu = tangon.useExperiment;
        michal = {};
        entity = argFoo;
        michal['location'] = entity;
        entity = {};
        report = false;
        entity['autoTrackExposure'] = report;
        entity = zuuluu.bind(tangon)(michal, entity);
        return entity;
    };
    zuuluu['useVoiceActivityNotificationsExperiment'] = tangon;
    michal = function(argFoo) { // Original name: isEligibleForVoiceActivityNotifications
        zuuluu = _closure1_slot0;
        michal = zuuluu.getCurrentConfig;
        entity = {};
        tangon = argFoo;
        entity['location'] = tangon;
        entity = michal.bind(zuuluu)(entity);
        entity = entity.enabled;
        return entity;
    };
    zuuluu['isEligibleForVoiceActivityNotifications'] = michal;
    return entity;
})();