// app/modules/voice_calls/VoiceActivityNotificationExperiment.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var6 = require;
    var3 = exports;
    var7 = dependencyMap;
    var1 = global;
    var8 = var1.Object;
    var5 = var8.defineProperty;
    var4 = {};
    var13 = true;
    var4['value'] = var13;
    var1 = '__esModule';
    var1 = var5.bind(var8)(var3, var1, var4);
    var1 = 0;
    var4 = var7[var1];
    var1 = undefined;
    var9 = var6.bind(var1)(var4);
    var8 = var9.createExperiment;
    var4 = {'kind': 'user', 'id': '2025-07_voice_activity_notifications', 'label': 'Voice Activity Notifications'};
    var5 = {};
    var10 = false;
    var5['enabled'] = var10;
    var4['defaultConfig'] = var5;
    var11 = {'id': 1, 'label': '70% Affinity'};
    var5 = 1;
    var10 = {};
    var10['enabled'] = var13;
    var11['config'] = var10;
    var10 = new Array(2);
    var10[0] = var11;
    var11 = {'id': 2, 'label': '80% Affinity'};
    var12 = {};
    var12['enabled'] = var13;
    var11['config'] = var12;
    var10[1] = var11;
    var4['treatments'] = var10;
    var4 = var8.bind(var9)(var4);
    var _closure1_slot0 = var4;
    var5 = var7[var5];
    var7 = var6.bind(var1)(var5);
    var6 = var7.fileFinishedImporting;
    var5 = 'modules/voice_calls/VoiceActivityNotificationExperiment.tsx';
    var5 = var6.bind(var7)(var5);
    var3['VoiceActivityNotificationsExperiment'] = var4;
    var4 = function useVoiceActivityNotificationsExperiment(arg1) {
        var4 = _closure1_slot0;
        var3 = var4.useExperiment;
        var2 = {};
        var1 = arg1;
        var2['location'] = var1;
        var1 = {};
        var5 = false;
        var1['autoTrackExposure'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var3['useVoiceActivityNotificationsExperiment'] = var4;
    var2 = function isEligibleForVoiceActivityNotifications(arg1) {
        var3 = _closure1_slot0;
        var2 = var3.getCurrentConfig;
        var1 = {};
        var4 = arg1;
        var1['location'] = var4;
        var1 = var2.bind(var3)(var1);
        var1 = var1.enabled;
        return var1;
    };
    var3['isEligibleForVoiceActivityNotifications'] = var2;
    return var1;
})();