// app/modules/search_v2/native/components/list/rows/Separators.tsx
export default (function(_, argBar, __, argCor, ___, argFre, argPlu) {
    report = argBar;
    zuuluu = argFre;
    oscard = argPlu;
    entity = global;
    option = entity.Object;
    golfie = option.defineProperty;
    tangon = {};
    entity = true;
    tangon['value'] = entity;
    entity = '__esModule';
    entity = golfie.bind(option)(zuuluu, entity, tangon);
    entity = 0;
    golfie = oscard[entity];
    tangon = argCor;
    entity = undefined;
    tangon = tangon.bind(entity)(golfie);
    tangon = 1;
    tangon = oscard[tangon];
    tangon = report.bind(entity)(tangon);
    tangon = tangon.View;
    var _closure1_slot0 = tangon;
    tangon = 2;
    tangon = oscard[tangon];
    tangon = report.bind(entity)(tangon);
    yankee = tangon.MEDIA_ITEM_GAP_WIDTH;
    romeon = tangon.FILES_OR_LINKS_GAP_WIDTH;
    tangon = 3;
    tangon = oscard[tangon];
    tangon = report.bind(entity)(tangon);
    tangon = tangon.jsx;
    var _closure1_slot1 = tangon;
    offset = 4;
    tangon = oscard[offset];
    option = report.bind(entity)(tangon);
    golfie = option.createStyles;
    tangon = {};
    verify = {};
    verify['height'] = romeon;
    tangon['filesOrLinksSeparator'] = verify;
    verify = {};
    verify['height'] = yankee;
    tangon['mediaSeparator'] = verify;
    verify = {};
    verify['height'] = offset;
    tangon['messageSeparator'] = verify;
    tangon = golfie.bind(option)(tangon);
    var _closure1_slot2 = tangon;
    tangon = 5;
    tangon = oscard[tangon];
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/search_v2/native/components/list/rows/Separators.tsx';
    tangon = report.bind(oscard)(tangon);
    tangon = function() { // Original name: MessageVerticalSeparator
        michal = _closure1_slot2;
        tangon = undefined;
        report = michal.bind(tangon)();
        zuuluu = _closure1_slot1;
        michal = _closure1_slot0;
        entity = {};
        report = report.messageSeparator;
        entity['style'] = report;
        entity = zuuluu.bind(tangon)(michal, entity);
        return entity;
    };
    zuuluu['MessageVerticalSeparator'] = tangon;
    tangon = function() { // Original name: MediaVerticalSeparator
        michal = _closure1_slot2;
        tangon = undefined;
        report = michal.bind(tangon)();
        zuuluu = _closure1_slot1;
        michal = _closure1_slot0;
        entity = {};
        report = report.mediaSeparator;
        entity['style'] = report;
        entity = zuuluu.bind(tangon)(michal, entity);
        return entity;
    };
    zuuluu['MediaVerticalSeparator'] = tangon;
    michal = function() { // Original name: CardVerticalSeparator
        michal = _closure1_slot2;
        tangon = undefined;
        report = michal.bind(tangon)();
        zuuluu = _closure1_slot1;
        michal = _closure1_slot0;
        entity = {};
        report = report.filesOrLinksSeparator;
        entity['style'] = report;
        entity = zuuluu.bind(tangon)(michal, entity);
        return entity;
    };
    zuuluu['CardVerticalSeparator'] = michal;
    return entity;
})();