// app/modules/chat_input/native/guard/ChatInputGuardGuildCommunicationDisabled.tsx
export default (function(argFoo, argBar, argBaz, argCorge, _, argFred, argPlugh) {
    report = argBar;
    zulu = argFred;
    oscar = argPlugh;
    var _closure1_slot0 = report;
    entity = argBaz;
    var _closure1_slot1 = entity;
    var _closure1_slot2 = oscar;
    entity = global;
    options = entity.Object;
    golf = options.defineProperty;
    tango = {};
    entity = true;
    tango['value'] = entity;
    entity = '__esModule';
    entity = golf.bind(options)(zulu, entity, tango);
    entity = 0;
    golf = oscar[entity];
    tango = argCorge;
    entity = undefined;
    golf = tango.bind(entity)(golf);
    tango = 1;
    tango = oscar[tango];
    tango = report.bind(entity)(tango);
    tango = tango.GUILD_COMMUNICATION_DISABLED_RESOURCE_LINK;
    var _closure1_slot3 = tango;
    tango = 2;
    tango = oscar[tango];
    tango = report.bind(entity)(tango);
    tango = tango.jsx;
    var _closure1_slot4 = tango;
    tango = golf.memo;
    mike = function(argFoo) { // Original name: CommunicationDisabledNoticeForGuild
        _fun101526: for(var _fun101526_ip = 0; ; ) switch(_fun101526_ip) {
 0:
            entity = argFoo;
            entity = entity.guildMember;
            zulu = _closure1_slot0;
            tango = _closure1_slot2;
            mike = 3;
            mike = tango[mike];
            tango = undefined;
            zulu = zulu.bind(tango)(mike);
            mike = zulu.useCommunicationDisabledCountdownCleanup;
            mike = mike.bind(zulu)(entity);
            zulu = entity.communicationDisabledUntil;
            entity = null;
            if(!(entity != zulu)) { _fun101526_ip = 90; continue _fun101526 }
 57:
            entity = global;
            entity = entity.Date;
            mike = entity.prototype;
            mike = Object.create(mike, {constructor: {value: entity}});
            kilo = mike;
            backup = zulu;
            entity = new kilo[entity](backup, foxtrot);
            report = entity instanceof Object ? entity : mike;
            _fun101526_ip = 118; continue _fun101526;
 90:
            entity = global;
            entity = entity.Date;
            mike = entity.prototype;
            mike = Object.create(mike, {constructor: {value: entity}});
            kilo = mike;
            entity = new kilo[entity](backup);
            report = entity instanceof Object ? entity : mike;
 118:
            zulu = _closure1_slot4;
            mike = _closure1_slot1;
            yankee = _closure1_slot2;
            entity = 4;
            entity = yankee[entity];
            mike = mike.bind(tango)(entity);
            entity = {};
            oscar = 'simple-action';
            entity['type'] = oscar;
            golf = _closure1_slot0;
            oscar = 5;
            oscar = yankee[oscar];
            oscar = golf.bind(tango)(oscar);
            options = oscar.ClockWarningIcon;
            oscar = {};
            oscar = zulu.bind(tango)(options, oscar);
            entity['icon'] = oscar;
            oscar = 6;
            options = yankee[oscar];
            options = golf.bind(tango)(options);
            romeo = options.intl;
            verify = romeo.string;
            options = yankee[oscar];
            options = golf.bind(tango)(options);
            options = options.t;
            options = options.VSpdzM;
            options = verify.bind(romeo)(options);
            entity['message'] = options;
            options = yankee[oscar];
            options = golf.bind(tango)(options);
            verify = options.intl;
            options = verify.format;
            oscar = yankee[oscar];
            oscar = golf.bind(tango)(oscar);
            oscar = oscar.t;
            golf = oscar.4ZwD5O;
            oscar = {};
            offset = _closure1_slot3;
            oscar['link'] = offset;
            oscar = options.bind(verify)(golf, oscar);
            entity['subtext'] = oscar;
            entity['countdown'] = report;
            entity = zulu.bind(tango)(mike, entity);
            return entity;
        }
    };
    mike = tango.bind(golf)(mike);
    tango = 7;
    tango = oscar[tango];
    oscar = report.bind(entity)(tango);
    report = oscar.fileFinishedImporting;
    tango = 'modules/chat_input/native/guard/ChatInputGuardGuildCommunicationDisabled.tsx';
    tango = report.bind(oscar)(tango);
    zulu['default'] = mike;
    return entity;
})();