// app/modules/keyboard/native/KeyboardTypes.tsx
export default (function(_, argBar, __, ___, ____, argFre, argPlu) {
    zuuluu = argFre;
    entity = global;
    report = entity.Object;
    tangon = report.defineProperty;
    michal = {};
    entity = true;
    michal['value'] = entity;
    entity = '__esModule';
    entity = tangon.bind(report)(zuuluu, entity, michal);
    michal = {};
    entity = 'system';
    michal['SYSTEM'] = entity;
    entity = 'expression';
    michal['EXPRESSION'] = entity;
    entity = 'media';
    michal['MEDIA'] = entity;
    entity = 'app_launcher';
    michal['APP_LAUNCHER'] = entity;
    tangon = argPlu;
    entity = 0;
    report = tangon[entity];
    tangon = argBar;
    entity = undefined;
    oscard = tangon.bind(entity)(report);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/keyboard/native/KeyboardTypes.tsx';
    tangon = report.bind(oscard)(tangon);
    zuuluu['KeyboardTypes'] = michal;
    return entity;
})();