// app/modules/keyboard/native/PortalKeyboardFooterIOS.ios.tsx
export default (function(argFoo, argBar, argBaz, argCorge, _, argFred, argPlugh) {
    report = argBar;
    yankee = argBaz;
    zulu = argFred;
    oscar = argPlugh;
    var _closure1_slot0 = report;
    var _closure1_slot1 = yankee;
    var _closure1_slot2 = oscar;
    entity = global;
    options = entity.Object;
    golf = options.defineProperty;
    tango = {};
    entity = true;
    tango['value'] = entity;
    entity = '__esModule';
    entity = golf.bind(options)(zulu, entity, tango);
    entity = 0;
    golf = oscar[entity];
    tango = argCorge;
    entity = undefined;
    tango = tango.bind(entity)(golf);
    var _closure1_slot3 = tango;
    tango = 1;
    tango = oscar[tango];
    tango = report.bind(entity)(tango);
    tango = tango.jsx;
    var _closure1_slot4 = tango;
    tango = 2;
    tango = oscar[tango];
    options = report.bind(entity)(tango);
    golf = options.createStyles;
    tango = {};
    verify = {'position': 'absolute', 'bottom': 0, 'left': 0, 'right': 0, 'zIndex': 1, 'flex': 1};
    offset = 3;
    offset = oscar[offset];
    offset = yankee.bind(entity)(offset);
    offset = offset.colors;
    offset = offset.BG_BASE_SECONDARY;
    verify['backgroundColor'] = offset;
    tango['keyboardStickyFooter'] = verify;
    tango = golf.bind(options)(tango);
    var _closure1_slot5 = tango;
    tango = {};
    golf = "function PortalKeyboardFooterIOSIosTsx1(){const{interpolate,progress,bottom,animatedSheetIndex,height,EXPRESSION_FOOTER_HEIGHT}=this.__closure;const offset=interpolate(progress.get(),[0,1],[0,bottom]);if(animatedSheetIndex.get()>=0){return{transform:[{translateY:height.get()+offset}]};}return{transform:[{translateY:interpolate(animatedSheetIndex.get(),[-1,0],[EXPRESSION_FOOTER_HEIGHT+bottom,0],'clamp')}]};}";
    tango['code'] = golf;
    var _closure1_slot6 = tango;
    tango = 9;
    tango = oscar[tango];
    oscar = report.bind(entity)(tango);
    report = oscar.fileFinishedImporting;
    tango = 'modules/keyboard/native/PortalKeyboardFooterIOS.ios.tsx';
    tango = report.bind(oscar)(tango);
    mike = function(argFoo) { // Original name: PortalKeyboardFooterIOS
        _fun77979: for(var _fun77979_ip = 0; ; ) switch(_fun77979_ip) {
 0:
            entity = argFoo;
            kilo = entity.animatedSheetIndex;
            var _closure2_slot0 = kilo;
            golf = entity.portalHostName;
            tango = undefined;
            if(!(golf === tango)) { _fun77979_ip = 33; continue _fun77979 }
 27:
            golf = 'expression-footer';
 33:
            var _closure2_slot1 = tango;
            var _closure2_slot2 = tango;
            var _closure2_slot3 = tango;
            var _closure2_slot4 = tango;
            var _closure2_slot5 = tango;
            entity = _closure1_slot5;
            romeo = entity.bind(tango)();
            _closure2_slot1 = romeo;
            mike = _closure1_slot1;
            options = _closure1_slot2;
            entity = 4;
            entity = options[entity];
            entity = mike.bind(tango)(entity);
            entity = entity.bind(tango)();
            sizing = entity.bottom;
            _closure2_slot2 = sizing;
            oscar = _closure1_slot0;
            entity = 5;
            entity = options[entity];
            verify = oscar.bind(tango)(entity);
            entity = verify.useReanimatedKeyboardAnimation;
            entity = entity.bind(verify)();
            backup = entity.height;
            _closure2_slot3 = backup;
            output = entity.progress;
            _closure2_slot4 = output;
            entity = 6;
            verify = options[entity];
            yankee = oscar.bind(tango)(verify);
            offset = yankee.useAnimatedStyle;
            verify = function() { // Original name: _
                _fun77980: for(var _fun77980_ip = 0; ; ) switch(_fun77980_ip) {
 0:
                    mike = _closure1_slot0;
                    entity = _closure1_slot2;
                    oscar = 6;
                    entity = entity[oscar];
                    romeo = undefined;
                    options = mike.bind(romeo)(entity);
                    report = options.interpolate;
                    mike = _closure2_slot4;
                    entity = mike.get;
                    tango = entity.bind(mike)();
                    entity = _closure2_slot2;
                    mike = [0];
                    mike[1] = entity;
                    entity = [0, 1];
                    report = report.bind(options)(tango, entity, mike);
                    mike = _closure2_slot0;
                    entity = mike.get;
                    entity = entity.bind(mike)();
                    mike = 0;
                    if(!(!(entity >= mike))) { _fun77980_ip = 239; continue _fun77980 }
 104:
                    entity = {};
                    tango = {};
                    yankee = _closure1_slot0;
                    foxtrot = _closure1_slot2;
                    oscar = foxtrot[oscar];
                    offset = yankee.bind(romeo)(oscar);
                    verify = offset.interpolate;
                    golf = _closure2_slot0;
                    oscar = golf.get;
                    options = oscar.bind(golf)();
                    golf = new Array(2);
                    oscar = -1;
                    golf[0] = oscar;
                    golf[1] = mike;
                    oscar = 7;
                    oscar = foxtrot[oscar];
                    oscar = yankee.bind(romeo)(oscar);
                    yankee = oscar.EXPRESSION_FOOTER_HEIGHT;
                    oscar = _closure2_slot2;
                    yankee = yankee + oscar;
                    oscar = new Array(2);
                    oscar[0] = yankee;
                    oscar[1] = mike;
                    backup = 'clamp';
                    result = offset;
                    output = options;
                    sizing = golf;
                    kilo = oscar;
                    mike = result[verify](output, sizing, kilo, backup, foxtrot);
                    tango['translateY'] = mike;
                    mike = new Array(1);
                    mike[0] = tango;
                    entity['transform'] = mike;
                    _fun77980_ip = 280; continue _fun77980;
 239:
                    mike = {};
                    tango = {};
                    oscar = _closure2_slot3;
                    zulu = oscar.get;
                    zulu = zulu.bind(oscar)();
                    zulu = zulu + report;
                    tango['translateY'] = zulu;
                    zulu = new Array(1);
                    zulu[0] = tango;
                    mike['transform'] = zulu;
                    entity = mike;
 280:
                    return entity;
                }
            };
            foxtrot = {};
            result = options[entity];
            result = oscar.bind(tango)(result);
            result = result.interpolate;
            foxtrot['interpolate'] = result;
            foxtrot['progress'] = output;
            foxtrot['bottom'] = sizing;
            foxtrot['animatedSheetIndex'] = kilo;
            foxtrot['height'] = backup;
            backup = 7;
            backup = options[backup];
            backup = oscar.bind(tango)(backup);
            backup = backup.EXPRESSION_FOOTER_HEIGHT;
            foxtrot['EXPRESSION_FOOTER_HEIGHT'] = backup;
            verify['__closure'] = foxtrot;
            foxtrot = 5681202963788.0;
            verify['__workletHash'] = foxtrot;
            foxtrot = _closure1_slot6;
            verify['__initData'] = foxtrot;
            foxtrot = offset.bind(yankee)(verify);
            _closure2_slot5 = foxtrot;
            yankee = _closure1_slot3;
            offset = yankee.useMemo;
            verify = new Array(2);
            verify[0] = foxtrot;
            verify[1] = romeo;
            report = function() {
                entity = _closure2_slot1;
                zulu = entity.keyboardStickyFooter;
                entity = new Array(2);
                entity[0] = zulu;
                mike = _closure2_slot5;
                entity[1] = mike;
                return entity;
            };
            report = offset.bind(yankee)(report, verify);
            zulu = _closure1_slot4;
            entity = options[entity];
            entity = mike.bind(tango)(entity);
            mike = entity.View;
            entity = {};
            entity['style'] = report;
            report = 8;
            report = options[report];
            report = oscar.bind(tango)(report);
            oscar = report.PortalHost;
            report = {};
            report['name'] = golf;
            report = zulu.bind(tango)(oscar, report);
            entity['children'] = report;
            entity = zulu.bind(tango)(mike, entity);
            return entity;
        }
    };
    zulu['default'] = mike;
    return entity;
})();