// app/modules/activities/utils/deferJoinActivityInChannel.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var3 = exports;
    var4 = dependencyMap;
    var1 = metroImportDefault;
    var _closure1_slot0 = var1;
    var _closure1_slot1 = var4;
    var1 = global;
    var7 = var1.Object;
    var6 = var7.defineProperty;
    var5 = {};
    var1 = true;
    var5['value'] = var1;
    var1 = '__esModule';
    var1 = var6.bind(var7)(var3, var1, var5);
    var1 = 1;
    var5 = var4[var1];
    var4 = require;
    var1 = undefined;
    var6 = var4.bind(var1)(var5);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/activities/utils/deferJoinActivityInChannel.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function deferJoinActivityApplication(arg1) {
        var1 = arg1;
        var10 = var1.channelId;
        var9 = var1.applicationId;
        var8 = var1.intent;
        var7 = var1.inviterUserId;
        var6 = var1.analyticsLocations;
        var5 = var1.commandOrigin;
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 0;
        var2 = var2[var1];
        var1 = undefined;
        var4 = var3.bind(var1)(var2);
        var3 = var4.dispatch;
        var2 = {};
        var11 = 'EMBEDDED_ACTIVITY_DEFERRED_OPEN';
        var2['type'] = var11;
        var2['channelId'] = var10;
        var2['applicationId'] = var9;
        var2['intent'] = var8;
        var2['inviterUserId'] = var7;
        var2['analyticsLocations'] = var6;
        var2['commandOrigin'] = var5;
        var2 = var3.bind(var4)(var2);
        return var1;
    };
    var3['default'] = var2;
    return var1;
})();