// app/modules/routing/transitionToGuild.native.tsx
export default (function(argFoo, argBar, _, __, ___, argFred, argPlugh) {
    report = argBar;
    zulu = argFred;
    oscar = argPlugh;
    var _closure1_slot0 = report;
    var _closure1_slot1 = oscar;
    entity = global;
    options = entity.Object;
    golf = options.defineProperty;
    tango = {};
    entity = true;
    tango['value'] = entity;
    entity = '__esModule';
    entity = golf.bind(options)(zulu, entity, tango);
    entity = 0;
    tango = oscar[entity];
    entity = undefined;
    tango = report.bind(entity)(tango);
    tango = tango.Routes;
    var _closure1_slot2 = tango;
    tango = 4;
    tango = oscar[tango];
    oscar = report.bind(entity)(tango);
    report = oscar.fileFinishedImporting;
    tango = 'modules/routing/transitionToGuild.native.tsx';
    tango = report.bind(oscar)(tango);
    mike = function(argFoo, argBar) { // Original name: transitionToGuild
        golf = argFoo;
        tango = _closure1_slot0;
        report = _closure1_slot1;
        entity = 1;
        zulu = report[entity];
        entity = undefined;
        oscar = tango.bind(entity)(zulu);
        zulu = oscar.getChannelIdForGuildTransition;
        oscar = zulu.bind(oscar)(golf);
        zulu = 2;
        zulu = report[zulu];
        verify = tango.bind(entity)(zulu);
        options = verify.DeprecatedLayoutAnimation;
        zulu = {};
        offset = 0;
        zulu['duration'] = offset;
        zulu['create'] = entity;
        zulu['update'] = entity;
        zulu['delete'] = entity;
        zulu = options.bind(verify)(zulu);
        zulu = 3;
        zulu = report[zulu];
        report = tango.bind(entity)(zulu);
        tango = report.transitionTo;
        zulu = _closure1_slot2;
        mike = zulu.CHANNEL;
        zulu = mike.bind(zulu)(golf, oscar);
        mike = {};
        oscar = true;
        mike['navigationReplace'] = oscar;
        yankee = argBar;
        romeo = mike;
        oscar = copyDataProperties(romeo, yankee);
        mike = tango.bind(report)(zulu, mike);
        return entity;
    };
    zulu['transitionToGuild'] = mike;
    return entity;
})();