// app/modules/user_settings/UserSettingsSafetySelectedGuildStore.tsx
export default (function(argFoo, argBar, _, __, ___, argFre, argPlu) {
    golfie = argBar;
    zuuluu = argFre;
    option = argPlu;
    entity = global;
    oscard = entity.Object;
    report = oscard.defineProperty;
    tangon = {};
    entity = true;
    tangon['value'] = entity;
    entity = '__esModule';
    entity = report.bind(oscard)(zuuluu, entity, tangon);
    entity = {};
    report = '0';
    entity['selectedGuildId'] = report;
    var _closure1_slot0 = entity;
    entity = 0;
    tangon = option[entity];
    entity = undefined;
    verify = golfie.bind(entity)(tangon);
    oscard = verify.create;
    tangon = function(argFoo) {
        entity = argFoo;
        var _closure2_slot0 = entity;
        entity = {};
        report = _closure1_slot0;
        oscard = entity;
        zuuluu = copyDataProperties(oscard, report);
        tangon = function(argFoo) { // Original name: setSelectedGuildId
            zuuluu = _closure2_slot0;
            michal = {};
            entity = argFoo;
            michal['selectedGuildId'] = entity;
            entity = undefined;
            michal = zuuluu.bind(entity)(michal);
            return entity;
        };
        zuuluu = 'setSelectedGuildId';
        entity[zuuluu] = tangon;
        zuuluu = function() { // Original name: reset
            zuuluu = _closure2_slot0;
            michal = _closure1_slot0;
            entity = undefined;
            michal = zuuluu.bind(entity)(michal);
            return entity;
        };
        michal = 'reset';
        entity[michal] = zuuluu;
        return entity;
    };
    tangon = oscard.bind(verify)(tangon);
    var _closure1_slot1 = tangon;
    oscard = 1;
    oscard = option[oscard];
    option = golfie.bind(entity)(oscard);
    golfie = option.fileFinishedImporting;
    oscard = 'modules/user_settings/UserSettingsSafetySelectedGuildStore.tsx';
    oscard = golfie.bind(option)(oscard);
    zuuluu['GUILD_SELECT_ALL_SERVERS_OPTION_ID'] = report;
    zuuluu['useUserSafetySettingsSelectedGuildStore'] = tangon;
    tangon = function(argFoo) { // Original name: setSelectedGuildId
        zuuluu = _closure1_slot1;
        michal = zuuluu.setState;
        entity = {};
        tangon = argFoo;
        entity['selectedGuildId'] = tangon;
        entity = michal.bind(zuuluu)(entity);
        return entity;
    };
    zuuluu['setSelectedGuildId'] = tangon;
    michal = function() { // Original name: getSelectedGuildId
        michal = _closure1_slot1;
        entity = michal.getState;
        entity = entity.bind(michal)();
        entity = entity.selectedGuildId;
        return entity;
    };
    zuuluu['getSelectedGuildId'] = michal;
    return entity;
})();