// app/modules/app_launcher/native/hooks/useTrackAppLauncherItemImpressionOnFirstView.tsx
export default (function(argFoo, argBar, _, argCor, __, argFre, argPlu) {
    report = argBar;
    zuuluu = argFre;
    oscard = argPlu;
    var _closure1_slot0 = report;
    var _closure1_slot1 = oscard;
    entity = global;
    option = entity.Object;
    golfie = option.defineProperty;
    tangon = {};
    entity = true;
    tangon['value'] = entity;
    entity = '__esModule';
    entity = golfie.bind(option)(zuuluu, entity, tangon);
    entity = 0;
    golfie = oscard[entity];
    tangon = argCor;
    entity = undefined;
    tangon = tangon.bind(entity)(golfie);
    var _closure1_slot2 = tangon;
    tangon = 5;
    tangon = oscard[tangon];
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/app_launcher/native/hooks/useTrackAppLauncherItemImpressionOnFirstView.tsx';
    tangon = report.bind(oscard)(tangon);
    michal = function() { // Original name: useTrackAppLauncherItemImpressionOnFirstView
        tangon = _closure1_slot0;
        golfie = _closure1_slot1;
        zuuluu = 1;
        report = golfie[zuuluu];
        zuuluu = undefined;
        oscard = tangon.bind(zuuluu)(report);
        report = oscard.useAppLauncherContext;
        report = report.bind(oscard)();
        oscard = report.entrypoint;
        var _closure2_slot0 = oscard;
        report = _closure1_slot2;
        option = report.useRef;
        entity = global;
        entity = entity.Set;
        verify = entity.prototype;
        verify = Object.create(verify, {constructor: {value: entity}});
        romeon = verify;
        entity = new romeon[entity](yankee);
        entity = entity instanceof Object ? entity : verify;
        entity = option.bind(report)(entity);
        var _closure2_slot1 = entity;
        entity = 2;
        entity = golfie[entity];
        tangon = tangon.bind(zuuluu)(entity);
        zuuluu = tangon.useFocusEffect;
        option = report.useCallback;
        golfie = function() {
            entity = _closure2_slot1;
            michal = entity.current;
            entity = michal.clear;
            entity = entity.bind(michal)();
            entity = undefined;
            return entity;
        };
        entity = new Array(0);
        entity = option.bind(report)(golfie, entity);
        entity = zuuluu.bind(tangon)(entity);
        entity = {};
        tangon = report.useCallback;
        zuuluu = new Array(1);
        zuuluu[0] = oscard;
        michal = function(argFoo) {
            _fun00001: for(var _fun00002_ip = 0; ; ) switch(_fun00002_ip) {
 0:
                entity = argFoo;
                zuuluu = entity.itemKey;
                offset = entity.sectionName;
                verify = entity.sectionPosition;
                option = entity.sectionOverallPosition;
                golfie = entity.applicationId;
                oscard = entity.commandId;
                report = entity.applicationFlags;
                entity = _closure2_slot1;
                michal = entity.current;
                entity = michal.has;
                entity = entity.bind(michal)(zuuluu);
                if(entity) { _fun00002_ip = 233; continue _fun00001 }
 72:
                entity = _closure2_slot1;
                michal = entity.current;
                entity = michal.add;
                entity = entity.bind(michal)(zuuluu);
                foxtra = _closure1_slot0;
                backup = _closure1_slot1;
                entity = 3;
                entity = backup[entity];
                romeon = undefined;
                zuuluu = foxtra.bind(romeon)(entity);
                michal = zuuluu.trackImpression;
                entity = {};
                tangon = 4;
                kiloes = backup[tangon];
                kiloes = foxtra.bind(romeon)(kiloes);
                kiloes = kiloes.ImpressionTypes;
                kiloes = kiloes.VIEW;
                entity['type'] = kiloes;
                tangon = backup[tangon];
                tangon = foxtra.bind(romeon)(tangon);
                tangon = tangon.ImpressionNames;
                tangon = tangon.APP_LAUNCHER_ITEM;
                entity['name'] = tangon;
                tangon = {};
                yankee = _closure2_slot0;
                tangon['source'] = yankee;
                tangon['section_name'] = offset;
                tangon['section_position'] = verify;
                tangon['section_overall_position'] = option;
                tangon['application_id'] = golfie;
                tangon['command_id'] = oscard;
                tangon['application_flags'] = report;
                entity['properties'] = tangon;
                entity = michal.bind(zuuluu)(entity);
 233:
                entity = undefined;
                return entity;
            }
        };
        michal = tangon.bind(report)(michal, zuuluu);
        entity['trackAppLauncherItemImpressionOnFirstView'] = michal;
        return entity;
    };
    zuuluu['useTrackAppLauncherItemImpressionOnFirstView'] = michal;
    return entity;
})();