// app/modules/guild_invite/native/InviteSettingsModal.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var11 = metroImportDefault;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var11;
    var _closure1_slot2 = var6;
    var1 = function AdvancedInstantInviteScreen() {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var2 = _closure1_slot12;
            var4 = undefined;
            var18 = var2.bind(var4)();
            var3 = _closure1_slot0;
            var6 = _closure1_slot2;
            var2 = 10;
            var2 = var6[var2];
            var7 = var3.bind(var4)(var2);
            var2 = var7.useNavigation;
            var10 = var2.bind(var7)();
            var _closure2_slot0 = var10;
            var2 = 11;
            var2 = var6[var2];
            var7 = var3.bind(var4)(var2);
            var6 = var7.useStateFromStoresObject;
            var2 = _closure1_slot5;
            var3 = new Array(3);
            var3[0] = var2;
            var2 = _closure1_slot6;
            var3[1] = var2;
            var2 = _closure1_slot7;
            var3[2] = var2;
            var2 = function() {
                _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
case 0:
                    var3 = _closure1_slot6;
                    var1 = var3.getPendingSettings;
                    var5 = var1.bind(var3)();
                    var6 = _closure1_slot1;
                    var8 = _closure1_slot2;
                    var3 = 12;
                    var4 = var8[var3];
                    var1 = undefined;
                    var10 = var6.bind(var1)(var4);
                    var7 = null;
                    var9 = var7 != var5;
                    var4 = 'Received null pending invite settings';
                    var4 = var10.bind(var1)(var9, var4);
                    var9 = _closure1_slot6;
                    var4 = var9.getInviteSettings;
                    var4 = var4.bind(var9)();
                    var3 = var8[var3];
                    var8 = var6.bind(var1)(var3);
                    var6 = var7 != var4;
                    var3 = 'Received null invite settings';
                    var3 = var8.bind(var1)(var6, var3);
                    var8 = _closure1_slot5;
                    var6 = var8.getChannel;
                    var3 = var5.channelId;
                    var3 = var6.bind(var8)(var3);
                    var6 = _closure1_slot7;
                    var2 = var6.getGuild;
                    var7 = var7 == var3;
                    if(var7) { _fun0002_ip = 2; continue _fun0002 }
case 3:
                    var7 = var3.getGuildId;
                    var1 = var7.bind(var3)();
case 2:
                    var2 = var2.bind(var6)(var1);
                    var1 = {};
                    var1['settings'] = var5;
                    var1['inviteSettings'] = var4;
                    var1['channel'] = var3;
                    var1['guild'] = var2;
                    return var1;
                }
            };
            var2 = var6.bind(var7)(var3, var2);
            var13 = var2.settings;
            var8 = var2.inviteSettings;
            var3 = var2.channel;
            var _closure2_slot1 = var3;
            var14 = var2.guild;
            var6 = _closure1_slot4;
            var2 = var6.useState;
            var7 = var2.bind(var6)(var3);
            var6 = _closure1_slot3;
            var2 = 2;
            var6 = var6.bind(var4)(var7, var2);
            var2 = 0;
            var17 = var6[var2];
            var2 = 1;
            var2 = var6[var2];
            var6 = null;
            var6 = var6 != var3;
            if(!var6) { _fun0001_ip = 4; continue _fun0001 }
case 5:
            var6 = var3 !== var17;
case 4:
            if(!var6) { _fun0001_ip = 6; continue _fun0001 }
case 7:
            var2 = var2.bind(var4)(var3);
case 6:
            var2 = _closure1_slot0;
            var16 = _closure1_slot2;
            var6 = 13;
            var6 = var16[var6];
            var7 = var2.bind(var4)(var6);
            var6 = var7.isEqual;
            var6 = var6.bind(var7)(var13, var8);
            var9 = !var6;
            var _closure2_slot2 = var9;
            var11 = _closure1_slot4;
            var8 = var11.useEffect;
            var7 = new Array(1);
            var7[0] = var3;
            var6 = function() {
                _fun0003: for(var _fun0003_ip = 0; ; ) switch(_fun0003_ip) {
case 0:
                    var1 = _closure2_slot1;
                    var2 = null;
                    if(!(var2 == var1)) { _fun0003_ip = 8; continue _fun0003 }
case 9:
                    var4 = _closure1_slot6;
                    var3 = var4.getGuildId;
                    var6 = var3.bind(var4)();
                    var3 = var2 != var6;
                    var4 = null;
                    if(!var3) { _fun0003_ip = 10; continue _fun0003 }
case 11:
                    var7 = _closure1_slot0;
                    var5 = _closure1_slot2;
                    var3 = 14;
                    var5 = var5[var3];
                    var3 = undefined;
                    var5 = var7.bind(var3)(var5);
                    var3 = var5.getInvitableChannelForGuild;
                    var4 = var3.bind(var5)(var6);
case 10:
                    if(!(var2 == var4)) { _fun0003_ip = 12; continue _fun0003 }
case 13:
                    var8 = _closure1_slot1;
                    var9 = _closure1_slot2;
                    var2 = 16;
                    var2 = var9[var2];
                    var7 = undefined;
                    var5 = var8.bind(var7)(var2);
                    var3 = var5.show;
                    var2 = {};
                    var12 = _closure1_slot0;
                    var6 = 17;
                    var10 = var9[var6];
                    var10 = var12.bind(var7)(var10);
                    var13 = var10.intl;
                    var11 = var13.string;
                    var10 = var9[var6];
                    var10 = var12.bind(var7)(var10);
                    var10 = var10.t;
                    var10 = var10.VINpSK;
                    var10 = var11.bind(var13)(var10);
                    var2['title'] = var10;
                    var10 = var9[var6];
                    var10 = var12.bind(var7)(var10);
                    var11 = var10.intl;
                    var10 = var11.string;
                    var6 = var9[var6];
                    var6 = var12.bind(var7)(var6);
                    var6 = var6.t;
                    var6 = var6.kQ6fit;
                    var6 = var10.bind(var11)(var6);
                    var2['body'] = var6;
                    var6 = 15;
                    var6 = var9[var6];
                    var6 = var8.bind(var7)(var6);
                    var6 = var6.close;
                    var2['onConfirm'] = var6;
                    var2 = var3.bind(var5)(var2);
                    _fun0003_ip = 8; continue _fun0003;
case 12:
                    var3 = _closure1_slot1;
                    var2 = _closure1_slot2;
                    var1 = 15;
                    var2 = var2[var1];
                    var1 = undefined;
                    var3 = var3.bind(var1)(var2);
                    var2 = var3.updateSettings;
                    var1 = {};
                    var4 = var4.channel;
                    var4 = var4.id;
                    var1['channelId'] = var4;
                    var1 = var2.bind(var3)(var1);
case 8:
                    var1 = undefined;
                    return var1;
                }
            };
            var6 = var8.bind(var11)(var6, var7);
            var6 = 18;
            var6 = var16[var6];
            var8 = var2.bind(var4)(var6);
            var7 = var8.useUnmountEffect;
            var6 = function() {
                var5 = _closure1_slot1;
                var6 = _closure1_slot2;
                var1 = 19;
                var2 = var6[var1];
                var1 = undefined;
                var4 = var5.bind(var1)(var2);
                var3 = var4.wait;
                var2 = 15;
                var2 = var6[var2];
                var2 = var5.bind(var1)(var2);
                var2 = var2.resetSettings;
                var2 = var3.bind(var4)(var2);
                return var1;
            };
            var6 = var7.bind(var8)(var6);
            var8 = _closure1_slot4;
            var7 = var8.useCallback;
            var6 = new Array(1);
            var6[0] = var3;
            var3 = function() {
                _fun0004: for(var _fun0004_ip = 0; ; ) switch(_fun0004_ip) {
case 0:
                    var3 = _closure2_slot1;
                    var1 = null;
                    if(!(var1 != var3)) { _fun0004_ip = 14; continue _fun0004 }
case 15:
                    var5 = _closure1_slot8;
                    var4 = var5.can;
                    var3 = _closure1_slot10;
                    var3 = var3.CREATE_INSTANT_INVITE;
                    var2 = _closure2_slot1;
                    var2 = var4.bind(var5)(var3, var2);
                    if(var2) { _fun0004_ip = 16; continue _fun0004 }
case 14:
                    var7 = _closure1_slot1;
                    var8 = _closure1_slot2;
                    var2 = 16;
                    var2 = var8[var2];
                    var6 = undefined;
                    var4 = var7.bind(var6)(var2);
                    var3 = var4.show;
                    var2 = {};
                    var11 = _closure1_slot0;
                    var5 = 17;
                    var9 = var8[var5];
                    var9 = var11.bind(var6)(var9);
                    var12 = var9.intl;
                    var10 = var12.string;
                    var9 = var8[var5];
                    var9 = var11.bind(var6)(var9);
                    var9 = var9.t;
                    var9 = var9.VINpSK;
                    var9 = var10.bind(var12)(var9);
                    var2['title'] = var9;
                    var9 = var8[var5];
                    var9 = var11.bind(var6)(var9);
                    var10 = var9.intl;
                    var9 = var10.string;
                    var5 = var8[var5];
                    var5 = var11.bind(var6)(var5);
                    var5 = var5.t;
                    var5 = var5.RiiKV0;
                    var5 = var9.bind(var10)(var5);
                    var2['body'] = var5;
                    var5 = 15;
                    var5 = var8[var5];
                    var5 = var7.bind(var6)(var5);
                    var5 = var5.close;
                    var2['onConfirm'] = var5;
                    var2 = var3.bind(var4)(var2);
                    _fun0004_ip = 17; continue _fun0004;
case 16:
                    var3 = _closure1_slot1;
                    var4 = _closure1_slot2;
                    var1 = 15;
                    var5 = var4[var1];
                    var2 = undefined;
                    var7 = var3.bind(var2)(var5);
                    var6 = var7.createInvite;
                    var5 = 'IOS Regenerate';
                    var5 = var6.bind(var7)(var5);
                    var1 = var4[var1];
                    var2 = var3.bind(var2)(var1);
                    var1 = var2.close;
                    var1 = var1.bind(var2)();
case 17:
                    var1 = undefined;
                    return var1;
                }
            };
            var3 = var7.bind(var8)(var3, var6);
            var _closure2_slot3 = var3;
            var8 = _closure1_slot4;
            var7 = var8.useEffect;
            var6 = new Array(3);
            var6[0] = var10;
            var6[1] = var9;
            var6[2] = var3;
            var3 = function() {
                var3 = _closure2_slot0;
                var2 = var3.setOptions;
                var1 = {};
                var4 = function headerRight() {
                    _fun0005: for(var _fun0005_ip = 0; ; ) switch(_fun0005_ip) {
case 0:
                        var2 = _closure2_slot2;
                        var5 = undefined;
                        var1 = undefined;
                        if(!var2) { _fun0005_ip = 18; continue _fun0005 }
case 19:
                        var4 = _closure1_slot11;
                        var9 = _closure1_slot0;
                        var10 = _closure1_slot2;
                        var2 = 20;
                        var2 = var10[var2];
                        var2 = var9.bind(var5)(var2);
                        var3 = var2.HeaderActionButton;
                        var2 = {};
                        var6 = _closure2_slot3;
                        var2['onPress'] = var6;
                        var6 = 17;
                        var7 = var10[var6];
                        var7 = var9.bind(var5)(var7);
                        var8 = var7.intl;
                        var7 = var8.string;
                        var6 = var10[var6];
                        var6 = var9.bind(var5)(var6);
                        var6 = var6.t;
                        var6 = var6.R3BPH+;
                        var6 = var7.bind(var8)(var6);
                        var2['text'] = var6;
                        var1 = var4.bind(var5)(var3, var2);
case 18:
                        return var1;
                    }
                };
                var1['headerRight'] = var4;
                var1 = var2.bind(var3)(var1);
                var1 = undefined;
                return var1;
            };
            var3 = var7.bind(var8)(var3, var6);
            var8 = _closure1_slot4;
            var7 = var8.useCallback;
            var6 = function(arg1) {
                var3 = _closure1_slot1;
                var2 = _closure1_slot2;
                var1 = 15;
                var2 = var2[var1];
                var1 = undefined;
                var4 = var3.bind(var1)(var2);
                var3 = var4.updateSettings;
                var2 = {};
                var5 = arg1;
                var2['maxUses'] = var5;
                var2 = var3.bind(var4)(var2);
                return var1;
            };
            var3 = new Array(0);
            var11 = var7.bind(var8)(var6, var3);
            var8 = _closure1_slot4;
            var7 = var8.useCallback;
            var6 = function(arg1) {
                var3 = _closure1_slot1;
                var2 = _closure1_slot2;
                var1 = 15;
                var2 = var2[var1];
                var1 = undefined;
                var4 = var3.bind(var1)(var2);
                var3 = var4.updateSettings;
                var2 = {};
                var5 = arg1;
                var2['maxAge'] = var5;
                var2 = var3.bind(var4)(var2);
                return var1;
            };
            var3 = new Array(0);
            var12 = var7.bind(var8)(var6, var3);
            var8 = _closure1_slot4;
            var7 = var8.useCallback;
            var6 = function(arg1) {
                var3 = _closure1_slot1;
                var2 = _closure1_slot2;
                var1 = 15;
                var2 = var2[var1];
                var1 = undefined;
                var4 = var3.bind(var1)(var2);
                var3 = var4.updateSettings;
                var2 = {};
                var5 = arg1;
                var2['temporary'] = var5;
                var2 = var3.bind(var4)(var2);
                return var1;
            };
            var3 = new Array(0);
            var10 = var7.bind(var8)(var6, var3);
            var8 = _closure1_slot4;
            var7 = var8.useCallback;
            var6 = function(arg1) {
                var3 = _closure1_slot1;
                var2 = _closure1_slot2;
                var1 = 15;
                var2 = var2[var1];
                var1 = undefined;
                var4 = var3.bind(var1)(var2);
                var3 = var4.updateSettings;
                var2 = {};
                var5 = arg1;
                var2['flags'] = var5;
                var2 = var3.bind(var4)(var2);
                return var1;
            };
            var3 = new Array(0);
            var9 = var7.bind(var8)(var6, var3);
            var7 = _closure1_slot4;
            var6 = var7.useCallback;
            var3 = function(arg1) {
                var3 = _closure1_slot1;
                var2 = _closure1_slot2;
                var1 = 15;
                var2 = var2[var1];
                var1 = undefined;
                var4 = var3.bind(var1)(var2);
                var3 = var4.updateSettings;
                var2 = {};
                var5 = arg1;
                var2['roleIds'] = var5;
                var2 = var3.bind(var4)(var2);
                return var1;
            };
            var1 = new Array(0);
            var8 = var6.bind(var7)(var3, var1);
            var3 = _closure1_slot11;
            var1 = 21;
            var1 = var16[var1];
            var1 = var2.bind(var4)(var1);
            var2 = var1.Form;
            var1 = {};
            var6 = var18.formContainer;
            var1['contentContainerStyle'] = var6;
            var7 = _closure1_slot11;
            var15 = _closure1_slot1;
            var5 = 22;
            var5 = var16[var5];
            var6 = var15.bind(var4)(var5);
            var5 = {};
            var18 = var18.formContent;
            var5['style'] = var18;
            var5['channel'] = var17;
            var5['guild'] = var14;
            var14 = var13.maxAge;
            var5['maxAge'] = var14;
            var14 = var13.maxUses;
            var5['maxUses'] = var14;
            var14 = 23;
            var14 = var16[var14];
            var14 = var15.bind(var4)(var14);
            var14 = var14.getMaxUsesOptions;
            var5['maxUsesOptions'] = var14;
            var14 = var13.temporary;
            var5['temporary'] = var14;
            var14 = var13.flags;
            var5['flags'] = var14;
            var13 = var13.roleIds;
            var5['roleIds'] = var13;
            var5['onChangeMaxAge'] = var12;
            var5['onChangeMaxUses'] = var11;
            var5['onChangeTemporary'] = var10;
            var5['onChangeFlags'] = var9;
            var5['onChangeRoleIds'] = var8;
            var5 = var7.bind(var4)(var6, var5);
            var1['children'] = var5;
            var1 = var3.bind(var4)(var2, var1);
            return var1;
        }
    };
    var _closure1_slot13 = var1;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var11.bind(var1)(var4);
    var _closure1_slot3 = var4;
    var4 = 1;
    var7 = var6[var4];
    var4 = metroImportAll;
    var4 = var4.bind(var1)(var7);
    var _closure1_slot4 = var4;
    var4 = 2;
    var4 = var6[var4];
    var4 = var11.bind(var1)(var4);
    var _closure1_slot5 = var4;
    var4 = 3;
    var4 = var6[var4];
    var4 = var11.bind(var1)(var4);
    var _closure1_slot6 = var4;
    var4 = 4;
    var4 = var6[var4];
    var4 = var11.bind(var1)(var4);
    var _closure1_slot7 = var4;
    var4 = 5;
    var4 = var6[var4];
    var4 = var11.bind(var1)(var4);
    var _closure1_slot8 = var4;
    var4 = 6;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var7 = var4.InviteModalScenes;
    var _closure1_slot9 = var7;
    var4 = var4.Permissions;
    var _closure1_slot10 = var4;
    var4 = 7;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.jsx;
    var _closure1_slot11 = var4;
    var4 = 8;
    var4 = var6[var4];
    var8 = var5.bind(var1)(var4);
    var7 = var8.createStyles;
    var4 = {};
    var9 = {};
    var10 = 9;
    var12 = var6[var10];
    var12 = var11.bind(var1)(var12);
    var12 = var12.space;
    var12 = var12.PX_16;
    var9['paddingTop'] = var12;
    var12 = var6[var10];
    var12 = var11.bind(var1)(var12);
    var12 = var12.space;
    var12 = var12.PX_32;
    var9['paddingBottom'] = var12;
    var4['formContainer'] = var9;
    var9 = {};
    var10 = var6[var10];
    var10 = var11.bind(var1)(var10);
    var10 = var10.modules;
    var10 = var10.mobile;
    var10 = var10.TABLE_ROW_PADDING;
    var9['paddingHorizontal'] = var10;
    var4['formContent'] = var9;
    var4 = var7.bind(var8)(var4);
    var _closure1_slot12 = var4;
    var4 = 27;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/guild_invite/native/InviteSettingsModal.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function InviteSettingsModal() {
        var4 = _closure1_slot4;
        var3 = var4.useMemo;
        var2 = function() {
            var2 = function getScreens() {
                var1 = {};
                var2 = _closure1_slot9;
                var3 = var2.ADVANCED;
                var2 = {};
                var6 = _closure1_slot0;
                var9 = _closure1_slot2;
                var5 = 24;
                var5 = var9[var5];
                var8 = undefined;
                var5 = var6.bind(var8)(var5);
                var5 = var5.ImpressionNames;
                var5 = var5.GUILD_INVITE_LINK_SETTINGS;
                var2['impressionName'] = var5;
                var5 = 17;
                var7 = var9[var5];
                var7 = var6.bind(var8)(var7);
                var10 = var7.intl;
                var7 = var10.string;
                var5 = var9[var5];
                var5 = var6.bind(var8)(var5);
                var5 = var5.t;
                var5 = var5.Yx4IiC;
                var5 = var7.bind(var10)(var5);
                var2['title'] = var5;
                var5 = 25;
                var5 = var9[var5];
                var6 = var6.bind(var8)(var5);
                var5 = var6.getHeaderCloseButton;
                var7 = _closure1_slot1;
                var4 = 15;
                var4 = var9[var4];
                var4 = var7.bind(var8)(var4);
                var4 = var4.close;
                var4 = var5.bind(var6)(var4);
                var2['headerLeft'] = var4;
                var4 = function render() {
                    var4 = _closure1_slot11;
                    var3 = _closure1_slot13;
                    var2 = undefined;
                    var1 = {};
                    var1 = var4.bind(var2)(var3, var1);
                    return var1;
                };
                var2['render'] = var4;
                var1[2] = var2;
                return var1;
            };
            var1 = undefined;
            var1 = var2.bind(var1)();
            return var1;
        };
        var1 = new Array(0);
        var6 = var3.bind(var4)(var2, var1);
        var4 = _closure1_slot11;
        var2 = _closure1_slot0;
        var3 = _closure1_slot2;
        var1 = 26;
        var1 = var3[var1];
        var3 = undefined;
        var1 = var2.bind(var3)(var1);
        var2 = var1.Navigator;
        var1 = {};
        var1['screens'] = var6;
        var5 = _closure1_slot9;
        var5 = var5.ADVANCED;
        var1['initialRouteName'] = var5;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var3['default'] = var2;
    return var1;
})();