// app/modules/collectibles/native/ShopProductPreviewActionSheet.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var11 = metroImportDefault;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var11;
    var _closure1_slot2 = var6;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var11.bind(var1)(var4);
    var _closure1_slot3 = var4;
    var10 = 1;
    var7 = var6[var10];
    var4 = metroImportAll;
    var4 = var4.bind(var1)(var7);
    var _closure1_slot4 = var4;
    var4 = var6[var10];
    var4 = var5.bind(var1)(var4);
    var4 = var4.useCallback;
    var _closure1_slot5 = var4;
    var4 = 2;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.AnalyticEvents;
    var _closure1_slot6 = var4;
    var4 = 3;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var7 = var4.jsx;
    var _closure1_slot7 = var7;
    var4 = var4.jsxs;
    var _closure1_slot8 = var4;
    var4 = 4;
    var4 = var6[var4];
    var8 = var5.bind(var1)(var4);
    var7 = var8.createStyles;
    var4 = {};
    var9 = {};
    var9['flex'] = var10;
    var10 = 5;
    var10 = var6[var10];
    var10 = var11.bind(var1)(var10);
    var10 = var10.colors;
    var10 = var10.BG_BASE_SECONDARY;
    var9['backgroundColor'] = var10;
    var4['container'] = var9;
    var4 = var7.bind(var8)(var4);
    var _closure1_slot9 = var4;
    var4 = 21;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/collectibles/native/ShopProductPreviewActionSheet.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function ShopProductPreviewActionSheet(arg1) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var1 = arg1;
            var18 = var1.product;
            var _closure2_slot0 = var18;
            var1 = var1.analyticsLocations;
            var4 = undefined;
            if(!(var1 === var4)) { _fun0001_ip = 2; continue _fun0001 }
case 3:
            var1 = new Array(0);
case 2:
            var _closure2_slot1 = var1;
            var _closure2_slot2 = var4;
            var _closure2_slot3 = var4;
            var _closure2_slot4 = var4;
            var _closure2_slot5 = var4;
            var2 = _closure1_slot9;
            var22 = var2.bind(var4)();
            var6 = _closure1_slot4;
            var2 = var6.useRef;
            var13 = null;
            var10 = var2.bind(var6)(var13);
            var2 = var6.useRef;
            var21 = var2.bind(var6)(var13);
            _closure2_slot2 = var21;
            var2 = var6.useState;
            var8 = 0;
            var2 = var2.bind(var6)(var8);
            var23 = _closure1_slot3;
            var9 = 2;
            var2 = var23.bind(var4)(var2, var9);
            var24 = var2[var8];
            var3 = 1;
            var15 = var2[var3];
            var14 = _closure1_slot1;
            var20 = _closure1_slot2;
            var5 = 10;
            var2 = var20[var5];
            var12 = var14.bind(var4)(var2);
            var2 = new Array(1);
            var30 = var2;
            var29 = var1;
            var28 = 0;
            var16 = arraySpread(var30, var29, var28);
            var17 = 11;
            var17 = var20[var17];
            var17 = var14.bind(var4)(var17);
            var17 = var17.COLLECTIBLES_SHOP_PROFILE_PREVIEW;
            var2[var16] = var17;
            var16 = var16 + var3;
            var2 = var12.bind(var4)(var2);
            var17 = var2.analyticsLocations;
            var2 = var6.useState;
            var16 = true;
            var2 = var2.bind(var6)(var16);
            var2 = var23.bind(var4)(var2, var9);
            var26 = var2[var8];
            var2 = var2[var3];
            _closure2_slot3 = var2;
            var12 = _closure1_slot0;
            var19 = 12;
            var19 = var20[var19];
            var25 = var12.bind(var4)(var19);
            var19 = var25.usePreviewCollectibleProduct;
            var19 = var19.bind(var25)(var18, var26);
            var25 = {};
            var25['product'] = var18;
            var25['analyticsLocations'] = var17;
            var25['setShouldReset'] = var2;
            var19 = function useHandlePreviewPress(arg1) {
                _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
case 0:
                    var2 = arg1;
                    var3 = var2.product;
                    var _closure3_slot0 = var3;
                    var9 = var2.analyticsLocations;
                    var _closure3_slot1 = var9;
                    var11 = var2.setShouldReset;
                    var _closure3_slot2 = var11;
                    var5 = _closure1_slot0;
                    var6 = _closure1_slot2;
                    var2 = 6;
                    var7 = var6[var2];
                    var2 = undefined;
                    var8 = var5.bind(var2)(var7);
                    var7 = var8.useCurrentUser;
                    var10 = var7.bind(var8)();
                    var _closure3_slot3 = var10;
                    var8 = _closure1_slot4;
                    var7 = var8.useCallback;
                    var4 = new Array(4);
                    var4[0] = var3;
                    var4[1] = var11;
                    var10 = var10.id;
                    var4[2] = var10;
                    var4[3] = var9;
                    var1 = function() {
                        var3 = _closure3_slot2;
                        var1 = undefined;
                        var2 = false;
                        var2 = var3.bind(var1)(var2);
                        var3 = _closure1_slot1;
                        var5 = _closure1_slot2;
                        var2 = 7;
                        var2 = var5[var2];
                        var3 = var3.bind(var1)(var2);
                        var2 = {};
                        var5 = _closure3_slot3;
                        var5 = var5.id;
                        var2['userId'] = var5;
                        var5 = true;
                        var2['isPreviewingChanges'] = var5;
                        var4 = _closure3_slot1;
                        var2['sourceAnalyticsLocations'] = var4;
                        var4 = function onClose() {
                            var3 = _closure1_slot0;
                            var2 = _closure1_slot2;
                            var1 = 8;
                            var2 = var2[var1];
                            var1 = undefined;
                            var3 = var3.bind(var1)(var2);
                            var2 = var3.openProductDetailActionSheet;
                            var1 = {};
                            var5 = _closure3_slot0;
                            var1['product'] = var5;
                            var4 = _closure3_slot1;
                            var1['analyticsLocations'] = var4;
                            var1 = var2.bind(var3)(var1);
                            return var1;
                        };
                        var2['onClose'] = var4;
                        var2 = var3.bind(var1)(var2);
                        return var1;
                    };
                    var1 = var7.bind(var8)(var1, var4);
                    var4 = var3.type;
                    var3 = 9;
                    var3 = var6[var3];
                    var3 = var5.bind(var2)(var3);
                    var3 = var3.CollectiblesItemType;
                    var3 = var3.NAMEPLATE;
                    if(!(var4 === var3)) { _fun0002_ip = 4; continue _fun0002 }
case 5:
                    return var2;
case 4:
                    return var1;
                }
            };
            var25 = var19.bind(var4)(var25);
            var26 = _closure1_slot5;
            var19 = new Array(2);
            var19[0] = var18;
            var19[1] = var2;
            var2 = function() {
                _fun0003: for(var _fun0003_ip = 0; ; ) switch(_fun0003_ip) {
case 0:
                    var1 = _closure2_slot0;
                    var4 = var1.type;
                    var5 = _closure1_slot0;
                    var3 = _closure1_slot2;
                    var1 = 9;
                    var3 = var3[var1];
                    var1 = undefined;
                    var3 = var5.bind(var1)(var3);
                    var3 = var3.CollectiblesItemType;
                    var3 = var3.BUNDLE;
                    if(!(var4 === var3)) { _fun0003_ip = 6; continue _fun0003 }
case 7:
                    var3 = _closure2_slot3;
                    var2 = false;
                    var2 = var3.bind(var1)(var2);
case 6:
                    return var1;
                }
            };
            var19 = var26.bind(var4)(var2, var19);
            var2 = var6.useState;
            var2 = var2.bind(var6)(var3);
            var2 = var23.bind(var4)(var2, var9);
            var9 = var2[var8];
            _closure2_slot4 = var9;
            var2 = var2[var3];
            _closure2_slot5 = var2;
            var8 = var6.useCallback;
            var3 = new Array(2);
            var3[0] = var9;
            var3[1] = var2;
            var2 = function(arg1) {
                _fun0004: for(var _fun0004_ip = 0; ; ) switch(_fun0004_ip) {
case 0:
                    var1 = arg1;
                    var2 = var1.nativeEvent;
                    var2 = var2.layout;
                    var4 = var2.height;
                    var3 = _closure2_slot4;
                    if(!(var4 !== var3)) { _fun0004_ip = 8; continue _fun0004 }
case 2:
                    var3 = _closure2_slot5;
                    var1 = var1.nativeEvent;
                    var1 = var1.layout;
                    var2 = var1.height;
                    var1 = undefined;
                    var1 = var3.bind(var1)(var2);
case 8:
                    var1 = undefined;
                    return var1;
                }
            };
            var23 = var8.bind(var6)(var2, var3);
            var3 = var6.useEffect;
            var2 = new Array(2);
            var2[0] = var1;
            var1 = var18.skuId;
            var2[1] = var1;
            var1 = function() {
                var4 = _closure1_slot1;
                var3 = _closure1_slot2;
                var1 = 13;
                var3 = var3[var1];
                var1 = undefined;
                var5 = var4.bind(var1)(var3);
                var4 = var5.track;
                var2 = _closure1_slot6;
                var3 = var2.OPEN_MODAL;
                var2 = {};
                var6 = 'Collectibles Shop Details Modal';
                var2['type'] = var6;
                var7 = _closure2_slot1;
                var2['location_stack'] = var7;
                var6 = _closure2_slot0;
                var6 = var6.skuId;
                var2['sku_id'] = var6;
                var2 = var4.bind(var5)(var3, var2);
                return var1;
            };
            var1 = var3.bind(var6)(var1, var2);
            var3 = _closure1_slot7;
            var1 = 14;
            var1 = var20[var1];
            var1 = var12.bind(var4)(var1);
            var2 = var1.ThemeContextProvider;
            var1 = {};
            var5 = var20[var5];
            var5 = var12.bind(var4)(var5);
            var6 = var5.AnalyticsLocationProvider;
            var5 = {};
            var5['value'] = var17;
            var9 = _closure1_slot8;
            var7 = 15;
            var7 = var20[var7];
            var7 = var12.bind(var4)(var7);
            var8 = var7.BottomSheet;
            var7 = {'scrollable': true, 'startExpanded': true};
            var11 = function onExpand() {
                _fun0005: for(var _fun0005_ip = 0; ; ) switch(_fun0005_ip) {
case 0:
                    var1 = _closure2_slot2;
                    var4 = var1.current;
                    var1 = null;
                    var2 = var1 == var4;
                    var1 = undefined;
                    if(var2) { _fun0005_ip = 9; continue _fun0005 }
case 10:
                    var3 = var4.scrollToEnd;
                    var2 = {};
                    var5 = true;
                    var2['animated'] = var5;
                    var1 = var3.bind(var4)(var2);
case 9:
                    return var1;
                }
            };
            var7['onExpand'] = var11;
            var7['ref'] = var10;
            var10 = 16;
            var10 = var20[var10];
            var10 = var12.bind(var4)(var10);
            var11 = var10.BottomSheetScrollView;
            var10 = {};
            var10['onLayout'] = var23;
            var23 = false;
            var10['scrollsToTop'] = var23;
            var23 = var22.container;
            var22 = new Array(1);
            var22[0] = var23;
            var10['style'] = var22;
            var22 = {};
            var22['bottom'] = var24;
            var10['scrollIndicatorInsets'] = var22;
            var10['ref'] = var21;
            var22 = 17;
            var21 = var20[var22];
            var21 = var12.bind(var4)(var21);
            var23 = var21.PreviewContent;
            var21 = {};
            var21['product'] = var18;
            var21['handlePreviewPress'] = var25;
            var23 = var3.bind(var4)(var23, var21);
            var21 = new Array(3);
            var21[0] = var23;
            var22 = var20[var22];
            var22 = var12.bind(var4)(var22);
            var23 = var22.ProductDetailsV2;
            var22 = {};
            var22['product'] = var18;
            var22['onBuy'] = var19;
            var22['analyticsLocations'] = var17;
            var22 = var3.bind(var4)(var23, var22);
            var21[1] = var22;
            var22 = 18;
            var22 = var20[var22];
            var23 = var14.bind(var4)(var22);
            var22 = {};
            var22['size'] = var24;
            var22 = var3.bind(var4)(var23, var22);
            var21[2] = var22;
            var10['children'] = var21;
            var11 = var9.bind(var4)(var11, var10);
            var10 = new Array(2);
            var10[0] = var11;
            var11 = 19;
            var11 = var20[var11];
            var11 = var12.bind(var4)(var11);
            var12 = var11.NativePaymentContextProvider;
            var11 = {};
            var21 = new Array(0);
            var11['skuIDs'] = var21;
            var11['activeSubscription'] = var13;
            var13 = 20;
            var13 = var20[var13];
            var14 = var14.bind(var4)(var13);
            var13 = {};
            var13['onBuy'] = var19;
            var13['product'] = var18;
            var13['analyticsLocations'] = var17;
            var13['condensed'] = var16;
            var13['onHeightChange'] = var15;
            var13 = var3.bind(var4)(var14, var13);
            var11['children'] = var13;
            var11 = var3.bind(var4)(var12, var11);
            var10[1] = var11;
            var7['children'] = var10;
            var7 = var9.bind(var4)(var8, var7);
            var5['children'] = var7;
            var5 = var3.bind(var4)(var6, var5);
            var1['children'] = var5;
            var1 = var3.bind(var4)(var2, var1);
            return var1;
        }
    };
    var3['default'] = var2;
    return var1;
})();