// app/modules/collectibles/native/SkeletonCard.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var1 = metroImportDefault;
    var _closure1_slot1 = var1;
    var _closure1_slot2 = var6;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var7 = var6[var1];
    var4 = metroImportAll;
    var1 = undefined;
    var4 = var4.bind(var1)(var7);
    var _closure1_slot3 = var4;
    var4 = 1;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.jsx;
    var _closure1_slot4 = var4;
    var4 = 2;
    var4 = var6[var4];
    var8 = var5.bind(var1)(var4);
    var7 = var8.createStyles;
    var4 = function(arg1, arg2) {
        var1 = {};
        var2 = {};
        var3 = arg1;
        var2['width'] = var3;
        var3 = arg2;
        var2['height'] = var3;
        var5 = _closure1_slot1;
        var6 = _closure1_slot2;
        var3 = 3;
        var7 = var6[var3];
        var4 = undefined;
        var7 = var5.bind(var4)(var7);
        var7 = var7.colors;
        var7 = var7.BACKGROUND_MODIFIER_ACCENT;
        var2['backgroundColor'] = var7;
        var3 = var6[var3];
        var3 = var5.bind(var4)(var3);
        var3 = var3.radii;
        var3 = var3.sm;
        var2['borderRadius'] = var3;
        var1['skeletonCard'] = var2;
        return var1;
    };
    var4 = var7.bind(var8)(var4);
    var _closure1_slot5 = var4;
    var4 = {};
    var7 = 'function SkeletonCardTsx1(){const{opacity}=this.__closure;return{opacity:opacity.get()};}';
    var4['code'] = var7;
    var _closure1_slot6 = var4;
    var4 = 7;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/collectibles/native/SkeletonCard.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function _default(arg1) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var1 = arg1;
            var6 = var1.width;
            var4 = undefined;
            if(!(var6 === var4)) { _fun0001_ip = 2; continue _fun0001 }
case 3:
            var5 = _closure1_slot0;
            var7 = _closure1_slot2;
            var2 = 4;
            var2 = var7[var2];
            var2 = var5.bind(var4)(var2);
            var6 = var2.COLLECTIBLES_SHOP_CARD_WIDTH;
case 2:
            var5 = var1.height;
            var7 = var1.style;
            var _closure2_slot0 = var4;
            var1 = null;
            if(!(var1 == var5)) { _fun0001_ip = 4; continue _fun0001 }
case 5:
            var2 = _closure1_slot0;
            var8 = _closure1_slot2;
            var1 = 4;
            var1 = var8[var1];
            var1 = var2.bind(var4)(var1);
            var5 = var1.COLLECTIBLES_SHOP_CARD_HEIGHT;
case 4:
            var1 = _closure1_slot5;
            var5 = var1.bind(var4)(var6, var5);
            var9 = _closure1_slot0;
            var8 = _closure1_slot2;
            var1 = 5;
            var6 = var8[var1];
            var11 = var9.bind(var4)(var6);
            var10 = var11.useSharedValue;
            var6 = 0.3;
            var11 = var10.bind(var11)(var6);
            _closure2_slot0 = var11;
            var13 = _closure1_slot3;
            var12 = var13.useEffect;
            var10 = new Array(1);
            var10[0] = var11;
            var6 = function() {
                var4 = _closure2_slot0;
                var3 = var4.set;
                var5 = _closure1_slot0;
                var6 = _closure1_slot2;
                var1 = 5;
                var2 = var6[var1];
                var1 = undefined;
                var8 = var5.bind(var1)(var2);
                var7 = var8.withRepeat;
                var2 = 6;
                var2 = var6[var2];
                var9 = var5.bind(var1)(var2);
                var6 = var9.withTiming;
                var5 = {};
                var2 = 650;
                var5['duration'] = var2;
                var2 = 1;
                var6 = var6.bind(var9)(var2, var5);
                var5 = -1;
                var2 = true;
                var2 = var7.bind(var8)(var6, var5, var2);
                var2 = var3.bind(var4)(var2);
                return var1;
            };
            var6 = var12.bind(var13)(var6, var10);
            var6 = var8[var1];
            var9 = var9.bind(var4)(var6);
            var6 = var9.useAnimatedStyle;
            var3 = function y() {
                var1 = {};
                var3 = _closure2_slot0;
                var2 = var3.get;
                var2 = var2.bind(var3)();
                var1['opacity'] = var2;
                return var1;
            };
            var10 = {};
            var10['opacity'] = var11;
            var3['__closure'] = var10;
            var10 = 5620456625640.0;
            var3['__workletHash'] = var10;
            var10 = _closure1_slot6;
            var3['__initData'] = var10;
            var6 = var6.bind(var9)(var3);
            var3 = _closure1_slot4;
            var2 = _closure1_slot1;
            var1 = var8[var1];
            var1 = var2.bind(var4)(var1);
            var2 = var1.View;
            var1 = {};
            var8 = var5.skeletonCard;
            var5 = new Array(3);
            var5[0] = var8;
            var5[1] = var7;
            var5[2] = var6;
            var1['style'] = var5;
            var1 = var3.bind(var4)(var2, var1);
            return var1;
        }
    };
    var3['default'] = var2;
    return var1;
})();