// app/modules/application_commands/native/ContextMenuCommandItem.tsx
export default (function(argFoo, argBar, argBaz, argCorge, _, argFred, argPlugh) {
    report = argBar;
    yankee = argBaz;
    zulu = argFred;
    oscar = argPlugh;
    var _closure1_slot0 = report;
    var _closure1_slot1 = yankee;
    var _closure1_slot2 = oscar;
    entity = function(argFoo) { // Original name: SendButton
        entity = argFoo;
        golf = entity.onPress;
        tango = _closure1_slot5;
        oscar = _closure1_slot0;
        options = _closure1_slot2;
        entity = 5;
        entity = options[entity];
        zulu = undefined;
        entity = oscar.bind(zulu)(entity);
        mike = entity.Button;
        entity = {'accessibilityRole': 'none', 'size': 'sm', 'variant': 'secondary'};
        verify = 6;
        offset = options[verify];
        offset = oscar.bind(zulu)(offset);
        yankee = offset.intl;
        offset = yankee.string;
        verify = options[verify];
        verify = oscar.bind(zulu)(verify);
        verify = verify.t;
        verify = verify.TXNS7e;
        verify = offset.bind(yankee)(verify);
        entity['text'] = verify;
        entity['onPress'] = golf;
        golf = _closure1_slot5;
        report = 7;
        report = options[report];
        report = oscar.bind(zulu)(report);
        oscar = report.SendMessageIcon;
        report = {};
        options = 'xs';
        report['size'] = options;
        report = golf.bind(zulu)(oscar, report);
        entity['icon'] = report;
        report = true;
        entity['grow'] = report;
        entity = tango.bind(zulu)(mike, entity);
        return entity;
    };
    var _closure1_slot7 = entity;
    entity = global;
    options = entity.Object;
    golf = options.defineProperty;
    tango = {};
    entity = true;
    tango['value'] = entity;
    entity = '__esModule';
    entity = golf.bind(options)(zulu, entity, tango);
    entity = 0;
    golf = oscar[entity];
    tango = argCorge;
    entity = undefined;
    tango = tango.bind(entity)(golf);
    var _closure1_slot3 = tango;
    tango = 1;
    tango = oscar[tango];
    tango = report.bind(entity)(tango);
    tango = tango.View;
    var _closure1_slot4 = tango;
    tango = 2;
    tango = oscar[tango];
    tango = report.bind(entity)(tango);
    tango = tango.jsx;
    var _closure1_slot5 = tango;
    tango = 3;
    tango = oscar[tango];
    options = report.bind(entity)(tango);
    golf = options.createStyles;
    tango = {};
    verify = {'width': 32, 'height': 32};
    offset = 4;
    romeo = oscar[offset];
    romeo = yankee.bind(entity)(romeo);
    romeo = romeo.radii;
    romeo = romeo.lg;
    verify['borderRadius'] = romeo;
    tango['commandIcon'] = verify;
    verify = {};
    romeo = oscar[offset];
    romeo = yankee.bind(entity)(romeo);
    romeo = romeo.colors;
    romeo = romeo.BACKGROUND_ACCENT;
    verify['backgroundColor'] = romeo;
    tango['loadingIcon'] = verify;
    verify = {};
    romeo = oscar[offset];
    romeo = yankee.bind(entity)(romeo);
    romeo = romeo.colors;
    romeo = romeo.BACKGROUND_ACCENT;
    verify['backgroundColor'] = romeo;
    romeo = 24;
    verify['height'] = romeo;
    offset = oscar[offset];
    offset = yankee.bind(entity)(offset);
    offset = offset.radii;
    offset = offset.md;
    verify['borderRadius'] = offset;
    tango['loadingName'] = verify;
    tango = golf.bind(options)(tango);
    var _closure1_slot6 = tango;
    tango = 13;
    tango = oscar[tango];
    oscar = report.bind(entity)(tango);
    report = oscar.fileFinishedImporting;
    tango = 'modules/application_commands/native/ContextMenuCommandItem.tsx';
    tango = report.bind(oscar)(tango);
    tango = function(argFoo) { // Original name: ContextMenuCommandItem
        _fun82017: for(var _fun82017_ip = 0; ; ) switch(_fun82017_ip) {
 0:
            mike = argFoo;
            golf = mike.item;
            var _closure2_slot0 = golf;
            options = mike.onPress;
            yankee = mike.section;
            var _closure2_slot1 = yankee;
            mike = _closure1_slot6;
            tango = undefined;
            romeo = mike.bind(tango)();
            verify = _closure1_slot3;
            zulu = verify.useMemo;
            mike = new Array(2);
            mike[0] = golf;
            oscar = null;
            foxtrot = oscar == yankee;
            offset = undefined;
            if(foxtrot) { _fun82017_ip = 74; continue _fun82017 }
 69:
            offset = yankee.name;
 74:
            mike[1] = offset;
            entity = function() {
                _fun82018: for(var _fun82018_ip = 0; ; ) switch(_fun82018_ip) {
 0:
                    entity = _closure2_slot0;
                    zulu = entity.type;
                    tango = _closure1_slot0;
                    mike = _closure1_slot2;
                    golf = 10;
                    mike = mike[golf];
                    oscar = undefined;
                    mike = tango.bind(oscar)(mike);
                    mike = mike.ApplicationCommandType;
                    mike = mike.MESSAGE;
                    if(!(mike !== zulu)) { _fun82018_ip = 88; continue _fun82018 }
 53:
                    tango = _closure1_slot0;
                    mike = _closure1_slot2;
                    mike = mike[golf];
                    mike = tango.bind(oscar)(mike);
                    mike = mike.ApplicationCommandType;
                    mike = mike.USER;
                    if(!(mike !== zulu)) { _fun82018_ip = 88; continue _fun82018 }
 86:
                    return oscar;
 88:
                    mike = _closure1_slot0;
                    golf = _closure1_slot2;
                    entity = 6;
                    zulu = golf[entity];
                    zulu = mike.bind(oscar)(zulu);
                    tango = zulu.intl;
                    zulu = tango.formatToPlainString;
                    entity = golf[entity];
                    entity = mike.bind(oscar)(entity);
                    entity = entity.t;
                    mike = entity.Pk4Mz8;
                    entity = {};
                    options = _closure2_slot1;
                    golf = null;
                    golf = golf == options;
                    oscar = undefined;
                    if(golf) { _fun82018_ip = 164; continue _fun82018 }
 155:
                    golf = _closure2_slot1;
                    oscar = golf.name;
 164:
                    entity['applicationName'] = oscar;
                    report = _closure2_slot0;
                    report = report.displayName;
                    entity['commandName'] = report;
                    entity = zulu.bind(tango)(mike, entity);
                    return entity;
                }
            };
            verify = zulu.bind(verify)(entity, mike);
            mike = _closure1_slot0;
            offset = _closure1_slot2;
            entity = 11;
            entity = offset[entity];
            zulu = mike.bind(tango)(entity);
            entity = zulu.getApplicationCommandsIconSource;
            yankee = entity.bind(zulu)(yankee);
            zulu = _closure1_slot5;
            entity = 8;
            entity = offset[entity];
            entity = mike.bind(tango)(entity);
            mike = entity.FormRow;
            entity = {};
            entity['accessibilityLabel'] = verify;
            entity['onPress'] = options;
            golf = golf.displayName;
            entity['label'] = golf;
            oscar = oscar != yankee;
            if(!oscar) { _fun82017_ip = 216; continue _fun82017 }
 170:
            offset = _closure1_slot5;
            verify = _closure1_slot1;
            foxtrot = _closure1_slot2;
            golf = 12;
            golf = foxtrot[golf];
            verify = verify.bind(tango)(golf);
            golf = {};
            romeo = romeo.commandIcon;
            golf['style'] = romeo;
            golf['source'] = yankee;
            oscar = offset.bind(tango)(verify, golf);
 216:
            entity['leading'] = oscar;
            golf = _closure1_slot5;
            oscar = _closure1_slot7;
            report = {};
            report['onPress'] = options;
            report = golf.bind(tango)(oscar, report);
            entity['trailing'] = report;
            entity = zulu.bind(tango)(mike, entity);
            return entity;
        }
    };
    zulu['default'] = tango;
    tango = function() { // Original name: ContextMenuCommandLoadingItem
        entity = _closure1_slot6;
        tango = undefined;
        verify = entity.bind(tango)();
        zulu = _closure1_slot5;
        mike = _closure1_slot0;
        backup = _closure1_slot2;
        entity = 8;
        entity = backup[entity];
        entity = mike.bind(tango)(entity);
        mike = entity.FormRow;
        entity = {};
        options = _closure1_slot5;
        golf = _closure1_slot4;
        oscar = {};
        yankee = verify.loadingName;
        offset = new Array(2);
        offset[0] = yankee;
        yankee = {};
        foxtrot = _closure1_slot1;
        romeo = 9;
        romeo = backup[romeo];
        kilo = foxtrot.bind(tango)(romeo);
        backup = kilo.random;
        foxtrot = 60;
        romeo = 80;
        kilo = backup.bind(kilo)(foxtrot, romeo);
        romeo = global;
        romeo = romeo.HermesInternal;
        backup = romeo.concat;
        foxtrot = '';
        romeo = '%';
        romeo = backup.bind(foxtrot)(kilo, romeo);
        yankee['width'] = romeo;
        offset[1] = yankee;
        oscar['style'] = offset;
        oscar = options.bind(tango)(golf, oscar);
        entity['label'] = oscar;
        oscar = _closure1_slot5;
        report = {};
        offset = verify.commandIcon;
        options = new Array(2);
        options[0] = offset;
        verify = verify.loadingIcon;
        options[1] = verify;
        report['style'] = options;
        report = oscar.bind(tango)(golf, report);
        entity['leading'] = report;
        entity = zulu.bind(tango)(mike, entity);
        return entity;
    };
    zulu['ContextMenuCommandLoadingItem'] = tango;
    mike = function() { // Original name: ContextMenuCommandEmptyItem
        entity = _closure1_slot6;
        tango = undefined;
        verify = entity.bind(tango)();
        zulu = _closure1_slot5;
        offset = _closure1_slot0;
        yankee = _closure1_slot2;
        entity = 8;
        entity = yankee[entity];
        entity = offset.bind(tango)(entity);
        mike = entity.FormRow;
        entity = {};
        oscar = 6;
        golf = yankee[oscar];
        golf = offset.bind(tango)(golf);
        options = golf.intl;
        golf = options.string;
        oscar = yankee[oscar];
        oscar = offset.bind(tango)(oscar);
        oscar = oscar.t;
        oscar = oscar.YSNlV1;
        oscar = golf.bind(options)(oscar);
        entity['label'] = oscar;
        golf = _closure1_slot5;
        oscar = _closure1_slot4;
        report = {};
        offset = verify.commandIcon;
        options = new Array(2);
        options[0] = offset;
        verify = verify.loadingIcon;
        options[1] = verify;
        report['style'] = options;
        report = golf.bind(tango)(oscar, report);
        entity['leading'] = report;
        entity = zulu.bind(tango)(mike, entity);
        return entity;
    };
    zulu['ContextMenuCommandEmptyItem'] = mike;
    return entity;
})();