// app/modules/image/native/ImagePicker.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var9 = metroImportDefault;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var9;
    var _closure1_slot2 = var6;
    var8 = function launchImageLibrary(arg1, arg2) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var2 = arg1;
            var3 = var2.mediaType;
            var1 = 'any';
            if(!(var1 === var3)) { _fun0001_ip = 2; continue _fun0001 }
case 3:
            var4 = _closure1_slot0;
            var3 = _closure1_slot2;
            var1 = 2;
            var3 = var3[var1];
            var1 = undefined;
            var3 = var4.bind(var1)(var3);
            var1 = var3.isIOS;
            var1 = var1.bind(var3)();
            var10 = 'mixed';
            if(var1) { _fun0001_ip = 4; continue _fun0001 }
case 2:
            var10 = var2.mediaType;
case 4:
            var8 = var2.selections;
            var1 = null;
            if(!(var1 == var8)) { _fun0001_ip = 5; continue _fun0001 }
case 6:
            var8 = new Array(0);
case 5:
            var1 = var2.disableNewIOSPicker;
            var7 = !var1;
            var5 = _closure1_slot0;
            var4 = _closure1_slot2;
            var1 = 2;
            var4 = var4[var1];
            var1 = undefined;
            var5 = var5.bind(var1)(var4);
            var4 = var5.isIOS;
            var4 = var4.bind(var5)();
            var9 = undefined;
            if(!var4) { _fun0001_ip = 7; continue _fun0001 }
case 8:
            var9 = 'pageSheet';
case 7:
            var4 = _closure1_slot0;
            var5 = _closure1_slot2;
            var3 = 3;
            var3 = var5[var3];
            var6 = var4.bind(var1)(var3);
            var3 = var6.isActionPickSupported;
            var3 = var3.bind(var6)();
            var6 = !var3;
            var3 = 4;
            var3 = var5[var3];
            var5 = var4.bind(var1)(var3);
            var4 = var5.launchImageLibrary;
            var3 = {};
            var12 = var3;
            var11 = var2;
            var2 = copyDataProperties(var12, var11);
            var2 = 'mediaType';
            var3[var2] = var10;
            var2 = 'presentationStyle';
            var3[var2] = var9;
            var2 = 'selection';
            var3[var2] = var8;
            var2 = 'useNewIOSPicker';
            var3[var2] = var7;
            var2 = 'forceGetContent';
            var3[var2] = var6;
            var2 = arg2;
            var2 = var4.bind(var5)(var3, var2);
            return var1;
        }
    };
    var _closure1_slot5 = var8;
    var7 = function launchCamera(arg1, arg2) {
        var3 = _closure1_slot0;
        var2 = _closure1_slot2;
        var1 = 4;
        var2 = var2[var1];
        var1 = undefined;
        var5 = var3.bind(var1)(var2);
        var4 = var5.launchCamera;
        var3 = arg1;
        var2 = arg2;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var _closure1_slot6 = var7;
    var1 = global;
    var11 = var1.Object;
    var10 = var11.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var10.bind(var11)(var3, var1, var2);
    var1 = 0;
    var2 = var6[var1];
    var1 = undefined;
    var2 = var9.bind(var1)(var2);
    var _closure1_slot3 = var2;
    var2 = 1;
    var2 = var6[var2];
    var2 = var5.bind(var1)(var2);
    var2 = var2.ThemeTypes;
    var _closure1_slot4 = var2;
    var2 = {};
    var2['launchImageLibrary'] = var8;
    var8 = function launchImageLibraryAsync(arg1) {
        var2 = arg1;
        var _closure2_slot0 = var2;
        var2 = global;
        var3 = var2.Promise;
        var2 = var3.prototype;
        var2 = Object.create(var2, {constructor: {value: var3}});
        var4 = function(arg1) {
            var1 = arg1;
            var _closure3_slot0 = var1;
            var4 = _closure1_slot5;
            var3 = _closure2_slot0;
            var1 = undefined;
            var2 = function(arg1) {
                var3 = _closure3_slot0;
                var1 = undefined;
                var2 = arg1;
                var2 = var3.bind(var1)(var2);
                return var1;
            };
            var2 = var4.bind(var1)(var3, var2);
            return var1;
        };
        var5 = var2;
        var1 = new var5[var3](var4, var3);
        var1 = var1 instanceof Object ? var1 : var2;
        return var1;
    };
    var2['launchImageLibraryAsync'] = var8;
    var2['launchCamera'] = var7;
    var7 = function launchCameraAsync(arg1) {
        var2 = arg1;
        var _closure2_slot0 = var2;
        var2 = global;
        var3 = var2.Promise;
        var2 = var3.prototype;
        var2 = Object.create(var2, {constructor: {value: var3}});
        var4 = function(arg1) {
            var1 = arg1;
            var _closure3_slot0 = var1;
            var4 = _closure1_slot6;
            var3 = _closure2_slot0;
            var1 = undefined;
            var2 = function(arg1) {
                var3 = _closure3_slot0;
                var1 = undefined;
                var2 = arg1;
                var2 = var3.bind(var1)(var2);
                return var1;
            };
            var2 = var4.bind(var1)(var3, var2);
            return var1;
        };
        var5 = var2;
        var1 = new var5[var3](var4, var3);
        var1 = var1 instanceof Object ? var1 : var2;
        return var1;
    };
    var2['launchCameraAsync'] = var7;
    var4 = function launchCropper(arg1) {
        var1 = arg1;
        var19 = var1.uri;
        var18 = var1.width;
        var17 = var1.height;
        var16 = var1.includeBase64;
        var15 = var1.mimeType;
        var13 = var1.freeStyleCropEnabled;
        var1 = _closure1_slot3;
        var14 = var1.theme;
        var2 = _closure1_slot1;
        var9 = _closure1_slot2;
        var1 = 5;
        var3 = var9[var1];
        var8 = undefined;
        var3 = var2.bind(var8)(var3);
        var6 = var3.internal;
        var5 = var6.resolveSemanticColor;
        var3 = var9[var1];
        var3 = var2.bind(var8)(var3);
        var3 = var3.colors;
        var3 = var3.BACKGROUND_BASE_LOW;
        var6 = var5.bind(var6)(var14, var3);
        var3 = var9[var1];
        var3 = var2.bind(var8)(var3);
        var7 = var3.internal;
        var5 = var7.resolveSemanticColor;
        var3 = var9[var1];
        var3 = var2.bind(var8)(var3);
        var3 = var3.colors;
        var3 = var3.BACKGROUND_SURFACE_HIGH;
        var11 = var5.bind(var7)(var14, var3);
        var3 = var9[var1];
        var3 = var2.bind(var8)(var3);
        var7 = var3.internal;
        var5 = var7.resolveSemanticColor;
        var3 = var9[var1];
        var3 = var2.bind(var8)(var3);
        var3 = var3.colors;
        var3 = var3.MOBILE_TEXT_HEADING_PRIMARY;
        var5 = var5.bind(var7)(var14, var3);
        var3 = var9[var1];
        var3 = var2.bind(var8)(var3);
        var10 = var3.internal;
        var7 = var10.resolveSemanticColor;
        var3 = var9[var1];
        var3 = var2.bind(var8)(var3);
        var3 = var3.colors;
        var3 = var3.TEXT_MUTED;
        var12 = var7.bind(var10)(var14, var3);
        var3 = var9[var1];
        var3 = var2.bind(var8)(var3);
        var10 = var3.internal;
        var7 = var10.resolveSemanticColor;
        var3 = var9[var1];
        var3 = var2.bind(var8)(var3);
        var3 = var3.colors;
        var3 = var3.TEXT_BRAND;
        var7 = var7.bind(var10)(var14, var3);
        var3 = var9[var1];
        var3 = var2.bind(var8)(var3);
        var10 = var3.internal;
        var3 = var10.resolveSemanticColor;
        var1 = var9[var1];
        var1 = var2.bind(var8)(var1);
        var1 = var1.colors;
        var1 = var1.TEXT_DEFAULT;
        var10 = var3.bind(var10)(var14, var1);
        var1 = 6;
        var1 = var9[var1];
        var3 = var2.bind(var8)(var1);
        var2 = var3.openCropper;
        var1 = {};
        var20 = 'photo';
        var1['mediaType'] = var20;
        var1['path'] = var19;
        var1['width'] = var18;
        var1['height'] = var17;
        var1['includeBase64'] = var16;
        var1['mimeType'] = var15;
        var1['freeStyleCropEnabled'] = var13;
        var13 = _closure1_slot4;
        var15 = var13.LIGHT;
        var15 = var14 === var15;
        var1['cropperStatusBarLight'] = var15;
        var13 = var13.LIGHT;
        var13 = var14 === var13;
        var1['cropperNavigationBarLight'] = var13;
        var1['cropperActiveWidgetColor'] = var5;
        var1['cropperInactiveWidgetColor'] = var12;
        var1['cropperControlsColor'] = var11;
        var1['cropperControlsBarColor'] = var6;
        var1['cropperChooseColor'] = var7;
        var7 = _closure1_slot0;
        var4 = 7;
        var11 = var9[var4];
        var11 = var7.bind(var8)(var11);
        var13 = var11.intl;
        var12 = var13.string;
        var11 = var9[var4];
        var11 = var7.bind(var8)(var11);
        var11 = var11.t;
        var11 = var11["1Qm822"];
        var11 = var12.bind(var13)(var11);
        var1['cropperChooseText'] = var11;
        var1['cropperCancelColor'] = var10;
        var10 = var9[var4];
        var10 = var7.bind(var8)(var10);
        var12 = var10.intl;
        var11 = var12.string;
        var10 = var9[var4];
        var10 = var7.bind(var8)(var10);
        var10 = var10.t;
        var10 = var10.ETE/oC;
        var10 = var11.bind(var12)(var10);
        var1['cropperCancelText'] = var10;
        var1['cropperToolbarColor'] = var6;
        var1['cropperToolbarWidgetColor'] = var5;
        var5 = var9[var4];
        var5 = var7.bind(var8)(var5);
        var10 = var5.intl;
        var6 = var10.string;
        var5 = var9[var4];
        var5 = var7.bind(var8)(var5);
        var5 = var5.t;
        var5 = var5.b0y3DL;
        var5 = var6.bind(var10)(var5);
        var1['cropperToolbarTitle'] = var5;
        var5 = var9[var4];
        var5 = var7.bind(var8)(var5);
        var10 = var5.intl;
        var6 = var10.string;
        var5 = var9[var4];
        var5 = var7.bind(var8)(var5);
        var5 = var5.t;
        var5 = var5.Izf9u1;
        var5 = var6.bind(var10)(var5);
        var1['cropperRotateByAngleAccessibilityLabel'] = var5;
        var5 = var9[var4];
        var5 = var7.bind(var8)(var5);
        var10 = var5.intl;
        var6 = var10.string;
        var5 = var9[var4];
        var5 = var7.bind(var8)(var5);
        var5 = var5.t;
        var5 = var5.iz4w1M;
        var5 = var6.bind(var10)(var5);
        var1['cropperResetRotationAccessibilityLabel'] = var5;
        var5 = var9[var4];
        var5 = var7.bind(var8)(var5);
        var6 = var5.intl;
        var5 = var6.string;
        var4 = var9[var4];
        var4 = var7.bind(var8)(var4);
        var4 = var4.t;
        var4 = var4.QHvDTL;
        var4 = var5.bind(var6)(var4);
        var1['cropperClampButtonAccessibilityLabel'] = var4;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var2['launchCropper'] = var4;
    var4 = 8;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/image/native/ImagePicker.tsx';
    var4 = var5.bind(var6)(var4);
    var3['default'] = var2;
    return var1;
})();