// app/modules/guild_settings/GuildSettingsModalChannelsActionCreators.tsx
export default (function(argFoo, argBar, argBaz, _, __, argFred, argPlugh) {
    zulu = argFred;
    tango = argPlugh;
    mike = argBaz;
    var _closure1_slot0 = mike;
    var _closure1_slot1 = tango;
    mike = global;
    golf = mike.Object;
    oscar = golf.defineProperty;
    report = {};
    mike = true;
    report['value'] = mike;
    mike = '__esModule';
    mike = oscar.bind(golf)(zulu, mike, report);
    mike = {};
    report = function() { // Original name: terminate
        zulu = _closure1_slot0;
        mike = _closure1_slot1;
        entity = 0;
        mike = mike[entity];
        entity = undefined;
        tango = zulu.bind(entity)(mike);
        zulu = tango.dispatch;
        mike = {};
        report = 'GUILD_SETTINGS_MODAL_CHANNELS_TERMINATE';
        mike['type'] = report;
        mike = zulu.bind(tango)(mike);
        return entity;
    };
    mike['terminate'] = report;
    report = function(argFoo) { // Original name: startReordering
        mike = 0;
        golf = 0;
        report = copyRestArgs(golf);
        zulu = _closure1_slot0;
        entity = _closure1_slot1;
        mike = entity[mike];
        entity = undefined;
        tango = zulu.bind(entity)(mike);
        zulu = tango.dispatch;
        mike = {};
        oscar = 'GUILD_SETTINGS_MODAL_CHANNELS_START_REORDER';
        mike['type'] = oscar;
        mike['sortingType'] = report;
        mike = zulu.bind(tango)(mike);
        return entity;
    };
    mike['startReordering'] = report;
    report = function() { // Original name: stopReordering
        zulu = _closure1_slot0;
        mike = _closure1_slot1;
        entity = 0;
        mike = mike[entity];
        entity = undefined;
        tango = zulu.bind(entity)(mike);
        zulu = tango.dispatch;
        mike = {};
        report = 'GUILD_SETTINGS_MODAL_CHANNELS_STOP_REORDER';
        mike['type'] = report;
        mike = zulu.bind(tango)(mike);
        return entity;
    };
    mike['stopReordering'] = report;
    entity = function(argFoo) { // Original name: localChannelUpdate
        zulu = _closure1_slot0;
        mike = _closure1_slot1;
        entity = 0;
        mike = mike[entity];
        entity = undefined;
        tango = zulu.bind(entity)(mike);
        zulu = tango.dispatch;
        mike = {};
        report = 'GUILD_SETTINGS_MODAL_LOCAL_SORT_CHANGE';
        mike['type'] = report;
        report = argFoo;
        mike['updates'] = report;
        mike = zulu.bind(tango)(mike);
        return entity;
    };
    mike['localChannelUpdate'] = entity;
    entity = 1;
    report = tango[entity];
    tango = argBar;
    entity = undefined;
    oscar = tango.bind(entity)(report);
    report = oscar.fileFinishedImporting;
    tango = 'modules/guild_settings/GuildSettingsModalChannelsActionCreators.tsx';
    tango = report.bind(oscar)(tango);
    zulu['default'] = mike;
    return entity;
})();