// app/modules/guild_settings/HighlightedSettingsTypes.tsx
export default (function(_, argBar, __, ___, ____, argFred, argPlugh) {
    zulu = argFred;
    entity = global;
    report = entity.Object;
    tango = report.defineProperty;
    mike = {};
    entity = true;
    mike['value'] = entity;
    entity = '__esModule';
    entity = tango.bind(report)(zulu, entity, mike);
    mike = {};
    entity = 'accent';
    mike['ACCENT'] = entity;
    entity = 'statusGreen';
    mike['GREEN'] = entity;
    entity = 'statusYellow';
    mike['YELLOW'] = entity;
    entity = 'statusOrange';
    mike['ORANGE'] = entity;
    entity = 'statusRed';
    mike['RED'] = entity;
    entity = 'transparent';
    mike['NONE'] = entity;
    tango = argPlugh;
    entity = 0;
    report = tango[entity];
    tango = argBar;
    entity = undefined;
    oscar = tango.bind(entity)(report);
    report = oscar.fileFinishedImporting;
    tango = 'modules/guild_settings/HighlightedSettingsTypes.tsx';
    tango = report.bind(oscar)(tango);
    zulu['HighlightColors'] = mike;
    return entity;
})();