// app/modules/premium/native/gifting/PremiumGiftPlanSelect.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var7 = metroImportDefault;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var7;
    var _closure1_slot2 = var6;
    var1 = global;
    var9 = var1.Object;
    var8 = var9.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var8.bind(var9)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var7.bind(var1)(var4);
    var _closure1_slot3 = var4;
    var4 = 1;
    var4 = var6[var4];
    var4 = var7.bind(var1)(var4);
    var _closure1_slot4 = var4;
    var4 = 2;
    var8 = var6[var4];
    var4 = metroImportAll;
    var4 = var4.bind(var1)(var8);
    var _closure1_slot5 = var4;
    var4 = 3;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var8 = var4.Pressable;
    var _closure1_slot6 = var8;
    var8 = var4.View;
    var _closure1_slot7 = var8;
    var4 = var4.ScrollView;
    var _closure1_slot8 = var4;
    var4 = 4;
    var4 = var6[var4];
    var4 = var7.bind(var1)(var4);
    var _closure1_slot9 = var4;
    var4 = 5;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var7 = var4.PremiumTypes;
    var4 = 6;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.VerticalGradient;
    var _closure1_slot10 = var4;
    var4 = 7;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var8 = var4.jsx;
    var _closure1_slot11 = var8;
    var8 = var4.Fragment;
    var _closure1_slot12 = var8;
    var4 = var4.jsxs;
    var _closure1_slot13 = var4;
    var8 = var7.TIER_2;
    var4 = new Array(2);
    var4[0] = var8;
    var7 = var7.TIER_0;
    var4[1] = var7;
    var _closure1_slot14 = var4;
    var4 = 8;
    var4 = var6[var4];
    var8 = var5.bind(var1)(var4);
    var7 = var8.createStyles;
    var4 = function(arg1, arg2) {
        var7 = arg1;
        var9 = arg2;
        var1 = {};
        var2 = {};
        var3 = 1;
        var2['flex'] = var3;
        var5 = _closure1_slot1;
        var6 = _closure1_slot2;
        var3 = 9;
        var8 = var6[var3];
        var4 = undefined;
        var8 = var5.bind(var4)(var8);
        var8 = var8.colors;
        var8 = var8.BACKGROUND_BASE_LOW;
        var2['backgroundColor'] = var8;
        var1['container'] = var2;
        var2 = {};
        var10 = 'absolute';
        var2['position'] = var10;
        var2['width'] = var7;
        var11 = 0.1;
        var8 = var11 * var9;
        var2['height'] = var8;
        var8 = 1.75;
        var12 = var9 / var8;
        var11 = var11 * var9;
        var11 = var12 - var11;
        var2['top'] = var11;
        var1['headerBackground'] = var2;
        var2 = {};
        var11 = var6[var3];
        var11 = var5.bind(var4)(var11);
        var11 = var11.colors;
        var11 = var11.BACKGROUND_BASE_LOW;
        var2['color'] = var11;
        var1['headerBackgroundColor'] = var2;
        var2 = {};
        var2['position'] = var10;
        var2['width'] = var7;
        var8 = var9 / var8;
        var2['height'] = var8;
        var1['headerImageContainer'] = var2;
        var2 = {};
        var2['width'] = var7;
        var1['headerImage'] = var2;
        var2 = {};
        var2['width'] = var7;
        var7 = 10;
        var7 = var6[var7];
        var8 = var5.bind(var4)(var7);
        var7 = '#000000';
        var9 = var8.bind(var4)(var7);
        var8 = var9.alpha;
        var7 = 0.8;
        var8 = var8.bind(var9)(var7);
        var7 = var8.hex;
        var7 = var7.bind(var8)();
        var2['backgroundColor'] = var7;
        var1['headerOverlay'] = var2;
        var2 = {};
        var7 = 'center';
        var2['alignSelf'] = var7;
        var1['avatar'] = var2;
        var2 = {};
        var2['textAlign'] = var7;
        var8 = var6[var3];
        var8 = var5.bind(var4)(var8);
        var8 = var8.spacing;
        var8 = var8.PX_12;
        var2['marginTop'] = var8;
        var8 = var6[var3];
        var8 = var5.bind(var4)(var8);
        var8 = var8.spacing;
        var8 = var8.PX_24;
        var2['marginHorizontal'] = var8;
        var1['title'] = var2;
        var2 = {};
        var2['textAlign'] = var7;
        var7 = var6[var3];
        var7 = var5.bind(var4)(var7);
        var7 = var7.spacing;
        var7 = var7.PX_12;
        var2['marginTop'] = var7;
        var7 = var6[var3];
        var7 = var5.bind(var4)(var7);
        var7 = var7.spacing;
        var7 = var7.PX_24;
        var2['marginHorizontal'] = var7;
        var1['description'] = var2;
        var2 = {};
        var7 = var6[var3];
        var7 = var5.bind(var4)(var7);
        var7 = var7.spacing;
        var7 = var7.PX_32;
        var2['marginTop'] = var7;
        var1['carousel'] = var2;
        var2 = {};
        var7 = 0;
        var2['marginBottom'] = var7;
        var1['pagination'] = var2;
        var2 = {};
        var7 = var6[var3];
        var7 = var5.bind(var4)(var7);
        var7 = var7.spacing;
        var7 = var7.PX_16;
        var2['paddingTop'] = var7;
        var1['dmGiftingContent'] = var2;
        var2 = {'position': 'absolute', 'top': 0, 'left': 0, 'zIndex': 1};
        var1['closeButtonContainer'] = var2;
        var2 = {};
        var3 = var6[var3];
        var3 = var5.bind(var4)(var3);
        var3 = var3.spacing;
        var3 = var3.PX_16;
        var2['padding'] = var3;
        var1['closeButton'] = var2;
        var2 = {'width': 24, 'height': 24, 'tintColor': 'white'};
        var1['closeButtonIcon'] = var2;
        return var1;
    };
    var4 = var7.bind(var8)(var4);
    var _closure1_slot15 = var4;
    var4 = {};
    var7 = 'function PremiumGiftPlanSelectTsx1(){const{STANDARD_EASING,withTiming,carouselVisibility}=this.__closure;const animationSettings={easing:STANDARD_EASING,duration:500};return{opacity:withTiming(carouselVisibility.get()?1:0,animationSettings),transform:[{translateY:withTiming(carouselVisibility.get()?0:100,animationSettings)}]};}';
    var4['code'] = var7;
    var _closure1_slot16 = var4;
    var4 = 36;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/premium/native/gifting/PremiumGiftPlanSelect.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function PremiumGiftPlanSelect(arg1) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var1 = arg1;
            var1 = var1.shouldUseDMWishlistGiftingDesign;
            var15 = _closure1_slot0;
            var26 = _closure1_slot2;
            var2 = 11;
            var2 = var26[var2];
            var5 = undefined;
            var3 = var15.bind(var5)(var2);
            var2 = var3.useNavigation;
            var30 = var2.bind(var3)();
            var _closure2_slot0 = var30;
            var3 = _closure1_slot1;
            var2 = 12;
            var2 = var26[var2];
            var2 = var3.bind(var5)(var2);
            var2 = var2.bind(var5)();
            var28 = var2.top;
            var2 = 13;
            var2 = var26[var2];
            var2 = var3.bind(var5)(var2);
            var2 = var2.bind(var5)();
            var24 = var2.width;
            var _closure2_slot1 = var24;
            var4 = var2.height;
            var2 = 14;
            var2 = var26[var2];
            var3 = var15.bind(var5)(var2);
            var2 = var3.useNativeGiftContext;
            var3 = var2.bind(var3)();
            var38 = var3.recipientUser;
            var29 = var3.setPremiumType;
            var _closure2_slot2 = var29;
            var10 = var3.claimableRewards;
            var _closure2_slot3 = var10;
            var8 = var3.recipientUserId;
            var _closure2_slot4 = var8;
            var12 = var3.planInterval;
            var _closure2_slot5 = var12;
            var2 = var3.setOrder;
            var _closure2_slot6 = var2;
            var13 = var3.onClose;
            var _closure2_slot7 = var13;
            var3 = 15;
            var3 = var26[var3];
            var7 = var15.bind(var5)(var3);
            var6 = var7.useNavigatorBackPressHandler;
            var3 = function() {
                var2 = _closure2_slot7;
                var1 = undefined;
                var1 = var2.bind(var1)();
                var1 = true;
                return var1;
            };
            var3 = var6.bind(var7)(var3);
            var3 = 16;
            var3 = var26[var3];
            var9 = var15.bind(var5)(var3);
            var7 = var9.useStateFromStores;
            var3 = _closure1_slot9;
            var6 = new Array(1);
            var6[0] = var3;
            var3 = function() {
                var2 = _closure1_slot9;
                var1 = var2.getGiftPromotionRewardSkuIds;
                var1 = var1.bind(var2)();
                return var1;
            };
            var9 = var7.bind(var9)(var6, var3);
            var3 = 17;
            var3 = var26[var3];
            var7 = var15.bind(var5)(var3);
            var6 = var7.useCreateOrReuseGiftOrder;
            var3 = 'PremiumGiftPlanSelect';
            var14 = var6.bind(var7)(var3);
            var _closure2_slot8 = var14;
            var3 = _closure1_slot15;
            var17 = var3.bind(var5)(var24, var4);
            var _closure2_slot9 = var17;
            var7 = _closure1_slot5;
            var3 = var7.useState;
            var11 = 0;
            var3 = var3.bind(var7)(var11);
            var25 = _closure1_slot4;
            var23 = 2;
            var3 = var25.bind(var5)(var3, var23);
            var18 = var3[var11];
            var _closure2_slot10 = var18;
            var4 = 1;
            var16 = var3[var4];
            var3 = var7.useState;
            var20 = false;
            var3 = var3.bind(var7)(var20);
            var3 = var25.bind(var5)(var3, var23);
            var6 = var3[var11];
            var3 = var3[var4];
            var _closure2_slot11 = var3;
            var27 = var7.useEffect;
            var22 = new Array(1);
            var22[0] = var30;
            var3 = function() {
                var5 = _closure2_slot0;
                var4 = var5.addListener;
                var3 = 'state';
                var2 = function() {
                    var3 = _closure2_slot0;
                    var1 = var3.getState;
                    var1 = var1.bind(var3)();
                    var3 = var1.routes;
                    var1 = var1.index;
                    var1 = var3[var1];
                    var3 = _closure2_slot11;
                    var4 = var1.name;
                    var5 = _closure1_slot0;
                    var2 = _closure1_slot2;
                    var1 = 18;
                    var2 = var2[var1];
                    var1 = undefined;
                    var2 = var5.bind(var1)(var2);
                    var2 = var2.PremiumGiftScreens;
                    var2 = var2.PLAN_SELECT;
                    var2 = var4 === var2;
                    var2 = var3.bind(var1)(var2);
                    return var1;
                };
                var2 = var4.bind(var5)(var3, var2);
                var _closure3_slot0 = var2;
                var1 = function() {
                    var4 = _closure2_slot0;
                    var3 = var4.removeListener;
                    var2 = _closure3_slot0;
                    var1 = 'state';
                    var1 = var3.bind(var4)(var1, var2);
                    var1 = undefined;
                    return var1;
                };
                return var1;
            };
            var3 = var27.bind(var7)(var3, var22);
            var3 = var7.useState;
            var22 = null;
            var3 = var3.bind(var7)(var22);
            var3 = var25.bind(var5)(var3, var23);
            var23 = var3[var11];
            var _closure2_slot12 = var23;
            var3 = var3[var4];
            var _closure2_slot13 = var3;
            var25 = var7.useRef;
            var4 = new Array(0);
            var27 = var25.bind(var7)(var4);
            var _closure2_slot14 = var27;
            var25 = var7.useCallback;
            var4 = new Array(1);
            var4[0] = var3;
            var3 = function() {
                _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
case 0:
                    var2 = _closure2_slot14;
                    var2 = var2.current;
                    var3 = var2.length;
                    var2 = _closure1_slot14;
                    var2 = var2.length;
                    if(!(var3 >= var2)) { _fun0002_ip = 2; continue _fun0002 }
case 3:
                    var2 = global;
                    var5 = var2.Math;
                    var4 = var5.max;
                    var3 = _closure2_slot14;
                    var9 = var3.current;
                    var3 = new Array(0);
                    var8 = 0;
                    var10 = var3;
                    var6 = arraySpread(var10, var9, var8);
                    var10 = var4;
                    var9 = var3;
                    var8 = var5;
                    var3 = apply(var10, var9, var8);
                    var4 = var2.Number;
                    var2 = var4.isNaN;
                    var2 = var2.bind(var4)(var3);
                    if(var2) { _fun0002_ip = 2; continue _fun0002 }
case 4:
                    var2 = _closure2_slot13;
                    var1 = undefined;
                    var1 = var2.bind(var1)(var3);
case 2:
                    var1 = undefined;
                    return var1;
                }
            };
            var25 = var25.bind(var7)(var3, var4);
            var _closure2_slot15 = var25;
            var4 = var7.useCallback;
            var3 = new Array(12);
            var3[0] = var30;
            var3[1] = var24;
            var3[2] = var29;
            var3[3] = var27;
            var3[4] = var25;
            var3[5] = var23;
            var3[6] = var18;
            var3[7] = var10;
            var3[8] = var14;
            var3[9] = var12;
            var3[10] = var8;
            var3[11] = var2;
            var2 = function(arg1) {
                _fun0003: for(var _fun0003_ip = 0; ; ) switch(_fun0003_ip) {
case 0:
                    var1 = arg1;
                    var11 = var1.item;
                    var _closure3_slot0 = var11;
                    var7 = var1.index;
                    var _closure3_slot1 = var7;
                    var4 = _closure1_slot11;
                    var3 = _closure1_slot7;
                    var2 = {};
                    var1 = _closure2_slot10;
                    var1 = var1 !== var7;
                    var2['aria-hidden'] = var1;
                    var6 = _closure1_slot1;
                    var5 = _closure1_slot2;
                    var1 = 19;
                    var5 = var5[var1];
                    var1 = undefined;
                    var6 = var6.bind(var1)(var5);
                    var5 = {};
                    var5['premiumType'] = var11;
                    var11 = _closure1_slot3;
                    var10 = function* () {
                        var1 = function* anon_0_() {
                            _fun0004: for(var _fun0004_ip = 0; ; ) switch(_fun0004_ip) {
case 0:
                                StartGenerator();
                                ResumeGenerator(result_out_reg=0, return_bool_out_reg=1);
                                if(var2) { _fun0004_ip = 5; continue _fun0004 }
case 6:
                                var9 = undefined;
                                var4 = undefined;
                                var7 = undefined;
                                var2 = _closure2_slot2;
                                var10 = _closure3_slot0;
                                var2 = var2.bind(var9)(var10);
                                var6 = _closure1_slot0;
                                var8 = _closure1_slot2;
                                var2 = 20;
                                var2 = var8[var2];
                                var8 = var6.bind(var9)(var2);
                                var6 = var8.getPlanIdForPremiumType;
                                var2 = _closure2_slot5;
                                var7 = var6.bind(var8)(var10, var2);
case 7: // try_start_0
                                var6 = _closure2_slot8;
                                var2 = {};
                                var2['planId'] = var7;
                                var7 = _closure2_slot4;
                                var2['recipientUserId'] = var7;
                                var2 = var6.bind(var9)(var2);
                                SaveGenerator(address=103);
case 4:
                                return var2;
case 8:
                                ResumeGenerator(result_out_reg=1, return_bool_out_reg=5);
                                if(var6) { _fun0004_ip = 9; continue _fun0004 }
case 10:
                                var4 = var2;
case 2: // try_end0
                                var6 = _closure2_slot6;
                                var4 = var6.bind(var9)(var4);
                                var6 = _closure2_slot0;
                                var4 = var6.navigate;
                                var7 = _closure1_slot0;
                                var8 = _closure1_slot2;
                                var3 = 18;
                                var3 = var8[var3];
                                var3 = var7.bind(var9)(var3);
                                var3 = var3.PremiumGiftScreens;
                                var3 = var3.CUSTOMIZATION;
                                var3 = var4.bind(var6)(var3);
                                return var9;
case 9:
                                return var2;
case 11: // catch_target0
                                CatchBlockStart(arg_register=1);
                                var3 = _closure1_slot1;
                                var10 = _closure1_slot2;
                                var2 = 21;
                                var2 = var10[var2];
                                var4 = var3.bind(var9)(var2);
                                var3 = var4.show;
                                var2 = {};
                                var8 = _closure1_slot0;
                                var5 = 22;
                                var6 = var10[var5];
                                var6 = var8.bind(var9)(var6);
                                var11 = var6.intl;
                                var7 = var11.string;
                                var6 = var10[var5];
                                var6 = var8.bind(var9)(var6);
                                var6 = var6.t;
                                var6 = var6.R0RpRX;
                                var6 = var7.bind(var11)(var6);
                                var2['title'] = var6;
                                var6 = var10[var5];
                                var6 = var8.bind(var9)(var6);
                                var7 = var6.intl;
                                var6 = var7.string;
                                var5 = var10[var5];
                                var5 = var8.bind(var9)(var5);
                                var5 = var5.t;
                                var5 = var5.CKsXk3;
                                var5 = var6.bind(var7)(var5);
                                var2['body'] = var5;
                                var2 = var3.bind(var4)(var2);
                                var2 = undefined;
                                return var2;
case 5:
                                return var1;
                            }
                        };
                        return var1;
                    };
                    var10 = var11.bind(var1)(var10);
                    var5['onPress'] = var10;
                    var10 = {};
                    var12 = _closure2_slot12;
                    var11 = null;
                    var12 = var11 != var12;
                    var11 = undefined;
                    if(!var12) { _fun0003_ip = 12; continue _fun0003 }
case 13:
                    var11 = _closure2_slot12;
case 12:
                    var10['height'] = var11;
                    var11 = 'center';
                    var10['alignSelf'] = var11;
                    var12 = _closure2_slot1;
                    var11 = 0.86;
                    var11 = var11 * var12;
                    var10['width'] = var11;
                    var5['style'] = var10;
                    var9 = function onLayout(arg1) {
                        _fun0005: for(var _fun0005_ip = 0; ; ) switch(_fun0005_ip) {
case 0:
                            var1 = arg1;
                            var1 = var1.nativeEvent;
                            var1 = var1.layout;
                            var7 = var1.height;
                            var6 = 0;
                            if(!(var7 > var6)) { _fun0005_ip = 4; continue _fun0005 }
case 14:
                            var8 = _closure2_slot14;
                            var4 = var8.current;
                            var3 = _closure3_slot1;
                            var2 = global;
                            var5 = var2.Math;
                            var2 = var5.max;
                            var8 = var8.current;
                            var8 = var8[var3];
                            var9 = null;
                            var9 = var9 != var8;
                            var6 = 0;
                            if(!var9) { _fun0005_ip = 15; continue _fun0005 }
case 16:
                            var6 = var8;
case 15:
                            var2 = var2.bind(var5)(var7, var6);
                            var4[var3] = var2;
                            var2 = _closure2_slot15;
                            var1 = undefined;
                            var1 = var2.bind(var1)();
case 4:
                            var1 = undefined;
                            return var1;
                        }
                    };
                    var5['onLayout'] = var9;
                    var9 = _closure2_slot3;
                    var5['claimableRewards'] = var9;
                    var8 = _closure2_slot10;
                    var8 = var8 === var7;
                    var5['isSelected'] = var8;
                    var5 = var4.bind(var1)(var6, var5, var7);
                    var2['children'] = var5;
                    var1 = var4.bind(var1)(var3, var2);
                    return var1;
                }
            };
            var25 = var4.bind(var7)(var2, var3);
            var2 = 23;
            var3 = var26[var2];
            var4 = var15.bind(var5)(var3);
            var3 = var4.useSharedValue;
            var12 = var3.bind(var4)(var20);
            var _closure2_slot16 = var12;
            var8 = var7.useEffect;
            var4 = new Array(2);
            var4[0] = var12;
            var4[1] = var23;
            var3 = function() {
                var3 = _closure2_slot16;
                var2 = var3.set;
                var4 = _closure2_slot12;
                var1 = null;
                var1 = var1 != var4;
                var1 = var2.bind(var3)(var1);
                var1 = undefined;
                return var1;
            };
            var3 = var8.bind(var7)(var3, var4);
            var2 = var26[var2];
            var4 = var15.bind(var5)(var2);
            var3 = var4.useAnimatedStyle;
            var2 = function ee() {
                _fun0006: for(var _fun0006_ip = 0; ; ) switch(_fun0006_ip) {
case 0:
                    var6 = {};
                    var3 = _closure1_slot0;
                    var2 = _closure1_slot2;
                    var1 = 24;
                    var1 = var2[var1];
                    var8 = undefined;
                    var1 = var3.bind(var8)(var1);
                    var1 = var1.STANDARD_EASING;
                    var6['easing'] = var1;
                    var1 = 500;
                    var6['duration'] = var1;
                    var1 = {};
                    var9 = 25;
                    var2 = var2[var9];
                    var10 = var3.bind(var8)(var2);
                    var5 = var10.withTiming;
                    var7 = _closure2_slot16;
                    var3 = var7.get;
                    var11 = var3.bind(var7)();
                    var3 = 0;
                    if(!var11) { _fun0006_ip = 17; continue _fun0006 }
case 18:
                    var3 = 1;
case 17:
                    var3 = var5.bind(var10)(var3, var6);
                    var1['opacity'] = var3;
                    var3 = {};
                    var5 = _closure1_slot0;
                    var4 = _closure1_slot2;
                    var4 = var4[var9];
                    var5 = var5.bind(var8)(var4);
                    var4 = var5.withTiming;
                    var8 = _closure2_slot16;
                    var2 = var8.get;
                    var8 = var2.bind(var8)();
                    var2 = 100;
                    if(!var8) { _fun0006_ip = 19; continue _fun0006 }
case 20:
                    var2 = 0;
case 19:
                    var2 = var4.bind(var5)(var2, var6);
                    var3['translateY'] = var2;
                    var2 = new Array(1);
                    var2[0] = var3;
                    var1['transform'] = var2;
                    return var1;
                }
            };
            var8 = {};
            var14 = 24;
            var14 = var26[var14];
            var14 = var15.bind(var5)(var14);
            var14 = var14.STANDARD_EASING;
            var8['STANDARD_EASING'] = var14;
            var14 = 25;
            var14 = var26[var14];
            var14 = var15.bind(var5)(var14);
            var14 = var14.withTiming;
            var8['withTiming'] = var14;
            var8['carouselVisibility'] = var12;
            var2['__closure'] = var8;
            var8 = 2946262965957.0;
            var2['__workletHash'] = var8;
            var8 = _closure1_slot16;
            var2['__initData'] = var8;
            var26 = var3.bind(var4)(var2);
            var4 = var7.useMemo;
            var3 = new Array(1);
            var3[0] = var17;
            var2 = function() {
                var5 = _closure1_slot1;
                var6 = _closure1_slot2;
                var3 = 10;
                var1 = var6[var3];
                var4 = undefined;
                var7 = var5.bind(var4)(var1);
                var2 = _closure2_slot9;
                var1 = var2.headerBackgroundColor;
                var1 = var1.color;
                var8 = var7.bind(var4)(var1);
                var7 = var8.alpha;
                var1 = 0;
                var7 = var7.bind(var8)(var1);
                var1 = var7.hex;
                var7 = var1.bind(var7)();
                var1 = new Array(2);
                var1[0] = var7;
                var3 = var6[var3];
                var3 = var5.bind(var4)(var3);
                var2 = var2.headerBackgroundColor;
                var2 = var2.color;
                var4 = var3.bind(var4)(var2);
                var3 = var4.alpha;
                var2 = 1;
                var3 = var3.bind(var4)(var2);
                var2 = var3.hex;
                var2 = var2.bind(var3)();
                var1[1] = var2;
                return var1;
            };
            var12 = var4.bind(var7)(var2, var3);
            if(var1) { _fun0001_ip = 21; continue _fun0001 }
case 22:
            var3 = _closure1_slot13;
            var2 = _closure1_slot12;
            var1 = {};
            if(!var6) { _fun0001_ip = 23; continue _fun0001 }
case 24:
            var8 = _closure1_slot11;
            var7 = _closure1_slot1;
            var14 = _closure1_slot2;
            var4 = 28;
            var4 = var14[var4];
            var7 = var7.bind(var5)(var4);
            var4 = {'animated': true, 'barStyle': 'light-content'};
            var6 = var8.bind(var5)(var7, var4);
case 23:
            var4 = new Array(6);
            var4[0] = var6;
            var8 = _closure1_slot11;
            var7 = _closure1_slot6;
            var6 = {};
            var15 = var17.closeButtonContainer;
            var14 = new Array(2);
            var14[0] = var15;
            var15 = {};
            var15['paddingTop'] = var28;
            var14[1] = var15;
            var6['style'] = var14;
            var6['onPress'] = var13;
            var13 = 'button';
            var6['accessibilityRole'] = var13;
            var31 = _closure1_slot0;
            var30 = _closure1_slot2;
            var34 = 22;
            var13 = var30[var34];
            var13 = var31.bind(var5)(var13);
            var15 = var13.intl;
            var14 = var15.string;
            var13 = var30[var34];
            var13 = var31.bind(var5)(var13);
            var13 = var13.t;
            var13 = var13.cpT0Cq;
            var13 = var14.bind(var15)(var13);
            var6['accessibilityLabel'] = var13;
            var14 = _closure1_slot7;
            var13 = {};
            var15 = var17.closeButton;
            var13['style'] = var15;
            var15 = 29;
            var15 = var30[var15];
            var15 = var31.bind(var5)(var15);
            var27 = var15.XSmallIcon;
            var15 = {};
            var29 = 'md';
            var15['size'] = var29;
            var29 = var17.closeButtonIcon;
            var15['style'] = var29;
            var15 = var8.bind(var5)(var27, var15);
            var13['children'] = var15;
            var13 = var8.bind(var5)(var14, var13);
            var6['children'] = var13;
            var6 = var8.bind(var5)(var7, var6);
            var4[1] = var6;
            var29 = _closure1_slot1;
            var6 = 30;
            var6 = var30[var6];
            var7 = var29.bind(var5)(var6);
            var6 = {};
            var13 = 'cover';
            var6['resizeMode'] = var13;
            var15 = var17.headerImageContainer;
            var13 = new Array(2);
            var13[0] = var15;
            var15 = var17.headerImage;
            var13[1] = var15;
            var6['style'] = var13;
            var13 = 31;
            var13 = var30[var13];
            var13 = var29.bind(var5)(var13);
            var6['source'] = var13;
            var6 = var8.bind(var5)(var7, var6);
            var4[2] = var6;
            var6 = {};
            var13 = var17.headerImageContainer;
            var7 = new Array(2);
            var7[0] = var13;
            var13 = var17.headerOverlay;
            var7[1] = var13;
            var6['style'] = var7;
            var6 = var8.bind(var5)(var14, var6);
            var4[3] = var6;
            var6 = 32;
            var6 = var30[var6];
            var7 = var29.bind(var5)(var6);
            var6 = {};
            var13 = var17.headerBackground;
            var6['style'] = var13;
            var13 = _closure1_slot10;
            var15 = var13.START;
            var6['start'] = var15;
            var13 = var13.END;
            var6['end'] = var13;
            var6['colors'] = var12;
            var6 = var8.bind(var5)(var7, var6);
            var4[4] = var6;
            var7 = _closure1_slot8;
            var6 = {};
            var13 = _closure1_slot13;
            var12 = {};
            var27 = {};
            var15 = 33;
            var15 = var30[var15];
            var15 = var31.bind(var5)(var15);
            var15 = var15.NAV_BAR_HEIGHT;
            var28 = var28 + var15;
            var15 = 9;
            var15 = var30[var15];
            var15 = var29.bind(var5)(var15);
            var15 = var15.spacing;
            var15 = var15.PX_12;
            var15 = var28 + var15;
            var27['paddingTop'] = var15;
            var15 = new Array(1);
            var15[0] = var27;
            var12['style'] = var15;
            var27 = var22 != var38;
            if(!var27) { _fun0001_ip = 25; continue _fun0001 }
case 26:
            var29 = _closure1_slot11;
            var28 = _closure1_slot1;
            var32 = _closure1_slot2;
            var30 = 34;
            var15 = var32[var30];
            var28 = var28.bind(var5)(var15);
            var15 = {};
            var31 = var17.avatar;
            var15['style'] = var31;
            var15['guildId'] = var5;
            var31 = _closure1_slot0;
            var30 = var32[var30];
            var30 = var31.bind(var5)(var30);
            var30 = var30.AvatarSizes;
            var30 = var30.XLARGE;
            var15['size'] = var30;
            var15['user'] = var38;
            var27 = var29.bind(var5)(var28, var15);
case 25:
            var15 = new Array(4);
            var15[0] = var27;
            var30 = _closure1_slot11;
            var29 = _closure1_slot0;
            var28 = _closure1_slot2;
            var27 = 35;
            var28 = var28[var27];
            var28 = var29.bind(var5)(var28);
            var29 = var28.Text;
            var28 = {'style': null, 'variant': 'heading-xxl/extrabold', 'color': 'always-white'};
            var31 = var17.title;
            var28['style'] = var31;
            if(!(var22 == var38)) { _fun0001_ip = 27; continue _fun0001 }
case 28:
            var35 = _closure1_slot0;
            var31 = _closure1_slot2;
            var32 = var31[var34];
            var32 = var35.bind(var5)(var32);
            var33 = var32.intl;
            var32 = var33.string;
            var31 = var31[var34];
            var31 = var35.bind(var5)(var31);
            var31 = var31.t;
            var31 = var31.dqQgZv;
            var31 = var32.bind(var33)(var31);
            _fun0001_ip = 29; continue _fun0001;
case 27:
            var33 = _closure1_slot0;
            var32 = _closure1_slot2;
            var35 = var32[var34];
            var35 = var33.bind(var5)(var35);
            var36 = var35.intl;
            var35 = var36.formatToPlainString;
            var32 = var32[var34];
            var32 = var33.bind(var5)(var32);
            var32 = var32.t;
            var33 = var32.m5ggvH;
            var32 = {};
            var37 = var38.globalName;
            if(!(var22 == var37)) { _fun0001_ip = 30; continue _fun0001 }
case 31:
            var37 = var38.username;
case 30:
            var32['username'] = var37;
            var31 = var35.bind(var36)(var33, var32);
case 29:
            var28['children'] = var31;
            var28 = var30.bind(var5)(var29, var28);
            var15[1] = var28;
            var29 = _closure1_slot11;
            var33 = _closure1_slot0;
            var30 = _closure1_slot2;
            var27 = var30[var27];
            var27 = var33.bind(var5)(var27);
            var28 = var27.Text;
            var27 = {'style': null, 'variant': 'heading-sm/medium', 'color': 'always-white'};
            var31 = var17.description;
            var27['style'] = var31;
            var31 = var30[var34];
            var31 = var33.bind(var5)(var31);
            var32 = var31.intl;
            var31 = var32.string;
            var30 = var30[var34];
            var30 = var33.bind(var5)(var30);
            var30 = var30.t;
            var30 = var30.30qzrd;
            var30 = var31.bind(var32)(var30);
            var27['children'] = var30;
            var27 = var29.bind(var5)(var28, var27);
            var15[2] = var27;
            var27 = var9.length;
            if(!(var11 !== var27)) { _fun0001_ip = 32; continue _fun0001 }
case 33:
            var27 = null;
            if(!(var5 !== var10)) { _fun0001_ip = 34; continue _fun0001 }
case 32:
            var30 = _closure1_slot13;
            var29 = _closure1_slot12;
            var28 = {};
            var33 = _closure1_slot11;
            var32 = _closure1_slot1;
            var34 = _closure1_slot2;
            var31 = 26;
            var31 = var34[var31];
            var32 = var32.bind(var5)(var31);
            var31 = {};
            var35 = var17.carousel;
            var34 = new Array(2);
            var34[0] = var35;
            var34[1] = var26;
            var31['style'] = var34;
            var34 = _closure1_slot14;
            var31['data'] = var34;
            var31['renderItem'] = var25;
            var31['width'] = var24;
            var35 = var22 != var23;
            var34 = undefined;
            if(!var35) { _fun0001_ip = 35; continue _fun0001 }
case 36:
            var34 = var23;
case 35:
            var31['height'] = var34;
            var34 = function onConfigurePanGesture(arg1) {
                var3 = arg1;
                var2 = var3.activeOffsetX;
                var1 = new Array(2);
                var4 = -10;
                var1[0] = var4;
                var4 = 10;
                var1[1] = var4;
                var1 = var2.bind(var3)(var1);
                var1 = undefined;
                return var1;
            };
            var31['onConfigurePanGesture'] = var34;
            var31['loop'] = var20;
            var34 = 200;
            var31['scrollAnimationDuration'] = var34;
            var34 = 'parallax';
            var31['mode'] = var34;
            var34 = {'parallaxScrollingScale': 1, 'parallaxScrollingOffset': 40};
            var31['modeConfig'] = var34;
            var31['onSnapToItem'] = var16;
            var32 = var33.bind(var5)(var32, var31);
            var31 = new Array(2);
            var31[0] = var32;
            var34 = _closure1_slot11;
            var33 = _closure1_slot1;
            var35 = _closure1_slot2;
            var32 = 27;
            var32 = var35[var32];
            var33 = var33.bind(var5)(var32);
            var32 = {};
            var35 = _closure1_slot14;
            var35 = var35.length;
            var32['numberOfItems'] = var35;
            var32['currentIndex'] = var18;
            var35 = var17.pagination;
            var32['containerStyle'] = var35;
            var32 = var34.bind(var5)(var33, var32);
            var31[1] = var32;
            var28['children'] = var31;
            var27 = var30.bind(var5)(var29, var28);
case 34:
            var15[3] = var27;
            var12['children'] = var15;
            var12 = var13.bind(var5)(var14, var12);
            var6['children'] = var12;
            var6 = var8.bind(var5)(var7, var6);
            var4[5] = var6;
            var1['children'] = var4;
            var1 = var3.bind(var5)(var2, var1);
            _fun0001_ip = 37; continue _fun0001;
case 21:
            var4 = _closure1_slot11;
            var3 = _closure1_slot7;
            var2 = {};
            var6 = var17.container;
            var2['style'] = var6;
            var7 = _closure1_slot8;
            var6 = {};
            var8 = {};
            var12 = var17.dmGiftingContent;
            var8['style'] = var12;
            var9 = var9.length;
            if(!(var11 !== var9)) { _fun0001_ip = 38; continue _fun0001 }
case 39:
            var9 = null;
            if(!(var5 !== var10)) { _fun0001_ip = 40; continue _fun0001 }
case 38:
            var12 = _closure1_slot13;
            var11 = _closure1_slot12;
            var10 = {};
            var15 = _closure1_slot11;
            var14 = _closure1_slot1;
            var27 = _closure1_slot2;
            var13 = 26;
            var13 = var27[var13];
            var14 = var14.bind(var5)(var13);
            var13 = {};
            var13['style'] = var26;
            var26 = _closure1_slot14;
            var13['data'] = var26;
            var13['renderItem'] = var25;
            var13['width'] = var24;
            var24 = var22 != var23;
            var22 = undefined;
            if(!var24) { _fun0001_ip = 41; continue _fun0001 }
case 42:
            var22 = var23;
case 41:
            var13['height'] = var22;
            var21 = function onConfigurePanGesture(arg1) {
                var3 = arg1;
                var2 = var3.activeOffsetX;
                var1 = new Array(2);
                var4 = -10;
                var1[0] = var4;
                var4 = 10;
                var1[1] = var4;
                var1 = var2.bind(var3)(var1);
                var1 = undefined;
                return var1;
            };
            var13['onConfigurePanGesture'] = var21;
            var13['loop'] = var20;
            var20 = 200;
            var13['scrollAnimationDuration'] = var20;
            var20 = 'parallax';
            var13['mode'] = var20;
            var20 = {'parallaxScrollingScale': 1, 'parallaxScrollingOffset': 40};
            var13['modeConfig'] = var20;
            var13['onSnapToItem'] = var16;
            var14 = var15.bind(var5)(var14, var13);
            var13 = new Array(2);
            var13[0] = var14;
            var16 = _closure1_slot11;
            var15 = _closure1_slot1;
            var20 = _closure1_slot2;
            var14 = 27;
            var14 = var20[var14];
            var15 = var15.bind(var5)(var14);
            var14 = {};
            var19 = _closure1_slot14;
            var19 = var19.length;
            var14['numberOfItems'] = var19;
            var14['currentIndex'] = var18;
            var17 = var17.pagination;
            var14['containerStyle'] = var17;
            var14 = var16.bind(var5)(var15, var14);
            var13[1] = var14;
            var10['children'] = var13;
            var9 = var12.bind(var5)(var11, var10);
case 40:
            var8['children'] = var9;
            var8 = var4.bind(var5)(var3, var8);
            var6['children'] = var8;
            var6 = var4.bind(var5)(var7, var6);
            var2['children'] = var6;
            var1 = var4.bind(var5)(var3, var2);
case 37:
            return var1;
        }
    };
    var3['default'] = var2;
    return var1;
})();