// app/modules/auth/native/RegistrationUIStore.tsx
export default (function(argFoo, argBar, _, __, ___, argFred, argPlugh) {
    oscar = argBar;
    zulu = argFred;
    golf = argPlugh;
    var _closure1_slot0 = oscar;
    var _closure1_slot1 = golf;
    entity = global;
    options = entity.Object;
    report = options.defineProperty;
    tango = {};
    entity = true;
    tango['value'] = entity;
    entity = '__esModule';
    entity = report.bind(options)(zulu, entity, tango);
    entity = 0;
    tango = golf[entity];
    entity = undefined;
    options = oscar.bind(entity)(tango);
    report = options.create;
    tango = function() {
        entity = {};
        mike = {};
        entity['errors'] = mike;
        mike = {};
        entity['registrationOptions'] = mike;
        return entity;
    };
    tango = report.bind(options)(tango);
    var _closure1_slot2 = tango;
    report = 2;
    report = golf[report];
    golf = oscar.bind(entity)(report);
    oscar = golf.fileFinishedImporting;
    report = 'modules/auth/native/RegistrationUIStore.tsx';
    report = oscar.bind(golf)(report);
    zulu['useRegistrationUIStore'] = tango;
    tango = function(argFoo) { // Original name: setRegistrationErrors
        entity = argFoo;
        var _closure2_slot0 = entity;
        tango = _closure1_slot0;
        zulu = _closure1_slot1;
        entity = 1;
        zulu = zulu[entity];
        entity = undefined;
        tango = tango.bind(entity)(zulu);
        zulu = tango.batchUpdates;
        mike = function() {
            zulu = _closure1_slot2;
            mike = zulu.setState;
            entity = {};
            tango = _closure2_slot0;
            entity['errors'] = tango;
            entity = mike.bind(zulu)(entity);
            entity = undefined;
            return entity;
        };
        mike = zulu.bind(tango)(mike);
        return entity;
    };
    zulu['setRegistrationErrors'] = tango;
    tango = function(argFoo) { // Original name: updateRegistrationOptions
        entity = argFoo;
        var _closure2_slot0 = entity;
        tango = _closure1_slot2;
        zulu = tango.getState;
        zulu = zulu.bind(tango)();
        zulu = zulu.registrationOptions;
        var _closure2_slot1 = zulu;
        tango = _closure1_slot0;
        zulu = _closure1_slot1;
        entity = 1;
        zulu = zulu[entity];
        entity = undefined;
        tango = tango.bind(entity)(zulu);
        zulu = tango.batchUpdates;
        mike = function() {
            zulu = _closure1_slot2;
            mike = zulu.setState;
            entity = {};
            tango = {};
            golf = _closure2_slot1;
            options = tango;
            oscar = copyDataProperties(options, golf);
            golf = _closure2_slot0;
            options = tango;
            report = copyDataProperties(options, golf);
            entity['registrationOptions'] = tango;
            entity = mike.bind(zulu)(entity);
            entity = undefined;
            return entity;
        };
        mike = zulu.bind(tango)(mike);
        return entity;
    };
    zulu['updateRegistrationOptions'] = tango;
    mike = function() { // Original name: resetRegistration
        zulu = _closure1_slot0;
        mike = _closure1_slot1;
        entity = 1;
        mike = mike[entity];
        entity = undefined;
        tango = zulu.bind(entity)(mike);
        zulu = tango.batchUpdates;
        mike = function() {
            zulu = _closure1_slot2;
            mike = zulu.setState;
            entity = {};
            tango = {};
            entity['errors'] = tango;
            tango = {};
            entity['registrationOptions'] = tango;
            entity = mike.bind(zulu)(entity);
            entity = undefined;
            return entity;
        };
        mike = zulu.bind(tango)(mike);
        return entity;
    };
    zulu['resetRegistration'] = mike;
    return entity;
})();