// app/modules/game_profile/native/utils/getGameProfileWebsiteData.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var1 = metroImportDefault;
    var _closure1_slot1 = var1;
    var _closure1_slot2 = var6;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var5.bind(var1)(var4);
    var4 = var4.jsx;
    var _closure1_slot3 = var4;
    var4 = 13;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/game_profile/native/utils/getGameProfileWebsiteData.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function getGameProfileWebsiteData(arg1) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var2 = arg1;
            var4 = var2.category;
            var5 = _closure1_slot0;
            var1 = _closure1_slot2;
            var6 = 1;
            var1 = var1[var6];
            var7 = undefined;
            var1 = var5.bind(var7)(var1);
            var1 = var1.ThirdPartyGameApplicationWebsiteCategory;
            var1 = var1.OFFICIAL;
            if(!(var1 !== var4)) { _fun0001_ip = 2; continue _fun0001 }
case 3:
            var5 = _closure1_slot0;
            var1 = _closure1_slot2;
            var1 = var1[var6];
            var1 = var5.bind(var7)(var1);
            var1 = var1.ThirdPartyGameApplicationWebsiteCategory;
            var1 = var1.TWITTER;
            if(!(var1 !== var4)) { _fun0001_ip = 4; continue _fun0001 }
case 5:
            var5 = _closure1_slot0;
            var1 = _closure1_slot2;
            var1 = var1[var6];
            var1 = var5.bind(var7)(var1);
            var1 = var1.ThirdPartyGameApplicationWebsiteCategory;
            var1 = var1.YOUTUBE;
            if(!(var1 !== var4)) { _fun0001_ip = 6; continue _fun0001 }
case 7:
            var5 = _closure1_slot0;
            var1 = _closure1_slot2;
            var1 = var1[var6];
            var1 = var5.bind(var7)(var1);
            var1 = var1.ThirdPartyGameApplicationWebsiteCategory;
            var1 = var1.FACEBOOK;
            if(!(var1 !== var4)) { _fun0001_ip = 8; continue _fun0001 }
case 9:
            var5 = _closure1_slot0;
            var1 = _closure1_slot2;
            var1 = var1[var6];
            var1 = var5.bind(var7)(var1);
            var1 = var1.ThirdPartyGameApplicationWebsiteCategory;
            var1 = var1.INSTAGRAM;
            if(!(var1 !== var4)) { _fun0001_ip = 10; continue _fun0001 }
case 11:
            var5 = _closure1_slot0;
            var1 = _closure1_slot2;
            var1 = var1[var6];
            var1 = var5.bind(var7)(var1);
            var1 = var1.ThirdPartyGameApplicationWebsiteCategory;
            var1 = var1.BLUESKY;
            if(!(var1 !== var4)) { _fun0001_ip = 12; continue _fun0001 }
case 13:
            var5 = _closure1_slot0;
            var1 = _closure1_slot2;
            var1 = var1[var6];
            var1 = var5.bind(var7)(var1);
            var1 = var1.ThirdPartyGameApplicationWebsiteCategory;
            var1 = var1.REDDIT;
            if(!(var1 !== var4)) { _fun0001_ip = 14; continue _fun0001 }
case 15:
            var5 = _closure1_slot0;
            var1 = _closure1_slot2;
            var1 = var1[var6];
            var1 = var5.bind(var7)(var1);
            var1 = var1.ThirdPartyGameApplicationWebsiteCategory;
            var1 = var1.TWITCH;
            if(!(var1 !== var4)) { _fun0001_ip = 16; continue _fun0001 }
case 17:
            var1 = null;
            return var1;
case 16:
            var1 = {};
            var6 = _closure1_slot3;
            var8 = _closure1_slot0;
            var9 = _closure1_slot2;
            var4 = 12;
            var4 = var9[var4];
            var4 = var8.bind(var7)(var4);
            var5 = var4.TwitchNeutralIcon;
            var4 = {};
            var10 = 'md';
            var4['size'] = var10;
            var4 = var6.bind(var7)(var5, var4);
            var1['icon'] = var4;
            var4 = 3;
            var4 = var9[var4];
            var4 = var8.bind(var7)(var4);
            var4 = var4.GameProfileTrackActionActions;
            var4 = var4.TwitchLink;
            var1['action'] = var4;
            var4 = 4;
            var5 = var9[var4];
            var5 = var8.bind(var7)(var5);
            var6 = var5.intl;
            var5 = var6.string;
            var4 = var9[var4];
            var4 = var8.bind(var7)(var4);
            var4 = var4.t;
            var4 = var4.7xtz4G;
            var4 = var5.bind(var6)(var4);
            var1['title'] = var4;
            var4 = var2.url;
            var1['url'] = var4;
            return var1;
case 14:
            var1 = {};
            var6 = _closure1_slot3;
            var8 = _closure1_slot0;
            var9 = _closure1_slot2;
            var4 = 11;
            var4 = var9[var4];
            var4 = var8.bind(var7)(var4);
            var5 = var4.RedditNeutralIcon;
            var4 = {};
            var10 = 'md';
            var4['size'] = var10;
            var4 = var6.bind(var7)(var5, var4);
            var1['icon'] = var4;
            var4 = 3;
            var4 = var9[var4];
            var4 = var8.bind(var7)(var4);
            var4 = var4.GameProfileTrackActionActions;
            var4 = var4.RedditLink;
            var1['action'] = var4;
            var4 = 4;
            var5 = var9[var4];
            var5 = var8.bind(var7)(var5);
            var6 = var5.intl;
            var5 = var6.string;
            var4 = var9[var4];
            var4 = var8.bind(var7)(var4);
            var4 = var4.t;
            var4 = var4.Hgb+fc;
            var4 = var5.bind(var6)(var4);
            var1['title'] = var4;
            var4 = var2.url;
            var1['url'] = var4;
            return var1;
case 12:
            var1 = {};
            var6 = _closure1_slot3;
            var8 = _closure1_slot0;
            var9 = _closure1_slot2;
            var4 = 10;
            var4 = var9[var4];
            var4 = var8.bind(var7)(var4);
            var5 = var4.BlueskyNeutralIcon;
            var4 = {};
            var10 = 'md';
            var4['size'] = var10;
            var4 = var6.bind(var7)(var5, var4);
            var1['icon'] = var4;
            var4 = 3;
            var4 = var9[var4];
            var4 = var8.bind(var7)(var4);
            var4 = var4.GameProfileTrackActionActions;
            var4 = var4.BlueskyLink;
            var1['action'] = var4;
            var4 = 4;
            var5 = var9[var4];
            var5 = var8.bind(var7)(var5);
            var6 = var5.intl;
            var5 = var6.string;
            var4 = var9[var4];
            var4 = var8.bind(var7)(var4);
            var4 = var4.t;
            var4 = var4.D/PHq5;
            var4 = var5.bind(var6)(var4);
            var1['title'] = var4;
            var4 = var2.url;
            var1['url'] = var4;
            return var1;
case 10:
            var1 = {};
            var6 = _closure1_slot3;
            var8 = _closure1_slot0;
            var9 = _closure1_slot2;
            var4 = 9;
            var4 = var9[var4];
            var4 = var8.bind(var7)(var4);
            var5 = var4.InstagramNeutralIcon;
            var4 = {};
            var10 = 'md';
            var4['size'] = var10;
            var4 = var6.bind(var7)(var5, var4);
            var1['icon'] = var4;
            var4 = 3;
            var4 = var9[var4];
            var4 = var8.bind(var7)(var4);
            var4 = var4.GameProfileTrackActionActions;
            var4 = var4.InstagramLink;
            var1['action'] = var4;
            var4 = 4;
            var5 = var9[var4];
            var5 = var8.bind(var7)(var5);
            var6 = var5.intl;
            var5 = var6.string;
            var4 = var9[var4];
            var4 = var8.bind(var7)(var4);
            var4 = var4.t;
            var4 = var4.cgR+IK;
            var4 = var5.bind(var6)(var4);
            var1['title'] = var4;
            var4 = var2.url;
            var1['url'] = var4;
            return var1;
case 8:
            var1 = {};
            var6 = _closure1_slot3;
            var8 = _closure1_slot0;
            var9 = _closure1_slot2;
            var4 = 8;
            var4 = var9[var4];
            var4 = var8.bind(var7)(var4);
            var5 = var4.FacebookNeutralIcon;
            var4 = {};
            var10 = 'md';
            var4['size'] = var10;
            var4 = var6.bind(var7)(var5, var4);
            var1['icon'] = var4;
            var4 = 3;
            var4 = var9[var4];
            var4 = var8.bind(var7)(var4);
            var4 = var4.GameProfileTrackActionActions;
            var4 = var4.FacebookLink;
            var1['action'] = var4;
            var4 = 4;
            var5 = var9[var4];
            var5 = var8.bind(var7)(var5);
            var6 = var5.intl;
            var5 = var6.string;
            var4 = var9[var4];
            var4 = var8.bind(var7)(var4);
            var4 = var4.t;
            var4 = var4.FjyREK;
            var4 = var5.bind(var6)(var4);
            var1['title'] = var4;
            var4 = var2.url;
            var1['url'] = var4;
            return var1;
case 6:
            var1 = {};
            var6 = _closure1_slot3;
            var8 = _closure1_slot0;
            var9 = _closure1_slot2;
            var4 = 7;
            var4 = var9[var4];
            var4 = var8.bind(var7)(var4);
            var5 = var4.YoutubeNeutralIcon;
            var4 = {};
            var10 = 'md';
            var4['size'] = var10;
            var4 = var6.bind(var7)(var5, var4);
            var1['icon'] = var4;
            var4 = 3;
            var4 = var9[var4];
            var4 = var8.bind(var7)(var4);
            var4 = var4.GameProfileTrackActionActions;
            var4 = var4.YouTubeLink;
            var1['action'] = var4;
            var4 = 4;
            var5 = var9[var4];
            var5 = var8.bind(var7)(var5);
            var6 = var5.intl;
            var5 = var6.string;
            var4 = var9[var4];
            var4 = var8.bind(var7)(var4);
            var4 = var4.t;
            var4 = var4.lNmxbE;
            var4 = var5.bind(var6)(var4);
            var1['title'] = var4;
            var4 = var2.url;
            var1['url'] = var4;
            return var1;
case 4:
            var1 = {};
            var6 = _closure1_slot3;
            var8 = _closure1_slot0;
            var9 = _closure1_slot2;
            var4 = 5;
            var4 = var9[var4];
            var4 = var8.bind(var7)(var4);
            var5 = var4.XNeutralIcon;
            var4 = {};
            var10 = 'md';
            var4['size'] = var10;
            var11 = _closure1_slot1;
            var10 = 6;
            var10 = var9[var10];
            var10 = var11.bind(var7)(var10);
            var10 = var10.colors;
            var10 = var10.INTERACTIVE_ICON_DEFAULT;
            var4['color'] = var10;
            var4 = var6.bind(var7)(var5, var4);
            var1['icon'] = var4;
            var4 = 3;
            var4 = var9[var4];
            var4 = var8.bind(var7)(var4);
            var4 = var4.GameProfileTrackActionActions;
            var4 = var4.XLink;
            var1['action'] = var4;
            var4 = 4;
            var5 = var9[var4];
            var5 = var8.bind(var7)(var5);
            var6 = var5.intl;
            var5 = var6.string;
            var4 = var9[var4];
            var4 = var8.bind(var7)(var4);
            var4 = var4.t;
            var4 = var4.INic4y;
            var4 = var5.bind(var6)(var4);
            var1['title'] = var4;
            var4 = var2.url;
            var1['url'] = var4;
            return var1;
case 2:
            var1 = {};
            var5 = _closure1_slot3;
            var6 = _closure1_slot0;
            var8 = _closure1_slot2;
            var3 = 2;
            var3 = var8[var3];
            var3 = var6.bind(var7)(var3);
            var4 = var3.GlobeEarthIcon;
            var3 = {};
            var9 = 'md';
            var3['size'] = var9;
            var3 = var5.bind(var7)(var4, var3);
            var1['icon'] = var3;
            var3 = 3;
            var3 = var8[var3];
            var3 = var6.bind(var7)(var3);
            var3 = var3.GameProfileTrackActionActions;
            var3 = var3.WebsiteLink;
            var1['action'] = var3;
            var3 = 4;
            var4 = var8[var3];
            var4 = var6.bind(var7)(var4);
            var5 = var4.intl;
            var4 = var5.string;
            var3 = var8[var3];
            var3 = var6.bind(var7)(var3);
            var3 = var3.t;
            var3 = var3.fOUKvg;
            var3 = var4.bind(var5)(var3);
            var1['title'] = var3;
            var2 = var2.url;
            var1['url'] = var2;
            return var1;
        }
    };
    var3['default'] = var2;
    return var1;
})();