// app/modules/age_gate/native/components/Constants.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var3 = exports;
    var1 = global;
    var5 = var1.Object;
    var4 = var5.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var4.bind(var5)(var3, var1, var2);
    var2 = {};
    var4 = 0;
    var2['MODAL'] = var4;
    var1 = 'MODAL';
    var2[var4] = var1;
    var5 = 1;
    var2['GUILD_SIDEBAR'] = var5;
    var1 = 'GUILD_SIDEBAR';
    var2[var5] = var1;
    var1 = dependencyMap;
    var5 = var1[var4];
    var4 = require;
    var1 = undefined;
    var6 = var4.bind(var1)(var5);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/age_gate/native/components/Constants.tsx';
    var4 = var5.bind(var6)(var4);
    var3['NsfwGateSource'] = var2;
    return var1;
})();