// app/modules/dice_roll/DiceRollConstants.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var3 = exports;
    var1 = global;
    var6 = var1.Object;
    var5 = var6.defineProperty;
    var4 = {};
    var2 = true;
    var4['value'] = var2;
    var2 = '__esModule';
    var2 = var5.bind(var6)(var3, var2, var4);
    var4 = [4, 6, 8, 10, 12, 20];
    var1 = var1.Set;
    var2 = var1.prototype;
    var2 = Object.create(var2, {constructor: {value: var1}});
    var11 = var2;
    var10 = var4;
    var1 = new var11[var1](var10, var9);
    var2 = var1 instanceof Object ? var1 : var2;
    var5 = dependencyMap;
    var1 = 0;
    var6 = var5[var1];
    var5 = require;
    var1 = undefined;
    var7 = var5.bind(var1)(var6);
    var6 = var7.fileFinishedImporting;
    var5 = 'modules/dice_roll/DiceRollConstants.tsx';
    var5 = var6.bind(var7)(var5);
    var5 = 1500;
    var3['ROLL_DURATION_MS'] = var5;
    var5 = 2000;
    var3['AFTER_ROLL_DELAY_MS'] = var5;
    var5 = 300;
    var3['DISMISS_DELAY_MS'] = var5;
    var5 = 10;
    var3['MAX_DICE_COUNT'] = var5;
    var3['ALLOWED_DICE_SIDES'] = var4;
    var3['ALLOWED_DICE_SIDES_SET'] = var2;
    var2 = 6;
    var3['DEFAULT_DICE_SIDES'] = var2;
    return var1;
})();