// app/modules/quests/native/QuestDock/QuestDockUnenrolledBody.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var12 = metroImportDefault;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var12;
    var _closure1_slot2 = var6;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var12.bind(var1)(var4);
    var _closure1_slot3 = var4;
    var4 = 1;
    var7 = var6[var4];
    var4 = metroImportAll;
    var7 = var4.bind(var1)(var7);
    var _closure1_slot4 = var7;
    var4 = 2;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.View;
    var _closure1_slot5 = var4;
    var4 = 3;
    var4 = var6[var4];
    var4 = var12.bind(var1)(var4);
    var _closure1_slot6 = var4;
    var4 = 4;
    var4 = var6[var4];
    var4 = var12.bind(var1)(var4);
    var _closure1_slot7 = var4;
    var4 = 5;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var8 = var4.QuestDockMode;
    var _closure1_slot8 = var8;
    var4 = var4.QuestsExperimentLocations;
    var _closure1_slot9 = var4;
    var4 = 6;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var11 = var4.QUEST_DOCK_BORDER_RADII;
    var13 = var4.QUEST_DOCK_EXPANDED_PADDING_BOTTOM;
    var _closure1_slot10 = var13;
    var14 = var4.QUEST_DOCK_EXPANDED_PADDING_HORIZONTAL;
    var4 = 7;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var8 = var4.jsx;
    var _closure1_slot11 = var8;
    var4 = var4.jsxs;
    var _closure1_slot12 = var4;
    var4 = 8;
    var4 = var6[var4];
    var9 = var5.bind(var1)(var4);
    var8 = var9.createStyles;
    var4 = {};
    var10 = {'flexGrow': 1, 'flexShrink': 0, 'justifyContent': 'flex-end'};
    var10['paddingHorizontal'] = var14;
    var10['paddingBottom'] = var13;
    var4['wrapper'] = var10;
    var10 = {'borderRadius': null, 'overflow': 'hidden', 'padding': 8, 'paddingRight': 16};
    var10['borderRadius'] = var11;
    var4['rewardContentWrapper'] = var10;
    var10 = {'alignItems': 'center', 'flexDirection': 'row', 'gap': 16};
    var4['rewardContent'] = var10;
    var10 = {'flexGrow': 1, 'flexShrink': 1, 'gap': 4};
    var4['rewardContentCopy'] = var10;
    var10 = {};
    var11 = 9;
    var13 = var6[var11];
    var13 = var12.bind(var1)(var13);
    var13 = var13.radii;
    var13 = var13.lg;
    var10['borderRadius'] = var13;
    var4['questDockRewardTile'] = var10;
    var10 = {'marginTop': 12, 'paddingHorizontal': 4, 'paddingTop': 16, 'position': 'relative'};
    var4['questDockCtaWrapper'] = var10;
    var10 = {};
    var13 = var6[var11];
    var13 = var12.bind(var1)(var13);
    var13 = var13.radii;
    var13 = var13.round;
    var10['borderRadius'] = var13;
    var4['questDockCta'] = var10;
    var10 = {'position': 'absolute', 'left': 4294967284, 'right': 4294967284, 'top': 0, 'backgroundColor': null, 'height': 1, 'opacity': 1};
    var11 = var6[var11];
    var11 = var12.bind(var1)(var11);
    var11 = var11.colors;
    var11 = var11.BORDER_SUBTLE;
    var10['backgroundColor'] = var11;
    var4['questDockCtaSaparator'] = var10;
    var4 = var8.bind(var9)(var4);
    var _closure1_slot13 = var4;
    var4 = var7.memo;
    var2 = function QuestDockUnenrolledBody() {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var5 = _closure1_slot4;
            var3 = var5.useContext;
            var2 = _closure1_slot1;
            var9 = _closure1_slot2;
            var1 = 10;
            var1 = var9[var1];
            var4 = undefined;
            var1 = var2.bind(var4)(var1);
            var1 = var3.bind(var5)(var1);
            var15 = var1.isVisible;
            var18 = var1.quest;
            var _closure2_slot0 = var18;
            var1 = _closure1_slot13;
            var22 = var1.bind(var4)();
            var3 = _closure1_slot0;
            var1 = 11;
            var6 = var9[var1];
            var11 = var3.bind(var4)(var6);
            var8 = var11.useStateFromStores;
            var6 = _closure1_slot7;
            var7 = new Array(1);
            var7[0] = var6;
            var6 = function() {
                var2 = _closure1_slot7;
                var2 = var2.prevRestingQuestDockMode;
                var1 = _closure1_slot8;
                var1 = var1.EXPANDED;
                var1 = var2 === var1;
                return var1;
            };
            var13 = var8.bind(var11)(var7, var6);
            var1 = var9[var1];
            var8 = var3.bind(var4)(var1);
            var7 = var8.useStateFromStores;
            var1 = _closure1_slot6;
            var6 = new Array(1);
            var6[0] = var1;
            var1 = function() {
                var3 = _closure1_slot6;
                var2 = var3.isEnrolling;
                var1 = _closure2_slot0;
                var1 = var1.id;
                var1 = var2.bind(var3)(var1);
                return var1;
            };
            var20 = var7.bind(var8)(var6, var1);
            var1 = 12;
            var6 = var9[var1];
            var8 = var3.bind(var4)(var6);
            var7 = var8.useHasWatchVideoOnMobileTasks;
            var6 = var18.config;
            var11 = var7.bind(var8)(var6);
            var _closure2_slot1 = var11;
            var6 = 13;
            var6 = var9[var6];
            var7 = var3.bind(var4)(var6);
            var6 = var7.useQuestTaskDetails;
            var33 = var6.bind(var7)(var18);
            var1 = var9[var1];
            var6 = var3.bind(var4)(var1);
            var1 = var6.useMobileActivityQuest;
            var1 = var1.bind(var6)(var18);
            var8 = var1.isMobileActivityQuest;
            var _closure2_slot2 = var8;
            var17 = var1.questApplication;
            var6 = var1.launchMobileActivity;
            var _closure2_slot3 = var6;
            var1 = 14;
            var1 = var9[var1];
            var1 = var2.bind(var4)(var1);
            var1 = var1.bind(var4)();
            var12 = var1.bottom;
            var1 = 15;
            var1 = var9[var1];
            var7 = var3.bind(var4)(var1);
            var2 = var7.useYouBarEnabled;
            var1 = 'QuestDockUnenrolledBody';
            var7 = var2.bind(var7)(var1);
            var2 = var5.useContext;
            var1 = 16;
            var1 = var9[var1];
            var1 = var3.bind(var4)(var1);
            var1 = var1.QuestDockExternalCoordinationContext;
            var1 = var2.bind(var5)(var1);
            var9 = var1.setRestingQuestDockMode;
            var _closure2_slot4 = var9;
            var3 = var5.useCallback;
            var2 = _closure1_slot3;
            var1 = function* () {
                var1 = function* anon_0_() {
                    _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
case 0:
                        StartGenerator();
                        ResumeGenerator(result_out_reg=0, return_bool_out_reg=1);
                        if(var2) { _fun0002_ip = 2; continue _fun0002 }
case 3:
                        var11 = _closure1_slot0;
                        var9 = _closure1_slot2;
                        var2 = 17;
                        var2 = var9[var2];
                        var4 = undefined;
                        var8 = var11.bind(var4)(var2);
                        var7 = var8.enrollInQuest;
                        var2 = _closure2_slot0;
                        var3 = var2.id;
                        var2 = {};
                        var10 = 18;
                        var10 = var9[var10];
                        var10 = var11.bind(var4)(var10);
                        var10 = var10.QuestContentCTA;
                        var10 = var10.ACCEPT_QUEST;
                        var2['questContentCTA'] = var10;
                        var10 = 19;
                        var12 = var9[var10];
                        var12 = var11.bind(var4)(var12);
                        var12 = var12.QuestContent;
                        var12 = var12.QUEST_BAR_MOBILE;
                        var2['questContent'] = var12;
                        var9 = var9[var10];
                        var9 = var11.bind(var4)(var9);
                        var9 = var9.QuestContent;
                        var9 = var9.QUEST_BAR_MOBILE;
                        var2['sourceQuestContent'] = var9;
                        var2 = var7.bind(var8)(var3, var2);
                        SaveGenerator(address=149);
case 4:
                        return var2;
case 5:
                        ResumeGenerator(result_out_reg=1, return_bool_out_reg=2);
                        if(var3) { _fun0002_ip = 6; continue _fun0002 }
case 7:
                        var3 = _closure2_slot2;
                        if(var3) { _fun0002_ip = 8; continue _fun0002 }
case 9:
                        var3 = _closure2_slot1;
                        if(!var3) { _fun0002_ip = 10; continue _fun0002 }
case 11:
                        var7 = _closure1_slot1;
                        var8 = _closure1_slot2;
                        var3 = 20;
                        var3 = var8[var3];
                        var7 = var7.bind(var4)(var3);
                        var3 = {};
                        var9 = _closure2_slot0;
                        var9 = var9.id;
                        var3['questId'] = var9;
                        var9 = _closure1_slot0;
                        var8 = var8[var10];
                        var8 = var9.bind(var4)(var8);
                        var8 = var8.QuestContent;
                        var8 = var8.QUEST_BAR_MOBILE;
                        var3['sourceQuestContent'] = var8;
                        var3 = var7.bind(var4)(var3);
                        var7 = _closure2_slot4;
                        var3 = _closure1_slot8;
                        var3 = var3.COLLAPSED;
                        var3 = var7.bind(var4)(var3);
                        _fun0002_ip = 10; continue _fun0002;
case 8:
                        var3 = _closure2_slot3;
                        var3 = var3.bind(var4)();
                        SaveGenerator(address=279);
case 12:
                        return var3;
case 13:
                        ResumeGenerator(result_out_reg=2, return_bool_out_reg=6);
                        if(var7) { _fun0002_ip = 14; continue _fun0002 }
case 15:
                        var6 = _closure2_slot4;
                        var5 = _closure1_slot8;
                        var5 = var5.COLLAPSED;
                        var5 = var6.bind(var4)(var5);
case 10:
                        return var4;
case 14:
                        return var3;
case 6:
                        return var2;
case 2:
                        return var1;
                    }
                };
                return var1;
            };
            var2 = var2.bind(var4)(var1);
            var14 = var18.id;
            var1 = new Array(5);
            var1[0] = var14;
            var1[1] = var11;
            var1[2] = var9;
            var1[3] = var8;
            var1[4] = var6;
            var21 = var3.bind(var5)(var2, var1);
            var3 = _closure1_slot12;
            var2 = _closure1_slot5;
            var1 = {};
            var6 = var22.wrapper;
            var5 = new Array(2);
            var5[0] = var6;
            var6 = null;
            if(!var7) { _fun0001_ip = 16; continue _fun0001 }
case 17:
            var7 = {};
            var8 = global;
            var11 = var8.Math;
            var9 = var11.max;
            var8 = _closure1_slot10;
            var8 = var9.bind(var11)(var12, var8);
            var7['paddingBottom'] = var8;
            var6 = var7;
case 16:
            var5[1] = var6;
            var1['style'] = var5;
            var9 = _closure1_slot12;
            var6 = _closure1_slot5;
            var5 = {};
            var7 = var22.rewardContentWrapper;
            var5['style'] = var7;
            var12 = _closure1_slot11;
            var8 = _closure1_slot1;
            var14 = _closure1_slot2;
            var7 = 21;
            var7 = var14[var7];
            var11 = var8.bind(var4)(var7);
            var7 = {};
            var7 = var12.bind(var4)(var11, var7);
            var11 = new Array(2);
            var11[0] = var7;
            var23 = {};
            var7 = var22.rewardContent;
            var23['style'] = var7;
            var7 = 22;
            var7 = var14[var7];
            var8 = var8.bind(var4)(var7);
            var7 = {'paused': null, 'height': 80, 'width': 80};
            var14 = !var13;
            if(var14) { _fun0001_ip = 18; continue _fun0001 }
case 19:
            var14 = !var15;
case 18:
            var7['paused'] = var14;
            var7['quest'] = var18;
            var14 = var22.questDockRewardTile;
            var7['style'] = var14;
            var14 = var13;
            if(!var14) { _fun0001_ip = 20; continue _fun0001 }
case 21:
            var14 = var15;
case 20:
            var7['withAnimation'] = var14;
            var7 = var12.bind(var4)(var8, var7);
            var24 = new Array(2);
            var24[0] = var7;
            var8 = _closure1_slot12;
            var7 = _closure1_slot5;
            var25 = {};
            var12 = var22.rewardContentCopy;
            var25['style'] = var12;
            var12 = _closure1_slot11;
            var15 = _closure1_slot0;
            var16 = _closure1_slot2;
            var14 = 23;
            var26 = var16[var14];
            var26 = var15.bind(var4)(var26);
            var27 = var26.Text;
            var26 = {'variant': 'heading-md/medium', 'color': 'mobile-text-heading-primary'};
            var28 = 24;
            var29 = var16[var28];
            var29 = var15.bind(var4)(var29);
            var31 = var29.intl;
            var30 = var31.format;
            var28 = var16[var28];
            var28 = var15.bind(var4)(var28);
            var28 = var28.t;
            var29 = var28.EQa7os;
            var28 = {};
            var32 = var18.config;
            var32 = var32.messages;
            var32 = var32.questName;
            var28['questName'] = var32;
            var28 = var30.bind(var31)(var29, var28);
            var26['children'] = var28;
            var27 = var12.bind(var4)(var27, var26);
            var26 = new Array(2);
            var26[0] = var27;
            var14 = var16[var14];
            var14 = var15.bind(var4)(var14);
            var28 = var14.Text;
            var27 = {'color': 'text-default', 'variant': 'text-sm/normal'};
            var14 = 25;
            var29 = var16[var14];
            var31 = var15.bind(var4)(var29);
            var30 = var31.useQuestsInstructionsToWinReward;
            var29 = {};
            var29['quest'] = var18;
            var32 = _closure1_slot9;
            var32 = var32.QUESTS_BAR_MOBILE;
            var29['location'] = var32;
            var32 = 19;
            var34 = var16[var32];
            var34 = var15.bind(var4)(var34);
            var34 = var34.QuestContent;
            var34 = var34.QUEST_BAR_MOBILE;
            var29['questContent'] = var34;
            var29['taskDetails'] = var33;
            var32 = var16[var32];
            var32 = var15.bind(var4)(var32);
            var32 = var32.QuestContent;
            var32 = var32.QUEST_BAR_MOBILE;
            var29['sourceQuestContent'] = var32;
            var29 = var30.bind(var31)(var29);
            var27['children'] = var29;
            var27 = var12.bind(var4)(var28, var27);
            var26[1] = var27;
            var25['children'] = var26;
            var25 = var8.bind(var4)(var7, var25);
            var24[1] = var25;
            var23['children'] = var24;
            var23 = var9.bind(var4)(var6, var23);
            var11[1] = var23;
            var5['children'] = var11;
            var6 = var9.bind(var4)(var6, var5);
            var5 = new Array(2);
            var5[0] = var6;
            var6 = {};
            var9 = var22.questDockCtaWrapper;
            var6['style'] = var9;
            var9 = {};
            var11 = var22.questDockCtaSaparator;
            var9['style'] = var11;
            var11 = var12.bind(var4)(var7, var9);
            var9 = new Array(2);
            var9[0] = var11;
            var11 = _closure1_slot1;
            var10 = 26;
            var10 = var16[var10];
            var11 = var11.bind(var4)(var10);
            var10 = {};
            var22 = var22.questDockCta;
            var10['style'] = var22;
            var10['onPress'] = var21;
            var10['loading'] = var20;
            var19 = function renderIcon() {
                var3 = _closure1_slot0;
                var2 = _closure1_slot2;
                var1 = 27;
                var2 = var2[var1];
                var1 = undefined;
                var4 = var3.bind(var1)(var2);
                var3 = var4.getPrimaryCtaIcon;
                var2 = _closure2_slot0;
                var1 = true;
                var1 = var3.bind(var4)(var2, var1);
                return var1;
            };
            var10['renderIcon'] = var19;
            var14 = var16[var14];
            var16 = var15.bind(var4)(var14);
            var15 = var16.usePrimaryCtaCopy;
            var14 = {};
            var14['quest'] = var18;
            var14['application'] = var17;
            var14 = var15.bind(var16)(var14);
            var10['text'] = var14;
            var13 = !var13;
            var10['shineDisabled'] = var13;
            var10 = var12.bind(var4)(var11, var10);
            var9[1] = var10;
            var6['children'] = var9;
            var6 = var8.bind(var4)(var7, var6);
            var5[1] = var6;
            var1['children'] = var5;
            var1 = var3.bind(var4)(var2, var1);
            return var1;
        }
    };
    var2 = var4.bind(var7)(var2);
    var4 = 28;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/quests/native/QuestDock/QuestDockUnenrolledBody.tsx';
    var4 = var5.bind(var6)(var4);
    var3['default'] = var2;
    return var1;
})();