// app/modules/app_analytics/clickstream/ClickstreamExperiment.tsx
export default (function(native1, native2, native3, native4, native5, native6, native7) {
    var5 = native2;
    var3 = native6;
    var6 = native7;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var12 = true;
    var4['value'] = var12;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var9 = var5.bind(var1)(var4);
    var8 = var9.createExperiment;
    var7 = {'kind': 'user', 'id': '2024-03_clickstream_analytics', 'label': 'Clickstream Analytics'};
    var4 = {};
    var10 = false;
    var4['enabled'] = var10;
    var7['defaultConfig'] = var4;
    var11 = {'id': 1, 'label': 'Enable Clickstream Analytics'};
    var4 = 1;
    var10 = {};
    var10['enabled'] = var12;
    var11['config'] = var10;
    var10 = new Array(1);
    var10[0] = var11;
    var7['treatments'] = var10;
    var7 = var8.bind(var9)(var7);
    var _closure1_slot0 = var7;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/app_analytics/clickstream/ClickstreamExperiment.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function clickstreamExperimentEnabled() {
        var3 = _closure1_slot0;
        var2 = var3.getCurrentConfig;
        var1 = {};
        var4 = 'clickstream';
        var1['location'] = var4;
        var1 = var2.bind(var3)(var1);
        var1 = var1.enabled;
        return var1;
    };
    var3['clickstreamExperimentEnabled'] = var2;
    return var1;
})();