// app/design/components/AccessibilityAnnouncer/AccessibilityAnnouncerLiveRegion.android.tsx
export default (function(argFoo, argBar, _, argCorge, __, argFred, argPlugh) {
    oscar = argBar;
    zulu = argFred;
    golf = argPlugh;
    entity = global;
    options = entity.Object;
    report = options.defineProperty;
    mike = {};
    entity = true;
    mike['value'] = entity;
    entity = '__esModule';
    entity = report.bind(options)(zulu, entity, mike);
    entity = 0;
    report = golf[entity];
    mike = argCorge;
    entity = undefined;
    options = mike.bind(entity)(report);
    mike = 1;
    mike = golf[mike];
    mike = oscar.bind(entity)(mike);
    mike = mike.Text;
    var _closure1_slot0 = mike;
    mike = 2;
    mike = golf[mike];
    mike = oscar.bind(entity)(mike);
    mike = mike.jsx;
    var _closure1_slot1 = mike;
    mike = 3;
    mike = golf[mike];
    verify = oscar.bind(entity)(mike);
    report = verify.create;
    mike = function() {
        entity = {};
        mike = undefined;
        entity['message'] = mike;
        mike = 0;
        entity['version'] = mike;
        return entity;
    };
    mike = report.bind(verify)(mike);
    var _closure1_slot2 = mike;
    report = options.memo;
    mike = function() {
        mike = _closure1_slot2;
        report = undefined;
        mike = mike.bind(report)();
        oscar = mike.message;
        tango = mike.version;
        zulu = _closure1_slot1;
        mike = _closure1_slot0;
        entity = {};
        golf = 'polite';
        entity['accessibilityLiveRegion'] = golf;
        golf = {};
        options = 'none';
        golf['display'] = options;
        entity['style'] = golf;
        entity['children'] = oscar;
        entity = zulu.bind(report)(mike, entity, tango);
        return entity;
    };
    mike = report.bind(options)(mike);
    report = 4;
    report = golf[report];
    golf = oscar.bind(entity)(report);
    oscar = golf.fileFinishedImporting;
    report = 'design/components/AccessibilityAnnouncer/AccessibilityAnnouncerLiveRegion.android.tsx';
    report = oscar.bind(golf)(report);
    tango = function(argFoo) { // Original name: updateAccessibilityAnnouncerLiveRegionMessage
        mike = argFoo;
        var _closure2_slot0 = mike;
        zulu = _closure1_slot2;
        mike = zulu.setState;
        entity = function(argFoo) {
            entity = argFoo;
            zulu = entity.version;
            entity = {};
            mike = _closure2_slot0;
            entity['message'] = mike;
            mike = 1;
            mike = zulu + mike;
            entity['version'] = mike;
            return entity;
        };
        entity = mike.bind(zulu)(entity);
        entity = undefined;
        return entity;
    };
    zulu['updateAccessibilityAnnouncerLiveRegionMessage'] = tango;
    zulu['AccessibilityAnnouncerLiveRegion'] = mike;
    return entity;
})();