// app/design/components/AccessibilityAnnouncer/AccessibilityAnnouncerLiveRegion.android.tsx
export default (function(argFoo, argBar, _, argCor, __, argFre, argPlu) {
    oscard = argBar;
    zuuluu = argFre;
    golfie = argPlu;
    entity = global;
    option = entity.Object;
    report = option.defineProperty;
    michal = {};
    entity = true;
    michal['value'] = entity;
    entity = '__esModule';
    entity = report.bind(option)(zuuluu, entity, michal);
    entity = 0;
    report = golfie[entity];
    michal = argCor;
    entity = undefined;
    option = michal.bind(entity)(report);
    michal = 1;
    michal = golfie[michal];
    michal = oscard.bind(entity)(michal);
    michal = michal.Text;
    var _closure1_slot0 = michal;
    michal = 2;
    michal = golfie[michal];
    michal = oscard.bind(entity)(michal);
    michal = michal.jsx;
    var _closure1_slot1 = michal;
    michal = 3;
    michal = golfie[michal];
    verify = oscard.bind(entity)(michal);
    report = verify.create;
    michal = function() {
        entity = {};
        michal = undefined;
        entity['message'] = michal;
        michal = 0;
        entity['version'] = michal;
        return entity;
    };
    michal = report.bind(verify)(michal);
    var _closure1_slot2 = michal;
    report = option.memo;
    michal = function() {
        michal = _closure1_slot2;
        report = undefined;
        michal = michal.bind(report)();
        oscard = michal.message;
        tangon = michal.version;
        zuuluu = _closure1_slot1;
        michal = _closure1_slot0;
        entity = {};
        golfie = 'polite';
        entity['accessibilityLiveRegion'] = golfie;
        golfie = {};
        option = 'none';
        golfie['display'] = option;
        entity['style'] = golfie;
        entity['children'] = oscard;
        entity = zuuluu.bind(report)(michal, entity, tangon);
        return entity;
    };
    michal = report.bind(option)(michal);
    report = 4;
    report = golfie[report];
    golfie = oscard.bind(entity)(report);
    oscard = golfie.fileFinishedImporting;
    report = 'design/components/AccessibilityAnnouncer/AccessibilityAnnouncerLiveRegion.android.tsx';
    report = oscard.bind(golfie)(report);
    tangon = function(argFoo) { // Original name: updateAccessibilityAnnouncerLiveRegionMessage
        michal = argFoo;
        var _closure2_slot0 = michal;
        zuuluu = _closure1_slot2;
        michal = zuuluu.setState;
        entity = function(argFoo) {
            entity = argFoo;
            zuuluu = entity.version;
            entity = {};
            michal = _closure2_slot0;
            entity['message'] = michal;
            michal = 1;
            michal = zuuluu + michal;
            entity['version'] = michal;
            return entity;
        };
        entity = michal.bind(zuuluu)(entity);
        entity = undefined;
        return entity;
    };
    zuuluu['updateAccessibilityAnnouncerLiveRegionMessage'] = tangon;
    zuuluu['AccessibilityAnnouncerLiveRegion'] = michal;
    return entity;
})();