// app/modules/video_calls/native/components/ChannelVoiceChatModal.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var1 = metroImportDefault;
    var _closure1_slot1 = var1;
    var _closure1_slot2 = var6;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var7 = var6[var1];
    var4 = metroImportAll;
    var1 = undefined;
    var4 = var4.bind(var1)(var7);
    var _closure1_slot3 = var4;
    var4 = 1;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.jsx;
    var _closure1_slot4 = var4;
    var4 = 7;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/video_calls/native/components/ChannelVoiceChatModal.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function ChannelVoiceChatModal(arg1) {
        var1 = arg1;
        var7 = var1.channel;
        var _closure2_slot0 = var7;
        var4 = _closure1_slot3;
        var3 = var4.useEffect;
        var1 = var7.id;
        var2 = new Array(1);
        var2[0] = var1;
        var1 = function() {
            var3 = _closure1_slot1;
            var2 = _closure1_slot2;
            var1 = 2;
            var2 = var2[var1];
            var1 = undefined;
            var4 = var3.bind(var1)(var2);
            var3 = var4.updateChatOpen;
            var1 = _closure2_slot0;
            var2 = var1.id;
            var1 = true;
            var1 = var3.bind(var4)(var2, var1);
            var1 = function() {
                var3 = _closure1_slot1;
                var2 = _closure1_slot2;
                var1 = 2;
                var2 = var2[var1];
                var1 = undefined;
                var5 = var3.bind(var1)(var2);
                var4 = var5.updateChatOpen;
                var2 = _closure2_slot0;
                var3 = var2.id;
                var2 = false;
                var2 = var4.bind(var5)(var3, var2);
                return var1;
            };
            return var1;
        };
        var1 = var3.bind(var4)(var1, var2);
        var4 = _closure1_slot4;
        var10 = _closure1_slot1;
        var11 = _closure1_slot2;
        var1 = 3;
        var1 = var11[var1];
        var3 = undefined;
        var2 = var10.bind(var3)(var1);
        var1 = {};
        var8 = 'StageVoiceChat';
        var1['screenKey'] = var8;
        var7 = var7.name;
        var1['title'] = var7;
        var7 = _closure1_slot0;
        var6 = 4;
        var6 = var11[var6];
        var6 = var7.bind(var3)(var6);
        var7 = var6.StageIcon;
        var6 = {};
        var8 = 'sm';
        var6['size'] = var8;
        var8 = {};
        var9 = 5;
        var9 = var11[var9];
        var9 = var10.bind(var3)(var9);
        var9 = var9.spacing;
        var9 = var9.PX_8;
        var8['marginRight'] = var9;
        var6['style'] = var8;
        var6 = var4.bind(var3)(var7, var6);
        var1['titleIcon'] = var6;
        var5 = function render() {
            var4 = _closure1_slot4;
            var2 = _closure1_slot1;
            var3 = _closure1_slot2;
            var1 = 6;
            var1 = var3[var1];
            var3 = undefined;
            var2 = var2.bind(var3)(var1);
            var1 = {};
            var5 = _closure2_slot0;
            var1['channel'] = var5;
            var5 = true;
            var1['inModal'] = var5;
            var1 = var4.bind(var3)(var2, var1);
            return var1;
        };
        var1['render'] = var5;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var3['default'] = var2;
    return var1;
})();