// app/modules/video_calls/native/components/SingleStream.tsx
export default (function(argFoo, argBar, argBaz, argCorge, _, argFred, argPlugh) {
    report = argBar;
    zulu = argFred;
    oscar = argPlugh;
    var _closure1_slot0 = report;
    entity = argBaz;
    var _closure1_slot1 = entity;
    var _closure1_slot2 = oscar;
    entity = global;
    options = entity.Object;
    golf = options.defineProperty;
    tango = {};
    entity = true;
    tango['value'] = entity;
    entity = '__esModule';
    entity = golf.bind(options)(zulu, entity, tango);
    entity = 0;
    golf = oscar[entity];
    tango = argCorge;
    entity = undefined;
    tango = tango.bind(entity)(golf);
    tango = 1;
    tango = oscar[tango];
    tango = report.bind(entity)(tango);
    golf = tango.toggleFocus;
    var _closure1_slot3 = golf;
    tango = tango.resetFocus;
    var _closure1_slot4 = tango;
    tango = 2;
    tango = oscar[tango];
    tango = report.bind(entity)(tango);
    tango = tango.jsx;
    var _closure1_slot5 = tango;
    tango = 6;
    tango = oscar[tango];
    oscar = report.bind(entity)(tango);
    report = oscar.fileFinishedImporting;
    tango = 'modules/video_calls/native/components/SingleStream.tsx';
    tango = report.bind(oscar)(tango);
    mike = function(argFoo) { // Original name: _default
        entity = argFoo;
        report = entity.participant;
        entity = entity.channel;
        var _closure2_slot0 = entity;
        tango = _closure1_slot5;
        mike = _closure1_slot1;
        verify = _closure1_slot2;
        entity = 3;
        entity = verify[entity];
        zulu = undefined;
        mike = mike.bind(zulu)(entity);
        entity = {};
        options = true;
        entity['gestureEnabled'] = options;
        options = _closure1_slot0;
        golf = 4;
        golf = verify[golf];
        golf = options.bind(zulu)(golf);
        golf = golf.ResizeMode;
        golf = golf.CONTAIN;
        entity['resizeMode'] = golf;
        golf = function() { // Original name: onSingleTap
            mike = _closure1_slot3;
            entity = undefined;
            mike = mike.bind(entity)();
            return entity;
        };
        entity['onSingleTap'] = golf;
        oscar = function() { // Original name: onDoubleTap
            zulu = _closure1_slot4;
            entity = undefined;
            zulu = zulu.bind(entity)();
            zulu = _closure1_slot1;
            tango = _closure1_slot2;
            mike = 5;
            mike = tango[mike];
            report = zulu.bind(entity)(mike);
            tango = report.selectParticipant;
            mike = _closure2_slot0;
            zulu = mike.id;
            mike = null;
            mike = tango.bind(report)(zulu, mike);
            return entity;
        };
        entity['onDoubleTap'] = oscar;
        entity['participant'] = report;
        report = {};
        oscar = 1;
        report['flex'] = oscar;
        entity['style'] = report;
        entity = tango.bind(zulu)(mike, entity);
        return entity;
    };
    zulu['default'] = mike;
    return entity;
})();