// app/modules/video_calls/native/components/usePipPosition.tsx
export default (function(native1, native2, native3, native4, native5, native6, native7) {
    var5 = native2;
    var3 = native6;
    var6 = native7;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var6;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var7 = var6[var1];
    var4 = native3;
    var1 = undefined;
    var4 = var4.bind(var1)(var7);
    var _closure1_slot2 = var4;
    var4 = 1;
    var7 = var6[var4];
    var4 = native4;
    var4 = var4.bind(var1)(var7);
    var _closure1_slot3 = var4;
    var4 = 4;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/video_calls/native/components/usePipPosition.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function usePipPosition() {
        var5 = _closure1_slot3;
        var4 = var5.useState;
        var3 = function() {
            var5 = _closure1_slot0;
            var6 = _closure1_slot1;
            var1 = 2;
            var1 = var6[var1];
            var2 = undefined;
            var1 = var5.bind(var2)(var1);
            var4 = var1.Storage;
            var3 = var4.get;
            var1 = 3;
            var1 = var6[var1];
            var1 = var5.bind(var2)(var1);
            var2 = var1.DEFAULT_PIP_POSITION;
            var1 = 'CameraPreviewPosition';
            var1 = var3.bind(var4)(var1, var2);
            return var1;
        };
        var6 = var4.bind(var5)(var3);
        var4 = _closure1_slot2;
        var3 = undefined;
        var1 = 2;
        var4 = var4.bind(var3)(var6, var1);
        var1 = 0;
        var3 = var4[var1];
        var1 = 1;
        var1 = var4[var1];
        var _closure2_slot0 = var1;
        var1 = new Array(2);
        var1[0] = var3;
        var4 = var5.useCallback;
        var3 = function(arg1) {
            var3 = arg1;
            var4 = _closure1_slot0;
            var2 = _closure1_slot1;
            var1 = 2;
            var2 = var2[var1];
            var1 = undefined;
            var2 = var4.bind(var1)(var2);
            var5 = var2.Storage;
            var4 = var5.set;
            var2 = 'CameraPreviewPosition';
            var2 = var4.bind(var5)(var2, var3);
            var2 = _closure2_slot0;
            var2 = var2.bind(var1)(var3);
            return var1;
        };
        var2 = new Array(0);
        var2 = var4.bind(var5)(var3, var2);
        var1[1] = var2;
        return var1;
    };
    var3['default'] = var2;
    return var1;
})();