// app/modules/mfa/native/screens/WebAuthnScreen.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var6 = require;
    var14 = metroImportDefault;
    var3 = exports;
    var7 = dependencyMap;
    var _closure1_slot0 = var6;
    var _closure1_slot1 = var14;
    var _closure1_slot2 = var7;
    var1 = function AndroidAuthRadioGroup(arg1) {
        var1 = arg1;
        var6 = var1.authenticatorSelection;
        var2 = var1.setAuthenticator;
        var _closure2_slot0 = var2;
        var5 = var1.inProgress;
        var2 = _closure1_slot6;
        var4 = undefined;
        var9 = var2.bind(var4)();
        var2 = {};
        var3 = _closure1_slot7;
        var3 = var3.ANDROID_PASSKEY;
        var2['value'] = var3;
        var13 = _closure1_slot0;
        var10 = _closure1_slot2;
        var3 = 6;
        var8 = var10[var3];
        var8 = var13.bind(var4)(var8);
        var12 = var8.intl;
        var11 = var12.string;
        var8 = var10[var3];
        var8 = var13.bind(var4)(var8);
        var8 = var8.t;
        var8 = var8.PVVXRE;
        var8 = var11.bind(var12)(var8);
        var2['name'] = var8;
        var8 = new Array(2);
        var8[0] = var2;
        var2 = {};
        var11 = _closure1_slot7;
        var11 = var11.AUTHENTICATE;
        var2['value'] = var11;
        var11 = var10[var3];
        var11 = var13.bind(var4)(var11);
        var12 = var11.intl;
        var11 = var12.string;
        var3 = var10[var3];
        var3 = var13.bind(var4)(var3);
        var3 = var3.t;
        var3 = var3.TKop3d;
        var3 = var11.bind(var12)(var3);
        var2['name'] = var3;
        var8[1] = var2;
        var3 = _closure1_slot5;
        var2 = _closure1_slot1;
        var1 = 7;
        var1 = var10[var1];
        var2 = var2.bind(var4)(var1);
        var1 = {};
        var9 = var9.radioItem;
        var1['style'] = var9;
        var1['options'] = var8;
        var7 = function onChange(arg1) {
            var1 = arg1;
            var3 = var1.value;
            var2 = _closure2_slot0;
            var1 = undefined;
            var1 = var2.bind(var1)(var3);
            return var1;
        };
        var1['onChange'] = var7;
        var1['value'] = var6;
        var1['disabled'] = var5;
        var5 = true;
        var1['withSpacing'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var _closure1_slot9 = var1;
    var1 = global;
    var8 = var1.Object;
    var5 = var8.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var5.bind(var8)(var3, var1, var2);
    var10 = 0;
    var2 = var7[var10];
    var1 = undefined;
    var2 = var14.bind(var1)(var2);
    var _closure1_slot3 = var2;
    var9 = 1;
    var5 = var7[var9];
    var2 = metroImportAll;
    var2 = var2.bind(var1)(var5);
    var _closure1_slot4 = var2;
    var2 = 2;
    var2 = var7[var2];
    var2 = var6.bind(var1)(var2);
    var8 = var2.NativeModules;
    var2 = 3;
    var2 = var7[var2];
    var2 = var6.bind(var1)(var2);
    var2 = var2.jsx;
    var _closure1_slot5 = var2;
    var2 = 4;
    var2 = var7[var2];
    var11 = var6.bind(var1)(var2);
    var5 = var11.createStyles;
    var2 = {};
    var12 = {};
    var13 = 5;
    var15 = var7[var13];
    var15 = var14.bind(var1)(var15);
    var15 = var15.colors;
    var15 = var15.BACKGROUND_SECONDARY;
    var12['backgroundColor'] = var15;
    var13 = var7[var13];
    var13 = var14.bind(var1)(var13);
    var13 = var13.radii;
    var13 = var13.md;
    var12['borderRadius'] = var13;
    var2['radioItem'] = var12;
    var2 = var5.bind(var11)(var2);
    var _closure1_slot6 = var2;
    var2 = {};
    var2['AUTHENTICATE'] = var10;
    var5 = 'AUTHENTICATE';
    var2[var10] = var5;
    var2['ANDROID_PASSKEY'] = var9;
    var5 = 'ANDROID_PASSKEY';
    var2[var9] = var5;
    var _closure1_slot7 = var2;
    var5 = {};
    var10 = var2.AUTHENTICATE;
    var9 = var8.DCDSecurityKeyManager;
    var9 = var9.authenticate;
    var5[var10] = var9;
    var9 = var2.ANDROID_PASSKEY;
    var8 = var8.DCDSecurityKeyManager;
    var8 = var8.authenticatePasskey;
    var5[var9] = var8;
    var _closure1_slot8 = var5;
    var5 = 13;
    var5 = var7[var5];
    var7 = var6.bind(var1)(var5);
    var6 = var7.fileFinishedImporting;
    var5 = 'modules/mfa/native/screens/WebAuthnScreen.tsx';
    var5 = var6.bind(var7)(var5);
    var4 = function WebAuthnScreen(arg1) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
 0:
            var2 = arg1;
            var8 = var2.mfaChallenge;
            var7 = var2.finish;
            var _closure2_slot0 = var7;
            var4 = undefined;
            var _closure2_slot3 = var4;
            var _closure2_slot4 = var4;
            var _closure2_slot5 = var4;
            var _closure2_slot6 = var4;
            var11 = _closure1_slot4;
            var2 = var11.useState;
            var14 = false;
            var2 = var2.bind(var11)(var14);
            var5 = _closure1_slot3;
            var13 = 2;
            var2 = var5.bind(var4)(var2, var13);
            var9 = 0;
            var12 = var2[var9];
            var3 = 1;
            var2 = var2[var3];
            var _closure2_slot1 = var2;
            var2 = var11.useState;
            var2 = var2.bind(var11)(var4);
            var2 = var5.bind(var4)(var2, var13);
            var5 = var2[var9];
            var2 = var2[var3];
            var _closure2_slot2 = var2;
            var6 = var11.useState;
            var16 = _closure1_slot0;
            var2 = _closure1_slot2;
            var10 = 8;
            var2 = var2[var10];
            var16 = var16.bind(var4)(var2);
            var2 = var16.isAndroid;
            var2 = var2.bind(var16)();
            var16 = _closure1_slot7;
            if(var2) { _fun0001_ip = 165; continue _fun0001 }
 157:
            var2 = var16.AUTHENTICATE;
            _fun0001_ip = 171; continue _fun0001;
 165:
            var2 = var16.ANDROID_PASSKEY;
 171:
            var2 = var6.bind(var11)(var2);
            var11 = _closure1_slot3;
            var2 = var11.bind(var4)(var2, var13);
            var17 = var2[var9];
            _closure2_slot3 = var17;
            var16 = var2[var3];
            var6 = _closure1_slot4;
            var2 = var6.useState;
            var2 = var2.bind(var6)(var14);
            var2 = var11.bind(var4)(var2, var13);
            var13 = var2[var9];
            var2 = var2[var3];
            _closure2_slot4 = var2;
            var9 = var8.methods;
            var3 = var9.find;
            var2 = function(arg1) {
                var1 = arg1;
                var2 = var1.type;
                var1 = 'webauthn';
                var1 = var1 === var2;
                return var1;
            };
            var2 = var3.bind(var9)(var2);
            var9 = var2.challenge;
            _closure2_slot5 = var9;
            var11 = var6.useMemo;
            var3 = new Array(1);
            var3[0] = var17;
            var2 = function() {
                var2 = _closure1_slot8;
                var1 = _closure2_slot3;
                var1 = var2[var1];
                return var1;
            };
            var11 = var11.bind(var6)(var2, var3);
            _closure2_slot6 = var11;
            var3 = var6.useCallback;
            var2 = new Array(3);
            var2[0] = var11;
            var2[1] = var9;
            var2[2] = var7;
            var1 = function() {
                var4 = _closure2_slot2;
                var1 = undefined;
                var4 = var4.bind(var1)(var1);
                var5 = _closure2_slot1;
                var4 = true;
                var4 = var5.bind(var1)(var4);
                var4 = _closure2_slot6;
                var3 = _closure2_slot5;
                var5 = var4.bind(var1)(var3);
                var4 = var5.then;
                var3 = function(arg1) {
                    var3 = _closure2_slot0;
                    var2 = {};
                    var1 = 'webauthn';
                    var2['mfaType'] = var1;
                    var1 = arg1;
                    var2['data'] = var1;
                    var1 = undefined;
                    var1 = var3.bind(var1)(var2);
                    return var1;
                };
                var5 = var4.bind(var5)(var3);
                var4 = var5.then;
                var3 = function() {
                    var3 = _closure2_slot4;
                    var2 = undefined;
                    var1 = true;
                    var1 = var3.bind(var2)(var1);
                    return var1;
                };
                var5 = var4.bind(var5)(var3);
                var4 = var5.catch;
                var3 = function(arg1) {
                    _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
 0:
                        var4 = arg1;
                        var5 = _closure1_slot0;
                        var3 = _closure1_slot2;
                        var1 = 9;
                        var3 = var3[var1];
                        var1 = undefined;
                        var3 = var5.bind(var1)(var3);
                        var3 = var3.HTTPResponseError;
                        var5 = var4 instanceof var3;
                        var3 = _closure2_slot2;
                        if(var5) { _fun0002_ip = 60; continue _fun0002 }
 48:
                        var4 = var4.message;
                        var4 = var3.bind(var1)(var4);
                        _fun0002_ip = 120; continue _fun0002;
 60:
                        var6 = _closure1_slot0;
                        var7 = _closure1_slot2;
                        var2 = 6;
                        var4 = var7[var2];
                        var4 = var6.bind(var1)(var4);
                        var5 = var4.intl;
                        var4 = var5.string;
                        var2 = var7[var2];
                        var2 = var6.bind(var1)(var2);
                        var2 = var2.t;
                        var2 = var2.xSCvBQ;
                        var2 = var4.bind(var5)(var2);
                        var2 = var3.bind(var1)(var2);
 120:
                        return var1;
                    }
                };
                var4 = var4.bind(var5)(var3);
                var3 = var4.finally;
                var2 = function() {
                    var3 = _closure2_slot1;
                    var2 = undefined;
                    var1 = false;
                    var1 = var3.bind(var2)(var1);
                    return var1;
                };
                var2 = var3.bind(var4)(var2);
                return var1;
            };
            var11 = var3.bind(var6)(var1, var2);
            var3 = _closure1_slot5;
            var2 = _closure1_slot1;
            var6 = _closure1_slot2;
            var1 = 10;
            var1 = var6[var1];
            var2 = var2.bind(var4)(var1);
            var1 = {};
            var9 = _closure1_slot0;
            var18 = 6;
            var14 = var6[var18];
            var14 = var9.bind(var4)(var14);
            var20 = var14.intl;
            var19 = var20.string;
            var14 = var6[var18];
            var14 = var9.bind(var4)(var14);
            var14 = var14.t;
            var14 = var14.saHocH;
            var14 = var19.bind(var20)(var14);
            var1['headerText'] = var14;
            var14 = var6[var18];
            var14 = var9.bind(var4)(var14);
            var20 = var14.intl;
            var19 = var20.string;
            var14 = var6[var18];
            var14 = var9.bind(var4)(var14);
            var14 = var14.t;
            var14 = var14.YpMrqK;
            var14 = var19.bind(var20)(var14);
            var1['subtitle'] = var14;
            var20 = _closure1_slot5;
            var14 = 11;
            var14 = var6[var14];
            var14 = var9.bind(var4)(var14);
            var19 = var14.KeyImage;
            var14 = {};
            var14 = var20.bind(var4)(var19, var14);
            var1['headerImage'] = var14;
            var6 = var6[var10];
            var9 = var9.bind(var4)(var6);
            var6 = var9.isAndroid;
            var6 = var6.bind(var9)();
            if(!var6) { _fun0001_ip = 559; continue _fun0001 }
 519:
            var14 = _closure1_slot5;
            var10 = _closure1_slot9;
            var9 = {};
            var9['authenticatorSelection'] = var17;
            var9['setAuthenticator'] = var16;
            var16 = var12;
            if(var12) { _fun0001_ip = 548; continue _fun0001 }
 545:
            var16 = var13;
 548:
            var9['inProgress'] = var16;
            var6 = var14.bind(var4)(var10, var9);
 559:
            var1['content'] = var6;
            var10 = _closure1_slot5;
            var9 = _closure1_slot1;
            var14 = _closure1_slot2;
            var6 = 12;
            var6 = var14[var6];
            var9 = var9.bind(var4)(var6);
            var6 = {};
            var16 = 'primary';
            var6['variant'] = var16;
            var17 = _closure1_slot0;
            var15 = var14[var18];
            var15 = var17.bind(var4)(var15);
            var16 = var15.intl;
            var15 = var16.string;
            var14 = var14[var18];
            var14 = var17.bind(var4)(var14);
            var14 = var14.t;
            var14 = var14.Xr3Ekp;
            var14 = var15.bind(var16)(var14);
            var6['text'] = var14;
            var14 = var12;
            if(var12) { _fun0001_ip = 660; continue _fun0001 }
 657:
            var14 = var13;
 660:
            var6['loading'] = var14;
            if(var12) { _fun0001_ip = 671; continue _fun0001 }
 668:
            var12 = var13;
 671:
            var6['disabled'] = var12;
            var6['onPress'] = var11;
            var6 = var10.bind(var4)(var9, var6);
            var1['submit'] = var6;
            var6 = {};
            var6['mfaChallenge'] = var8;
            var6['finish'] = var7;
            var1['screenProps'] = var6;
            var6 = 'webauthn';
            var1['mfaMethod'] = var6;
            var1['error'] = var5;
            var1 = var3.bind(var4)(var2, var1);
            return var1;
        }
    };
    var3['default'] = var4;
    var3['AuthenticatorOption'] = var2;
    return var1;
})();