// app/modules/app_database/managers/MobileAppDatabaseManager.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var6;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var2);
    var1 = 0;
    var2 = var6[var1];
    var1 = undefined;
    var2 = var5.bind(var1)(var2);
    var9 = var2.AppDatabaseManager;
    var2 = {};
    var7 = 'Channels';
    var2['name'] = var7;
    var7 = ['BACKGROUND_SYNC', 'CHANNEL_CREATE', 'CHANNEL_DELETE', 'CHANNEL_RECIPIENT_ADD', 'CHANNEL_RECIPIENT_REMOVE', 'CHANNEL_UPDATES', 'CONNECTION_OPEN', 'CONNECTION_OPEN_SUPPLEMENTAL', 'GUILD_CREATE', 'GUILD_DELETE'];
    var2['actions'] = var7;
    var7 = function require() {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 1;
        var2 = var2[var1];
        var1 = undefined;
        var1 = var3.bind(var1)(var2);
        var1 = var1.default;
        return var1;
    };
    var2['require'] = var7;
    var8 = new Array(16);
    var8[0] = var2;
    var2 = {};
    var7 = 'GuildBasicChannels';
    var2['name'] = var7;
    var7 = ['BACKGROUND_SYNC', 'CHANNEL_CREATE', 'CHANNEL_DELETE', 'CHANNEL_UPDATES', 'CONNECTION_OPEN', 'GUILD_CREATE', 'GUILD_DELETE', 'GUILD_MEMBER_UPDATE', 'GUILD_ROLE_UPDATE', 'GUILD_UPDATE', 'POST_CONNECTION_OPEN', 'WRITE_CACHES'];
    var2['actions'] = var7;
    var7 = function require() {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 2;
        var2 = var2[var1];
        var1 = undefined;
        var1 = var3.bind(var1)(var2);
        var1 = var1.default;
        return var1;
    };
    var2['require'] = var7;
    var8[1] = var2;
    var2 = {};
    var7 = 'GuildEmojis';
    var2['name'] = var7;
    var7 = ['BACKGROUND_SYNC', 'CONNECTION_OPEN', 'GUILD_CREATE', 'GUILD_DELETE', 'GUILD_EMOJIS_UPDATE', 'GUILD_UPDATE'];
    var2['actions'] = var7;
    var7 = function require() {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 3;
        var2 = var2[var1];
        var1 = undefined;
        var1 = var3.bind(var1)(var2);
        var1 = var1.default;
        return var1;
    };
    var2['require'] = var7;
    var8[2] = var2;
    var2 = {};
    var7 = 'Guilds';
    var2['name'] = var7;
    var7 = ['BACKGROUND_SYNC', 'CONNECTION_OPEN', 'GUILD_CREATE', 'GUILD_DELETE', 'GUILD_MEMBER_ADD', 'GUILD_MEMBER_UPDATE', 'GUILD_ROLE_CREATE', 'GUILD_ROLE_DELETE', 'GUILD_ROLE_UPDATE', 'GUILD_UPDATE'];
    var2['actions'] = var7;
    var7 = function require() {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 4;
        var2 = var2[var1];
        var1 = undefined;
        var1 = var3.bind(var1)(var2);
        var1 = var1.default;
        return var1;
    };
    var2['require'] = var7;
    var8[3] = var2;
    var2 = {};
    var7 = 'GuildsRequiringDeletedIdsSync';
    var2['name'] = var7;
    var7 = ['BACKGROUND_SYNC', 'CONNECTION_OPEN', 'GUILD_CREATE', 'DELETED_ENTITY_IDS'];
    var2['actions'] = var7;
    var7 = function require() {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 5;
        var2 = var2[var1];
        var1 = undefined;
        var1 = var3.bind(var1)(var2);
        var1 = var1.default;
        return var1;
    };
    var2['require'] = var7;
    var8[4] = var2;
    var2 = {};
    var7 = 'GuildsRequiringChannelSync';
    var2['name'] = var7;
    var7 = ['BACKGROUND_SYNC', 'CONNECTION_OPEN', 'GUILD_CREATE', 'CHANNEL_SYNC'];
    var2['actions'] = var7;
    var7 = function require() {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 6;
        var2 = var2[var1];
        var1 = undefined;
        var1 = var3.bind(var1)(var2);
        var1 = var1.default;
        return var1;
    };
    var2['require'] = var7;
    var8[5] = var2;
    var2 = {};
    var7 = 'GuildStickers';
    var2['name'] = var7;
    var7 = ['BACKGROUND_SYNC', 'CONNECTION_OPEN', 'GUILD_CREATE', 'GUILD_DELETE', 'GUILD_STICKERS_UPDATE', 'GUILD_UPDATE'];
    var2['actions'] = var7;
    var7 = function require() {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 7;
        var2 = var2[var1];
        var1 = undefined;
        var1 = var3.bind(var1)(var2);
        var1 = var1.default;
        return var1;
    };
    var2['require'] = var7;
    var8[6] = var2;
    var2 = {};
    var7 = 'GuildVersions';
    var2['name'] = var7;
    var7 = ['BACKGROUND_SYNC', 'CHANNEL_CREATE', 'CHANNEL_DELETE', 'CHANNEL_UPDATES', 'CONNECTION_OPEN', 'GUILD_CREATE', 'GUILD_DELETE', 'GUILD_EMOJIS_UPDATE', 'GUILD_ROLE_CREATE', 'GUILD_ROLE_DELETE', 'GUILD_ROLE_UPDATE', 'GUILD_STICKERS_UPDATE', 'GUILD_UPDATE'];
    var2['actions'] = var7;
    var7 = function require() {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 8;
        var2 = var2[var1];
        var1 = undefined;
        var1 = var3.bind(var1)(var2);
        var1 = var1.default;
        return var1;
    };
    var2['require'] = var7;
    var8[7] = var2;
    var2 = {};
    var7 = 'KvCacheVersion';
    var2['name'] = var7;
    var7 = ['CONNECTION_OPEN', 'WRITE_CACHES', 'BACKGROUND_SYNC'];
    var2['actions'] = var7;
    var7 = function require() {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 9;
        var2 = var2[var1];
        var1 = undefined;
        var1 = var3.bind(var1)(var2);
        var1 = var1.default;
        return var1;
    };
    var2['require'] = var7;
    var8[8] = var2;
    var2 = {};
    var7 = 'Messages';
    var2['name'] = var7;
    var7 = ['CHANNEL_DELETE', 'GUILD_DELETE', 'LOAD_MESSAGES_SUCCESS', 'MESSAGE_CREATE', 'MESSAGE_DELETE_BULK', 'MESSAGE_DELETE', 'MESSAGE_PREVIEWS_LOADED', 'MESSAGE_UPDATE'];
    var2['actions'] = var7;
    var7 = function require() {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 10;
        var2 = var2[var1];
        var1 = undefined;
        var1 = var3.bind(var1)(var2);
        var1 = var1.default;
        return var1;
    };
    var2['require'] = var7;
    var8[9] = var2;
    var2 = {};
    var7 = 'LowDiskTrim';
    var2['name'] = var7;
    var7 = ['POST_CONNECTION_OPEN'];
    var2['actions'] = var7;
    var7 = function require() {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 11;
        var2 = var2[var1];
        var1 = undefined;
        var1 = var3.bind(var1)(var2);
        var1 = var1.default;
        return var1;
    };
    var2['require'] = var7;
    var8[10] = var2;
    var2 = {};
    var7 = 'NonGuildVersions';
    var2['name'] = var7;
    var7 = ['CONNECTION_OPEN', 'BACKGROUND_SYNC'];
    var2['actions'] = var7;
    var7 = function require() {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 12;
        var2 = var2[var1];
        var1 = undefined;
        var1 = var3.bind(var1)(var2);
        var1 = var1.default;
        return var1;
    };
    var2['require'] = var7;
    var8[11] = var2;
    var2 = {};
    var7 = 'ReadStates';
    var2['name'] = var7;
    var7 = ['CONNECTION_OPEN', 'CHANNEL_PINS_ACK', 'MESSAGE_ACK', 'BACKGROUND_SYNC_FINISHED', 'WRITE_CACHES'];
    var2['actions'] = var7;
    var7 = function require() {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 13;
        var2 = var2[var1];
        var1 = undefined;
        var1 = var3.bind(var1)(var2);
        var1 = var1.default;
        return var1;
    };
    var2['require'] = var7;
    var8[12] = var2;
    var2 = {};
    var7 = 'UserSettingsProto';
    var2['name'] = var7;
    var7 = ['CONNECTION_OPEN', 'USER_SETTINGS_PROTO_UPDATE', 'USER_SETTINGS_PROTO_ENQUEUE_UPDATE', 'USER_SETTINGS_PROTO_UPDATE_EDIT_INFO'];
    var2['actions'] = var7;
    var7 = function require() {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 14;
        var2 = var2[var1];
        var1 = undefined;
        var1 = var3.bind(var1)(var2);
        var1 = var1.default;
        return var1;
    };
    var2['require'] = var7;
    var8[13] = var2;
    var2 = {};
    var7 = 'UserGuildSettings';
    var2['name'] = var7;
    var7 = ['CONNECTION_OPEN', 'USER_GUILD_SETTINGS_FULL_UPDATE'];
    var2['actions'] = var7;
    var7 = function require() {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 15;
        var2 = var2[var1];
        var1 = undefined;
        var1 = var3.bind(var1)(var2);
        var1 = var1.default;
        return var1;
    };
    var2['require'] = var7;
    var8[14] = var2;
    var2 = {};
    var7 = 'UserSearchItems';
    var2['name'] = var7;
    var7 = ['POST_CONNECTION_OPEN', 'WRITE_CACHES'];
    var2['actions'] = var7;
    var4 = function require() {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 16;
        var2 = var2[var1];
        var1 = undefined;
        var1 = var3.bind(var1)(var2);
        var1 = var1.default;
        return var1;
    };
    var2['require'] = var4;
    var8[15] = var2;
    var2 = var9.prototype;
    var4 = Object.create(var2, {constructor: {value: var9}});
    var12 = 'MobileAppDatabaseManager';
    var11 = new Array(0);
    var13 = var4;
    var10 = var8;
    var2 = new var13[var9](var12, var11, var10, var9);
    var2 = var2 instanceof Object ? var2 : var4;
    var4 = 17;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/app_database/managers/MobileAppDatabaseManager.tsx';
    var4 = var5.bind(var6)(var4);
    var3['default'] = var2;
    return var1;
})();