// app/modules/modals/native/useModalPanGesture.tsx
export default (function(argFoo, argBar, argBaz, _, __, argFre, argPlu) {
    report = argBar;
    zuuluu = argFre;
    tangon = argPlu;
    var _closure1_slot0 = report;
    entity = argBaz;
    var _closure1_slot1 = entity;
    var _closure1_slot2 = tangon;
    entity = global;
    option = entity.Object;
    golfie = option.defineProperty;
    oscard = {};
    entity = true;
    oscard['value'] = entity;
    entity = '__esModule';
    entity = golfie.bind(option)(zuuluu, entity, oscard);
    entity = {};
    oscard = "function useModalPanGestureTsx1({velocityY:velocityY}){const{translateY,thresholdTranslate,thresholdVelocity,withSpring,height,runOnJS,ModalActionCreators,onEnd}=this.__closure;const config={damping:15,mass:1,stiffness:250,overshootClamping:true,restSpeedThreshold:0.001,restDisplacementThreshold:0.001,velocity:velocityY};if(translateY.get()>=thresholdTranslate||velocityY>=thresholdVelocity){translateY.set(withSpring(height,config,'respect-motion-settings',function(){runOnJS(ModalActionCreators.pop)();}));}else{translateY.set(withSpring(0,config));}if(onEnd!=null){runOnJS(onEnd)();}}";
    entity['code'] = oscard;
    var _closure1_slot3 = entity;
    entity = {};
    oscard = 'function useModalPanGestureTsx2({translationY:translationY}){const{translateY,interpolate,start,maxTranslate,Extrapolate}=this.__closure;translateY.set(interpolate(start.get().y+translationY,[0,maxTranslate],[0,maxTranslate],Extrapolate.CLAMP));}';
    entity['code'] = oscard;
    var _closure1_slot4 = entity;
    entity = {};
    oscard = 'function useModalPanGestureTsx3(){const{onStart,runOnJS,start,translateY}=this.__closure;if(onStart!=null){runOnJS(onStart)();}start.set({y:translateY.get()});}';
    entity['code'] = oscard;
    var _closure1_slot5 = entity;
    entity = {};
    oscard = 'function useModalPanGestureTsx4(){const{runOnJS,ModalActionCreators}=this.__closure;runOnJS(ModalActionCreators.pop)();}';
    entity['code'] = oscard;
    var _closure1_slot6 = entity;
    entity = 4;
    tangon = tangon[entity];
    entity = undefined;
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/modals/native/useModalPanGesture.tsx';
    tangon = report.bind(oscard)(tangon);
    michal = function(argFoo) { // Original name: useModalPanGesture
        _fun00001: for(var _fun00002_ip = 0; ; ) switch(_fun00002_ip) {
 0:
            michal = argFoo;
            romeon = michal.thresholdVelocity;
            verify = undefined;
            if(!(romeon === verify)) { _fun00002_ip = 23; continue _fun00001 }
 17:
            romeon = 500;
 23:
            var _closure2_slot0 = romeon;
            report = michal.gestureEnabled;
            sizing = michal.maxTranslate;
            var _closure2_slot1 = sizing;
            foxtra = michal.thresholdTranslate;
            var _closure2_slot2 = foxtra;
            yankee = michal.height;
            var _closure2_slot3 = yankee;
            backup = michal.translateY;
            var _closure2_slot4 = backup;
            result = michal.onStart;
            var _closure2_slot5 = result;
            oscard = michal.onEnd;
            var _closure2_slot6 = oscard;
            var _closure2_slot7 = verify;
            option = _closure1_slot0;
            offset = _closure1_slot2;
            golfie = 0;
            michal = offset[golfie];
            kiloes = option.bind(verify)(michal);
            zuuluu = kiloes.useSharedValue;
            michal = {};
            michal['y'] = golfie;
            output = zuuluu.bind(kiloes)(michal);
            _closure2_slot7 = output;
            michal = 1;
            michal = offset[michal];
            michal = option.bind(verify)(michal);
            zuuluu = michal.Gesture;
            michal = zuuluu.Pan;
            zuuluu = michal.bind(zuuluu)();
            michal = zuuluu.enabled;
            report = michal.bind(zuuluu)(report);
            zuuluu = report.onStart;
            michal = function() { // Original name: x
                _fun00003: for(var _fun00004_ip = 0; ; ) switch(_fun00004_ip) {
 0:
                    michal = _closure2_slot5;
                    entity = null;
                    if(!(entity != michal)) { _fun00004_ip = 55; continue _fun00003 }
 13:
                    zuuluu = _closure1_slot0;
                    michal = _closure1_slot2;
                    entity = 0;
                    entity = michal[entity];
                    michal = undefined;
                    report = zuuluu.bind(michal)(entity);
                    zuuluu = report.runOnJS;
                    entity = _closure2_slot5;
                    entity = zuuluu.bind(report)(entity);
                    entity = entity.bind(michal)();
 55:
                    zuuluu = _closure2_slot7;
                    michal = zuuluu.set;
                    entity = {};
                    report = _closure2_slot4;
                    tangon = report.get;
                    tangon = tangon.bind(report)();
                    entity['y'] = tangon;
                    entity = michal.bind(zuuluu)(entity);
                    entity = undefined;
                    return entity;
                }
            };
            kiloes = {};
            kiloes['onStart'] = result;
            result = offset[golfie];
            result = option.bind(verify)(result);
            result = result.runOnJS;
            kiloes['runOnJS'] = result;
            kiloes['start'] = output;
            kiloes['translateY'] = backup;
            michal['__closure'] = kiloes;
            kiloes = 15847989720945.0;
            michal['__workletHash'] = kiloes;
            kiloes = _closure1_slot5;
            michal['__initData'] = kiloes;
            report = zuuluu.bind(report)(michal);
            zuuluu = report.onUpdate;
            michal = function(argFoo) { // Original name: O
                entity = argFoo;
                golfie = entity.translationY;
                tangon = _closure2_slot4;
                zuuluu = tangon.set;
                offset = _closure1_slot0;
                yankee = _closure1_slot2;
                michal = 0;
                oscard = yankee[michal];
                entity = undefined;
                verify = offset.bind(entity)(oscard);
                option = verify.interpolate;
                romeon = _closure2_slot7;
                oscard = romeon.get;
                oscard = oscard.bind(romeon)();
                oscard = oscard.y;
                golfie = oscard + golfie;
                romeon = _closure2_slot1;
                oscard = [0];
                oscard[1] = romeon;
                report = [0];
                report[1] = romeon;
                michal = yankee[michal];
                michal = offset.bind(entity)(michal);
                michal = michal.Extrapolate;
                foxtra = michal.CLAMP;
                output = verify;
                sizing = golfie;
                kiloes = oscard;
                backup = report;
                michal = output[option](sizing, kiloes, backup, foxtra, romeon);
                michal = zuuluu.bind(tangon)(michal);
                return entity;
            };
            kiloes = {};
            kiloes['translateY'] = backup;
            result = offset[golfie];
            result = option.bind(verify)(result);
            result = result.interpolate;
            kiloes['interpolate'] = result;
            kiloes['start'] = output;
            kiloes['maxTranslate'] = sizing;
            sizing = offset[golfie];
            sizing = option.bind(verify)(sizing);
            sizing = sizing.Extrapolate;
            kiloes['Extrapolate'] = sizing;
            michal['__closure'] = kiloes;
            kiloes = 6809176231356.0;
            michal['__workletHash'] = kiloes;
            kiloes = _closure1_slot4;
            michal['__initData'] = kiloes;
            zuuluu = zuuluu.bind(report)(michal);
            michal = zuuluu.onEnd;
            entity = function(argFoo) { // Original name: Y
                _fun00005: for(var _fun00006_ip = 0; ; ) switch(_fun00006_ip) {
 0:
                    entity = argFoo;
                    zuuluu = entity.velocityY;
                    verify = {'damping': 15, 'mass': 1, 'stiffness': 250, 'overshootClamping': true, 'restSpeedThreshold': 0.001, 'restDisplacementThreshold': 0.001};
                    verify['velocity'] = zuuluu;
                    tangon = _closure2_slot4;
                    michal = tangon.get;
                    tangon = michal.bind(tangon)();
                    michal = _closure2_slot2;
                    if(!(!(tangon >= michal))) { _fun00006_ip = 117; continue _fun00005 }
 52:
                    michal = _closure2_slot0;
                    if(!(!(zuuluu >= michal))) { _fun00006_ip = 117; continue _fun00005 }
 60:
                    tangon = _closure2_slot4;
                    zuuluu = tangon.set;
                    oscard = _closure1_slot0;
                    report = _closure1_slot2;
                    michal = 2;
                    report = report[michal];
                    michal = undefined;
                    oscard = oscard.bind(michal)(report);
                    report = oscard.withSpring;
                    michal = 0;
                    michal = report.bind(oscard)(michal, verify);
                    michal = zuuluu.bind(tangon)(michal);
                    _fun00006_ip = 271; continue _fun00005;
 117:
                    tangon = _closure2_slot4;
                    zuuluu = tangon.set;
                    romeon = _closure1_slot0;
                    backup = _closure1_slot2;
                    report = 2;
                    report = backup[report];
                    foxtra = undefined;
                    option = romeon.bind(foxtra)(report);
                    golfie = option.withSpring;
                    oscard = _closure2_slot3;
                    report = function() { // Original name: n
                        tangon = _closure1_slot0;
                        oscard = _closure1_slot2;
                        entity = 0;
                        zuuluu = oscard[entity];
                        entity = undefined;
                        tangon = tangon.bind(entity)(zuuluu);
                        zuuluu = tangon.runOnJS;
                        report = _closure1_slot1;
                        michal = 3;
                        michal = oscard[michal];
                        michal = report.bind(entity)(michal);
                        michal = michal.pop;
                        michal = zuuluu.bind(tangon)(michal);
                        michal = michal.bind(entity)();
                        return entity;
                    };
                    offset = {};
                    yankee = 0;
                    yankee = backup[yankee];
                    yankee = romeon.bind(foxtra)(yankee);
                    yankee = yankee.runOnJS;
                    offset['runOnJS'] = yankee;
                    romeon = _closure1_slot1;
                    yankee = 3;
                    yankee = backup[yankee];
                    yankee = romeon.bind(foxtra)(yankee);
                    offset['ModalActionCreators'] = yankee;
                    report['__closure'] = offset;
                    offset = 14223008059411.0;
                    report['__workletHash'] = offset;
                    michal = _closure1_slot6;
                    report['__initData'] = michal;
                    sizing = 'respect-motion-settings';
                    echoed = option;
                    result = oscard;
                    output = verify;
                    kiloes = report;
                    michal = echoed[golfie](result, output, sizing, kiloes, backup);
                    michal = zuuluu.bind(tangon)(michal);
 271:
                    zuuluu = _closure2_slot6;
                    michal = null;
                    if(!(michal != zuuluu)) { _fun00006_ip = 323; continue _fun00005 }
 281:
                    tangon = _closure1_slot0;
                    zuuluu = _closure1_slot2;
                    michal = 0;
                    zuuluu = zuuluu[michal];
                    michal = undefined;
                    tangon = tangon.bind(michal)(zuuluu);
                    zuuluu = tangon.runOnJS;
                    entity = _closure2_slot6;
                    entity = zuuluu.bind(tangon)(entity);
                    entity = entity.bind(michal)();
 323:
                    entity = undefined;
                    return entity;
                }
            };
            report = {};
            report['translateY'] = backup;
            report['thresholdTranslate'] = foxtra;
            report['thresholdVelocity'] = romeon;
            romeon = 2;
            romeon = offset[romeon];
            romeon = option.bind(verify)(romeon);
            romeon = romeon.withSpring;
            report['withSpring'] = romeon;
            report['height'] = yankee;
            golfie = offset[golfie];
            golfie = option.bind(verify)(golfie);
            golfie = golfie.runOnJS;
            report['runOnJS'] = golfie;
            option = _closure1_slot1;
            golfie = 3;
            golfie = offset[golfie];
            golfie = option.bind(verify)(golfie);
            report['ModalActionCreators'] = golfie;
            report['onEnd'] = oscard;
            entity['__closure'] = report;
            report = 14726748946839.0;
            entity['__workletHash'] = report;
            tangon = _closure1_slot3;
            entity['__initData'] = tangon;
            zuuluu = michal.bind(zuuluu)(entity);
            michal = zuuluu.failOffsetY;
            entity = -0.01;
            zuuluu = michal.bind(zuuluu)(entity);
            michal = zuuluu.activeOffsetY;
            entity = new Array(2);
            tangon = -5;
            entity[0] = tangon;
            tangon = 15;
            entity[1] = tangon;
            entity = michal.bind(zuuluu)(entity);
            return entity;
        }
    };
    zuuluu['default'] = michal;
    return entity;
})();