// app/modules/activities/panel/native/ActivityPanelStateContext.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var6 = require;
    var3 = exports;
    var7 = dependencyMap;
    var1 = global;
    var8 = var1.Object;
    var5 = var8.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var5.bind(var8)(var3, var1, var2);
    var1 = 0;
    var5 = var7[var1];
    var2 = metroImportAll;
    var1 = undefined;
    var5 = var2.bind(var1)(var5);
    var2 = {};
    var8 = 1;
    var8 = var7[var8];
    var8 = var6.bind(var1)(var8);
    var8 = var8.ActivityPanelModes;
    var8 = var8.PANEL;
    var2['mode'] = var8;
    var8 = function setMode() {
        var1 = global;
        var3 = var1.Error;
        var1 = var3.prototype;
        var2 = Object.create(var1, {constructor: {value: var3}});
        var4 = 'ActivityPanelStateContextType.Provider.setMode: not called within a context provider';
        var5 = var2;
        var1 = new var5[var3](var4, var3);
        var1 = var1 instanceof Object ? var1 : var2;
        throw var1;
    };
    var2['setMode'] = var8;
    var8 = {'width': 9, 'height': 16, 'isLandscape': false, 'isWindowLandscape': false};
    var2['wrapperDimensions'] = var8;
    var8 = 2;
    var9 = var7[var8];
    var11 = var6.bind(var1)(var9);
    var10 = var11.createFakeSharedValue;
    var9 = {'x': 4294967295, 'y': 4294967295};
    var9 = var10.bind(var11)(var9);
    var2['pipState'] = var9;
    var9 = var7[var8];
    var11 = var6.bind(var1)(var9);
    var10 = var11.createFakeSharedValue;
    var9 = {'top': 0, 'bottom': 0};
    var9 = var10.bind(var11)(var9);
    var2['pipAvoidanceSpecs'] = var9;
    var8 = var7[var8];
    var10 = var6.bind(var1)(var8);
    var9 = var10.createFakeSharedValue;
    var8 = {'x': 0, 'y': 0, 'gestureActive': false};
    var8 = var9.bind(var10)(var8);
    var2['wrapperOffset'] = var8;
    var4 = function useActivityWebViewLock() {
        var1 = true;
        return var1;
    };
    var2['useActivityWebViewLock'] = var4;
    var4 = var5.createContext;
    var4 = var4.bind(var5)(var2);
    var5 = 3;
    var5 = var7[var5];
    var7 = var6.bind(var1)(var5);
    var6 = var7.fileFinishedImporting;
    var5 = 'modules/activities/panel/native/ActivityPanelStateContext.tsx';
    var5 = var6.bind(var7)(var5);
    var3['default'] = var4;
    var3['activityPanelStateContextDefault'] = var2;
    return var1;
})();