// app/modules/guild_member_verification/native/MemberVerificationAlertActionCreators.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var7 = require;
    var5 = metroImportAll;
    var3 = exports;
    var8 = dependencyMap;
    var _closure1_slot0 = var7;
    var1 = metroImportDefault;
    var _closure1_slot1 = var1;
    var _closure1_slot2 = var5;
    var _closure1_slot3 = var8;
    var1 = global;
    var9 = var1.Object;
    var6 = var9.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var6.bind(var9)(var3, var1, var4);
    var1 = 0;
    var4 = var8[var1];
    var1 = undefined;
    var4 = var5.bind(var1)(var4);
    var4 = 1;
    var4 = var8[var4];
    var4 = var7.bind(var1)(var4);
    var4 = var4.jsx;
    var _closure1_slot4 = var4;
    var5 = function openMemberVerificationCancelPendingAlert(arg1) {
        var1 = arg1;
        var2 = var1.guildId;
        var _closure2_slot0 = var2;
        var2 = var1.confirmText;
        var _closure2_slot1 = var2;
        var2 = var1.subtitleText;
        var _closure2_slot2 = var2;
        var1 = var1.onClose;
        var _closure2_slot3 = var1;
        var6 = _closure1_slot2;
        var4 = _closure1_slot3;
        var1 = 2;
        var3 = var4[var1];
        var1 = undefined;
        var6 = var6.bind(var1)(var3);
        var3 = var6.dismissGlobalKeyboard;
        var3 = var3.bind(var6)();
        var3 = _closure1_slot1;
        var2 = 3;
        var2 = var4[var2];
        var4 = var3.bind(var1)(var2);
        var3 = var4.openLazy;
        var2 = {};
        var5 = function importer() {
            var3 = _closure1_slot0;
            var1 = _closure1_slot3;
            var2 = 5;
            var2 = var1[var2];
            var4 = undefined;
            var3 = var3.bind(var4)(var2);
            var2 = 7;
            var2 = var1[var2];
            var1 = var1.paths;
            var3 = var3.bind(var4)(var2, var1);
            var2 = var3.then;
            var1 = function(arg1) {
                var2 = arg1;
                var2 = var2.default;
                var _closure4_slot0 = var2;
                var1 = function(arg1) {
                    var4 = _closure1_slot4;
                    var3 = _closure4_slot0;
                    var2 = {};
                    var8 = arg1;
                    var9 = var2;
                    var1 = copyDataProperties(var9, var8);
                    var7 = _closure2_slot0;
                    var6 = 'guildId';
                    var2[var6] = var7;
                    var7 = _closure2_slot1;
                    var6 = 'confirmText';
                    var2[var6] = var7;
                    var7 = _closure2_slot2;
                    var6 = 'subtitleText';
                    var2[var6] = var7;
                    var6 = _closure1_slot6;
                    var5 = _closure2_slot3;
                    var1 = undefined;
                    var6 = var6.bind(var1)(var5);
                    var5 = 'onClose';
                    var2[var5] = var6;
                    var1 = var4.bind(var1)(var3, var2);
                    return var1;
                };
                return var1;
            };
            var1 = var2.bind(var3)(var1);
            return var1;
        };
        var2['importer'] = var5;
        var2 = var3.bind(var4)(var2);
        return var1;
    };
    var _closure1_slot5 = var5;
    var4 = function closeMemberVerificationAlert(arg1) {
        var2 = arg1;
        var _closure2_slot0 = var2;
        var1 = function() {
            _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
 0:
                var3 = _closure1_slot1;
                var2 = _closure1_slot3;
                var1 = 3;
                var2 = var2[var1];
                var1 = undefined;
                var3 = var3.bind(var1)(var2);
                var2 = var3.close;
                var2 = var2.bind(var3)();
                var4 = _closure2_slot0;
                var3 = null;
                if(!(var3 != var4)) { _fun0001_ip = 56; continue _fun0001 }
 48:
                var2 = _closure2_slot0;
                var2 = var2.bind(var1)();
 56:
                return var1;
            }
        };
        return var1;
    };
    var _closure1_slot6 = var4;
    var6 = 13;
    var6 = var8[var6];
    var8 = var7.bind(var1)(var6);
    var7 = var8.fileFinishedImporting;
    var6 = 'modules/guild_member_verification/native/MemberVerificationAlertActionCreators.tsx';
    var6 = var7.bind(var8)(var6);
    var6 = function(arg1, arg2) {
        var1 = arg1;
        var _closure2_slot0 = var1;
        var1 = arg2;
        var _closure2_slot1 = var1;
        var6 = _closure1_slot2;
        var4 = _closure1_slot3;
        var1 = 2;
        var3 = var4[var1];
        var1 = undefined;
        var6 = var6.bind(var1)(var3);
        var3 = var6.dismissGlobalKeyboard;
        var3 = var3.bind(var6)();
        var3 = _closure1_slot1;
        var2 = 3;
        var2 = var4[var2];
        var4 = var3.bind(var1)(var2);
        var3 = var4.openLazy;
        var2 = {};
        var5 = function importer() {
            var3 = _closure1_slot0;
            var1 = _closure1_slot3;
            var2 = 5;
            var2 = var1[var2];
            var4 = undefined;
            var3 = var3.bind(var4)(var2);
            var2 = 4;
            var2 = var1[var2];
            var1 = var1.paths;
            var3 = var3.bind(var4)(var2, var1);
            var2 = var3.then;
            var1 = function(arg1) {
                var2 = arg1;
                var2 = var2.default;
                var _closure4_slot0 = var2;
                var1 = function(arg1) {
                    var4 = _closure1_slot4;
                    var3 = _closure4_slot0;
                    var2 = {};
                    var7 = arg1;
                    var8 = var2;
                    var1 = copyDataProperties(var8, var7);
                    var6 = _closure2_slot0;
                    var5 = 'guildId';
                    var2[var5] = var6;
                    var5 = _closure2_slot1;
                    var1 = 'handleConfirmAndAck';
                    var2[var1] = var5;
                    var1 = undefined;
                    var1 = var4.bind(var1)(var3, var2);
                    return var1;
                };
                return var1;
            };
            var1 = var2.bind(var3)(var1);
            return var1;
        };
        var2['importer'] = var5;
        var2 = var3.bind(var4)(var2);
        return var1;
    };
    var3['openMemberVerificationSuccessAlert'] = var6;
    var6 = function(arg1, arg2) {
        var1 = arg1;
        var _closure2_slot0 = var1;
        var1 = arg2;
        var _closure2_slot1 = var1;
        var6 = _closure1_slot2;
        var4 = _closure1_slot3;
        var1 = 2;
        var3 = var4[var1];
        var1 = undefined;
        var6 = var6.bind(var1)(var3);
        var3 = var6.dismissGlobalKeyboard;
        var3 = var3.bind(var6)();
        var3 = _closure1_slot1;
        var2 = 3;
        var2 = var4[var2];
        var4 = var3.bind(var1)(var2);
        var3 = var4.openLazy;
        var2 = {};
        var5 = function importer() {
            var3 = _closure1_slot0;
            var1 = _closure1_slot3;
            var2 = 5;
            var2 = var1[var2];
            var4 = undefined;
            var3 = var3.bind(var4)(var2);
            var2 = 6;
            var2 = var1[var2];
            var1 = var1.paths;
            var3 = var3.bind(var4)(var2, var1);
            var2 = var3.then;
            var1 = function(arg1) {
                var2 = arg1;
                var2 = var2.default;
                var _closure4_slot0 = var2;
                var1 = function(arg1) {
                    var4 = _closure1_slot4;
                    var3 = _closure4_slot0;
                    var2 = {};
                    var8 = arg1;
                    var9 = var2;
                    var1 = copyDataProperties(var9, var8);
                    var7 = _closure2_slot0;
                    var6 = 'guildId';
                    var2[var6] = var7;
                    var6 = _closure1_slot6;
                    var5 = _closure2_slot1;
                    var1 = undefined;
                    var6 = var6.bind(var1)(var5);
                    var5 = 'onClose';
                    var2[var5] = var6;
                    var1 = var4.bind(var1)(var3, var2);
                    return var1;
                };
                return var1;
            };
            var1 = var2.bind(var3)(var1);
            return var1;
        };
        var2['importer'] = var5;
        var2 = var3.bind(var4)(var2);
        return var1;
    };
    var3['openMemberVerificationPendingAlert'] = var6;
    var3['openMemberVerificationCancelPendingAlert'] = var5;
    var5 = function(arg1) {
        _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
 0:
            var1 = arg1;
            var2 = var1.guildId;
            var _closure2_slot0 = var2;
            var3 = var1.canWithdraw;
            var6 = var1.onClose;
            var _closure2_slot1 = var6;
            var1 = undefined;
            var _closure2_slot3 = var1;
            var4 = _closure1_slot6;
            var7 = var4.bind(var1)(var6);
            var _closure2_slot2 = var7;
            var6 = _closure1_slot4;
            var8 = _closure1_slot0;
            var9 = _closure1_slot3;
            var4 = 8;
            var4 = var9[var4];
            var4 = var8.bind(var1)(var4);
            var4 = var4.Button;
            if(var3) { _fun0002_ip = 152; continue _fun0002 }
 85:
            var3 = {};
            var11 = _closure1_slot0;
            var12 = _closure1_slot3;
            var8 = 9;
            var9 = var12[var8];
            var9 = var11.bind(var1)(var9);
            var10 = var9.intl;
            var9 = var10.string;
            var8 = var12[var8];
            var8 = var11.bind(var1)(var8);
            var8 = var8.t;
            var8 = var8.BddRzc;
            var8 = var9.bind(var10)(var8);
            var3['text'] = var8;
            var3['onPress'] = var7;
            _fun0002_ip = 239; continue _fun0002;
 152:
            var7 = {};
            var11 = _closure1_slot0;
            var12 = _closure1_slot3;
            var8 = 9;
            var9 = var12[var8];
            var9 = var11.bind(var1)(var9);
            var10 = var9.intl;
            var9 = var10.string;
            var8 = var12[var8];
            var8 = var11.bind(var1)(var8);
            var8 = var8.t;
            var8 = var8.g9tK0t;
            var8 = var9.bind(var10)(var8);
            var7['text'] = var8;
            var8 = 'destructive';
            var7['variant'] = var8;
            var8 = function onPress() {
                var2 = _closure2_slot2;
                var1 = undefined;
                var2 = var2.bind(var1)();
                var3 = _closure1_slot5;
                var2 = {};
                var4 = _closure2_slot0;
                var2['guildId'] = var4;
                var2 = var3.bind(var1)(var2);
                return var1;
            };
            var7['onPress'] = var8;
            var3 = var7;
 239:
            var3 = var6.bind(var1)(var4, var3);
            _closure2_slot3 = var3;
            var6 = _closure1_slot2;
            var4 = _closure1_slot3;
            var3 = 2;
            var3 = var4[var3];
            var6 = var6.bind(var1)(var3);
            var3 = var6.dismissGlobalKeyboard;
            var3 = var3.bind(var6)();
            var3 = _closure1_slot1;
            var2 = 3;
            var2 = var4[var2];
            var4 = var3.bind(var1)(var2);
            var3 = var4.openLazy;
            var2 = {};
            var5 = function importer() {
                var3 = _closure1_slot0;
                var1 = _closure1_slot3;
                var2 = 5;
                var2 = var1[var2];
                var4 = undefined;
                var3 = var3.bind(var4)(var2);
                var2 = 10;
                var2 = var1[var2];
                var1 = var1.paths;
                var3 = var3.bind(var4)(var2, var1);
                var2 = var3.then;
                var1 = function(arg1) {
                    var2 = arg1;
                    var2 = var2.default;
                    var _closure4_slot0 = var2;
                    var1 = function(arg1) {
                        var4 = _closure1_slot4;
                        var3 = _closure4_slot0;
                        var2 = {};
                        var8 = arg1;
                        var9 = var2;
                        var5 = copyDataProperties(var9, var8);
                        var7 = _closure2_slot0;
                        var6 = 'guildId';
                        var2[var6] = var7;
                        var7 = _closure1_slot6;
                        var6 = _closure2_slot1;
                        var1 = undefined;
                        var7 = var7.bind(var1)(var6);
                        var6 = 'onClose';
                        var2[var6] = var7;
                        var6 = _closure2_slot3;
                        var5 = 'secondaryButton';
                        var2[var5] = var6;
                        var1 = var4.bind(var1)(var3, var2);
                        return var1;
                    };
                    return var1;
                };
                var1 = var2.bind(var3)(var1);
                return var1;
            };
            var2['importer'] = var5;
            var2 = var3.bind(var4)(var2);
            return var1;
        }
    };
    var3['openMemberVerificationRejectedAlert'] = var5;
    var5 = function() {
        var5 = _closure1_slot2;
        var4 = _closure1_slot3;
        var1 = 2;
        var3 = var4[var1];
        var1 = undefined;
        var5 = var5.bind(var1)(var3);
        var3 = var5.dismissGlobalKeyboard;
        var3 = var3.bind(var5)();
        var3 = _closure1_slot1;
        var2 = 3;
        var2 = var4[var2];
        var4 = var3.bind(var1)(var2);
        var3 = var4.openLazy;
        var2 = {};
        var5 = function importer() {
            var3 = _closure1_slot0;
            var1 = _closure1_slot3;
            var2 = 5;
            var2 = var1[var2];
            var4 = undefined;
            var3 = var3.bind(var4)(var2);
            var2 = 11;
            var2 = var1[var2];
            var1 = var1.paths;
            var3 = var3.bind(var4)(var2, var1);
            var2 = var3.then;
            var1 = function(arg1) {
                var2 = arg1;
                var2 = var2.default;
                var _closure4_slot0 = var2;
                var1 = function(arg1) {
                    var4 = _closure1_slot4;
                    var3 = _closure4_slot0;
                    var2 = {};
                    var5 = arg1;
                    var6 = var2;
                    var1 = copyDataProperties(var6, var5);
                    var1 = undefined;
                    var1 = var4.bind(var1)(var3, var2);
                    return var1;
                };
                return var1;
            };
            var1 = var2.bind(var3)(var1);
            return var1;
        };
        var2['importer'] = var5;
        var2 = var3.bind(var4)(var2);
        return var1;
    };
    var3['openMemberVerificationUpdateAlert'] = var5;
    var3['closeMemberVerificationAlert'] = var4;
    var2 = function(arg1, arg2) {
        var1 = arg1;
        var _closure2_slot0 = var1;
        var1 = arg2;
        var _closure2_slot1 = var1;
        var6 = _closure1_slot2;
        var4 = _closure1_slot3;
        var1 = 2;
        var3 = var4[var1];
        var1 = undefined;
        var6 = var6.bind(var1)(var3);
        var3 = var6.dismissGlobalKeyboard;
        var3 = var3.bind(var6)();
        var3 = _closure1_slot1;
        var2 = 3;
        var2 = var4[var2];
        var4 = var3.bind(var1)(var2);
        var3 = var4.openLazy;
        var2 = {};
        var5 = function importer() {
            var3 = _closure1_slot0;
            var1 = _closure1_slot3;
            var2 = 5;
            var2 = var1[var2];
            var4 = undefined;
            var3 = var3.bind(var4)(var2);
            var2 = 12;
            var2 = var1[var2];
            var1 = var1.paths;
            var3 = var3.bind(var4)(var2, var1);
            var2 = var3.then;
            var1 = function(arg1) {
                var2 = arg1;
                var2 = var2.default;
                var _closure4_slot0 = var2;
                var1 = function(arg1) {
                    var4 = _closure1_slot4;
                    var3 = _closure4_slot0;
                    var2 = {};
                    var8 = arg1;
                    var9 = var2;
                    var1 = copyDataProperties(var9, var8);
                    var7 = _closure2_slot0;
                    var6 = 'guildId';
                    var2[var6] = var7;
                    var6 = _closure1_slot6;
                    var5 = _closure2_slot1;
                    var1 = undefined;
                    var6 = var6.bind(var1)(var5);
                    var5 = 'onClose';
                    var2[var5] = var6;
                    var1 = var4.bind(var1)(var3, var2);
                    return var1;
                };
                return var1;
            };
            var1 = var2.bind(var3)(var1);
            return var1;
        };
        var2['importer'] = var5;
        var2 = var3.bind(var4)(var2);
        return var1;
    };
    var3['openMemberVerificationIncompleteAlert'] = var2;
    return var1;
})();