// app/modules/channel_text_area/native/ChannelAutocompleteConstants.tsx
export default (function(_, argBar, __, ___, ____, argFre, argPlu) {
    zuuluu = argFre;
    entity = global;
    report = entity.Object;
    tangon = report.defineProperty;
    michal = {};
    entity = true;
    michal['value'] = entity;
    entity = '__esModule';
    entity = tangon.bind(report)(zuuluu, entity, michal);
    michal = {};
    entity = 'MENTIONS';
    michal['MENTIONS'] = entity;
    entity = 'CHANNELS';
    michal['CHANNELS'] = entity;
    entity = 'EMOJIS_AND_STICKERS';
    michal['EMOJIS_AND_STICKERS'] = entity;
    entity = 'SLASHES';
    michal['SLASHES'] = entity;
    entity = 'SLASHES_DISCOVERY';
    michal['SLASHES_DISCOVERY'] = entity;
    entity = 'CHOICES';
    michal['CHOICES'] = entity;
    tangon = argPlu;
    entity = 0;
    report = tangon[entity];
    tangon = argBar;
    entity = undefined;
    oscard = tangon.bind(entity)(report);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/channel_text_area/native/ChannelAutocompleteConstants.tsx';
    tangon = report.bind(oscard)(tangon);
    zuuluu['AutocompleteTypes'] = michal;
    return entity;
})();