// app/modules/media_engine/AudioEffectsExperiment.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var1 = global;
    var7 = var1.Object;
    var4 = var7.defineProperty;
    var2 = {};
    var11 = true;
    var2['value'] = var11;
    var1 = '__esModule';
    var1 = var4.bind(var7)(var3, var1, var2);
    var10 = {};
    var1 = false;
    var10['probeAudioEffects'] = var1;
    var1 = 0;
    var2 = var6[var1];
    var1 = undefined;
    var7 = var5.bind(var1)(var2);
    var4 = var7.createApexExperiment;
    var2 = {'name': '2026-03-audio-effects-probe', 'kind': 'user'};
    var2['defaultConfig'] = var10;
    var8 = {};
    var9 = {};
    var14 = var9;
    var13 = var10;
    var10 = copyDataProperties(var14, var13);
    var10 = 'probeAudioEffects';
    var9[var10] = var11;
    var8[1] = var9;
    var2['variations'] = var8;
    var2 = var4.bind(var7)(var2);
    var4 = 1;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/media_engine/AudioEffectsExperiment.tsx';
    var4 = var5.bind(var6)(var4);
    var3['default'] = var2;
    return var1;
})();