// app/modules/media_engine/NativeScreenSharePickerExperiment.tsx
export default (function(_, argBar, __, ___, ____, argFred, argPlugh) {
    report = argBar;
    zulu = argFred;
    oscar = argPlugh;
    entity = global;
    golf = entity.Object;
    tango = golf.defineProperty;
    mike = {};
    entity = true;
    mike['value'] = entity;
    entity = '__esModule';
    entity = tango.bind(golf)(zulu, entity, mike);
    entity = 0;
    mike = oscar[entity];
    entity = undefined;
    options = report.bind(entity)(mike);
    golf = options.createExperiment;
    mike = {'kind': 'user', 'id': '2024-07_native_screen_share_picker', 'label': 'Use system picker for screen sharing'};
    tango = {'enableSystemPicker': false, 'useSystemPickerInModalByDefault': false};
    mike['defaultConfig'] = tango;
    offset = {'id': 1, 'label': 'Enable system picker'};
    tango = 1;
    verify = {'enableSystemPicker': true, 'useSystemPickerInModalByDefault': true};
    offset['config'] = verify;
    verify = new Array(2);
    verify[0] = offset;
    offset = {'id': 2, 'label': 'Enable system picker behind pref gate'};
    yankee = {'enableSystemPicker': true, 'useSystemPickerInModalByDefault': false};
    offset['config'] = yankee;
    verify[1] = offset;
    mike['treatments'] = verify;
    mike = golf.bind(options)(mike);
    tango = oscar[tango];
    oscar = report.bind(entity)(tango);
    report = oscar.fileFinishedImporting;
    tango = 'modules/media_engine/NativeScreenSharePickerExperiment.tsx';
    tango = report.bind(oscar)(tango);
    zulu['default'] = mike;
    return entity;
})();