// app/modules/media_engine/NvencNewPresets.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var10 = 0;
    var4 = var6[var10];
    var1 = undefined;
    var8 = var5.bind(var1)(var4);
    var7 = var8.createApexExperiment;
    var4 = {'name': '2026-01-nvenc-new-presets', 'kind': 'user'};
    var9 = {};
    var9['vbvBufferSize'] = var10;
    var4['defaultConfig'] = var9;
    var9 = {};
    var10 = {};
    var11 = 250;
    var10['vbvBufferSize'] = var11;
    var9[1] = var10;
    var10 = {};
    var11 = 125;
    var10['vbvBufferSize'] = var11;
    var9[2] = var10;
    var10 = {};
    var11 = 75;
    var10['vbvBufferSize'] = var11;
    var9[3] = var10;
    var4['variations'] = var9;
    var4 = var7.bind(var8)(var4);
    var _closure1_slot0 = var4;
    var4 = 1;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/media_engine/NvencNewPresets.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function getNvEncNewPresets(arg1) {
        var3 = _closure1_slot0;
        var2 = var3.getConfig;
        var1 = {};
        var4 = arg1;
        var1['location'] = var4;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var3['getNvEncNewPresets'] = var2;
    return var1;
})();