// app/modules/media_engine/SidechainCompressionExperiment.tsx
export default (function(_, argBar, __, ___, ____, argFre, argPlu) {
    report = argBar;
    zuuluu = argFre;
    oscard = argPlu;
    entity = global;
    golfie = entity.Object;
    tangon = golfie.defineProperty;
    michal = {};
    entity = true;
    michal['value'] = entity;
    entity = '__esModule';
    entity = tangon.bind(golfie)(zuuluu, entity, michal);
    entity = 0;
    michal = oscard[entity];
    entity = undefined;
    option = report.bind(entity)(michal);
    golfie = option.createExperiment;
    michal = {'kind': 'user', 'id': '2024-07_sidechain_compression', 'label': 'Test sidechain compression'};
    tangon = {'sidechainAvailable': false, 'sidechainEnabled': false};
    michal['defaultConfig'] = tangon;
    offset = {'id': 1, 'label': 'Sidechain Compression available, default enabled'};
    tangon = 1;
    verify = {'sidechainAvailable': true, 'sidechainEnabled': true};
    offset['config'] = verify;
    verify = new Array(2);
    verify[0] = offset;
    offset = {'id': 2, 'label': 'Sidechain Compression avialable, default disabled'};
    yankee = {'sidechainAvailable': true, 'sidechainEnabled': false};
    offset['config'] = yankee;
    verify[1] = offset;
    michal['treatments'] = verify;
    michal = golfie.bind(option)(michal);
    tangon = oscard[tangon];
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/media_engine/SidechainCompressionExperiment.tsx';
    tangon = report.bind(oscard)(tangon);
    zuuluu['default'] = michal;
    return entity;
})();