// app/modules/media_engine/VoiceFiltersPreProcessMuteExperiment.tsx
export default (function(native1, native2, native3, native4, native5, native6, native7) {
    var5 = native2;
    var3 = native6;
    var6 = native7;
    var1 = global;
    var7 = var1.Object;
    var4 = var7.defineProperty;
    var2 = {};
    var11 = true;
    var2['value'] = var11;
    var1 = '__esModule';
    var1 = var4.bind(var7)(var3, var1, var2);
    var1 = 0;
    var2 = var6[var1];
    var1 = undefined;
    var8 = var5.bind(var1)(var2);
    var7 = var8.createExperiment;
    var2 = {'kind': 'user', 'id': '2025-02_voice_filters_pre_process_mute', 'label': 'Voice Filters Pre Process Mute'};
    var4 = {};
    var9 = false;
    var4['voiceFiltersPreProcessMute'] = var9;
    var2['defaultConfig'] = var4;
    var10 = {'id': 1, 'label': 'Mute before processing when voice filters is enabled'};
    var4 = 1;
    var9 = {};
    var9['voiceFiltersPreProcessMute'] = var11;
    var10['config'] = var9;
    var9 = new Array(1);
    var9[0] = var10;
    var2['treatments'] = var9;
    var2 = var7.bind(var8)(var2);
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/media_engine/VoiceFiltersPreProcessMuteExperiment.tsx';
    var4 = var5.bind(var6)(var4);
    var3['default'] = var2;
    return var1;
})();