// app/modules/main_tabs_v2/native/settings/definitions/AccessibilitySetting.tsx
export default (function(_, argBar, argBaz, __, ___, argFre, argPlu) {
    report = argBar;
    zuuluu = argFre;
    oscard = argPlu;
    var _closure1_slot0 = report;
    entity = argBaz;
    var _closure1_slot1 = entity;
    var _closure1_slot2 = oscard;
    entity = global;
    option = entity.Object;
    tangon = option.defineProperty;
    michal = {};
    entity = true;
    michal['value'] = entity;
    entity = '__esModule';
    entity = tangon.bind(option)(zuuluu, entity, michal);
    entity = 0;
    michal = oscard[entity];
    entity = undefined;
    michal = report.bind(entity)(michal);
    tangon = michal.RendererType;
    michal = 1;
    michal = oscard[michal];
    michal = report.bind(entity)(michal);
    option = michal.UserSettingsSections;
    michal = 2;
    michal = oscard[michal];
    michal = report.bind(entity)(michal);
    michal = michal.jsx;
    var _closure1_slot3 = michal;
    michal = {};
    tangon = tangon.ROUTE;
    michal['type'] = tangon;
    tangon = function() { // Original name: title
        report = _closure1_slot0;
        oscard = _closure1_slot2;
        entity = 4;
        michal = oscard[entity];
        tangon = undefined;
        michal = report.bind(tangon)(michal);
        zuuluu = michal.intl;
        michal = zuuluu.string;
        entity = oscard[entity];
        entity = report.bind(tangon)(entity);
        entity = entity.t;
        entity = entity.G0neg4;
        entity = michal.bind(zuuluu)(entity);
        return entity;
    };
    michal['title'] = tangon;
    tangon = null;
    michal['parent'] = tangon;
    tangon = 7;
    tangon = oscard[tangon];
    tangon = report.bind(entity)(tangon);
    tangon = tangon.AccessibilityIcon;
    michal['IconComponent'] = tangon;
    tangon = function() { // Original name: useTrailing
        tangon = _closure1_slot3;
        option = _closure1_slot0;
        verify = _closure1_slot2;
        entity = 3;
        entity = verify[entity];
        zuuluu = undefined;
        entity = option.bind(zuuluu)(entity);
        michal = entity.TextBadge;
        entity = {};
        report = 4;
        oscard = verify[report];
        oscard = option.bind(zuuluu)(oscard);
        golfie = oscard.intl;
        oscard = golfie.string;
        report = verify[report];
        report = option.bind(zuuluu)(report);
        report = report.t;
        report = report.y2b7CA;
        report = oscard.bind(golfie)(report);
        entity['text'] = report;
        entity = tangon.bind(zuuluu)(michal, entity);
        return entity;
    };
    michal['useTrailing'] = tangon;
    tangon = function() { // Original name: useTrailingDismissibleContent
        _fun00001: for(var _fun00002_ip = 0; ; ) switch(_fun00002_ip) {
 0:
            zuuluu = _closure1_slot1;
            tangon = _closure1_slot2;
            entity = 5;
            entity = tangon[entity];
            tangon = undefined;
            report = zuuluu.bind(tangon)(entity);
            zuuluu = report.useExperiment;
            entity = {};
            oscard = 'SettingsOverview';
            entity['location'] = oscard;
            entity = zuuluu.bind(report)(entity);
            entity = entity.enabled;
            if(entity) { _fun00002_ip = 62; continue _fun00001 }
 56:
            entity = new Array(0);
            _fun00002_ip = 105; continue _fun00001;
 62:
            zuuluu = _closure1_slot0;
            report = _closure1_slot2;
            michal = 6;
            michal = report[michal];
            michal = zuuluu.bind(tangon)(michal);
            michal = michal.DismissibleContent;
            zuuluu = michal.MOBILE_ACCESSIBILITY_COLOR_SETTINGS;
            michal = new Array(1);
            michal[0] = zuuluu;
            entity = michal;
 105:
            return entity;
        }
    };
    michal['useTrailingDismissibleContent'] = tangon;
    tangon = {};
    option = option.ACCESSIBILITY;
    tangon['route'] = option;
    golfie = function() { // Original name: getComponent
        zuuluu = _closure1_slot0;
        michal = _closure1_slot2;
        entity = 8;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    tangon['getComponent'] = golfie;
    michal['screen'] = tangon;
    tangon = 9;
    tangon = oscard[tangon];
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/main_tabs_v2/native/settings/definitions/AccessibilitySetting.tsx';
    tangon = report.bind(oscard)(tangon);
    zuuluu['default'] = michal;
    return entity;
})();