// app/modules/main_tabs_v2/native/settings/definitions/DataAndPrivacySetting.tsx
export default (function(_, argBar, __, ___, ____, argFre, argPlu) {
    report = argBar;
    zuuluu = argFre;
    oscard = argPlu;
    var _closure1_slot0 = report;
    var _closure1_slot1 = oscard;
    entity = global;
    option = entity.Object;
    golfie = option.defineProperty;
    michal = {};
    entity = true;
    michal['value'] = entity;
    entity = '__esModule';
    entity = golfie.bind(option)(zuuluu, entity, michal);
    entity = 0;
    michal = oscard[entity];
    entity = undefined;
    michal = report.bind(entity)(michal);
    golfie = michal.RendererType;
    michal = 1;
    michal = oscard[michal];
    michal = report.bind(entity)(michal);
    option = michal.UserSettingsSections;
    michal = {};
    golfie = golfie.ROUTE;
    michal['type'] = golfie;
    golfie = function() { // Original name: title
        report = _closure1_slot0;
        oscard = _closure1_slot1;
        entity = 2;
        michal = oscard[entity];
        tangon = undefined;
        michal = report.bind(tangon)(michal);
        zuuluu = michal.intl;
        michal = zuuluu.string;
        entity = oscard[entity];
        entity = report.bind(tangon)(entity);
        entity = entity.t;
        entity = entity.OAuOHB;
        entity = michal.bind(zuuluu)(entity);
        return entity;
    };
    michal['title'] = golfie;
    golfie = null;
    michal['parent'] = golfie;
    golfie = 3;
    golfie = oscard[golfie];
    golfie = report.bind(entity)(golfie);
    golfie = golfie.ShieldLockIcon;
    michal['IconComponent'] = golfie;
    golfie = {};
    option = option.DATA_AND_PRIVACY;
    golfie['route'] = option;
    option = function() { // Original name: getComponent
        zuuluu = _closure1_slot0;
        michal = _closure1_slot1;
        entity = 4;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    golfie['getComponent'] = option;
    michal['screen'] = golfie;
    tangon = function() { // Original name: preNavigationAction
        zuuluu = _closure1_slot0;
        tangon = _closure1_slot1;
        entity = 5;
        entity = tangon[entity];
        michal = undefined;
        report = zuuluu.bind(michal)(entity);
        entity = report.fetchConsents;
        entity = entity.bind(report)();
        entity = 6;
        entity = tangon[entity];
        michal = zuuluu.bind(michal)(entity);
        entity = michal.fetchHarvestStatus;
        entity = entity.bind(michal)();
        entity = true;
        return entity;
    };
    michal['preNavigationAction'] = tangon;
    tangon = 7;
    tangon = oscard[tangon];
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/main_tabs_v2/native/settings/definitions/DataAndPrivacySetting.tsx';
    tangon = report.bind(oscard)(tangon);
    zuuluu['default'] = michal;
    return entity;
})();