// app/modules/main_tabs_v2/native/settings/definitions/FamilyCenterSetting.tsx
export default (function(_, argBar, argBaz, __, ___, argFre, argPlu) {
    report = argBar;
    zuuluu = argFre;
    oscard = argPlu;
    var _closure1_slot0 = report;
    entity = argBaz;
    var _closure1_slot1 = entity;
    var _closure1_slot2 = oscard;
    entity = global;
    option = entity.Object;
    tangon = option.defineProperty;
    michal = {};
    entity = true;
    michal['value'] = entity;
    entity = '__esModule';
    entity = tangon.bind(option)(zuuluu, entity, michal);
    entity = 0;
    michal = oscard[entity];
    entity = undefined;
    michal = report.bind(entity)(michal);
    tangon = michal.RendererType;
    michal = 1;
    michal = oscard[michal];
    michal = report.bind(entity)(michal);
    option = michal.UserSettingsSections;
    michal = {};
    tangon = tangon.ROUTE;
    michal['type'] = tangon;
    tangon = function() { // Original name: title
        zuuluu = _closure1_slot0;
        oscard = _closure1_slot2;
        michal = 2;
        michal = oscard[michal];
        report = undefined;
        michal = zuuluu.bind(report)(michal);
        zuuluu = michal.intl;
        michal = zuuluu.string;
        tangon = _closure1_slot1;
        entity = 3;
        entity = oscard[entity];
        entity = tangon.bind(report)(entity);
        entity = entity.RZqaJi;
        entity = michal.bind(zuuluu)(entity);
        return entity;
    };
    michal['title'] = tangon;
    tangon = null;
    michal['parent'] = tangon;
    tangon = 4;
    tangon = oscard[tangon];
    tangon = report.bind(entity)(tangon);
    tangon = tangon.GroupIcon;
    michal['IconComponent'] = tangon;
    tangon = {};
    option = option.FAMILY_CENTER;
    tangon['route'] = option;
    golfie = function() { // Original name: getComponent
        zuuluu = _closure1_slot0;
        michal = _closure1_slot2;
        entity = 5;
        michal = michal[entity];
        entity = undefined;
        entity = zuuluu.bind(entity)(michal);
        entity = entity.default;
        return entity;
    };
    tangon['getComponent'] = golfie;
    michal['screen'] = tangon;
    tangon = 6;
    tangon = oscard[tangon];
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/main_tabs_v2/native/settings/definitions/FamilyCenterSetting.tsx';
    tangon = report.bind(oscard)(tangon);
    zuuluu['default'] = michal;
    return entity;
})();