// app/modules/main_tabs_v2/native/settings/definitions/InputModeSetting.tsx
export default (function(_, argBar, argBaz, __, ___, argFre, argPlu) {
    report = argBar;
    zuuluu = argFre;
    oscard = argPlu;
    var _closure1_slot0 = report;
    var _closure1_slot1 = oscard;
    entity = global;
    option = entity.Object;
    golfie = option.defineProperty;
    michal = {};
    entity = true;
    michal['value'] = entity;
    entity = '__esModule';
    entity = golfie.bind(option)(zuuluu, entity, michal);
    entity = 0;
    golfie = oscard[entity];
    michal = argBaz;
    entity = undefined;
    michal = michal.bind(entity)(golfie);
    var _closure1_slot2 = michal;
    michal = 1;
    michal = oscard[michal];
    michal = report.bind(entity)(michal);
    golfie = michal.MobileSetting;
    michal = 2;
    michal = oscard[michal];
    michal = report.bind(entity)(michal);
    option = michal.RendererType;
    michal = 3;
    michal = oscard[michal];
    michal = report.bind(entity)(michal);
    michal = michal.InputModes;
    var _closure1_slot3 = michal;
    michal = {};
    option = option.PRESSABLE;
    michal['type'] = option;
    option = function() { // Original name: title
        report = _closure1_slot0;
        oscard = _closure1_slot1;
        entity = 5;
        michal = oscard[entity];
        tangon = undefined;
        michal = report.bind(tangon)(michal);
        zuuluu = michal.intl;
        michal = zuuluu.string;
        entity = oscard[entity];
        entity = report.bind(tangon)(entity);
        entity = entity.t;
        entity = entity.pS+K2N;
        entity = michal.bind(zuuluu)(entity);
        return entity;
    };
    michal['title'] = option;
    golfie = golfie.VOICE;
    michal['parent'] = golfie;
    golfie = function() { // Original name: useInputModeSettingTrailing
        _fun00001: for(var _fun00002_ip = 0; ; ) switch(_fun00002_ip) {
 0:
            zuuluu = _closure1_slot0;
            tangon = _closure1_slot1;
            entity = 4;
            entity = tangon[entity];
            oscard = undefined;
            report = zuuluu.bind(oscard)(entity);
            tangon = report.useStateFromStores;
            entity = _closure1_slot2;
            zuuluu = new Array(1);
            zuuluu[0] = entity;
            entity = function() {
                michal = _closure1_slot2;
                entity = michal.getMode;
                entity = entity.bind(michal)();
                return entity;
            };
            zuuluu = tangon.bind(report)(zuuluu, entity);
            entity = _closure1_slot3;
            entity = entity.PUSH_TO_TALK;
            if(!(zuuluu !== entity)) { _fun00002_ip = 128; continue _fun00001 }
 71:
            report = _closure1_slot0;
            golfie = _closure1_slot1;
            entity = 5;
            zuuluu = golfie[entity];
            zuuluu = report.bind(oscard)(zuuluu);
            tangon = zuuluu.intl;
            zuuluu = tangon.string;
            entity = golfie[entity];
            entity = report.bind(oscard)(entity);
            entity = entity.t;
            entity = entity.cHCEOD;
            entity = zuuluu.bind(tangon)(entity);
            _fun00002_ip = 183; continue _fun00001;
 128:
            report = _closure1_slot0;
            golfie = _closure1_slot1;
            michal = 5;
            zuuluu = golfie[michal];
            zuuluu = report.bind(oscard)(zuuluu);
            tangon = zuuluu.intl;
            zuuluu = tangon.string;
            michal = golfie[michal];
            michal = report.bind(oscard)(michal);
            michal = michal.t;
            michal = michal.Q8gkVF;
            entity = zuuluu.bind(tangon)(michal);
 183:
            return entity;
        }
    };
    michal['useTrailing'] = golfie;
    golfie = 6;
    golfie = oscard[golfie];
    golfie = report.bind(entity)(golfie);
    golfie = golfie.handleInputModePress;
    michal['onPress'] = golfie;
    tangon = function() { // Original name: additionalSearchTerms
        report = _closure1_slot0;
        oscard = _closure1_slot1;
        entity = 5;
        michal = oscard[entity];
        tangon = undefined;
        michal = report.bind(tangon)(michal);
        zuuluu = michal.intl;
        michal = zuuluu.string;
        entity = oscard[entity];
        entity = report.bind(tangon)(entity);
        entity = entity.t;
        entity = entity.nuFtHB;
        michal = michal.bind(zuuluu)(entity);
        entity = new Array(1);
        entity[0] = michal;
        return entity;
    };
    michal['additionalSearchTerms'] = tangon;
    tangon = 7;
    tangon = oscard[tangon];
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/main_tabs_v2/native/settings/definitions/InputModeSetting.tsx';
    tangon = report.bind(oscard)(tangon);
    zuuluu['default'] = michal;
    return entity;
})();