// app/modules/main_tabs_v2/native/settings/definitions/ShowDevToolsSetting.tsx
export default (function(argFoo, argBar, _, __, ___, argFre, argPlu) {
    report = argBar;
    zuuluu = argFre;
    oscard = argPlu;
    var _closure1_slot0 = report;
    var _closure1_slot1 = oscard;
    entity = global;
    verify = entity.Object;
    option = verify.defineProperty;
    michal = {};
    tangon = true;
    michal['value'] = tangon;
    entity = '__esModule';
    entity = option.bind(verify)(zuuluu, entity, michal);
    michal = {'type': null, 'title': 'Show Dev Tools', 'parent': null};
    entity = 0;
    option = oscard[entity];
    entity = undefined;
    option = report.bind(entity)(option);
    option = option.RendererType;
    option = option.PRESSABLE;
    michal['type'] = option;
    option = 2;
    option = oscard[option];
    option = report.bind(entity)(option);
    option = option.StaffBadgeIcon;
    michal['IconComponent'] = option;
    option = 3;
    option = oscard[option];
    option = report.bind(entity)(option);
    option = option.navigateToDevTools;
    michal['onPress'] = option;
    option = 4;
    option = oscard[option];
    option = report.bind(entity)(option);
    option = option.useStaffOrDevEnvSettingPredicate;
    michal['usePredicate'] = option;
    golfie = function() { // Original name: getAdditionalSearchTerms
        entity = global;
        zuuluu = entity.Object;
        michal = zuuluu.values;
        report = _closure1_slot0;
        tangon = _closure1_slot1;
        entity = 1;
        tangon = tangon[entity];
        entity = undefined;
        entity = report.bind(entity)(tangon);
        entity = entity.DevToolsScreens;
        zuuluu = michal.bind(zuuluu)(entity);
        michal = zuuluu.map;
        entity = function(argFoo) {
            entity = argFoo;
            entity = entity.headerTitle;
            return entity;
        };
        entity = michal.bind(zuuluu)(entity);
        return entity;
    };
    michal['additionalSearchTerms'] = golfie;
    michal['withArrow'] = tangon;
    tangon = 5;
    tangon = oscard[tangon];
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/main_tabs_v2/native/settings/definitions/ShowDevToolsSetting.tsx';
    tangon = report.bind(oscard)(tangon);
    zuuluu['default'] = michal;
    return entity;
})();