// app/modules/main_tabs_v2/native/settings/definitions/ShowLinkDecorationsSetting.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var7 = require;
    var3 = exports;
    var8 = dependencyMap;
    var _closure1_slot0 = var7;
    var _closure1_slot1 = var8;
    var4 = function useShowLinkDecorationsSettingValue() {
        var4 = _closure1_slot0;
        var3 = _closure1_slot1;
        var2 = 3;
        var3 = var3[var2];
        var2 = undefined;
        var4 = var4.bind(var2)(var3);
        var3 = var4.useStateFromStores;
        var1 = _closure1_slot2;
        var2 = new Array(1);
        var2[0] = var1;
        var1 = function() {
            var1 = _closure1_slot2;
            var1 = var1.alwaysShowLinkDecorations;
            return var1;
        };
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var2 = function onShowLinkDecorationsValueChange(arg1) {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 4;
        var2 = var2[var1];
        var1 = undefined;
        var4 = var3.bind(var1)(var2);
        var3 = var4.setAlwaysShowLinkDecorations;
        var2 = arg1;
        var2 = var3.bind(var4)(var2);
        return var1;
    };
    var1 = global;
    var10 = var1.Object;
    var6 = var10.defineProperty;
    var5 = {};
    var1 = true;
    var5['value'] = var1;
    var1 = '__esModule';
    var1 = var6.bind(var10)(var3, var1, var5);
    var1 = 0;
    var6 = var8[var1];
    var5 = metroImportDefault;
    var1 = undefined;
    var5 = var5.bind(var1)(var6);
    var _closure1_slot2 = var5;
    var5 = 1;
    var5 = var8[var5];
    var5 = var7.bind(var1)(var5);
    var6 = var5.MobileSetting;
    var5 = {};
    var10 = 2;
    var10 = var8[var10];
    var10 = var7.bind(var1)(var10);
    var10 = var10.RendererType;
    var10 = var10.TOGGLE;
    var5['type'] = var10;
    var9 = function title() {
        var5 = _closure1_slot0;
        var6 = _closure1_slot1;
        var1 = 5;
        var2 = var6[var1];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var3 = var2.intl;
        var2 = var3.string;
        var1 = var6[var1];
        var1 = var5.bind(var4)(var1);
        var1 = var1.t;
        var1 = var1.OLZFBw;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var5['title'] = var9;
    var6 = var6.ACCESSIBILITY;
    var5['parent'] = var6;
    var5['useValue'] = var4;
    var5['onValueChange'] = var2;
    var6 = 6;
    var6 = var8[var6];
    var8 = var7.bind(var1)(var6);
    var7 = var8.fileFinishedImporting;
    var6 = 'modules/main_tabs_v2/native/settings/definitions/ShowLinkDecorationsSetting.tsx';
    var6 = var7.bind(var8)(var6);
    var3['default'] = var5;
    var3['useShowLinkDecorationsSettingValue'] = var4;
    var3['onShowLinkDecorationsValueChange'] = var2;
    return var1;
})();