// app/modules/rpc/server/OptimizedRPCAuthorizeExperiment.tsx
export default (function(_, argBar, __, ___, ____, argFred, argPlugh) {
    oscar = argBar;
    zulu = argFred;
    golf = argPlugh;
    entity = global;
    options = entity.Object;
    report = options.defineProperty;
    tango = {};
    romeo = true;
    tango['value'] = romeo;
    entity = '__esModule';
    entity = report.bind(options)(zulu, entity, tango);
    entity = 0;
    tango = golf[entity];
    entity = undefined;
    tango = oscar.bind(entity)(tango);
    verify = tango.CommonTriggerPoints;
    tango = 1;
    tango = golf[tango];
    options = oscar.bind(entity)(tango);
    report = options.createExperiment;
    tango = {'kind': 'user', 'id': '2025-02_optimized_rpc_authorize', 'label': 'Optimized RPC Authorization Experiment'};
    offset = {};
    yankee = false;
    offset['enabled'] = yankee;
    tango['defaultConfig'] = offset;
    yankee = {'id': 1, 'label': 'Enable optimized RPC authorization'};
    offset = {};
    offset['enabled'] = romeo;
    yankee['config'] = offset;
    offset = new Array(1);
    offset[0] = yankee;
    tango['treatments'] = offset;
    verify = verify.CONNECTION_OPEN;
    tango['commonTriggerPoint'] = verify;
    tango = report.bind(options)(tango);
    var _closure1_slot0 = tango;
    report = 2;
    report = golf[report];
    golf = oscar.bind(entity)(report);
    oscar = golf.fileFinishedImporting;
    report = 'modules/rpc/server/OptimizedRPCAuthorizeExperiment.tsx';
    report = oscar.bind(golf)(report);
    zulu['OptimizedRPCAuthorizeExperiment'] = tango;
    mike = function() { // Original name: isOptimizedRPCAuthorizeEnabled
        zulu = _closure1_slot0;
        mike = zulu.getCurrentConfig;
        entity = {};
        tango = 'isOptimizedRPCAuthorizeEnabled';
        entity['location'] = tango;
        entity = mike.bind(zulu)(entity);
        entity = entity.enabled;
        return entity;
    };
    zulu['isOptimizedRPCAuthorizeEnabled'] = mike;
    return entity;
})();