// app/modules/nuf/native/components/notification/RedesignNotificationModal.tsx
export default (function(native1, native2, native3, native4, native5, native6, native7) {
    var6 = native2;
    var12 = native3;
    var3 = native6;
    var7 = native7;
    var _closure1_slot0 = var6;
    var _closure1_slot1 = var12;
    var _closure1_slot2 = var7;
    var4 = function RedesignNotificationModal(arg1) {
        var2 = arg1;
        var6 = var2.onComplete;
        var _closure2_slot0 = var6;
        var2 = _closure1_slot11;
        var4 = undefined;
        var13 = var2.bind(var4)();
        var7 = _closure1_slot3;
        var5 = var7.useCallback;
        var3 = new Array(1);
        var3[0] = var6;
        var2 = function() {
            var4 = _closure1_slot0;
            var3 = _closure1_slot2;
            var1 = 8;
            var3 = var3[var1];
            var1 = undefined;
            var6 = var4.bind(var1)(var3);
            var5 = var6.requestPushNotificationPermission;
            var3 = _closure1_slot8;
            var4 = var3.ALLOW_TO_REQUEST;
            var2 = _closure1_slot7;
            var3 = var2.ALERT;
            var2 = function() {
                _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
 0:
                    var3 = _closure2_slot0;
                    var2 = null;
                    if(!(var2 != var3)) { _fun0001_ip = 23; continue _fun0001 }
 13:
                    var2 = _closure2_slot0;
                    var1 = undefined;
                    var1 = var2.bind(var1)();
 23:
                    var1 = undefined;
                    return var1;
                }
            };
            var2 = var5.bind(var6)(var4, var3, var2);
            return var1;
        };
        var10 = var5.bind(var7)(var2, var3);
        var5 = _closure1_slot3;
        var3 = var5.useCallback;
        var2 = new Array(1);
        var2[0] = var6;
        var1 = function() {
            _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
 0:
                var5 = _closure1_slot1;
                var4 = _closure1_slot2;
                var1 = 9;
                var3 = var4[var1];
                var1 = undefined;
                var7 = var5.bind(var1)(var3);
                var6 = var7.track;
                var3 = _closure1_slot9;
                var5 = var3.NOTIFICATION_PERMISSION_PREPROMPT_ACKED;
                var3 = {};
                var8 = _closure1_slot8;
                var8 = var8.SKIP_STEP;
                var3['action_type'] = var8;
                var8 = _closure1_slot7;
                var8 = var8.ALERT;
                var3['action_location'] = var8;
                var3 = var6.bind(var7)(var5, var3);
                var3 = _closure1_slot0;
                var5 = 10;
                var5 = var4[var5];
                var6 = var3.bind(var1)(var5);
                var5 = var6.setPushPermissionState;
                var2 = _closure1_slot6;
                var2 = var2.PROMPT_SKIPPED;
                var2 = var5.bind(var6)(var2);
                var2 = 8;
                var2 = var4[var2];
                var3 = var3.bind(var1)(var2);
                var2 = var3.enableProvisionalPushNotification;
                var2 = var2.bind(var3)();
                var4 = _closure2_slot0;
                var3 = null;
                if(!(var3 != var4)) { _fun0002_ip = 161; continue _fun0002 }
 150:
                var3 = _closure2_slot0;
                var2 = true;
                var2 = var3.bind(var1)(var2);
 161:
                return var1;
            }
        };
        var9 = var3.bind(var5)(var1, var2);
        var3 = _closure1_slot10;
        var2 = _closure1_slot5;
        var1 = {};
        var5 = var13.container;
        var1['style'] = var5;
        var7 = _closure1_slot10;
        var14 = _closure1_slot1;
        var12 = _closure1_slot2;
        var5 = 11;
        var5 = var12[var5];
        var6 = var14.bind(var4)(var5);
        var5 = {};
        var5['onAllow'] = var10;
        var5['onDontAllow'] = var9;
        var11 = _closure1_slot10;
        var10 = _closure1_slot4;
        var9 = {};
        var15 = 'contain';
        var9['resizeMode'] = var15;
        var13 = var13.notificationHeaderImage;
        var9['style'] = var13;
        var13 = 12;
        var13 = var12[var13];
        var13 = var14.bind(var4)(var13);
        var9['source'] = var13;
        var9 = var11.bind(var4)(var10, var9);
        var5['header'] = var9;
        var11 = _closure1_slot0;
        var8 = 13;
        var9 = var12[var8];
        var9 = var11.bind(var4)(var9);
        var13 = var9.intl;
        var10 = var13.string;
        var9 = var12[var8];
        var9 = var11.bind(var4)(var9);
        var9 = var9.t;
        var9 = var9.3nx0b2;
        var9 = var10.bind(var13)(var9);
        var5['title'] = var9;
        var9 = var12[var8];
        var9 = var11.bind(var4)(var9);
        var10 = var9.intl;
        var9 = var10.string;
        var8 = var12[var8];
        var8 = var11.bind(var4)(var8);
        var8 = var8.t;
        var8 = var8.Gf7U1d;
        var8 = var9.bind(var10)(var8);
        var5['subtitle'] = var8;
        var5 = var7.bind(var4)(var6, var5);
        var1['children'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var _closure1_slot12 = var4;
    var1 = global;
    var9 = var1.Object;
    var8 = var9.defineProperty;
    var5 = {};
    var1 = true;
    var5['value'] = var1;
    var1 = '__esModule';
    var1 = var8.bind(var9)(var3, var1, var5);
    var1 = 0;
    var8 = var7[var1];
    var5 = native4;
    var1 = undefined;
    var5 = var5.bind(var1)(var8);
    var _closure1_slot3 = var5;
    var11 = 1;
    var5 = var7[var11];
    var5 = var6.bind(var1)(var5);
    var8 = var5.Image;
    var _closure1_slot4 = var8;
    var5 = var5.View;
    var _closure1_slot5 = var5;
    var5 = 2;
    var5 = var7[var5];
    var5 = var6.bind(var1)(var5);
    var5 = var5.PermissionStateType;
    var _closure1_slot6 = var5;
    var5 = 3;
    var5 = var7[var5];
    var5 = var6.bind(var1)(var5);
    var8 = var5.EventActionLocation;
    var _closure1_slot7 = var8;
    var5 = var5.EventActionType;
    var _closure1_slot8 = var5;
    var5 = 4;
    var5 = var7[var5];
    var5 = var6.bind(var1)(var5);
    var5 = var5.AnalyticEvents;
    var _closure1_slot9 = var5;
    var5 = 5;
    var5 = var7[var5];
    var5 = var6.bind(var1)(var5);
    var5 = var5.jsx;
    var _closure1_slot10 = var5;
    var5 = 6;
    var5 = var7[var5];
    var9 = var6.bind(var1)(var5);
    var8 = var9.createStyles;
    var5 = {};
    var10 = {};
    var10['flex'] = var11;
    var11 = 7;
    var13 = var7[var11];
    var13 = var12.bind(var1)(var13);
    var13 = var13.colors;
    var13 = var13.BACKGROUND_PRIMARY;
    var10['backgroundColor'] = var13;
    var11 = var7[var11];
    var11 = var12.bind(var1)(var11);
    var11 = var11.spacing;
    var11 = var11.PX_48;
    var11 = -var11;
    var10['marginTop'] = var11;
    var5['container'] = var10;
    var10 = {'position': 'absolute', 'alignSelf': 'center', 'zIndex': 2, 'top': 4294967156, 'height': 156, 'width': 150};
    var5['notificationHeaderImage'] = var10;
    var5 = var8.bind(var9)(var5);
    var _closure1_slot11 = var5;
    var5 = 14;
    var5 = var7[var5];
    var7 = var6.bind(var1)(var5);
    var6 = var7.fileFinishedImporting;
    var5 = 'modules/nuf/native/components/notification/RedesignNotificationModal.tsx';
    var5 = var6.bind(var7)(var5);
    var3['default'] = var4;
    var2 = function RedesignNotificationScreen(arg1) {
        var1 = arg1;
        var1 = var1.route;
        var1 = var1.params;
        var1 = var1.onComplete;
        var4 = _closure1_slot10;
        var3 = _closure1_slot12;
        var2 = {};
        var2['onComplete'] = var1;
        var1 = undefined;
        var1 = var4.bind(var1)(var3, var2);
        return var1;
    };
    var3['RedesignNotificationScreen'] = var2;
    return var1;
})();