// app/modules/channel/native/ChannelActionSheetUtils.tsx
export default (function(argFoo, argBar, _, __, ___, argFre, argPlu) {
    report = argBar;
    zuuluu = argFre;
    tangon = argPlu;
    var _closure1_slot0 = report;
    var _closure1_slot1 = tangon;
    entity = global;
    option = entity.Object;
    golfie = option.defineProperty;
    oscard = {};
    entity = true;
    oscard['value'] = entity;
    entity = '__esModule';
    entity = golfie.bind(option)(zuuluu, entity, oscard);
    entity = 3;
    tangon = tangon[entity];
    entity = undefined;
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/channel/native/ChannelActionSheetUtils.tsx';
    tangon = report.bind(oscard)(tangon);
    michal = function(argFoo, argBar) { // Original name: copyGuildChannelOrThreadLink
        zuuluu = _closure1_slot0;
        tangon = _closure1_slot1;
        entity = 0;
        michal = tangon[entity];
        entity = undefined;
        golfie = zuuluu.bind(entity)(michal);
        oscard = golfie.getChannelPermalink;
        report = argFoo;
        michal = argBar;
        oscard = oscard.bind(golfie)(report, michal);
        michal = 1;
        michal = tangon[michal];
        report = zuuluu.bind(entity)(michal);
        michal = report.copy;
        michal = michal.bind(report)(oscard);
        michal = 2;
        michal = tangon[michal];
        zuuluu = zuuluu.bind(entity)(michal);
        michal = zuuluu.presentLinkCopied;
        michal = michal.bind(zuuluu)();
        return entity;
    };
    zuuluu['copyGuildChannelOrThreadLink'] = michal;
    return entity;
})();