// app/modules/user_settings/native/quest_preview/QuestThemePicker.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var12 = metroImportDefault;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var12;
    var _closure1_slot2 = var6;
    var2 = function QuestThemePicker() {
        var1 = _closure1_slot12;
        var4 = undefined;
        var16 = var1.bind(var4)();
        var _closure2_slot0 = var16;
        var3 = _closure1_slot1;
        var20 = _closure1_slot2;
        var1 = 9;
        var1 = var20[var1];
        var2 = var3.bind(var4)(var1);
        var1 = 10;
        var1 = var20[var1];
        var1 = var3.bind(var4)(var1);
        var1 = var1.USER_SETTINGS;
        var1 = var2.bind(var4)(var1);
        var6 = var1.analyticsLocations;
        var _closure2_slot1 = var6;
        var19 = _closure1_slot0;
        var1 = 11;
        var1 = var20[var1];
        var2 = var19.bind(var4)(var1);
        var1 = var2.useAllMobileThemes;
        var2 = var1.bind(var2)();
        var _closure2_slot2 = var2;
        var1 = 12;
        var5 = var20[var1];
        var10 = var19.bind(var4)(var5);
        var9 = var10.useStateFromStores;
        var5 = _closure1_slot7;
        var7 = new Array(1);
        var7[0] = var5;
        var5 = function() {
            var1 = _closure1_slot7;
            var1 = var1.theme;
            return var1;
        };
        var5 = var9.bind(var10)(var7, var5);
        var _closure2_slot3 = var5;
        var1 = var20[var1];
        var10 = var19.bind(var4)(var1);
        var9 = var10.useStateFromStoresObject;
        var1 = _closure1_slot6;
        var7 = new Array(1);
        var7[0] = var1;
        var1 = function() {
            var1 = {};
            var4 = _closure1_slot6;
            var3 = var4.shouldSync;
            var2 = 'appearance';
            var2 = var3.bind(var4)(var2);
            var1['isSynced'] = var2;
            return var1;
        };
        var1 = var9.bind(var10)(var7, var1);
        var1 = var1.isSynced;
        var _closure2_slot4 = var1;
        var10 = _closure1_slot3;
        var9 = var10.useRef;
        var7 = null;
        var7 = var9.bind(var10)(var7);
        var _closure2_slot5 = var7;
        var10 = _closure1_slot3;
        var9 = var10.useEffect;
        var7 = new Array(1);
        var7[0] = var5;
        var5 = function() {
            _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
                var2 = _closure2_slot5;
                var3 = var2.current;
                var2 = null;
                if(!(var2 == var3)) { _fun0001_ip = 2; continue _fun0001 }
case 3:
                var2 = _closure2_slot5;
                var1 = _closure2_slot3;
                var2['current'] = var1;
case 2:
                var1 = undefined;
                return var1;
            }
        };
        var5 = var9.bind(var10)(var5, var7);
        var9 = _closure1_slot3;
        var7 = var9.useMemo;
        var5 = new Array(1);
        var5[0] = var2;
        var2 = function() {
            var2 = _closure1_slot9;
            var4 = var2.LIGHT;
            var2 = new Array(3);
            var2[0] = var4;
            var4 = _closure1_slot9;
            var4 = var4.DARKER;
            var2[1] = var4;
            var3 = _closure1_slot9;
            var3 = var3.MIDNIGHT;
            var2[2] = var3;
            var _closure3_slot0 = var2;
            var3 = _closure2_slot2;
            var2 = var3.filter;
            var1 = function(arg1) {
                _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
case 0:
                    var2 = arg1;
                    var3 = var2.type;
                    var5 = _closure1_slot0;
                    var4 = _closure1_slot2;
                    var1 = 13;
                    var4 = var4[var1];
                    var1 = undefined;
                    var1 = var5.bind(var1)(var4);
                    var1 = var1.ClientThemeType;
                    var1 = var1.STANDARD_BACKGROUND_THEME;
                    var1 = var3 === var1;
                    if(!var1) { _fun0002_ip = 4; continue _fun0002 }
case 5:
                    var5 = _closure3_slot0;
                    var4 = var5.includes;
                    var3 = var2.theme;
                    var1 = var4.bind(var5)(var3);
case 4:
                    if(!var1) { _fun0002_ip = 6; continue _fun0002 }
case 7:
                    var3 = var2.theme;
                    var2 = 'system';
                    var1 = var2 !== var3;
case 6:
                    return var1;
                }
            };
            var1 = var2.bind(var3)(var1);
            return var1;
        };
        var11 = var7.bind(var9)(var2, var5);
        var _closure2_slot6 = var11;
        var5 = 14;
        var2 = var20[var5];
        var12 = var19.bind(var4)(var2);
        var10 = var12.useToken;
        var2 = 8;
        var7 = var20[var2];
        var7 = var3.bind(var4)(var7);
        var7 = var7.colors;
        var9 = var7.BG_BASE_PRIMARY;
        var7 = _closure1_slot9;
        var7 = var7.LIGHT;
        var10 = var10.bind(var12)(var9, var7);
        var _closure2_slot7 = var10;
        var7 = var20[var5];
        var14 = var19.bind(var4)(var7);
        var12 = var14.useToken;
        var7 = var20[var2];
        var7 = var3.bind(var4)(var7);
        var7 = var7.colors;
        var9 = var7.BG_BASE_PRIMARY;
        var7 = _closure1_slot9;
        var7 = var7.DARKER;
        var9 = var12.bind(var14)(var9, var7);
        var _closure2_slot8 = var9;
        var5 = var20[var5];
        var7 = var19.bind(var4)(var5);
        var5 = var7.useToken;
        var2 = var20[var2];
        var2 = var3.bind(var4)(var2);
        var2 = var2.colors;
        var3 = var2.BG_BASE_PRIMARY;
        var2 = _closure1_slot9;
        var2 = var2.MIDNIGHT;
        var2 = var5.bind(var7)(var3, var2);
        var _closure2_slot9 = var2;
        var7 = _closure1_slot3;
        var5 = var7.useMemo;
        var3 = new Array(4);
        var3[0] = var11;
        var3[1] = var10;
        var3[2] = var9;
        var3[3] = var2;
        var2 = function() {
            var3 = {};
            var2 = _closure1_slot9;
            var6 = var2.LIGHT;
            var5 = _closure2_slot7;
            var3[var6] = var5;
            var5 = _closure1_slot9;
            var6 = var5.DARKER;
            var5 = _closure2_slot8;
            var3[var6] = var5;
            var4 = _closure1_slot9;
            var5 = var4.MIDNIGHT;
            var4 = _closure2_slot9;
            var3[var5] = var4;
            var _closure3_slot0 = var3;
            var3 = _closure2_slot6;
            var2 = var3.map;
            var1 = function(arg1) {
                _fun0003: for(var _fun0003_ip = 0; ; ) switch(_fun0003_ip) {
case 0:
                    var4 = arg1;
                    var3 = var4.theme;
                    var5 = _closure1_slot0;
                    var2 = _closure1_slot2;
                    var1 = 15;
                    var2 = var2[var1];
                    var1 = undefined;
                    var6 = var5.bind(var1)(var2);
                    var5 = var6.isNullOrEmpty;
                    var2 = _closure3_slot0;
                    var2 = var2[var3];
                    var5 = var5.bind(var6)(var2);
                    var2 = '#000000';
                    if(var5) { _fun0003_ip = 8; continue _fun0003 }
case 9:
                    var1 = _closure3_slot0;
                    var2 = var1[var3];
case 8:
                    var1 = {};
                    var3 = var4.theme;
                    var1['theme'] = var3;
                    var3 = var4.getName;
                    var3 = var3.bind(var4)();
                    var1['name'] = var3;
                    var1['color'] = var2;
                    return var1;
                }
            };
            var1 = var2.bind(var3)(var1);
            return var1;
        };
        var10 = var5.bind(var7)(var2, var3);
        var5 = _closure1_slot3;
        var3 = var5.useCallback;
        var2 = new Array(2);
        var2[0] = var6;
        var2[1] = var1;
        var1 = function(arg1) {
            _fun0004: for(var _fun0004_ip = 0; ; ) switch(_fun0004_ip) {
case 0:
                var1 = arg1;
                var _closure3_slot0 = var1;
                var4 = _closure1_slot8;
                var3 = var4.find;
                var2 = function(arg1) {
                    var1 = arg1;
                    var2 = var1.theme;
                    var1 = _closure3_slot0;
                    var1 = var2 === var1;
                    return var1;
                };
                var5 = var3.bind(var4)(var2);
                var2 = null;
                if(!(var2 != var5)) { _fun0004_ip = 10; continue _fun0004 }
case 11:
                var3 = _closure1_slot0;
                var2 = _closure1_slot2;
                var1 = 16;
                var2 = var2[var1];
                var1 = undefined;
                var4 = var3.bind(var1)(var2);
                var3 = var4.handleSaveTheme;
                var2 = _closure2_slot1;
                var1 = _closure2_slot4;
                var1 = var3.bind(var4)(var5, var2, var1);
case 10:
                var1 = undefined;
                return var1;
            }
        };
        var1 = var3.bind(var5)(var1, var2);
        var _closure2_slot10 = var1;
        var5 = _closure1_slot3;
        var3 = var5.useCallback;
        var2 = new Array(1);
        var2[0] = var1;
        var1 = function() {
            _fun0005: for(var _fun0005_ip = 0; ; ) switch(_fun0005_ip) {
case 0:
                var2 = _closure2_slot5;
                var3 = var2.current;
                var2 = null;
                if(!(var2 != var3)) { _fun0005_ip = 12; continue _fun0005 }
case 3:
                var3 = _closure2_slot10;
                var1 = _closure2_slot5;
                var2 = var1.current;
                var1 = undefined;
                var1 = var3.bind(var1)(var2);
case 12:
                var1 = undefined;
                return var1;
            }
        };
        var12 = var3.bind(var5)(var1, var2);
        var3 = _closure1_slot10;
        var2 = _closure1_slot4;
        var1 = {};
        var5 = var16.themeSection;
        var1['style'] = var5;
        var7 = _closure1_slot11;
        var6 = _closure1_slot4;
        var5 = {};
        var9 = var16.themeSelector;
        var5['style'] = var9;
        var9 = var10.map;
        var8 = function(arg1) {
            _fun0006: for(var _fun0006_ip = 0; ; ) switch(_fun0006_ip) {
case 0:
                var1 = arg1;
                var _closure3_slot0 = var1;
                var5 = _closure1_slot11;
                var4 = _closure1_slot5;
                var3 = {};
                var2 = _closure2_slot0;
                var8 = var2.themeOption;
                var3['style'] = var8;
                var6 = function onPress() {
                    var3 = _closure2_slot10;
                    var1 = _closure3_slot0;
                    var2 = var1.theme;
                    var1 = undefined;
                    var1 = var3.bind(var1)(var2);
                    return var1;
                };
                var3['onPress'] = var6;
                var9 = _closure1_slot10;
                var8 = _closure1_slot4;
                var6 = {};
                var11 = var2.themeCircle;
                var2 = new Array(3);
                var2[0] = var11;
                var11 = {};
                var12 = var1.color;
                var11['backgroundColor'] = var12;
                var2[1] = var11;
                var12 = _closure2_slot3;
                var11 = var1.theme;
                var11 = var12 === var11;
                if(!var11) { _fun0006_ip = 13; continue _fun0006 }
case 14:
                var12 = _closure2_slot0;
                var11 = var12.themeCircleSelected;
case 13:
                var2[2] = var11;
                var6['style'] = var2;
                var2 = undefined;
                var8 = var9.bind(var2)(var8, var6);
                var6 = new Array(2);
                var6[0] = var8;
                var9 = _closure1_slot10;
                var8 = _closure1_slot0;
                var11 = _closure1_slot2;
                var7 = 17;
                var7 = var11[var7];
                var7 = var8.bind(var2)(var7);
                var8 = var7.Text;
                var7 = {'variant': 'text-xs/medium', 'color': 'text-muted'};
                var10 = _closure2_slot0;
                var10 = var10.themeLabel;
                var7['style'] = var10;
                var10 = var1.name;
                var7['children'] = var10;
                var7 = var9.bind(var2)(var8, var7);
                var6[1] = var7;
                var3['children'] = var6;
                var1 = var1.theme;
                var1 = var5.bind(var2)(var4, var3, var1);
                return var1;
            }
        };
        var9 = var9.bind(var10)(var8);
        var8 = new Array(2);
        var8[0] = var9;
        var11 = _closure1_slot11;
        var10 = _closure1_slot5;
        var9 = {};
        var14 = var16.resetButton;
        var9['style'] = var14;
        var9['onPress'] = var12;
        var15 = _closure1_slot10;
        var14 = _closure1_slot4;
        var12 = {};
        var17 = var16.resetIcon;
        var12['style'] = var17;
        var21 = _closure1_slot10;
        var17 = 18;
        var17 = var20[var17];
        var17 = var19.bind(var4)(var17);
        var18 = var17.RefreshIcon;
        var17 = {};
        var22 = 'sm';
        var17['size'] = var22;
        var17 = var21.bind(var4)(var18, var17);
        var12['children'] = var17;
        var14 = var15.bind(var4)(var14, var12);
        var12 = new Array(2);
        var12[0] = var14;
        var15 = _closure1_slot10;
        var13 = 17;
        var13 = var20[var13];
        var13 = var19.bind(var4)(var13);
        var14 = var13.Text;
        var13 = {'variant': 'text-xs/medium', 'color': 'text-muted'};
        var16 = var16.themeLabel;
        var13['style'] = var16;
        var16 = 19;
        var17 = var20[var16];
        var17 = var19.bind(var4)(var17);
        var18 = var17.intl;
        var17 = var18.string;
        var16 = var20[var16];
        var16 = var19.bind(var4)(var16);
        var16 = var16.t;
        var16 = var16.yBZMsb;
        var16 = var17.bind(var18)(var16);
        var13['children'] = var16;
        var13 = var15.bind(var4)(var14, var13);
        var12[1] = var13;
        var9['children'] = var12;
        var9 = var11.bind(var4)(var10, var9);
        var8[1] = var9;
        var5['children'] = var8;
        var5 = var7.bind(var4)(var6, var5);
        var1['children'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var1 = global;
    var9 = var1.Object;
    var8 = var9.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var8.bind(var9)(var3, var1, var4);
    var1 = 0;
    var8 = var6[var1];
    var4 = metroImportAll;
    var1 = undefined;
    var4 = var4.bind(var1)(var8);
    var _closure1_slot3 = var4;
    var4 = 1;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var8 = var4.View;
    var _closure1_slot4 = var8;
    var4 = var4.TouchableOpacity;
    var _closure1_slot5 = var4;
    var4 = 2;
    var4 = var6[var4];
    var4 = var12.bind(var1)(var4);
    var _closure1_slot6 = var4;
    var4 = 3;
    var4 = var6[var4];
    var4 = var12.bind(var1)(var4);
    var _closure1_slot7 = var4;
    var4 = 4;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.REDESIGN_STANDARD_BACKGROUND_THEMES;
    var _closure1_slot8 = var4;
    var4 = 5;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.ThemeTypes;
    var _closure1_slot9 = var4;
    var4 = 6;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var8 = var4.jsx;
    var _closure1_slot10 = var8;
    var4 = var4.jsxs;
    var _closure1_slot11 = var4;
    var4 = 7;
    var4 = var6[var4];
    var9 = var5.bind(var1)(var4);
    var8 = var9.createStyles;
    var4 = {};
    var10 = {};
    var11 = 8;
    var13 = var6[var11];
    var13 = var12.bind(var1)(var13);
    var13 = var13.spacing;
    var13 = var13.PX_8;
    var10['marginBottom'] = var13;
    var4['themeSection'] = var10;
    var10 = {};
    var13 = var6[var11];
    var13 = var12.bind(var1)(var13);
    var13 = var13.spacing;
    var13 = var13.PX_8;
    var10['marginBottom'] = var13;
    var4['themeSectionTitle'] = var10;
    var10 = {};
    var13 = 'row';
    var10['flexDirection'] = var13;
    var13 = var6[var11];
    var13 = var12.bind(var1)(var13);
    var13 = var13.spacing;
    var13 = var13.PX_12;
    var10['gap'] = var13;
    var4['themeSelector'] = var10;
    var10 = {};
    var13 = 'center';
    var10['alignItems'] = var13;
    var14 = var6[var11];
    var14 = var12.bind(var1)(var14);
    var14 = var14.spacing;
    var14 = var14.PX_4;
    var10['gap'] = var14;
    var4['themeOption'] = var10;
    var10 = {'width': 32, 'height': 32, 'borderRadius': null, 'borderWidth': 2, 'borderColor': 'transparent'};
    var14 = var6[var11];
    var14 = var12.bind(var1)(var14);
    var14 = var14.radii;
    var14 = var14.round;
    var10['borderRadius'] = var14;
    var4['themeCircle'] = var10;
    var10 = {};
    var14 = var6[var11];
    var14 = var12.bind(var1)(var14);
    var14 = var14.colors;
    var14 = var14.BUTTON_OUTLINE_BRAND_BORDER;
    var10['borderColor'] = var14;
    var4['themeCircleSelected'] = var10;
    var10 = {};
    var14 = 11;
    var10['fontSize'] = var14;
    var4['themeLabel'] = var10;
    var10 = {};
    var10['alignItems'] = var13;
    var13 = var6[var11];
    var13 = var12.bind(var1)(var13);
    var13 = var13.spacing;
    var13 = var13.PX_4;
    var10['gap'] = var13;
    var4['resetButton'] = var10;
    var10 = {'width': 32, 'height': 32, 'borderRadius': null, 'borderWidth': 2, 'borderColor': 'transparent', 'justifyContent': 'center', 'alignItems': 'center'};
    var11 = var6[var11];
    var11 = var12.bind(var1)(var11);
    var11 = var11.radii;
    var11 = var11.round;
    var10['borderRadius'] = var11;
    var4['resetIcon'] = var10;
    var4 = var8.bind(var9)(var4);
    var _closure1_slot12 = var4;
    var4 = 20;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/user_settings/native/quest_preview/QuestThemePicker.tsx';
    var4 = var5.bind(var6)(var4);
    var3['default'] = var2;
    var3['QuestThemePicker'] = var2;
    return var1;
})();