// app/modules/react_asset/native/native_required_assets.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var1 = global;
    var7 = var1.Object;
    var4 = var7.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var4.bind(var7)(var3, var1, var2);
    var2 = {};
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var5.bind(var1)(var4);
    var9 = var4.NATIVE_REQUIRED_ASSETS_ICONS;
    var10 = var2;
    var4 = copyDataProperties(var10, var9);
    var4 = 1;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var9 = var4.NATIVE_REQUIRED_ASSETS_MISC;
    var10 = var2;
    var4 = copyDataProperties(var10, var9);
    var4 = 2;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/react_asset/native/native_required_assets.tsx';
    var4 = var5.bind(var6)(var4);
    var3['NATIVE_REQUIRED_ASSETS'] = var2;
    return var1;
})();