// app/modules/captcha/tooling/native/CaptchaTestModal.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var11 = metroImportDefault;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var11;
    var _closure1_slot2 = var6;
    var1 = function CaptchaTestScreen(arg1) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var2 = arg1;
            var8 = null;
            if(!(var2 != var8)) { _fun0001_ip = 2; continue _fun0001 }
case 3:
            var5 = undefined;
            var _closure2_slot0 = var5;
            var _closure2_slot1 = var5;
            var _closure2_slot2 = var5;
            var _closure2_slot3 = var5;
            var1 = function _sendCaptchaRequest() {
                var4 = undefined;
                var1 = undefined;
                var3 = _closure1_slot3;
                var2 = function* () {
                    var1 = function* anon_0_() {
                        _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
case 0:
                            StartGenerator();
                            ResumeGenerator(result_out_reg=0, return_bool_out_reg=1);
                            if(var2) { _fun0002_ip = 4; continue _fun0002 }
case 5:
                            var2 = _closure2_slot0;
                            var10 = null;
                            if(!(var10 != var2)) { _fun0002_ip = 6; continue _fun0002 }
case 7: // try_start_0
                            var4 = _closure1_slot0;
                            var5 = _closure1_slot2;
                            var2 = 8;
                            var2 = var5[var2];
                            var5 = undefined;
                            var7 = var4.bind(var5)(var2);
                            var6 = var7.testCaptcha;
                            var4 = _closure2_slot0;
                            var2 = {};
                            var8 = _closure2_slot2;
                            var10 = var10 != var8;
                            var8 = undefined;
                            if(!var10) { _fun0002_ip = 8; continue _fun0002 }
case 9:
                            var8 = _closure2_slot2;
case 8:
                            var2['difficulty'] = var8;
                            var2 = var6.bind(var7)(var4, var2);
                            SaveGenerator(address=97);
case 10:
                            return var2;
case 11:
                            ResumeGenerator(result_out_reg=1, return_bool_out_reg=3);
                            if(var4) { _fun0002_ip = 12; continue _fun0002 }
case 13:
                            var4 = _closure1_slot1;
                            var6 = _closure1_slot2;
                            var3 = 9;
                            var3 = var6[var3];
                            var5 = var4.bind(var5)(var3);
                            var4 = var5.open;
                            var3 = {'key': 'captcha-test-modal-success', 'content': 'Captcha completed!'};
                            var3 = var4.bind(var5)(var3);
case 14: // try_end0
                            _fun0002_ip = 6; continue _fun0002;
case 12:
                            return var2;
case 15: // catch_target0
                            CatchBlockStart(arg_register=4);
                            var4 = _closure1_slot1;
                            var3 = _closure1_slot2;
                            var2 = 9;
                            var3 = var3[var2];
                            var2 = undefined;
                            var4 = var4.bind(var2)(var3);
                            var3 = var4.open;
                            var2 = {};
                            var6 = 'captcha-test-modal-error';
                            var2['key'] = var6;
                            var5 = var5.message;
                            var2['content'] = var5;
                            var2 = var3.bind(var4)(var2);
case 6:
                            var2 = undefined;
                            return var2;
case 4:
                            return var1;
                        }
                    };
                    return var1;
                };
                var4 = var3.bind(var4)(var2);
                _closure2_slot4 = var4;
                var3 = var4.apply;
                var1 = arguments;
                var2 = var1;
                var1 = this;
                var1 = var3.bind(var4)(var1, var2);
                return var1;
            };
            var _closure2_slot4 = var1;
            var1 = _closure1_slot9;
            var16 = var1.bind(var5)();
            var3 = _closure1_slot5;
            var1 = var3.useState;
            var3 = var1.bind(var3)(var8);
            var1 = _closure1_slot4;
            var7 = 2;
            var1 = var1.bind(var5)(var3, var7);
            var4 = 0;
            var11 = var1[var4];
            _closure2_slot0 = var11;
            var3 = 1;
            var1 = var1[var3];
            _closure2_slot1 = var1;
            var6 = _closure1_slot5;
            var1 = var6.useState;
            var6 = var1.bind(var6)(var8);
            var1 = _closure1_slot4;
            var1 = var1.bind(var5)(var6, var7);
            var22 = var1[var4];
            _closure2_slot2 = var22;
            var1 = var1[var3];
            _closure2_slot3 = var1;
            var4 = _closure1_slot8;
            var3 = _closure1_slot6;
            var1 = {};
            var6 = var16.container;
            var1['style'] = var6;
            var8 = _closure1_slot8;
            var7 = _closure1_slot6;
            var6 = {};
            var9 = var16.content;
            var6['style'] = var9;
            var18 = _closure1_slot8;
            var10 = _closure1_slot6;
            var9 = {};
            var21 = _closure1_slot7;
            var12 = _closure1_slot0;
            var13 = _closure1_slot2;
            var15 = 10;
            var19 = var13[var15];
            var19 = var12.bind(var5)(var19);
            var20 = var19.Text;
            var19 = {'variant': 'heading-lg/bold', 'color': 'mobile-text-heading-primary', 'children': 'Decider'};
            var19 = var21.bind(var5)(var20, var19);
            var20 = new Array(2);
            var20[0] = var19;
            var25 = _closure1_slot7;
            var23 = 11;
            var19 = var13[var23];
            var19 = var12.bind(var5)(var19);
            var24 = var19.RadioGroup;
            var21 = {};
            var19 = true;
            var21['withSpacing'] = var19;
            var21['value'] = var11;
            var26 = _closure1_slot12;
            var21['options'] = var26;
            var26 = function onChange(arg1) {
                _fun0003: for(var _fun0003_ip = 0; ; ) switch(_fun0003_ip) {
case 0:
                    var1 = arg1;
                    var3 = var1.value;
                    var4 = _closure1_slot0;
                    var2 = _closure1_slot2;
                    var1 = 8;
                    var2 = var2[var1];
                    var1 = undefined;
                    var2 = var4.bind(var1)(var2);
                    var2 = var2.CaptchaDeciderType;
                    var2 = var2.HCAPTCHA_RQDATA;
                    if(!(var3 !== var2)) { _fun0003_ip = 16; continue _fun0003 }
case 17:
                    var4 = _closure2_slot3;
                    var2 = null;
                    var2 = var4.bind(var1)(var2);
case 16:
                    var2 = _closure2_slot1;
                    var2 = var2.bind(var1)(var3);
                    return var1;
                }
            };
            var21['onChange'] = var26;
            var21 = var25.bind(var5)(var24, var21);
            var20[1] = var21;
            var9['children'] = var20;
            var10 = var18.bind(var5)(var10, var9);
            var9 = new Array(2);
            var9[0] = var10;
            var10 = 8;
            var10 = var13[var10];
            var10 = var12.bind(var5)(var10);
            var10 = var10.CaptchaDeciderType;
            var10 = var10.HCAPTCHA_RQDATA;
            var10 = var11 === var10;
            if(!var10) { _fun0001_ip = 18; continue _fun0001 }
case 19:
            var13 = _closure1_slot8;
            var12 = _closure1_slot6;
            var11 = {};
            var24 = _closure1_slot7;
            var20 = _closure1_slot0;
            var18 = _closure1_slot2;
            var15 = var18[var15];
            var15 = var20.bind(var5)(var15);
            var21 = var15.Text;
            var15 = {'variant': 'heading-lg/bold', 'color': 'mobile-text-heading-primary', 'children': 'Difficulty'};
            var21 = var24.bind(var5)(var21, var15);
            var15 = new Array(2);
            var15[0] = var21;
            var21 = _closure1_slot7;
            var18 = var18[var23];
            var18 = var20.bind(var5)(var18);
            var20 = var18.RadioGroup;
            var18 = {};
            var18['withSpacing'] = var19;
            var18['value'] = var22;
            var22 = _closure1_slot10;
            var18['options'] = var22;
            var22 = function onChange(arg1) {
                _fun0004: for(var _fun0004_ip = 0; ; ) switch(_fun0004_ip) {
case 0:
                    var1 = arg1;
                    var3 = var1.value;
                    var5 = _closure2_slot0;
                    var6 = _closure1_slot0;
                    var4 = _closure1_slot2;
                    var1 = 8;
                    var4 = var4[var1];
                    var1 = undefined;
                    var4 = var6.bind(var1)(var4);
                    var4 = var4.CaptchaDeciderType;
                    var4 = var4.HCAPTCHA_RQDATA;
                    if(!(var5 === var4)) { _fun0004_ip = 20; continue _fun0004 }
case 21:
                    var2 = _closure2_slot3;
                    var2 = var2.bind(var1)(var3);
case 20:
                    return var1;
                }
            };
            var18['onChange'] = var22;
            var18 = var21.bind(var5)(var20, var18);
            var15[1] = var18;
            var11['children'] = var15;
            var10 = var13.bind(var5)(var12, var11);
case 18:
            var9[1] = var10;
            var6['children'] = var9;
            var7 = var8.bind(var5)(var7, var6);
            var6 = new Array(2);
            var6[0] = var7;
            var9 = _closure1_slot8;
            var8 = _closure1_slot6;
            var7 = {};
            var10 = var16.footerContainer;
            var7['style'] = var10;
            var12 = _closure1_slot7;
            var11 = _closure1_slot6;
            var10 = {};
            var13 = var16.separator;
            var10['style'] = var13;
            var11 = var12.bind(var5)(var11, var10);
            var10 = new Array(2);
            var10[0] = var11;
            var13 = _closure1_slot7;
            var15 = _closure1_slot0;
            var18 = _closure1_slot2;
            var11 = 12;
            var11 = var18[var11];
            var11 = var15.bind(var5)(var11);
            var12 = var11.SafeAreaPaddingView;
            var11 = {};
            var11['bottom'] = var19;
            var16 = var16.footerButton;
            var11['style'] = var16;
            var16 = _closure1_slot7;
            var14 = 13;
            var14 = var18[var14];
            var14 = var15.bind(var5)(var14);
            var15 = var14.Button;
            var14 = {};
            var17 = function sendCaptchaRequest() {
                var1 = undefined;
                var4 = _closure2_slot4;
                var3 = var4.apply;
                var1 = arguments;
                var2 = var1;
                var1 = this;
                var1 = var3.bind(var4)(var1, var2);
                return var1;
            };
            var14['onPress'] = var17;
            var17 = 'Submit';
            var14['text'] = var17;
            var14 = var16.bind(var5)(var15, var14);
            var11['children'] = var14;
            var11 = var13.bind(var5)(var12, var11);
            var10[1] = var11;
            var7['children'] = var10;
            var7 = var9.bind(var5)(var8, var7);
            var6[1] = var7;
            var1['children'] = var6;
            var1 = var4.bind(var5)(var3, var1);
            return var1;
case 2:
            var27 = "Cannot destructure 'undefined' or 'null'.";
            var28 = var2;
            var1 = throwTypeError(var28, var27);
            var1 = undefined;
            throw var1;
        }
    };
    var _closure1_slot15 = var1;
    var8 = global;
    var9 = var8.Object;
    var7 = var9.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var9)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var11.bind(var1)(var4);
    var _closure1_slot3 = var4;
    var14 = 1;
    var4 = var6[var14];
    var4 = var11.bind(var1)(var4);
    var _closure1_slot4 = var4;
    var4 = 2;
    var7 = var6[var4];
    var4 = metroImportAll;
    var4 = var4.bind(var1)(var7);
    var _closure1_slot5 = var4;
    var4 = 3;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.View;
    var _closure1_slot6 = var4;
    var4 = 4;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var7 = var4.jsx;
    var _closure1_slot7 = var7;
    var4 = var4.jsxs;
    var _closure1_slot8 = var4;
    var4 = 5;
    var7 = var6[var4];
    var12 = var5.bind(var1)(var7);
    var9 = var12.createStyles;
    var7 = {};
    var13 = {'flex': 1, 'justifyContent': 'space-between'};
    var10 = 6;
    var15 = var6[var10];
    var15 = var11.bind(var1)(var15);
    var15 = var15.colors;
    var15 = var15.BACKGROUND_BASE_LOW;
    var13['backgroundColor'] = var15;
    var7['container'] = var13;
    var13 = {};
    var13['height'] = var14;
    var14 = var6[var10];
    var14 = var11.bind(var1)(var14);
    var14 = var14.colors;
    var14 = var14.BORDER_SUBTLE;
    var13['backgroundColor'] = var14;
    var14 = var6[var10];
    var14 = var11.bind(var1)(var14);
    var14 = var14.space;
    var14 = var14.PX_24;
    var13['marginVertical'] = var14;
    var7['separator'] = var13;
    var13 = {};
    var14 = var6[var10];
    var14 = var11.bind(var1)(var14);
    var14 = var14.space;
    var14 = var14.PX_16;
    var13['marginBottom'] = var14;
    var7['footerContainer'] = var13;
    var13 = {};
    var14 = var6[var10];
    var14 = var11.bind(var1)(var14);
    var14 = var14.space;
    var14 = var14.PX_16;
    var13['paddingHorizontal'] = var14;
    var7['footerButton'] = var13;
    var13 = {};
    var14 = var6[var10];
    var14 = var11.bind(var1)(var14);
    var14 = var14.space;
    var14 = var14.PX_16;
    var13['margin'] = var14;
    var14 = var6[var10];
    var14 = var11.bind(var1)(var14);
    var14 = var14.space;
    var14 = var14.PX_24;
    var13['gap'] = var14;
    var7['content'] = var13;
    var7 = var9.bind(var12)(var7);
    var _closure1_slot9 = var7;
    var7 = 7;
    var9 = var6[var7];
    var9 = var5.bind(var1)(var9);
    var13 = var9.HCAPTCHA_DIFFICULTY_OPTIONS;
    var12 = var13.map;
    var9 = function(arg1) {
        var1 = arg1;
        var3 = var1.label;
        var2 = var1.value;
        var1 = {};
        var1['name'] = var3;
        var1['value'] = var2;
        return var1;
    };
    var9 = var12.bind(var13)(var9);
    var _closure1_slot10 = var9;
    var12 = var8.Set;
    var9 = 8;
    var8 = var6[var9];
    var8 = var5.bind(var1)(var8);
    var8 = var8.CaptchaDeciderType;
    var13 = var8.HCAPTCHA_RQDATA;
    var8 = new Array(2);
    var8[0] = var13;
    var9 = var6[var9];
    var9 = var5.bind(var1)(var9);
    var9 = var9.CaptchaDeciderType;
    var9 = var9.SMITE_RQDATA;
    var8[1] = var9;
    var9 = var12.prototype;
    var9 = Object.create(var9, {constructor: {value: var12}});
    var19 = var9;
    var18 = var8;
    var8 = new var19[var12](var18, var17);
    var8 = var8 instanceof Object ? var8 : var9;
    var _closure1_slot11 = var8;
    var7 = var6[var7];
    var7 = var5.bind(var1)(var7);
    var9 = var7.CAPTCHA_DECIDER_TYPE_OPTIONS;
    var8 = var9.map;
    var7 = function(arg1) {
        var1 = arg1;
        var3 = var1.label;
        var2 = var1.value;
        var1 = {};
        var1['name'] = var3;
        var1['value'] = var2;
        return var1;
    };
    var9 = var8.bind(var9)(var7);
    var8 = var9.filter;
    var7 = function(arg1) {
        var1 = arg1;
        var3 = var1.value;
        var2 = _closure1_slot11;
        var1 = var2.has;
        var1 = var1.bind(var2)(var3);
        return var1;
    };
    var7 = var8.bind(var9)(var7);
    var _closure1_slot12 = var7;
    var7 = {};
    var8 = 'TEST_CAPTCHA';
    var7['TEST_CAPTCHA'] = var8;
    var _closure1_slot13 = var7;
    var4 = var6[var4];
    var8 = var5.bind(var1)(var4);
    var7 = var8.createStyles;
    var4 = {};
    var9 = {};
    var10 = var6[var10];
    var10 = var11.bind(var1)(var10);
    var10 = var10.colors;
    var10 = var10.BACKGROUND_BASE_LOWER;
    var9['backgroundColor'] = var10;
    var4['headerStyle'] = var9;
    var4 = var7.bind(var8)(var4);
    var _closure1_slot14 = var4;
    var4 = 18;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/captcha/tooling/native/CaptchaTestModal.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function CaptchaTestModal() {
        var2 = _closure1_slot14;
        var4 = undefined;
        var7 = var2.bind(var4)();
        var _closure2_slot0 = var7;
        var6 = _closure1_slot5;
        var3 = var6.useMemo;
        var2 = new Array(1);
        var2[0] = var7;
        var1 = function() {
            var3 = _closure2_slot0;
            var2 = function getScreens(arg1) {
                var1 = {};
                var2 = _closure1_slot13;
                var3 = var2.TEST_CAPTCHA;
                var2 = {};
                var6 = arg1;
                var6 = var6.headerStyle;
                var2['headerStyle'] = var6;
                var6 = 'Captcha Test Tool';
                var2['headerTitle'] = var6;
                var7 = _closure1_slot0;
                var6 = _closure1_slot2;
                var5 = 15;
                var6 = var6[var5];
                var5 = undefined;
                var7 = var7.bind(var5)(var6);
                var6 = var7.getHeaderCloseButton;
                var5 = function closeModal() {
                    var3 = _closure1_slot1;
                    var2 = _closure1_slot2;
                    var1 = 14;
                    var2 = var2[var1];
                    var1 = undefined;
                    var2 = var3.bind(var1)(var2);
                    var1 = var2.pop;
                    var1 = var1.bind(var2)();
                    return var1;
                };
                var5 = var6.bind(var7)(var5);
                var2['headerLeft'] = var5;
                var4 = function render() {
                    var4 = _closure1_slot7;
                    var3 = _closure1_slot15;
                    var2 = undefined;
                    var1 = {};
                    var1 = var4.bind(var2)(var3, var1);
                    return var1;
                };
                var2['render'] = var4;
                var1[2] = var2;
                return var1;
            };
            var1 = undefined;
            var1 = var2.bind(var1)(var3);
            return var1;
        };
        var6 = var3.bind(var6)(var1, var2);
        var3 = _closure1_slot7;
        var8 = _closure1_slot0;
        var9 = _closure1_slot2;
        var1 = 16;
        var1 = var9[var1];
        var1 = var8.bind(var4)(var1);
        var2 = var1.Navigator;
        var1 = {};
        var1['screens'] = var6;
        var5 = _closure1_slot13;
        var5 = var5.TEST_CAPTCHA;
        var1['initialRouteName'] = var5;
        var5 = 17;
        var6 = var9[var5];
        var6 = var8.bind(var4)(var6);
        var7 = var6.intl;
        var6 = var7.string;
        var5 = var9[var5];
        var5 = var8.bind(var4)(var5);
        var5 = var5.t;
        var5 = var5["13/7kX"];
        var5 = var6.bind(var7)(var5);
        var1['headerBackTitle'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var3['default'] = var2;
    return var1;
})();