// app/modules/visual_effect_view/native/VisualEffectViewAndroid.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var6 = require;
    var9 = metroImportDefault;
    var3 = exports;
    var7 = dependencyMap;
    var1 = global;
    var5 = var1.Object;
    var4 = var5.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var4.bind(var5)(var3, var1, var2);
    var1 = 0;
    var2 = var7[var1];
    var1 = undefined;
    var4 = var6.bind(var1)(var2);
    var2 = var4.getSystemVersionMajor;
    var4 = var2.bind(var4)();
    var2 = 31;
    var2 = var4 >= var2;
    var4 = 1;
    var4 = var7[var4];
    var5 = var9.bind(var1)(var4);
    var4 = {};
    var8 = 'DCDVisualEffectView';
    var4['componentName'] = var8;
    var8 = 2;
    var8 = var7[var8];
    var8 = var9.bind(var1)(var8);
    var4['componentFoundInstance'] = var8;
    var4 = var5.bind(var1)(var4);
    var5 = 3;
    var5 = var7[var5];
    var7 = var6.bind(var1)(var5);
    var6 = var7.fileFinishedImporting;
    var5 = 'modules/visual_effect_view/native/VisualEffectViewAndroid.tsx';
    var5 = var6.bind(var7)(var5);
    var3['default'] = var4;
    var3['MODERN_ANDROID_BLURRING_AVAILABLE'] = var2;
    return var1;
})();