// app/modules/visual_effect_view/native/VisualEffectViewAndroid.tsx
export default (function(_, argBar, argBaz, __, ___, argFre, argPlu) {
    oscard = argBar;
    verify = argBaz;
    zuuluu = argFre;
    golfie = argPlu;
    michal = global;
    option = michal.Object;
    report = option.defineProperty;
    tangon = {};
    entity = true;
    tangon['value'] = entity;
    entity = '__esModule';
    entity = report.bind(option)(zuuluu, entity, tangon);
    entity = 0;
    tangon = golfie[entity];
    entity = undefined;
    tangon = oscard.bind(entity)(tangon);
    tangon = tangon.Platform;
    report = michal.parseInt;
    option = tangon.Version;
    michal = michal.HermesInternal;
    tangon = michal.concat;
    michal = '';
    tangon = tangon.bind(michal)(option);
    michal = 10;
    tangon = report.bind(entity)(tangon, michal);
    michal = 31;
    michal = tangon >= michal;
    tangon = 1;
    tangon = golfie[tangon];
    report = verify.bind(entity)(tangon);
    tangon = {};
    option = 'DCDVisualEffectView';
    tangon['componentName'] = option;
    option = 2;
    option = golfie[option];
    option = verify.bind(entity)(option);
    tangon['componentFoundInstance'] = option;
    tangon = report.bind(entity)(tangon);
    report = 3;
    report = golfie[report];
    golfie = oscard.bind(entity)(report);
    oscard = golfie.fileFinishedImporting;
    report = 'modules/visual_effect_view/native/VisualEffectViewAndroid.tsx';
    report = oscard.bind(golfie)(report);
    zuuluu['default'] = tangon;
    zuuluu['MODERN_ANDROID_BLURRING_AVAILABLE'] = michal;
    return entity;
})();