// app/modules/emoji_studio/native/opener.tsx
export default (function(native1, native2, native3, native4, native5, native6, native7) {
    var5 = native2;
    var7 = native3;
    var3 = native6;
    var6 = native7;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var7;
    var _closure1_slot2 = var6;
    var1 = ['analyticsLocation'];
    var _closure1_slot3 = var1;
    var1 = global;
    var9 = var1.Object;
    var8 = var9.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var8.bind(var9)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var7.bind(var1)(var4);
    var _closure1_slot4 = var4;
    var4 = 4;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/emoji_studio/native/opener.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function openEmojiStudio(arg1) {
        var4 = arg1;
        var1 = var4.analyticsLocation;
        var3 = _closure1_slot4;
        var2 = _closure1_slot3;
        var1 = undefined;
        var5 = var3.bind(var1)(var4, var2);
        var4 = _closure1_slot1;
        var2 = _closure1_slot2;
        var3 = 1;
        var3 = var2[var3];
        var4 = var4.bind(var1)(var3);
        var3 = var4.pushLazy;
        var7 = _closure1_slot0;
        var6 = 3;
        var6 = var2[var6];
        var7 = var7.bind(var1)(var6);
        var6 = 2;
        var6 = var2[var6];
        var2 = var2.paths;
        var2 = var7.bind(var1)(var6, var2);
        var2 = var3.bind(var4)(var2, var5);
        return var1;
    };
    var3['openEmojiStudio'] = var2;
    return var1;
})();