// app/modules/relationships/RelationshipConstants.tsx
export default (function(_, argBar, __, ___, ____, argFre, argPlu) {
    zuuluu = argFre;
    entity = global;
    report = entity.Object;
    tangon = report.defineProperty;
    michal = {};
    entity = true;
    michal['value'] = entity;
    entity = '__esModule';
    entity = tangon.bind(report)(zuuluu, entity, michal);
    tangon = {};
    michal = 1;
    tangon['SPAM'] = michal;
    entity = 'SPAM';
    tangon[michal] = entity;
    michal = 2;
    tangon['IGNORED'] = michal;
    entity = 'IGNORED';
    tangon[michal] = entity;
    michal = {};
    entity = 'GOTO_IGNORE';
    michal['GOTO_IGNORE'] = entity;
    entity = 'GOTO_BLOCK';
    michal['GOTO_BLOCK'] = entity;
    entity = 'EXPLORE_FEATURE_GUILD';
    michal['EXPLORE_FEATURE_GUILD'] = entity;
    entity = 'DISMISS_IGNORE';
    michal['DISMISS_IGNORE'] = entity;
    entity = 'DISMISS_BLOCK';
    michal['DISMISS_BLOCK'] = entity;
    entity = 'CANCEL_IGNORE';
    michal['CANCEL_IGNORE'] = entity;
    entity = 'CANCEL_BLOCK';
    michal['CANCEL_BLOCK'] = entity;
    report = argPlu;
    entity = 0;
    oscard = report[entity];
    report = argBar;
    entity = undefined;
    golfie = report.bind(entity)(oscard);
    oscard = golfie.fileFinishedImporting;
    report = 'modules/relationships/RelationshipConstants.tsx';
    report = oscard.bind(golfie)(report);
    zuuluu['ClearFriendRequestFilters'] = tangon;
    zuuluu['UserRemediationAction'] = michal;
    return entity;
})();