// app/modules/guild_settings/integrations/native/GuildSettingsModalIntegrationSettings.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var8 = metroImportDefault;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var8;
    var _closure1_slot2 = var6;
    var1 = function _isNativeReflectConstruct() {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
 0:
 2: // try_start_0
            var2 = global;
            var3 = var2.Boolean;
            var3 = var3.prototype;
            var4 = var3.valueOf;
            var3 = var4.call;
            var8 = var2.Reflect;
            var7 = var8.construct;
            var6 = var2.Boolean;
            var5 = new Array(0);
            var2 = function() {
                var1 = undefined;
                return var1;
            };
            var2 = var7.bind(var8)(var6, var5, var2);
            var2 = var3.bind(var4)(var2);
            var2 = !var2;
            var _closure2_slot0 = var2;
 72: // try_end0
            _fun0001_ip = 76; continue _fun0001;
 74: // catch_target0
            CatchBlockStart(arg_register=1);
 76:
            var2 = function _isNativeReflectConstruct() {
                var1 = _closure2_slot0;
                var1 = !var1;
                var1 = !var1;
                return var1;
            };
            _closure1_slot18 = var2;
            var1 = undefined;
            var1 = var2.bind(var1)();
            return var1;
        }
    };
    var _closure1_slot18 = var1;
    var1 = function GraceOption(arg1) {
        _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
 0:
            var1 = arg1;
            var15 = var1.integration;
            var14 = var1.option;
            var _closure2_slot0 = var14;
            var8 = var1.isLast;
            var1 = var1.onPress;
            var _closure2_slot1 = var1;
            var4 = _closure1_slot14;
            var3 = _closure1_slot8;
            var2 = {};
            var9 = _closure1_slot13;
            var12 = _closure1_slot0;
            var11 = _closure1_slot2;
            var10 = 12;
            var5 = var11[var10];
            var1 = undefined;
            var5 = var12.bind(var1)(var5);
            var6 = var5.FormRow;
            var5 = {};
            var18 = _closure1_slot13;
            var16 = var11[var10];
            var16 = var12.bind(var1)(var16);
            var16 = var16.FormRow;
            var17 = var16.Label;
            var16 = {};
            var19 = var14.label;
            var16['text'] = var19;
            var16 = var18.bind(var1)(var17, var16);
            var5['label'] = var16;
            var13 = function onPress() {
                var3 = _closure2_slot1;
                var1 = _closure2_slot0;
                var2 = var1.value;
                var1 = undefined;
                var1 = var3.bind(var1)(var2);
                return var1;
            };
            var5['onPress'] = var13;
            var13 = _closure1_slot13;
            var11 = var11[var10];
            var11 = var12.bind(var1)(var11);
            var11 = var11.FormRow;
            var12 = var11.Radio;
            var11 = {};
            var15 = var15.expire_grace_period;
            var14 = var14.value;
            var14 = var15 === var14;
            var11['selected'] = var14;
            var11 = var13.bind(var1)(var12, var11);
            var5['leading'] = var11;
            var6 = var9.bind(var1)(var6, var5);
            var5 = new Array(2);
            var5[0] = var6;
            var6 = null;
            if(var8) { _fun0002_ip = 259; continue _fun0002 }
 217:
            var9 = _closure1_slot13;
            var8 = _closure1_slot0;
            var7 = _closure1_slot2;
            var7 = var7[var10];
            var7 = var8.bind(var1)(var7);
            var8 = var7.FormDivider;
            var7 = {};
            var10 = true;
            var7['iconPush'] = var10;
            var6 = var9.bind(var1)(var8, var7);
 259:
            var5[1] = var6;
            var2['children'] = var5;
            var1 = var4.bind(var1)(var3, var2);
            return var1;
        }
    };
    var _closure1_slot19 = var1;
    var1 = function ForceSyncIcon(arg1) {
        _fun0003: for(var _fun0003_ip = 0; ; ) switch(_fun0003_ip) {
 0:
            var2 = arg1;
            var1 = var2.isSyncing;
            var6 = var2.onPress;
            var4 = _closure1_slot0;
            var5 = _closure1_slot2;
            var3 = 11;
            var3 = var5[var3];
            var5 = undefined;
            var7 = var4.bind(var5)(var3);
            var4 = var7.useLegacyClassComponentStyles;
            var3 = _closure1_slot16;
            var9 = var4.bind(var7)(var3);
            var4 = _closure1_slot13;
            if(var1) { _fun0003_ip = 262; continue _fun0003 }
 64:
            var7 = _closure1_slot0;
            var11 = _closure1_slot2;
            var1 = 13;
            var1 = var11[var1];
            var1 = var7.bind(var5)(var1);
            var3 = var1.PressableOpacity;
            var1 = {};
            var8 = 'button';
            var1['accessibilityRole'] = var8;
            var8 = 10;
            var10 = var11[var8];
            var10 = var7.bind(var5)(var10);
            var12 = var10.intl;
            var10 = var12.string;
            var8 = var11[var8];
            var8 = var7.bind(var5)(var8);
            var8 = var8.t;
            var8 = var8.+Joso6;
            var8 = var10.bind(var12)(var8);
            var1['accessibilityLabel'] = var8;
            var1['onPress'] = var6;
            var8 = _closure1_slot13;
            var6 = 12;
            var6 = var11[var6];
            var6 = var7.bind(var5)(var6);
            var6 = var6.FormRow;
            var7 = var6.Icon;
            var6 = {};
            var9 = var9.forceSyncIcon;
            var6['style'] = var9;
            var10 = _closure1_slot1;
            var9 = 14;
            var9 = var11[var9];
            var9 = var10.bind(var5)(var9);
            var6['source'] = var9;
            var9 = 15;
            var9 = var11[var9];
            var9 = var10.bind(var5)(var9);
            var9 = var9.unsafe_rawColors;
            var9 = var9.PRIMARY_500;
            var6['color'] = var9;
            var6 = var8.bind(var5)(var7, var6);
            var1['children'] = var6;
            var1 = var4.bind(var5)(var3, var1);
            _fun0003_ip = 286; continue _fun0003;
 262:
            var3 = _closure1_slot10;
            var2 = {'animating': true, 'size': 'small'};
            var1 = var4.bind(var5)(var3, var2);
 286:
            return var1;
        }
    };
    var _closure1_slot20 = var1;
    var1 = function TwitchEmoticonsRow(arg1) {
        var1 = arg1;
        var8 = var1.integration;
        var9 = var1.onPress;
        var4 = _closure1_slot13;
        var13 = _closure1_slot0;
        var14 = _closure1_slot2;
        var5 = 12;
        var1 = var14[var5];
        var3 = undefined;
        var1 = var13.bind(var3)(var1);
        var2 = var1.FormSection;
        var1 = {};
        var12 = _closure1_slot13;
        var7 = var14[var5];
        var7 = var13.bind(var3)(var7);
        var11 = var7.FormHint;
        var7 = {};
        var10 = 10;
        var15 = var14[var10];
        var15 = var13.bind(var3)(var15);
        var17 = var15.intl;
        var16 = var17.string;
        var15 = var14[var10];
        var15 = var13.bind(var3)(var15);
        var15 = var15.t;
        var15 = var15.7r4OKi;
        var15 = var16.bind(var17)(var15);
        var7['children'] = var15;
        var7 = var12.bind(var3)(var11, var7);
        var1['hint'] = var7;
        var7 = _closure1_slot13;
        var5 = var14[var5];
        var5 = var13.bind(var3)(var5);
        var6 = var5.FormSwitchRow;
        var5 = {};
        var11 = var14[var10];
        var11 = var13.bind(var3)(var11);
        var12 = var11.intl;
        var11 = var12.string;
        var10 = var14[var10];
        var10 = var13.bind(var3)(var10);
        var10 = var10.t;
        var10 = var10.bZBLBg;
        var10 = var11.bind(var12)(var10);
        var5['label'] = var10;
        var10 = var8.enable_emoticons;
        var5['value'] = var10;
        var5['onValueChange'] = var9;
        var8 = var8.syncing;
        var5['disabled'] = var8;
        var5 = var7.bind(var3)(var6, var5);
        var1['children'] = var5;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var _closure1_slot21 = var1;
    var1 = global;
    var9 = var1.Object;
    var7 = var9.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var9)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var8.bind(var1)(var4);
    var _closure1_slot3 = var4;
    var4 = 1;
    var4 = var6[var4];
    var4 = var8.bind(var1)(var4);
    var _closure1_slot4 = var4;
    var4 = 2;
    var4 = var6[var4];
    var4 = var8.bind(var1)(var4);
    var _closure1_slot5 = var4;
    var4 = 3;
    var4 = var6[var4];
    var4 = var8.bind(var1)(var4);
    var _closure1_slot6 = var4;
    var4 = 4;
    var4 = var6[var4];
    var4 = var8.bind(var1)(var4);
    var _closure1_slot7 = var4;
    var4 = 5;
    var7 = var6[var4];
    var4 = metroImportAll;
    var4 = var4.bind(var1)(var7);
    var7 = 6;
    var7 = var6[var7];
    var7 = var5.bind(var1)(var7);
    var9 = var7.View;
    var _closure1_slot8 = var9;
    var9 = var7.Image;
    var _closure1_slot9 = var9;
    var7 = var7.ActivityIndicator;
    var _closure1_slot10 = var7;
    var7 = 7;
    var7 = var6[var7];
    var7 = var8.bind(var1)(var7);
    var _closure1_slot11 = var7;
    var7 = 8;
    var7 = var6[var7];
    var7 = var8.bind(var1)(var7);
    var _closure1_slot12 = var7;
    var7 = 9;
    var7 = var6[var7];
    var7 = var5.bind(var1)(var7);
    var8 = var7.jsx;
    var _closure1_slot13 = var8;
    var8 = var7.jsxs;
    var _closure1_slot14 = var8;
    var7 = var7.Fragment;
    var _closure1_slot15 = var7;
    var7 = 11;
    var7 = var6[var7];
    var9 = var5.bind(var1)(var7);
    var8 = var9.createLegacyClassComponentStyles;
    var7 = {};
    var10 = {};
    var11 = 24;
    var10['fontSize'] = var11;
    var7['integrationLabel'] = var10;
    var10 = {'width': 48, 'height': 48, 'marginRight': 16};
    var7['integrationIcon'] = var10;
    var10 = {};
    var11 = 10;
    var10['marginLeft'] = var11;
    var7['forceSyncIcon'] = var10;
    var10 = {};
    var11 = 'right';
    var10['textAlign'] = var11;
    var7['value'] = var10;
    var7 = var8.bind(var9)(var7);
    var _closure1_slot16 = var7;
    var7 = var4.PureComponent;
    var4 = function(arg1) {
        var4 = function GuildSettingsModalIntegrationSettings(arg1) {
            _fun0004: for(var _fun0004_ip = 0; ; ) switch(_fun0004_ip) {
 0:
                var5 = this;
                var13 = 0;
                var1 = copyRestArgs(var13);
                var8 = _closure1_slot3;
                var3 = _closure2_slot0;
                var4 = undefined;
                var8 = var8.bind(var4)(var5, var3);
                var10 = new Array(0);
                var13 = var10;
                var12 = var1;
                var11 = 0;
                var1 = arraySpread(var13, var12, var11);
                var1 = _closure1_slot6;
                var9 = var1.bind(var4)(var3);
                var3 = _closure1_slot5;
                var1 = _closure1_slot18;
                var1 = var1.bind(var4)();
                if(var1) { _fun0004_ip = 86; continue _fun0004 }
 73:
                var1 = var9.apply;
                var1 = var1.bind(var9)(var5, var10);
                _fun0004_ip = 120; continue _fun0004;
 86:
                var7 = global;
                var8 = var7.Reflect;
                var7 = var8.construct;
                var6 = _closure1_slot6;
                var6 = var6.bind(var4)(var5);
                var6 = var6.constructor;
                var1 = var7.bind(var8)(var9, var10, var6);
 120:
                var1 = var3.bind(var4)(var5, var1);
                var _closure3_slot0 = var1;
                var3 = function(arg1) {
                    var1 = _closure3_slot0;
                    var1 = var1.props;
                    var8 = var1.guildId;
                    var2 = var1.integration;
                    var4 = _closure1_slot1;
                    var3 = _closure1_slot2;
                    var1 = 16;
                    var3 = var3[var1];
                    var1 = undefined;
                    var7 = var4.bind(var1)(var3);
                    var6 = var7.updateIntegration;
                    var12 = var2.id;
                    var10 = var2.expire_grace_period;
                    var9 = var2.enable_emoticons;
                    var11 = arg1;
                    var14 = var7;
                    var13 = var8;
                    var2 = var14[var6](var13, var12, var11, var10, var9, var8);
                    return var1;
                };
                var1['handleExpireBehaviorChange'] = var3;
                var3 = function(arg1) {
                    var1 = _closure3_slot0;
                    var1 = var1.props;
                    var8 = var1.guildId;
                    var2 = var1.integration;
                    var4 = _closure1_slot1;
                    var3 = _closure1_slot2;
                    var1 = 16;
                    var3 = var3[var1];
                    var1 = undefined;
                    var7 = var4.bind(var1)(var3);
                    var6 = var7.updateIntegration;
                    var12 = var2.id;
                    var11 = var2.expire_behavior;
                    var9 = var2.enable_emoticons;
                    var10 = arg1;
                    var14 = var7;
                    var13 = var8;
                    var2 = var14[var6](var13, var12, var11, var10, var9, var8);
                    return var1;
                };
                var1['handleExpireGracePeriodChange'] = var3;
                var3 = function(arg1) {
                    var1 = _closure3_slot0;
                    var1 = var1.props;
                    var8 = var1.guildId;
                    var2 = var1.integration;
                    var4 = _closure1_slot1;
                    var3 = _closure1_slot2;
                    var1 = 16;
                    var3 = var3[var1];
                    var1 = undefined;
                    var7 = var4.bind(var1)(var3);
                    var6 = var7.updateIntegration;
                    var12 = var2.id;
                    var11 = var2.expire_behavior;
                    var10 = var2.expire_grace_period;
                    var9 = arg1;
                    var14 = var7;
                    var13 = var8;
                    var2 = var14[var6](var13, var12, var11, var10, var9, var8);
                    return var1;
                };
                var1['handleToggleEmotes'] = var3;
                var2 = function() {
                    var1 = _closure3_slot0;
                    var1 = var1.props;
                    var5 = var1.guildId;
                    var2 = var1.integration;
                    var4 = _closure1_slot1;
                    var3 = _closure1_slot2;
                    var1 = 16;
                    var3 = var3[var1];
                    var1 = undefined;
                    var4 = var4.bind(var1)(var3);
                    var3 = var4.syncIntegration;
                    var2 = var2.id;
                    var2 = var3.bind(var4)(var5, var2);
                    return var1;
                };
                var1['handleSync'] = var2;
                return var1;
            }
        };
        var _closure2_slot0 = var4;
        var6 = _closure1_slot7;
        var3 = undefined;
        var5 = arg1;
        var5 = var6.bind(var3)(var4, var5);
        var2 = _closure1_slot4;
        var5 = {};
        var6 = 'render';
        var5['key'] = var6;
        var1 = function value() {
            _fun0005: for(var _fun0005_ip = 0; ; ) switch(_fun0005_ip) {
 0:
                var25 = this;
                var _closure3_slot0 = var25;
                var2 = _closure1_slot16;
                var1 = var25.context;
                var4 = undefined;
                var29 = var2.bind(var4)(var1);
                var1 = var25.props;
                var2 = var1.guildRoles;
                var26 = var1.integration;
                var _closure3_slot1 = var26;
                var12 = var1.theme;
                var1 = var26.role_id;
                var28 = null;
                var3 = var28 != var1;
                var14 = null;
                if(!var3) { _fun0005_ip = 76; continue _fun0005 }
 72:
                var14 = var2[var1];
 76:
                var1 = var28 != var14;
                var18 = undefined;
                if(!var1) { _fun0005_ip = 304; continue _fun0005 }
 88:
                var3 = _closure1_slot14;
                var2 = _closure1_slot8;
                var1 = {};
                var9 = _closure1_slot13;
                var11 = _closure1_slot0;
                var16 = _closure1_slot2;
                var7 = 12;
                var5 = var16[var7];
                var5 = var11.bind(var4)(var5);
                var8 = var5.FormDivider;
                var5 = {};
                var8 = var9.bind(var4)(var8, var5);
                var5 = new Array(2);
                var5[0] = var8;
                var9 = _closure1_slot13;
                var7 = var16[var7];
                var7 = var11.bind(var4)(var7);
                var8 = var7.FormRow;
                var7 = {};
                var10 = 10;
                var13 = var16[var10];
                var13 = var11.bind(var4)(var13);
                var17 = var13.intl;
                var13 = var17.string;
                var10 = var16[var10];
                var10 = var11.bind(var4)(var10);
                var10 = var10.t;
                var10 = var10.eBtNBQ;
                var10 = var13.bind(var17)(var10);
                var7['label'] = var10;
                var13 = _closure1_slot13;
                var10 = 17;
                var10 = var16[var10];
                var10 = var11.bind(var4)(var10);
                var11 = var10.Text;
                var10 = {'style': null, 'variant': 'text-md/medium', 'color': 'text-muted'};
                var16 = var29.value;
                var10['style'] = var16;
                var14 = var14.name;
                var10['children'] = var14;
                var10 = var13.bind(var4)(var11, var10);
                var7['trailing'] = var10;
                var7 = var9.bind(var4)(var8, var7);
                var5[1] = var7;
                var1['children'] = var5;
                var18 = var3.bind(var4)(var2, var1);
 304:
                var2 = var26.type;
                var1 = 'youtube';
                if(!(var1 !== var2)) { _fun0005_ip = 461; continue _fun0005 }
 320:
                var3 = var26.name;
                var1 = global;
                var1 = var1.HermesInternal;
                var2 = var1.concat;
                var1 = 'twitch.tv/';
                var21 = var2.bind(var1)(var3);
                var5 = _closure1_slot0;
                var7 = _closure1_slot2;
                var1 = 10;
                var2 = var7[var1];
                var2 = var5.bind(var4)(var2);
                var9 = var2.intl;
                var8 = var9.string;
                var2 = var7[var1];
                var2 = var5.bind(var4)(var2);
                var2 = var2.t;
                var2 = var2.S/WCrK;
                var19 = var8.bind(var9)(var2);
                var1 = var7[var1];
                var1 = var5.bind(var4)(var1);
                var1 = var1.t;
                var30 = var1.RdUTrq;
                var7 = _closure1_slot13;
                var5 = _closure1_slot21;
                var1 = {};
                var1['integration'] = var26;
                var8 = var25.handleToggleEmotes;
                var1['onPress'] = var8;
                var11 = var7.bind(var4)(var5, var1);
                _fun0005_ip = 565; continue _fun0005;
 461:
                var1 = var26.account;
                var2 = var28 == var1;
                var3 = undefined;
                if(var2) { _fun0005_ip = 481; continue _fun0005 }
 476:
                var3 = var1.name;
 481:
                var5 = _closure1_slot0;
                var7 = _closure1_slot2;
                var1 = 10;
                var2 = var7[var1];
                var2 = var5.bind(var4)(var2);
                var9 = var2.intl;
                var8 = var9.string;
                var2 = var7[var1];
                var2 = var5.bind(var4)(var2);
                var2 = var2.t;
                var2 = var2.A5MiqK;
                var19 = var8.bind(var9)(var2);
                var1 = var7[var1];
                var1 = var5.bind(var4)(var1);
                var1 = var1.t;
                var30 = var1.7lNtcX;
                var21 = var3;
                var11 = undefined;
 565:
                var2 = _closure1_slot1;
                var3 = _closure1_slot2;
                var1 = 18;
                var1 = var3[var1];
                var3 = var2.bind(var4)(var1);
                var2 = var3.get;
                var1 = var26.type;
                var9 = var2.bind(var3)(var1);
                var1 = var28 != var9;
                var20 = null;
                if(!var1) { _fun0005_ip = 715; continue _fun0005 }
 609:
                var3 = _closure1_slot13;
                var2 = _closure1_slot9;
                var1 = {};
                var10 = _closure1_slot0;
                var13 = _closure1_slot2;
                var5 = 19;
                var5 = var13[var5];
                var8 = var10.bind(var4)(var5);
                var7 = var8.makeSource;
                var5 = 20;
                var5 = var13[var5];
                var10 = var10.bind(var4)(var5);
                var5 = var10.isThemeDark;
                var5 = var5.bind(var10)(var12);
                var9 = var9.icon;
                if(var5) { _fun0005_ip = 684; continue _fun0005 }
 676:
                var5 = var9.lightPNG;
                _fun0005_ip = 690; continue _fun0005;
 684:
                var5 = var9.darkPNG;
 690:
                var5 = var7.bind(var8)(var5);
                var1['source'] = var5;
                var5 = var29.integrationIcon;
                var1['style'] = var5;
                var20 = var3.bind(var4)(var2, var1);
 715:
                var1 = function getSubGracePeriodOptions() {
                    var3 = [1, 3, 7, 14, 30];
                    var2 = var3.map;
                    var1 = function(arg1) {
                        var6 = arg1;
                        var1 = {};
                        var1['value'] = var6;
                        var7 = _closure1_slot0;
                        var8 = _closure1_slot2;
                        var2 = 10;
                        var4 = var8[var2];
                        var3 = undefined;
                        var4 = var7.bind(var3)(var4);
                        var5 = var4.intl;
                        var4 = var5.formatToPlainString;
                        var2 = var8[var2];
                        var2 = var7.bind(var3)(var2);
                        var2 = var2.t;
                        var3 = var2.eGjmy8;
                        var2 = {};
                        var2['days'] = var6;
                        var2 = var4.bind(var5)(var3, var2);
                        var1['label'] = var2;
                        return var1;
                    };
                    var1 = var2.bind(var3)(var1);
                    return var1;
                };
                var17 = var1.bind(var4)();
                var _closure3_slot2 = var17;
                var3 = _closure1_slot14;
                var2 = _closure1_slot15;
                var1 = {};
                var23 = _closure1_slot0;
                var22 = _closure1_slot2;
                var12 = 12;
                var5 = var22[var12];
                var5 = var23.bind(var4)(var5);
                var8 = var5.Form;
                var5 = {};
                var7 = {};
                var27 = 1;
                var7['flex'] = var27;
                var5['style'] = var7;
                var7 = var25.props;
                var7 = var7.contentContainerStyle;
                var5['contentContainerStyle'] = var7;
                var10 = _closure1_slot13;
                var7 = var22[var12];
                var7 = var23.bind(var4)(var7);
                var9 = var7.FormSection;
                var7 = {};
                var16 = _closure1_slot13;
                var13 = var22[var12];
                var13 = var23.bind(var4)(var13);
                var14 = var13.FormRow;
                var13 = {};
                var24 = _closure1_slot13;
                var22 = var22[var12];
                var22 = var23.bind(var4)(var22);
                var22 = var22.FormRow;
                var23 = var22.Label;
                var22 = {};
                var29 = var29.integrationLabel;
                var22['style'] = var29;
                var32 = var26.user;
                var31 = var28 == var32;
                var29 = undefined;
                if(var31) { _fun0005_ip = 899; continue _fun0005 }
 890:
                var31 = var32.toString;
                var29 = var31.bind(var32)();
 899:
                var22['text'] = var29;
                var22 = var24.bind(var4)(var23, var22);
                var13['label'] = var22;
                var13['subLabel'] = var21;
                var13['leading'] = var20;
                var13 = var16.bind(var4)(var14, var13);
                var7['children'] = var13;
                var7 = var10.bind(var4)(var9, var7);
                var10 = new Array(5);
                var10[0] = var7;
                var13 = _closure1_slot14;
                var23 = _closure1_slot0;
                var32 = _closure1_slot2;
                var7 = var32[var12];
                var7 = var23.bind(var4)(var7);
                var9 = var7.FormSection;
                var7 = {};
                var16 = 10;
                var14 = var32[var16];
                var14 = var23.bind(var4)(var14);
                var21 = var14.intl;
                var20 = var21.string;
                var14 = var32[var16];
                var14 = var23.bind(var4)(var14);
                var14 = var14.t;
                var14 = var14.i17qFR;
                var14 = var20.bind(var21)(var14);
                var7['title'] = var14;
                var21 = _closure1_slot13;
                var14 = var32[var12];
                var14 = var23.bind(var4)(var14);
                var20 = var14.FormRow;
                var14 = {};
                var22 = var32[var16];
                var22 = var23.bind(var4)(var22);
                var29 = var22.intl;
                var24 = var29.format;
                var22 = {};
                var31 = var26.subscriber_count;
                var22['subscribers'] = var31;
                var22 = var24.bind(var29)(var30, var22);
                var14['label'] = var22;
                var22 = var32[var16];
                var22 = var23.bind(var4)(var22);
                var29 = var22.intl;
                var24 = var29.formatToPlainString;
                var22 = var32[var16];
                var22 = var23.bind(var4)(var22);
                var22 = var22.t;
                var23 = var22.+42M+v;
                var22 = {};
                var31 = _closure1_slot1;
                var30 = 21;
                var30 = var32[var30];
                var31 = var31.bind(var4)(var30);
                var30 = var26.synced_at;
                var31 = var31.bind(var4)(var30);
                var30 = var31.calendar;
                var30 = var30.bind(var31)();
                var22['datetime'] = var30;
                var22 = var24.bind(var29)(var23, var22);
                var14['subLabel'] = var22;
                var24 = _closure1_slot13;
                var23 = _closure1_slot20;
                var22 = {};
                var29 = var26.syncing;
                var28 = var28 != var29;
                if(!var28) { _fun0005_ip = 1216; continue _fun0005 }
 1213:
                var28 = var29;
 1216:
                var22['isSyncing'] = var28;
                var25 = var25.handleSync;
                var22['onPress'] = var25;
                var22 = var24.bind(var4)(var23, var22);
                var14['trailing'] = var22;
                var20 = var21.bind(var4)(var20, var14);
                var14 = new Array(2);
                var14[0] = var20;
                var14[1] = var18;
                var7['children'] = var14;
                var7 = var13.bind(var4)(var9, var7);
                var10[1] = var7;
                var18 = _closure1_slot14;
                var7 = _closure1_slot0;
                var9 = _closure1_slot2;
                var13 = var9[var12];
                var13 = var7.bind(var4)(var13);
                var14 = var13.FormSection;
                var13 = {};
                var13['title'] = var19;
                var21 = _closure1_slot13;
                var19 = var9[var12];
                var19 = var7.bind(var4)(var19);
                var20 = var19.FormRow;
                var19 = {};
                var22 = var9[var16];
                var22 = var7.bind(var4)(var22);
                var24 = var22.intl;
                var23 = var24.string;
                var22 = var9[var16];
                var22 = var7.bind(var4)(var22);
                var22 = var22.t;
                var22 = var22.6kpw4u;
                var22 = var23.bind(var24)(var22);
                var19['label'] = var22;
                var22 = function onPress() {
                    var3 = _closure3_slot0;
                    var2 = var3.handleExpireBehaviorChange;
                    var1 = 0;
                    var1 = var2.bind(var3)(var1);
                    return var1;
                };
                var19['onPress'] = var22;
                var24 = _closure1_slot13;
                var22 = var9[var12];
                var22 = var7.bind(var4)(var22);
                var22 = var22.FormRow;
                var23 = var22.Radio;
                var22 = {};
                var28 = var26.expire_behavior;
                var25 = 0;
                var25 = var25 === var28;
                var22['selected'] = var25;
                var22 = var24.bind(var4)(var23, var22);
                var19['leading'] = var22;
                var20 = var21.bind(var4)(var20, var19);
                var19 = new Array(3);
                var19[0] = var20;
                var22 = _closure1_slot13;
                var20 = var9[var12];
                var20 = var7.bind(var4)(var20);
                var21 = var20.FormDivider;
                var20 = {};
                var23 = true;
                var20['iconPush'] = var23;
                var20 = var22.bind(var4)(var21, var20);
                var19[1] = var20;
                var22 = _closure1_slot13;
                var20 = var9[var12];
                var20 = var7.bind(var4)(var20);
                var21 = var20.FormRow;
                var20 = {};
                var23 = var9[var16];
                var23 = var7.bind(var4)(var23);
                var25 = var23.intl;
                var24 = var25.string;
                var23 = var9[var16];
                var23 = var7.bind(var4)(var23);
                var23 = var23.t;
                var23 = var23.fQUQIC;
                var23 = var24.bind(var25)(var23);
                var20['label'] = var23;
                var23 = function onPress() {
                    var3 = _closure3_slot0;
                    var2 = var3.handleExpireBehaviorChange;
                    var1 = 1;
                    var1 = var2.bind(var3)(var1);
                    return var1;
                };
                var20['onPress'] = var23;
                var25 = _closure1_slot13;
                var23 = var9[var12];
                var23 = var7.bind(var4)(var23);
                var23 = var23.FormRow;
                var24 = var23.Radio;
                var23 = {};
                var26 = var26.expire_behavior;
                var26 = var27 === var26;
                var23['selected'] = var26;
                var23 = var25.bind(var4)(var24, var23);
                var20['leading'] = var23;
                var20 = var22.bind(var4)(var21, var20);
                var19[2] = var20;
                var13['children'] = var19;
                var13 = var18.bind(var4)(var14, var13);
                var10[2] = var13;
                var14 = _closure1_slot13;
                var12 = var9[var12];
                var12 = var7.bind(var4)(var12);
                var13 = var12.FormSection;
                var12 = {};
                var18 = var9[var16];
                var18 = var7.bind(var4)(var18);
                var19 = var18.intl;
                var18 = var19.string;
                var16 = var9[var16];
                var16 = var7.bind(var4)(var16);
                var16 = var16.t;
                var16 = var16.uiXMo6;
                var16 = var18.bind(var19)(var16);
                var12['title'] = var16;
                var16 = var17.map;
                var15 = function(arg1, arg2) {
                    var5 = arg2;
                    var4 = _closure1_slot13;
                    var3 = _closure1_slot19;
                    var2 = {};
                    var6 = _closure3_slot1;
                    var2['integration'] = var6;
                    var6 = arg1;
                    var2['option'] = var6;
                    var6 = _closure3_slot2;
                    var7 = var6.length;
                    var6 = 1;
                    var6 = var7 - var6;
                    var6 = var5 === var6;
                    var2['isLast'] = var6;
                    var1 = _closure3_slot0;
                    var1 = var1.handleExpireGracePeriodChange;
                    var2['onPress'] = var1;
                    var1 = undefined;
                    var1 = var4.bind(var1)(var3, var2, var5);
                    return var1;
                };
                var15 = var16.bind(var17)(var15);
                var12['children'] = var15;
                var12 = var14.bind(var4)(var13, var12);
                var10[3] = var12;
                var10[4] = var11;
                var5['children'] = var10;
                var8 = var3.bind(var4)(var8, var5);
                var5 = new Array(2);
                var5[0] = var8;
                var8 = _closure1_slot13;
                var6 = 22;
                var6 = var9[var6];
                var6 = var7.bind(var4)(var6);
                var7 = var6.NavScrim;
                var6 = {};
                var6 = var8.bind(var4)(var7, var6);
                var5[1] = var6;
                var1['children'] = var5;
                var1 = var3.bind(var4)(var2, var1);
                return var1;
            }
        };
        var5['value'] = var1;
        var1 = new Array(1);
        var1[0] = var5;
        var1 = var2.bind(var3)(var4, var1);
        return var1;
    };
    var7 = var4.bind(var1)(var7);
    var _closure1_slot17 = var7;
    var4 = 23;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.ThemeContext;
    var7['contextType'] = var4;
    var4 = 27;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/guild_settings/integrations/native/GuildSettingsModalIntegrationSettings.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function ConnectedGuildSettingsModalIntegrationSettings(arg1) {
        _fun0006: for(var _fun0006_ip = 0; ; ) switch(_fun0006_ip) {
 0:
            var1 = arg1;
            var3 = var1.integrationId;
            var6 = var1.contentContainerStyle;
            var4 = _closure1_slot0;
            var7 = _closure1_slot2;
            var1 = 24;
            var9 = var7[var1];
            var5 = undefined;
            var12 = var4.bind(var5)(var9);
            var11 = var12.useStateFromStores;
            var9 = _closure1_slot12;
            var10 = new Array(1);
            var10[0] = var9;
            var9 = function() {
                var2 = _closure1_slot12;
                var1 = var2.getProps;
                var1 = var1.bind(var2)();
                return var1;
            };
            var9 = var11.bind(var12)(var10, var9);
            var10 = var9.guild;
            var _closure2_slot0 = var10;
            var12 = var9.integrations;
            var1 = var7[var1];
            var11 = var4.bind(var5)(var1);
            var9 = var11.useStateFromStores;
            var1 = _closure1_slot11;
            var4 = new Array(1);
            var4[0] = var1;
            var1 = function() {
                _fun0007: for(var _fun0007_ip = 0; ; ) switch(_fun0007_ip) {
 0:
                    var3 = _closure2_slot0;
                    var1 = null;
                    var3 = var1 != var3;
                    var1 = undefined;
                    if(!var3) { _fun0007_ip = 45; continue _fun0007 }
 18:
                    var4 = _closure1_slot11;
                    var3 = var4.getRolesSnapshot;
                    var2 = _closure2_slot0;
                    var2 = var2.id;
                    var1 = var3.bind(var4)(var2);
 45:
                    return var1;
                }
            };
            var9 = var9.bind(var11)(var4, var1);
            var4 = _closure1_slot1;
            var1 = 25;
            var1 = var7[var1];
            var1 = var4.bind(var5)(var1);
            var7 = var1.bind(var5)();
            var4 = null;
            var11 = var4 == var12;
            var1 = undefined;
            if(var11) { _fun0006_ip = 174; continue _fun0006 }
 157:
            var11 = var12.filter;
            var8 = function(arg1) {
                var3 = _closure1_slot0;
                var2 = _closure1_slot2;
                var1 = 26;
                var2 = var2[var1];
                var1 = undefined;
                var1 = var3.bind(var1)(var2);
                var3 = var1.SUPPORTED_SETTINGS_INTEGRATION_PLATFORMS;
                var2 = var3.includes;
                var1 = arg1;
                var1 = var1.type;
                var1 = var2.bind(var3)(var1);
                return var1;
            };
            var1 = var11.bind(var12)(var8);
 174:
            var11 = var4 == var1;
            var8 = undefined;
            if(var11) { _fun0006_ip = 187; continue _fun0006 }
 183:
            var8 = var1[var3];
 187:
            var3 = var4 == var10;
            var1 = null;
            if(var3) { _fun0006_ip = 259; continue _fun0006 }
 196:
            var3 = var4 == var8;
            var1 = null;
            if(var3) { _fun0006_ip = 259; continue _fun0006 }
 205:
            var3 = var4 == var9;
            var1 = null;
            if(var3) { _fun0006_ip = 259; continue _fun0006 }
 214:
            var4 = _closure1_slot13;
            var3 = _closure1_slot17;
            var2 = {};
            var10 = var10.id;
            var2['guildId'] = var10;
            var2['guildRoles'] = var9;
            var2['integration'] = var8;
            var2['theme'] = var7;
            var2['contentContainerStyle'] = var6;
            var1 = var4.bind(var5)(var3, var2);
 259:
            return var1;
        }
    };
    var3['default'] = var2;
    return var1;
})();