// app/modules/guild_settings/integrations/native/GuildSettingsModalIntegrationSettings.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var8 = metroImportDefault;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var8;
    var _closure1_slot2 = var6;
    var1 = function _isNativeReflectConstruct() {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
case 2: // try_start_0
            var2 = global;
            var3 = var2.Boolean;
            var3 = var3.prototype;
            var4 = var3.valueOf;
            var3 = var4.call;
            var8 = var2.Reflect;
            var7 = var8.construct;
            var6 = var2.Boolean;
            var5 = new Array(0);
            var2 = function() {
                var1 = undefined;
                return var1;
            };
            var2 = var7.bind(var8)(var6, var5, var2);
            var2 = var3.bind(var4)(var2);
            var2 = !var2;
            var _closure2_slot0 = var2;
case 3: // try_end0
            _fun0001_ip = 4; continue _fun0001;
case 5: // catch_target0
            CatchBlockStart(arg_register=1);
case 4:
            var2 = function _isNativeReflectConstruct() {
                var1 = _closure2_slot0;
                var1 = !var1;
                var1 = !var1;
                return var1;
            };
            _closure1_slot22 = var2;
            var1 = undefined;
            var1 = var2.bind(var1)();
            return var1;
        }
    };
    var _closure1_slot22 = var1;
    var1 = function GraceOption(arg1) {
        _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
case 0:
            var1 = arg1;
            var14 = var1.integration;
            var13 = var1.option;
            var _closure2_slot0 = var13;
            var8 = var1.isLast;
            var1 = var1.onPress;
            var _closure2_slot1 = var1;
            var4 = _closure1_slot13;
            var3 = _closure1_slot8;
            var2 = {};
            var9 = _closure1_slot12;
            var11 = _closure1_slot0;
            var15 = _closure1_slot2;
            var10 = 13;
            var5 = var15[var10];
            var1 = undefined;
            var5 = var11.bind(var1)(var5);
            var6 = var5.FormRow;
            var5 = {};
            var18 = _closure1_slot12;
            var16 = var15[var10];
            var16 = var11.bind(var1)(var16);
            var16 = var16.FormRow;
            var17 = var16.Label;
            var16 = {};
            var19 = var13.label;
            var16['text'] = var19;
            var16 = var18.bind(var1)(var17, var16);
            var5['label'] = var16;
            var12 = function onPress() {
                var3 = _closure2_slot1;
                var1 = _closure2_slot0;
                var2 = var1.value;
                var1 = undefined;
                var1 = var3.bind(var1)(var2);
                return var1;
            };
            var5['onPress'] = var12;
            var12 = _closure1_slot12;
            var10 = var15[var10];
            var10 = var11.bind(var1)(var10);
            var10 = var10.FormRow;
            var11 = var10.Radio;
            var10 = {};
            var14 = var14.expire_grace_period;
            var13 = var13.value;
            var13 = var14 === var13;
            var10['selected'] = var13;
            var10 = var12.bind(var1)(var11, var10);
            var5['leading'] = var10;
            var6 = var9.bind(var1)(var6, var5);
            var5 = new Array(2);
            var5[0] = var6;
            var6 = null;
            if(var8) { _fun0002_ip = 6; continue _fun0002 }
case 7:
            var6 = _closure1_slot16;
case 6:
            var5[1] = var6;
            var2['children'] = var5;
            var1 = var4.bind(var1)(var3, var2);
            return var1;
        }
    };
    var _closure1_slot23 = var1;
    var1 = function ForceSyncIcon(arg1) {
        _fun0003: for(var _fun0003_ip = 0; ; ) switch(_fun0003_ip) {
case 0:
            var2 = arg1;
            var1 = var2.isSyncing;
            var6 = var2.onPress;
            var4 = _closure1_slot0;
            var5 = _closure1_slot2;
            var3 = 12;
            var3 = var5[var3];
            var5 = undefined;
            var7 = var4.bind(var5)(var3);
            var4 = var7.useLegacyClassComponentStyles;
            var3 = _closure1_slot15;
            var9 = var4.bind(var7)(var3);
            if(var1) { _fun0003_ip = 8; continue _fun0003 }
case 9:
            var4 = _closure1_slot12;
            var7 = _closure1_slot0;
            var11 = _closure1_slot2;
            var1 = 14;
            var1 = var11[var1];
            var1 = var7.bind(var5)(var1);
            var3 = var1.PressableOpacity;
            var1 = {};
            var8 = 'button';
            var1['accessibilityRole'] = var8;
            var8 = 11;
            var10 = var11[var8];
            var10 = var7.bind(var5)(var10);
            var12 = var10.intl;
            var10 = var12.string;
            var8 = var11[var8];
            var8 = var7.bind(var5)(var8);
            var8 = var8.t;
            var8 = var8.+Josox;
            var8 = var10.bind(var12)(var8);
            var1['accessibilityLabel'] = var8;
            var1['onPress'] = var6;
            var8 = _closure1_slot12;
            var6 = 13;
            var6 = var11[var6];
            var6 = var7.bind(var5)(var6);
            var6 = var6.FormRow;
            var7 = var6.Icon;
            var6 = {};
            var9 = var9.forceSyncIcon;
            var6['style'] = var9;
            var10 = _closure1_slot1;
            var9 = 15;
            var9 = var11[var9];
            var9 = var10.bind(var5)(var9);
            var6['source'] = var9;
            var9 = 16;
            var9 = var11[var9];
            var9 = var10.bind(var5)(var9);
            var9 = var9.unsafe_rawColors;
            var9 = var9.PRIMARY_500;
            var6['color'] = var9;
            var6 = var8.bind(var5)(var7, var6);
            var1['children'] = var6;
            var1 = var4.bind(var5)(var3, var1);
            _fun0003_ip = 10; continue _fun0003;
case 8:
            var1 = _closure1_slot17;
case 10:
            return var1;
        }
    };
    var _closure1_slot24 = var1;
    var1 = function TwitchEmoticonsRow(arg1) {
        var1 = arg1;
        var8 = var1.integration;
        var9 = var1.onPress;
        var4 = _closure1_slot12;
        var13 = _closure1_slot0;
        var14 = _closure1_slot2;
        var5 = 13;
        var1 = var14[var5];
        var3 = undefined;
        var1 = var13.bind(var3)(var1);
        var2 = var1.FormSection;
        var1 = {};
        var12 = _closure1_slot12;
        var7 = var14[var5];
        var7 = var13.bind(var3)(var7);
        var11 = var7.FormHint;
        var7 = {};
        var10 = 11;
        var15 = var14[var10];
        var15 = var13.bind(var3)(var15);
        var17 = var15.intl;
        var16 = var17.string;
        var15 = var14[var10];
        var15 = var13.bind(var3)(var15);
        var15 = var15.t;
        var15 = var15.7r4OKg;
        var15 = var16.bind(var17)(var15);
        var7['children'] = var15;
        var7 = var12.bind(var3)(var11, var7);
        var1['hint'] = var7;
        var7 = _closure1_slot12;
        var5 = var14[var5];
        var5 = var13.bind(var3)(var5);
        var6 = var5.FormSwitchRow;
        var5 = {};
        var11 = var14[var10];
        var11 = var13.bind(var3)(var11);
        var12 = var11.intl;
        var11 = var12.string;
        var10 = var14[var10];
        var10 = var13.bind(var3)(var10);
        var10 = var10.t;
        var10 = var10.bZBLBs;
        var10 = var11.bind(var12)(var10);
        var5['label'] = var10;
        var10 = var8.enable_emoticons;
        var5['value'] = var10;
        var5['onValueChange'] = var9;
        var8 = var8.syncing;
        var5['disabled'] = var8;
        var5 = var7.bind(var3)(var6, var5);
        var1['children'] = var5;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var _closure1_slot25 = var1;
    var1 = global;
    var9 = var1.Object;
    var7 = var9.defineProperty;
    var4 = {};
    var10 = true;
    var4['value'] = var10;
    var1 = '__esModule';
    var1 = var7.bind(var9)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var8.bind(var1)(var4);
    var _closure1_slot3 = var4;
    var4 = 1;
    var4 = var6[var4];
    var4 = var8.bind(var1)(var4);
    var _closure1_slot4 = var4;
    var4 = 2;
    var4 = var6[var4];
    var4 = var8.bind(var1)(var4);
    var _closure1_slot5 = var4;
    var4 = 3;
    var4 = var6[var4];
    var4 = var8.bind(var1)(var4);
    var _closure1_slot6 = var4;
    var4 = 4;
    var4 = var6[var4];
    var4 = var8.bind(var1)(var4);
    var _closure1_slot7 = var4;
    var4 = 5;
    var7 = var6[var4];
    var4 = metroImportAll;
    var4 = var4.bind(var1)(var7);
    var7 = 6;
    var7 = var6[var7];
    var7 = var5.bind(var1)(var7);
    var9 = var7.View;
    var _closure1_slot8 = var9;
    var9 = var7.Image;
    var _closure1_slot9 = var9;
    var11 = var7.ActivityIndicator;
    var7 = 7;
    var7 = var6[var7];
    var7 = var8.bind(var1)(var7);
    var _closure1_slot10 = var7;
    var7 = 8;
    var7 = var6[var7];
    var7 = var8.bind(var1)(var7);
    var _closure1_slot11 = var7;
    var7 = 9;
    var7 = var6[var7];
    var7 = var5.bind(var1)(var7);
    var9 = var7.jsx;
    var _closure1_slot12 = var9;
    var8 = var7.jsxs;
    var _closure1_slot13 = var8;
    var7 = var7.Fragment;
    var _closure1_slot14 = var7;
    var7 = 12;
    var7 = var6[var7];
    var12 = var5.bind(var1)(var7);
    var8 = var12.createLegacyClassComponentStyles;
    var7 = {};
    var13 = {};
    var14 = 24;
    var13['fontSize'] = var14;
    var7['integrationLabel'] = var13;
    var13 = {'width': 48, 'height': 48, 'marginRight': 16};
    var7['integrationIcon'] = var13;
    var13 = {};
    var14 = 10;
    var13['marginLeft'] = var14;
    var7['forceSyncIcon'] = var13;
    var13 = {};
    var14 = 'right';
    var13['textAlign'] = var14;
    var7['value'] = var13;
    var7 = var8.bind(var12)(var7);
    var _closure1_slot15 = var7;
    var7 = 13;
    var8 = var6[var7];
    var8 = var5.bind(var1)(var8);
    var12 = var8.FormDivider;
    var8 = {};
    var8['iconPush'] = var10;
    var8 = var9.bind(var1)(var12, var8);
    var _closure1_slot16 = var8;
    var8 = {'animating': true, 'size': 'small'};
    var8 = var9.bind(var1)(var11, var8);
    var _closure1_slot17 = var8;
    var8 = var6[var7];
    var8 = var5.bind(var1)(var8);
    var11 = var8.FormDivider;
    var8 = {};
    var8 = var9.bind(var1)(var11, var8);
    var _closure1_slot18 = var8;
    var7 = var6[var7];
    var7 = var5.bind(var1)(var7);
    var8 = var7.FormDivider;
    var7 = {};
    var7['iconPush'] = var10;
    var7 = var9.bind(var1)(var8, var7);
    var _closure1_slot19 = var7;
    var7 = 17;
    var7 = var6[var7];
    var7 = var5.bind(var1)(var7);
    var8 = var7.NavScrim;
    var7 = {};
    var7 = var9.bind(var1)(var8, var7);
    var _closure1_slot20 = var7;
    var7 = var4.PureComponent;
    var4 = function(arg1) {
        var4 = function GuildSettingsModalIntegrationSettings(arg1) {
            _fun0004: for(var _fun0004_ip = 0; ; ) switch(_fun0004_ip) {
case 0:
                var5 = this;
                var13 = 0;
                var1 = copyRestArgs(var13);
                var8 = _closure1_slot3;
                var3 = _closure2_slot0;
                var4 = undefined;
                var8 = var8.bind(var4)(var5, var3);
                var10 = new Array(0);
                var13 = var10;
                var12 = var1;
                var11 = 0;
                var1 = arraySpread(var13, var12, var11);
                var1 = _closure1_slot6;
                var9 = var1.bind(var4)(var3);
                var3 = _closure1_slot5;
                var1 = _closure1_slot22;
                var1 = var1.bind(var4)();
                if(var1) { _fun0004_ip = 11; continue _fun0004 }
case 12:
                var1 = var9.apply;
                var1 = var1.bind(var9)(var5, var10);
                _fun0004_ip = 13; continue _fun0004;
case 11:
                var7 = global;
                var8 = var7.Reflect;
                var7 = var8.construct;
                var6 = _closure1_slot6;
                var6 = var6.bind(var4)(var5);
                var6 = var6.constructor;
                var1 = var7.bind(var8)(var9, var10, var6);
case 13:
                var1 = var3.bind(var4)(var5, var1);
                var _closure3_slot0 = var1;
                var3 = function(arg1) {
                    var1 = _closure3_slot0;
                    var1 = var1.props;
                    var8 = var1.guildId;
                    var2 = var1.integration;
                    var4 = _closure1_slot1;
                    var3 = _closure1_slot2;
                    var1 = 18;
                    var3 = var3[var1];
                    var1 = undefined;
                    var7 = var4.bind(var1)(var3);
                    var6 = var7.updateIntegration;
                    var12 = var2.id;
                    var10 = var2.expire_grace_period;
                    var9 = var2.enable_emoticons;
                    var11 = arg1;
                    var14 = var7;
                    var13 = var8;
                    var2 = var14[var6](var13, var12, var11, var10, var9, var8);
                    return var1;
                };
                var1['handleExpireBehaviorChange'] = var3;
                var3 = function(arg1) {
                    var1 = _closure3_slot0;
                    var1 = var1.props;
                    var8 = var1.guildId;
                    var2 = var1.integration;
                    var4 = _closure1_slot1;
                    var3 = _closure1_slot2;
                    var1 = 18;
                    var3 = var3[var1];
                    var1 = undefined;
                    var7 = var4.bind(var1)(var3);
                    var6 = var7.updateIntegration;
                    var12 = var2.id;
                    var11 = var2.expire_behavior;
                    var9 = var2.enable_emoticons;
                    var10 = arg1;
                    var14 = var7;
                    var13 = var8;
                    var2 = var14[var6](var13, var12, var11, var10, var9, var8);
                    return var1;
                };
                var1['handleExpireGracePeriodChange'] = var3;
                var3 = function(arg1) {
                    var1 = _closure3_slot0;
                    var1 = var1.props;
                    var8 = var1.guildId;
                    var2 = var1.integration;
                    var4 = _closure1_slot1;
                    var3 = _closure1_slot2;
                    var1 = 18;
                    var3 = var3[var1];
                    var1 = undefined;
                    var7 = var4.bind(var1)(var3);
                    var6 = var7.updateIntegration;
                    var12 = var2.id;
                    var11 = var2.expire_behavior;
                    var10 = var2.expire_grace_period;
                    var9 = arg1;
                    var14 = var7;
                    var13 = var8;
                    var2 = var14[var6](var13, var12, var11, var10, var9, var8);
                    return var1;
                };
                var1['handleToggleEmotes'] = var3;
                var2 = function() {
                    var1 = _closure3_slot0;
                    var1 = var1.props;
                    var5 = var1.guildId;
                    var2 = var1.integration;
                    var4 = _closure1_slot1;
                    var3 = _closure1_slot2;
                    var1 = 18;
                    var3 = var3[var1];
                    var1 = undefined;
                    var4 = var4.bind(var1)(var3);
                    var3 = var4.syncIntegration;
                    var2 = var2.id;
                    var2 = var3.bind(var4)(var5, var2);
                    return var1;
                };
                var1['handleSync'] = var2;
                return var1;
            }
        };
        var _closure2_slot0 = var4;
        var6 = _closure1_slot7;
        var3 = undefined;
        var5 = arg1;
        var5 = var6.bind(var3)(var4, var5);
        var2 = _closure1_slot4;
        var5 = {};
        var6 = 'render';
        var5['key'] = var6;
        var1 = function value() {
            _fun0005: for(var _fun0005_ip = 0; ; ) switch(_fun0005_ip) {
case 0:
                var25 = this;
                var _closure3_slot0 = var25;
                var2 = _closure1_slot15;
                var1 = var25.context;
                var4 = undefined;
                var29 = var2.bind(var4)(var1);
                var1 = var25.props;
                var2 = var1.guildRoles;
                var27 = var1.integration;
                var _closure3_slot1 = var27;
                var12 = var1.theme;
                var1 = var27.role_id;
                var26 = null;
                var3 = var26 != var1;
                var15 = null;
                if(!var3) { _fun0005_ip = 4; continue _fun0005 }
case 3:
                var15 = var2[var1];
case 4:
                var1 = var26 != var15;
                var18 = undefined;
                if(!var1) { _fun0005_ip = 14; continue _fun0005 }
case 15:
                var3 = _closure1_slot13;
                var2 = _closure1_slot8;
                var1 = {};
                var7 = _closure1_slot18;
                var5 = new Array(2);
                var5[0] = var7;
                var9 = _closure1_slot12;
                var11 = _closure1_slot0;
                var16 = _closure1_slot2;
                var7 = 13;
                var7 = var16[var7];
                var7 = var11.bind(var4)(var7);
                var8 = var7.FormRow;
                var7 = {};
                var10 = 11;
                var14 = var16[var10];
                var14 = var11.bind(var4)(var14);
                var17 = var14.intl;
                var14 = var17.string;
                var10 = var16[var10];
                var10 = var11.bind(var4)(var10);
                var10 = var10.t;
                var10 = var10.eBtNBa;
                var10 = var14.bind(var17)(var10);
                var7['label'] = var10;
                var14 = _closure1_slot12;
                var10 = 19;
                var10 = var16[var10];
                var10 = var11.bind(var4)(var10);
                var11 = var10.Text;
                var10 = {'style': null, 'variant': 'text-md/medium', 'color': 'text-muted'};
                var16 = var29.value;
                var10['style'] = var16;
                var15 = var15.name;
                var10['children'] = var15;
                var10 = var14.bind(var4)(var11, var10);
                var7['trailing'] = var10;
                var7 = var9.bind(var4)(var8, var7);
                var5[1] = var7;
                var1['children'] = var5;
                var18 = var3.bind(var4)(var2, var1);
case 14:
                var2 = var27.type;
                var1 = 'youtube';
                if(!(var1 !== var2)) { _fun0005_ip = 16; continue _fun0005 }
case 17:
                var3 = var27.name;
                var1 = global;
                var1 = var1.HermesInternal;
                var2 = var1.concat;
                var1 = 'twitch.tv/';
                var21 = var2.bind(var1)(var3);
                var5 = _closure1_slot0;
                var7 = _closure1_slot2;
                var1 = 11;
                var2 = var7[var1];
                var2 = var5.bind(var4)(var2);
                var9 = var2.intl;
                var8 = var9.string;
                var2 = var7[var1];
                var2 = var5.bind(var4)(var2);
                var2 = var2.t;
                var2 = var2.S/WCrG;
                var17 = var8.bind(var9)(var2);
                var1 = var7[var1];
                var1 = var5.bind(var4)(var1);
                var1 = var1.t;
                var28 = var1.RdUTrl;
                var7 = _closure1_slot12;
                var5 = _closure1_slot25;
                var1 = {};
                var1['integration'] = var27;
                var8 = var25.handleToggleEmotes;
                var1['onPress'] = var8;
                var9 = var7.bind(var4)(var5, var1);
                _fun0005_ip = 18; continue _fun0005;
case 16:
                var1 = var27.account;
                var2 = var26 == var1;
                var3 = undefined;
                if(var2) { _fun0005_ip = 19; continue _fun0005 }
case 20:
                var3 = var1.name;
case 19:
                var5 = _closure1_slot0;
                var7 = _closure1_slot2;
                var1 = 11;
                var2 = var7[var1];
                var2 = var5.bind(var4)(var2);
                var10 = var2.intl;
                var8 = var10.string;
                var2 = var7[var1];
                var2 = var5.bind(var4)(var2);
                var2 = var2.t;
                var2 = var2.A5MiqO;
                var17 = var8.bind(var10)(var2);
                var1 = var7[var1];
                var1 = var5.bind(var4)(var1);
                var1 = var1.t;
                var28 = var1.7lNtce;
                var21 = var3;
                var9 = undefined;
case 18:
                var2 = _closure1_slot1;
                var3 = _closure1_slot2;
                var1 = 20;
                var1 = var3[var1];
                var3 = var2.bind(var4)(var1);
                var2 = var3.get;
                var1 = var27.type;
                var10 = var2.bind(var3)(var1);
                var1 = var26 != var10;
                var20 = null;
                if(!var1) { _fun0005_ip = 21; continue _fun0005 }
case 22:
                var3 = _closure1_slot12;
                var2 = _closure1_slot9;
                var1 = {};
                var11 = _closure1_slot0;
                var14 = _closure1_slot2;
                var5 = 21;
                var5 = var14[var5];
                var8 = var11.bind(var4)(var5);
                var7 = var8.makeSource;
                var5 = 22;
                var5 = var14[var5];
                var11 = var11.bind(var4)(var5);
                var5 = var11.isThemeDark;
                var5 = var5.bind(var11)(var12);
                var10 = var10.icon;
                if(var5) { _fun0005_ip = 23; continue _fun0005 }
case 24:
                var5 = var10.lightPNG;
                _fun0005_ip = 25; continue _fun0005;
case 23:
                var5 = var10.darkPNG;
case 25:
                var5 = var7.bind(var8)(var5);
                var1['source'] = var5;
                var5 = var29.integrationIcon;
                var1['style'] = var5;
                var20 = var3.bind(var4)(var2, var1);
case 21:
                var1 = function getSubGracePeriodOptions() {
                    var2 = global;
                    var4 = var2.Object;
                    var3 = var4.values;
                    var6 = _closure1_slot0;
                    var5 = _closure1_slot2;
                    var2 = 10;
                    var5 = var5[var2];
                    var2 = undefined;
                    var2 = var6.bind(var2)(var5);
                    var2 = var2.IntegrationExpireGracePeriodTypes;
                    var4 = var3.bind(var4)(var2);
                    var3 = var4.filter;
                    var2 = function(arg1) {
                        var1 = global;
                        var3 = var1.Number;
                        var2 = var3.isInteger;
                        var1 = arg1;
                        var1 = var2.bind(var3)(var1);
                        return var1;
                    };
                    var3 = var3.bind(var4)(var2);
                    var2 = var3.map;
                    var1 = function(arg1) {
                        var6 = arg1;
                        var1 = {};
                        var1['value'] = var6;
                        var7 = _closure1_slot0;
                        var8 = _closure1_slot2;
                        var2 = 11;
                        var4 = var8[var2];
                        var3 = undefined;
                        var4 = var7.bind(var3)(var4);
                        var5 = var4.intl;
                        var4 = var5.formatToPlainString;
                        var2 = var8[var2];
                        var2 = var7.bind(var3)(var2);
                        var2 = var2.t;
                        var3 = var2.eGjmy5;
                        var2 = {};
                        var2['days'] = var6;
                        var2 = var4.bind(var5)(var3, var2);
                        var1['label'] = var2;
                        return var1;
                    };
                    var1 = var2.bind(var3)(var1);
                    return var1;
                };
                var15 = var1.bind(var4)();
                var _closure3_slot2 = var15;
                var3 = _closure1_slot13;
                var2 = _closure1_slot14;
                var1 = {};
                var23 = _closure1_slot0;
                var22 = _closure1_slot2;
                var10 = 13;
                var5 = var22[var10];
                var5 = var23.bind(var4)(var5);
                var7 = var5.Form;
                var5 = {};
                var8 = {};
                var11 = 1;
                var8['flex'] = var11;
                var5['style'] = var8;
                var8 = var25.props;
                var8 = var8.contentContainerStyle;
                var5['contentContainerStyle'] = var8;
                var12 = _closure1_slot12;
                var8 = var22[var10];
                var8 = var23.bind(var4)(var8);
                var11 = var8.FormSection;
                var8 = {};
                var19 = _closure1_slot12;
                var14 = var22[var10];
                var14 = var23.bind(var4)(var14);
                var16 = var14.FormRow;
                var14 = {};
                var24 = _closure1_slot12;
                var22 = var22[var10];
                var22 = var23.bind(var4)(var22);
                var22 = var22.FormRow;
                var23 = var22.Label;
                var22 = {};
                var29 = var29.integrationLabel;
                var22['style'] = var29;
                var31 = var27.user;
                var30 = var26 == var31;
                var29 = undefined;
                if(var30) { _fun0005_ip = 26; continue _fun0005 }
case 27:
                var30 = var31.toString;
                var29 = var30.bind(var31)();
case 26:
                var22['text'] = var29;
                var22 = var24.bind(var4)(var23, var22);
                var14['label'] = var22;
                var14['subLabel'] = var21;
                var14['leading'] = var20;
                var14 = var19.bind(var4)(var16, var14);
                var8['children'] = var14;
                var11 = var12.bind(var4)(var11, var8);
                var8 = new Array(5);
                var8[0] = var11;
                var14 = _closure1_slot13;
                var23 = _closure1_slot0;
                var22 = _closure1_slot2;
                var11 = var22[var10];
                var11 = var23.bind(var4)(var11);
                var12 = var11.FormSection;
                var11 = {};
                var19 = 11;
                var16 = var22[var19];
                var16 = var23.bind(var4)(var16);
                var21 = var16.intl;
                var20 = var21.string;
                var16 = var22[var19];
                var16 = var23.bind(var4)(var16);
                var16 = var16.t;
                var16 = var16.i17qFc;
                var16 = var20.bind(var21)(var16);
                var11['title'] = var16;
                var21 = _closure1_slot12;
                var16 = var22[var10];
                var16 = var23.bind(var4)(var16);
                var20 = var16.FormRow;
                var16 = {};
                var22 = var22[var19];
                var22 = var23.bind(var4)(var22);
                var24 = var22.intl;
                var23 = var24.format;
                var22 = {};
                var30 = var27.subscriber_count;
                var31 = var26 != var30;
                var29 = '';
                if(!var31) { _fun0005_ip = 28; continue _fun0005 }
case 29:
                var29 = var30;
case 28:
                var22['subscribers'] = var29;
                var22 = var23.bind(var24)(var28, var22);
                var16['label'] = var22;
                var23 = _closure1_slot0;
                var31 = _closure1_slot2;
                var22 = var31[var19];
                var22 = var23.bind(var4)(var22);
                var28 = var22.intl;
                var24 = var28.formatToPlainString;
                var22 = var31[var19];
                var22 = var23.bind(var4)(var22);
                var22 = var22.t;
                var23 = var22.+42M+u;
                var22 = {};
                var30 = _closure1_slot1;
                var29 = 23;
                var29 = var31[var29];
                var30 = var30.bind(var4)(var29);
                var29 = var27.synced_at;
                var30 = var30.bind(var4)(var29);
                var29 = var30.calendar;
                var29 = var29.bind(var30)();
                var22['datetime'] = var29;
                var22 = var24.bind(var28)(var23, var22);
                var16['subLabel'] = var22;
                var24 = _closure1_slot12;
                var23 = _closure1_slot24;
                var22 = {};
                var28 = var27.syncing;
                var26 = var26 != var28;
                if(!var26) { _fun0005_ip = 30; continue _fun0005 }
case 31:
                var26 = var28;
case 30:
                var22['isSyncing'] = var26;
                var25 = var25.handleSync;
                var22['onPress'] = var25;
                var22 = var24.bind(var4)(var23, var22);
                var16['trailing'] = var22;
                var20 = var21.bind(var4)(var20, var16);
                var16 = new Array(2);
                var16[0] = var20;
                var16[1] = var18;
                var11['children'] = var16;
                var11 = var14.bind(var4)(var12, var11);
                var8[1] = var11;
                var16 = _closure1_slot13;
                var18 = _closure1_slot0;
                var14 = _closure1_slot2;
                var11 = var14[var10];
                var11 = var18.bind(var4)(var11);
                var12 = var11.FormSection;
                var11 = {};
                var11['title'] = var17;
                var21 = _closure1_slot12;
                var17 = var14[var10];
                var17 = var18.bind(var4)(var17);
                var20 = var17.FormRow;
                var17 = {};
                var22 = var14[var19];
                var22 = var18.bind(var4)(var22);
                var24 = var22.intl;
                var23 = var24.string;
                var22 = var14[var19];
                var22 = var18.bind(var4)(var22);
                var22 = var22.t;
                var22 = var22.6kpw4i;
                var22 = var23.bind(var24)(var22);
                var17['label'] = var22;
                var22 = function onPress() {
                    var3 = _closure3_slot0;
                    var2 = var3.handleExpireBehaviorChange;
                    var5 = _closure1_slot0;
                    var4 = _closure1_slot2;
                    var1 = 24;
                    var4 = var4[var1];
                    var1 = undefined;
                    var1 = var5.bind(var1)(var4);
                    var1 = var1.IntegrationExpireBehaviorTypes;
                    var1 = var1.REMOVE_ROLE;
                    var1 = var2.bind(var3)(var1);
                    return var1;
                };
                var17['onPress'] = var22;
                var24 = _closure1_slot12;
                var22 = var14[var10];
                var22 = var18.bind(var4)(var22);
                var22 = var22.FormRow;
                var23 = var22.Radio;
                var22 = {};
                var28 = var27.expire_behavior;
                var26 = 24;
                var25 = var14[var26];
                var25 = var18.bind(var4)(var25);
                var25 = var25.IntegrationExpireBehaviorTypes;
                var25 = var25.REMOVE_ROLE;
                var25 = var28 === var25;
                var22['selected'] = var25;
                var22 = var24.bind(var4)(var23, var22);
                var17['leading'] = var22;
                var20 = var21.bind(var4)(var20, var17);
                var17 = new Array(3);
                var17[0] = var20;
                var20 = _closure1_slot19;
                var17[1] = var20;
                var22 = _closure1_slot12;
                var20 = var14[var10];
                var20 = var18.bind(var4)(var20);
                var21 = var20.FormRow;
                var20 = {};
                var23 = var14[var19];
                var23 = var18.bind(var4)(var23);
                var25 = var23.intl;
                var24 = var25.string;
                var23 = var14[var19];
                var23 = var18.bind(var4)(var23);
                var23 = var23.t;
                var23 = var23.fQUQIJ;
                var23 = var24.bind(var25)(var23);
                var20['label'] = var23;
                var23 = function onPress() {
                    var3 = _closure3_slot0;
                    var2 = var3.handleExpireBehaviorChange;
                    var5 = _closure1_slot0;
                    var4 = _closure1_slot2;
                    var1 = 24;
                    var4 = var4[var1];
                    var1 = undefined;
                    var1 = var5.bind(var1)(var4);
                    var1 = var1.IntegrationExpireBehaviorTypes;
                    var1 = var1.KICK;
                    var1 = var2.bind(var3)(var1);
                    return var1;
                };
                var20['onPress'] = var23;
                var25 = _closure1_slot12;
                var23 = var14[var10];
                var23 = var18.bind(var4)(var23);
                var23 = var23.FormRow;
                var24 = var23.Radio;
                var23 = {};
                var27 = var27.expire_behavior;
                var26 = var14[var26];
                var26 = var18.bind(var4)(var26);
                var26 = var26.IntegrationExpireBehaviorTypes;
                var26 = var26.KICK;
                var26 = var27 === var26;
                var23['selected'] = var26;
                var23 = var25.bind(var4)(var24, var23);
                var20['leading'] = var23;
                var20 = var22.bind(var4)(var21, var20);
                var17[2] = var20;
                var11['children'] = var17;
                var11 = var16.bind(var4)(var12, var11);
                var8[2] = var11;
                var12 = _closure1_slot12;
                var10 = var14[var10];
                var10 = var18.bind(var4)(var10);
                var11 = var10.FormSection;
                var10 = {};
                var16 = var14[var19];
                var16 = var18.bind(var4)(var16);
                var17 = var16.intl;
                var16 = var17.string;
                var14 = var14[var19];
                var14 = var18.bind(var4)(var14);
                var14 = var14.t;
                var14 = var14.uiXMow;
                var14 = var16.bind(var17)(var14);
                var10['title'] = var14;
                var14 = var15.map;
                var13 = function(arg1, arg2) {
                    var5 = arg2;
                    var4 = _closure1_slot12;
                    var3 = _closure1_slot23;
                    var2 = {};
                    var6 = _closure3_slot1;
                    var2['integration'] = var6;
                    var6 = arg1;
                    var2['option'] = var6;
                    var6 = _closure3_slot2;
                    var7 = var6.length;
                    var6 = 1;
                    var6 = var7 - var6;
                    var6 = var5 === var6;
                    var2['isLast'] = var6;
                    var1 = _closure3_slot0;
                    var1 = var1.handleExpireGracePeriodChange;
                    var2['onPress'] = var1;
                    var1 = undefined;
                    var1 = var4.bind(var1)(var3, var2, var5);
                    return var1;
                };
                var13 = var14.bind(var15)(var13);
                var10['children'] = var13;
                var10 = var12.bind(var4)(var11, var10);
                var8[3] = var10;
                var8[4] = var9;
                var5['children'] = var8;
                var7 = var3.bind(var4)(var7, var5);
                var5 = new Array(2);
                var5[0] = var7;
                var6 = _closure1_slot20;
                var5[1] = var6;
                var1['children'] = var5;
                var1 = var3.bind(var4)(var2, var1);
                return var1;
            }
        };
        var5['value'] = var1;
        var1 = new Array(1);
        var1[0] = var5;
        var1 = var2.bind(var3)(var4, var1);
        return var1;
    };
    var7 = var4.bind(var1)(var7);
    var _closure1_slot21 = var7;
    var4 = 25;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.ThemeContext;
    var7['contextType'] = var4;
    var4 = 29;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/guild_settings/integrations/native/GuildSettingsModalIntegrationSettings.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function ConnectedGuildSettingsModalIntegrationSettings(arg1) {
        _fun0006: for(var _fun0006_ip = 0; ; ) switch(_fun0006_ip) {
case 0:
            var1 = arg1;
            var3 = var1.integrationId;
            var6 = var1.contentContainerStyle;
            var4 = _closure1_slot0;
            var7 = _closure1_slot2;
            var1 = 26;
            var9 = var7[var1];
            var5 = undefined;
            var12 = var4.bind(var5)(var9);
            var11 = var12.useStateFromStores;
            var9 = _closure1_slot11;
            var10 = new Array(1);
            var10[0] = var9;
            var9 = function() {
                var2 = _closure1_slot11;
                var1 = var2.getProps;
                var1 = var1.bind(var2)();
                return var1;
            };
            var9 = var11.bind(var12)(var10, var9);
            var10 = var9.guild;
            var _closure2_slot0 = var10;
            var12 = var9.integrations;
            var1 = var7[var1];
            var11 = var4.bind(var5)(var1);
            var9 = var11.useStateFromStores;
            var1 = _closure1_slot10;
            var4 = new Array(1);
            var4[0] = var1;
            var1 = function() {
                _fun0007: for(var _fun0007_ip = 0; ; ) switch(_fun0007_ip) {
case 0:
                    var3 = _closure2_slot0;
                    var1 = null;
                    var3 = var1 != var3;
                    var1 = undefined;
                    if(!var3) { _fun0007_ip = 32; continue _fun0007 }
case 33:
                    var4 = _closure1_slot10;
                    var3 = var4.getRolesSnapshot;
                    var2 = _closure2_slot0;
                    var2 = var2.id;
                    var1 = var3.bind(var4)(var2);
case 32:
                    return var1;
                }
            };
            var9 = var9.bind(var11)(var4, var1);
            var4 = _closure1_slot1;
            var1 = 27;
            var1 = var7[var1];
            var1 = var4.bind(var5)(var1);
            var7 = var1.bind(var5)();
            var4 = null;
            var11 = var4 == var12;
            var1 = undefined;
            if(var11) { _fun0006_ip = 34; continue _fun0006 }
case 35:
            var11 = var12.filter;
            var8 = function(arg1) {
                var3 = _closure1_slot0;
                var2 = _closure1_slot2;
                var1 = 28;
                var2 = var2[var1];
                var1 = undefined;
                var1 = var3.bind(var1)(var2);
                var3 = var1.SUPPORTED_SETTINGS_INTEGRATION_PLATFORMS;
                var2 = var3.includes;
                var1 = arg1;
                var1 = var1.type;
                var1 = var2.bind(var3)(var1);
                return var1;
            };
            var1 = var11.bind(var12)(var8);
case 34:
            var11 = var4 == var1;
            var8 = undefined;
            if(var11) { _fun0006_ip = 36; continue _fun0006 }
case 37:
            var8 = var1[var3];
case 36:
            var3 = var4 == var10;
            var1 = null;
            if(var3) { _fun0006_ip = 38; continue _fun0006 }
case 39:
            var3 = var4 == var8;
            var1 = null;
            if(var3) { _fun0006_ip = 38; continue _fun0006 }
case 40:
            var3 = var4 == var9;
            var1 = null;
            if(var3) { _fun0006_ip = 38; continue _fun0006 }
case 41:
            var4 = _closure1_slot12;
            var3 = _closure1_slot21;
            var2 = {};
            var10 = var10.id;
            var2['guildId'] = var10;
            var2['guildRoles'] = var9;
            var2['integration'] = var8;
            var2['theme'] = var7;
            var2['contentContainerStyle'] = var6;
            var1 = var4.bind(var5)(var3, var2);
case 38:
            return var1;
        }
    };
    var3['default'] = var2;
    return var1;
})();