// app/modules/quests/native/BountiesModal/bountiesSwipeUpNuxDevTools.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var4 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var4;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var6 = {};
    var1 = true;
    var6['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var6);
    var1 = 1;
    var4 = var4[var1];
    var1 = undefined;
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/quests/native/BountiesModal/bountiesSwipeUpNuxDevTools.tsx';
    var4 = var5.bind(var6)(var4);
    var4 = 'devtools-force-bounties-swipe-up-nux';
    var3['FORCE_BOUNTIES_SWIPE_UP_NUX_STORAGE_KEY'] = var4;
    var2 = function useForceBountiesSwipeUpNux() {
        var3 = _closure1_slot0;
        var2 = _closure1_slot1;
        var1 = 0;
        var2 = var2[var1];
        var1 = undefined;
        var4 = var3.bind(var1)(var2);
        var3 = var4.useLocalStorageState;
        var2 = 'devtools-force-bounties-swipe-up-nux';
        var1 = false;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var3['useForceBountiesSwipeUpNux'] = var2;
    return var1;
})();