// app/modules/chat_input/native/action_buttons/ChatInputRightActions.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var7 = metroImportDefault;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var7;
    var _closure1_slot2 = var6;
    var1 = global;
    var9 = var1.Object;
    var8 = var9.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var8.bind(var9)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var7.bind(var1)(var4);
    var _closure1_slot3 = var4;
    var4 = 1;
    var7 = var6[var4];
    var4 = metroImportAll;
    var7 = var4.bind(var1)(var7);
    var _closure1_slot4 = var7;
    var4 = 2;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.View;
    var _closure1_slot5 = var4;
    var4 = 3;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var8 = var4.jsx;
    var _closure1_slot6 = var8;
    var4 = var4.jsxs;
    var _closure1_slot7 = var4;
    var4 = 4;
    var4 = var6[var4];
    var9 = var5.bind(var1)(var4);
    var8 = var9.createStyles;
    var4 = function() {
        var1 = {};
        var2 = {'flexDirection': 'row', 'alignItems': 'center'};
        var5 = _closure1_slot1;
        var4 = _closure1_slot2;
        var3 = 5;
        var4 = var4[var3];
        var3 = undefined;
        var3 = var5.bind(var3)(var4);
        var3 = var3.modules;
        var3 = var3.mobile;
        var3 = var3.CHAT_INPUT_ACTION_BUTTON_GAP;
        var2['gap'] = var3;
        var1['container'] = var2;
        return var1;
    };
    var4 = var8.bind(var9)(var4);
    var _closure1_slot8 = var4;
    var4 = var7.forwardRef;
    var2 = function(arg1, arg2) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var2 = arg1;
            var12 = var2.channel;
            var15 = var2.keyboardType;
            var8 = var2.shouldShowGiftButton;
            var11 = var2.onPressAction;
            var13 = var2.onPressExpression;
            var2 = _closure1_slot8;
            var4 = undefined;
            var5 = var2.bind(var4)();
            var9 = _closure1_slot4;
            var3 = var9.useState;
            var2 = true;
            var6 = var3.bind(var9)(var2);
            var3 = _closure1_slot3;
            var2 = 2;
            var3 = var3.bind(var4)(var6, var2);
            var2 = 0;
            var10 = var3[var2];
            var2 = 1;
            var2 = var3[var2];
            var _closure2_slot0 = var2;
            var6 = var9.useImperativeHandle;
            var3 = arg2;
            var2 = function() {
                var1 = {};
                var3 = function onDismissActions() {
                    var3 = _closure2_slot0;
                    var2 = undefined;
                    var1 = false;
                    var1 = var3.bind(var2)(var1);
                    return var1;
                };
                var1['onDismissActions'] = var3;
                var2 = function onShowActions() {
                    var3 = _closure2_slot0;
                    var2 = undefined;
                    var1 = true;
                    var1 = var3.bind(var2)(var1);
                    return var1;
                };
                var1['onShowActions'] = var2;
                return var1;
            };
            var1 = new Array(0);
            var1 = var6.bind(var9)(var3, var2, var1);
            var3 = _closure1_slot7;
            var2 = _closure1_slot5;
            var1 = {};
            var5 = var5.container;
            var1['style'] = var5;
            var9 = _closure1_slot6;
            var6 = _closure1_slot1;
            var17 = _closure1_slot2;
            var5 = 6;
            var5 = var17[var5];
            var6 = var6.bind(var4)(var5);
            var5 = {};
            var16 = _closure1_slot0;
            var14 = 7;
            var14 = var17[var14];
            var14 = var16.bind(var4)(var14);
            var14 = var14.KeyboardTypes;
            var14 = var14.EXPRESSION;
            var14 = var15 === var14;
            var5['active'] = var14;
            var5['onPress'] = var13;
            var6 = var9.bind(var4)(var6, var5);
            var5 = new Array(2);
            var5[0] = var6;
            var6 = null;
            if(!var10) { _fun0001_ip = 2; continue _fun0001 }
case 3:
            var6 = null;
            if(!var8) { _fun0001_ip = 2; continue _fun0001 }
case 4:
            var9 = _closure1_slot6;
            var8 = _closure1_slot1;
            var10 = _closure1_slot2;
            var7 = 8;
            var7 = var10[var7];
            var8 = var8.bind(var4)(var7);
            var7 = {};
            var10 = false;
            var7['canStartThreads'] = var10;
            var7['channel'] = var12;
            var7['onPress'] = var11;
            var7['styleButton'] = var4;
            var7['shouldShowThread'] = var10;
            var6 = var9.bind(var4)(var8, var7);
case 2:
            var5[1] = var6;
            var1['children'] = var5;
            var1 = var3.bind(var4)(var2, var1);
            return var1;
        }
    };
    var4 = var4.bind(var7)(var2);
    var2 = 'ChatInputRightActions';
    var4['displayName'] = var2;
    var2 = var7.memo;
    var2 = var2.bind(var7)(var4);
    var4 = 9;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/chat_input/native/action_buttons/ChatInputRightActions.tsx';
    var4 = var5.bind(var6)(var4);
    var3['default'] = var2;
    return var1;
})();