// app/modules/guild_onboarding_home/native/OnboardingHomeResourcesSheet.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var1 = metroImportDefault;
    var _closure1_slot1 = var1;
    var _closure1_slot2 = var6;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var7 = var6[var1];
    var4 = metroImportAll;
    var1 = undefined;
    var4 = var4.bind(var1)(var7);
    var4 = 1;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.ONBOARDING_HOME_RESOURCES_SHEET_KEY;
    var _closure1_slot3 = var4;
    var4 = 2;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.TABLE_ROW_ICON_SIZE;
    var _closure1_slot4 = var4;
    var4 = 3;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.jsx;
    var _closure1_slot5 = var4;
    var4 = 11;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/guild_onboarding_home/native/OnboardingHomeResourcesSheet.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function OnboardingHomeResourcesSheet(arg1) {
        var1 = arg1;
        var3 = var1.guildId;
        var _closure2_slot0 = var3;
        var5 = _closure1_slot1;
        var8 = _closure1_slot2;
        var2 = 4;
        var2 = var8[var2];
        var4 = undefined;
        var2 = var5.bind(var4)(var2);
        var9 = var2.bind(var4)(var3);
        var3 = _closure1_slot5;
        var6 = _closure1_slot0;
        var1 = 7;
        var1 = var8[var1];
        var1 = var6.bind(var4)(var1);
        var2 = var1.ActionSheet;
        var1 = {};
        var5 = 8;
        var5 = var8[var5];
        var5 = var6.bind(var4)(var5);
        var5 = var5.ActionSheetRow;
        var6 = var5.Group;
        var5 = {};
        var8 = var9.map;
        var7 = function(arg1) {
            _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
 0:
                var1 = arg1;
                var _closure3_slot0 = var1;
                var3 = _closure1_slot1;
                var4 = _closure1_slot2;
                var2 = 9;
                var2 = var4[var2];
                var5 = undefined;
                var3 = var3.bind(var5)(var2);
                var2 = var3.getResourceChannelIconURL;
                var2 = var2.bind(var3)(var1);
                var7 = null;
                var3 = var7 != var2;
                var12 = undefined;
                if(!var3) { _fun0001_ip = 59; continue _fun0001 }
 56:
                var12 = var2;
 59:
                var4 = _closure1_slot5;
                var3 = _closure1_slot0;
                var8 = _closure1_slot2;
                var2 = 8;
                var2 = var8[var2];
                var2 = var3.bind(var5)(var2);
                var3 = var2.ActionSheetRow;
                var2 = {};
                var8 = var1.title;
                var2['label'] = var8;
                var8 = var7 != var12;
                var7 = undefined;
                if(!var8) { _fun0001_ip = 169; continue _fun0001 }
 109:
                var10 = _closure1_slot5;
                var9 = _closure1_slot1;
                var11 = _closure1_slot2;
                var8 = 10;
                var8 = var11[var8];
                var9 = var9.bind(var5)(var8);
                var8 = {};
                var11 = {};
                var13 = _closure1_slot4;
                var11['width'] = var13;
                var11['height'] = var13;
                var8['style'] = var11;
                var11 = {};
                var11['uri'] = var12;
                var8['source'] = var11;
                var7 = var10.bind(var5)(var9, var8);
 169:
                var2['icon'] = var7;
                var6 = function onPress() {
                    var1 = _closure3_slot0;
                    var7 = var1.channelId;
                    var3 = _closure1_slot0;
                    var5 = _closure1_slot2;
                    var2 = 5;
                    var2 = var5[var2];
                    var4 = undefined;
                    var6 = var3.bind(var4)(var2);
                    var3 = var6.selectHomeResourceChannel;
                    var2 = _closure2_slot0;
                    var2 = var3.bind(var6)(var2, var7);
                    var3 = _closure1_slot1;
                    var2 = 6;
                    var2 = var5[var2];
                    var3 = var3.bind(var4)(var2);
                    var2 = var3.hideActionSheet;
                    var1 = _closure1_slot3;
                    var1 = var2.bind(var3)(var1);
                    var1 = undefined;
                    return var1;
                };
                var2['onPress'] = var6;
                var6 = true;
                var2['arrow'] = var6;
                var1 = var1.channelId;
                var1 = var4.bind(var5)(var3, var2, var1);
                return var1;
            }
        };
        var7 = var8.bind(var9)(var7);
        var5['children'] = var7;
        var5 = var3.bind(var4)(var6, var5);
        var1['children'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var3['default'] = var2;
    return var1;
})();