// app/modules/slayer_storefront/native/SocialLayerStorefrontGiftPurchaseSection.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var7 = metroImportDefault;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var7;
    var _closure1_slot2 = var6;
    var1 = function SocialLayerStorefrontGiftPurchaseSection(arg1) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var2 = arg1;
            var8 = var2.skuId;
            var _closure2_slot0 = var8;
            var7 = var2.sku;
            var12 = var2.isPurchaseDisabled;
            var1 = var2.giftOptions;
            var _closure2_slot1 = var1;
            var2 = var2.giftingOrigin;
            var _closure2_slot2 = var2;
            var4 = undefined;
            var _closure2_slot3 = var4;
            var _closure2_slot4 = var4;
            var3 = _closure1_slot1;
            var10 = _closure1_slot2;
            var2 = 7;
            var2 = var10[var2];
            var2 = var3.bind(var4)(var2);
            var2 = var2.bind(var4)();
            var2 = var2.insets;
            var3 = _closure1_slot10;
            var2 = var2.bottom;
            var5 = var3.bind(var4)(var2);
            var3 = _closure1_slot0;
            var2 = 8;
            var2 = var10[var2];
            var10 = var3.bind(var4)(var2);
            var3 = var10.useGetOrFetchApplication;
            var14 = null;
            var11 = var14 == var7;
            var2 = undefined;
            if(var11) { _fun0001_ip = 2; continue _fun0001 }
case 3:
            var2 = var7.applicationId;
case 2:
            var13 = var3.bind(var10)(var2);
            var10 = _closure1_slot4;
            var3 = var10.useMemo;
            var2 = new Array(1);
            var2[0] = var1;
            var1 = function() {
                var1 = {};
                var2 = true;
                var1['isGift'] = var2;
                var2 = _closure2_slot1;
                var1['options'] = var2;
                return var1;
            };
            var3 = var3.bind(var10)(var1, var2);
            var10 = _closure1_slot4;
            var2 = var10.useState;
            var1 = false;
            var10 = var2.bind(var10)(var1);
            var2 = _closure1_slot3;
            var1 = 2;
            var2 = var2.bind(var4)(var10, var1);
            var1 = 0;
            var11 = var2[var1];
            var1 = 1;
            var1 = var2[var1];
            _closure2_slot3 = var1;
            var2 = _closure1_slot1;
            var17 = _closure1_slot2;
            var1 = 9;
            var1 = var17[var1];
            var2 = var2.bind(var4)(var1);
            var1 = {};
            var1['skuId'] = var8;
            var1['sku'] = var7;
            var1['giftParams'] = var3;
            var3 = function onPurchaseComplete() {
                _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
case 0:
                    var3 = _closure2_slot3;
                    var1 = undefined;
                    var2 = false;
                    var2 = var3.bind(var1)(var2);
                    var2 = _closure2_slot1;
                    var3 = var2.recipient_id;
                    var2 = null;
                    var2 = var2 == var3;
                    if(var2) { _fun0002_ip = 4; continue _fun0002 }
case 5:
                    var6 = _closure2_slot2;
                    var3 = _closure1_slot6;
                    var3 = var3.USER_PROFILE_WISHLIST;
                    var3 = var6 !== var3;
                    if(!var3) { _fun0002_ip = 6; continue _fun0002 }
case 7:
                    var6 = _closure2_slot2;
                    var4 = _closure1_slot6;
                    var4 = var4.DM_CHANNEL_WISHLIST;
                    var3 = var6 !== var4;
case 6:
                    var2 = var3;
case 4:
                    if(var2) { _fun0002_ip = 8; continue _fun0002 }
case 9:
                    var3 = _closure1_slot1;
                    var4 = _closure1_slot2;
                    var2 = 10;
                    var2 = var4[var2];
                    var4 = var3.bind(var1)(var2);
                    var3 = var4.dispatch;
                    var2 = {};
                    var6 = 'WISHLIST_GIFT_SENT';
                    var2['type'] = var6;
                    var6 = _closure2_slot0;
                    var2['skuId'] = var6;
                    var5 = _closure2_slot1;
                    var5 = var5.recipient_id;
                    var2['recipientId'] = var5;
                    var2 = var3.bind(var4)(var2);
case 8:
                    var3 = _closure1_slot1;
                    var4 = _closure1_slot2;
                    var2 = 11;
                    var2 = var4[var2];
                    var5 = var3.bind(var1)(var2);
                    var2 = var5.pop;
                    var2 = var2.bind(var5)();
                    var2 = 12;
                    var2 = var4[var2];
                    var4 = var3.bind(var1)(var2);
                    var3 = var4.openLazy;
                    var2 = {};
                    var5 = function importer() {
                        var3 = _closure1_slot0;
                        var1 = _closure1_slot2;
                        var2 = 14;
                        var2 = var1[var2];
                        var4 = undefined;
                        var3 = var3.bind(var4)(var2);
                        var2 = 13;
                        var2 = var1[var2];
                        var1 = var1.paths;
                        var3 = var3.bind(var4)(var2, var1);
                        var2 = var3.then;
                        var1 = function(arg1) {
                            var2 = arg1;
                            var2 = var2.default;
                            var _closure5_slot0 = var2;
                            var1 = function(arg1) {
                                _fun0003: for(var _fun0003_ip = 0; ; ) switch(_fun0003_ip) {
case 0:
                                    var4 = _closure1_slot8;
                                    var3 = _closure5_slot0;
                                    var2 = {};
                                    var1 = _closure2_slot1;
                                    var1 = var1.gift_style;
                                    var6 = null;
                                    if(!(var6 == var1)) { _fun0003_ip = 10; continue _fun0003 }
case 5:
                                    var5 = _closure1_slot7;
                                    var1 = var5.STANDARD_BOX;
case 10:
                                    var2['giftStyle'] = var1;
                                    var7 = arg1;
                                    var8 = var2;
                                    var1 = copyDataProperties(var8, var7);
                                    var1 = undefined;
                                    var1 = var4.bind(var1)(var3, var2);
                                    return var1;
                                }
                            };
                            return var1;
                        };
                        var1 = var2.bind(var3)(var1);
                        return var1;
                    };
                    var2['importer'] = var5;
                    var2 = var3.bind(var4)(var2);
                    return var1;
                }
            };
            var1['onPurchaseComplete'] = var3;
            var3 = function onPurchaseError() {
                var3 = _closure2_slot3;
                var1 = undefined;
                var2 = false;
                var2 = var3.bind(var1)(var2);
                return var1;
            };
            var1['onPurchaseError'] = var3;
            var3 = function onPurchasePending() {
                var1 = undefined;
                return var1;
            };
            var1['onPurchasePending'] = var3;
            var1 = var2.bind(var4)(var1);
            _closure2_slot4 = var1;
            var16 = _closure1_slot0;
            var1 = 15;
            var2 = var17[var1];
            var2 = var16.bind(var4)(var2);
            var3 = var2.intl;
            var2 = var3.string;
            var1 = var17[var1];
            var1 = var16.bind(var4)(var1);
            var1 = var1.t;
            var1 = var1.ouo4FK;
            var10 = var2.bind(var3)(var1);
            var3 = _closure1_slot9;
            var2 = _closure1_slot5;
            var1 = {};
            var5 = var5.container;
            var1['style'] = var5;
            var8 = _closure1_slot8;
            var5 = 16;
            var5 = var17[var5];
            var5 = var16.bind(var4)(var5);
            var7 = var5.TextWithIOSLinkWorkaround;
            var5 = {};
            var15 = 'text-xs/normal';
            var5['variant'] = var15;
            var15 = 17;
            var15 = var17[var15];
            var17 = var16.bind(var4)(var15);
            var16 = var17.getMobileFinePrintMessageForApplication;
            var14 = var14 != var13;
            var15 = undefined;
            if(!var14) { _fun0001_ip = 11; continue _fun0001 }
case 12:
            var15 = var13;
case 11:
            var14 = {};
            var13 = true;
            var14['shouldAppendDisclaimer'] = var13;
            var13 = {};
            var18 = 'SocialLayerStorefrontGiftPurchaseSection';
            var13['location'] = var18;
            var23 = var17;
            var22 = var15;
            var21 = var10;
            var20 = var14;
            var19 = var13;
            var13 = var23[var16](var22, var21, var20, var19, var18);
            var5['children'] = var13;
            var7 = var8.bind(var4)(var7, var5);
            var5 = new Array(2);
            var5[0] = var7;
            var8 = _closure1_slot8;
            var7 = _closure1_slot0;
            var13 = _closure1_slot2;
            var6 = 18;
            var6 = var13[var6];
            var6 = var7.bind(var4)(var6);
            var7 = var6.Button;
            var6 = {};
            var13 = 'active';
            var6['variant'] = var13;
            var6['disabled'] = var12;
            var6['loading'] = var11;
            var6['text'] = var10;
            var9 = function onPress() {
                var4 = _closure2_slot3;
                var1 = undefined;
                var3 = true;
                var3 = var4.bind(var1)(var3);
                var2 = _closure2_slot4;
                var4 = var2.bind(var1)();
                var3 = var4.catch;
                var2 = function() {
                    var3 = _closure2_slot3;
                    var1 = undefined;
                    var2 = false;
                    var2 = var3.bind(var1)(var2);
                    return var1;
                };
                var2 = var3.bind(var4)(var2);
                return var1;
            };
            var6['onPress'] = var9;
            var6 = var8.bind(var4)(var7, var6);
            var5[1] = var6;
            var1['children'] = var5;
            var1 = var3.bind(var4)(var2, var1);
            return var1;
        }
    };
    var _closure1_slot11 = var1;
    var1 = global;
    var9 = var1.Object;
    var8 = var9.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var8.bind(var9)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var7.bind(var1)(var4);
    var _closure1_slot3 = var4;
    var4 = 1;
    var7 = var6[var4];
    var4 = metroImportAll;
    var4 = var4.bind(var1)(var7);
    var _closure1_slot4 = var4;
    var4 = 2;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.View;
    var _closure1_slot5 = var4;
    var4 = 3;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var7 = var4.GiftingOrigin;
    var _closure1_slot6 = var7;
    var4 = var4.PremiumGiftStyles;
    var _closure1_slot7 = var4;
    var4 = 4;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var7 = var4.jsx;
    var _closure1_slot8 = var7;
    var4 = var4.jsxs;
    var _closure1_slot9 = var4;
    var4 = 5;
    var4 = var6[var4];
    var8 = var5.bind(var1)(var4);
    var7 = var8.createStyles;
    var4 = function(arg1) {
        var1 = {};
        var2 = {};
        var5 = _closure1_slot1;
        var6 = _closure1_slot2;
        var3 = 6;
        var7 = var6[var3];
        var4 = undefined;
        var7 = var5.bind(var4)(var7);
        var7 = var7.spacing;
        var8 = var7.PX_12;
        var7 = arg1;
        var7 = var8 + var7;
        var2['paddingBottom'] = var7;
        var7 = var6[var3];
        var7 = var5.bind(var4)(var7);
        var7 = var7.spacing;
        var7 = var7.PX_12;
        var2['paddingTop'] = var7;
        var7 = var6[var3];
        var7 = var5.bind(var4)(var7);
        var7 = var7.spacing;
        var7 = var7.PX_16;
        var2['paddingHorizontal'] = var7;
        var7 = var6[var3];
        var7 = var5.bind(var4)(var7);
        var7 = var7.spacing;
        var7 = var7.PX_8;
        var2['gap'] = var7;
        var7 = var6[var3];
        var7 = var5.bind(var4)(var7);
        var7 = var7.colors;
        var7 = var7.BACKGROUND_BASE_LOW;
        var2['backgroundColor'] = var7;
        var3 = var6[var3];
        var3 = var5.bind(var4)(var3);
        var3 = var3.shadows;
        var9 = var3.SHADOW_TOP_HIGH;
        var10 = var2;
        var3 = copyDataProperties(var10, var9);
        var1['container'] = var2;
        return var1;
    };
    var4 = var7.bind(var8)(var4);
    var _closure1_slot10 = var4;
    var4 = 20;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/slayer_storefront/native/SocialLayerStorefrontGiftPurchaseSection.tsx';
    var4 = var5.bind(var6)(var4);
    var2 = function SocialLayerStorefrontGiftPurchaseSectionWrapper(arg1) {
        var1 = arg1;
        var12 = var1.skuId;
        var11 = var1.sku;
        var10 = var1.isPurchaseDisabled;
        var9 = var1.giftOptions;
        var8 = var1.giftingOrigin;
        var4 = _closure1_slot8;
        var2 = _closure1_slot0;
        var3 = _closure1_slot2;
        var1 = 19;
        var1 = var3[var1];
        var3 = undefined;
        var1 = var2.bind(var3)(var1);
        var2 = var1.NativePaymentContextProvider;
        var1 = {};
        var6 = new Array(0);
        var1['skuIDs'] = var6;
        var6 = null;
        var1['activeSubscription'] = var6;
        var7 = _closure1_slot8;
        var6 = _closure1_slot11;
        var5 = {};
        var5['skuId'] = var12;
        var5['sku'] = var11;
        var5['isPurchaseDisabled'] = var10;
        var5['giftOptions'] = var9;
        var5['giftingOrigin'] = var8;
        var5 = var7.bind(var3)(var6, var5);
        var1['children'] = var5;
        var1 = var4.bind(var3)(var2, var1);
        return var1;
    };
    var3['default'] = var2;
    return var1;
})();