// app/modules/main_tabs_v2/native/you_bar/YouBarUser.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var12 = metroImportDefault;
    var3 = exports;
    var6 = dependencyMap;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var12;
    var _closure1_slot2 = var6;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var7 = var6[var1];
    var4 = metroImportAll;
    var1 = undefined;
    var7 = var4.bind(var1)(var7);
    var _closure1_slot3 = var7;
    var4 = 1;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.View;
    var _closure1_slot4 = var4;
    var4 = 2;
    var4 = var6[var4];
    var4 = var12.bind(var1)(var4);
    var _closure1_slot5 = var4;
    var4 = 3;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var8 = var4.YOU_BAR_SPRING_CONFIG;
    var _closure1_slot6 = var8;
    var8 = var4.YOU_BAR_LARGE_AVATAR_NAME_MARGIN;
    var _closure1_slot7 = var8;
    var4 = var4.YOU_BAR_SMALL_AVATAR_NAME_MARGIN;
    var _closure1_slot8 = var4;
    var4 = 4;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var8 = var4.jsx;
    var _closure1_slot9 = var8;
    var4 = var4.jsxs;
    var _closure1_slot10 = var4;
    var4 = 5;
    var4 = var6[var4];
    var9 = var5.bind(var1)(var4);
    var8 = var9.createStyles;
    var4 = {};
    var10 = {'flexDirection': 'row', 'alignItems': 'center'};
    var11 = 6;
    var13 = var6[var11];
    var13 = var12.bind(var1)(var13);
    var13 = var13.modules;
    var13 = var13.mobile;
    var13 = var13.YOU_BAR_BORDER_RADIUS;
    var10['borderRadius'] = var13;
    var4['youButton'] = var10;
    var10 = {'flexDirection': 'column', 'justifyContent': 'center', 'height': '100%', 'gap': 1};
    var4['userText'] = var10;
    var10 = {};
    var13 = var6[var11];
    var13 = var12.bind(var1)(var13);
    var13 = var13.colors;
    var13 = var13.BACKGROUND_MOD_MUTED;
    var10['backgroundColor'] = var13;
    var11 = var6[var11];
    var11 = var12.bind(var1)(var11);
    var11 = var11.radii;
    var11 = var11.round;
    var10['borderRadius'] = var11;
    var11 = 16;
    var10['height'] = var11;
    var11 = 80;
    var10['width'] = var11;
    var4['placeholder'] = var10;
    var4 = var8.bind(var9)(var4);
    var _closure1_slot11 = var4;
    var4 = {};
    var8 = 'function YouBarUserTsx1(){const{nameMargin}=this.__closure;return{marginLeft:nameMargin.get()};}';
    var4['code'] = var8;
    var _closure1_slot12 = var4;
    var4 = var7.memo;
    var2 = function YouBarUser(arg1) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
case 0:
            var2 = arg1;
            var5 = var2.isQuestRendered;
            var7 = var2.onAvatarPress;
            var4 = undefined;
            var _closure2_slot1 = var4;
            var2 = _closure1_slot11;
            var12 = var2.bind(var4)();
            var3 = _closure1_slot0;
            var2 = _closure1_slot2;
            var6 = 7;
            var6 = var2[var6];
            var11 = var3.bind(var4)(var6);
            var9 = var11.useStateFromStores;
            var6 = _closure1_slot5;
            var8 = new Array(1);
            var8[0] = var6;
            var6 = function() {
                var2 = _closure1_slot5;
                var1 = var2.getCurrentUser;
                var1 = var1.bind(var2)();
                return var1;
            };
            var17 = var9.bind(var11)(var8, var6);
            var15 = !var5;
            var _closure2_slot0 = var15;
            var11 = 8;
            var2 = var2[var11];
            var5 = var3.bind(var4)(var2);
            var3 = var5.useSharedValue;
            if(var15) { _fun0001_ip = 2; continue _fun0001 }
case 3:
            var2 = _closure1_slot8;
            _fun0001_ip = 4; continue _fun0001;
case 2:
            var2 = _closure1_slot7;
case 4:
            var8 = var3.bind(var5)(var2);
            _closure2_slot1 = var8;
            var6 = _closure1_slot3;
            var5 = var6.useEffect;
            var3 = new Array(2);
            var3[0] = var15;
            var3[1] = var8;
            var2 = function() {
                _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
case 0:
                    var4 = _closure2_slot1;
                    var3 = var4.set;
                    var7 = _closure1_slot0;
                    var6 = _closure1_slot2;
                    var1 = 9;
                    var6 = var6[var1];
                    var1 = undefined;
                    var7 = var7.bind(var1)(var6);
                    var6 = var7.withSpring;
                    var5 = _closure2_slot0;
                    if(var5) { _fun0002_ip = 5; continue _fun0002 }
case 6:
                    var5 = _closure1_slot8;
                    _fun0002_ip = 7; continue _fun0002;
case 5:
                    var5 = _closure1_slot7;
case 7:
                    var2 = _closure1_slot6;
                    var2 = var6.bind(var7)(var5, var2);
                    var2 = var3.bind(var4)(var2);
                    return var1;
                }
            };
            var2 = var5.bind(var6)(var2, var3);
            var5 = _closure1_slot0;
            var3 = _closure1_slot2;
            var2 = var3[var11];
            var5 = var5.bind(var4)(var2);
            var2 = var5.useAnimatedStyle;
            var1 = function S() {
                var1 = {};
                var3 = _closure2_slot1;
                var2 = var3.get;
                var2 = var2.bind(var3)();
                var1['marginLeft'] = var2;
                return var1;
            };
            var6 = {};
            var6['nameMargin'] = var8;
            var1['__closure'] = var6;
            var6 = 12063452832866.0;
            var1['__workletHash'] = var6;
            var6 = _closure1_slot12;
            var1['__initData'] = var6;
            var13 = var2.bind(var5)(var1);
            var2 = _closure1_slot1;
            var1 = 10;
            var1 = var3[var1];
            var2 = var2.bind(var4)(var1);
            var1 = var2.useName;
            var16 = var1.bind(var2)(var17);
            var3 = _closure1_slot10;
            var2 = _closure1_slot4;
            var1 = null;
            if(!(var1 != var17)) { _fun0001_ip = 8; continue _fun0001 }
case 9:
            if(!(var1 != var16)) { _fun0001_ip = 8; continue _fun0001 }
case 10:
            var1 = {};
            var5 = var12.youButton;
            var1['style'] = var5;
            var8 = _closure1_slot9;
            var14 = _closure1_slot1;
            var18 = _closure1_slot2;
            var5 = 12;
            var5 = var18[var5];
            var6 = var14.bind(var4)(var5);
            var5 = {};
            var5['isLargeAvatar'] = var15;
            var5['onPress'] = var7;
            var6 = var8.bind(var4)(var6, var5);
            var5 = new Array(2);
            var5[0] = var6;
            var6 = var18[var11];
            var6 = var14.bind(var4)(var6);
            var7 = var6.View;
            var6 = {};
            var19 = var12.userText;
            var9 = new Array(3);
            var9[0] = var19;
            var9[1] = var13;
            var19 = {};
            var20 = 1;
            var19['flexShrink'] = var20;
            var9[2] = var19;
            var6['style'] = var9;
            var9 = 13;
            var9 = var18[var9];
            var14 = var14.bind(var4)(var9);
            var9 = {};
            var17 = var17.id;
            var9['userId'] = var17;
            var9['username'] = var16;
            var9 = var8.bind(var4)(var14, var9);
            var6['children'] = var9;
            var6 = var8.bind(var4)(var7, var6);
            var5[1] = var6;
            var1['children'] = var5;
            _fun0001_ip = 11; continue _fun0001;
case 8:
            var5 = {};
            var7 = var12.youButton;
            var6 = new Array(1);
            var6[0] = var7;
            var5['style'] = var6;
            var9 = _closure1_slot9;
            var8 = _closure1_slot1;
            var7 = _closure1_slot2;
            var6 = 11;
            var6 = var7[var6];
            var14 = var8.bind(var4)(var6);
            var6 = {};
            var6['isLarge'] = var15;
            var14 = var9.bind(var4)(var14, var6);
            var6 = new Array(2);
            var6[0] = var14;
            var7 = var7[var11];
            var7 = var8.bind(var4)(var7);
            var8 = var7.View;
            var7 = {};
            var14 = var12.userText;
            var11 = new Array(3);
            var11[0] = var14;
            var11[1] = var13;
            var13 = {};
            var14 = 1;
            var13['flexShrink'] = var14;
            var11[2] = var13;
            var7['style'] = var11;
            var11 = _closure1_slot4;
            var10 = {};
            var12 = var12.placeholder;
            var10['style'] = var12;
            var10 = var9.bind(var4)(var11, var10);
            var7['children'] = var10;
            var7 = var9.bind(var4)(var8, var7);
            var6[1] = var7;
            var5['children'] = var6;
            var1 = var5;
case 11:
            var1 = var3.bind(var4)(var2, var1);
            return var1;
        }
    };
    var2 = var4.bind(var7)(var2);
    var4 = 14;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/main_tabs_v2/native/you_bar/YouBarUser.tsx';
    var4 = var5.bind(var6)(var4);
    var3['default'] = var2;
    return var1;
})();