// app/modules/foreground_service/mobile/ForegroundServiceManagerTypes.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var3 = exports;
    var1 = global;
    var5 = var1.Object;
    var4 = var5.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var4.bind(var5)(var3, var1, var2);
    var4 = {};
    var5 = 0;
    var4['HIGH'] = var5;
    var1 = 'HIGH';
    var4[var5] = var1;
    var7 = 1;
    var4['MEDIUM'] = var7;
    var1 = 'MEDIUM';
    var4[var7] = var1;
    var6 = 2;
    var4['LOW'] = var6;
    var1 = 'LOW';
    var4[var6] = var1;
    var2 = {};
    var2['FILE_UPLOAD'] = var5;
    var1 = 'FILE_UPLOAD';
    var2[var5] = var1;
    var2['VOICE_CALL'] = var7;
    var1 = 'VOICE_CALL';
    var2[var7] = var1;
    var2['SCREEN_SHARE'] = var6;
    var1 = 'SCREEN_SHARE';
    var2[var6] = var1;
    var1 = dependencyMap;
    var6 = var1[var5];
    var5 = require;
    var1 = undefined;
    var7 = var5.bind(var1)(var6);
    var6 = var7.fileFinishedImporting;
    var5 = 'modules/foreground_service/mobile/ForegroundServiceManagerTypes.tsx';
    var5 = var6.bind(var7)(var5);
    var3['ServiceNotificationPriority'] = var4;
    var3['ServiceNotificationType'] = var2;
    return var1;
})();