// app/modules/main_tabs_v2/native/settings/screens/appearance/components/SettingsAppearanceActivityCardsItem.tsx
export default (function(argFoo, argBar, argBaz, argCorge, _, argFred, argPlugh) {
    report = argBar;
    zulu = argFred;
    oscar = argPlugh;
    var _closure1_slot0 = report;
    entity = argBaz;
    var _closure1_slot1 = entity;
    var _closure1_slot2 = oscar;
    entity = global;
    options = entity.Object;
    golf = options.defineProperty;
    tango = {};
    entity = true;
    tango['value'] = entity;
    entity = '__esModule';
    entity = golf.bind(options)(zulu, entity, tango);
    entity = 0;
    golf = oscar[entity];
    tango = argCorge;
    entity = undefined;
    tango = tango.bind(entity)(golf);
    tango = 1;
    tango = oscar[tango];
    tango = report.bind(entity)(tango);
    tango = tango.jsx;
    var _closure1_slot3 = tango;
    tango = 5;
    tango = oscar[tango];
    oscar = report.bind(entity)(tango);
    report = oscar.fileFinishedImporting;
    tango = 'modules/main_tabs_v2/native/settings/screens/appearance/components/SettingsAppearanceActivityCardsItem.tsx';
    tango = report.bind(oscar)(tango);
    mike = function(argFoo) { // Original name: ActivityCardsItem
        entity = argFoo;
        oscar = entity.cards;
        entity = entity.animatedStyles;
        var _closure2_slot0 = entity;
        tango = _closure1_slot3;
        mike = _closure1_slot0;
        offset = _closure1_slot2;
        entity = 2;
        entity = offset[entity];
        zulu = undefined;
        entity = mike.bind(zulu)(entity);
        mike = entity.FlashList;
        entity = {};
        golf = {};
        verify = _closure1_slot1;
        options = 3;
        yankee = offset[options];
        yankee = verify.bind(zulu)(yankee);
        yankee = yankee.spacing;
        yankee = yankee.PX_16;
        golf['paddingVertical'] = yankee;
        options = offset[options];
        options = verify.bind(zulu)(options);
        options = options.spacing;
        options = options.PX_16;
        golf['paddingHorizontal'] = options;
        entity['contentContainerStyle'] = golf;
        entity['data'] = oscar;
        oscar = function(argFoo) { // Original name: renderItem
            entity = argFoo;
            golf = entity.item;
            tango = _closure1_slot3;
            mike = _closure1_slot1;
            zulu = _closure1_slot2;
            entity = 4;
            entity = zulu[entity];
            zulu = undefined;
            mike = mike.bind(zulu)(entity);
            entity = {};
            oscar = _closure2_slot0;
            entity['animatedStyles'] = oscar;
            options = entity;
            report = copyDataProperties(options, golf);
            entity = tango.bind(zulu)(mike, entity);
            return entity;
        };
        entity['renderItem'] = oscar;
        report = function(argFoo) { // Original name: keyExtractor
            entity = argFoo;
            entity = entity.title;
            return entity;
        };
        entity['keyExtractor'] = report;
        report = 265;
        entity['estimatedItemSize'] = report;
        report = false;
        entity['showsHorizontalScrollIndicator'] = report;
        report = true;
        entity['horizontal'] = report;
        entity = tango.bind(zulu)(mike, entity);
        return entity;
    };
    zulu['default'] = mike;
    return entity;
})();