// app/design/utils/native/useFocus.native.tsx
export default (function(_, argBar, argBaz, argCor, __, argFre, argPlu) {
    zuuluu = argFre;
    report = argPlu;
    entity = global;
    golfie = entity.Object;
    oscard = golfie.defineProperty;
    tangon = {};
    entity = true;
    tangon['value'] = entity;
    entity = '__esModule';
    entity = oscard.bind(golfie)(zuuluu, entity, tangon);
    entity = 0;
    oscard = report[entity];
    tangon = argBaz;
    entity = undefined;
    tangon = tangon.bind(entity)(oscard);
    var _closure1_slot0 = tangon;
    tangon = 1;
    oscard = report[tangon];
    tangon = argCor;
    tangon = tangon.bind(entity)(oscard);
    var _closure1_slot1 = tangon;
    tangon = 2;
    report = report[tangon];
    tangon = argBar;
    oscard = tangon.bind(entity)(report);
    report = oscard.fileFinishedImporting;
    tangon = 'design/utils/native/useFocus.native.tsx';
    tangon = report.bind(oscard)(tangon);
    michal = function() { // Original name: useFocus
        oscard = _closure1_slot1;
        tangon = oscard.useState;
        michal = false;
        report = tangon.bind(oscard)(michal);
        tangon = _closure1_slot0;
        michal = undefined;
        entity = 2;
        tangon = tangon.bind(michal)(report, entity);
        entity = 0;
        michal = tangon[entity];
        entity = 1;
        entity = tangon[entity];
        var _closure2_slot0 = entity;
        entity = {};
        report = oscard.useMemo;
        tangon = function() {
            entity = {};
            zuuluu = function() { // Original name: onFocus
                zuuluu = _closure2_slot0;
                michal = undefined;
                entity = true;
                entity = zuuluu.bind(michal)(entity);
                return entity;
            };
            entity['onFocus'] = zuuluu;
            michal = function() { // Original name: onBlur
                zuuluu = _closure2_slot0;
                michal = undefined;
                entity = false;
                entity = zuuluu.bind(michal)(entity);
                return entity;
            };
            entity['onBlur'] = michal;
            return entity;
        };
        zuuluu = new Array(0);
        zuuluu = report.bind(oscard)(tangon, zuuluu);
        entity['focusProps'] = zuuluu;
        entity['isFocused'] = michal;
        return entity;
    };
    zuuluu['useFocus'] = michal;
    return entity;
})();