// app/modules/growth/PasswordRecoveryExperiment.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var6 = require;
    var3 = exports;
    var7 = dependencyMap;
    var _closure1_slot0 = var6;
    var _closure1_slot1 = var7;
    var1 = global;
    var8 = var1.Object;
    var5 = var8.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var5.bind(var8)(var3, var1, var4);
    var1 = 0;
    var4 = var7[var1];
    var1 = undefined;
    var9 = var6.bind(var1)(var4);
    var8 = var9.createExperiment;
    var4 = {'kind': 'user', 'id': '2025-08_mobile_password_recovery', 'label': 'Mobile Password Recovery Revamp'};
    var5 = {'showNudgeModal': false, 'hasNewLandingPage': false, 'hasNewErrorState': false};
    var4['defaultConfig'] = var5;
    var5 = {'id': 1, 'label': 'Nudge Modal To Reset Password After 2 Attempts'};
    var10 = {'showNudgeModal': true, 'hasNewLandingPage': false, 'hasNewErrorState': false};
    var5['config'] = var10;
    var10 = new Array(5);
    var10[0] = var5;
    var11 = {'id': 2, 'label': 'Redesigned Landing Page'};
    var5 = 2;
    var12 = {'showNudgeModal': false, 'hasNewLandingPage': true, 'hasNewErrorState': false};
    var11['config'] = var12;
    var10[1] = var11;
    var11 = {'id': 3, 'label': 'Redesigned Error States'};
    var12 = {'showNudgeModal': false, 'hasNewLandingPage': false, 'hasNewErrorState': true};
    var11['config'] = var12;
    var10[2] = var11;
    var11 = {'id': 4, 'label': 'Redesigned Landing Page + Error States'};
    var12 = {'showNudgeModal': false, 'hasNewLandingPage': true, 'hasNewErrorState': true};
    var11['config'] = var12;
    var10[3] = var11;
    var11 = {'id': 5, 'label': 'Has Nudge Modal, Redesigned Landing, and New Error States - TESTING ONLY'};
    var12 = {'showNudgeModal': true, 'hasNewLandingPage': true, 'hasNewErrorState': true};
    var11['config'] = var12;
    var10[4] = var11;
    var4['treatments'] = var10;
    var4 = var8.bind(var9)(var4);
    var _closure1_slot2 = var4;
    var5 = var7[var5];
    var7 = var6.bind(var1)(var5);
    var6 = var7.fileFinishedImporting;
    var5 = 'modules/growth/PasswordRecoveryExperiment.tsx';
    var5 = var6.bind(var7)(var5);
    var3['MobilePasswordRecoveryExperiment'] = var4;
    var4 = function(arg1) {
        var4 = _closure1_slot0;
        var3 = _closure1_slot1;
        var2 = 1;
        var3 = var3[var2];
        var2 = undefined;
        var4 = var4.bind(var2)(var3);
        var3 = var4.useAccessExperiment;
        var2 = _closure1_slot2;
        var1 = arg1;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var3['useMobilePasswordRecoveryExperiment'] = var4;
    var2 = function(arg1) {
        var4 = _closure1_slot0;
        var3 = _closure1_slot1;
        var2 = 1;
        var3 = var3[var2];
        var2 = undefined;
        var4 = var4.bind(var2)(var3);
        var3 = var4.getAccessExperiment;
        var2 = _closure1_slot2;
        var1 = arg1;
        var1 = var3.bind(var4)(var2, var1);
        return var1;
    };
    var3['getMobilePasswordRecoveryExperiment'] = var2;
    return var1;
})();