// app/modules/main_tabs_v2/native/sidebar/details/ChannelDetailsHeaderExperimentV2.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var6 = dependencyMap;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var4 = {};
    var12 = true;
    var4['value'] = var12;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var9 = var5.bind(var1)(var4);
    var8 = var9.createExperiment;
    var7 = {'kind': 'user', 'id': '2025-01_channel_details_header_v2', 'label': 'Channel Details Header v2'};
    var4 = {};
    var10 = false;
    var4['enabled'] = var10;
    var7['defaultConfig'] = var4;
    var11 = {'id': 1, 'label': 'Header with compacted buttons'};
    var4 = 1;
    var10 = {};
    var10['enabled'] = var12;
    var11['config'] = var10;
    var10 = new Array(1);
    var10[0] = var11;
    var7['treatments'] = var10;
    var7 = var8.bind(var9)(var7);
    var _closure1_slot0 = var7;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/main_tabs_v2/native/sidebar/details/ChannelDetailsHeaderExperimentV2.tsx';
    var4 = var5.bind(var6)(var4);
    var4 = function isChannelDetailsHeaderExperimentV2Enabled(arg1) {
        var4 = _closure1_slot0;
        var3 = var4.getCurrentConfig;
        var2 = {};
        var1 = arg1;
        var2['location'] = var1;
        var1 = {};
        var5 = false;
        var1['autoTrackExposure'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        var1 = var1.enabled;
        return var1;
    };
    var3['isChannelDetailsHeaderExperimentV2Enabled'] = var4;
    var2 = function useChannelDetailsHeaderExperimentV2Enabled(arg1) {
        var4 = _closure1_slot0;
        var3 = var4.useExperiment;
        var2 = {};
        var1 = arg1;
        var2['location'] = var1;
        var1 = {};
        var5 = true;
        var1['autoTrackExposure'] = var5;
        var1 = var3.bind(var4)(var2, var1);
        var1 = var1.enabled;
        return var1;
    };
    var3['useChannelDetailsHeaderExperimentV2Enabled'] = var2;
    return var1;
})();