// app/modules/virtual_currency/native/index.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var5 = require;
    var3 = exports;
    var4 = dependencyMap;
    var1 = global;
    var7 = var1.Object;
    var6 = var7.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var6.bind(var7)(var3, var1, var2);
    var1 = 0;
    var2 = var4[var1];
    var1 = undefined;
    var7 = var5.bind(var1)(var2);
    var6 = var7.fileFinishedImporting;
    var2 = 'modules/virtual_currency/native/index.tsx';
    var2 = var6.bind(var7)(var2);
    var2 = 1;
    var2 = var4[var2];
    var2 = var5.bind(var1)(var2);
    var2 = var2.BalanceWidgetPill;
    var3['BalanceWidgetPill'] = var2;
    var2 = 2;
    var2 = var4[var2];
    var2 = var5.bind(var1)(var2);
    var2 = var2.BalanceCounter;
    var3['BalanceCounter'] = var2;
    var2 = 3;
    var4 = var4[var2];
    var2 = metroImportDefault;
    var2 = var2.bind(var1)(var4);
    var3['BalanceWidgetActionSheet'] = var2;
    return var1;
})();