// app/modules/guild_moderation/native/showKickConfirmModal.tsx
export default (function(argFoo, argBar, argBaz, _, __, argFre, argPlu) {
    report = argBar;
    zuuluu = argFre;
    tangon = argPlu;
    var _closure1_slot0 = report;
    entity = argBaz;
    var _closure1_slot1 = entity;
    var _closure1_slot2 = tangon;
    entity = global;
    option = entity.Object;
    golfie = option.defineProperty;
    oscard = {};
    entity = true;
    oscard['value'] = entity;
    entity = '__esModule';
    entity = golfie.bind(option)(zuuluu, entity, oscard);
    entity = 4;
    tangon = tangon[entity];
    entity = undefined;
    oscard = report.bind(entity)(tangon);
    report = oscard.fileFinishedImporting;
    tangon = 'modules/guild_moderation/native/showKickConfirmModal.tsx';
    tangon = report.bind(oscard)(tangon);
    michal = function(argFoo) { // Original name: showKickConfirmModal
        report = _closure1_slot1;
        michal = _closure1_slot2;
        entity = 0;
        tangon = michal[entity];
        entity = undefined;
        oscard = report.bind(entity)(tangon);
        tangon = oscard.hideActionSheet;
        tangon = tangon.bind(oscard)();
        tangon = 1;
        tangon = michal[tangon];
        report = report.bind(entity)(tangon);
        tangon = report.pushLazy;
        oscard = _closure1_slot0;
        zuuluu = 3;
        zuuluu = michal[zuuluu];
        oscard = oscard.bind(entity)(zuuluu);
        zuuluu = 2;
        zuuluu = michal[zuuluu];
        michal = michal.paths;
        zuuluu = oscard.bind(entity)(zuuluu, michal);
        michal = argFoo;
        michal = tangon.bind(report)(zuuluu, michal);
        return entity;
    };
    zuuluu['default'] = michal;
    return entity;
})();