// app/modules/overlay/OverlayV3Experiment.tsx
export default (function(global, require, metroImportDefault, metroImportAll, moduleObject, exports, dependencyMap) {
    var10 = require;
    var3 = exports;
    var11 = dependencyMap;
    var6 = function getOverlayChatConfig(arg1) {
        var3 = _closure1_slot1;
        var2 = var3.getConfig;
        var1 = {};
        var4 = arg1;
        var1['location'] = var4;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var _closure1_slot3 = var6;
    var4 = function getOverlayStreamerModeConfig(arg1) {
        var3 = _closure1_slot2;
        var2 = var3.getConfig;
        var1 = {};
        var4 = arg1;
        var1['location'] = var4;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var _closure1_slot4 = var4;
    var1 = global;
    var8 = var1.Object;
    var7 = var8.defineProperty;
    var5 = {};
    var15 = true;
    var5['value'] = var15;
    var1 = '__esModule';
    var1 = var7.bind(var8)(var3, var1, var5);
    var5 = 0;
    var7 = var11[var5];
    var1 = undefined;
    var9 = var10.bind(var1)(var7);
    var8 = var9.createApexExperiment;
    var7 = {'name': '2026-03-overlay-default-keybind', 'kind': 'user'};
    var12 = {};
    var12['keybindOverride'] = var1;
    var7['defaultConfig'] = var12;
    var12 = {};
    var13 = {};
    var14 = 'ctrl+tab';
    var13['keybindOverride'] = var14;
    var12[1] = var13;
    var13 = {};
    var14 = 'alt+x';
    var13['keybindOverride'] = var14;
    var12[2] = var13;
    var13 = {};
    var14 = 'ctrl+l';
    var13['keybindOverride'] = var14;
    var12[3] = var13;
    var7['variations'] = var12;
    var8 = var8.bind(var9)(var7);
    var _closure1_slot0 = var8;
    var7 = var11[var5];
    var12 = var10.bind(var1)(var7);
    var9 = var12.createApexExperiment;
    var7 = {'name': '2025-11-overlay-chat', 'kind': 'user'};
    var14 = false;
    var13 = {'hasChat': false, 'hasFriendList': false, 'showNowPlayingForDifferentGames': false};
    var7['defaultConfig'] = var13;
    var13 = {};
    var16 = {'hasChat': true, 'hasFriendList': false, 'showNowPlayingForDifferentGames': false};
    var13[1] = var16;
    var16 = {'hasChat': true, 'hasFriendList': true, 'showNowPlayingForDifferentGames': false};
    var13[2] = var16;
    var16 = {'hasChat': true, 'hasFriendList': true, 'showNowPlayingForDifferentGames': true};
    var13[3] = var16;
    var7['variations'] = var13;
    var7 = var9.bind(var12)(var7);
    var _closure1_slot1 = var7;
    var5 = var11[var5];
    var12 = var10.bind(var1)(var5);
    var9 = var12.createApexExperiment;
    var5 = {'name': '2026-04-overlay-streamer-mode', 'kind': 'user'};
    var13 = {};
    var13['enabled'] = var14;
    var5['defaultConfig'] = var13;
    var13 = {};
    var14 = {};
    var14['enabled'] = var15;
    var13[1] = var14;
    var5['variations'] = var13;
    var5 = var9.bind(var12)(var5);
    var _closure1_slot2 = var5;
    var9 = 1;
    var9 = var11[var9];
    var11 = var10.bind(var1)(var9);
    var10 = var11.fileFinishedImporting;
    var9 = 'modules/overlay/OverlayV3Experiment.tsx';
    var9 = var10.bind(var11)(var9);
    var3['OverlayDefaultKeybindOverrideExperiment'] = var8;
    var8 = function getOverlayDefaultKeybind(arg1) {
        var3 = _closure1_slot0;
        var2 = var3.getConfig;
        var1 = {};
        var4 = arg1;
        var1['location'] = var4;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var3['getOverlayDefaultKeybind'] = var8;
    var3['OverlayChatExperiment'] = var7;
    var3['getOverlayChatConfig'] = var6;
    var6 = function useOverlayChat(arg1) {
        var3 = _closure1_slot1;
        var2 = var3.useConfig;
        var1 = {};
        var4 = arg1;
        var1['location'] = var4;
        var1 = var2.bind(var3)(var1);
        return var1;
    };
    var3['useOverlayChat'] = var6;
    var3['OverlayStreamerModeExperiment'] = var5;
    var3['getOverlayStreamerModeConfig'] = var4;
    var4 = function useOverlayStreamerMode(arg1) {
        var3 = _closure1_slot2;
        var2 = var3.useConfig;
        var1 = {};
        var4 = arg1;
        var1['location'] = var4;
        var1 = var2.bind(var3)(var1);
        var1 = var1.enabled;
        return var1;
    };
    var3['useOverlayStreamerMode'] = var4;
    var2 = function trackOverlayInitializedExperiments() {
        var4 = _closure1_slot3;
        var1 = undefined;
        var3 = 'OVERLAY_INITIALIZED';
        var4 = var4.bind(var1)(var3);
        var2 = _closure1_slot4;
        var2 = var2.bind(var1)(var3);
        return var1;
    };
    var3['trackOverlayInitializedExperiments'] = var2;
    return var1;
})();