name: update

on:
  workflow_dispatch:
  schedule:
    - cron: "20 6 * * *" # this is right after Discord pushes a new alpha

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          path: main
      - uses: actions/checkout@v4
        with:
          ref: data
          path: data

      - uses: oven-sh/setup-bun@v1

      - working-directory: main
        run: bun install

      - name: Check for version
        id: versioner
        working-directory: main
        run: echo "version=$(bun run check)" >> $GITHUB_OUTPUT

      - name: Update
        if: steps.versioner.outcome.version != 'false'
        env:
          code_webhook: ${{ secrets.CODE_WEBHOOK }}
          color_webhook: ${{ secrets.COLOR_WEBHOOK }}
          icons_webhook: ${{ secrets.ICONS_WEBHOOK }}
        working-directory: main
        run: bun run update

      - name: Publish changes
        working-directory: data
        run: |
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "chore: update for version ${{ steps.versioner.outputs.version }}" || true
          git push
