// app/modules/calls/getParticipantUserKey.tsx
export default (function(native1, native2, native3, native4, native5, native6, native7) {
    var3 = native6;
    var1 = global;
    var5 = var1.Object;
    var4 = var5.defineProperty;
    var2 = {};
    var1 = true;
    var2['value'] = var1;
    var1 = '__esModule';
    var1 = var4.bind(var5)(var3, var1, var2);
    var2 = native7;
    var1 = 0;
    var4 = var2[var1];
    var2 = native2;
    var1 = undefined;
    var5 = var2.bind(var1)(var4);
    var4 = var5.fileFinishedImporting;
    var2 = 'modules/calls/getParticipantUserKey.tsx';
    var2 = var4.bind(var5)(var2);
    var2 = function getParticipantUserKey(arg1, arg2) {
        var2 = arg1;
        var1 = var2.toLowerCase;
        var4 = var1.bind(var2)();
        var3 = var4.padEnd;
        var2 = 32;
        var1 = '!';
        var4 = var3.bind(var4)(var2, var1);
        var1 = arg2;
        var3 = var1.id;
        var1 = global;
        var1 = var1.HermesInternal;
        var2 = var1.concat;
        var1 = '';
        var1 = var2.bind(var1)(var4, var3);
        return var1;
    };
    var3['default'] = var2;
    return var1;
})();