// app/modules/gplay/native/GPlayAnalyticsStore.tsx
export default (function(argFoo, argBar, _, __, ___, argFre, argPlu) {
    oscard = argBar;
    zuuluu = argFre;
    golfie = argPlu;
    var _closure1_slot0 = oscard;
    var _closure1_slot1 = golfie;
    entity = global;
    verify = entity.Object;
    option = verify.defineProperty;
    report = {};
    michal = true;
    report['value'] = michal;
    michal = '__esModule';
    michal = option.bind(verify)(zuuluu, michal, report);
    report = entity.Object;
    michal = report.freeze;
    entity = {};
    option = {};
    entity['analyticsByProductId'] = option;
    entity = michal.bind(report)(entity);
    var _closure1_slot2 = entity;
    entity = 0;
    michal = golfie[entity];
    entity = undefined;
    option = oscard.bind(entity)(michal);
    report = option.create;
    michal = function() {
        entity = _closure1_slot2;
        return entity;
    };
    michal = report.bind(option)(michal);
    var _closure1_slot3 = michal;
    report = 2;
    report = golfie[report];
    golfie = oscard.bind(entity)(report);
    oscard = golfie.fileFinishedImporting;
    report = 'modules/gplay/native/GPlayAnalyticsStore.tsx';
    report = oscard.bind(golfie)(report);
    report = function(argFoo, argBar) {
        entity = argFoo;
        var _closure2_slot0 = entity;
        entity = argBar;
        var _closure2_slot1 = entity;
        tangon = _closure1_slot0;
        zuuluu = _closure1_slot1;
        entity = 1;
        zuuluu = zuuluu[entity];
        entity = undefined;
        tangon = tangon.bind(entity)(zuuluu);
        zuuluu = tangon.batchUpdates;
        michal = function() {
            zuuluu = _closure1_slot3;
            michal = zuuluu.setState;
            entity = function(argFoo) {
                entity = {};
                michal = {};
                zuuluu = argFoo;
                report = zuuluu.analyticsByProductId;
                oscard = michal;
                zuuluu = copyDataProperties(oscard, report);
                tangon = _closure2_slot0;
                zuuluu = _closure2_slot1;
                michal[tangon] = zuuluu;
                entity['analyticsByProductId'] = michal;
                return entity;
            };
            entity = michal.bind(zuuluu)(entity);
            entity = undefined;
            return entity;
        };
        michal = zuuluu.bind(tangon)(michal);
        return entity;
    };
    zuuluu['setGPlayAnalytics'] = report;
    tangon = function(argFoo) {
        entity = argFoo;
        var _closure2_slot0 = entity;
        tangon = _closure1_slot0;
        zuuluu = _closure1_slot1;
        entity = 1;
        zuuluu = zuuluu[entity];
        entity = undefined;
        tangon = tangon.bind(entity)(zuuluu);
        zuuluu = tangon.batchUpdates;
        michal = function() {
            zuuluu = _closure1_slot3;
            michal = zuuluu.setState;
            entity = function(argFoo) {
                michal = {};
                entity = argFoo;
                zuuluu = entity.analyticsByProductId;
                tangon = michal;
                entity = copyDataProperties(tangon, zuuluu);
                entity = _closure2_slot0;
                entity = delete michal[entity];
                entity = {};
                entity['analyticsByProductId'] = michal;
                return entity;
            };
            entity = michal.bind(zuuluu)(entity);
            entity = undefined;
            return entity;
        };
        michal = zuuluu.bind(tangon)(michal);
        return entity;
    };
    zuuluu['deleteGPlayAnalytics'] = tangon;
    zuuluu['useGPlayAnalyticsStore'] = michal;
    return entity;
})();