// app/modules/forums/tracking/Tracking.tsx
export default (function(native1, native2, native3, native4, native5, native6, native7) {
    var5 = native2;
    var7 = native3;
    var3 = native6;
    var6 = native7;
    var _closure1_slot0 = var5;
    var _closure1_slot1 = var7;
    var _closure1_slot2 = var6;
    var1 = global;
    var9 = var1.Object;
    var8 = var9.defineProperty;
    var4 = {};
    var1 = true;
    var4['value'] = var1;
    var1 = '__esModule';
    var1 = var8.bind(var9)(var3, var1, var4);
    var1 = 0;
    var4 = var6[var1];
    var1 = undefined;
    var4 = var7.bind(var1)(var4);
    var _closure1_slot3 = var4;
    var4 = 1;
    var8 = var6[var4];
    var8 = var7.bind(var1)(var8);
    var _closure1_slot4 = var8;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var4 = var4.DraftType;
    var _closure1_slot5 = var4;
    var4 = 2;
    var4 = var6[var4];
    var4 = var7.bind(var1)(var4);
    var _closure1_slot6 = var4;
    var4 = 3;
    var4 = var6[var4];
    var4 = var7.bind(var1)(var4);
    var _closure1_slot7 = var4;
    var4 = 4;
    var4 = var6[var4];
    var4 = var5.bind(var1)(var4);
    var7 = var4.AnalyticEvents;
    var _closure1_slot8 = var7;
    var4 = var4.AnalyticsSections;
    var _closure1_slot9 = var4;
    var4 = 11;
    var4 = var6[var4];
    var6 = var5.bind(var1)(var4);
    var5 = var6.fileFinishedImporting;
    var4 = 'modules/forums/tracking/Tracking.tsx';
    var4 = var5.bind(var6)(var4);
    var4 = function trackForumChannelSeenBatch(arg1) {
        var1 = arg1;
        var10 = var1.guildId;
        var9 = var1.channelId;
        var13 = var1.sessionId;
        var8 = var1.postIds;
        var7 = var1.additionalTimes;
        var3 = _closure1_slot1;
        var12 = _closure1_slot2;
        var1 = 5;
        var2 = var12[var1];
        var1 = undefined;
        var5 = var3.bind(var1)(var2);
        var4 = var5.trackWithMetadata;
        var2 = _closure1_slot8;
        var3 = var2.FORUM_CHANNEL_SEEN_BATCH;
        var2 = {};
        var11 = _closure1_slot0;
        var6 = 6;
        var6 = var12[var6];
        var12 = var11.bind(var1)(var6);
        var11 = var12.collectForumAnalyticsMetadata;
        var6 = {};
        var6['channelId'] = var9;
        var6['sessionId'] = var13;
        var15 = var11.bind(var12)(var6);
        var16 = var2;
        var6 = copyDataProperties(var16, var15);
        var6 = 'guild_id';
        var2[var6] = var10;
        var6 = 'channel_id';
        var2[var6] = var9;
        var6 = 'post_ids';
        var2[var6] = var8;
        var6 = 'additional_seen_time_millis';
        var2[var6] = var7;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackForumChannelSeenBatch'] = var4;
    var4 = function trackForumSearched(arg1) {
        var1 = arg1;
        var9 = var1.guildId;
        var8 = var1.channelId;
        var7 = var1.numSearchResults;
        var3 = _closure1_slot1;
        var11 = _closure1_slot2;
        var1 = 5;
        var2 = var11[var1];
        var1 = undefined;
        var5 = var3.bind(var1)(var2);
        var4 = var5.trackWithMetadata;
        var2 = _closure1_slot8;
        var3 = var2.FORUM_CHANNEL_SEARCHED;
        var2 = {};
        var10 = _closure1_slot0;
        var6 = 6;
        var6 = var11[var6];
        var11 = var10.bind(var1)(var6);
        var10 = var11.collectForumAnalyticsMetadata;
        var6 = {};
        var6['channelId'] = var8;
        var13 = var10.bind(var11)(var6);
        var14 = var2;
        var6 = copyDataProperties(var14, var13);
        var6 = 'guild_id';
        var2[var6] = var9;
        var6 = 'channel_id';
        var2[var6] = var8;
        var6 = 'num_search_results';
        var2[var6] = var7;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackForumSearched'] = var4;
    var4 = function trackForumSearchCleared(arg1) {
        var1 = arg1;
        var8 = var1.guildId;
        var7 = var1.channelId;
        var3 = _closure1_slot1;
        var10 = _closure1_slot2;
        var1 = 5;
        var2 = var10[var1];
        var1 = undefined;
        var5 = var3.bind(var1)(var2);
        var4 = var5.trackWithMetadata;
        var2 = _closure1_slot8;
        var3 = var2.FORUM_CHANNEL_SEARCH_CLEARED;
        var2 = {};
        var9 = _closure1_slot0;
        var6 = 6;
        var6 = var10[var6];
        var10 = var9.bind(var1)(var6);
        var9 = var10.collectForumAnalyticsMetadata;
        var6 = {};
        var6['channelId'] = var7;
        var12 = var9.bind(var10)(var6);
        var13 = var2;
        var6 = copyDataProperties(var13, var12);
        var6 = 'guild_id';
        var2[var6] = var8;
        var6 = 'channel_id';
        var2[var6] = var7;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackForumSearchCleared'] = var4;
    var4 = function trackForumTagFilterClicked(arg1) {
        var1 = arg1;
        var12 = var1.guildId;
        var11 = var1.channelId;
        var10 = var1.tagId;
        var9 = var1.filterTagIds;
        var8 = var1.added;
        var7 = var1.location;
        var3 = _closure1_slot1;
        var14 = _closure1_slot2;
        var1 = 5;
        var2 = var14[var1];
        var1 = undefined;
        var5 = var3.bind(var1)(var2);
        var4 = var5.trackWithMetadata;
        var2 = _closure1_slot8;
        var3 = var2.FORUM_CHANNEL_TAG_FILTER_CLICKED;
        var2 = {};
        var13 = _closure1_slot0;
        var6 = 6;
        var6 = var14[var6];
        var14 = var13.bind(var1)(var6);
        var13 = var14.collectForumAnalyticsMetadata;
        var6 = {};
        var6['channelId'] = var11;
        var16 = var13.bind(var14)(var6);
        var17 = var2;
        var6 = copyDataProperties(var17, var16);
        var6 = 'guild_id';
        var2[var6] = var12;
        var6 = 'channel_id';
        var2[var6] = var11;
        var6 = 'tag_id';
        var2[var6] = var10;
        var6 = 'filter_tag_ids';
        var2[var6] = var9;
        var6 = 'added';
        var2[var6] = var8;
        var6 = 'location';
        var2[var6] = var7;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackForumTagFilterClicked'] = var4;
    var4 = function trackForumCreateNewPostClick(arg1) {
        var1 = arg1;
        var8 = var1.guildId;
        var7 = var1.channelId;
        var3 = _closure1_slot1;
        var10 = _closure1_slot2;
        var1 = 5;
        var2 = var10[var1];
        var1 = undefined;
        var5 = var3.bind(var1)(var2);
        var4 = var5.trackWithMetadata;
        var2 = _closure1_slot8;
        var3 = var2.FORUM_CHANNEL_CREATE_NEW_POST_CLICKED;
        var2 = {};
        var9 = _closure1_slot0;
        var6 = 6;
        var6 = var10[var6];
        var10 = var9.bind(var1)(var6);
        var9 = var10.collectForumAnalyticsMetadata;
        var6 = {};
        var6['channelId'] = var7;
        var12 = var9.bind(var10)(var6);
        var13 = var2;
        var6 = copyDataProperties(var13, var12);
        var6 = 'guild_id';
        var2[var6] = var8;
        var6 = 'channel_id';
        var2[var6] = var7;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackForumCreateNewPostClick'] = var4;
    var4 = function trackForumCreateNewPostKeybindUsed(arg1) {
        var1 = arg1;
        var8 = var1.guildId;
        var7 = var1.channelId;
        var3 = _closure1_slot1;
        var10 = _closure1_slot2;
        var1 = 5;
        var2 = var10[var1];
        var1 = undefined;
        var5 = var3.bind(var1)(var2);
        var4 = var5.trackWithMetadata;
        var2 = _closure1_slot8;
        var3 = var2.FORUM_CHANNEL_CREATE_NEW_POST_KEYBIND_USED;
        var2 = {};
        var9 = _closure1_slot0;
        var6 = 6;
        var6 = var10[var6];
        var10 = var9.bind(var1)(var6);
        var9 = var10.collectForumAnalyticsMetadata;
        var6 = {};
        var6['channelId'] = var7;
        var12 = var9.bind(var10)(var6);
        var13 = var2;
        var6 = copyDataProperties(var13, var12);
        var6 = 'guild_id';
        var2[var6] = var8;
        var6 = 'channel_id';
        var2[var6] = var7;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackForumCreateNewPostKeybindUsed'] = var4;
    var4 = function maybeTrackForumNewPostDraftCreated(arg1) {
        _fun0001: for(var _fun0001_ip = 0; ; ) switch(_fun0001_ip) {
 0:
            var1 = arg1;
            var11 = var1.guildId;
            var7 = var1.channelId;
            var2 = _closure1_slot3;
            var1 = var2.getChannel;
            var1 = var1.bind(var2)(var7);
            var9 = null;
            if(!(var9 != var1)) { _fun0001_ip = 462; continue _fun0001 }
 39:
            var3 = _closure1_slot4;
            var2 = var3.getThreadSettings;
            var4 = var2.bind(var3)(var7);
            var2 = var1.template;
            var1 = var9 == var2;
            var8 = undefined;
            var3 = undefined;
            if(var1) { _fun0001_ip = 81; continue _fun0001 }
 71:
            var1 = var2.trim;
            var3 = var1.bind(var2)();
 81:
            var6 = _closure1_slot4;
            var2 = var6.getDraft;
            var1 = _closure1_slot5;
            var1 = var1.FirstThreadMessage;
            var10 = var2.bind(var6)(var7, var1);
            var1 = var9 == var10;
            if(var1) { _fun0001_ip = 125; continue _fun0001 }
 114:
            var6 = var10.length;
            var2 = 0;
            var1 = var2 === var6;
 125:
            if(var1) { _fun0001_ip = 151; continue _fun0001 }
 128:
            var6 = var9 == var10;
            var2 = undefined;
            if(var6) { _fun0001_ip = 147; continue _fun0001 }
 137:
            var6 = var10.trim;
            var2 = var6.bind(var10)();
 147:
            var1 = var2 === var3;
 151:
            var3 = var9 == var4;
            var2 = undefined;
            if(var3) { _fun0001_ip = 166; continue _fun0001 }
 160:
            var2 = var4.appliedTags;
 166:
            var3 = var9 == var2;
            if(var3) { _fun0001_ip = 208; continue _fun0001 }
 173:
            var2 = var9 == var4;
            var6 = undefined;
            if(var2) { _fun0001_ip = 202; continue _fun0001 }
 182:
            var2 = var4.appliedTags;
            var10 = var9 == var2;
            var6 = undefined;
            if(var10) { _fun0001_ip = 202; continue _fun0001 }
 197:
            var6 = var2.size;
 202:
            var2 = 0;
            var3 = var2 === var6;
 208:
            var6 = var9 == var4;
            var2 = undefined;
            if(var6) { _fun0001_ip = 222; continue _fun0001 }
 217:
            var2 = var4.name;
 222:
            var2 = var9 == var2;
            if(var2) { _fun0001_ip = 282; continue _fun0001 }
 229:
            var10 = var9 == var4;
            var6 = undefined;
            if(var10) { _fun0001_ip = 276; continue _fun0001 }
 238:
            var10 = var4.name;
            var4 = var9 == var10;
            var6 = undefined;
            if(var4) { _fun0001_ip = 276; continue _fun0001 }
 252:
            var4 = var10.trim;
            var4 = var4.bind(var10)();
            var9 = var9 == var4;
            var6 = undefined;
            if(var9) { _fun0001_ip = 276; continue _fun0001 }
 271:
            var6 = var4.length;
 276:
            var4 = 0;
            var2 = var4 === var6;
 282:
            if(!var1) { _fun0001_ip = 288; continue _fun0001 }
 285:
            var1 = var3;
 288:
            if(!var1) { _fun0001_ip = 294; continue _fun0001 }
 291:
            var1 = var2;
 294:
            if(var1) { _fun0001_ip = 462; continue _fun0001 }
 300:
            var2 = _closure1_slot1;
            var9 = _closure1_slot2;
            var1 = 5;
            var1 = var9[var1];
            var4 = var2.bind(var8)(var1);
            var3 = var4.trackWithMetadata;
            var1 = _closure1_slot8;
            var2 = var1.FORUM_CHANNEL_NEW_POST_DRAFT_CREATED;
            var1 = {};
            var6 = _closure1_slot0;
            var5 = 6;
            var10 = var9[var5];
            var13 = var6.bind(var8)(var10);
            var12 = var13.collectForumAnalyticsMetadata;
            var10 = {};
            var10['channelId'] = var7;
            var15 = var12.bind(var13)(var10);
            var16 = var1;
            var10 = copyDataProperties(var16, var15);
            var10 = 'guild_id';
            var1[var10] = var11;
            var10 = 'channel_id';
            var1[var10] = var7;
            var10 = var9[var5];
            var11 = var6.bind(var8)(var10);
            var10 = var11.getForumPostDraftAppliedTagIds;
            var11 = var10.bind(var11)(var7);
            var10 = 'applied_tag_ids';
            var1[var10] = var11;
            var5 = var9[var5];
            var6 = var6.bind(var8)(var5);
            var5 = var6.getForumPostDraftNumAttachments;
            var6 = var5.bind(var6)(var7);
            var5 = 'num_attachments';
            var1[var5] = var6;
            var1 = var3.bind(var4)(var2, var1);
 462:
            var1 = undefined;
            return var1;
        }
    };
    var3['maybeTrackForumNewPostDraftCreated'] = var4;
    var4 = function trackForumNewPostCleared(arg1) {
        var1 = arg1;
        var8 = var1.guildId;
        var7 = var1.channelId;
        var3 = _closure1_slot1;
        var10 = _closure1_slot2;
        var1 = 5;
        var2 = var10[var1];
        var1 = undefined;
        var5 = var3.bind(var1)(var2);
        var4 = var5.trackWithMetadata;
        var2 = _closure1_slot8;
        var3 = var2.FORUM_CHANNEL_NEW_POST_DRAFT_CLEARED;
        var2 = {};
        var9 = _closure1_slot0;
        var6 = 6;
        var6 = var10[var6];
        var10 = var9.bind(var1)(var6);
        var9 = var10.collectForumAnalyticsMetadata;
        var6 = {};
        var6['channelId'] = var7;
        var12 = var9.bind(var10)(var6);
        var13 = var2;
        var6 = copyDataProperties(var13, var12);
        var6 = 'guild_id';
        var2[var6] = var8;
        var6 = 'channel_id';
        var2[var6] = var7;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackForumNewPostCleared'] = var4;
    var4 = function trackForumPostCreated(arg1) {
        _fun0002: for(var _fun0002_ip = 0; ; ) switch(_fun0002_ip) {
 0:
            var2 = arg1;
            var3 = var2.guildId;
            var _closure2_slot0 = var3;
            var3 = var2.channelId;
            var _closure2_slot1 = var3;
            var6 = var2.postId;
            var _closure2_slot2 = var6;
            var4 = function _trackForumPostCreated() {
                var3 = _closure1_slot1;
                var8 = _closure1_slot2;
                var1 = 5;
                var2 = var8[var1];
                var1 = undefined;
                var5 = var3.bind(var1)(var2);
                var4 = var5.trackWithMetadata;
                var2 = _closure1_slot8;
                var3 = var2.FORUM_CHANNEL_POST_CREATED;
                var2 = {};
                var7 = _closure1_slot0;
                var6 = 6;
                var6 = var8[var6];
                var9 = var7.bind(var1)(var6);
                var8 = var9.collectForumPostAnalyticsMetadata;
                var7 = {};
                var10 = _closure2_slot2;
                var7['channelId'] = var10;
                var11 = var8.bind(var9)(var7);
                var12 = var2;
                var7 = copyDataProperties(var12, var11);
                var8 = _closure2_slot0;
                var7 = 'guild_id';
                var2[var7] = var8;
                var7 = _closure2_slot1;
                var6 = 'channel_id';
                var2[var6] = var7;
                var2 = var4.bind(var5)(var3, var2);
                return var1;
            };
            var _closure2_slot3 = var4;
            var5 = _closure1_slot6;
            var3 = var5.isLoading;
            var3 = var3.bind(var5)(var6);
            if(var3) { _fun0002_ip = 71; continue _fun0002 }
 63:
            var3 = undefined;
            var3 = var4.bind(var3)();
            _fun0002_ip = 91; continue _fun0002;
 71:
            var3 = _closure1_slot6;
            var2 = var3.addConditionalChangeListener;
            var1 = function() {
                _fun0003: for(var _fun0003_ip = 0; ; ) switch(_fun0003_ip) {
 0:
                    var4 = _closure1_slot6;
                    var3 = var4.isLoading;
                    var1 = _closure2_slot2;
                    var1 = var3.bind(var4)(var1);
                    var3 = !var1;
                    var1 = !var3;
                    if(!var3) { _fun0003_ip = 46; continue _fun0003 }
 34:
                    var3 = _closure2_slot3;
                    var2 = undefined;
                    var2 = var3.bind(var2)();
                    var1 = false;
 46:
                    return var1;
                }
            };
            var1 = var2.bind(var3)(var1);
 91:
            var1 = undefined;
            return var1;
        }
    };
    var3['trackForumPostCreated'] = var4;
    var4 = function trackForumScrolled(arg1) {
        var1 = arg1;
        var8 = var1.guildId;
        var7 = var1.channelId;
        var3 = _closure1_slot1;
        var10 = _closure1_slot2;
        var1 = 5;
        var2 = var10[var1];
        var1 = undefined;
        var5 = var3.bind(var1)(var2);
        var4 = var5.trackWithMetadata;
        var2 = _closure1_slot8;
        var3 = var2.FORUM_CHANNEL_SCROLLED;
        var2 = {};
        var9 = _closure1_slot0;
        var6 = 6;
        var6 = var10[var6];
        var10 = var9.bind(var1)(var6);
        var9 = var10.collectForumAnalyticsMetadata;
        var6 = {};
        var6['channelId'] = var7;
        var12 = var9.bind(var10)(var6);
        var13 = var2;
        var6 = copyDataProperties(var13, var12);
        var6 = 'guild_id';
        var2[var6] = var8;
        var6 = 'channel_id';
        var2[var6] = var7;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackForumScrolled'] = var4;
    var4 = function trackForumMorePostsLoaded(arg1) {
        var1 = arg1;
        var12 = var1.guildId;
        var11 = var1.channelId;
        var15 = var1.numArchivedThreads;
        var9 = var1.hasMoreThreads;
        var8 = var1.filterTagIds;
        var7 = var1.sortOrder;
        var3 = _closure1_slot1;
        var13 = _closure1_slot2;
        var1 = 7;
        var2 = var13[var1];
        var1 = undefined;
        var5 = var3.bind(var1)(var2);
        var4 = var5.track;
        var2 = _closure1_slot8;
        var3 = var2.FORUM_CHANNEL_MORE_POSTS_LOADED;
        var2 = {};
        var10 = _closure1_slot0;
        var14 = 5;
        var16 = var13[var14];
        var17 = var10.bind(var1)(var16);
        var16 = var17.collectGuildAnalyticsMetadata;
        var19 = var16.bind(var17)(var12);
        var20 = var2;
        var16 = copyDataProperties(var20, var19);
        var14 = var13[var14];
        var16 = var10.bind(var1)(var14);
        var14 = var16.collectChannelAnalyticsMetadata;
        var17 = _closure1_slot3;
        var6 = var17.getChannel;
        var6 = var6.bind(var17)(var11);
        var19 = var14.bind(var16)(var6);
        var20 = var2;
        var6 = copyDataProperties(var20, var19);
        var6 = 6;
        var14 = var13[var6];
        var17 = var10.bind(var1)(var14);
        var16 = var17.collectForumAnalyticsMetadata;
        var14 = {};
        var14['channelId'] = var11;
        var19 = var16.bind(var17)(var14);
        var20 = var2;
        var14 = copyDataProperties(var20, var19);
        var14 = 'guild_id';
        var2[var14] = var12;
        var14 = 'channel_id';
        var2[var14] = var11;
        var14 = 'num_archived_threads';
        var2[var14] = var15;
        var6 = var13[var6];
        var10 = var10.bind(var1)(var6);
        var6 = var10.getNumActiveThreads;
        var10 = var6.bind(var10)(var12, var11);
        var6 = 'num_active_threads';
        var2[var6] = var10;
        var6 = 'has_more_threads';
        var2[var6] = var9;
        var6 = 'filter_tag_ids';
        var2[var6] = var8;
        var6 = 'sort_order';
        var2[var6] = var7;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackForumMorePostsLoaded'] = var4;
    var4 = function trackForumPostClicked(arg1) {
        var1 = arg1;
        var10 = var1.guildId;
        var9 = var1.channelId;
        var13 = var1.postId;
        var7 = var1.location;
        var3 = _closure1_slot1;
        var12 = _closure1_slot2;
        var1 = 5;
        var2 = var12[var1];
        var1 = undefined;
        var5 = var3.bind(var1)(var2);
        var4 = var5.trackWithMetadata;
        var2 = _closure1_slot8;
        var3 = var2.FORUM_CHANNEL_POST_CLICKED;
        var2 = {};
        var11 = _closure1_slot0;
        var8 = 6;
        var8 = var12[var8];
        var12 = var11.bind(var1)(var8);
        var11 = var12.collectForumPostAnalyticsMetadata;
        var8 = {};
        var8['channelId'] = var13;
        var14 = var11.bind(var12)(var8);
        var15 = var2;
        var8 = copyDataProperties(var15, var14);
        var8 = 'guild_id';
        var2[var8] = var10;
        var8 = 'channel_id';
        var2[var8] = var9;
        var8 = _closure1_slot7;
        var6 = var8.getSearchResults;
        var8 = var6.bind(var8)(var9);
        var6 = null;
        var8 = var6 != var8;
        var6 = 'is_search_result';
        var2[var6] = var8;
        var6 = 'location';
        var2[var6] = var7;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackForumPostClicked'] = var4;
    var4 = function trackForumSortOrderUpdated(arg1) {
        var1 = arg1;
        var12 = var1.guildId;
        var11 = var1.channelId;
        var7 = var1.sortOrder;
        var3 = _closure1_slot1;
        var9 = _closure1_slot2;
        var1 = 5;
        var2 = var9[var1];
        var1 = undefined;
        var5 = var3.bind(var1)(var2);
        var4 = var5.trackWithMetadata;
        var2 = _closure1_slot8;
        var3 = var2.FORUM_CHANNEL_POSTS_SORTED;
        var2 = {};
        var8 = _closure1_slot0;
        var6 = 6;
        var10 = var9[var6];
        var14 = var8.bind(var1)(var10);
        var13 = var14.collectForumAnalyticsMetadata;
        var10 = {};
        var10['channelId'] = var11;
        var16 = var13.bind(var14)(var10);
        var17 = var2;
        var10 = copyDataProperties(var17, var16);
        var10 = 'guild_id';
        var2[var10] = var12;
        var10 = 'channel_id';
        var2[var10] = var11;
        var6 = var9[var6];
        var8 = var8.bind(var1)(var6);
        var6 = var8.convertSortOrderToReadableString;
        var8 = var6.bind(var8)(var7);
        var6 = 'sort_type';
        var2[var6] = var8;
        var6 = 'sort_order';
        var2[var6] = var7;
        var6 = 'forum_channel_sort_order';
        var2[var6] = var7;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackForumSortOrderUpdated'] = var4;
    var4 = function trackForumLayoutUpdated(arg1) {
        var1 = arg1;
        var9 = var1.guildId;
        var8 = var1.channelId;
        var7 = var1.forumLayout;
        var3 = _closure1_slot1;
        var11 = _closure1_slot2;
        var1 = 5;
        var2 = var11[var1];
        var1 = undefined;
        var5 = var3.bind(var1)(var2);
        var4 = var5.trackWithMetadata;
        var2 = _closure1_slot8;
        var3 = var2.FORUM_CHANNEL_LAYOUT_UPDATED;
        var2 = {};
        var10 = _closure1_slot0;
        var6 = 6;
        var6 = var11[var6];
        var11 = var10.bind(var1)(var6);
        var10 = var11.collectForumAnalyticsMetadata;
        var6 = {};
        var6['channelId'] = var8;
        var13 = var10.bind(var11)(var6);
        var14 = var2;
        var6 = copyDataProperties(var14, var13);
        var6 = 'guild_id';
        var2[var6] = var9;
        var6 = 'channel_id';
        var2[var6] = var8;
        var6 = 'forum_channel_layout';
        var2[var6] = var7;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackForumLayoutUpdated'] = var4;
    var4 = function trackForumPostLinkCopied(arg1) {
        var1 = arg1;
        var7 = var1.postId;
        var6 = var1.location;
        var4 = _closure1_slot1;
        var3 = _closure1_slot2;
        var1 = 5;
        var3 = var3[var1];
        var1 = undefined;
        var5 = var4.bind(var1)(var3);
        var4 = var5.trackWithMetadata;
        var2 = _closure1_slot8;
        var3 = var2.FORUM_POST_LINK_COPIED;
        var2 = {};
        var2['forum_post_id'] = var7;
        var2['location'] = var6;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackForumPostLinkCopied'] = var4;
    var4 = function trackForumOnboardingClicked(arg1) {
        var1 = arg1;
        var6 = var1.onboardingCTA;
        var4 = _closure1_slot1;
        var3 = _closure1_slot2;
        var1 = 5;
        var3 = var3[var1];
        var1 = undefined;
        var5 = var4.bind(var1)(var3);
        var4 = var5.trackWithMetadata;
        var2 = _closure1_slot8;
        var3 = var2.FORUM_CHANNEL_ONBOARDING_CLICKED;
        var2 = {};
        var2['onboarding_cta_type'] = var6;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackForumOnboardingClicked'] = var4;
    var4 = function trackForumUpsellModalClicked(arg1) {
        var1 = arg1;
        var6 = var1.forumDemoId;
        var4 = _closure1_slot1;
        var3 = _closure1_slot2;
        var1 = 5;
        var3 = var3[var1];
        var1 = undefined;
        var5 = var4.bind(var1)(var3);
        var4 = var5.trackWithMetadata;
        var2 = _closure1_slot8;
        var3 = var2.FORUM_UPSELL_MODAL_CLICKED;
        var2 = {};
        var2['forum_demo_id'] = var6;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackForumUpsellModalClicked'] = var4;
    var4 = function trackForumAddMediaToOriginalPostClicked(arg1) {
        var1 = arg1;
        var6 = var1.added;
        var4 = _closure1_slot1;
        var3 = _closure1_slot2;
        var1 = 5;
        var3 = var3[var1];
        var1 = undefined;
        var5 = var4.bind(var1)(var3);
        var4 = var5.trackWithMetadata;
        var2 = _closure1_slot8;
        var3 = var2.FORUM_ADD_MEDIA_TO_ORIGINAL_POST_CLICKED;
        var2 = {};
        var2['added'] = var6;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackForumAddMediaToOriginalPostClicked'] = var4;
    var4 = function trackForumHelperCardClicked(arg1) {
        var1 = arg1;
        var6 = var1.readGuideCta;
        var4 = _closure1_slot1;
        var3 = _closure1_slot2;
        var1 = 5;
        var3 = var3[var1];
        var1 = undefined;
        var5 = var4.bind(var1)(var3);
        var4 = var5.trackWithMetadata;
        var2 = _closure1_slot8;
        var3 = var2.FORUM_CHANNEL_HELPER_CARD_CLICKED;
        var2 = {};
        var2['read_guide_cta'] = var6;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackForumHelperCardClicked'] = var4;
    var4 = function trackForumChannelMediaUploaderClicked(arg1) {
        var1 = arg1;
        var6 = var1.isMobile;
        var4 = _closure1_slot1;
        var3 = _closure1_slot2;
        var1 = 5;
        var3 = var3[var1];
        var1 = undefined;
        var5 = var4.bind(var1)(var3);
        var4 = var5.trackWithMetadata;
        var2 = _closure1_slot8;
        var3 = var2.FORUM_CHANNEL_MEDIA_UPLOADER_CLICKED;
        var2 = {};
        var2['is_mobile'] = var6;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackForumChannelMediaUploaderClicked'] = var4;
    var4 = function trackForumEnableAutomodClicked() {
        var4 = _closure1_slot1;
        var3 = _closure1_slot2;
        var1 = 5;
        var3 = var3[var1];
        var1 = undefined;
        var4 = var4.bind(var1)(var3);
        var3 = var4.trackWithMetadata;
        var2 = _closure1_slot8;
        var2 = var2.FORUM_CHANNEL_ENABLE_AUTOMOD_CLICKED;
        var2 = var3.bind(var4)(var2);
        return var1;
    };
    var3['trackForumEnableAutomodClicked'] = var4;
    var4 = function trackForumPreviewPostClicked() {
        var4 = _closure1_slot1;
        var3 = _closure1_slot2;
        var1 = 5;
        var3 = var3[var1];
        var1 = undefined;
        var4 = var4.bind(var1)(var3);
        var3 = var4.trackWithMetadata;
        var2 = _closure1_slot8;
        var2 = var2.FORUM_CHANNEL_ENABLE_PREVIEW_CLICKED;
        var2 = var3.bind(var4)(var2);
        return var1;
    };
    var3['trackForumPreviewPostClicked'] = var4;
    var4 = function trackForumPostSidebarViewed(arg1) {
        var6 = arg1;
        var3 = _closure1_slot1;
        var5 = _closure1_slot2;
        var10 = 5;
        var2 = var5[var10];
        var1 = undefined;
        var9 = var3.bind(var1)(var2);
        var8 = var9.trackWithMetadata;
        var2 = _closure1_slot8;
        var7 = var2.CHANNEL_OPENED;
        var3 = {};
        var4 = _closure1_slot0;
        var11 = var5[var10];
        var13 = var4.bind(var1)(var11);
        var12 = var13.collectGuildAnalyticsMetadata;
        var11 = var6.guild_id;
        var14 = var12.bind(var13)(var11);
        var15 = var3;
        var11 = copyDataProperties(var15, var14);
        var11 = var5[var10];
        var12 = var4.bind(var1)(var11);
        var11 = var12.collectChannelAnalyticsMetadata;
        var14 = var11.bind(var12)(var6);
        var15 = var3;
        var11 = copyDataProperties(var15, var14);
        var11 = 8;
        var11 = var5[var11];
        var13 = var4.bind(var1)(var11);
        var12 = var13.collectThreadMetadata;
        var11 = true;
        var14 = var12.bind(var13)(var6, var11);
        var15 = var3;
        var11 = copyDataProperties(var15, var14);
        var10 = var5[var10];
        var12 = var4.bind(var1)(var10);
        var11 = var12.getChannelOpenedMetadata;
        var10 = var6.id;
        var14 = var11.bind(var12)(var10);
        var15 = var3;
        var10 = copyDataProperties(var15, var14);
        var11 = 'Split View';
        var10 = 'channel_view';
        var3[var10] = var11;
        var10 = 9;
        var10 = var5[var10];
        var11 = var4.bind(var1)(var10);
        var10 = var11.getPlatform;
        var11 = var10.bind(var11)();
        var10 = 'platform';
        var3[var10] = var11;
        var3 = var8.bind(var9)(var7, var3);
        var3 = 10;
        var3 = var5[var3];
        var5 = var4.bind(var1)(var3);
        var4 = var5.trackClickstream;
        var3 = var2.CHANNEL_OPENED_CLICKSTREAM;
        var2 = {};
        var6 = var6.id;
        var2['channelId'] = var6;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackForumPostSidebarViewed'] = var4;
    var4 = function trackMobileForumComposerOpened(arg1) {
        var1 = arg1;
        var8 = var1.guildId;
        var7 = var1.channelId;
        var6 = var1.location;
        var4 = _closure1_slot1;
        var3 = _closure1_slot2;
        var1 = 7;
        var3 = var3[var1];
        var1 = undefined;
        var5 = var4.bind(var1)(var3);
        var4 = var5.track;
        var2 = _closure1_slot8;
        var3 = var2.OPEN_MODAL;
        var2 = {};
        var9 = 'Create Forum Post';
        var2['type'] = var9;
        var2['guild_id'] = var8;
        var2['channel_id'] = var7;
        var2['location'] = var6;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackMobileForumComposerOpened'] = var4;
    var4 = function trackMobileForumComposerDismissed() {
        var4 = _closure1_slot1;
        var3 = _closure1_slot2;
        var1 = 7;
        var3 = var3[var1];
        var1 = undefined;
        var5 = var4.bind(var1)(var3);
        var4 = var5.track;
        var2 = _closure1_slot8;
        var3 = var2.MODAL_DISMISSED;
        var2 = {};
        var6 = 'Create Forum Post';
        var2['type'] = var6;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackMobileForumComposerDismissed'] = var4;
    var4 = function trackForumUpsellModalViewed() {
        var3 = _closure1_slot1;
        var2 = _closure1_slot2;
        var1 = 5;
        var2 = var2[var1];
        var1 = undefined;
        var5 = var3.bind(var1)(var2);
        var4 = var5.trackWithMetadata;
        var2 = _closure1_slot8;
        var3 = var2.OPEN_MODAL;
        var2 = {};
        var6 = 'Forum Channel Upsell Modal';
        var2['type'] = var6;
        var6 = {};
        var7 = _closure1_slot9;
        var7 = var7.CHANNEL_WELCOME_CTA;
        var6['section'] = var7;
        var2['location'] = var6;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackForumUpsellModalViewed'] = var4;
    var2 = function trackForumCreateNewPostStarted(arg1) {
        var1 = arg1;
        var7 = var1.guildId;
        var8 = var1.channelId;
        var3 = _closure1_slot1;
        var11 = _closure1_slot2;
        var1 = 5;
        var2 = var11[var1];
        var1 = undefined;
        var5 = var3.bind(var1)(var2);
        var4 = var5.trackWithMetadata;
        var2 = _closure1_slot8;
        var3 = var2.THREAD_CREATION_STARTED;
        var2 = {};
        var10 = _closure1_slot0;
        var9 = 8;
        var9 = var11[var9];
        var10 = var10.bind(var1)(var9);
        var9 = var10.collectThreadMetadata;
        var11 = _closure1_slot3;
        var6 = var11.getChannel;
        var6 = var6.bind(var11)(var8);
        var12 = var9.bind(var10)(var6);
        var13 = var2;
        var6 = copyDataProperties(var13, var12);
        var6 = 'channel_id';
        var2[var6] = var8;
        var6 = 'guild_id';
        var2[var6] = var7;
        var2 = var4.bind(var5)(var3, var2);
        return var1;
    };
    var3['trackForumCreateNewPostStarted'] = var2;
    return var1;
})();