// app/modules/native_menu/native/NativeMenuActionCreators.tsx
export default (function(argFoo, argBar, argBaz, _, __, argFred, argPlugh) {
    report = argBar;
    zulu = argFred;
    tango = argPlugh;
    var _closure1_slot0 = report;
    mike = argBaz;
    var _closure1_slot1 = mike;
    var _closure1_slot2 = tango;
    mike = global;
    options = mike.Object;
    golf = options.defineProperty;
    oscar = {};
    mike = true;
    oscar['value'] = mike;
    mike = '__esModule';
    mike = golf.bind(options)(zulu, mike, oscar);
    mike = {};
    oscar = function(argFoo, argBar) { // Original name: showNativeMenu
        entity = argFoo;
        var _closure2_slot0 = entity;
        entity = argBar;
        var _closure2_slot1 = entity;
        tango = _closure1_slot1;
        zulu = _closure1_slot2;
        entity = 0;
        zulu = zulu[entity];
        entity = undefined;
        tango = tango.bind(entity)(zulu);
        zulu = tango.wait;
        mike = function() {
            report = _closure1_slot0;
            tango = _closure1_slot2;
            entity = 1;
            zulu = tango[entity];
            entity = undefined;
            oscar = report.bind(entity)(zulu);
            report = oscar.triggerHapticFeedback;
            zulu = _closure1_slot1;
            mike = 2;
            mike = tango[mike];
            mike = zulu.bind(entity)(mike);
            mike = mike.IMPACT_LIGHT;
            mike = report.bind(oscar)(mike);
            mike = 0;
            mike = tango[mike];
            tango = zulu.bind(entity)(mike);
            zulu = tango.dispatch;
            mike = {};
            report = 'SHOW_NATIVE_MENU';
            mike['type'] = report;
            oscar = _closure2_slot0;
            mike['key'] = oscar;
            report = _closure2_slot1;
            mike['menu'] = report;
            mike = zulu.bind(tango)(mike);
            return entity;
        };
        mike = zulu.bind(tango)(mike);
        return entity;
    };
    mike['showNativeMenu'] = oscar;
    entity = function(argFoo) { // Original name: hideNativeMenu
        zulu = _closure1_slot1;
        mike = _closure1_slot2;
        entity = 0;
        mike = mike[entity];
        entity = undefined;
        tango = zulu.bind(entity)(mike);
        zulu = tango.dispatch;
        mike = {};
        report = 'HIDE_NATIVE_MENU';
        mike['type'] = report;
        report = argFoo;
        mike['key'] = report;
        mike = zulu.bind(tango)(mike);
        return entity;
    };
    mike['hideNativeMenu'] = entity;
    entity = 3;
    tango = tango[entity];
    entity = undefined;
    oscar = report.bind(entity)(tango);
    report = oscar.fileFinishedImporting;
    tango = 'modules/native_menu/native/NativeMenuActionCreators.tsx';
    tango = report.bind(oscar)(tango);
    zulu['default'] = mike;
    return entity;
})();