// app/modules/premium/sounds/soundmoji/SoundmojiRenderingExperiment.tsx
export default (function(argFoo, argBar, _, __, ___, argFre, argPlu) {
    oscard = argBar;
    zuuluu = argFre;
    golfie = argPlu;
    entity = global;
    option = entity.Object;
    report = option.defineProperty;
    tangon = {};
    yankee = true;
    tangon['value'] = yankee;
    entity = '__esModule';
    entity = report.bind(option)(zuuluu, entity, tangon);
    entity = 0;
    tangon = golfie[entity];
    entity = undefined;
    tangon = oscard.bind(entity)(tangon);
    verify = tangon.CommonTriggerPoints;
    tangon = 1;
    tangon = golfie[tangon];
    option = oscard.bind(entity)(tangon);
    report = option.createExperiment;
    tangon = {'id': '2024-11_soundmoji_rendering', 'label': 'Render soundmojis', 'kind': 'user'};
    offset = {};
    romeon = false;
    offset['enabled'] = romeon;
    tangon['defaultConfig'] = offset;
    verify = verify.CONNECTION_OPEN;
    tangon['commonTriggerPoint'] = verify;
    offset = {'id': 1, 'label': 'Enabled'};
    verify = {};
    verify['enabled'] = yankee;
    offset['config'] = verify;
    verify = new Array(1);
    verify[0] = offset;
    tangon['treatments'] = verify;
    tangon = report.bind(option)(tangon);
    var _closure1_slot0 = tangon;
    report = 2;
    report = golfie[report];
    golfie = oscard.bind(entity)(report);
    oscard = golfie.fileFinishedImporting;
    report = 'modules/premium/sounds/soundmoji/SoundmojiRenderingExperiment.tsx';
    report = oscard.bind(golfie)(report);
    zuuluu['SoundmojiRenderingExperiment'] = tangon;
    tangon = function(argFoo) { // Original name: getSoundmojiRenderingExperiment
        entity = argFoo;
        entity = entity.location;
        tangon = _closure1_slot0;
        zuuluu = tangon.getCurrentConfig;
        michal = {};
        michal['location'] = entity;
        entity = {};
        report = false;
        entity['autoTrackExposure'] = report;
        entity = zuuluu.bind(tangon)(michal, entity);
        entity = entity.enabled;
        return entity;
    };
    zuuluu['getSoundmojiRenderingExperiment'] = tangon;
    michal = function(argFoo) { // Original name: useSoundmojiRenderingExperiment
        entity = argFoo;
        entity = entity.location;
        tangon = _closure1_slot0;
        zuuluu = tangon.useExperiment;
        michal = {};
        michal['location'] = entity;
        entity = {};
        report = false;
        entity['autoTrackExposure'] = report;
        entity = zuuluu.bind(tangon)(michal, entity);
        entity = entity.enabled;
        return entity;
    };
    zuuluu['useSoundmojiRenderingExperiment'] = michal;
    return entity;
})();